### ISSUE TITLE
使用疑问：<你有咩问题>更新到最新版本后，语言只有英语，尴尬了

### ISSUE THREAD

**Issue by fengkai2020** [Qv2ray/Qv2ray#1000]
### 你想做啥？
*简要描述你的最原始的目的。*
例：我在学校，校园网能解锁文献数据库，我想对这些地址直连。

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
例：看完文档，没有相关内容，就过来问一问。

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by fengkai2020** [comment]
最新版只有英语吗？

**Comment by MarksonHon** [comment]
@fengkai2020 <https://t.me/qv2ray>

请加群讨论，因为你是遇到了使用上的问题，而不是发现了软件本身的故障。此 Issue 会被关闭。

**Comment by DuckSoft** [comment]
从什么渠道下载的？什么平台？什么版本？
另外，你似乎没有按照模板填写 Issue。本 Issue 将关闭。
