### ISSUE TITLE
功能请求：优化新复杂配置设置

### ISSUE THREAD

**Issue by jones1088** [Qv2ray/Qv2ray#1003]
希望在现有连接 节点的下拉列表第一项添加为“全部节点”选项，因为节点太多，一个一个添加很麻烦，而且容易混。
希望在均衡器框里的下拉菜单第一项添加“全部节点”选项。

**Comment by cangyin** [comment]
或者 添加一个组内的所有节点

**Comment by U-v-U** [comment]
done, closing.
