### ISSUE TITLE
mac catalina 10.15.7 安装了qv2ray 和trohan插件之后可以连接成功,但是无法科学上网,怎么破?

### ISSUE THREAD

**Issue by LionNeo** [Qv2ray/Qv2ray#1005]
![image](https://user-images.githubusercontent.com/16424323/94894571-38e7a500-04bc-11eb-856a-f26e40be8659.png)
如图片所示,可以连接但是无法上网

**Comment by EpLiar** [comment]
请详细查看文档： qv2ray.net
