### ISSUE TITLE
使用疑问：由于某些众所周知的政策原因

### ISSUE THREAD

**Issue by ps4jpacce** [Qv2ray/Qv2ray#1006]
由于某些众所周知的政策原因，Qv2ray 本身并 不包含 V2Ray 核心可执行文件。

说真的，我没看到上面那段话之前，以为你故意不集成核心文件是防止小白多导致软件泛滥。
然后突然看到什么政策原因，come on，
软件名已经诉说了一切，
立下心做一件事的话，就做好啦。

**Comment by U-v-U** [comment]
原因有三：
1. 自带 Core 没必要，毕竟 Qv2ray 本身很复杂，用户都应该会下载和放置
2. 文档写的很清楚的东西，就没必要在代码层面再实现一遍
3. 「某种神秘的政策原因」
4. Qv2ray 可以不依赖 V2Ray-Core （设想关闭 V2Ray 集成的 SSR / Trojan / Trojan-Go / NaiveProxy）

**Comment by ps4jpacce** [comment]
如果你觉得有必要，那就可以让任何人随便都能轻易用上。
你主观觉得没必要，那的确可以拦截70%以上的刚接触用户

**Comment by U-v-U** [comment]
> 说真的，我没看到上面那段话之前，以为你故意不集成核心文件是防止小白多导致软件泛滥。

本身 Qv2ray 怕的不是泛滥，怕的是小白

**Comment by U-v-U** [comment]
（另外不带 Core 这件事原因因人看法而异，我倒是纯粹因为懒得写而不加 ~~随便别人怎么想~~

**Comment by ps4jpacce** [comment]
Do you still remember the experience when you were little White

**Comment by U-v-U** [comment]
（不带 core 并非政策原因，文档那么写，你就那么一看就完事了）

**Comment by U-v-U** [comment]
小白怎么了
每个人都曾经是小白

我为什么要照顾不会跟文档的小白呢
「文档写那么好干嘛不看」

**Comment by U-v-U** [comment]
我承认之前也是重度一键脚本用户
 - 「要是不学习就一直是小白」
 - 「所以我看文档，看说明，读配置文件」

（然后就脱离小白群体咯）

**Comment by U-v-U** [comment]
fixed in https://github.com/Qv2ray/qv2ray.github.io/commit/d6bf3e75a91cf80d3293b96918b2399087b5ee92
