### ISSUE TITLE
似乎不支持无后缀订阅

### ISSUE THREAD

**Issue by ntgeralt** [Qv2ray/Qv2ray#1007]
MAC使用贵站最新版本；
重现方式：订阅地址，网址指向一个无后缀文件
点更新时，提示订阅中仅有0项可用（重试多次排除网络问题）

之后，
无后缀文件加个.txt解决问题

**Comment by DuckSoft** [comment]
我相信你的确遇到了这个问题，但请务必提供足够的信息量以使我们能复现此问题，否则我们也无可奈何。
欢迎加群讨论：https://t.me/qv2ray

**Comment by ntgeralt** [comment]
似乎是我的问题，换了台mac测试正常没那问题。
