### ISSUE TITLE
在 Fedora 33 上的打包问题

### ISSUE THREAD

**Issue by v21cesc** [Qv2ray/Qv2ray#1014]
使用wiki推荐的opensuse software带的fedora源，rawhide，依赖不满足
nothing provides libprotobuf.so.22()(64bit) needed by Qv2ray-2.6.3-33.1.x86_64

33现在已经退出rawhide，还没有33版本的分支，需要更新源。
尝试用32等版本，会有同样问题。

谢谢

**Comment by DuckSoft** [comment]
已转交给 Fedora/openSUSE 仓库维护者 @zzndb。

**Comment by zzndb** [comment]
@v21cesc 
Fedora 33 大致由于目前还是测试版的原因，还未进入 openSUSE build service 的可构建发行版列表，所以得等。

然后这个依赖问题，我这儿用 LXD 开了个 Fedora 32 （没有 rawhide 的镜像……），测试可正常安装，无此依赖问题。这个包是系统自带源里提供的，还请自行检查对应源状态

![图片](https://user-images.githubusercontent.com/20870493/95012149-8ef94b80-0668-11eb-9130-811094d03c23.png)

**Comment by v21cesc** [comment]
> @v21cesc
> Fedora 33 大致由于目前还是测试版的原因，还未进入 openSUSE build service 的可构建发行版列表，所以得等。
> 
> 然后这个依赖问题，我这儿用 LXD 开了个 Fedora 32 （没有 rawhide 的镜像……），测试可正常安装，无此依赖问题。这个包是系统自带源里提供的，还请自行检查对应源状态
> 
> ![图片](https://user-images.githubusercontent.com/20870493/95012149-8ef94b80-0668-11eb-9130-811094d03c23.png)

33 protobuf带的是libprotobuf.so.23和23.0.4 或许spec里面requires改成protobuf代替具体.so文件就可以了

**Comment by zzndb** [comment]
> 33 protobuf带的是libprotobuf.so.23和23.0.4 或许spec里面requires改成protobuf代替具体.so文件就可以了

目前没有 Fedora 33 的原因仅仅是因为 OBS 上还没有提供这个发行版。

另外，这个所谓 Requires 是 RPM 在安装时为满足包里的文件所需共享库依赖自己生成的，并没有手动在 spec 指定（对于可以不手动指定的也并不建议自己指定），另外我也不觉得我写了它就不会再自己依赖对应具体的文件了。

**Comment by sixg0000d** [comment]
对于 Fedora 33 用户，如果实在无法安装 / 使用 OBS 中的 Qv2ray ，可以先使用其他安装方式例如 [AppImage](https://github.com/Qv2ray/Qv2ray/releases/latest) 和 [Snapcraft](https://snapcraft.io/qv2ray) （需安装 snapd）代替，直到 OBS 提供 Fedora 33 的仓库（在 Fedora 33 正式释出后不久应该就会有了，准确来说就是下个月左右？）。

**Comment by zzndb** [comment]
> 在 Fedora 33 正式释出后不久应该就会有了，准确来说就是下个月左右？

看起来貌似是实例管理员直接创建对应仓库，添加对应所需包上游下载源，再完成一堆看不懂的仓库项目配置，就能依托 OBS 添加发行版支持了。

还没有相应经验，这次可以观察一下一般要多久，捏了个 Huginn Agent 每天去检查一下。有了支持就会尽快添加构建……

**Comment by v21cesc** [comment]
> > 在 Fedora 33 正式释出后不久应该就会有了，准确来说就是下个月左右？
> 
> 看起来貌似是实例管理员直接创建对应仓库，添加对应所需包上游下载源，再完成一堆看不懂的仓库项目配置，就能依托 OBS 添加发行版支持了。
> 
> 还没有相应经验，这次可以观察一下一般要多久，捏了个 Huginn Agent 每天去检查一下。有了支持就会尽快添加构建……

好的谢谢解答

**Comment by v21cesc** [comment]
> 对于 Fedora 33 用户，如果实在无法安装 / 使用 OBS 中的 Qv2ray ，可以先使用其他安装方式例如 [AppImage](https://github.com/Qv2ray/Qv2ray/releases/latest) 和 [Snapcraft](https://snapcraft.io/qv2ray) （需安装 snapd）代替，直到 OBS 提供 Fedora 33 的仓库（在 Fedora 33 正式释出后不久应该就会有了，准确来说就是下个月左右？）。

从copr求助到了hub。。其实我是用appimage反过来用回rpm的，问题先关了吧，另外关之前请教个问题，纯2进制文件能否打包成srpm

**Comment by sixg0000d** [comment]
> > 对于 Fedora 33 用户，如果实在无法安装 / 使用 OBS 中的 Qv2ray ，可以先使用其他安装方式例如 [AppImage](https://github.com/Qv2ray/Qv2ray/releases/latest) 和 [Snapcraft](https://snapcraft.io/qv2ray) （需安装 snapd）代替，直到 OBS 提供 Fedora 33 的仓库（在 Fedora 33 正式释出后不久应该就会有了，准确来说就是下个月左右？）。
> 
> 从copr求助到了hub。。其实我是用appimage反过来用回rpm的，问题先关了吧，另外关之前请教个问题，纯2进制文件能否打包成srpm

就我所知是可以的，可以作为 source 打包进 srpm，只是不太符合一些规范（比如 [Fedora Packaging Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/what-can-be-packaged/#prebuilt-binaries-or-libraries)）。
欢迎加入 telegram 群组讨论：https://t.me/fedorazh

**Comment by zzndb** [comment]
已添加 Fedora 33 [相关构建](https://build.opensuse.org/project/monitor/home:zzndb:Qv2ray?defaults=0&succeeded=1&failed=1&unresolvable=1&broken=1&blocked=1&dispatching=1&scheduled=1&building=1&finished=1&signing=1&locked=1&deleting=1&arch_aarch64=1&arch_armv7l=1&arch_i586=1&arch_x86_64=1&repo_Fedora_33=1)

---
BTW, 大概摸清楚了这个套路，即使啥都弄好了， OBS 拉包的上游不给拉也得等到正式发布……

![图片](https://user-images.githubusercontent.com/20870493/97321036-694b1500-18a9-11eb-801c-9efc18999cac.png)

**Comment by v21cesc** [comment]
多谢，已经可以用了
