### ISSUE TITLE
使用trojan-go插件时遇到问题(已解决)

### ISSUE THREAD

**Issue by mcbbsandnz** [Qv2ray/Qv2ray#1016]
## 简单描述这个 Bug:
但使用qv2ray的trojan-go插件时,使用编辑好的配置并尝试启动时,出现trojan-go核心意外关闭
![212112](https://user-images.githubusercontent.com/63087712/95361398-44453100-08ff-11eb-9025-9ed49ac5e8b7.PNG)
## 如何触发这个 Bug：
1. 在trojan插件上证明可以使用的配置转用trojan-go时,尝试启动就会出现Trojan-GO Kernel Crashed(服务器安装的为trojan-go服务)

### 相关截图或日志
![qeqeqeq](https://user-images.githubusercontent.com/63087712/95361937-f4b33500-08ff-11eb-9aae-91993d6081ca.PNG)

请从此行下面的行开始粘贴 Qv2ray 日志：
暂无
## 系统信息
版本: qv2ray版本2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.windows-latest
trojan-go版本为0.8.2
trojan-go-windows-amd64.zip
### 操作系统
windows10 1909专业版, 

### 安装来源
github发布
### 已安装的插件、版本及安装来源
trojan
trojan-go
都源自github发布
## 附加信息
trojan-go插件的核心路径已经填写为trojan-go核心所在
*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
@mcbbsandnz 请读日志第一行。

**Comment by MarksonHon** [comment]
@mcbbsandnz 求助请入群：
<https://t.me/qv2ray>

非反馈软件开发相关的issue将被关闭

**Comment by DuckSoft** [comment]
常见问题：

1. 问题：SNI 忘记填写了
   解决方案：复制域名贴过去
2. 问题：Path 没有以斜线开头
   解决方案：缺斜线补斜线

其他问题可进群交流。

**Comment by mcbbsandnz** [comment]
> 常见问题：
> 
> 1. 问题：SNI忘记填写了
>    解决方案：复制域名贴过去
> 2. 问题：路径没有以斜线开头
>    解决方案：缺斜线补斜线
> 
> 其他问题可进群交流。
感谢,经尝试是sni没有填写,因为服务器那边我是留空的,remote_addr我是直接填写我的域名,现在问题已解决
