### ISSUE TITLE
节点连接成功后，上传下载速度均为零，无法使用

### ISSUE THREAD

**Issue by Adam-fei** [Qv2ray/Qv2ray#1018]
### 连接成功后，上传下载速度均为零
Ubuntu 平台，18.04.4 LTS
QV2ray 版本 2.6.3
内核配置成功，且路径配置检查通过，V2Ray当前版本是 4.28.2
通过订阅地址更新出的节点，显示已连接，延迟时间在 100ms 左右。 上传下载速度都为零，速度图像为直线
相同的节点在 iOS 及 windows 平台均可正常使用

### 你目前试了啥？
1. 内核设置中的联网对时，时间偏差为 0
2. 内核版本，内核版本是 4.28.2，应为可适配版本
3. 调整 log 等级至调试，日志如下补充

#### vCore log
V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
A unified platform for anti-censorship.
2020/10/11 01:49:25 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /home/adam/.config/qv2ray/generated/config.gen.json
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/log: Logger started
2020/10/11 01:49:25 [Info] v2ray.com/core/app/dns: DNS: created udp client inited for 8.8.4.4:53
2020/10/11 01:49:25 [Info] v2ray.com/core/app/dns: DNS: created udp client inited for 1.1.1.1:53
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/stats: create new counter inbound>>>_QV2RAY_API_INBOUND_>>>traffic>>>uplink
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/stats: create new counter inbound>>>_QV2RAY_API_INBOUND_>>>traffic>>>downlink
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:15490
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/stats: create new counter inbound>>>http_IN>>>traffic>>>uplink
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/stats: create new counter inbound>>>http_IN>>>traffic>>>downlink
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:8888
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/stats: create new counter inbound>>>socks_IN>>>traffic>>>uplink
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/stats: create new counter inbound>>>socks_IN>>>traffic>>>downlink
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:1088
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/stats: create new counter outbound>>>outBound_PROXY>>>traffic>>>uplink
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/stats: create new counter outbound>>>outBound_PROXY>>>traffic>>>downlink
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/stats: create new counter outbound>>>outBound_DIRECT>>>traffic>>>uplink
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/stats: create new counter outbound>>>outBound_DIRECT>>>traffic>>>downlink
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/stats: create new counter outbound>>>outBound_BLACKHOLE>>>traffic>>>uplink
2020/10/11 01:49:25 [Debug] v2ray.com/core/app/stats: create new counter outbound>>>outBound_BLACKHOLE>>>traffic>>>downlink
2020/10/11 01:49:25 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:15490
2020/10/11 01:49:25 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:8888
2020/10/11 01:49:25 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1088
2020/10/11 01:49:25 [Info] v2ray.com/core/transport/internet/udp: listening UDP on 127.0.0.1:1088
2020/10/11 01:49:25 [Warning] v2ray.com/core: V2Ray 4.28.2 started
2020/10/11 01:49:25 [Debug] [2176468094] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:35978
2020/10/11 01:49:25 [Info] [2176468094] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:35978
2020/10/11 01:49:25 [Info] [2176468094] v2ray.com/core/app/dispatcher: taking detour [_QV2RAY_API_] for [tcp:127.0.0.1:0]
2020/10/11 01:49:25 127.0.0.1:35978 accepted tcp:127.0.0.1:0 [_QV2RAY_API_]
#### Qv2ray log (1)
[CORE-CONNECTION]: Inserting default values to simple config
[CORE-CONNECTION]: Outbound protocol vmess is not a registered plugin outbound.
[CORE-CONNECTION]: Outbound protocol freedom is not a registered plugin outbound.
[CORE-CONNECTION]: Outbound protocol blackhole is not a registered plugin outbound.
[CORE-CONNECTION]: Applying new outbound settings.
[CORE-VCORE]: Starting kernels with V2RayIntegration.
[CORE-VCORE]: Core ABI: ELF amd64 可执行文件
[CORE-VCORE]: Host ABI: ELF amd64 可执行文件
[CORE-VCORE]: Host is compatible with core
[CORE-VCORE]: V2Ray output: V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64);A unified platform for anti-censorship.
[CORE-UI]: Setting current item.
[CORE-VCORE]: API call returns: 14 (Socket closed)
#### Qv2ray log (2)
[CORE-CONNECTION]: Inserting default values to simple config
[CORE-CONNECTION]: Outbound protocol vmess is not a registered plugin outbound.
[CORE-CONNECTION]: Outbound protocol freedom is not a registered plugin outbound.
[CORE-CONNECTION]: Outbound protocol blackhole is not a registered plugin outbound.
[CORE-CONNECTION]: Applying new outbound settings.
[CORE-VCORE]: Starting kernels with V2RayIntegration.
[CORE-VCORE]: Core ABI: ELF amd64 可执行文件
[CORE-VCORE]: Host ABI: ELF amd64 可执行文件
[CORE-VCORE]: Host is compatible with core
[CORE-VCORE]: V2Ray output: V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64);A unified platform for anti-censorship.
[CORE-UI]: Setting current item.

[CORE-VCORE]: API call returns: 14 (Socket closed)
[CORE-VCORE]: API call returns: 14 (Connect Failed)
[CORE-VCORE]: API call returns: 14 (channel is in state TRANSIENT_FAILURE)
[CORE-VCORE]: API call returns: 14 (channel is in state TRANSIENT_FAILURE)

#### 日志说明
多次连接尝试，vCore 日志内容不变。Qv2ray log 期初为 (1) 中内容，之后变成 (2) 中内容

**Comment by EpLiar** [comment]
应用代理设置好了么？看起来并没有相关流量走了代理出去

**Comment by DuckSoft** [comment]
没有流量进来。喂他一口试试：

```bash
curl -sSLvv -x http://127.0.0.1:8888 https://www.google.com/
```

**Comment by MarksonHon** [comment]
@DuckSoft 使用问题请加群反馈，此 issue 将被关闭。

Telegram 群组：<https://t.me/qv2ray>

**Comment by Adam-fei** [comment]
@DuckSoft 
速度图像有了一个凸起，看来是成功了？ 终端里内容如下

> *   Trying 127.0.0.1:8888...
> * TCP_NODELAY set
> * Connected to 127.0.0.1 (127.0.0.1) port 8888 (#0)
> * allocate connect buffer!
> * Establish HTTP proxy tunnel to www.google.com:443
> > CONNECT www.google.com:443 HTTP/1.1
> > Host: www.google.com:443
> > User-Agent: curl/7.65.3
> > Proxy-Connection: Keep-Alive
> > 
> < HTTP/1.1 200 Connection established
> < 
> * Proxy replied 200 to CONNECT request
> * CONNECT phase completed!
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /home/adam/anaconda3/ssl/cacert.pem
>   CApath: none
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * CONNECT phase completed!
> * CONNECT phase completed!
> * OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443 
> * Closing connection 0
> curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443 
>

**Comment by Adam-fei** [comment]
设置应用代理后，速度图像有了值，确认现在流量都走了代理。但此时浏览器连墙内网页也无法进入(但可以ping通墙内地址，无法ping通墙外地址)，断开连接后恢复正常
错误日志如下
```
2020/10/11 17:58:14 [Info] [3871619007] v2ray.com/core/app/dispatcher: default route for tcp:cn.bing.com:443
2020/10/11 17:58:14 [Info] [3871619007] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:hk01.ipv2.xyz:23336
2020/10/11 17:58:14 127.0.0.1:36344 accepted //cn.bing.com:443 [outBound_PROXY]
2020/10/11 17:58:14 [Info] [3871619007] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:cn.bing.com:443 via tcp:×××.×××.xyz:23336
2020/10/11 17:58:14 [Info] [3871619007] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: Failed To Decrypt Length > cipher: message authentication failed
2020/10/11 17:58:14 [Info] [3871619007] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
2020/10/11 17:58:17 [Info] [1856039854] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: failed to read http request > EOF
2020/10/11 17:58:19 [Info] [4169948128] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: failed to read http request > EOF
```

**Comment by DuckSoft** [comment]
https://github.com/v2fly/v2ray-core/blob/ed97a250e4d0a08b16fad6914c534506490e7814/proxy/vmess/encoding/client.go#L210

你这个错误日志是 VMess AEAD 的错误日志。猜测你的 AlterID 设置成 0，无意间出发了 4.28.1 及之后版本的一个机制。
请看上游关于[此版本](https://github.com/v2fly/v2ray-core/releases/tag/v4.28.1)的说明：
```
    Use GO 1.15
    VMess AEAD will be used when alterId is 0. ("testsEnabled" is discarded)
    Fix incorrect AEAD IV usage which slightly reduced security. thanks @cute
```

注意：VMess AEAD will be used when alterId is 0。

**Comment by DuckSoft** [comment]
你其他平台、以及你的服务器上使用的版本应该都是 4.28.1 发生变更之前的版本。
尤其是 iOS 平台和 WIndows 平台，如果你使用的不是来自 V2Ray Core 的、跟进较慢的第三方实现（如 Clash、Shadowrocket 等），顺便还设置了 AlterID = 0，就会出现这种情况。

你有以下几种选择，每一个都能解决问题：
1. 客户端降级。降级 V2Ray Core 到 4.27.x。其他配置无需变更。
2. 客户端绕过。右键编辑节点，若 AlterID 为 0，修改 AlterID 到 1。注意，这个有潜在的几率导致连接不稳定。
3. 全平台升级。升级你所有平台的客户端到 4.28.1 及以上版本，升级所有第三方的客户端到支持 VMess AEAD 的版本，升级你的服务器 V2Ray Core 到支持 VMess AEAD 的版本。

其他方案不一一列出。

另外：鉴于此问题并非 Qv2ray 本体问题，后续细节请去我们的 Telegram 群里细聊。

**Comment by jiandandian2** [comment]
> 设置应用代理后，速度图像有了值，确认现在流量都走了代理。但此时浏览器连墙内网页也无法进入(但可以ping通墙内地址，无法ping通墙外地址)，断开连接后恢复正常
> 错误日志如下
> 
> ```
> 2020/10/11 17:58:14 [Info] [3871619007] v2ray.com/core/app/dispatcher: default route for tcp:cn.bing.com:443
> 2020/10/11 17:58:14 [Info] [3871619007] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:hk01.ipv2.xyz:23336
> 2020/10/11 17:58:14 127.0.0.1:36344 accepted //cn.bing.com:443 [outBound_PROXY]
> 2020/10/11 17:58:14 [Info] [3871619007] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:cn.bing.com:443 via tcp:×××.×××.xyz:23336
> 2020/10/11 17:58:14 [Info] [3871619007] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: Failed To Decrypt Length > cipher: message authentication failed
> 2020/10/11 17:58:14 [Info] [3871619007] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
> 2020/10/11 17:58:17 [Info] [1856039854] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: failed to read http request > EOF
> 2020/10/11 17:58:19 [Info] [4169948128] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: failed to read http request > EOF
> ```

hello, I have the same mistake, have u solved it?

**Comment by zthooo** [comment]
遇到相同的问题，请问有解决么？

**Comment by DuckSoft** [comment]
具体问题具体分析，请勿挖坟，谢谢配合。
