### ISSUE TITLE
使用疑问：使用的过程中，MAC会不断弹出网络代理验证弹窗

### ISSUE THREAD

**Issue by Ezio0** [Qv2ray/Qv2ray#1019]
### 你想做啥？
*简要描述你的最原始的目的。*
MAC在使用Qv2ray的时候，总是会弹出网络代理认证的弹窗，每次点确定之后再弹一次，再确定之后，会有一段时间不再弹出，过一段时间再弹出

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
在网上没找到解决方案

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by EpLiar** [comment]
这个应该和系统以及无线网络有关，和 Qv2ray 没有关系

**Comment by DuckSoft** [comment]
macOS 权限问题。

```zsh
$ sudo security authorizationdb write system.services.systemconfiguration.network allow
YES (0)
```

根除。

**Comment by Ezio0** [comment]
我试一下

**Comment by Ezio0** [comment]
> macOS 权限问题。
> 
> ```shell
> $ sudo security authorizationdb write system.services.systemconfiguration.network allow
> YES (0)
> ```
> 
> 根除。

还是不行。。。

**Comment by DuckSoft** [comment]
我在 macOS 10.14 10.15.6 10.15.7 全都测试过了，没有任何问题。
难不成你是 macOS 10.16/11.0 Bug Sir?

**Comment by U-v-U** [comment]
瞅一眼 config.gen.json 里的相关入站设置？

**Comment by Ezio0** [comment]
> 我在 macOS 10.14 10.15.6 10.15.7 全都测试过了，没有任何问题。
> 难不成你是 macOS 10.16/11.0 Bug Sir?

10.15.7

**Comment by Ezio0** [comment]
> 瞅一眼 config.gen.json 里的相关入站设置？

这个在哪儿。。。

**Comment by DuckSoft** [comment]
你的网络环境是否特殊？比如公司的网络，必须经过特殊配置才能上网之类的？

**Comment by U-v-U** [comment]
config.gen.json 在插件文件夹上一层，即为配置文件目录内的 generated 子文件夹内

**Comment by Ezio0** [comment]
> 你的网络环境是否特殊？比如公司的网络，必须经过特殊配置才能上网之类的？

我在家里也会弹，不只是公司

**Comment by DuckSoft** [comment]
弹的时候可否截个图让我们看看

**Comment by DuckSoft** [comment]
另外，GitHub 上不适合进行即时通讯，因为我们每次发帖/回复一条消息，本项目里的 22 个人的邮箱都会同时收到通知。
若有条件，建议加入 https://t.me/qv2ray 我们的讨论群与我们直接沟通。

**Comment by Ezio0** [comment]
> 另外，GitHub 上不适合进行即时通讯，因为我们每次发帖/回复一条消息，本项目里的 22 个人的邮箱都会同时收到通知。
> 若有条件，建议加入 https://t.me/qv2ray 我们的讨论群与我们直接沟通。

    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 15490,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "sniffing": {
            },
            "tag": "_QV2RAY_API_INBOUND_"
        },
        {
            "listen": "127.0.0.1",
            "port": 8889,
            "protocol": "http",
            "settings": {
            },
            "sniffing": {
                "enabled": false
            },
            "tag": "http_IN"
        },
        {
            "listen": "127.0.0.1",
            "port": 1089,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "ip": "127.0.0.1",
                "udp": true,
                "userLevel": 0
            },
            "sniffing": {
                "enabled": false
            },
            "tag": "socks_IN"
        }
    ],
    "log": {
        "loglevel": "warning"

**Comment by DuckSoft** [comment]
已在 Telegram 上沟通。确认此问题并非来自 Qv2ray。

**Comment by mengyangniu** [comment]
> 已在 Telegram 上沟通。确认此问题并非来自 Qv2ray。

同公司电脑，我也有这个问题。请问你解决了吗？

**Comment by 27149** [comment]
请问这个问题最后怎么解决的？目前也遇到这个问题，烦不胜烦

**Comment by jiayong** [comment]
我也遇见这个问题了，总是弹窗
