### ISSUE TITLE
Ubuntu 18.04 使用疑问一则

### ISSUE THREAD

**Issue by NewYinbao** [Qv2ray/Qv2ray#1021]
版本：2.6.3:5840
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.ubuntu-16.04

v2ray内核配置正常
内核版本4.26.0
连接后，无字节传输。

终端出现：
[CORE-UI]: Setting current item.
[CORE-VCORE]: gRPC Version: 1.19.1
[CORE-VCORE]: API call returns: 14 (Connect Failed)
[CORE-VCORE]: API call returns: 14 (channel is in state TRANSIENT_FAILURE)
[CORE-VCORE]: API call returns: 14 (channel is in state TRANSIENT_FAILURE)

**Comment by DuckSoft** [comment]
```bash
curl -x socks5h://127.0.0.1:1089 -sSLv https://www.google.com/
```

**Comment by DuckSoft** [comment]
You may want to have a look at some similar issues:
https://github.com/Qv2ray/Qv2ray/issues/1018

**Comment by DuckSoft** [comment]
Also read the fancy documentation: https://qv2ray.net/
