### ISSUE TITLE
V2Ray 核心可执行文件未找到

### ISSUE THREAD

**Issue by Zhaoxun** [Qv2ray/Qv2ray#1022]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 如何触发这个 Bug：

1. 编辑连接
2. 填好主机、端口，类型（VMess)，UUID, Alter ID，安全（auto），测试（none），传输协议（tcp），类型（none）
3. 点击连接

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
未测试

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```
V2Ray 核心设置不正确。

错误如下: 
V2Ray 核心可执行文件未找到。
</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3-32bit
编译信息：
额外编译信息：
```

### 操作系统

- Windows 7-32bit

### 安装来源

- Github Release / Scoop / Chocolatey

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
https://qv2ray.net/getting-started/step1

**Comment by MarksonHon** [comment]
@Zhaoxun 请阅读文档，此 issue 会被关闭，因为这不是软件的故障，只是你没有配置好。

Telegram 群：<https:/t.me/qv2ray>
