### ISSUE TITLE
(k)ubuntu20.10 安装时提示“缺少依赖”？？从20.04LTS 升级，无法启动

### ISSUE THREAD

**Issue by discuss1314** [Qv2ray/Qv2ray#1026]
从20.04LTS 升级，无法启动。原本是正常的.升级到20.10beta后无法启动，也无法安装 
![Screenshot_20201014_033400](https://user-images.githubusercontent.com/64603548/95907498-38111600-0dce-11eb-90e0-d167ed069357.jpg)

**Comment by DuckSoft** [comment]
20.04LTS 是 debian stable
20.10 是 debian unstable

记得根据 https://qv2ray.net/debian 指示换源。
