### ISSUE TITLE
功能请求：Qv2ray的后置代理设置，v2ray通过其他代理链接！！！

### ISSUE THREAD

**Issue by Eternallove123** [Qv2ray/Qv2ray#1027]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
请尽可能清晰简洁地描述问题。例：每次吃饭都要出门穿衣收拾打扮，太烦了……

**简单描述你预期的解决方案？**
请尽可能清晰简洁描述问题。例：我想打电话给餐馆让他们直接给我送过来……

**你有想到其他比较容易实现的解决方案吗？**
请简单清晰描述。例：或者直接给餐馆签个协议也行……

**补充内容**
请在此附加任何你认为对你的描述有所帮助的内容。

**Comment by kidonng** [comment]
请按照 issue 模板详细描述你的需求。

**Comment by MarksonHon** [comment]
@Eternallove123 讲真，我们看不懂你到底想要啥新功能。

**Comment by Copay** [comment]
@Eternallove123 _Marked as abuse of issues_

**Comment by U-v-U** [comment]
closed
