### ISSUE TITLE
功能请求：希望增加dns over tcp/udp的相关设置

### ISSUE THREAD

**Issue by EsuRt** [Qv2ray/Qv2ray#1030]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
使用shadowsocks协议访问被墙网站时，如果ss服务器端没有开通udp，当Qv2ray使用国内dns时，容易被污染；当Qv2ray使用国外dns时，解析速度非常慢，有时会丢包。希望对于shadowsocks协议，能够增加下dns over tcp或udp的相关设置。
使用vmess协议时，解析是正常的。

**简单描述你预期的解决方案？**
国外网站或被墙网站使用国外dns时，让用户选择是否通过代理来访问国外dns。

**你有想到其他比较容易实现的解决方案吗？**
无

**补充内容**
无

**Comment by kslr** [comment]
原版 ss 有这个功能吗？

**Comment by DuckSoft** [comment]
你好，此功能属代理功能，为上游 v2ray-core 核心所提供，Qv2ray 本体并无代理能力。
请移步上游 https://github.com/v2fly/v2ray-core.
