### ISSUE TITLE
“静态解析域名”的上下移动按钮未随主题切换亮色/暗色

### ISSUE THREAD

**Issue by sixg0000d** [Qv2ray/Qv2ray#1031]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

DNS 设置页面，所有按键的符号，在任何情况下都显示不清晰，似乎是渲染有问题
（已经存在了有几个版本了，其余的按键渲染问题似乎在我的系统中的最新版 Qv2ray 里已经没有了，只剩下这几个了

经测试在以下界面主题下显示不清晰：
Breeze
Fusion
Windows
flatwhite
在以下界面主题下显示清晰：
Built-in Darkmode
psblack
也就是说在除暗色主题外所有主题显示都不清晰

## 如何触发这个 Bug：

1. 打开 Qv2ray 面板，打开首选项
2. 打开 DNS 设置
3. DNS 服务器选项卡下，四个按键皆看不清楚
4. 静态解析域名选项卡下，两个按键皆看不清楚

### 相关截图或日志

<details>

![Screenshot_20201016_181447](https://user-images.githubusercontent.com/17105863/96247578-e38fb580-0fdc-11eb-95a2-528fcc5d6332.png)
![Screenshot_20201016_182416](https://user-images.githubusercontent.com/17105863/96247585-e5597900-0fdc-11eb-99cb-fd2dd0e51731.png)

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.7.0-alpha2:6010
编译信息：Qv2ray built by Fedora Copr
额外编译信息：(Unofficial Build) 5.8.14-300.fc33.x86_64 x86_64, Qt 5.15.1
```

### 操作系统

- Linux

操作系统： Fedora 33
KDE Plasma 版本： 5.19.5
KDE 框架版本： 5.73.0
Qt 版本： 5.15.1
内核版本： 5.8.14-300.fc33.x86_64

X.Org X Server 1.20.9
X Protocol Version 11, Revision 0

### 安装来源

- 手动编译（自行打包，可以算是手动编译吧）

### 已安装的插件、版本及安装来源

和源码一起编译出来的俩内建插件，版本同 Qv2ray：
/usr/share/qv2ray/plugins/libQvPlugin-BuiltinProtocolSupport.so
/usr/share/qv2ray/plugins/libQvPlugin-BuiltinSubscriptionSupport.so

## 附加信息

编译时使用的一些可能相关的依赖：
```
...
qt5-qtbase-gui-5.15.1-5.fc33.x86_64 1601473938 19316001 11ec04a66e8dcfaf94fd07b3e1d8c32f installed
qt5-qtsvg-5.15.1-1.fc33.x86_64 1599817879 625320 808a66e897bf5fc1efc2887894578f2f installed
...
qt5-qtbase-devel-5.15.1-5.fc33.x86_64 1601473938 19793312 8b11ccbcf82ae63dc8e64d48e9c84a40 installed
qt5-qtsvg-devel-5.15.1-1.fc33.x86_64 1599817879 85635 5e243be435c32e2b329a39e915929d1c installed
...
qt5-linguist-5.15.1-1.fc33.x86_64 1599821677 2899671 a0b9145b70a8829de45dddabc15c730d installed
```
*请注意打码隐私相关信息。*

**Comment by MarksonHon** [comment]
@sixg0000d 先说明下你的桌面环境与操作系统，是 KDE Plasma 么？

**Comment by MarksonHon** [comment]
@sixg0000d 同时也说明下你的桌面是运在 Xorg 下 还是 Wayland 下。

**Comment by DuckSoft** [comment]
复现。大概是因为没有区分暗/亮色图标。

**Comment by U-v-U** [comment]
fixed in https://github.com/Qv2ray/Qv2ray/commit/389b29d10576c7874c7f8e919b3ccdfccebd8f9f

**Comment by sixg0000d** [comment]
我已经升级到
```
版本: 2.7.0-pre1:6039
编译信息：Qv2ray built by Fedora Copr
额外编译信息：(Unofficial Build) 5.8.17-300.fc33.x86_64 x86_64, Qt 5.15.1
```

但是看上去 `静态解析域名` 里的两个按键还是显示不清晰，忘记修复了吗:joy:

**Comment by DuckSoft** [comment]
> 我已经升级到
> 
> ```
> 版本: 2.7.0-pre1:6039
> 编译信息：Qv2ray built by Fedora Copr
> 额外编译信息：(Unofficial Build) 5.8.17-300.fc33.x86_64 x86_64, Qt 5.15.1
> ```
> 
> 但是看上去 `静态解析域名` 里的两个按键还是显示不清晰，忘记修复了吗😂

请贴图，谢谢

**Comment by sixg0000d** [comment]
> > 我已经升级到
> > ```
> > 版本: 2.7.0-pre1:6039
> > 编译信息：Qv2ray built by Fedora Copr
> > 额外编译信息：(Unofficial Build) 5.8.17-300.fc33.x86_64 x86_64, Qt 5.15.1
> > ```
> > 
> > 
> > 但是看上去 `静态解析域名` 里的两个按键还是显示不清晰，忘记修复了吗joy
> 
> 请贴图，谢谢

![image](https://user-images.githubusercontent.com/17105863/98226135-988c1100-1f90-11eb-84d6-cd93b96d6c85.png)

**Comment by DuckSoft** [comment]
好像……的确没修复……太草了……

**Comment by DuckSoft** [comment]
@sixg0000d 这次真的修好了……咕咕咕
