### ISSUE TITLE
qv2ray: symbol lookup error: qv2ray: undefined symbol: _ZN4grpc13CreateChannelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_18ChannelCredentialsEE

### ISSUE THREAD

**Issue by vfdxvffd** [Qv2ray/Qv2ray#1034]
Manjaro更新到2.6.3-5，不能正常启动，命令行启动报错如下
~
❯ qv2ray
qv2ray: symbol lookup error: qv2ray: undefined symbol: _ZN4grpc13CreateChannelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_18ChannelCredentialsEE

**Comment by U-v-U** [comment]
https://t.me/qv2ray/384467

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/96354124-a541e580-1105-11eb-97bb-deca01f1a084.png)

**Comment by KiteAB** [comment]
This issue has been fixed.
