### ISSUE TITLE
qv2ray启动出现了错误

### ISSUE THREAD

**Issue by SuperH-0630** [Qv2ray/Qv2ray#1035]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

我启动``qv2ray``程序的时候出现了一下报错：
``
qv2ray: symbol lookup error: qv2ray: undefined symbol: _ZN4grpc13CreateChannelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_18ChannelCredentialsEE

当然，我尝试安装了``qv2ray-2.6.3-1``后并没有出现该问题
``

## 如何触发这个 Bug：

1. 安装``qv2ray-2.6.3-5``
2. 在命令行输入``qv2ray``
3. 出现错误提示

### 相关截图或日志
![image](https://user-images.githubusercontent.com/42832734/96337664-40619d80-10bb-11eb-8775-7f89becd0213.png)

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：

非常抱歉，我真的找不到 log 的位置
```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray for Arch Linux CN
额外编译信息：(Official Build) 5.6.12-arch1-1 x86_64

## 以上信息是我使用``qv2ray-2.6.3-1``重新安装后的信息，``qv2ray-2.6.3-5``是出现问题的版本，我无法启动界面，因此无法得到这些信息
```

### 操作系统

- Linux

### 安装来源

- ArchLinuxCN - 稳定版

**Comment by U-v-U** [comment]
https://t.me/qv2ray/384467

**Comment by vfdxvffd** [comment]
我也刚刚更新后出现了此问题，请问您有解决方案了吗？

**Comment by SuperH-0630** [comment]
先降级用着先，等源更新再升级应该就好了

**Comment by DuckSoft** [comment]
Manjaro 用户可以从 Arch Linux 仓库偷一个最新的 grpc 回来用：
https://mirrors.tuna.tsinghua.edu.cn/archlinux/community/os/x86_64/grpc-1.32.0-2-x86_64.pkg.tar.zst

偷回来，使用 `sudo pacman -U xxxx.pkg.tar.zst` 安装即可。

------
顺便：欢迎安装 Arch Linux:
https://wiki.archlinux.org/index.php/Installation_guide_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)
