### ISSUE TITLE
使用疑问：Qv2ray是不是就相当于代理？？

### ISSUE THREAD

**Issue by Corezcy** [Qv2ray/Qv2ray#1036]
如题。`Qv2ray`是不是就相当于代理，打通本机和`vps`的连接，然后通过`vps`上的`trojan`转发出去，再返回？？？
最近刚好做了个基于`websockets`的`python`的代理服务器，突然想到了。请教一下！！！

**Comment by Sinofine** [comment]
是，但可能不是trojan。
服务器上可能是v2ray-core，也可能是shadowsocks，还可以是shadowsocksr，抑或是Trojan，Trojan-Go，NaiveProxy之类。
如果你有兴趣，你也可以尝试编写你的代理协议在qv2ray上的客户端性质的插件。
ps. 你没照issue模板写，会被close
pss. 你可以加入Telegram群组参与讨论：https://t.me/qv2ray

**Comment by DuckSoft** [comment]
未按模板填写，且问题质量很差，直接关闭。
