### ISSUE TITLE
Bug:软件无法打开 ：qv2ray: symbol lookup error:qv2ray: undefined symbol:

### ISSUE THREAD

**Issue by littleantlive** [Qv2ray/Qv2ray#1037]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
昨天上午使用时电脑突然断电了，后来下午再次使用时发现无法打开，点击图标后没有任何反应，在终端中打开报错：
qv2ray: symbol lookup error: qv2ray: undefined symbol: _ZN9grpc_impl17CreateChannelImplERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_18ChannelCredentialsEE

## 如何触发这个 Bug：

1. 正常使用过程中突然断电
2. 没有办法再次打开软件
3. 卸载重装无法解决

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
不是连接问题，请忽略

### 相关截图或日志
qv2ray: symbol lookup error: qv2ray: undefined symbol: _ZN9grpc_impl17CreateChannelImplERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_18ChannelCredentialsEE
<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 由于无法打开软件，具体信息无法获取，版本就是AUR当中的最新稳定版

```

版本: 
编译信息：
额外编译信息：
```

### 操作系统

- Linux 

### 安装来源

- ArchLinuxCN - 稳定版

- ArchLinux AUR - 稳定版

### 已安装的插件、版本及安装来源
无插件

## 附加信息

*请注意打码隐私相关信息。*

**Comment by MarksonHon** [comment]
@littleantlive https://t.me/qv2ray/384467

**Comment by DuckSoft** [comment]
Arch Linux 用户注意

grpc 又升级了，相应更新构建已触发。
老规矩，源滞后用户可先降级 grpc，等待源更新即可。

![图片](https://user-images.githubusercontent.com/7822648/96356324-383b4980-111f-11eb-8344-95bd9dfb9820.png)

Manjaro 用户请不要再问为什么更新前和更新后都炸了。
