### ISSUE TITLE
今早manjaro xfce更新qv2ray，无法打开了。点击没反应。

### ISSUE THREAD

**Issue by Hiddensu** [Qv2ray/Qv2ray#1039]
## 简单描述这个 Bug:
今早manjaro xfce更新qv2ray，无法打开了。点击没反应。卸载重新安装也是这样。

### 操作系统

- Linux

### 安装来源

- ArchLinuxCN - 稳定版

### 已安装的插件、版本及安装来源
安装了SSR插件。

**Comment by DuckSoft** [comment]
#1038 #1037 #1035 #1034 #1033 #1032 
全是 Manjaro 用户，哎……

关于 Manjaro、KaOS 等基于 pacman 软件管理器等操作系统的安装 Qv2ray 的说明：

很多人并不知道，一个开源操作系统的衍生版本并不等于原始开源操作系统——衍生版本的操作系统有着自己的定制、打包计划与更新计划，它们的更新进度或快于原始系统（比如 Ubuntu、Kali Linux 的更新速度要比 Debian 快），也可能慢于原始系统（比如 Manjaro 的更新速度要慢于 Arch Linux），也可能直接用了原始系统的软件源（比如 Linux Mint Debian Edition 直接用了 Debian 的源，ArchBang Linux、Artix Linux 直接用了全部或者部分 Arch Linux 的源）。

Qv2ray 在 Arch Linux CN 这个源里面提供了安装包，不过，由于该软件源是适配 Arch Linux 的，因此我们不建议 Arch Linux 衍生版的用户直接使用该软件源提供的安装包，除非你所用的衍生版直接用了 Arch Linux 的软件源。

Manjaro、KaOS 用户建议从 AUR 编译安装 Qv2ray，或者直接使用 AppImage 版本。

----

https://t.me/qv2ray/386620
