### ISSUE TITLE
qv2ray图形界面无法打开

### ISSUE THREAD

**Issue by BrandonMoo** [Qv2ray/Qv2ray#1040]
系统manjaro 20.1.1 KDE 5.74.0 / Plasma 5.19.5，开机后没有自动启动，手动打开后仍无法打开，重启无法解决问题，pacman重装也无法解决问题。

**Comment by MarksonHon** [comment]
@BrandonMoo https://t.me/qv2ray/386620

**Comment by DuckSoft** [comment]
#1039 #1038 #1037 #1035 #1034 #1033 #1032

**Comment by MarksonHon** [comment]
@BrandonMoo 还有，你没按照模板填写故障问单，故而此问单将关闭。

建议加入我们的 Telegram 群。
