### ISSUE TITLE
manjaro 2.6.3-5更新后打不开软件

### ISSUE THREAD

**Issue by Wintere107** [Qv2ray/Qv2ray#1041]
##Qv2ray 日志：

qv2ray: symbol lookup error: qv2ray: undefined symbol: _ZN4grpc13CreateChannelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_18ChannelCredentialsEE
```
## 系统信息

OS: Manjaro 20.1.1 Mikah
Kernel: x86_64 Linux 5.8.11-1-MANJARO
DE: KDE 5.74.0 / Plasma 5.19.5

### 安装来源

- ArchLinuxCN - 稳定版

**Comment by wallena3** [comment]
manjaro用户请从AUR编译安装或使用Appimage。ArchLinuxCN不对ArchLinux以外用户提供任何担保。

**Comment by DuckSoft** [comment]
#1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032
全是 Manjaro 用户，你们啊，哎……

https://t.me/qv2ray/386620

----

关于 Manjaro、KaOS 等基于 pacman 软件管理器等操作系统的安装 Qv2ray 的说明：

很多人并不知道，一个开源操作系统的衍生版本并不等于原始开源操作系统——衍生版本的操作系统有着自己的定制、打包计划与更新计划，它们的更新进度或快于原始系统（比如 Ubuntu、Kali Linux 的更新速度要比 Debian 快），也可能慢于原始系统（比如 Manjaro 的更新速度要慢于 Arch Linux），也可能直接用了原始系统的软件源（比如 Linux Mint Debian Edition 直接用了 Debian 的源，ArchBang Linux、Artix Linux 直接用了全部或者部分 Arch Linux 的源）。

Qv2ray 在 Arch Linux CN 这个源里面提供了安装包，不过，由于该软件源是适配 Arch Linux 的，因此我们不建议 Arch Linux 衍生版的用户直接使用该软件源提供的安装包，除非你所用的衍生版直接用了 Arch Linux 的软件源。

Manjaro、KaOS 用户建议从 AUR 编译安装 Qv2ray，或者直接使用 AppImage 版本。

**Comment by Wintere107** [comment]
> #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032
> 全是 Manjaro 用户，你们啊，哎……
> 
> https://t.me/qv2ray/386620
> 
> 关于 Manjaro、KaOS 等基于 pacman 软件管理器等操作系统的安装 Qv2ray 的说明：
> 
> 很多人并不知道，一个开源操作系统的衍生版本并不等于原始开源操作系统——衍生版本的操作系统有着自己的定制、打包计划与更新计划，它们的更新进度或快于原始系统（比如 Ubuntu、Kali Linux 的更新速度要比 Debian 快），也可能慢于原始系统（比如 Manjaro 的更新速度要慢于 Arch Linux），也可能直接用了原始系统的软件源（比如 Linux Mint Debian Edition 直接用了 Debian 的源，ArchBang Linux、Artix Linux 直接用了全部或者部分 Arch Linux 的源）。
> 
> Qv2ray 在 Arch Linux CN 这个源里面提供了安装包，不过，由于该软件源是适配 Arch Linux 的，因此我们不建议 Arch Linux 衍生版的用户直接使用该软件源提供的安装包，除非你所用的衍生版直接用了 Arch Linux 的软件源。
> 
> Manjaro、KaOS 用户建议从 AUR 编译安装 Qv2ray，或者直接使用 


感谢！建议在readme里标注一下，如：“Manjaro、KaOS 用户建议从 AUR 编译安装 Qv2ray”。

**Comment by DuckSoft** [comment]
Fixed in 498580fb20151a2b43a604f5d724be438621eb1d
