### ISSUE TITLE
Qv2ray客户端如何设置后置代理，让其通过其他代理连接？希望Qv2ray社区大佬通过我的这个疑问？

### ISSUE THREAD

**Issue by nothingisimpossible666** [Qv2ray/Qv2ray#1042]
### 你想做啥？
*简要描述你的最原始的目的。*
例：我在学校，校园网能解锁文献数据库，我想对这些地址直连。

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
例：看完文档，没有相关内容，就过来问一问。

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by DuckSoft** [comment]
正文不含任何有效内容。直接关闭。
