### ISSUE TITLE
qv2ray后置代理如何设置，如果还是不显示此问题，我会一直发

### ISSUE THREAD

**Issue by nothingisimpossible666** [Qv2ray/Qv2ray#1043]
### 你想做啥？
*简要描述你的最原始的目的。*
例：我在学校，校园网能解锁文献数据库，我想对这些地址直连。

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
例：看完文档，没有相关内容，就过来问一问。

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by MarksonHon** [comment]
你没有按照模板填写，同时你也不是在报告问题，而是在求助，因此此 issue 将被关闭。
如果你想要人帮忙，请通过此链接进群：<https://t.me/qv2ray>

**Comment by U-v-U** [comment]
@nothingisimpossible666 
首先这东西应该叫前置代理
其次这东西首选项里面有，节点设置里面也有

![image](https://user-images.githubusercontent.com/59914293/96457964-f90e1500-1252-11eb-9a02-621c4a6ac4be.png)
![image](https://user-images.githubusercontent.com/59914293/96457975-fad7d880-1252-11eb-921a-70c9e60d73a5.png)


另外 Issue 模板是用来填写的，不是给你看的

**Comment by DuckSoft** [comment]
滚
