### ISSUE TITLE
复杂配置编辑器移动连线终点的问题

### ISSUE THREAD

**Issue by dna1982** [Qv2ray/Qv2ray#1045]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
复杂设置编辑器中，修改Routing --> Outbound时有问题，见下面的GIF。
这个BUG从 2.7.0-alpha1  一直到现在的 2.7.0-alpha3 都存在。
<del>（本以为这么明显的BUG会很快修复的。）</del>

## 如何触发这个 Bug：
见下面的GIF。

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
非连接问题

### 相关截图或日志
因为暴露了隐私，临时移除GIF。

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.7.0-alpha3:6022
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-8be5d7dd2a6c3ec55de0b825d71351308c08e382-ci.windows-latest
```

### 操作系统
- Windows

### 安装来源
- Github Release / Scoop / Chocolatey

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
Confirmed. Assigned to @U-v-U.

**Comment by U-v-U** [comment]
This has been fixed in the commit https://github.com/Qv2ray/Qv2ray/commit/4478ed9cb97b4323e600a71dccf10d47959f1466

**Comment by dna1982** [comment]
Thanks for your hard work.

**Comment by Arzenow** [comment]
> * [x]  **我确定我已经尝试多次触发此次问题，并且将会提供涉及会提供涉及此问题的系统**
> 
> ## اشکال 简单描述这个:
> مسیریابی --> خروجی ~（本以为这么明显的BUG会很快修复的。）~
> 
> ## 如何触发这个 اشکال：
> 见下面的GIF.
> 
> ### 如果是连接问题，在其他 V2Ray 客户端里出现过吗?
> 非连接问题
> 
> ### 相关截图或日志
> 因为暴露了隐私，临时移除GIF.
> 
> ## 系统信息
> ### 打开首选项 -> 关于，填写以下信息
> ```
> 版本: 2.7.0-alpha3:6022
> 编译信息：Qv2ray built from Github Action
> 额外编译信息：qt5.15.0-8be5d7dd2a6c3ec55de0b825d71351308c08e382-ci.windows-latest
> ```
> 
> ### 操作系统
> * پنجره ها
> 
> ### 安装来源
> * Github Release / Scoop / Chocolatey
> 
> ### 已安装的插件、版本及安装来源
> ## 附加信息
> _请注意打码隐私相关信息。_

V2RAYNG by arzenow.com
