### ISSUE TITLE
启动时提示符号查找错误

### ISSUE THREAD

**Issue by tfx2001** [Qv2ray/Qv2ray#1046]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

Qv2ray启动失败。

## 如何触发这个 Bug：

1. 启动Qv2ray时就会触发

### 相关截图或日志

<details>

```
qv2ray: symbol lookup error: qv2ray: undefined symbol: _ZN4grpc13CreateChannelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_18ChannelCredentialsEE
```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3-5
编译信息：无法查看
额外编译信息：无法查看
```

### 操作系统

- Linux

### 安装来源

- ArchLinuxCN - 稳定版

### 已安装的插件、版本及安装来源

无

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
#1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032
全是 Manjaro 用户，你们啊，哎……

https://t.me/qv2ray/386620

关于 Manjaro、KaOS 等基于 pacman 软件管理器等操作系统的安装 Qv2ray 的说明：

很多人并不知道，一个开源操作系统的衍生版本并不等于原始开源操作系统——衍生版本的操作系统有着自己的定制、打包计划与更新计划，它们的更新进度或快于原始系统（比如 Ubuntu、Kali Linux 的更新速度要比 Debian 快），也可能慢于原始系统（比如 Manjaro 的更新速度要慢于 Arch Linux），也可能直接用了原始系统的软件源（比如 Linux Mint Debian Edition 直接用了 Debian 的源，ArchBang Linux、Artix Linux 直接用了全部或者部分 Arch Linux 的源）。

Qv2ray 在 Arch Linux CN 这个源里面提供了安装包，不过，由于该软件源是适配 Arch Linux 的，因此我们不建议 Arch Linux 衍生版的用户直接使用该软件源提供的安装包，除非你所用的衍生版直接用了 Arch Linux 的软件源。

Manjaro、KaOS 用户建议从 AUR 编译安装 Qv2ray，或者直接使用 AppImage 版本。

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/96583539-726b3d80-130f-11eb-815a-9997516eb9c8.png)
