### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by phantooom** [Qv2ray/Qv2ray#1047]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
启动报错
qv2ray: symbol lookup error: qv2ray: undefined symbol: _ZN4grpc13CreateChannelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_18ChannelCredentialsEE

## 如何触发这个 Bug：

1. 
2. 
3. 
4. 

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
qv2ray 2.6.3-5
v2ray 4.29.0-1
v2ray-domain-list-community 20200925052921-1
v2ray-geoip 202009230005-1

```

### 操作系统

- Linux manjaro kernel（5.8.11-1-MANJARO）

### 安装来源

- manjaro 稳定源

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
#1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032

https://t.me/qv2ray/386620
