### ISSUE TITLE
关于近期发布的 Ubuntu 20.10 的常见问题

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#1052]
### 怎么装？
从我们维护的 [Debian 源](https://qv2ray.net/debian/) 安装。
注意：配置仓库的时候务必选择 `unstable` 仓库。

### 从 16.04 / 18.04 / 20.04 等 LTS 版本升级上来，打不开了，怎么办？
重新从我们维护的 [Debian 源](https://qv2ray.net/debian/) 安装。
注意：配置仓库的时候务必选择 `unstable` 仓库。

### 不想从 Debian 源装 / 不会配源？
- 从 Snapcraft 安装，或
- 使用 AppImage 版本

### 还有问题？
加群：https://t.me/qv2ray

**Comment by MarksonHon** [comment]
补充几句：
1. 从 Snap 安装的终端命令
   `sudo snap install qv2ray`
   详情：<https://snapcraft.io/qv2ray>
   如果不想打命令，那也可以打开 Ubuntu 应用商店（Ubuntu Software) 安装。
2. 别用 sudo 运行 Qv2ray，否则系统代理都给 root 用户设置了，你当前用户压根没吃到系统代理。

**Comment by uniartisan** [comment]
> 补充几句：
> 
>     1. 从 Snap 安装的终端命令
>        `sudo snap install qv2ray`
>        详情：https://snapcraft.io/qv2ray
>        如果不想打命令，那也可以打开 Ubuntu 应用商店（Ubuntu Software) 安装。
> 
>     2. 别用 sudo 运行 Qv2ray，否则系统代理都给 root 用户设置了，你当前用户压根没吃到系统代理。

您好，我遇到了这样的问题： 我安装snap版本以后无法开机自启动，这是snap程序本身的限制吗，我查询了必应但是么有看到有人遇到了相同的问题。

**Comment by MarksonHon** [comment]
@uniartisan 请勿回复这个 issue，需要帮助建议加群。

**Comment by U-v-U** [comment]
This can be marked as resolved now.
