### ISSUE TITLE
功能请求：隐藏启动时的 “检测到Deepin”

### ISSUE THREAD

**Issue by spraysparks** [Qv2ray/Qv2ray#1057]
**简单描述你预期的解决方案？**
增加 “下次不再提醒” 复选框或按钮等

**你有想到其他比较容易实现的解决方案吗？**
直接改为仅在第一次启动时提醒，后续不再弹出

**Comment by DuckSoft** [comment]
请仔细阅读上下文：https://github.com/linuxdeepin/go-lib/issues/15
最新的开发分支已将此提示去除：https://github.com/Qv2ray/Qv2ray/pull/1050
