### ISSUE TITLE
使用疑问：「 如何使用命令行开关代理 」

### ISSUE THREAD

**Issue by wlmqpsc** [Qv2ray/Qv2ray#1058]
### 你想做啥？
*简要描述你的最原始的目的。*

在使用ss-tproxy创建透明代理时，需要用到开关代理的命令，qv2ray是否能够使用命令行开关代理，

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

直接使用v2ray-core来创建透明代理，但是这样本机使用v2ray就不方便了

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by U-v-U** [comment]
试试看

`qv2ray --disconnect`
`qv2ray --reconnect`

**Comment by wlmqpsc** [comment]
感谢，刚刚在命令行里输了一下，没注意到！
