### ISSUE TITLE
使用kde 5的manjaro 20.1.2 无法运行qv2ray，闪退

### ISSUE THREAD

**Issue by AshleyCry** [Qv2ray/Qv2ray#1059]
- [√] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
我使用的是kde5桌面的manjaro20.1.2，内核5.8,无论从pacman还是yay安装的qv2ray都无法运行，闪退，且没有报任何错误，作为我用过的linux上最好的同类软件，不能使用真的很苦恼

## 如何触发这个 Bug：

1. 无法启动，打开软件后可以看见软件在任务栏里面停留了一下然后就闪退不见了 

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

非连接问题

### 相关截图或日志
![image](https://user-images.githubusercontent.com/50860756/97158422-5c98c500-17b4-11eb-829b-7907f5958f65.png)
<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：

kf.kio.gui: Failed to register new cgroup: "app-qv2ray-49e364e59fdd4aa0a6d23ae100a47d74.scope" "org.freedesktop.DBus.Error.UnixProcessIdUnknown" "Process with ID 6344 does not exist."
```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3
编译信息：因为闪退所以看不到
额外编译信息：因为闪退所以看不到
```

### 操作系统

- Linux 使用kde5的manjaro20.1.2

### 安装来源

- ArchLinuxCN - 稳定版
- ArchLinux AUR - 稳定版

### 已安装的插件、版本及安装来源

没装过

## 附加信息

*请注意打码隐私相关信息。*

**Comment by U-v-U** [comment]
尝试在终端 Konsole 运行 qv2ray 看下输出？

**Comment by AshleyCry** [comment]
qv2ray: symbol lookup error: qv2ray: undefined symbol: _ZN4grpc13CreateChannelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_18ChannelCredentialsEE

**Comment by AshleyCry** [comment]
> 尝试在终端 Konsole 运行 qv2ray 看下输出？

qv2ray: symbol lookup error: qv2ray: undefined symbol: _ZN4grpc13CreateChannelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_18ChannelCredentialsEE

**Comment by ayalhw** [comment]
@AshleyCry  您都不看文档和历史issue的吗……

**Comment by MarksonHon** [comment]
@AshleyCry 请换用 AppImage 或 Snap 版本，或自行从 AUR 编译。Arch Linux CN 源并不适配 Manjaro。

**Comment by DuckSoft** [comment]
下载 https://mirrors.tuna.tsinghua.edu.cn/archlinux/community/os/x86_64/grpc-1.33.0-1-x86_64.pkg.tar.zst。
之后执行 `sudo pacman -U grpc-1.33.0-1-x86_64.pkg.tar.zst`。
一切正常。

**Comment by AshleyCry** [comment]
> 下载 [https://mirrors.tuna.tsinghua.edu.cn/archlinux/community/os/x86_64/grpc-1.33.0-1-x86_64.pkg.tar.zst。](https://mirrors.tuna.tsinghua.edu.cn/archlinux/community/os/x86_64/grpc-1.33.0-1-x86_64.pkg.tar.zst%E3%80%82)
> 之后执行 `sudo pacman -U grpc-1.33.0-1-x86_64.pkg.tar.zst`。
> 一切正常。



> 下载 [https://mirrors.tuna.tsinghua.edu.cn/archlinux/community/os/x86_64/grpc-1.33.0-1-x86_64.pkg.tar.zst。](https://mirrors.tuna.tsinghua.edu.cn/archlinux/community/os/x86_64/grpc-1.33.0-1-x86_64.pkg.tar.zst%E3%80%82)
> 之后执行 `sudo pacman -U grpc-1.33.0-1-x86_64.pkg.tar.zst`。
> 一切正常。
> 
> 根本原因：Arch Linux CN 优先保证 Arch Linux 用户的依赖版本，Manjaro 作为一个把 Arch 的包搁置几天到一个星期的发行版，落后就要挨炸。

成了！！感谢大佬！！！

**Comment by DuckSoft** [comment]
这些 Issue，全是你们 Manjaro 用户：#1047 #1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032
欢迎安装 Arch Linux。

**Comment by zpike** [comment]
下载不了啊 404

**Comment by MarksonHon** [comment]
@zpike 你来晚了，不送。

**Comment by DuckSoft** [comment]
Arch 早就更新到 1.33.2 了，Manjaro 害没更新啊？
欢迎安装 Arch Linux。

https://mirrors.tuna.tsinghua.edu.cn/archlinux/community/os/x86_64/grpc-1.33.2-1-x86_64.pkg.tar.zst
