### ISSUE TITLE
centos8下，有几个按钮显示空白

### ISSUE THREAD

**Issue by wtjperi2003** [Qv2ray/Qv2ray#1060]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 如何触发这个 Bug：

1. 主界面上的几个按钮显示空白，win10下面正常
2. 
3. 
4. 

### 相关截图或日志
![qv2ray](https://user-images.githubusercontent.com/10322892/97251374-b47e0d00-1842-11eb-8f87-a54cf7521feb.png)

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 
编译信息：
额外编译信息：
```

### 操作系统

- Linux

### 安装来源

- ArchLinuxCN - 稳定版

## 附加信息

*请注意打码隐私相关信息。*

**Comment by U-v-U** [comment]
@wtjperi2003 Known Issue, AppImage 里面丢了 svg 包

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/97251477-ea22f600-1842-11eb-8930-7d3cffe600fa.png)
预览版呀，当时发出来就有人报了，我们已经修复过了，但是已经发出来的版本是不能改的。
你可以等等正式版，或者自己 cherrypick 一下。
