### ISSUE TITLE
使用疑问：「 订阅中0项可用」

### ISSUE THREAD

**Issue by tongchangD** [Qv2ray/Qv2ray#1061]
在更新订阅遇到问题
近两天更新订阅数据时一直提示“订阅中0项可用”
 可我在网上是有订阅的，请问这是什么问题？

**Comment by MarksonHon** [comment]
@tongchangD [回复 GitHub]
请进群寻求帮助：<http://t.me/qv2ray>
你的 issue 将被关闭

**Comment by DuckSoft** [comment]
大概率考虑上游订阅地址被 DNS 污染。
详情请进群讨论。

**Comment by leoxxx** [comment]
https://github.com/Qv2ray/Qv2ray/issues/986
可以看一下这个。

**Comment by tongchangD** [comment]
> @tongchangD [回复 GitHub]
> 请进群寻求帮助：http://t.me/qv2ray
> 你的 issue 将被关闭

您好,您提供的这个网址点不进去.

**Comment by tongchangD** [comment]
> #986
> 可以看一下这个。

谢谢,我去看看

**Comment by tongchangD** [comment]
> 大概率考虑上游订阅地址被 DNS 污染。
> 详情请进群讨论。

好的,谢谢

**Comment by tongchangD** [comment]
我有两台电脑 一台是windows 10 一台是 linux ,昨天 开始 都更新不了订阅了 ,更新订阅时提示 ,"订阅中仅有0项可用,要继续吗".继续显示"0条中过滤出0条项目,要继续吗"
最终结果就是翻不了 了,好悲伤
求教 该怎么回归,我重新安装下载一个新版本的Qv2ray 有作用吗

**Comment by DuckSoft** [comment]
订阅上游被墙，属于上游的责，与 Qv2ray 无关。

**Comment by leoxxx** [comment]
如果你用了代理去更新那个订阅也显示0的话，那就是那个连接的订阅真的完了。就这几天SSR一下子快死光了。

**Comment by tongchangD** [comment]
> 如果你用了代理去更新那个订阅也显示0的话，那就是那个连接的订阅真的完了。就这几天SSR一下子快死光了。

这么悲伤，好难受
