### ISSUE TITLE
从右键菜单和分组管理器更新订阅的行为似有不一致

### ISSUE THREAD

**Issue by cubercsl** [Qv2ray/Qv2ray#1063]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

在主界面选择分组右击选择更新订阅后显示 0 项可用，但在组编辑器中的订阅设置中更新订阅时可以得到订阅信息。

## 如何触发这个 Bug：

1. 在主页面选择一个分组右击，选择更新订阅，显示 0 项可用。
2. 在组编辑器里打开订阅设置，选择更新订阅，订阅更新成功。

### 相关截图或日志

<details>

![image](https://user-images.githubusercontent.com/22931465/97387187-823ae100-1910-11eb-891c-e6a89a80fdab.png)

![image](https://user-images.githubusercontent.com/22931465/97387147-66cfd600-1910-11eb-9ad8-a5722a2208c8.png)

Update: 相关日志
右键菜单：
```
[COMMON-NETWORK]: Network error: 
[CORE-SUBSCRIPTION]: Found a subscription with less than 5 connections.
```

分组管理器：
```
[COMMON-NETWORK]: Unknown error
[CORE-CONNECTION]: Deduced alias: ******
[CORE-CONNECTION]: Deduced alias: ******
[CORE-SUBSCRIPTION]: Found a subscription with less than 5 connections.

[CORE-SUBSCRIPTION]: Filtered out less than 5 connections.
[QV2RAY-CORE]: Reused connection id from name: ******
[QV2RAY-CORE]: Reused connection id from name: ******
[QV2RAY-CORE]: Reused connection id from name: ******
```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.macos-latest
```

### 操作系统

- macOS

### 安装来源

- Homebrew Cask

## 附加信息

*请注意打码隐私相关信息。*

**Comment by LeoYoung** [comment]
可能因为机场服务器的内核版本较低，因而订阅配置的格式结构也不大一样

我之前发现过类似的问题

之后将v2ray-core的版本降级到2.7.5后恢复正常，请参考尝试一下

**Comment by cangyin** [comment]
Windows +1

**Comment by U-v-U** [comment]
Closing due to the fact they are actually the same.
