### ISSUE TITLE
功能请求：实现控制台版本的qv2ray

### ISSUE THREAD

**Issue by fkxxyz** [Qv2ray/Qv2ray#1065]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

由于我多数情况下是用命令行工作，甚至在tty里面没有图形界面，或者是远程ssh连接的远程服务器，在这些场景下无法实现管理订阅选择节点等等基本功能，只能在一个地方用qv2ray处理这些然后选好节点，将 ~/.config/qv2ray/generated/config.gen.json 拷贝到目标机器才能使用，非常麻烦，如果有命令行版本的qv2ray那么这将得到解决。

**简单描述你预期的解决方案？**

把核心功能代码抽出来，写成一个或若干个.so的库，然后实现一个命令行版本的控制程序，如 /usr/bin/qv2rayctl ，设计出它自身的命令行语法等，调用这个库来实现各个功能。

**你有想到其他比较容易实现的解决方案吗？**

暂未想到

**补充内容**

无

**Comment by U-v-U** [comment]
FYI: `-DQV2RAY_USE_WIDGETS=OFF` and `src/ui/cli/` 
不过肯定编译不出来就是了

**Comment by DuckSoft** [comment]
@fkxxyz 目前 Qv2ray 已经基本完成前后端的分离了，你可以在 CMake 构建的时候发现有一个叫 qv2ray-lib 的静态目标。
你只需要在这个库的基础上进行二次开发即可实现。

目前开发组成员忙于学业和工作，无法顾及，还请谅解。
