### ISSUE TITLE
使用疑问：「 设置了系统代理，但是访问ipip.net或者百度IP的时候，显示的ip地址还是没有变化 」

### ISSUE THREAD

**Issue by xhochipe** [Qv2ray/Qv2ray#1066]
「 设置了系统代理，但是访问ipip.net或者百度IP的时候，显示的ip地址还是没有变化 」
期望是：切换不同的代理,ip地址是变化的

**Comment by DuckSoft** [comment]
https://qv2ray.net/faq/#_2-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E7%99%BE%E5%BA%A6%E6%9F%A5%E8%AF%A2%E5%88%B0%E7%9A%84-ip-%E4%BB%8D%E7%84%B6%E5%9C%A8%E5%9B%BD%E5%86%85
