### ISSUE TITLE
ubuntun20.04.1无法使用，报错核心设置不正确

### ISSUE THREAD

**Issue by nongbin** [Qv2ray/Qv2ray#1067]
V2Ray 核心设置不正确。
错误如下: 
当前用户没有 V2Ray 核心控制文件的可执行权限。Qv2ray 尝试设置，但由于权限不足，操作已失败。

但是我给了执行权限，具体如何设置核心配置文件？

**Comment by DuckSoft** [comment]
https://qv2ray.net/getting-started/step2.html

此外，未按模板填写的 Issue，直接关闭。
