### ISSUE TITLE
使用疑问：「 每次启动都提示无法加载trojan插件 」

### ISSUE THREAD

**Issue by onlyJinx** [Qv2ray/Qv2ray#1068]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

每次开机都会报错, 然后点击OK之后软件完全能正常使用, 不知道是什么原因 , 请问有解决方法吗? 谢谢

![image](https://user-images.githubusercontent.com/21324835/97771992-6a1bc980-1b7d-11eb-9328-75a5e9f92154.png)

![image](https://user-images.githubusercontent.com/21324835/97772006-81f34d80-1b7d-11eb-9ade-9def4fd7d586.png)

### 你想做啥？
*简要描述你的最原始的目的。*

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by DuckSoft** [comment]
插件目录是给你放 qv2ray 插件用的，不是给你放其他核心用的。
把trojan-go.exe换个地方放。

**Comment by onlyJinx** [comment]
明白了，谢谢啦
