### ISSUE TITLE
Arch稳定版仓库出现了. qv2ray: symbol lookup error: 

### ISSUE THREAD

**Issue by glide-the** [Qv2ray/Qv2ray#1069]
前段时间更新后出现了这个问题，在https://aur.archlinux.org/packages/qv2ray/看到了一楼叙述的解决办法，没有验证是不是如一楼所说的打包失败问题，找到安装之前打包的qv2ray-dev-git-2.6.3.5899.r2494.0ab039cc-1-x86_64.pkg.tar.xz没有此问题
![image](https://user-images.githubusercontent.com/16206043/97783833-37052480-1bd5-11eb-9e0c-290a0b5fbe39.png)

**Comment by DuckSoft** [comment]
重新构建。

**Comment by glide-the** [comment]
>__<

**Comment by DuckSoft** [comment]
本来这个 Issue 没有按照模板填写，我可以直接关闭，但我一句话也不说也不太好：

- 如果你是 Arch Linux 且从 Arch Linux CN 获取软件包：滚动升级。
- 如果你是从 AUR 获取软件包：重新构建。
- 如果你是 Manjaro 且从 Arch Linux CN 获取软件包：请参考 #1059 #1047 #1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032 等 Issue，建议放弃幻想，欢迎安装 Arch Linux。

**Comment by glide-the** [comment]
我只是没有搜索到相关的issue然后提了一个。
