### ISSUE TITLE
使用疑问：「 流控是否支持xtls-rprx-direct 」

### ISSUE THREAD

**Issue by onlyJinx** [Qv2ray/Qv2ray#1070]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

我在流控这里输入xtls-rprx-direct点击保存之后会被自动替换成xtls-rprx-origin, 使用的是2.7.0的版本

![image](https://user-images.githubusercontent.com/21324835/97796079-b122c100-1c48-11eb-9a65-26a218385ad4.png)

### 你想做啥？
*简要描述你的最原始的目的。*

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by U-v-U** [comment]
那是旧版本了，直接填写即可
旧版有个 bug ，填写进去的内容无法再次显示，你可以通过 `编辑json` 验证

**Comment by onlyJinx** [comment]
试了一下还真的, 编辑json后可以了, 谢谢啦~
