### ISSUE TITLE
更新后不能运行qv2ray: symbol lookup error: qv2ray: undefined symbol: 

### ISSUE THREAD

**Issue by 1322739583** [Qv2ray/Qv2ray#1073]
## 简单描述这个 Bug:
不能运行，运行报下面的错误。
qv2ray: symbol lookup error: qv2ray: undefined symbol: _ZN4grpc13CreateChannelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_18ChannelCredentialsEE
我是通过yay安装的。之前是可以用的，更新上个版本后就不能用了。

 
 
## 系统信息
 OS: Manjaro 20.1.2 Mikah
 Kernel: x86_64 Linux 5.8.16-2-MANJARO
 Uptime: 20h 26m
 Packages: 1544
 Shell: zsh 5.8
 Resolution: 2390x768
 DE: KDE 5.74.0 / Plasma 5.19.5
 WM: KWin
 GTK Theme: Breath [GTK2/3]
 Icon Theme: Flatery-Yellow
 Disk: 160G / 247G (69%)
 CPU: Intel Core i5-3210M @ 4x 3.1GHz [71.0°C]
 GPU: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
 RAM: 8299MiB / 11860MiB

**Comment by DuckSoft** [comment]
请参考 #1069 #1059 #1047 #1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032 等 Issue，建议放弃幻想，欢迎安装 Arch Linux。

**Comment by 1322739583** [comment]
谢谢 已经解决！   有相同问题的小伙伴参考#1059
