### ISSUE TITLE
Windows版本插件管理器中的打开本地插件目录与真实目录不一致

### ISSUE THREAD

**Issue by SekiBetu** [Qv2ray/Qv2ray#1075]
- [√] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
插件管理器中的打开本地插件目录与真实目录不一致

## 如何触发这个 Bug：

1. 打开Qv2ray
2. 打开插件管理器
3. 点击打开本地插件目录
4. 跳转的目录错误，不是本地的真实插件目录

### 相关截图或日志
![image](https://user-images.githubusercontent.com/38283893/98153242-c73fb400-1eca-11eb-8d9c-d7dce11cb7b2.png)
点击打开后
![image](https://user-images.githubusercontent.com/38283893/98153346-f35b3500-1eca-11eb-93db-bd2db8fe0ce0.png)
此为上述功能打开的目录，为空目录
![image](https://user-images.githubusercontent.com/38283893/98153320-e63e4600-1eca-11eb-9ae3-dbefc151a4dd.png)
此为真实的目录，有插件，与上述打开的路径不一致

**Comment by EpLiar** [comment]
Windows 2.7.0-pre1:6039 无法复现，请提供更多信息

**Comment by SekiBetu** [comment]
https://github.com/Qv2ray/Qv2ray/blob/912fe1b040544214b2f56c52e6da9fdb43c11f26/src/ui/windows/w_PluginManager.cpp#L122
此处不应加QV2RAY_CONFIG_DIR

**Comment by SekiBetu** [comment]
懂了，原来两处的plugins目录都能加载插件，为何要分成两个文件夹

**Comment by jing5460** [comment]
两处都试过了,无法更新订阅应该不是这里的问题
