### ISSUE TITLE
使用疑问：「 退出Qv2ray后，v2ray-core/v2ray 会一直运行？ 」

### ISSUE THREAD

**Issue by ryshi** [Qv2ray/Qv2ray#1077]
OS Version : MacOS 10.15.7
Qv2ray Version : 2.6.3:5840

现象，启动Qv2ray正常代理后退出，发现 `v2ray-core/v2ray` 会一直后台运行，是否有特别考虑？能否随Qv2ray一起关闭？

**Comment by DuckSoft** [comment]
@ryshi 那是 v2rayU 的，和我们无关。

**Comment by DuckSoft** [comment]
> 发现 v2ray-core/v2ray 会一直后台运行
建议自己看一下进程树，到底是谁开的。
Qv2ray 自己不会留进程的。

**Comment by ryshi** [comment]
确实，其他客户端残留……抱歉抱歉

**Comment by U-v-U** [comment]
那这是什么客户端的呢

**Comment by ryshi** [comment]
@U-v-U 是V2rayU的，跟Qv2ray无关
