### ISSUE TITLE
Qv2ray节点连接成功后不能上墙外地址

### ISSUE THREAD

**Issue by jiandandian2** [Qv2ray/Qv2ray#1079]
系统：ubuntu 18
远程vnc
![屏幕快照 2020-11-06 上午9 56 51](https://user-images.githubusercontent.com/33227739/98336106-42c37180-2041-11eb-87ba-61b283952d1c.png)

尝试使用命令： curl -sSLvv -x http://127.0.0.1:8888 https://www.google.com/
<img width="813" alt="屏幕快照 2020-11-06 下午3 10 56" src="https://user-images.githubusercontent.com/33227739/98336673-4c99a480-2042-11eb-8511-5de79baa1734.png">

Qv2ray配置：
<img width="904" alt="屏幕快照 2020-11-06 下午3 11 28" src="https://user-images.githubusercontent.com/33227739/98336732-689d4600-2042-11eb-9b2a-06852dbfa1f4.png">

**Comment by DuckSoft** [comment]
8889

**Comment by jiandandian2** [comment]
<img width="1662" alt="屏幕快照 2020-11-06 下午4 23 31" src="https://user-images.githubusercontent.com/33227739/98343518-e8301280-204c-11eb-864d-62ca2f940cca.png">

ping google没有反应。

**Comment by flyawayazure** [comment]
@jiandandian2 正常情况下代理一般情况下无法代理ICMP，和qv2ray无关
