### ISSUE TITLE
使用疑问：「 dns解析错误 」

### ISSUE THREAD

**Issue by yidasanqian** [Qv2ray/Qv2ray#1083]
### 你想做啥？
*简要描述你的最原始的目的。*
dns正确解析

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
dns设置成114.114.114.114还是解析错误

### 其他要补充的信息？
*在此附加其他需要补充的信息。*
<img width="527" alt="fail to parse responded DNS udp" src="https://user-images.githubusercontent.com/10655188/98433395-b62cb800-2101-11eb-822c-dba6db2ab045.png">

**Comment by DuckSoft** [comment]
？？？
