### ISSUE TITLE
功能请求：自定义路由优先级

### ISSUE THREAD

**Issue by BoBppy** [Qv2ray/Qv2ray#1084]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

-----------------

**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

请尽可能清晰简洁地描述问题。

尝试在json中编辑，然而开关节点就会恢复默认的优先级（

**简单描述你预期的解决方案？**

请尽可能清晰简洁描述问题。

高级路由设置中可以自定义优先级
1.拖动排序或者其他什么的有gui排列方式

**你有想到其他比较容易实现的解决方案吗？**

请简单清晰描述。 

2.增加自定义routing的开关

**补充内容**
请在此附加任何你认为对你的描述有所帮助的内容。

**Comment by DuckSoft** [comment]
![截屏2020-11-07 下午4 15 25](https://user-images.githubusercontent.com/7822648/98436196-7e7b3b80-2114-11eb-911c-38ff4abe9be7.png)
![截屏2020-11-07 下午4 14 29](https://user-images.githubusercontent.com/7822648/98436198-8044ff00-2114-11eb-84bc-75de28ae1fd3.png)

**Comment by BoBppy** [comment]
学不会这个，我爬了

**Comment by cangyin** [comment]
@BoBppy  入群，抱大佬的腿。包教包会

**Comment by BoBppy** [comment]
@cangyin 啥

**Comment by DuckSoft** [comment]
诸位，别把 GitHub Issue 当成论坛了。
先锁帖了。

至于群，自己去文档看。
