### ISSUE TITLE
qv2ray在图形界面下无法启动, 命令行启动失败

### ISSUE THREAD

**Issue by TD-Sky** [Qv2ray/Qv2ray#1085]
## Bug简述:
当我通过命令行启动qv2ray时, 会弹出一个提示"symbol lookup error", 于是我无法启动软件. 
我也尝试从GUI打开其qv2ray, 但是无响应. 
之前安装过v2ray, 能够正常打开, 但是更新后却打不开了, 所以我认为是版本(2.6.3-6)问题, 但我没有能力修复它.

## 触发Bug：

```bash
$ qv2ray
qv2ray: symbol lookup error: qv2ray: undefined symbol: _ZN4grpc13CreateChannelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_18ChannelCredentialsEE
```

## 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

并不是连接问题, 我也尝试使用v2ray, 但那上面连接失败了, 所以我寻求qv2ray的解决方案. 

## 系统信息

```
操作系统: Linux
版本: Manjaro 20.1.2 Mikah
内核: x86_64 Linux 5.8.16-2-MANJARO
桌面环境: KDE 5.74.0 / Plasma 5.19.5
```
#### 安装来源

- ArchLinuxCN - 稳定版

**Comment by DuckSoft** [comment]
请参考 #1073 #1069 #1059 #1047 #1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032 等 Issue，建议放弃幻想，欢迎安装 Arch Linux。
