### ISSUE TITLE
使用疑问：「 trojan协议可以不要插件吗？ 」

### ISSUE THREAD

**Issue by jacklee789** [Qv2ray/Qv2ray#1087]
v2raycore已经原生支持trojan协议，v2rayn可以直接使用trojan协议，为什么qvr2ray还需要插件才能使用trojan协议？

**Comment by MarksonHon** [comment]
@jacklee789 V2Ray对UDP的处理还有些问题，所以还是要用Trojan插件。而且，我们没法保证每个人都用了最新的内核。

**Comment by EpLiar** [comment]
如果你会手写 json 配置文件，可以使用 core 的 trojan 协议

**Comment by jacklee789** [comment]
谢谢解答。
