### ISSUE TITLE
使用疑问：「为什么比v2rayN慢」

### ISSUE THREAD

**Issue by mozhu69** [Qv2ray/Qv2ray#1088]
同一个vps，用v2rayN跑48M，用Q2ray只有22M。为什么？？？协议是VLESS+tcp+xtls

**Comment by rprx** [comment]
v2ray-core 的流量统计实现是加一层 Conn，这会导致无法用到 ReadV，关掉流量统计试试，v2rayNG 应该也存在此问题。

**注意：不显示不代表关掉了。**

之前测试开了流量统计 VMess 吞吐量会骤减，是一样的原理。不光流量统计，只要是多一层 Conn 都会这样。

（XTLS Direct Mode 的 Conn 可以穿透，所以不算多一层 Conn，可以用 ReadV，除非又加了浏览统计等）

**Comment by DuckSoft** [comment]
https://qv2ray.net/faq/#_1-%E6%84%9F%E8%A7%89-qv2ray-%E6%89%93%E5%BC%80%E7%BD%91%E9%A1%B5-%E5%88%87%E6%8D%A2%E8%BF%9E%E6%8E%A5%E7%9A%84%E9%80%9F%E5%BA%A6%E6%AF%94%E5%85%B6%E4%BB%96%E4%BB%A3%E7%90%86%E8%BD%AF%E4%BB%B6%E6%85%A2%E5%BE%97%E5%A4%9A

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/98489717-2b1b0180-226a-11eb-91d2-153fd4fab86d.png)
在首选项中禁用 API 子系统，即可关闭流量统计功能。

**Comment by rprx** [comment]
2020.11.12 更新（勘误）：

v4.32.1 版本的 VLESS XTLS Direct Mode 自动切换到 ReadV 后会绕过读数据时的流量统计功能（可能会修复）

但裸 VMess 等仍然存在开启流量统计后 ReadV 失效的问题，不过它们的 ReadV 本就只限制于桌面端，而不像 XTLS 的是全平台。

**Comment by rprx** [comment]
目前暂不推荐开启流量统计，测试各个传输组合的简单结论是普遍明显降性能，最多的降了 75%，且表现出了反规律，烧脑。

**Comment by rprx** [comment]
https://github.com/v2fly/v2ray-core/commit/f06ede1bc10be37acc18b6243d43d805c7a36c0b

目前暂不推荐开启流量统计，测试多个传输组合的简单结论是普遍明显降性能，最多的降了 75%，且表现出了反规律，烧脑。

研究的后续进展不更新到此 issue 了，可能在 https://github.com/v2fly/v2ray-core/issues
