### ISSUE TITLE
Subscription: zero nodes

### ISSUE THREAD

**Issue by hamedsbt** [Qv2ray/Qv2ray#1089]
Hello,

Several days ago, I tried to update my subscriptions but all of them return 0 result !!!
So I tested the links with browser and all of them has result.

version: 2.6.3:5840
V2Ray version: 4.31.0
Sub example:  [link](https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent)

Thank you for your awesome project.

**Comment by U-v-U** [comment]
@hamedsbt Did you try "Qv2ray Proxy" in the Preference Window?

**Comment by cangyin** [comment]
mark #1063

**Comment by DuckSoft** [comment]
It's DNS Record Pollution. You could either:

 - Proxy Your Requests by using "Qv2ray Proxy" options.
 - Use an Reverse Proxy Service. eg: 
    - For link you've provided: https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent
    - Subscribe here instead: https://raw.fastgit.org/voken100g/AutoSSR/master/recent

**Comment by hamedsbt** [comment]
> @hamedsbt Did you try "Qv2ray Proxy" in the Preference Window?

No.

**Comment by hamedsbt** [comment]
> It's DNS Record Pollution. You could either:
> 
> * Proxy Your Requests by using "Qv2ray Proxy" options.
> * Use an Reverse Proxy Service. eg:
>   
>   * For link you've provided: https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent
>   * Subscribe here instead: https://raw.fastgit.org/voken100g/AutoSSR/master/recent

Thank you for your advice, But I'm using dnsCrypt on windows an as I sad the browser can resolve the sub link without proxy. also I tested resolve dns from v2ray-proxy but it does not works (same result). 
My issue not resolved :(

**Comment by DuckSoft** [comment]
I noticed that your nodes are all SSR nodes. Have you installed QvPlugin-SSR?

**Comment by DuckSoft** [comment]
For 2.6.x, try use QvPlugin-SSR provided here: https://github.com/Qv2ray/QvPlugin-SSR/releases/tag/v2.0.3
You may want to read documentation for instructions to set it up.
If you have any other questions, you can join us on Telegram at https://t.me/qv2ray_intl.

**Comment by DuckSoft** [comment]
Please let us know if there's any update of your situation.

**Comment by hamedsbt** [comment]
> I noticed that your nodes are all SSR nodes. Have you installed QvPlugin-SSR?
> Since SSR is not supported by V2Ray natively, you have to grab a plugin to support it.
> Also the link protocol decoder is also located in the plugin. If you don't have the plugin, Qv2ray will simply ignore those nodes.
> After configuring QvPlugin-SSR, your subscription worked perfect on my machine.
> 
> You should have a read here: https://qv2ray.net/en/plugins/usage.html#what-is-a-plugin

It worked several day ago, I properly installed requirements.

**Comment by hamedsbt** [comment]
"Importing SSR Subscription will get zero nodes" isn't imply the issue, because all type ss,ssr,vmess,trojan... of subscription has  get zero nodes (same result).

**Comment by DuckSoft** [comment]
It's weird then. You can switch to Qv2ray log by right-click on Log window and choose "Switch to Qv2ray Log".
Reproduce the problem and see what's been output in the logs.

**Comment by hamedsbt** [comment]
Qv2ray Log for https://raw.fastgit.org/voken100g/AutoSSR/master/recent:
```
[COMMON-NETWORK]: Network error: 
[CORE-SUBSCRIPTION]: Found a subscription with less than 5 connections.

[CORE-SUBSCRIPTION]: Filtered out less than 5 connections.
```

**Comment by DuckSoft** [comment]
Check "Qv2ray Proxy" in Preference Window. Change this setting to "Use Customized Proxy", Click OK. 
Then reopen Preference Window, set this back to "Do Not Use".

I suspect there's a queer thing happened in the setting entry.

**Comment by hamedsbt** [comment]
![image](https://user-images.githubusercontent.com/7298328/98514423-52210580-2261-11eb-9e92-05977f83f44f.png)

```
[BASE-MESSAGING]: Emitting signal: UPDATE_COLORSCHEME

[BASE-MESSAGING]: Emitting signal: UPDATE_COLORSCHEME

[COMMON-NETWORK]: Network error: 
[CORE-SUBSCRIPTION]: Found a subscription with less than 5 connections.

[CORE-SUBSCRIPTION]: Filtered out less than 5 connections.
```

**Comment by DuckSoft** [comment]
Weird. There used to be a situation where user added some extra characters in subscription URI. You can have a check.

Would you please try use "Custom Proxy"? Here's the instructions:
1. Connect to a working node.
2. Check out your HTTP inbound port in Preferences -> Inbound Settings -> HTTP -> Port.
3. Change Qv2ray Proxy to Custom proxy. Replace the port with your HTTP inbound port. Click OK to save.
4. Open Group Manager and update the subscription.

If nothing works, I will investigate into this after today's job. 
Thank you for the precious feedback!

**Comment by hamedsbt** [comment]
![image](https://user-images.githubusercontent.com/7298328/98517721-44ba4a00-2266-11eb-8611-e259d40b4775.png)

```
[BASE-MESSAGING]: Emitting signal: UPDATE_COLORSCHEME

[BASE-MESSAGING]: Emitting signal: UPDATE_COLORSCHEME

[COMMON-NETWORK]: Network error: 
[CORE-SUBSCRIPTION]: Found a subscription with less than 5 connections.

[CORE-SUBSCRIPTION]: Filtered out less than 5 connections.

[BASE-MESSAGING]: Emitting signal: UPDATE_COLORSCHEME
```

**Comment by DuckSoft** [comment]
Hmmm... We've been in touch in Telegram Group.
I'll present a workaround: There's a hidden feature of Qv2ray, which allows you to subscribe from local file.
The network stack seems broken, but you can still use this trick to subscribe from files:

Example: `file:///c:/something.txt`
