### ISSUE TITLE
使用疑问：「 使用vnc作为QPA platform时无窗口管理 」

### ISSUE THREAD

**Issue by Provissy** [Qv2ray/Qv2ray#1093]
### 你想做啥？
Qv2ray运行在headless机器上, 需要进行远端控制. qt支援vnc作为一个QPA Platform, 可以不需要借助另外的display server即可远端显示与进行控制.

### 你目前试了啥？
Tested on `Ubuntu 20.04` and `debian Bullseye`

Qv2ray从官方提供的apt源安装, 安装时已自动解决dependencies

Start Qv2ray with:
```
qv2ray -platform vnc -qws -display VNC:0
```

结果是可以成功执行, but...
![Screenshot 2020-11-12 061026](https://user-images.githubusercontent.com/9506924/98864789-c819ac80-24ad-11eb-8ac9-b700422efa82.png)
![Screenshot 2020-11-12 061245](https://user-images.githubusercontent.com/9506924/98865010-1929a080-24ae-11eb-9ddb-a88daa0091f9.png)

看起来是没有Window Manager呢, 仔细看docs的话会看到...
From https://doc.qt.io/qt-5/embedded-linux.html
___Note: As of Qt 5.0, Qt no longer has its own window system (QWS) implementation. For single-process use cases, the Qt Platform Abstraction is a superior solution; multi-process use cases are supported through Wayland.___

Qt4的demo是这样的
https://doc.qt.io/archives/qt-4.8/qt-embedded-vnc.html

抱歉, 本人对qt学识较浅, 请问怎样才能达致类似qt4中qt-embedded-vnc 那样的效果呢? 看起来Qt是把window managing的工作交给Qtwayland了, 有没有可能让qt app自己作为自己的compositor而不用一个额外的compositor呢(比如weston)

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by MarksonHon** [comment]
@Provissy 就目前的情况来看，Qt5 是不自带窗口管理器系统了，所以建议你搭配个 OpenBox 来使用。

**Comment by Provissy** [comment]
> @Provissy 就目前的情况来看，Qt5 是不自带窗口管理器系统了，所以建议你搭配个 OpenBox 来使用。

谢谢答复!

到处搜寻了挺久, 看来的确只能依赖于额外的窗口管理系统了, 那就用个weston凑合吧. X的窗口管理程序都是远古产物了, 不是很想用, 可惜weston不支援tray icon...
