### ISSUE TITLE
使用疑问：「 在树莓派os上执行AppImage失败 」

### ISSUE THREAD

**Issue by BA-NANA** [Qv2ray/Qv2ray#1095]
问题：执行文件失败，在当前目录生成了一个乱码名文件，不知道是什么原因，恳请大神赐教！
图片：

![ADY8 OEJU)WPE3G$@3MPFUD](https://user-images.githubusercontent.com/45927088/99030424-ef58a280-25af-11eb-8f97-99a3aa23ee22.png)

报错信息如下：
./Qv2ray.v2.6.3.linux-x64.AppImage: 1: ./Qv2ray.v2.6.3.linux-x64.AppImage: �: not found
./Qv2ray.v2.6.3.linux-x64.AppImage: 1: ./Qv2ray.v2.6.3.linux-x64.AppImage: �b�: not found
./Qv2ray.v2.6.3.linux-x64.AppImage: 1: ./Qv2ray.v2.6.3.linux-x64.AppImage: ELFAI: not found
./Qv2ray.v2.6.3.linux-x64.AppImage: 3: ./Qv2ray.v2.6.3.linux-x64.AppImage: Syntax error: "(" unexpected

**Comment by U-v-U** [comment]
AppImage 是 x86_64 架构，不能在 ARM 架构上运行

**Comment by BA-NANA** [comment]
> AppImage 是 x86_64 架构，不能在 ARM 架构上运行

谢谢，原来是这样，那么Qv2ray有办法在ARM架构上运行吗？

**Comment by U-v-U** [comment]
可以使用 Snap 商店

**Comment by Provissy** [comment]
https://snapcraft.io/install/qv2ray/raspbian

**Comment by BA-NANA** [comment]
> 可以使用 Snap 商店



> https://snapcraft.io/install/qv2ray/raspbian


感谢大神们的解答，我使用snap安装完后执行 qv2ray 命令时发现有报错，不知道是什么原因呢？报错如下所示：
![1J_8JZT6A X2~5%A 18V0 X](https://user-images.githubusercontent.com/45927088/99035320-62ffad00-25ba-11eb-816e-cffd22c12da3.png)

**Comment by DuckSoft** [comment]
这个看起来是发霉派自带的那个什么 Raspberrian OS 的问题，他没有按照平台打包规范来，所以无法使用 Snap 的应用程序。
安装 Debian 等规范操作系统可解。

**Comment by Provissy** [comment]
建议换用其它作业系统如Ubuntu或Debian, 如果要继续用Raspberry pi OS的话可以自己build一份, 不是很难的

https://qv2ray.net/hacking/manuallybuild.html

安装Ubuntu系统的话网路上华文教程非常多, 也是非常简单的.
