### ISSUE TITLE
使用疑问：「 这个信息是在请求吗？会泄露配置信息吗？ 」

### ISSUE THREAD

**Issue by jcyuan** [Qv2ray/Qv2ray#1096]
![11111111](https://user-images.githubusercontent.com/850854/99035285-44011b00-25ba-11eb-9efd-9eeb5c93c6ad.png)

启动后连接trojan-go时打印的这个。这个信息是在以配置信息请求这个链接还是只是单纯的打印呢？
因为后面附加了整个连接配置信息，所以有这个疑问。谢谢。

**Comment by U-v-U** [comment]
Qv2ray 会传递链接信息给 Trojan-go 核心，这里的 `github.com/p4gefau1t/....` 不是域名，而是 Trojan-Go 的包名
不必慌张，并没有实际网络请求

**Comment by jcyuan** [comment]
了解了，谢谢。
