### ISSUE TITLE
Feature Request: 即使开启自动连线也在Qv2ray启动后展示窗口

### ISSUE THREAD

**Issue by Provissy** [Qv2ray/Qv2ray#1097]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

当前如果在Preferences里开启自动连线(Auto Connect), 那么每次Qv2ray启动后不会展示窗口而是隐藏至tray icon, 这导致:
* 在不带有tray的桌面环境中(eg. embedde linux), 无法通过GUI呼出界面, 需要再次执行Qv2ray以激活窗口.
* 每次启动Qv2ray都需要额外呼出视窗.

当前, __Launch at Login__ 与 __Auto Connect__ 是分开的, 所以不会导致用户开机后出现Qv2ray视窗.

**简单描述你预期的解决方案？**

增加一个选项于Preferences -> Auto Connect部分, 允许在起动后展示窗口.

**补充内容**

N/A

**Comment by DuckSoft** [comment]
Current Workaround: Qv2ray runs in user-level Single Instance mode. Simply run Qv2ray again to call out the Window.

We will be happy if someone can do us a pull request on this.

**Comment by Provissy** [comment]
> Current Workaround: Qv2ray runs in user-level Single Instance mode. Simply run Qv2ray again to call out the Window.
> 
> We will be happy if someone can do us a pull request on this.

Yes, I was forced to do this all the time ;) That is why this featured request is filed.

I didn't know this mechanism at first and wondered why the window is not showing up, wasted some time finding out why...
