### ISSUE TITLE
使用疑问：「重大安全隐私疑问：「出于什么目的Qv2ray要访问我的通讯录和提醒事项？」  」

### ISSUE THREAD

**Issue by liubuzhu-you** [Qv2ray/Qv2ray#1100]
**mac安装自动获取通讯录和提醒事项隐私权限？
这是出于什么目的这样做？请相关开发者解释下？
注意⚠️：
用过macOS都知道，这两个权限用户自己是无法添加的！
只有程序自己发起请求并通过！也可能是程序发起这样的请求后，我不经意点了同意！
我只想说：
细思极恐！**
<img width="780" alt="截屏2020-11-14 18 30 50" src="https://user-images.githubusercontent.com/74452794/99145460-10052300-26aa-11eb-85cb-a505136ff1d5.png">
<img width="780" alt="截屏2020-11-14 18 31 01" src="https://user-images.githubusercontent.com/74452794/99145461-11365000-26aa-11eb-95e9-552e3c65b2f1.png">

**Comment by Sinofine** [comment]
您审计一下源码？您可以看看审计后的源码在您的机器上编译产物是否有相同的行为。

**Comment by MarksonHon** [comment]
<img width="829" alt="图片" src="https://user-images.githubusercontent.com/50002150/99145559-e6003080-26aa-11eb-9f1c-0f55f768056c.png">
无法复现

**Comment by U-v-U** [comment]
唯一的可能就是
你把 vcore 或者什么东西放在对应位置了

**Comment by liubuzhu-you** [comment]
忘记什么版本了，2020年8月26日GitHub下载的！
今天检查才发现！
<img width="644" alt="截屏2020-11-14 18 57 30" src="https://user-images.githubusercontent.com/74452794/99145639-750d4880-26ab-11eb-89e5-ffc60761c9ad.png">

**Comment by KevinZonda** [comment]
欢迎审计Qv2ray原始码以验证猜想

**Comment by FANminiworld** [comment]
@liubuzhu-you 请详细说明应用程序版本与下载地址

**Comment by liubuzhu-you** [comment]
> 欢迎审核Qv2ray原始码以验证猜想

好的，有时间会仔细审查一遍！暂时没有深入分析！系统有几十个软件，就发现一个清理软件要求访问通讯录和qv2ray。
所以发来大家讨论下！

**Comment by MarksonHon** [comment]
你现在把权限关掉吧，如果哪天再提示说要权限就留意下，记得把日志、截图发这里，另外看下是否有软件恶意注入了，建议删除Qv2ray与内核后再安装。

**Comment by liubuzhu-you** [comment]
> 程序

https://github.com/Qv2ray/Qv2ray/releases/download/v2.6.3/Qv2ray-v2.6.3.macOS-x64.dmg

**Comment by Sinofine** [comment]
您能找到当时的下载文件吗？

**Comment by liubuzhu-you** [comment]
> 您现在把权限关掉吧，如果哪天再提示说要权限就留意下，记得把日志，截图发到这里，另外看下是否有软件恶意注入了，建议删除Qv2ray与内核后再安装。

是的，已经这样做！后期会分析！

**Comment by liubuzhu-you** [comment]
> 您能找到当时的下载文件吗？

找了一下，原始压缩包删除了。但是，我声明下。
我不会在GitHub以外的地方下载此类软件！

**Comment by U-v-U** [comment]
master 分支源码可以在此处进行交互式审查： https://code.qv2ray.net/master/qv2ray/
dev 分支源码可以在此处进行交互式审查： https://code.qv2ray.net/dev/qv2ray/
version-v2 分支源码可以在此处进行交互式审查： https://code.qv2ray.net/version-v2/qv2ray/

对于非交互式审查，你可以直接在 GitHub 查询
你的版本对应 commit 应该是 https://github.com/Qv2ray/Qv2ray/commit/912fe1b040544214b2f56c52e6da9fdb43c11f26

Release 对应信息是 https://api.github.com/repos/Qv2ray/Qv2ray/releases/tags/v2.6.3
其中请注意 Uploader 都是 github-action
![image](https://user-images.githubusercontent.com/59914293/99145844-f9140000-26ac-11eb-96ab-698025a8f0cb.png)

另外这个 commit 的 CI 配置文件在这里，你可以自行验证
https://github.com/Qv2ray/Qv2ray/blob/912fe1b040544214b2f56c52e6da9fdb43c11f26/.github/workflows/build-qv2ray-cmake.yml

Qv2ray 不会在编译时对代码进行任何修改

**Comment by liubuzhu-you** [comment]
> master各个类别代码可以在此处进行相互审查：[https](https://code.qv2ray.net/master/qv2ray/) :
> //code.qv2ray.net/master/qv2ray/ dev分支继承可以在此处进行相互审查：[https](https://code.qv2ray.net/dev/qv2ray/) ://code.qv2ray.net/dev/ [qv2ray /](https://code.qv2ray.net/dev/qv2ray/)
> version-v2分支源码可以在此处进行相互审查：[https](https://code.qv2ray.net/version-v2/qv2ray/) ://code.qv2ray.net/version-v2/qv2ray/[](https://code.qv2ray.net/version-v2/qv2ray/)
> 
> 对于非一致审查，你可以直接在GitHub查询
> 你的版本对应commit应该是[912fe1b](https://github.com/Qv2ray/Qv2ray/commit/912fe1b040544214b2f56c52e6da9fdb43c11f26)
> 
> 发布对应信息是https://api.github.com/repos/Qv2ray/Qv2ray/releases/tags/v2.6.3
> 其中请注意上传者是github-action
> ![图片](https://user-images.githubusercontent.com/59914293/99145844-f9140000-26ac-11eb-96ab-698025a8f0cb.png)
> 
> 另外这个commit的CI配置文件在这里，您可以自行验证
> https://github.com/Qv2ray/Qv2ray/blob/912fe1b040544214b2f56c52e6da9fdb43c11f26/.github/workflows/build-qv2ray-cmake.yml
> 
> Qv2ray不会在编译时对代码进行任何修改
> 
> 我们欢迎任何人对Qv2ray进行代码审查

<img width="801" alt="截屏2020-11-14 19 12 30" src="https://user-images.githubusercontent.com/74452794/99145884-750e4800-26ad-11eb-92b7-80783bef5370.png">

看了安装文档。的确是2.6.3

**Comment by liubuzhu-you** [comment]
> master各个类别代码可以在此处进行相互审查：[https](https://code.qv2ray.net/master/qv2ray/) :
> //code.qv2ray.net/master/qv2ray/ dev分支继承可以在此处进行相互审查：[https](https://code.qv2ray.net/dev/qv2ray/) ://code.qv2ray.net/dev/ [qv2ray /](https://code.qv2ray.net/dev/qv2ray/)
> version-v2分支源码可以在此处进行相互审查：[https](https://code.qv2ray.net/version-v2/qv2ray/) ://code.qv2ray.net/version-v2/qv2ray/[](https://code.qv2ray.net/version-v2/qv2ray/)
> 
> 对于非一致审查，你可以直接在GitHub查询
> 你的版本对应commit应该是[912fe1b](https://github.com/Qv2ray/Qv2ray/commit/912fe1b040544214b2f56c52e6da9fdb43c11f26)
> 
> 发布对应信息是https://api.github.com/repos/Qv2ray/Qv2ray/releases/tags/v2.6.3
> 其中请注意上传者是github-action
> ![图片](https://user-images.githubusercontent.com/59914293/99145844-f9140000-26ac-11eb-96ab-698025a8f0cb.png)
> 
> 另外这个commit的CI配置文件在这里，您可以自行验证
> https://github.com/Qv2ray/Qv2ray/blob/912fe1b040544214b2f56c52e6da9fdb43c11f26/.github/workflows/build-qv2ray-cmake.yml
> 
> Qv2ray不会在编译时对代码进行任何修改
> 
> 我们欢迎任何人对Qv2ray进行代码审查

好的！

**Comment by DuckSoft** [comment]
Bug Mac，名不虚传。
