### ISSUE TITLE
使用疑问：「 macOS Big Sur 11.0.1 下频繁导致系统崩溃（六国） 」

### ISSUE THREAD

**Issue by xinmingliunicky** [Qv2ray/Qv2ray#1101]
### 你想做啥？

macOS Big Sur 11.0.1 下频繁导致系统崩溃（六国），具体如下：
qv2ray 2.6.3:5840 + Proxifier 3.0，使用Mac第三方APP（如用Maipo刷微博、用网易云客户端听歌等等），系统频繁崩溃（六国，黑屏重启）。

### 你目前试了啥？

文档和过往issue中没有相关内容，Catalina下相同使用环境并无问题。qv2ray已设置绕过大陆，proxifier已设置第三方APP不走代理，均无效。

### 其他要补充的信息？

系统崩溃日志如下（举例）：

panic(cpu 2 caller 0xffffff800e4bf47d): "a freed zone element has been modified in zone flow_divert_pcb: " "expected 0x3a353007a2a5d8b8 but found 0, bits changed 0x3a353007a2a5d8b8, " "at offset 0 of 216 in element 0xffffff86b7b9ed88, cookies 0x3f001162774d5150 0x5352165d5e889e9"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.50.7/osfmk/kern/zalloc.c:1649
Backtrace (CPU 2), Frame : Return Address
0xffffffa082ef3920 : 0xffffff800dcbc66d 
0xffffffa082ef3970 : 0xffffff800ddff073 
0xffffffa082ef39b0 : 0xffffff800ddef6aa 
0xffffffa082ef3a00 : 0xffffff800dc61a2f 
0xffffffa082ef3a20 : 0xffffff800dcbbf0d 
0xffffffa082ef3b40 : 0xffffff800dcbc1f8 
0xffffffa082ef3bb0 : 0xffffff800e4bee1a 
0xffffffa082ef3c20 : 0xffffff800e4bf47d 
0xffffffa082ef3c70 : 0xffffff800e4bf63c 
0xffffffa082ef3cc0 : 0xffffff800dd1908b 
0xffffffa082ef3cf0 : 0xffffff800dd1924b 
0xffffffa082ef3d70 : 0xffffff800e1399f0 
0xffffffa082ef3dd0 : 0xffffff800e1ca38a 
0xffffffa082ef3e20 : 0xffffff800e2a772b 
0xffffffa082ef3e60 : 0xffffff800e2b8e39 
0xffffffa082ef3f40 : 0xffffff800e369ceb 
0xffffffa082ef3fa0 : 0xffffff800dc621f6 

Process name corresponding to current thread: v2ray
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20B29

Kernel version:
Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
Kernel UUID: 84C6DC45-6B02-335F-9439-5D2A9BC385A4
KernelCache slide: 0x000000000da00000
KernelCache base:  0xffffff800dc00000
Kernel slide:      0x000000000da10000
Kernel text base:  0xffffff800dc10000
__HIB  text base: 0xffffff800db00000
System model name: MacBookAir8,1 (Mac-827FAC58A8FDFA22)
System shutdown begun: NO
Hibernation exit count: 0

System uptime in nanoseconds: 255845134203
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000003b918ef43a
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000759b8e3e1 0x0000000000000000
last started kext at 11594280992: @filesystems.autofs	3.0 (addr 0xffffff7fadffa000, size 32768)
loaded kexts:
@filesystems.autofs	3.0
@fileutil	20.036.15
>!ATopCaseHIDEventDriver	4000.27
>!AHIDALSService	1
>AGPM	119
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
>!AGraphicsDevicePolicy	6.1.27
@AGDCPluginDisplayMetrics	6.1.27
>pmtelemetry	1
>LuaHardwareAccess	1.0.16
|IOUserEthernet	1.0.1
>!AUpstreamUserClient	3.6.8
>usb.!UUserHCI	1
>!ABridgeAudio!C	100.2
|IO!BSerialManager	8.0.1f5
>!A!IKBLGraphics	16.0.0
>AGDCBacklightControl	6.1.27
>eficheck	1
>!ABacklight	180.3
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
>!ADiskImages2	1
>!A!IKBLGraphicsFramebuffer	16.0.0
>!AGFXHDA	100.1.431
>BridgeAudioCommunication	100.2
>!AAVEBridge	6.1
>!A!IPCHPMC	2.0.1
>ACPI_SMC_PlatformPlugin	1.0.0
>!AMCCSControl	1.14
>!AThunderboltIP	4.0.3
>!A!ISlowAdaptiveClocking	4.0.0
>!AFIVRDriver	4.1.0
>BCMWLANFirmware4378.Hashstore	1
>BCMWLANFirmware4377.Hashstore	1
>BCMWLANFirmware4364.Hashstore	1
>BCMWLANFirmware4355.Hashstore	1
>!ABCMWLANBusInterfacePCIeMac	1
@filesystems.apfs	1677.50.1
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.41.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	310
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@kext.triggers	1.0
>!AHIDKeyboard	222
>!AActuatorDriver	4400.28
>!AMultitouchDriver	4400.28
>!AInputDeviceSupport	4400.35
>!AHS!BDriver	4000.27
>IO!BHIDDriver	8.0.1f5
>!AGraphicsControl	6.1.27
|IO!BHost!CUARTTransport	8.0.1f5
|IO!BHost!CTransport	8.0.1f5
>!ABacklightExpert	1.1.0
|IOAVB!F	900.12
@plugin.IOgPTPPlugin	900.11
|IOEthernetAVB!C	1.1.0
|IOAccelerator!F2	439.35.4
>!AHDA!C	283.15
|IOHDA!F	283.15
|IONDRVSupport	585
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
>!ASMBusPCI	1.0.14d1
>!A!ILpssUARTv1	3.0.60
>!A!ILpssUARTCommon	3.0.60
>!AOnboardSerial	1.0
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>!ASMBus!C	1.0.18d1
>!AThunderboltEDMSink	5.0.3
>!AThunderboltDPOutAdapter	8.1.4
@!AGPUWrangler	6.1.27
@!AGraphicsDeviceControl	6.1.27
|IOGraphics!F	585
|IOSlowAdaptiveClocking!F	1.0.0
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc.ecm	5.0.0
>usb.cdc.ncm	5.0.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!ABCMWLANCoreMac	1.0.0
|IOSerial!F	11
|IO80211!FV2	1200.12.2b1
>IOImageLoader	1.0.0
>corecapture	1.0.4
>!AThunderboltPCIDownAdapter	4.1.1
>!AThunderboltDPInAdapter	8.1.4
>!AThunderboltDPAdapter!F	8.1.4
>!AHPM	3.4.4
>!A!ILpssI2C!C	3.0.60
>!A!ILpssI2C	3.0.60
>!A!ILpssDmac	3.0.60
>!AXsanScheme	3
>!AThunderboltNHI	7.2.8
|IOThunderbolt!F	9.3.2
>usb.!UVHCIBCE	1.2
>usb.!UVHCICommonBCE	1.0
>usb.!UVHCI	1.2
>usb.!UVHCICommon	1.0
>!AEffaceableNOR	1.0
|IOBufferCopy!C	1.1.0
|IOBufferCopyEngine!F	1
|IONVMe!F	2.1.0
>!ABSDKextStarter	3
|IOSurface	289.3
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
@filesystems.hfs.encodings.kext	1
>!A!ILpssGspi	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
>!ASMCRTC	1.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOTimeSync!F	900.11
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.1f5
|IOReport!F	47
|IO!BPacketLogger	8.0.1f5
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.40.9
|IOUSBMass!SDriver	184.40.6
|IOSCSIBlockCommandsDevice	436.40.6
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.40.6
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1

**Comment by U-v-U** [comment]
这或许不是 Qv2ray 能导致的问题

**Comment by MarksonHon** [comment]
@xinmingliunicky 放弃 proxifier 吧，苹果在新系统里面把相关的权限收紧了

**Comment by xinmingliunicky** [comment]
> @xinmingliunicky 放弃 proxifier 吧，苹果在新系统里面把相关的权限收紧了

看起来确实是Proxifier的问题，说好的最新版支持Big Sur还是不行
