### ISSUE TITLE
右键菜单可能被任务栏遮挡

### ISSUE THREAD

**Issue by fengbugu** [Qv2ray/Qv2ray#1104]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
打开qv2ray的右键菜单时，菜单有可能被任务栏遮挡，导致菜单底部的选项（比如退出）无法使用。

## 如何触发这个 Bug：

1. 正常开启qv2ray使用代理
2. 开启全屏应用（例如全屏观看视频，这一步不是必要的，但可以增加bug出现的机率）
3. 关闭或退出全屏应用
4. 右击qv2ray打开右键菜单，菜单的底部会被任务栏遮挡

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.windows-latest
```

### 操作系统

- Windows(Windows 10 20h1和20h2均出现过此问题)

### 安装来源
- Github Release / Scoop / Chocolatey

### 已安装的插件、版本及安装来源
QvPlugin-SSR v2.0.3 修复版——来自GitHub release
QvPlugin-Trojan v2.0.0 正式版——来自GitHub release

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
系统/框架原生问题，无法干预。若有锦囊妙计，还请不吝赐教。

**Comment by fengbugu** [comment]
> 系统/框架原生问题，无法干预。若有锦囊妙计，还请不吝赐教。

好的，谢谢您的回复！
