### ISSUE TITLE
功能请求：节点列表显示分成2栏

### ISSUE THREAD

**Issue by jacklee789** [Qv2ray/Qv2ray#1107]
目前节点列表显示是1栏。如果展开一个节点较多的订阅分组，其他订阅分组需要操作滚动条才能看到。
希望将节点列表显示分成2栏，类似chrome浏览器的书签管理。第1栏显示分组目录，第2栏显示分组内的节点。

![image](https://user-images.githubusercontent.com/55917636/99468112-d3bc1600-297a-11eb-93f0-850ace9496bb.png)

**Comment by U-v-U** [comment]
> 我们正在内部设计的新 QML 界面或许能解决你的问题
不过近期应该是看不到了
