### ISSUE TITLE
有关在 Qv2ray 中使用 Xray 核心的说明

### ISSUE THREAD

**Issue by U-v-U** [Qv2ray/Qv2ray#1108]
近日 Xray 发布了 v1.0 版本

Qv2ray 使用/支持的是 V2Ray 核心，与 Xray 在 API 调用方面有不同之处
目前将不会适配双核心 API 支持

已知问题：
- 没有统计数据
- 没有 `XRAY_LOCATION_ASSET` 环境变量支持

**Comment by U-v-U** [comment]
https://github.com/v2fly/v2ray-core/pull/431

**Comment by rprx** [comment]
含 XTLS 的 v2ray-core，以及更多增强，将在 Project X 继续： https://github.com/XTLS

**Comment by ax003** [comment]
搞的我不敢更新v2ray-core了

**Comment by U-v-U** [comment]
XTLS has been marked as deprecated in https://github.com/Qv2ray/Qv2ray/commit/2e44f1859ac4c9247069fc478611d8dfe44ff8ce and will be removed in a future version.

Possibly some time from v2.7.x to v2.8
`flow` will be marked as deprecated in the next preview version.

**Comment by U-v-U** [comment]
XTLS has been marked as deprecated in https://github.com/Qv2ray/Qv2ray/commit/2e44f1859ac4c9247069fc478611d8dfe44ff8ce and will be removed in a future version.
Possibly between v2.7.x and v2.8

`flow` will be marked as deprecated in the next preview version.

**Comment by chanfried** [comment]
几个意思，要“分家”？

**Comment by EpLiar** [comment]
> 几个意思，要“分家”？

跟随上游

**Comment by winXray** [comment]
XRay 专用客户端： [https://github.com/winXray/winXray](https://github.com/winXray/winXray)

**Comment by U-v-U** [comment]
谢谢

**Comment by x19810000** [comment]
xray已pre1.1.1版本。添加流控splice...qv2ray何時適配

**Comment by EpLiar** [comment]
> xray已pre1.1.1版本。添加流控splice...qv2ray何時適配

如果 v2ray-core 适配，我们自然会做

**Comment by DuckSoft** [comment]
@x19810000 Anytime

**Comment by DuckSoft** [comment]
@x19810000 https://github.com/Qv2ray/Qv2ray/commit/285acb894f78cd12965bf02226f0c97e60ffd25d
https://github.com/Qv2ray/Qv2ray/issues/1140

**Comment by Bit-Geek** [comment]
xray-core怎么配置可以使用tor
