### ISSUE TITLE
功能请求：Outbounds 出口顺序允许修改，使自定义GFW成为可能。

### ISSUE THREAD

**Issue by 517030910405** [Qv2ray/Qv2ray#1110]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

-----------------

**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

路由规则中，没有出现的域名默认代理。希望增加选项，允许设置为域名默认不代理。

**简单描述你预期的解决方案？**

请尽可能清晰简洁描述问题。
Outbounds 里面的顺序允许更换，并用 GUI 控制。
如果直接有GFW开关更好：https://guide.v2fly.org/routing/sitedata.html#%E5%A4%96%E7%BD%AE%E7%9A%84%E5%9F%9F%E5%90%8D%E6%96%87%E4%BB%B6

**你有想到其他比较容易实现的解决方案吗？**

请简单清晰描述。 

觉得前面的方法不是太麻烦吧？

**补充内容**
请在此附加任何你认为对你的描述有所帮助的内容。

**Comment by DuckSoft** [comment]
你是不知道有个功能叫复杂配置吗……
