### ISSUE TITLE
Quiet Mode 无效果

### ISSUE THREAD

**Issue by wvq** [Qv2ray/Qv2ray#1115]
- [ * ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
在Mac Big Sur(11.0.1)系统下, Quiet Mode 设置无效，开机自启动(或手动开启应用) 均会弹出窗口

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.macos-latest
```

### 操作系统
- macOS

### 安装来源

- Github Release / Scoop / Chocolatey

## 附加信息

*请注意打码隐私相关信息。*

**Comment by 2014CAIS01** [comment]
@wvq https://qv2ray.net/manual/general.html#%E8%A1%8C%E4%B8%BA
你可能对安静模式的理解有误

**Comment by DuckSoft** [comment]
设置自动连接即可在自启时隐藏主界面。

**Comment by lennondotw** [comment]
但是最小化运行的时候这里还是会有个小点点：
<img width="97" alt="Screen Shot 2021-05-26 at 10 07 41" src="https://user-images.githubusercontent.com/26853900/119592117-7235a200-be0a-11eb-8c13-f00dbf8142cb.png">
必须手动关闭一次窗口才会消失，否则图标会一直留在 Dock 栏。
