### ISSUE TITLE
使用疑问：「目前qv2ray有负载均衡功能吗？  」

### ISSUE THREAD

**Issue by ax003** [Qv2ray/Qv2ray#1118]
是否可以理解，在一个组内，就是自动实现负载均衡？

**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

### 你想做啥？
*简要描述你的最原始的目的。*

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by U-v-U** [comment]
没有
