### ISSUE TITLE
功能请求：请求在静态域名解析中添加自动导入hosts信息的功能

### ISSUE THREAD

**Issue by EsuRt** [Qv2ray/Qv2ray#1120]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
在hosts中屏蔽了相关软件的联网验证，但有些软件会通过系统代理联网，导致在启用系统代理的情况下，hosts就失去作用了，需要重复在“静态域名解析”中添加相关信息。如果hosts中的信息过多，一个个添加会非常麻烦。

**简单描述你预期的解决方案？**
希望能在“静态域名解析”中添加一键导入hosts相关信息的功能，或自动同步hosts中的信息到“静态域名解析”。

**你有想到其他比较容易实现的解决方案吗？**
读取hosts中的信息，然后添加到DNS设置中的“静态域名解析”。

**补充内容**
无

**Comment by DuckSoft** [comment]
不妨同我们分享一下这些域名？我们直接 PR 到上游的 `domain-list-community`，到时候直接把 `geosite:xxx-verify` 丢阻断就好了。

**Comment by EsuRt** [comment]
> 不妨同我们分享一下这些域名？我们直接 PR 到上游的 `domain-list-community`，到时候直接把 `geosite:xxx-verify` 丢阻断就好了。

我屏蔽的主要是adobe的联网验证，但是在dns中设置解析为127.0.0.1后，发现就变直连了，确实应该放在阻断设置中。不过又有一个问题，有些软件的域名屏蔽后，软件的网站就无法打开了，软件更新又是个问题。最终，我还是选择了用防火墙屏蔽环回地址的方法，阻止软件访问127.0.0.1，要是qv2ray也能屏蔽某些软件连接系统代理就好了。

Adobe相关域名：
activate.adobe.com
practivate.adobe.com
lmlicenses.wip4.adobe.com
lm.licenses.adobe.com
na1r.services.adobe.com
hlrcv.stage.adobe.com
3dns.adobe.com
3dns-1.adobe.com
3dns-2.adobe.com
3dns-3.adobe.com
3dns-4.adobe.com
3dns-5.adobe.com
activate.wip1.adobe.com
activate.wip2.adobe.com
activate.wip3.adobe.com
activate.wip4.adobe.com
activate-sea.adobe.com
activate-sjc0.adobe.com
adobe-dns.adobe.com
adobe-dns-1.adobe.com
adobe-dns-2.adobe.com
adobe-dns-3.adobe.com
adobe-dns-4.adobe.com
adobeereg.com
ereg.adobe.com
ereg.wip.adobe.com
ereg.wip1.adobe.com
ereg.wip2.adobe.com
ereg.wip3.adobe.com
ereg.wip4.adobe.com
hl2rcv.adobe.com
practivate.adobe
practivate.adobe.ipp
practivate.adobe.newoa
practivate.adobe.ntp
wip.adobe.com
wip1.adobe.com
wip2.adobe.com
wip3.adobe.com
wip4.adobe.com
wwis-dubc1-vip100.adobe.com
wwis-dubc1-vip101.adobe.com
wwis-dubc1-vip102.adobe.com
wwis-dubc1-vip103.adobe.com
wwis-dubc1-vip104.adobe.com
wwis-dubc1-vip105.adobe.com
wwis-dubc1-vip106.adobe.com
wwis-dubc1-vip107.adobe.com
wwis-dubc1-vip108.adobe.com
wwis-dubc1-vip109.adobe.com
wwis-dubc1-vip110.adobe.com
wwis-dubc1-vip111.adobe.com
wwis-dubc1-vip112.adobe.com
wwis-dubc1-vip113.adobe.com
wwis-dubc1-vip114.adobe.com
wwis-dubc1-vip115.adobe.com
wwis-dubc1-vip116.adobe.com
wwis-dubc1-vip117.adobe.com
wwis-dubc1-vip118.adobe.com
wwis-dubc1-vip119.adobe.com
wwis-dubc1-vip120.adobe.com
wwis-dubc1-vip121.adobe.com
wwis-dubc1-vip122.adobe.com
wwis-dubc1-vip123.adobe.com
wwis-dubc1-vip124.adobe.com
wwis-dubc1-vip125.adobe.com
wwis-dubc1-vip30.adobe.com
wwis-dubc1-vip31.adobe.com
wwis-dubc1-vip32.adobe.com
wwis-dubc1-vip33.adobe.com
wwis-dubc1-vip34.adobe.com
wwis-dubc1-vip35.adobe.com
wwis-dubc1-vip36.adobe.com
wwis-dubc1-vip37.adobe.com
wwis-dubc1-vip38.adobe.com
wwis-dubc1-vip39.adobe.com
wwis-dubc1-vip40.adobe.com
wwis-dubc1-vip41.adobe.com
wwis-dubc1-vip42.adobe.com
wwis-dubc1-vip43.adobe.com
wwis-dubc1-vip44.adobe.com
wwis-dubc1-vip45.adobe.com
wwis-dubc1-vip46.adobe.com
wwis-dubc1-vip47.adobe.com
wwis-dubc1-vip48.adobe.com
wwis-dubc1-vip49.adobe.com
wwis-dubc1-vip50.adobe.com
wwis-dubc1-vip51.adobe.com
wwis-dubc1-vip52.adobe.com
wwis-dubc1-vip53.adobe.com
wwis-dubc1-vip54.adobe.com
wwis-dubc1-vip55.adobe.com
wwis-dubc1-vip56.adobe.com
wwis-dubc1-vip57.adobe.com
wwis-dubc1-vip58.adobe.com
wwis-dubc1-vip59.adobe.com
wwis-dubc1-vip60.adobe.com
wwis-dubc1-vip61.adobe.com
wwis-dubc1-vip62.adobe.com
wwis-dubc1-vip63.adobe.com
wwis-dubc1-vip64.adobe.com
wwis-dubc1-vip65.adobe.com
wwis-dubc1-vip66.adobe.com
wwis-dubc1-vip67.adobe.com
wwis-dubc1-vip68.adobe.com
wwis-dubc1-vip69.adobe.com
wwis-dubc1-vip70.adobe.com
wwis-dubc1-vip71.adobe.com
wwis-dubc1-vip72.adobe.com
wwis-dubc1-vip73.adobe.com
wwis-dubc1-vip74.adobe.com
wwis-dubc1-vip75.adobe.com
wwis-dubc1-vip76.adobe.com
wwis-dubc1-vip77.adobe.com
wwis-dubc1-vip78.adobe.com
wwis-dubc1-vip79.adobe.com
wwis-dubc1-vip80.adobe.com
wwis-dubc1-vip81.adobe.com
wwis-dubc1-vip82.adobe.com
wwis-dubc1-vip83.adobe.com
wwis-dubc1-vip84.adobe.com
wwis-dubc1-vip85.adobe.com
wwis-dubc1-vip86.adobe.com
wwis-dubc1-vip87.adobe.com
wwis-dubc1-vip88.adobe.com
wwis-dubc1-vip89.adobe.com
wwis-dubc1-vip90.adobe.com
wwis-dubc1-vip91.adobe.com
wwis-dubc1-vip92.adobe.com
wwis-dubc1-vip93.adobe.com
wwis-dubc1-vip94.adobe.com
wwis-dubc1-vip95.adobe.com
wwis-dubc1-vip96.adobe.com
wwis-dubc1-vip97.adobe.com
wwis-dubc1-vip98.adobe.com
wwis-dubc1-vip99.adobe.com
crl.versign.net
ood.opsource.net

**Comment by DuckSoft** [comment]
https://github.com/v2fly/domain-list-community/commit/85eb99f2915e94084ddf78e2d9c0a4a719dab887

**Comment by DuckSoft** [comment]
另：欢迎去 v2fly/domain-list-community 贡献更多的类似的高质量域名列表
