### ISSUE TITLE
Question: <启用系统代理后uwp该如何走规则>

### ISSUE THREAD

**Issue by heziyouyi** [Qv2ray/Qv2ray#1121]
我开启了系统代理，然后用哔哩哔哩uwp没法加载内容，怎样能单独让一个uwp走直连。
有试过添加 bilibili.com 到规则，但是并没有效果。

**Comment by U-v-U** [comment]
https://qv2ray.net/getting-started/step4.html#%E4%BD%BF%E7%94%A8%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86

**Comment by DuckSoft** [comment]
@heziyouyi 来自文档：

Windows 用户：UWP 应用回环问题

默认情况下，UWP 程序禁止使用带有回环地址（如 127.0.0.1）的代理，所以设置系统代理可能会导致你的 UWP 程序无法连接网络。

你可以使用一些第三方工具来 启用 UWP 回环，使 UWP 程序可被正常代理。 这里提供一个来自 Fiddler 项目的 EnableLoopback @ Fiddler。
