### ISSUE TITLE
使用疑问：「  」

### ISSUE THREAD

**Issue by xtyi1997** [Qv2ray/Qv2ray#1122]
![image](https://user-images.githubusercontent.com/28750869/100224591-fd1b0a00-2f57-11eb-8bc1-be5a7183c337.png)

一直显示outbound_proxy
v2ray:2.63
socks  127.0.0.1 端口1080  使用系统代理 
telegram 不能正常访问
google chrome 不能正常使用
楼主,求解答
(加群的时候回答问题,回答错了)

**Comment by xtyi1997** [comment]
系统时Ubuntu:16.04

**Comment by DuckSoft** [comment]
Telegram: https://qv2ray.net/getting-started/step4.html#telegram
Chrome: https://qv2ray.net/getting-started/step4.html#%E7%BD%91%E9%A1%B5%E6%B5%8F%E8%A7%88%E5%99%A8

看看文档，多谢。

**Comment by xtyi1997** [comment]
> Telegram: https://qv2ray.net/getting-started/step4.html#telegram
> Chrome: https://qv2ray.net/getting-started/step4.html#%E7%BD%91%E9%A1%B5%E6%B5%8F%E8%A7%88%E5%99%A8
> 
> 看看文档，多谢。

看了这个文档,我使用的是SwitchyOmega chrome 
设置了

**Comment by xtyi1997** [comment]
看了这个文档,我使用的是SwitchyOmega 这个工具
![image](https://user-images.githubusercontent.com/28750869/100226012-0c9b5280-2f5a-11eb-891c-7da6057639b4.png)
然后telegram这个也设置了custom代理
![image](https://user-images.githubusercontent.com/28750869/100226071-29378a80-2f5a-11eb-93b5-5d1c11de623a.png)
但都超出边界
![image](https://user-images.githubusercontent.com/28750869/100226176-52f0b180-2f5a-11eb-919d-3fd57a88aef6.png)
还请大佬给一些建议

telegram因为回答错误
![image](https://user-images.githubusercontent.com/28750869/100226348-93e8c600-2f5a-11eb-90d2-19e03d0d7685.png)

**Comment by EpLiar** [comment]
你用 SwitchyOmega 切换模式了么

**Comment by xtyi1997** [comment]
切换了,换成了proxy模式

**Comment by xtyi1997** [comment]
> 你用 SwitchyOmega 切换模式了么

切换了,换成了proxy的模式

**Comment by EpLiar** [comment]
Qv2ray 里 socks5 的端口确定是 1080 么？或者你试试用 HTTP？

**Comment by 2014CAIS01** [comment]
请问什么是超出边界……
`outbound_proxy` 是 出站代理

**Comment by xtyi1997** [comment]
> 请问什么是超出边界……
> `outbound_proxy` 是 出站代理

好的,谢谢大佬指正

**Comment by xtyi1997** [comment]
> Qv2ray 里 socks5 的端口确定是 1080 么？或者你试试用 HTTP？

对.在入站规则选择也是socks 1080 然后使用设置代理
http那里也勾选了,端口8889
也试了前站代理,不太管用,

试了,也没管用

**Comment by EpLiar** [comment]
等待一段期间后再次尝试加群吧

**Comment by xtyi1997** [comment]
> 等待一段期间后再次尝试加群吧

兄弟,这个解封大概多久,能问一下么?

**Comment by EpLiar** [comment]
一般是几十分钟一小时左右如果你不确定可以等明天或者零点

**Comment by xtyi1997** [comment]
> 一般是几十分钟一小时左右如果你不确定可以等明天或者零点

好的好的,谢谢大佬
