### ISSUE TITLE
Fedora OBS 来源的 Qv2ray 中无法粘贴

### ISSUE THREAD

**Issue by 520ignite** [Qv2ray/Qv2ray#1123]
- [x] **I'm sure I've tried to reproduce the problem several times and will provide the system environment, each software and its version that is involved in the problem.**

## Briefly describe this bug：

Ctrl+C Ctrl+V Not Working

## How to trigger this bug：

1. ????

### Related screenshots or logs

<details>

```
Please paste your Qv2ray log here:


```

</details>

### Open Preferences -> About, and enter the following info

```
Version: 
Build info: 
Extra build info: 
```

### Operating systems

- [x] Linux
 
### Installation source
 
- [x] Fedora - Stable

## Additional Info

*Please hide your server address and UUID if you wish to post the vmess string or your connection setting.*

**Comment by DuckSoft** [comment]
Assigned to Fedora Maintainers @zzndb & @sixg0000d.
Also, please provide with us your system environment information, including but not limited to:
 - OS Name
 - OS Release Version
 - X.org / Wayland
 - Desktop Environment
 - Desktop Environment Version

Only with sufficient information could we reproduce and locate the problem.

**Comment by 520ignite** [comment]
Fedora 33（workstation Edition）
GNOME 3.38.1
Wayland

**Comment by MarksonHon** [comment]
Wayland 目前有个通病，它没有统一的剪贴板标准。因此，在非 GTK 应用下很容易遭遇到复制粘贴的问题。缓解方法是使用 `Ctrl+C/V` 来进行粘贴。同时要注意，复制粘贴的时候要把复制窗口与目标窗口都打开再复制。

**Comment by DuckSoft** [comment]
Any updates?

**Comment by 520ignite** [comment]
缓解的方法确实可行，目前完美使用了！多谢
