### ISSUE TITLE
功能请求：可选择在更新订阅错误时自动使用代理重新请求

### ISSUE THREAD

**Issue by Fangliding** [Qv2ray/Qv2ray#1125]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

为了防止订阅链接被墙，qv2ray带有通过代理更新的功能，但是使用这个功能有一定缺陷。参考下列情景。（使用通过代理更新均默认使用Qv2ray自己创建的代理）
1.小明有两个订阅链接，一个是被墙的A，一个是未被墙的B，但是B的安全策略会拒绝大多数已知VPS服务商的IP
为了更新被墙的A，小明打开了通过代理更新。
成功更新A后，小明去更新B，但是B的安全策略拒绝了小明的更新，小明需要打开首选项去掉通过代理更新才成功

2.小明有1个订阅链接A，这个链接被墙了，于是小明一直是打开通过代理更新的，而使用的代理也是链接A的代理。
有一天，订阅链接A的服务器全部被墙了。小明找好基友小王借来了一个未被墙的订阅链接B，但是小明发现更新不出来，原因是服务器尝试去连接QV2ray的代理，但是现在它并没有配置上可用代理，于是小明又需要打开首选项去掉通过代理更新

[省略号]

**简单描述你预期的解决方案？**

IDM的代理服务器有一个功能，仅在下载错误时再向配置的代理服务器请求。QV2ray可以做成在更新订阅失败时再通过代理请求一次。

**你有想到其他比较容易实现的解决方案吗？**

先采用直连更新，如果返回结果是0个，再通过代理尝试一遍

**Comment by U-v-U** [comment]
Thanks for your contribution.

对于用户操作透明性来说，我反对后台偷偷请求两次
- 失败了就是失败了，要不要重试我说的算
- 因此，解决方案 = 增加一个 ‘使用代理更新 / 直连更新’ 订阅选项

**Comment by cpdyj** [comment]
我怎么觉得，按你这么说，正确的做法应该是同时发起两个请求看哪个能成功

**Comment by Fangliding** [comment]
> Thanks for your contribution.
> 
> 对于用户操作透明性来说，我反对后台偷偷请求两次
> 
> * 失败了就是失败了，要不要重试我说的算
> * 因此，解决方案 = 增加一个 ‘使用代理更新 / 直连更新’ 订阅选项

没有，你没有理解我的意思，我的意思是在选项选中使用代替之后 出现一个可勾选的选项，”仅在不通过代理更新失败时使用“ 这一类

**Comment by U-v-U** [comment]
仅在直连失败情况下使用
1. 直连，失败了
2. 于是开始使用代理

（那还是请求了两次）

**Comment by DuckSoft** [comment]
> > Thanks for your contribution.
> > 对于用户操作透明性来说，我反对后台偷偷请求两次
> > 
> > * 失败了就是失败了，要不要重试我说的算
> > * 因此，解决方案 = 增加一个 ‘使用代理更新 / 直连更新’ 订阅选项
> 
> 没有，你没有理解我的意思，我的意思是在选项选中使用代替之后 出现一个可勾选的选项，”仅在不通过代理更新失败时使用“ 这一类

这想法挺好的，不过最近挺忙，欢迎有志之士 PR 一个，先行谢过。

**Comment by U-v-U** [comment]
After a internal discussion, we have decided not to implement this.
Thanks for your report.
