### ISSUE TITLE
Feature Request: Option to disable automatic latency test

### ISSUE THREAD

**Issue by dyhkwong** [Qv2ray/Qv2ray#1127]
**Is your feature request related to a problem? Please describe.**
Qv2ray always attempts to TCPing/ICMPing when connecting to a new server. I prefer to trigger latency test manually. 

**Describe the solution you'd like**
An option to disable automatic latency test. Do not test latency when connecting to a new server.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by DuckSoft** [comment]
Nice One. Will be implemented ASAP.

**Comment by DuckSoft** [comment]
Thanks for that!
