### ISSUE TITLE
代理功能正常，但是界面卡死

### ISSUE THREAD

**Issue by JasonQWJ** [Qv2ray/Qv2ray#1134]
## 简单描述这个 Bug:

连接以后界面卡死，选择了自动连接，从此只要打开就卡死。。。

<details>

[Init] High DPI scaling is enabled. 
[BaseApplication] Qv2ray 2.7.0-pre1 on macOS High Sierra (10.13) x86_64 
[BaseApplication] Qv2ray Start Time:  3190545 
[BaseApplication] QV2RAY_BUILD_INFO Qv2ray built from Github Action 
[BaseApplication] QV2RAY_BUILD_EXTRA_INFO qt5.15.0-fa3ead7cdea00bd2ec88146a5ed4dd3e449dff4e-ci.macos-latest 
[BaseApplication] QV2RAY_BUILD_NUMBER 6039 
[BaseApplication] This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
Copyright (c) 2019-2020 Qv2ray Development Group.
Third-party libraries that have been used in this program can be found in the About page. 
[PlatformApplication] Startup Options: parser.isSet(noAPIOption): 0 
[PlatformApplication] Startup Options: parser.isSet(debugLogOption): 0 
[PlatformApplication] Startup Options: parser.isSet(noAutoConnectionOption): 0 
[PlatformApplication] Startup Options: parser.isSet(noPluginsOption): 0 
[PlatformApplication] Command line: errorMessage:  
[PlatformApplication] Non-fatal error, continue starting up. 
[Translator] Found translations: en_US ja_JP yue zh_CN zh_TW 
[Translator] Found zh_CN in folder: /Applications/qv2ray.app/Contents/Resources/lang 
[Translator] Successfully installed a translator for zh_CN 
[SettingsBackend] Application exec path: /Applications/qv2ray.app/Contents/MacOS 
[SettingsBackend] Path: /Applications/qv2ray.app/Contents/MacOS/config/ does not contain a valid config file. 
[SettingsBackend] Found a config file, conf["config_version"].toString():  path: /Users/jason/Library/Preferences/qv2ray/ 
[SettingsBackend] Path: /Users/jason/Library/Preferences/qv2ray  is valid. 
[SettingsBackend] Using  /Users/jason/Library/Preferences/qv2ray/  as the config path. 
[Translator] Found zh_CN in folder: /Applications/qv2ray.app/Contents/Resources/lang 
[Translator] Removed translations 
[Translator] Successfully installed a translator for zh_CN 
[PluginHost] Reloading plugin list 
[PluginHost] Loading plugin: libQvPlugin-BuiltinProtocolSupport.so from: /Applications/qv2ray.app/Contents/Resources/plugins 
[PluginHost] Loaded plugin: "Builtin Protocol Support" made by: "Qv2ray Core Workgroup" 
[PluginHost] Loading plugin: libQvPlugin-BuiltinSubscriptionSupport.so from: /Applications/qv2ray.app/Contents/Resources/plugins 
[PluginHost] Loaded plugin: "Builtin Subscription Support" made by: "Qv2ray Core Workgroup" 
[ConfigHandler] ConnectionHandler Constructor. 
[ConfigHandler] Loaded connection id: ocmghkdfujhz into cache. 
[gRPCBackend] API Worker initialised. 
[gRPCBackend] API Worker started. 
[StyleManager] Found factory style: macintosh 
[StyleManager] Found factory style: Windows 
[StyleManager] Found factory style: Fusion 
[StyleManager] Found QSS style at: ":/uistyles/flatwhite.css" 
[StyleManager] Found QSS style at: ":/uistyles/psblack.css" 
[StyleManager] Applying built-in darkmode theme. 
[RouteHandler] Processing a simple connection config 
[RouteHandler] Added global DNS config 
[InboundGenerator] Allocation is not used here, Not Implemented 
[InboundGenerator] Allocation is not used here, Not Implemented 
[RouteHandler] Added global inbound config 
[InboundGenerator] Allocation is not used here, Not Implemented 
[KernelHandler] Cannot disconnect when there's nothing connected. 
[KernelHandler] Outbound protocol vmess is not a registered plugin outbound. 
[KernelHandler] Outbound protocol freedom is not a registered plugin outbound. 
[KernelHandler] Outbound protocol blackhole is not a registered plugin outbound. 
[KernelHandler] Applying new outbound settings. 
[KernelHandler] There are other processes occupying the ports necessary to start the connection:
Endpoint: 127.0.0.1:15490 for inbound: "QV2RAY_API_INBOUND"
Endpoint: 127.0.0.1:8889 for inbound: "http_IN"
Endpoint: 127.0.0.1:1089 for inbound: "socks_IN" 
[Update] Start checking update for channel ID: 0 
[NetworkCore] Get without proxy.
[Update] Received update info:
 --> Latest: 2.6.3
 --> Current: 2.7.0-pre1
 --> Ignored: 0.0.0 
[Update] No suitable updates found on channel 0 
[GeositeReader] Reading geosites from: /Users/jason/Library/Preferences/qv2ray/vcore/v2ray/geosite.dat 
[GeositeReader] Loaded 1014 geosite entries from data file. 
[GeositeReader] Reading geosites from: /Users/jason/Library/Preferences/qv2ray/vcore/v2ray/geoip.dat 
[GeositeReader] Loaded 251 geosite entries from data file.

</details>
## 系统信息

macOS 10.13.6

版本:  卡死了看不到
编译信息：同上
额外编译信息：同上

### 操作系统

- macOS 10.13.6

### 安装来源

- Github Release

**Comment by DuckSoft** [comment]
10.13，苹果已经宣布放弃支持，我们也不打算支持了。要么去首选项内核设置关掉api子系统，要么就用不成。
