### ISSUE TITLE
Ubuntu下使用会闪退

### ISSUE THREAD

**Issue by Techmile** [Qv2ray/Qv2ray#1135]
我在移动硬盘中安装了Ubuntu18.04.5_x64，当我使用台式机运行该系统时，qv2ray一切正常。当使用另一台笔记本启动该系统时，qv2ray可以正常启动和设置代理，但是一旦访问网络就会闪退。

           我尝试了snap安装v2.6.4方式，和下载最新2.7.0，且更换过不同版本的v2ray-core，都会有该问题，并且我也尝试过更换网络，切换有线网卡，和无线网卡依然有这个问题，还有可能是哪里的问题呢？

以下是部分参考日志：
Dec  1 09:20:48 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [COMPONENT-UPDATE]: Received update info:
Dec  1 09:20:48 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]:  --> Latest: 2.6.3
Dec  1 09:20:48 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]:  --> Current: 2.6.3
Dec  1 09:20:48 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]:  --> Ignored: 0.0.0
Dec  1 09:20:48 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [COMPONENT-UPDATE]: No suitable updates found on channel 0
Dec  1 09:20:48 tecsmile-MS-7B89 oray_rundaemon[1182]: 1489
Dec  1 09:21:04 tecsmile-MS-7B89 oray_rundaemon[1182]: message repeated 15 times: [ 1489]
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-CONNECTION]: Inserting default values to simple config
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [QV2RAY-CORE]: Cannot disconnect when there's nothing connected.
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-CONNECTION]: Creating kernel plugin instance for protocolshadowsocksr
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-VCORE]: V2RayIntegration: 15000 = shadowsocksr
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-CONNECTION]: Sending connection settings to kernel.
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-CONNECTION]: Outbound protocol freedom is not a registered plugin outbound.
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-CONNECTION]: Outbound protocol blackhole is not a registered plugin outbound.
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-CONNECTION]: Applying new outbound settings.
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-VCORE]: Starting kernels with V2RayIntegration.
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-CONNECTION]: Starting kernel for protocol: shadowsocksr
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-VCORE]: Core ABI: ELF amd64 可执行文件
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-VCORE]: Host ABI: ELF amd64 可执行文件
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-VCORE]: Host is compatible with core
Dec  1 09:21:04 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-VCORE]: V2Ray output: V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 linux/amd64);A unified platform for anti-censorship.
Dec  1 09:21:05 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-UI]: ProxyAddress: 127.0.0.1
Dec  1 09:21:05 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [COMPONENT-PROXY]: Setting up System Proxy
Dec  1 09:21:05 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [COMPONENT-PROXY]: Qv2ray will set system proxy to use HTTP
Dec  1 09:21:05 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [COMPONENT-PROXY]: Qv2ray will set system proxy to use SOCKS
Dec  1 09:21:05 tecsmile-MS-7B89 kernel: [ 1827.528769] audit: type=1326 audit(1606785665.267:282): auid=1000 uid=1000 gid=1000 ses=2 pid=24785 comm="gsettings" exe="/snap/qv2ray/3605/usr/bin/gsettings" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7f63d522889d code=0x50000
Dec  1 09:21:05 tecsmile-MS-7B89 kernel: [ 1827.550017] audit: type=1326 audit(1606785665.291:283): auid=1000 uid=1000 gid=1000 ses=2 pid=24796 comm="gsettings" exe="/snap/qv2ray/3605/usr/bin/gsettings" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7f8f8fa8789d code=0x50000
Dec  1 09:21:05 tecsmile-MS-7B89 oray_rundaemon[1182]: 1489
Dec  1 09:21:05 tecsmile-MS-7B89 kernel: [ 1827.562170] audit: type=1326 audit(1606785665.303:284): auid=1000 uid=1000 gid=1000 ses=2 pid=24808 comm="gsettings" exe="/snap/qv2ray/3605/usr/bin/gsettings" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7f32018bc89d code=0x50000
Dec  1 09:21:05 tecsmile-MS-7B89 kernel: [ 1827.573961] audit: type=1326 audit(1606785665.315:285): auid=1000 uid=1000 gid=1000 ses=2 pid=24813 comm="gsettings" exe="/snap/qv2ray/3605/usr/bin/gsettings" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7f567d20089d code=0x50000
Dec  1 09:21:05 tecsmile-MS-7B89 kernel: [ 1827.585810] audit: type=1326 audit(1606785665.327:286): auid=1000 uid=1000 gid=1000 ses=2 pid=24818 comm="gsettings" exe="/snap/qv2ray/3605/usr/bin/gsettings" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7f57ff77e89d code=0x50000
Dec  1 09:21:05 tecsmile-MS-7B89 kernel: [ 1827.597291] audit: type=1326 audit(1606785665.335:287): auid=1000 uid=1000 gid=1000 ses=2 pid=24823 comm="gsettings" exe="/snap/qv2ray/3605/usr/bin/gsettings" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7f4cf292f89d code=0x50000
Dec  1 09:21:05 tecsmile-MS-7B89 kernel: [ 1827.608463] audit: type=1326 audit(1606785665.347:288): auid=1000 uid=1000 gid=1000 ses=2 pid=24828 comm="gsettings" exe="/snap/qv2ray/3605/usr/bin/gsettings" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7fc06305289d code=0x50000
Dec  1 09:21:05 tecsmile-MS-7B89 kernel: [ 1827.620318] audit: type=1326 audit(1606785665.359:289): auid=1000 uid=1000 gid=1000 ses=2 pid=24833 comm="gsettings" exe="/snap/qv2ray/3605/usr/bin/gsettings" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7fe6f966789d code=0x50000
Dec  1 09:21:05 tecsmile-MS-7B89 kernel: [ 1827.637204] audit: type=1326 audit(1606785665.375:290): auid=1000 uid=1000 gid=1000 ses=2 pid=24839 comm="gsettings" exe="/snap/qv2ray/3605/usr/bin/gsettings" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7f1d7354a89d code=0x50000
Dec  1 09:21:05 tecsmile-MS-7B89 kernel: [ 1827.649014] audit: type=1326 audit(1606785665.387:291): auid=1000 uid=1000 gid=1000 ses=2 pid=24844 comm="gsettings" exe="/snap/qv2ray/3605/usr/bin/gsettings" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7fac04e4689d code=0x50000
Dec  1 09:21:05 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-UI]: Setting current item.
Dec  1 09:21:05 tecsmile-MS-7B89 qv2ray_qv2ray.desktop[24471]: [CORE-VCORE]: gRPC Version: 1.16.1
Dec  1 09:21:06 tecsmile-MS-7B89 oray_rundaemon[1182]: 1489
Dec  1 09:21:11 tecsmile-MS-7B89 kernel: [ 1834.237522] traps: SSRThread[24764] trap invalid opcode ip:7f18f3124f9d sp:7f18c77fa3c0 error:0 in QvSSRPlugin.v2.0.3.linux-x64.so[7f18f305a000+11c000]
Dec  1 09:21:11 tecsmile-MS-7B89 oray_rundaemon[1182]: message repeated 5 times: [ 1489]
Dec  1 09:21:12 tecsmile-MS-7B89 gnome-shell[7055]: Object .Gjs_AppIndicatorIconActor__1 (0x5638d5175400), has been already finalized. Impossible to set any property to it.
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: == Stack trace for context 0x5638d280a320 ==
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: #0 0x7fff5517fb90 I   resource:///org/gnome/gjs/modules/_legacy.js:83 (0x7f07143b5de0 @ 87)
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: #1 0x5638d2bb0590 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/indicatorStatusIcon.js:93 (0x7f06beec4340 @ 58)
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: #2 0x7fff55180770 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f07143b5de0 @ 71)
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: #3 0x7fff55180830 b   self-hosted:916 (0x7f07143f12b8 @ 367)
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: #4 0x7fff551808b0 I   resource:///org/gnome/gjs/modules/signals.js:128 (0x7f07143d2230 @ 386)
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: #5 0x5638d2bb0508 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:190 (0x7f06beeb0f78 @ 22)
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: #6 0x7fff55181490 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f07143b5de0 @ 71)
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: #7 0x5638d2bb0460 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/statusNotifierWatcher.js:176 (0x7f06beeb02b8 @ 26)
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: #8 0x7fff55182070 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f07143b5de0 @ 71)
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: #9 0x5638d2bb03c0 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/statusNotifierWatcher.js:170 (0x7f06beeb0230 @ 68)
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: #10 0x7fff55182c60 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f07143b5de0 @ 71)
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: #11 0x7fff55182d30 b   self-hosted:918 (0x7f07143f12b8 @ 394)
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: [14563:14579:1201/092112.126465:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -100
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: [14563:14579:1201/092112.126849:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -100
Dec  1 09:21:12 tecsmile-MS-7B89 org.gnome.Shell.desktop[7055]: Fontconfig error: Cannot load default config file: No such file: (null)
Dec  1 09:21:12 tecsmile-MS-7B89 oray_rundaemon[1182]: 1489
Dec  1 09:21:16 tecsmile-MS-7B89 oray_rundaemon[1182]: message repeated 4 times: [ 1489]
Dec  1 09:21:17 tecsmile-MS-7B89 NetworkManager[1122]: <info>  [1606785677.7729] connectivity: (wlp3s0) timed out
Dec  1 09:21:17 tecsmile-MS-7B89 NetworkManager[1122]: <info>  [1606785677.7730] manager: NetworkManager state is now CONNECTED_SITE
Dec  1 09:21:17 tecsmile-MS-7B89 dbus-daemon[1054]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service' requested by ':1.14' (uid=0 pid=1122 comm="/usr/sbin/NetworkManager --no-daemon " label="unconfined")
Dec  1 09:21:17 tecsmile-MS-7B89 systemd[1]: Starting Network Manager Script Dispatcher Service...
Dec  1 09:21:17 tecsmile-MS-7B89 dbus-daemon[1054]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Dec  1 09:21:17 tecsmile-MS-7B89 systemd[1]: Started Network Manager Script Dispatcher Service.
Dec  1 09:21:17 tecsmile-MS-7B89 nm-dispatcher: req:1 'connectivity-change': new request (1 scripts)
Dec  1 09:21:17 tecsmile-MS-7B89 nm-dispatcher: req:1 'connectivity-change': start running ordered scripts...
Dec  1 09:21:17 tecsmile-MS-7B89 oray_rundaemon[1182]: 1489
Dec  1 09:21:26 tecsmile-MS-7B89 oray_rundaemon[1182]: message repeated 8 times: [ 1489]
Dec  1 09:21:26 tecsmile-MS-7B89 gnome-shell[7055]: [AppIndicatorSupport-WARN] Attempting to re-register :1.2/StatusNotifierItem; resetting instead
Dec  1 09:21:26 tecsmile-MS-7B89 gnome-shell[7055]: [AppIndicatorSupport-WARN] Item :1.2/StatusNotifierItem is already registered
Dec  1 09:21:26 tecsmile-MS-7B89 gnome-shell[7055]: [AppIndicatorSupport-WARN] Attempting to re-register :1.2/StatusNotifierItem; resetting instead
Dec  1 09:21:26 tecsmile-MS-7B89 gnome-shell[7055]: [AppIndicatorSupport-WARN] Item :1.2/StatusNotifierItem is already registered
Dec  1 09:21:27 tecsmile-MS-7B89 oray_rundaemon[1182]: 1489

**Comment by 12101111** [comment]
> trap invalid opcode ip

你的笔记本CPU是什么, 似乎没有avx?

**Comment by Techmile** [comment]
老神舟k480-i7-d3，芯片组：hm76

以下是cpu信息
架构：           x86_64
CPU 运行模式：   32-bit, 64-bit
字节序：         Little Endian
CPU:             8
在线 CPU 列表：  0-7
每个核的线程数： 2
每个座的核数：   4
座：             1
NUMA 节点：      1
厂商 ID：        GenuineIntel
CPU 系列：       6
型号：           58
型号名称：       Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
步进：           9
CPU MHz：        1197.412
CPU 最大 MHz：   3400.0000
CPU 最小 MHz：   1200.0000
BogoMIPS：       4789.42
虚拟化：         VT-x
L1d 缓存：       32K
L1i 缓存：       32K
L2 缓存：        256K
L3 缓存：        6144K
NUMA 节点0 CPU： 0-7
标记：           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d

**Comment by 12101111** [comment]
或许你可以试试结尾是linux-no-avx-x64.so的插件

**Comment by Techmile** [comment]
> 或许你可以试试结尾是linux-no-avx-x64.so的插件

非常感谢，看来就是这个问题
