### ISSUE TITLE
功能请求：监听多个 IP

### ISSUE THREAD

**Issue by sheep94lion** [Qv2ray/Qv2ray#1137]
-----------------

**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

请尽可能清晰简洁地描述问题。

我在windows中想让wsl使用windows中的代理，所以希望代理同时监听127.0.0.1和172.27.80.1（windows与wsl连接的网卡的ip），但是我又不想直接将监听地址设定为0.0.0.0， 这样不安全。

**简单描述你预期的解决方案？**

在配置中支持监听多个ip，例如127.0.0.1,172.27.80.1

**Comment by Janet-Baker** [comment]
负责监听的是配置文件里的listen，可以自己设定的呀。。
------
还有，加一个Windows防火墙不就行了吗？
防火墙已经不能满足需求了咩……

**Comment by kidonng** [comment]
WSL2 里的 host IP 是会变化的，所以即便能监听多个 IP 也需要手动更新。
如果觉得监听 0.0.0.0 不安全可以像 @Janet-Baker 说的用防火墙。

**Comment by cpdyj** [comment]
复杂路由配置，请

**Comment by Janet-Baker** [comment]
#https://github.com/Qv2ray/Qv2ray/issues/1114
