### ISSUE TITLE
Speed Graph at windows 10 is not working after I upgraded to 4.33.0

### ISSUE THREAD

**Issue by sioulisn** [Qv2ray/Qv2ray#1138]
- [ ] **I'm sure I've tried to reproduce the problem several times and will provide the system environment, each software and its version that is involved in the problem.**

## Briefly describe this bug：
Speed Graph at windows 10 is not working after I upgraded to "4.33.0" with vless ws tls
All other functions work as should be.

## How to trigger this bug：

1. Upgrade Server (ubuntu 20.04) and Windows 10 Client to 4.33.0 
2.  Create vless ws tls nginx connection
3.  Add connection to  Qv2ray 2.6.3 5840
4. Speed Graph is not working

### If it's a connection issue, has it happened in other V2Ray clients?
No connection issues, only Speed Graph

### Related screenshots or logs

<details>

```
Please paste your Qv2ray log here:


```

</details>

### Open Preferences -> About, and enter the following info

```
Version: 
Build info: 
Extra build info: 
```

### Operating systems

- [ ] Linux
- [ ] macOS
- [x] Windows
 
### Installation source
 
- [ ] ArchLinuxCN - Stable
- [ ] ArchLinuxCN - Dev-git
- [ ] ArchLinux AUR - Stable
- [ ] ArchLinux AUR - Development
- [ ] Fedora - Stable
- [ ] Fedora - Preview
- [ ] openSUSE - Stable
- [ ] openSUSE - Preview
- [ ] Flathub
- [ ] Snap
- [ ] Homebrew Cask
- [ ] Scoop / Chocolatey / Github Release
- [ ] Compile manually

## Additional Info

*Please hide your server address and UUID if you wish to post the vmess string or your connection setting.*

**Comment by cpdyj** [comment]
I think you should confirm the checkbox

**Comment by DuckSoft** [comment]
@sioulisn It is a known issue for vless outbounds in 2.6.3, and is already fixed in newer versions. You may want to upgrade.

**Comment by sioulisn** [comment]
May I ask one more different topic?
I was using vmess plain TCP and the speed was around 300-400mbps. After I start using vless(or vmess) with nginx ws tls that is more stable than plain TCP the speeds are hardly 100mbps. Is there any configuration that I miss or that's the protocol's limits?

**Comment by DuckSoft** [comment]
ws introduces handshaking, wrapping and encoding overhead.
tls introduces handshaking, encryption/decryption and encoding overhead.
plus the implementation in V2Ray will disable ReadV when tls is on.
it's expected to see a sharp drop in performance.

whether go loud or go quiet, it's up to you.

**Comment by sioulisn** [comment]
@DuckSoft thank you for your help! keep it up guys
