### ISSUE TITLE
Windows下关机时没有自动关闭系统代理

### ISSUE THREAD

**Issue by Joker2387089590** [Qv2ray/Qv2ray#1139]
- [Yes ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
我打开了系统代理，但是没有打开开机自动启动。关机后再开机，发现设置了代理的应用无法联网。检查发现是Windows系统代理没有还原。

## 如何触发这个 Bug：
（如上所述）

## 系统信息

```
版本: 2.6.3
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.windows-latest
```

### 操作系统
- Windows

### 安装来源
- Github Release

### 已安装的插件、版本及安装来源
SSR Plugin, 作者：Qv2ray Development Group，版本：v2.0.3

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
已知问题，暂时没找到好的解决方案。虽然我们在关机前已经自动断开连接并且手动取消了系统代理，但是仍有 Windows 用户报告这个问题。希望有好心人来深入调查一下。
