### ISSUE TITLE
招募适配 Xray 核心的志愿者

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#1140]
由于 Xray 迭代速度非常快，Qv2ray 开发组现有人手不足，没有足够的自信能及时跟进上游的变更。
欢迎有志之士加入。

**Comment by stephenzhang0713** [comment]
需要储备什么前提知识

**Comment by U-v-U** [comment]
@stephenzhang0713 会 Qt 即可

**Comment by Laputa0** [comment]
我正想问问怎么用xray来着，没想到已经行动了

**Comment by ax003** [comment]
请问计划推出安卓版本吗

**Comment by U-v-U** [comment]
Closing as resolved in https://github.com/Qv2ray/Qv2ray/pull/1150
