### ISSUE TITLE
在Linux系统上，“最近连接”的列表无法打开

### ISSUE THREAD

**Issue by Lonble** [Qv2ray/Qv2ray#1141]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

在Linux系统上，点击托盘图标，“最近连接”的列表无法打开。

## 如何触发这个 Bug：

1. 使用Gnome桌面环境
2. 使用AppIndicator and KStatusNotifierItem Support托盘图标扩展
3. 点击qv2ray的托盘图标
4. 点击最近连接，无法打开列表

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

非连接问题

### 相关截图或日志

![Screenshot from 2020-12-07 10-02-35](https://user-images.githubusercontent.com/74650029/101301443-cd330700-3873-11eb-8476-72783e3a3b99.png)

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5841
编译信息：Qv2ray from AUR
额外编译信息：(Manual Build) 5.8.14-arch1-1 x86_64
```

### 操作系统

- Linux

### 安装来源

- ArchLinux AUR - 稳定版

### 已安装的插件、版本及安装来源

无

## 附加信息

在Windows下这个地方没有问题，在Linux下“系统代理”列表也没问题，仅“最近连接”打不开。

*请注意打码隐私相关信息。*

**Comment by Lonble** [comment]
换了个图标扩展，没有问题了
<https://extensions.gnome.org/extension/1503/tray-icons/>

**Comment by FaithALL** [comment]
Ubuntu 20.04 使用 qv2ray官方源安装最新版 也无法打开最近连接，楼上的tray-icons好像也不起作用
