### ISSUE TITLE
浅色主题的日志配色问题

### ISSUE THREAD

**Issue by mojie126** [Qv2ray/Qv2ray#1142]
浅色主题的日志配色问题

那个骚黄色在浅色主题上基本看不清，希望可以重新配色下
还有部分图标在深色主题上也几乎看不清...

**Comment by DuckSoft** [comment]
https://qv2ray.net/getting-started/step5.html#%E8%B0%83%E6%95%B4%E7%95%8C%E9%9D%A2%E4%B8%8E%E6%98%BE%E7%A4%BA%E8%AF%AD%E8%A8%80

**Comment by mojie126** [comment]
![微信截图_20201211150436.png](https://i.loli.net/2020/12/11/tlnQqcz4orpaukG.png)

**Comment by U-v-U** [comment]
fixed

**Comment by DuckSoft** [comment]
already fixed in dev.
