### ISSUE TITLE
Linux下Qv2ray开机启动，无法加载托盘图标

### ISSUE THREAD

**Issue by Lonble** [Qv2ray/Qv2ray#1143]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

Linux设置Qv2ray开机启动，无法加载Qv2ray的托盘图标

## 如何触发这个 Bug：

1. 使用Gnome桌面环境
2. 使用AppIndicator and KStatusNotifierItem Support托盘图标扩展
3. 在Qv2ray首选项打开开机启动
4. 观察托盘图标，发现没有Qv2ray

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

非连接问题

### 相关截图或日志

![Screenshot from 2020-12-07 10-20-25](https://user-images.githubusercontent.com/74650029/101302348-5a775b00-3876-11eb-8bb5-845744aa64bc.png)

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5841
编译信息：Qv2ray from AUR
额外编译信息：(Manual Build) 5.8.14-arch1-1 x86_64
```

### 操作系统

- Linux

### 安装来源

- ArchLinux AUR - 稳定版

### 已安装的插件、版本及安装来源

无

## 附加信息

手动打开Qv2ray的时候可以正常加载托盘图标，但设置开机启动就不能加载托盘图标了。

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
上游问题，与我们无关。

**Comment by function2-llx** [comment]
如果只是为了解决想要开机启动的问题的话，可以参考这个：https://help.ubuntu.com/stable/ubuntu-help/startup-applications.html.en
