### ISSUE TITLE
修改dns后，软件无法正常使用

### ISSUE THREAD

**Issue by kongjue** [Qv2ray/Qv2ray#1144]
- [ ] 我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
本来一直可以正常使用，今天使用qv2ray过程中，使用其他软件修改了系统dns，之后qv2ray便无法正常使用，无论是重装软件还是恢复之前的dns或者尝试其他工具修复网络都一直无法正使用
其他上网一切正常，使用其他代理软件也正常

## 如何触发这个 Bug：

1. 修改dns导致的

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

使用clash产生过同样的情况，无法修复

### 相关截图或日志

<details>

![22](https://user-images.githubusercontent.com/75435118/101480401-9b629300-398e-11eb-8828-86733b56d861.png)

请从此行下面的行开始粘贴 Qv2ray 日志：

```

</details>

## 系统信息

<!-- 请删除所有不符合的操作系统和安装来源，只保留符合的项目 -->

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.7.0-pre1:6039
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-fa3ead7cdea00bd2ec88146a5ed4dd3e449dff4e-ci.windows-latest
```

### 操作系统


- Windows

### 安装来源

- ArchLinuxCN - 开发版

### 已安装的插件、版本及安装来源



## 附加信息

<!-- 你认为对修复 bug 有帮助的任何信息都可以在此写出来。 -->

*请注意打码隐私相关信息。*

**Comment by U-v-U** [comment]
那你改回去就好了
