### ISSUE TITLE
功能请求：<在断开连接以后依然代理流量，使其直连>

### ISSUE THREAD

**Issue by Lonble** [Qv2ray/Qv2ray#1145]
-----------------

**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

目前如果在Qv2ray中**断开连接**，就会关闭v2ray-core，并且关闭系统代理。对于使用系统代理的软件来说这样没什么问题，变成了直连。但是如果软件是**手动设置的代理**，或者开启了**透明代理**，断开连接会导致**无法上网**。

**简单描述你预期的解决方案？**

我希望断开连接只断开当前的节点，依然代理流量，使其直连。

**你有想到其他比较容易实现的解决方案吗？**

我在现有版本上的解决方案是：手动创建一个出口协议为“freedom”的连接，用此连接来替代断开连接。
但是我希望这种方案是内置到断开连接的，并且对用户不可见。

**补充内容**
请在此附加任何你认为对你的描述有所帮助的内容。

**Comment by U-v-U** [comment]
目前没有任何办法，因为 V2Ray 暂时做不到热重载配置

**Comment by Lonble** [comment]
也未必需要热重载配置，把v2ray进程关了再开，就像换节点那样

**Comment by U-v-U** [comment]
切换节点会造成瞬间的 TCP 断流，我认为这是不太合理的

**Comment by MarksonHon** [comment]
@U-v-U V2Ray 内核无法做到在不断开的情况下切换节点，因此你的需求应该向 V2Fly 反馈

**Comment by DuckSoft** [comment]
你可以做一个直连的复杂配置，然后用切换到这个节点来代替“断开”情形。

**Comment by U-v-U** [comment]
更正： 直连已经不需要复杂配置了
