### ISSUE TITLE
AppImage is blocking shutdown

### ISSUE THREAD

**Issue by EMUNES** [Qv2ray/Qv2ray#1147]
## Briefly describe this bug：
Unable to restart qv2ray though I set this option on. I must run *killall -9 qv2ray* and then re-run the qv2ray AppImage manually, which can be pretty troublesome.

And more, if I don't quit qv2ray before I shut down my pc, the system shutdown process will be idle and I have to wait for a long time for my pc to respond and shut down. 

All above, I must quit before shutdown and every time I restart my pc I have to kill the process and start it again by my hands.

## How to trigger this bug：

1. Exexute the AppImage file.
2. Turn on Lauch At Login.
3. Try Shutdown or restart your pc and you will find your computer idle (You don't need to turn on Lauch At Login to trigger this).
4. After restart you might not see qv2ray icon and you won't see any changes if you execute the AppImage file without killing the processes first.
5. This problem may show after several restarts.

### Related screenshots or logs
![Screenshot 2020-12-09 21:47:23](https://user-images.githubusercontent.com/53288091/101637788-29f71300-3a68-11eb-9f9b-fd74c2ed4b73.png)
This is when it works fine.

The problem is that: the .json file process will not run and you won't see it in the processes if you don't run the AppImage file manually. You must kill all the running qv2ray processes first. I tried to write script to run the AppImage file, however, only the *qv2ray* process and the AppImage process will run, just like when I restart my pc.

No log shown. However if I run it on the commandline it will show that the system needs version info blablablabla.

System:
kali linux 64 2020.4  GUI xfce
 

### Installed plugins, versions and sources
qv2ray v2.7.0-pre1 
qv2ray ssr plugin v2.7.0
v2ray core 4.33.0

Anyway to solve this and save time for competitive shutting down process and starting it manually.

**Comment by DuckSoft** [comment]
It's a known issue that Session Management is not properly handled by AppImage.
Kali Linux (and other Debian based distros) should always use Debian Packages rather than AppImage.
Currently our AppImage maintainer cannot find a way to fix this. Sorry for that.

If you got any idea, a pull request is always welcomed!
