### ISSUE TITLE
我每次使用都会出现多个v2ray图标，而且无法正常使用

### ISSUE THREAD

**Issue by johnzhao0520** [Qv2ray/Qv2ray#1148]
最新版我更新后出现这样的问题，和我安装多次有关系吗？
现在完全使用不了

![image](https://user-images.githubusercontent.com/53855416/101712437-7d04b080-3ad0-11eb-8339-6e903ade4b5b.png)

**Comment by DuckSoft** [comment]
你好，请先搞清楚那个图标是谁整出来的再发 Issue，谢谢。

**Comment by DuckSoft** [comment]
关于“最新版”（https://github.com/Qv2ray/Qv2ray/releases/tag/v2.7.0-pre1）：

发布页面清清楚楚写明白了，使用此版本需要更新插件，不更新可能会导致崩溃问题，并列出了所有插件的下载链接，我觉得你需要好好看看。

https://github.com/Qv2ray/QvPlugin-Trojan/releases/tag/v3.0.0-pre3
https://github.com/Qv2ray/QvPlugin-SSR/releases/tag/v3.0.0-pre3
https://github.com/Qv2ray/QvPlugin-NaiveProxy/releases/tag/v3.0.0-pre3
https://github.com/Qv2ray/QvPlugin-Trojan-Go/releases/tag/v3.0.0-pre3
https://github.com/Qv2ray/QvPlugin-SS/releases/tag/v3.0.0-pre3
https://github.com/Qv2ray/QvPlugin-Command/releases/tag/v3.0.0-pre3

**Comment by DuckSoft** [comment]
最后，你没有在发 Issue 的时候选择正确的模板，更没有按照模板提示和指引去完善你的问题。
这可能导致你没有看到我们放置在模板页面中的一个非常重要的提示：***请注意打码隐私相关信息。***

**你原来所发 Issue 的附图中已将你的节点信息全部泄漏。**

我已将你的 Issue 图片删除，但该图片已经永久存档到了 GitHub 的图床里，删不掉了。

**Comment by DuckSoft** [comment]
再唠叨几句：关于不看模板发 Issue，我希望这不仅仅是一个需要“下次注意”的问题。引用一句 Project V 的话：

> **如果你不花一分钟时间看一眼issue模板，我是一秒钟都不会花在你的issue上的。尊重是相互的。**
> ——*“Project V 官方公告”*, https://t.me/v2msg/42, 2017/12/26

你所发 Issue 的文字部分并没有准确清晰描述出问题的根本所在，我也是看了截图才知道原来根本的问题是“更新新版后卡死”而不是什么“托盘出现了114514个v2rayN的图标”。

最后，强烈建议阅读 https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**Comment by johnzhao0520** [comment]
感谢大佬，小白第一次发帖，已经解决问题了。原因是因为我打开了这个选项
![image](https://user-images.githubusercontent.com/53855416/101715866-31a1d080-3ad7-11eb-964e-a4b42d4a2f75.png)

**Comment by U-v-U** [comment]
@johnzhao0520 请截图一下首选项内核设置？

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/101716390-1f746200-3ad8-11eb-9852-8397589d21b0.png)
这已经不是一个XYZABCDEFGHIJKLMNOPQRST问题能解决的了……

**Comment by johnzhao0520** [comment]
大佬说的对，确实用的是v2rayN。但是我关了那个选项后也可以正常使用
![image](https://user-images.githubusercontent.com/53855416/101717656-afb3a680-3ada-11eb-87af-556441a33b47.png)
