### ISSUE TITLE
功能请求：能不能适配一下 apple silicon

### ISSUE THREAD

**Issue by takfate** [Qv2ray/Qv2ray#1149]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

请尽可能清晰简洁地描述问题。
能不能适配一下Apple silicon，转译的好像耗电有点高

**简单描述你预期的解决方案？**

请尽可能清晰简洁描述问题。
编译arm mac版并发布。

**你有想到其他比较容易实现的解决方案吗？**

请简单清晰描述。 
编译arm mac版并发布。

**补充内容**
请在此附加任何你认为对你的描述有所帮助的内容。

**Comment by U-v-U** [comment]
目前 Qt 还没有支持 M1 的编译
各大 CI Provider 也没有集成 Silicon 的通知

Qv2ray 作为下游只能等着

**Comment by DuckSoft** [comment]
@U-v-U 我在苹果的DTK上流畅无问题运行。如果你说是专门针对arm平台编译，那欢迎帮我们去Qt推动相应工具链的发展，我代表所有使用Qt的开发者感谢你

**Comment by takfate** [comment]
哈哈，原来qt还没出工具链，谢谢

**Comment by MarksonHon** [comment]
@U-v-U 目前 Apple 还没有适配 Qt 库（确信

**Comment by LER0ever** [comment]
@DuckSoft 目前HomeBrew上已经提供了Qt5的aarch64二进制bottle，并且实测可以编译Qt Creator的arm64原生二进制。

<img width="1287" alt="CleanShot 2021-01-08 at 18 17 31@2x" src="https://user-images.githubusercontent.com/10568668/104004016-3349db80-51de-11eb-956e-1218cf733a42.png">

是否可以在下次release的时候带上macOS arm64版的发布？

**Comment by DuckSoft** [comment]
感谢提醒。

我们正在使用的自动化构建环境 GitHub Actions 似乎还不支持 macOS Big Sur aarch64 架构。
如果你乐意在我们每次发布版本的时候手动编译一次，我们也不介意加上 macOS arm64 版本的发布。

**Comment by LER0ever** [comment]
> 我们正在使用的自动化构建环境 GitHub Actions 似乎还不支持 macOS Big Sur aarch64 架构。

@DuckSoft 的确，不过x86_64下的macOS host是可以给aarch64交叉编译的，有几个项目已经使用GitHub Action发布M1二进制了。

> 如果你乐意在我们每次发布版本的时候手动编译一次，我们也不介意加上 macOS arm64 版本的发布。

当然没问题，如果到时Actions还没有aarch64-darwin的host的话我可以帮忙编译。不过目前还没有跑通，grpc有一些问题尚需等待homebrew，ref: https://github.com/Homebrew/discussions/discussions/485

**Comment by kslr** [comment]
> > 我们正在使用的自动化构建环境 GitHub Actions 似乎还不支持 macOS Big Sur aarch64 架构。
> 
> @DuckSoft 的确，不过x86_64下的macOS host是可以给aarch64交叉编译的，有几个项目已经使用GitHub Action发布M1二进制了。
> 
> > 如果你乐意在我们每次发布版本的时候手动编译一次，我们也不介意加上 macOS arm64 版本的发布。
> 
> 当然没问题，如果到时Actions还没有aarch64-darwin的host的话我可以帮忙编译。不过目前还没有跑通，grpc有一些问题尚需等待homebrew，ref: [Homebrew/discussions#485](https://github.com/Homebrew/discussions/discussions/485)
> 
> 或许这个issue可以重开，或者另起一个追踪aarch64的build问题，据我所知v2ray也还不支持M1...

是的，在你编辑前我正好在看评论。目前我不确定能不能将编译系统换成macOS ，因为最近github提供机器似乎出现了随机性性能大跌。

**Comment by LER0ever** [comment]
> 是的，在你编辑前我正好在看评论。
> 我不确定能不能将编译系统换成macOS ，因为最近github提供机器似乎出现了随机性性能下降。

@kslr v2ray刚刚尝试了一下的确不行，简单说一下原因，之后我在v2ray-core repo下开一个issue。

目前aarch64-apple-darwin这个triplet需要Go1.16的beta才能编译，而v2ray-core有一个间接依赖项是 github.com/marten-seemann/qtls-go1-15，参考go.sum，这项无法在非1.15的Go编译器下编译。

**Comment by DuckSoft** [comment]
> > 我们正在使用的自动化构建环境 GitHub Actions 似乎还不支持 macOS Big Sur aarch64 架构。
> 
> @DuckSoft 的确，不过x86_64下的macOS host是可以给aarch64交叉编译的，有几个项目已经使用GitHub Action发布M1二进制了。
> 
> > 如果你乐意在我们每次发布版本的时候手动编译一次，我们也不介意加上 macOS arm64 版本的发布。
> 
> 当然没问题，如果到时Actions还没有aarch64-darwin的host的话我可以帮忙编译。不过目前还没有跑通，grpc有一些问题尚需等待homebrew，ref: [Homebrew/discussions#485](https://github.com/Homebrew/discussions/discussions/485)
> 
> 或许这个issue可以重开，或者另起一个追踪aarch64的build问题，据我所知v2ray-core也还不支持M1...

我来再开一个 Issue 追踪这个问题。刨坟容易惊到上古巨神。
