### ISSUE TITLE
功能请求：添加tap模式

### ISSUE THREAD

**Issue by yang05051** [Qv2ray/Qv2ray#1153]
能否添加tap模式以监管所有的流量？（创建tap虚拟适配器，监管流量）

**Comment by Laputa0** [comment]
我找很久了，找不到
目前mellow可以，不好用
clash premium也可以，不会用
要是qv2ray出这功能，必须点赞

**Comment by DuckSoft** [comment]
上游加，我们就加。啥时候 V2Ray 核心加入了 TAP 功能，我们马上支持。
