### ISSUE TITLE
最近偶尔开机后打开QV2ray启用连接会报错

### ISSUE THREAD

**Issue by amosniu** [Qv2ray/Qv2ray#1158]
偶尔开机后开启连接提示端口占用，但是查询端口占用的进程却提示无进程。
![屏幕截图 2020-12-14 094911](https://user-images.githubusercontent.com/16161472/102031787-ff071900-3df1-11eb-825d-c8402d4457d4.png)

**Comment by U-v-U** [comment]
https://qv2ray.net/faq/v2ray-core.html#windows-%E7%B3%BB%E7%BB%9F%E4%BF%9D%E7%95%99%E7%AB%AF%E5%8F%A3
