### ISSUE TITLE
win10上安装python库时发生 sslerror

### ISSUE THREAD

**Issue by zdypop** [Qv2ray/Qv2ray#1160]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
本人的os是win10，python版本是3.9。
在开启qv2ray后，在终端pip安装库时，发生sslerror。

## 如何触发这个 Bug：

1. pip安装
2. 更换不同协议的代理（tcp，ws，trojan，vmess）都会发生
3. 
4. 

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
使用v2rayN就不会发生。
如果不使用代理，库安装会很慢，所以以前都会挂代理安装库。

### 相关截图或日志

<details>
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)'))': /simple/numpy/
Could not fetch URL https://pypi.org/simple/numpy/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/numpy/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)'))) - skipping
ERROR: Could not find a version that satisfies the requirement numpy
ERROR: No matching distribution found for numpy
```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

qv2ray版本是 2.6.3

### 操作系统

- Windows10

### 安装来源

- Github Release / Scoop / Chocolatey

### 已安装的插件、版本及安装来源
trojan-gfw
trojan-go

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
请补充 V2Ray 核心的日志。
