### ISSUE TITLE
测试延迟出现错误

### ISSUE THREAD

**Issue by Arise903** [Qv2ray/Qv2ray#1161]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

测试延迟的时候，出现错误。但是可以连接成功，连接成功以后会出延迟的数字

## 如何触发这个 Bug：

1. 打开APP
2. 选择测试延迟就会出现

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

[在Qv2ray其他版本没有这个问题，只有这个版本有这个问题。](url)

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.7.0-pre1:6039
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-fa3ead7cdea00bd2ec88146a5ed4dd3e449dff4e-ci.macos-latest
```

### 操作系统

- macOS

### 安装来源

- Github Release / Scoop / Chocolatey

### 已安装的插件、版本及安装来源
Builtin Protocol
Builtin Subscription
NaiveProxy Plugin
Qv2ray Command
Shadowsocks SIP003 Plugin
SSR Plugin
Trojan-GFW Plugin
Trojan-Go Plugin

版本：都是在Github Release  2.7.0-pre1下面提供的最新版本
 

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
<img width="223" alt="图片" src="https://user-images.githubusercontent.com/7822648/102191833-eb90a680-3ef4-11eb-90b3-40e067e2b783.png">
Cannot Reproduce.
