### ISSUE TITLE
can't exit Qv2ray after click close

### ISSUE THREAD

**Issue by jeremy-peng** [Qv2ray/Qv2ray#1164]
- [x] **I'm sure I've tried to reproduce the problem several times and will provide the system environment, each software and its version that is involved in the problem.**

## How to trigger this bug：

1. add some group in Qv2ray
2. click "Close" button 

![image](https://user-images.githubusercontent.com/6103154/102239189-8e671600-3f31-11eb-8011-e277a2879ccd.png)

3. the process can't exit correctly, process hang, have to use "ctrl+c" to kill the process

![image](https://user-images.githubusercontent.com/6103154/102239272-a5a60380-3f31-11eb-96ad-69500d60c39a.png)

4. reopen the qv2ray, all setting aren't saved

### Related screenshots or logs

<details>

```
Please paste your Qv2ray log here:
[INIT]: Qv2ray PreInitialization: OK
[INIT]: Qv2ray 2.6.3 on Ubuntu 20.04 LTS x86_64
[CORE-UI]: Successfully installed a translator for en_US
[LICENCE]:
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

Copyright (c) 2019-2020 Qv2ray Development Group.
Third-party libraries that have been used in Qv2ray can be found in the About page.

[INIT]: Application exec path: /tmp/.mount_Qv2rayI2ivZE/usr/bin
[INIT]: Path: /tmp/.mount_Qv2rayI2ivZE/usr/bin/config/ does not contain a valid config file.
[CORE-SETTINGS]: Found a config file, v= path=/home/jepeng/.config/qv2ray/
[INIT]: Using /home/jepeng/.config/qv2ray/ as the config path.
[CORE-UI]: Removed translations
[CORE-UI]: Successfully installed a translator for en_US
[COMMON-NETWORK]: Current OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
[CORE-UI]: Found factory style: Windows
[CORE-UI]: Found factory style: Fusion
[CORE-UI]: Found QSS style at: ":/uistyles/flatwhite.css"
[CORE-UI]: Found QSS style at: ":/uistyles/psblack.css"
[COMPONENT-PLUGINHOST]: Reloading plugin list
[CORE-UI]: Applying UI style: Fusion
[CORE-UI]: Loading data...
[COMMON-NETWORK]: Start checking update for channel ID: 0
[COMPONENT-UPDATE]: Received update info:
 --> Latest: 2.6.3
 --> Current: 2.6.3
 --> Ignored: 0.0.0


```

</details>

### Open Preferences -> About, and enter the following info

```
Version: 2.6.3, 2.7.0-pre1
Build info: 
Extra build info: 
```

### Operating systems

- [x] Linux: Ubuntu 20.0
- [] macOS
- [ ] Windows
 
### Installation source
 
- [x] ArchLinuxCN - Stable
- [ ] ArchLinuxCN - Dev-git
- [ ] ArchLinux AUR - Stable
- [ ] ArchLinux AUR - Development
- [ ] Fedora - Stable
- [ ] Fedora - Preview
- [ ] openSUSE - Stable
- [ ] openSUSE - Preview
- [ ] Flathub
- [ ] Snap
- [ ] Homebrew Cask
- [ ] Scoop / Chocolatey / Github Release
- [ ] Compile manually

## Additional Info

*Please hide your server address and UUID if you wish to post the vmess string or your connection setting.*

**Comment by jeremy-peng** [comment]
two possible solutions:
1.add exit menu or button in App
2.save group and subscribe data while click "ok" in group config dialog

**Comment by MarksonHon** [comment]
1. Actually there is a 'exit' bottom in tray menu. Closing Qv2ray's main window is NOT the way to exit it but only makes it minimize to your tray.
2. Ctrl + C in terminal means you wanna stop  a process directly even if the process has no time to save data.

**Comment by DuckSoft** [comment]
Ctrl+Q in the main window if you don't have a tray.

**Comment by jeremy-peng** [comment]
> Ctrl+Q in the main window if you don't have a tray.

this works, 

thanks

**Comment by jeremy-peng** [comment]
> 1. Actually there is a 'exit' bottom in tray menu. Closing Qv2ray's main window is NOT the way to exit it but only makes it minimize to your tray.
> 2. Ctrl + C in terminal means you wanna stop  a process directly even if the process has no time to save data.

thanks, since I am connecting a server machine, so I can't see the try.
Ctrl + Q works.

Thanks
