### ISSUE TITLE
电脑从休眠或睡眠状态回来之后不能立即访问Google，似乎要过一分钟左右才会正常到科学上网

### ISSUE THREAD

**Issue by redstoneleo** [Qv2ray/Qv2ray#1165]
电脑从休眠或睡眠状态回来之后不能立即访问Google，似乎要过一分钟左右才会正常到科学上网。
我用的是Trojan插件，win7 32位。所以，希望本软件在这种状态下能够尽可能快速地恢复过来——尽快地回到科学上网模式

**Comment by SekiBetu** [comment]
@redstoneleo win7爬，32位爬

**Comment by DuckSoft** [comment]
尽可能快速地恢复过来：重开一下

**Comment by redstoneleo** [comment]
> 尽可能快速地恢复过来：重开一下

每次都手动操作？那也太麻烦了吧，让软件自己解决这个问题不行吗？

**Comment by DuckSoft** [comment]
@redstoneleo 抱歉，太菜了，不会。

**Comment by redstoneleo** [comment]
我说的或许就是让软件尽快重新连接到服务器的功能，这个做起来比较困难吗？

**Comment by SekiBetu** [comment]
https://www.softwareok.com/?seite=Microsoft/DontSleep/History 可以试试这个

**Comment by DuckSoft** [comment]
> 我说的或许就是让软件尽快重新连接到服务器的功能，这个做起来比较困难吗？

有思路请直接点明，有代码请交 PR，需求永远不缺，缺的是能干活的人。

**Comment by redstoneleo** [comment]
我是希望本软件在电脑休眠或睡眠状态回来之后能够尽可能快速地恢复过来——尽快地回到科学上网模式，重新连接到服务器。

代码我也不会写，如有打扰，多多见谅！

**Comment by MarksonHon** [comment]
你这个问题，目前还没有其它人反馈过。且你提供的信息也很少，甚至连Qv2ray日志都没有。
如果要寻求帮助可以加群（但是不一定有人帮你解决），不用打issue。
<https://t.me/qv2ray>

**Comment by U-v-U** [comment]
We can neither detect a suspend of your system, nor unexpectedly performing a disconnection while other applications are using the proxy service.
- It's your OS's fault, or network's fault.
- Cannot reproduce.
- Don't suspend

**Comment by U-v-U** [comment]
The network subsystem needs restarting, reassiciating after a resume.
Did you check for any other causes?

Qv2ray is just a proxy frontend, whereas v2ray is the core service provider, you may consider opening an issue there.

**Comment by U-v-U** [comment]
Did you have a time-based chart indicating Qv2ray is slowing down the initiation of your connection to Google?

- Further information needed
