### ISSUE TITLE
2.7.0-pre1:6039 macos 按照非默认排序后再连接节点后，焦点会跳到本组最后一个节点

### ISSUE THREAD

**Issue by zz5678** [Qv2ray/Qv2ray#1168]
如题，是个比较隐藏的bug，按照延迟排序后，会跳最后一个，但默认的名称排序就不会。
而且在节点数比较多（>200）的时候，会有轻微卡顿现象。

**Comment by DuckSoft** [comment]
很有可能不会修复，因为我们正准备迁移到 Qt 6 并使用 QML 构建我们的全新界面。
届时，此问题可能不会再出现。不过暂时，我们应该是没有精力去排查和解决这个问题。

敬请谅解。

另外：欢迎大家帮助我们调试、定位并修复问题。
