### ISSUE TITLE
Tracker: Support VMessAEAD / VLESS Link Schema

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#1173]
https://github.com/XTLS/Xray-core/issues/91

**Comment by DuckSoft** [comment]
咕咕咕，咕咕咕，明天就写

**Comment by DuckSoft** [comment]
写 完 了

68f8ddb7c5d180b61241fc0fae31beb668c4246b
ede6abd7662152a9000b97fba5a52a2f47f03e51

**Comment by zhangsean** [comment]
写完了，什么时候发布呀？最近用vless比较多，不支持分享和导入链接，非常不方便。
期待期待！加鸡腿🍗

**Comment by DuckSoft** [comment]
在 Qv2ray v2.7.0-pre2 里已经发布了呀

> 写完了，什么时候发布呀？最近用vless比较多，不支持分享和导入链接，非常不方便。
> 期待期待！加鸡腿poultry_leg

**Comment by zhangsean** [comment]
看到了，辛苦了！
首页只展示正式版发布，还以为没有发布呢。
