### ISSUE TITLE
使用疑问：「 mac上的qv2ray怎么导入windows版本中trojan的配置文件，thx」

### ISSUE THREAD

**Issue by ilovetaimei** [Qv2ray/Qv2ray#1174]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

`QV_ISSUE_QUESTION_TEMPLATE_PLACEHOLDER`

### 你想做啥？
*简要描述你的最原始的目的。*

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by DuckSoft** [comment]
配置文件全平台通用，配置文件目录 macOS 的路径应该在：`~/Library/Preferences/qv2ray/`，覆盖即可。
