### ISSUE TITLE
使用疑问：「 请问怎么将windows版本里的Trojan节点导入到mac的Qv2ray中,thx」

### ISSUE THREAD

**Issue by ilovetaimei** [Qv2ray/Qv2ray#1177]
导出的json文件导入后不能直接使用

**Comment by DuckSoft** [comment]
配置文件和导出的 JSON 文件不是一回事，不能通用。

正确且直接的方法是点击 Windows 上的节点分组，右边会出现整个分组所有节点的分享链接，全选并复制，打开mac上的软件，导入分享链接，粘贴进去导入即可

**Comment by ilovetaimei** [comment]
解决了,感谢
