### ISSUE TITLE
使用疑问：「 更改设置时提示invalid tproxy listening ivp4 address 」

### ISSUE THREAD

**Issue by TorchTheo** [Qv2ray/Qv2ray#1180]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

### 你想做啥？
*简要描述你的最原始的目的。*

想要应用首选项的时候会有提示invalid tproxy listening ivp4 address
### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

看完文档，没有相关内容，就过来问一问。
### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/102992533-54f86100-4556-11eb-85a6-0c6bbd0f2659.png)
注意此处的设定。
