### ISSUE TITLE
功能请求：日志导出筛选分析功能

### ISSUE THREAD

**Issue by LuminousXLB** [Qv2ray/Qv2ray#1181]
-----------------

**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

请尽可能清晰简洁地描述问题。

由于没有默认提供基于GFW List的路由设置， **仅绕过中国大陆** 的选项可能过于激进，导致一些虽然不在中国大陆，但本不须经过代理的目标也通过代理访问。
因此需要通过分析日志调整路由选项。

**简单描述你预期的解决方案？**

请尽可能清晰简洁描述问题。

添加日志导出功能，允许用户自行分析日志。
如果能提供 csv 导出，或直接在软件中提供日志筛选与分析功能则更佳。

**你有想到其他比较容易实现的解决方案吗？**

请简单清晰描述。 

把日志存进文件。
或者提供基于 GFW List 的路由设置。

**补充内容**
请在此附加任何你认为对你的描述有所帮助的内容。

NA

**Comment by database64128** [comment]
Configure `geosite:geolocation-!cn@cn` to use direct connection.

Also, just so you know, `gfwlist` is dead.

**Comment by LuminousXLB** [comment]
> geosite:geolocation-!cn@cn

Thanks for your kind reply.
I updated my config as below
![image](https://user-images.githubusercontent.com/23524048/102999472-0225a600-4564-11eb-90a9-e61ac7178f48.png)

But it still doesn't work well.
![image](https://user-images.githubusercontent.com/23524048/102999502-110c5880-4564-11eb-84ad-5c84af28eb54.png)

As you can see in the screenshot, it unexpectedly routes `csapp.cs.cmu.edu` to the proxy.

**Comment by DuckSoft** [comment]
@LuminousXLB geosite:category-scholar-!cn

**Comment by LuminousXLB** [comment]
> @LuminousXLB geosite:category-scholar-!cn

Thanks, but it still has the route to the proxy

![image](https://user-images.githubusercontent.com/23524048/102999863-cb03c480-4564-11eb-8648-27267816ee64.png)

![image](https://user-images.githubusercontent.com/23524048/102999883-d7881d00-4564-11eb-9861-2fcf08ca2daa.png)

**Comment by DuckSoft** [comment]
overkill workaround: add `domain:edu` to domain direct.

please consider open an issue on https://github.com/v2fly/domain-list-community/blob/master/data/category-scholar-!cn

add `cmu.edu` and some other domains

**Comment by LuminousXLB** [comment]
> overkill workaround: add `domain:edu` to domain direct.
> 
> please consider open an issue on https://github.com/v2fly/domain-list-community/blob/master/data/category-scholar-!cn
> 
> add `cmu.edu` and some other domains

I'm not writing to seek help for a config, although it's great if there is.
I hope that there's a better way where I can find such unexpected routes more easily.

**Comment by DuckSoft** [comment]
It's fine if someone would open a Pull Request. Major authors are all busy with studies, so don't expect too quick.

**Comment by U-v-U** [comment]
Closing due to the implementation complexity for now, but this issue will reopened when V2Ray has a log API.
