### ISSUE TITLE
使用疑问：「 断开连接后上不了网 」

### ISSUE THREAD

**Issue by TorchTheo** [Qv2ray/Qv2ray#1182]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

### 你想做啥？
*简要描述你的最原始的目的。*
想要在断开连接后能够上网

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
文档里没有，刚才也自己尝试重新启动删除项目等操作但是没有作用

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by TorchTheo** [comment]
请问是什么原因

**Comment by DuckSoft** [comment]
下次提问的时候，记得带上足够的信息。

~~不然就只能等我魔法水晶球修好了再给你看了哈~~
