### ISSUE TITLE
apt安装的qv2ray重启后任务栏图标消失

### ISSUE THREAD

**Issue by duhl1999** [Qv2ray/Qv2ray#1184]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
使用snap安装的qv2ray无法开机自启，apt安装的qv2ray重启后任务栏图标消失并且重启后订阅信息全部丢失

## 如何触发这个 Bug：

一、snap安装的
1.勾选登录时启动
2.sudo reboot
3.重启后qv2ray没有启动
二、apt安装的
1. 填入订阅并更新订阅后可以正常使用
2. sudo reboot重启
3. 重启后qv2ray会弹出，但是丢失了所有订阅信息。并且右上角图标也会消失
4. 

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5841
编译信息：Qv2ray from manual build
额外编译信息：Qv2ray 2.6.3:5841
```

### 操作系统

ubuntu20.04

### 安装来源

- Snap 包
- apt

### 已安装的插件、版本及安装来源
无

## 附加信息

*请注意打码隐私相关信息。*

**Comment by GuozhangLiao** [comment]
还有更换xray-core也无法运行，提示没有找到内核，和无权限执行

**Comment by DuckSoft** [comment]
> 还有更换xray-core也无法运行，提示没有找到内核，和无权限执行

请用 2.7.x 版本。还有，兄弟你串台了。

**Comment by DuckSoft** [comment]
“任务栏图标”：https://qv2ray.net/faq/#%E8%BD%AF%E4%BB%B6%E8%A1%8C%E4%B8%BA-%E5%A4%96%E8%A7%82%E9%97%AE%E9%A2%98
“订阅信息丢失”：保存频率低，sudo 关机重启属于强关，软件没有反应的时间。请正常退出软件关机。
