### ISSUE TITLE
使用疑问：「trajon-go插件该如何设置？  」

### ISSUE THREAD

**Issue by gzz4454** [Qv2ray/Qv2ray#1185]
安装v2ray内核时提示[Warning] v2ray.com/core: V2Ray 4.33.0 started
删除v2ray内核后提示[FATAL] 2020/12/24 19:34:32 github.com/p4gefau1t/trojan-go/url.(*url).Handle:option.go:73 empty host
请问该如何解决？

**Comment by MarksonHon** [comment]
请去 qv2ray.net 读文档

对于 Qv2ray 来讲，V2Ray 是一定要有的，除非你关闭插件集成功能。

**Comment by DuckSoft** [comment]
empty host：你 Host 没填。
