### ISSUE TITLE
真的是一脸懵，我的问题怎么就关闭了？

### ISSUE THREAD

**Issue by gzz4454** [Qv2ray/Qv2ray#1186]
本来就是按qv2ray文档里面的步骤走的，现在遇到问题还让我去看文档？
那文档里连步骤都没说明，trajon-go插件安装完之后要安装内核的事都没说清楚，看那文档有啥用啊
我自己一边百度一边把v2ray内核和trajon-go内核设置好现在遇到问题还让我去看文档？
![Screenshot_20201225-075309.jpg](https://user-images.githubusercontent.com/76430410/103111307-8c662b00-4686-11eb-8c3a-428008396461.jpg)

**Comment by DuckSoft** [comment]
![76FBD4C4-6690-4079-9146-A26C8C4F70AC](https://user-images.githubusercontent.com/7822648/103112560-4f536600-4691-11eb-8f05-d6aed0750b7e.png)
这是啥？你下载个插件，连他首页看一眼都不看的吗？开发者又不欠你的，至于这么大怨念吗？不养大爷，大爷您找个别的地方吧。

**Comment by DuckSoft** [comment]
@DuckSoft 最后，感谢你为开发者送出的圣诞大礼包。
