### ISSUE TITLE
每次系统重启后，配置文件丢失

### ISSUE THREAD

**Issue by Yofo-me** [Qv2ray/Qv2ray#1187]
在我的`ubuntu 20.04LTS`上，每次重新启动电脑后软件中的订阅及节点配置文件丢失，很奇怪的BUG。之前装的是稳定版的`deb`文件，后来`apt-get remove --purge -y qv2ray`后重新启动后重新安装为2.7版本，重新订阅后再重启电脑仍然出现上面的问题

**Comment by DuckSoft** [comment]
@Yofo-me 借问一下，是gnome wayland 桌面环境吗

**Comment by DuckSoft** [comment]
另外，先确认一下你的“重启”方式：是sudo reboot，还是正常在会话管理器中结束会话；是否尝试过有先手动退出qv2ray再重启。目前信息量不是很足够，我自己也有在用ubuntu 20.04，桌面是自己装的kde，没有上述问题。

**Comment by Yofo-me** [comment]
用的是sudo reboot

**Comment by DuckSoft** [comment]
那自然会出现问题。Qv2ray 是惰性保存配置文件的，如果你强制重启，Qv2ray 没有反应时间来保存文件，直接就被系统 KILL 了，数据丢了也正常。
