### ISSUE TITLE
请求：Qv2ray v2.7.0-pre1 预览版 追加linux的deb安装包。

### ISSUE THREAD

**Issue by xiangdongping999** [Qv2ray/Qv2ray#1189]
工程师辛苦了！
Qv2ray v2.7.0-pre1 预览版 linux只有appimage，没有deb安装包。
请求追加一个安装包。
虽然，appimage也可以使用，但是它对桌面快捷方式的支持不如deb安装方式友好。
所以还是希望能追加一个安装包。

               以上，表示感谢！

**Comment by uniartisan** [comment]
> 工程师辛苦了！
> Qv2ray v2.7.0-pre1 预览版 linux只有appimage，没有deb安装包。
> 请求追加一个安装包。
> 虽然，appimage也可以使用，但是它对桌面快捷方式的支持不如deb安装方式友好。
> 所以还是希望能追加一个安装包。
> 
> ```
>            以上，表示感谢！ 
> ```

https://github.com/TheAssassin/AppImageLauncher

**Comment by dyhkwong** [comment]
从 Actions 里拿 https://github.com/Qv2ray/Qv2ray/actions/runs/347009927

**Comment by DuckSoft** [comment]
Debian 稳定仓库：https://qv2ray.net/debian
Debian 持续构建仓库：https://qv2ray.net/debian-dev

**Comment by xiangdongping999** [comment]
谢谢
