### ISSUE TITLE
使用疑问：V2Ray Core Check exit code 11 on Kali

### ISSUE THREAD

**Issue by Aug-YCh** [Qv2ray/Qv2ray#1191]
### 你想做啥？
配置可用的v2ray代理

### 你目前试了啥？
按照文档进行配置，但是在kernel setting处遇到问题，报错信息为V2ray Core failed with an exit code:11

### 其他要补充的信息？
V2ray Core Executable Path 和 Assets Directory 配置应该OK
![Screenshot](https://tva1.sinaimg.cn/large/0081Kckwgy1gm5plzowpuj30is03zaat.jpg)

**Comment by DuckSoft** [comment]
你要不要手动执行一下你的 v2ray 核心看看会发生什么？

**Comment by Aug-YCh** [comment]
> 你要不要手动执行一下你的 v2ray 核心看看会发生什么？

```V2Ray 4.33.0 (user) 20201222-191220 (go1.15.6 linux/amd64)
A unified platform for anti-censorship.
2020/12/30 11:14:58 Using config from STDIN
2020/12/30 11:14:58 [Info] v2ray.com/core/main/jsonem: Reading config: stdin:```

**Comment by DuckSoft** [comment]
先请问是从何种渠道安装的，看图像是从 Snap 装的，先确认一下。

**Comment by DuckSoft** [comment]
抱歉，我好像眼瞎了，你是不是 `/usr/bin/v2ray` 是个目录呀？
真正的 `v2ray` 在 `/usr/bin/v2ray/v2ray`？

**Comment by Aug-YCh** [comment]
> 抱歉，我好像眼瞎了，你是不是 `/usr/bin/v2ray` 是个目录呀？真正的 `v2ray` 在 `/usr/bin/v2ray/v2ray`？
> 
> 新版已对这种睿智行为做了基本的检测，确保不会出现这样的问题：
> ![图片](https://user-images.githubusercontent.com/7822648/103328139-8ad7a100-4a92-11eb-938b-9ab9b6b91e84.png)

Hi, 不是这样子的。你可以看到在截图种当我输入`/usr/bin/v2ray`的时候字体颜色为绿色。在我使用的zsh中，这代表输入的是一个可执行文件。

**Comment by DuckSoft** [comment]
hmm... 那么请问是从何种渠道安装的呢？是 Snapcraft 吗？还是原生的 Debian 包？

**Comment by Aug-YCh** [comment]
使用的是Debian包

**Comment by Aug-YCh** [comment]
![可执行文件信息](https://tva1.sinaimg.cn/large/0081Kckwgy1gm6j8g5w66j30kn01d3yq.jpg)

**Comment by DuckSoft** [comment]
Qv2ray 的安装方式呢？

**Comment by Aug-YCh** [comment]
以`./Qv2ray.v2.6.3.linux-x64.AppImage`直接运行的AppImage

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/103379140-96bd7480-4b1f-11eb-8f97-ab6a33ed765c.png)
好，请尝试使用我们的 Debian 镜像源。我依稀记得 AppImage 在 Kali 上会有奇怪的问题。

https://qv2ray.net/debian

Kali 的代号应该是 `unstable`，注意替换。

**Comment by Aug-YCh** [comment]
> ![图片](https://user-images.githubusercontent.com/7822648/103379140-96bd7480-4b1f-11eb-8f97-ab6a33ed765c.png)
> 好，请尝试使用我们的 Debian 镜像源。我依稀记得 AppImage 在 Kali 上会有奇怪的问题。
> 
> https://qv2ray.net/debian
> 
> Kali 的代号应该是 `unstable`，注意替换文中的 `$YOUR_DISTRIBUTION`。

好的 我尝试下

**Comment by Aug-YCh** [comment]
emmm sorry 可能还是有一些问题

![image](https://user-images.githubusercontent.com/44114934/103379663-5c54d700-4b21-11eb-9b04-5a03f4c17cf7.png)

**Comment by Aug-YCh** [comment]
可以告诉我exit code 11的含义是什么吗 也许我能找到一些线索

**Comment by DuckSoft** [comment]
你没有退出当前实例。请退出当前实例再运行。

**Comment by Aug-YCh** [comment]
哦好的

**Comment by Aug-YCh** [comment]
十分感谢 解决了
![image](https://user-images.githubusercontent.com/44114934/103379756-af2e8e80-4b21-11eb-8235-ff7a0475179b.png)
AppImage的玄学问题😂

**Comment by DuckSoft** [comment]
Fine. 欢迎加入 Qv2ray User Group @ Telegram: https://t.me/qv2ray
如果胆子大，可以使用我们的每日更新仓库（真的是每日更新）：https://qv2ray.net/debian-dev

多看文档：https://qv2ray.net

**Comment by Aug-YCh** [comment]
好的
感谢您的帮助 幸苦了
