### ISSUE TITLE
Mac 暗黑主题 日志字体没有适配

### ISSUE THREAD

**Issue by beijiahiddink** [Qv2ray/Qv2ray#1192]
![2020-12-31 at 3 53 PM](https://user-images.githubusercontent.com/12680461/103400535-71ad1e00-4b80-11eb-91ca-047bcc4d7c86.png)

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/103400600-a7ea9d80-4b80-11eb-8297-b5760d1d38a6.png)
Please Read The Fancy Documentation: https://qv2ray.net/en/getting-started/step5.html
