### ISSUE TITLE
功能请求：为分出站流量统计增加对VLESS的支持

### ISSUE THREAD

**Issue by liuchibing** [Qv2ray/Qv2ray#1193]
-----------------

**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

目前开启分出站统计之后流量统计部分直接一直为0，想看到情况只能关闭分出站统计将流量统计混在一起，然后推测。。。

**简单描述你预期的解决方案？**

将VLESS流量认作代理流量

**你有想到其他比较容易实现的解决方案吗？**

无

**补充内容**
无

**Comment by DuckSoft** [comment]
https://github.com/Qv2ray/Qv2ray/releases/tag/v2.7.0-pre1
