### ISSUE TITLE
版本2.6.3 订阅更新没有获取到节点，但实际上该订阅地址有效？

### ISSUE THREAD

**Issue by dufengming2008** [Qv2ray/Qv2ray#1194]
到底是bug还是我打开的方式不对

**Comment by DuckSoft** [comment]
1. 域名被污染：如以 `raw.githubusercontent.com` 为主的白嫖订阅，DNS 被污染，无法载入实属正常。这种情况建议先连上一个可用的节点，再在首选项->Qv2ray 代理中将地址指向 V2Ray 入站，最后通过代理更新订阅。
2. 订阅不支持：如试图用 Qv2ray 去订阅 Clash 订阅等。这种情况建议找正确的订阅。
