### ISSUE TITLE
这是怎么回事

### ISSUE THREAD

**Issue by wtzabc123** [Qv2ray/Qv2ray#1198]
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 103.135.100.60:28553: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by EpLiar** [comment]
不影响使用就不用太在意

**Comment by MarksonHon** [comment]
@wtzabc123 你节点应该死了 换一个吧

**Comment by MarksonHon** [comment]
另外 建议进群：
<https://t.me/qv2ray>
