### ISSUE TITLE
再次打开时保留上次的窗口大小 

### ISSUE THREAD

**Issue by Rhythmicc** [Qv2ray/Qv2ray#1199]
-----------------

**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

每次打开都要调整窗口大小，太烦了。

**简单描述你预期的解决方案？**

再次打开软件时保留上次窗口大小

**你有想到其他比较容易实现的解决方案吗？**

每次打开我自己调整。

**补充内容**
嘤嘤嘤；

**Comment by cangyin** [comment]
此特性已在 dev 版本中实现。你可以在 [git actions](https://github.com/Qv2ray/Qv2ray/actions) 里面下载使用最近成功构建的一个版本。

**Comment by zhj9709** [comment]
![image](https://user-images.githubusercontent.com/13991774/103473135-15d8d400-4dd0-11eb-92ff-ddaeb1f1e3be.png)
可以记住调整后的样子吗，比如左边那部分自己调窄一点，连接图像收起来，但关闭软件重新打开后又变成下面的样子
![image](https://user-images.githubusercontent.com/13991774/103473164-60f2e700-4dd0-11eb-8ddc-bba9648560a6.png)
