### ISSUE TITLE
在入站设置流量嗅探 配置文件没有指定流量类型。

### ISSUE THREAD

**Issue by fvlw** [Qv2ray/Qv2ray#1200]
![图片](https://user-images.githubusercontent.com/71577616/103471641-96420980-4dbd-11eb-80ee-ba01d9f83e47.png)
![图片](https://user-images.githubusercontent.com/71577616/103471659-bc67a980-4dbd-11eb-9c4b-75cb963770cd.png)

开启了sniffing 但是没有指定流量类型
"destOverride": ["http", "tls" ]

**Comment by dyhkwong** [comment]
Qv2ray.conf 只是 Qv2ray 的配置文件，请到 config.gen.json 里找 "destOverride": ["http", "tls" ]
