### ISSUE TITLE
功能请求：<最小化到 system tray，自动连接上一次connection>

### ISSUE THREAD

**Issue by antiquealive** [Qv2ray/Qv2ray#1201]
希望添加如下功能
1. 打开软件，自动最小化到 system tray。现在每次开机，都要手工点一下。
2. 打开软件，自动连接上一次的connection。现在每次开机，都要手工点一下。
有了这两个功能，就可以彻底开机自启动啦。

其他建议
3. system tray的图标可以自定义，自适应感觉比较啰嗦。自定义，大家自己喜欢什么就自己选呗。管它light theme还是dark theme。仅个人意见。
系统是 win10，软件版本是2.6.3:5840

**Comment by kslr** [comment]
这两个功能都有，你仔细找一下配置

**Comment by antiquealive** [comment]
> 这两个功能都有，你仔细找一下配置

有了，谢谢，在 preference - general settings - auto connect，自动就能最小化了。
