### ISSUE TITLE
使用疑问：通过命令行修改系统代理

### ISSUE THREAD

**Issue by qimingyudaowenti** [Qv2ray/Qv2ray#1202]
### 你想做啥？

在Ubuntu20.04中想通过命令行调整系统代理：
![Screenshot from 2021-01-04 12-51-47](https://user-images.githubusercontent.com/17612199/103502310-cce65580-4e8b-11eb-8997-35a4ee19bee6.png)
（调整Manual/Disabled模式，端口号...）

### 你目前试了啥？

通过gsettings系列命令如 `gsettings get org.gnome.system.proxy mode 'none'` ，无法起到控制效果（至少上图界面内容没有改变）。
### 其他要补充的信息？
观察到 Qv2ray 可以成功的进行修改系统代理，是通过什么方式呢？
我应该如何操作才能通过命令方式修改？
感谢回复~

**Comment by 21wmd** [comment]
你想做什么呀，用命令行的方式设置代理？

**Comment by DuckSoft** [comment]
请在 Qv2ray 代码仓库中搜索关键词 gsettings。

**Comment by ymshenyu** [comment]
设置界面不是反应式的，你需要切换到其他关闭这个窗口然后重新打开才能看到更新之后的结果

**Comment by qimingyudaowenti** [comment]
> 你想做什么呀，用命令行的方式设置代理？

对，模仿Qv2ray修改代理的方式

**Comment by qimingyudaowenti** [comment]
> 请在 Qv2ray 代码仓库中搜索关键词 gsettings。

简单观察了下，发现也是用的`gsettings`命令，因为个人能力欠缺，没有看出来多余操作。是仅用`gsettings`就能实现吗？

**Comment by qimingyudaowenti** [comment]
> 设置界面不是反应式的，你需要关闭这个窗口然后重新打开才能看到更新之后的结果

重新打开设置界面也不行，难道[需要重启/重登录](https://unix.stackexchange.com/questions/152260/set-ubuntu-system-proxy-settings-without-restart-from-commandline)？

**Comment by qimingyudaowenti** [comment]
发现问题了，退出conda默认的base环境，用`gsettings`即可修改成功，感谢各位的回复~
