### ISSUE TITLE
mac 10.13.6 用v2.7.0-pre1加载xray1.2.0后节点连接后cpu占用率120%，风扇狂转，ui锁死

### ISSUE THREAD

**Issue by trxsudo** [Qv2ray/Qv2ray#1203]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
mac 10.13.6 用qv2ray v2.7.0-pre1加载xray-core（版本1.2.0和1.0.0均测试）后节点连接后cpu占用率120%，风扇狂转，并且dock ui界面锁死，无法对客户端做任何修改，但客户端后台似乎是在运行，需要强行关闭，强行关闭后风扇消停

## 如何触发这个 Bug：

1. 只要连接xray节点就会发生
2. 不知道是否与macos版本有关，10.13.6是很稳定的版本，占很大的macos用户群体，希望能够对这个系统版本多多支持
3.

### 相关截图或日志

请从此行下面的行开始粘贴 Qv2ray 日志：
﻿﻿节点连接后ui锁死，无法复制日志

## 系统信息
用的是vless + tcp + xtls
xraycore 1.0.0 / xraycore 1.2.0
qv2ray v2.7.0-pre1 (以前的旧版本无法加载xraycore）

### 操作系统
- macOS 10.13.6 high sierra

**Comment by DuckSoft** [comment]
@trxsudo 是grpc与macos10.13兼容性的问题，首选项找到api子系统并关闭可暂时缓解。此外，macos10.13苹果官方已经停止支持，我们也已经放弃支持。
