### ISSUE TITLE
功能请求：记住软件调整后的布局

### ISSUE THREAD

**Issue by zhj9709** [Qv2ray/Qv2ray#1204]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

请尽可能清晰简洁地描述问题。

![image](https://user-images.githubusercontent.com/13991774/103473135-15d8d400-4dd0-11eb-92ff-ddaeb1f1e3be.png)
可以记住调整后的样子吗，比如左边那部分自己调窄一点，连接图像收起来，但关闭软件重新打开后又变成下面的样子
![image](https://user-images.githubusercontent.com/13991774/103473164-60f2e700-4dd0-11eb-8ddc-bba9648560a6.png)

**简单描述你预期的解决方案？**

请尽可能清晰简洁描述问题。

**Comment by U-v-U** [comment]
Should have been implemented in dev.

**Comment by DuckSoft** [comment]
Qt 6 已至，我们的 UI 重做计划也已经开始，所以老 UI 的新功能近期大概是不会整了。

感谢你的反馈。
