### ISSUE TITLE
使用疑问：「 请问如何在树莓派4B（ARM）上安装 」

### ISSUE THREAD

**Issue by zhangyiming748** [Qv2ray/Qv2ray#1207]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

### 你想做啥？
*简要描述你的最原始的目的。*

我想在树莓派上运行QV2ray
### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

我看到其他的issue有人说安装是可行的，但是没有说方法
### 其他要补充的信息？
*在此附加其他需要补充的信息。*
软件很好用，不想再花时间成本去熟悉其他软件了

**Comment by MarksonHon** [comment]
加入群聊：
<https://t.me/qv2ray>

**Comment by DuckSoft** [comment]
如果使用的是 Debian / Ubuntu 系列的系统，可以直接从 Snapcraft 安装：https://snapcraft.io/qv2ray
当然，如果你用的是树莓派那个什么 Raspberrian OS，他自己有问题，Snap 恐怕是装不上。
除此之外，你也可以手动凑齐依赖编译，参见：https://qv2ray.net/en/hacking/manuallybuild.html
