### ISSUE TITLE
使用疑问：如何配置steam下载直连社区代理

### ISSUE THREAD

**Issue by Logic530** [Qv2ray/Qv2ray#1208]
### 你想做啥？
*如题。*

### 你目前试了啥？
+ 启用了绕过大陆功能
+ 阅读了路由功能的说明
+ 查找了预定义域名列表，发现并没有相关的列表

### 其他要补充的信息？
*本来还想加telegram群组问问，入群验证太难了。*

**Comment by MarksonHon** [comment]
去阅读V2Ray的文档吧：
https://www.v2fly.org

**Comment by DuckSoft** [comment]
domain-list-community 里的 `geosite:steam` 的粒度太粗了，没有区分社区和下载，这是一个问题，建议同时给上游开 issue。
目前我自用的方法是：在下载的时候观察刷出来的日志，找到下载的网址的规律，然后手动添加到分流矩阵的域名直连位置。
社区维护的软件，主要靠志愿者自行维护，建议去上游开个 issue，或者自力更生整一下，然后分享一下你的方法。

**Comment by BoBppy** [comment]
高级路由配置，用domain:列举完需要代理的例如steamcommunity.com。
鄙人目前用的就是这样的方法（
