### ISSUE TITLE
任意门是端口转发吗？应该怎么使用

### ISSUE THREAD

**Issue by heiyutian** [Qv2ray/Qv2ray#1209]
我理解的任意门就是ss{ssr}的客户端上面的端口转发，也不知道是不是一样，在ss上面填写了端口转发的ip和端口，同时填写一下本地端口之后，再去到比如浏览器插件填写代理类型和本地端口，就可以成功中转。
但是qv2ray并没有本地端口这个选项，那我应该在浏览器插件怎么弄，才能让我想转发的Ip先经过v2流量来中转。

一楼说没看懂，我简单说下我想干嘛。
我想在qv2ray使用端口转发这个功能，以前使用过ss{ssr}的这个功能，在qv2ray上面只发现了类似的任意门，所以我猜想这个是不是端口转发。
我想让前置是v2ray服务器，然后转发一个ip的流量，比如一些冷门地区的http代理ip和端口，因为这个http代理的直连速度很慢或者直连不了，但是中转之后是可以很快的，目前是可以通过路由器开启代理或者用ss的端口转发起到中转效果，qv2ray的任意门如果也是端口转发，我想知道为什么没有本地端口这个选项，我理解的是必须要配置本地端口，然后去浏览器插件配置才能转发流量吧。

再次更新，我不是说不会用qv2ray开启本地代理，我说的是想用端口转发来中转代理ip。

**Comment by DuckSoft** [comment]
原谅我语文不好，能请您更简练地描述一下你的最根本需求吗？上面这一大堆实在没看懂，抱歉。

**Comment by MarksonHon** [comment]
@heiyutian <https://www.v2fly.org>
请

**Comment by DuckSoft** [comment]
明白你的需求了，你可以使用复杂配置，下面是一个示例：
<img width="655" alt="图片" src="https://user-images.githubusercontent.com/7822648/103866062-20f97000-5100-11eb-956f-b7e2871475f0.png">
<img width="898" alt="图片" src="https://user-images.githubusercontent.com/7822648/103866118-39698a80-5100-11eb-850d-1f287e25a4cd.png">

**Comment by heiyutian** [comment]
> 明白你的需求了，你可以使用复杂配置，下面是一个示例：
> <img alt="图片" width="655" src="https://user-images.githubusercontent.com/7822648/103866062-20f97000-5100-11eb-956f-b7e2871475f0.png">
> <img alt="图片" width="898" src="https://user-images.githubusercontent.com/7822648/103866118-39698a80-5100-11eb-850d-1f287e25a4cd.png">

感谢你的方法，成功转发中转了流量，目前有个小问题，不知道能不能解决，就是如果我使用了中转，就需要一个独立的本地端口，同时需要独立的一个v2服务器来连接。这样如果我要切换，就需要同时切换所选v2服务器和浏览器插件的本地端口代理选项，我在ss上面设置端口转发的时候，我只需要切换浏览器插件的本地端口代理选项就行了，ss客户端不需要切换服务器。
比如ss的socks的端口是1080，然后转发的本地端口设置了是1082，我只需要切换浏览器的插件选项就行了，但是在v2这里这样做不行，切换了端口不能上网，必须同时要切换v2服务器才行，我知道这个可能很难实现，复杂配置第一次玩，所以可能是我不会，如果不支持的话就算了。非常感谢你的图片教程。

**Comment by DuckSoft** [comment]
你也许需要的不是端口转发，而是链式代理。参考图：
![图片](https://user-images.githubusercontent.com/7822648/103879123-62931680-5112-11eb-8088-311bcf8eb013.png)
![图片](https://user-images.githubusercontent.com/7822648/103879144-6b83e800-5112-11eb-905e-86630739fe7b.png)
这样浏览器只需要在三个端口之间切换即可做到直连JP、直连CN2、CN2中转JP。

**Comment by heiyutian** [comment]
> 你也许需要的不是端口转发，而是链式代理。参考图：
> ![图片](https://user-images.githubusercontent.com/7822648/103879123-62931680-5112-11eb-8088-311bcf8eb013.png)
> ![图片](https://user-images.githubusercontent.com/7822648/103879144-6b83e800-5112-11eb-905e-86630739fe7b.png)
> 这样浏览器只需要在三个端口之间切换即可做到直连JP、直连CN2、CN2中转JP。
> 路由编辑器的确需要一点时间去熟悉和学习。

好吧，可能需要系统性的学习才能玩好这个，因为不是程序员所以不是很会玩这个，因为需要一些冷门地区的ip去访问那些国家的资源，所以才提出这个想法。我还有一个问题想请教，qv2ray能不能在电脑端多开，比如我想打开两个qv2ray，一个使用1080用来浏览器访问，因为经常碰到谷歌验证，所以我可能需要频繁切换服务器来避免这个情况，所以我就想另一个使用1081，这个用来使用一些需要稳定的服务，比如说我idm下载文件，因为不能让下载中断，所以肯定不能使用1080，我尝试复制到另一个文件夹来双开，但是点击后还是回到原先打开的qv2ray客户端了，不知道这个是不是限制死了不能多开。

**Comment by cpdyj** [comment]
> > 你也许需要的不是端口转发，而是链式代理。参考图：
> > ![图片](https://user-images.githubusercontent.com/7822648/103879123-62931680-5112-11eb-8088-311bcf8eb013.png)
> > ![图片](https://user-images.githubusercontent.com/7822648/103879144-6b83e800-5112-11eb-905e-86630739fe7b.png)
> > 这样浏览器只需要在三个端口之间切换即可做到直连JP、直连CN2、CN2中转JP。
> > 路由编辑器的确需要一点时间去熟悉和学习。
> 
> 好吧，可能需要系统性的学习才能玩好这个，因为不是程序员所以不是很会玩这个，因为需要一些冷门地区的ip去访问那些国家的资源，所以才提出这个想法。我还有一个问题想请教，qv2ray能不能在电脑端多开，比如我想打开两个qv2ray，一个使用1080用来浏览器访问，因为经常碰到谷歌验证，所以我可能需要频繁切换服务器来避免这个情况，所以我就想另一个使用1081，这个用来使用一些需要稳定的服务，比如说我idm下载文件，因为不能让下载中断，所以肯定不能使用1080，我尝试复制到另一个文件夹来双开，但是点击后还是回到原先打开的qv2ray客户端了，不知道这个是不是限制死了不能多开。

复杂代理功能可以添加任意多个入站接口，路由和出站可以自行配置
