### ISSUE TITLE
使用疑问：2.7.0-pre1:6039 Trojan-Go

### ISSUE THREAD

**Issue by Dameko27r** [Qv2ray/Qv2ray#1212]
### 你想做啥？
*简要描述你的最原始的目的。*
MAC 2.7.0-pre1:6039 Trojan go协议下未能处理出站流量
### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
在Windows同版本号上试同一个配置是正常运行的

### 其他要补充的信息？
*在此附加其他需要补充的信息。*
2021/01/08 20:40:03 [Info] [3779809408] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:access-sngapm.qcloud.com:443 > common/retry: [dial tcp: lookup access-sngapm.qcloud.com on 8.8.8.8:53: no such host] > common/retry: all retry attempts failed
2021/01/08 20:40:03 [Info] [3779809408] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2021/01/08 20:40:03 [Info] [2139272112] proxy/http: request to Method [CONNECT] Host [access-sngapm.qcloud.com:443] with URL [//access-sngapm.qcloud.com:443]
2021/01/08 20:40:03 [Info] [2139272112] app/dispatcher: taking detour [DIRECT] for [tcp:access-sngapm.qcloud.com:443]
2021/01/08 20:40:03 [Info] [2139272112] proxy/freedom: opening connection to tcp:access-sngapm.qcloud.com:443
2021/01/08 20:40:03 [Info] [2139272112] transport/internet/tcp: dialing TCP to tcp:access-sngapm.qcloud.com:443
2021/01/08 20:40:03 127.0.0.1:55723 accepted //access-sngapm.qcloud.com:443 [DIRECT]

**Comment by MarksonHon** [comment]
提供下详细信息，包括 Trojan-Go 插件版本信息、Trojan-Go 内核版本信息。同时，也说明下你的 Trojan-Go 是如何导入到 Qv2ray的，并确认下你是否用了JSON配置或复杂配置。

**Comment by DuckSoft** [comment]
只见 Xray 核心日志，却未见你的 Trojan-Go 核心日志，这很奇怪。Qv2ray 会把两个核心的日志混在一起输出。
如 @MarksonHon 所说，请提供更为详细的信息，以足够允许开发者复现问题的程度为准。
现在这些信息，实在是令人摸不着头脑，爱莫能助。

**Comment by DuckSoft** [comment]
无回应，暂时关闭了。等补充信息再开。

**Comment by Dameko27r** [comment]
提醒到没有见到Trojan-Go核心日志发现导入路径添加到压缩文件上了。MAC还用不习惯..抱歉otz
