### ISSUE TITLE
win10 设置系统编码为utf8的时候乱码

### ISSUE THREAD

**Issue by Korov** [Qv2ray/Qv2ray#1215]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 如何触发这个 Bug：

1. 设置语言为utf8
![image](https://user-images.githubusercontent.com/45894441/104140765-f6ecca00-53ed-11eb-9563-36f376b00780.png)

2. 安装
![image](https://user-images.githubusercontent.com/45894441/104140747-dc1a5580-53ed-11eb-9c05-5be2d69bedeb.png)

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 
编译信息：
额外编译信息：
```

### 操作系统

- Linux
- macOS
- Windows

### 安装来源

- ArchLinuxCN - 稳定版
- ArchLinuxCN - 开发版
- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版
- Fedora - 稳定版
- Fedora - 开发版
- openSUSE - 稳定版
- openSUSE - 开发版
- Flathub 包
- Snap 包
- Homebrew Cask
- Github Release / Scoop / Chocolatey
- 手动编译

## 附加信息

*请注意打码隐私相关信息。*

**Comment by EpLiar** [comment]
https://github.com/Qv2ray/Qv2ray/issues/947
