### ISSUE TITLE
延迟测试添加真连接延迟的测试

### ISSUE THREAD

**Issue by 2293310198** [Qv2ray/Qv2ray#1216]
使用默认的TCping测试的连接，延迟很低但依然无法访问Google
是否可以考虑另加真延迟测试，连接上后尝试访问一次google，能正常访问的才记录延迟

另，可否添加自动去重功能

**Comment by DuckSoft** [comment]
https://t.me/qv2ray_dev/119

```
开发组关于“节点去重”功能的最终决定

正常的使用场景下，没有哪个机场会给你出现重复节点的订阅，就算有，这个问题也应该是机场的问题，而非客户端应该处理的问题。

除此之外，节点去重的最常见场景是四处找一些所谓的免费白嫖订阅，然后搅合在一起，结果却发现这些节点全是重样的，只是名字不一样。

我们认为，我们的目标用户群不会是这样的不注重自己的信息安全、只会搜集并使用白嫖节点的人，而开发者们也没有必要为自己永远不会用到的功能付出时间和精力。
```

**Comment by DuckSoft** [comment]
> 是否可以考虑另加真延迟测试，连接上后尝试访问一次google，能正常访问的才记录延迟

目前已有对已连接的节点做真延迟测试的功能。

对于“批量的真延迟测试”，开发者最近都在写作业、交福报，暂时没有人动工……
如果你有兴趣，可以考虑实现一个，发个 Pull Request 造福一下大家。

**Comment by 2293310198** [comment]
> 
> 
> > [https://t.me/qv2ray_dev/119 ](https://t.me/qv2ray_dev/119)
> 
> **开发组关于“节点去重”功能的最终决定 **
> 
> 正常的使用场景下，没有哪个机场会给你出现重复节点的订阅，就算有，这个问题也应该是机场的问题，而非客户端应该处理的问题。
> 
> 除此之外，节点去重的最常见场景是四处找一些所谓的免费白嫖订阅，然后搅合在一起，结果却发现这些节点全是重样的，只是名字不一样。
> 
> 我们认为，我们的目标用户群不会是这样的不注重自己的信息安全、只会搜集并使用白嫖节点的人，而开发者们也没有必要为自己永远不会用到的功能付出时间和精力。

> 

> 

> 

> 

> 

> 
> 
> > https://t.me/qv2ray_dev/119
> 
> **开发组关于“节点去重”功能的最终决定**
> 
> 正常的使用场景下，没有哪个机场会给你出现重复节点的订阅，就算有，这个问题也应该是机场的问题，而非客户端应该处理的问题。
> 
> 除此之外，节点去重的最常见场景是四处找一些所谓的免费白嫖订阅，然后搅合在一起，结果却发现这些节点全是重样的，只是名字不一样。
> 
> 我们认为，我们的目标用户群不会是这样的不注重自己的信息安全、只会搜集并使用白嫖节点的人，而开发者们也没有必要为自己永远不会用到的功能付出时间和精力。

👍，我自己有自建的，但是我**同时**也订阅免费节点，主要是因为有时候不稳而且我挂BT会通过不同节点寻找不同地区连接到存活的种子，另外，重复并不是由于订阅导致的。。。粘贴的时候多粘了一份
