### ISSUE TITLE
系统托盘在断开后依旧保持点亮

### ISSUE THREAD

**Issue by lian-longfeng** [Qv2ray/Qv2ray#1217]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
系统托盘在断开连接之后依然保持点亮状态：

## 如何触发这个 Bug：

1. 打开app，系统托盘未点亮
2. 连接，系统托盘点亮
3. 断开连接，系统托盘依旧点亮

### 相关截图或日志
![image](https://user-images.githubusercontent.com/58188246/104201497-d3c71800-53f7-11eb-9b64-893a509e1810.png)

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.ubuntu-16.04
```

### 操作系统

- Linux (Manjaro)
### 安装来源
- Github Release / Scoop / Chocolatey

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
是 AppImage 已知问题。换 AUR 编译可解。
