### ISSUE TITLE
Windows 更改屏幕分辨率后 UI 位置记忆工作异常

### ISSUE THREAD

**Issue by sadan9** [Qv2ray/Qv2ray#1220]
## 简单描述这个 Bug:
windows双屏环境，远程桌面登录后，Qv2ray的窗口有可能找不到。

## 如何触发这个 Bug：

1. 机器为双屏，使用帐号本地登录windows，并将Qv2ray移动到副屏上
2. 使用windows远程桌面客户端登录（1）中机器，则QV2ray窗口会不见（初步怀疑窗体定位在屏幕外），无法操作，重启也不行。
3. 可以通过关闭软件，删除config/UIState.json解决。

附：出现问题时UIState.json内容：
{
    "MainWindow": {
        "height": 769,
        "width": 790,
        "x": 3990,
        "y": 575
    },
    "RouteEditor": {
    }
}

**Comment by EpLiar** [comment]
如果其他程序在副屏也不可见的话，那此问题和 Qv2ray 就没有什么关系了，请确认一下

**Comment by sadan9** [comment]
试了几个其他程序（比如任务管理器，记事本，chrome），副屏上的程序会被重置窗体位置。

**Comment by EpLiar** [comment]
> 试了几个其他程序（比如任务管理器，记事本，chrome），副屏上的程序会被重置窗体位置。

试试看其他使用了 qt 框架编写的程序

**Comment by sadan9** [comment]
这…………手边好像没QT框架编写的应用……
话说能否在双击任务栏图标弹出窗体的时候对XY轴坐标做一个判断，如果大于屏幕分辨率则重置窗体坐标……

**Comment by EpLiar** [comment]
> 这…………手边好像没QT框架编写的应用……

qBittorrent https://github.com/qbittorrent/qBittorrent

> 话说能否在双击任务栏图标弹出窗体的时候对XY轴坐标做一个判断，如果大于屏幕分辨率则重置窗体坐标……

可能和现有逻辑有一些冲突

**Comment by DuckSoft** [comment]
可以考虑加一个禁用 UI 位置记忆的选项暂时缓解，不过这个问题的确需要一点时间来调查……

**Comment by anonymous-cn** [comment]
我也有遇到这样的问题，双屏幕时吧窗口放在了副屏幕，关机（笔记本电脑）带回家，不接扩展屏时无法选中软件界面

**Comment by dyhkwong** [comment]
在单屏幕下把屏幕分辨率改小也能复现，窗体定位在屏幕外了

**Comment by U-v-U** [comment]
Closing due to the removal of this feature.
