### ISSUE TITLE
功能请求：禁用系统代理支持记忆

### ISSUE THREAD

**Issue by qingsongya** [Qv2ray/Qv2ray#1221]
禁用系统代理有这样的一个现象，当禁用系统代理后，重启电脑，这时系统代理又是开启的状态。所以希望支持记忆功能，记住禁用系统代理的操作，即使重启电脑也不会影响。

**Comment by DuckSoft** [comment]
托盘右键菜单里的是一次性行为，首选项——入站设置里的才是持久行为。

**Comment by EpLiar** [comment]
作为一个长期不使用系统代理的用户表示，无法复现。

还请提供操作系统以及 Qv 的版本号

**Comment by 2014CAIS01** [comment]
@qingsongya 首选项——入站设置 勾选时会在连接成功后设置系统代理，与是否重启或是否在菜单里关闭无关。如果你开机设置了自动连接，那重启电脑，连接成功后自然就设置了系统代理。
