### ISSUE TITLE
使用疑问：「  为啥Qv2ray会有一个屏幕录制的操作」

### ISSUE THREAD

**Issue by Stonewalling** [Qv2ray/Qv2ray#1222]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

`QV_ISSUE_QUESTION_TEMPLATE_PLACEHOLDER`

### 你想做啥？
*简要描述你的最原始的目的。*
为什么Qv2ray mac中的隐私设置里面会有一个屏幕录制的勾选项

**Comment by EpLiar** [comment]
通过二维码导入节点
