### ISSUE TITLE
按钮无法点击

### ISSUE THREAD

**Issue by 2293310198** [Qv2ray/Qv2ray#1223]
![image](https://user-images.githubusercontent.com/30544914/104571538-2c174780-568e-11eb-82c1-85e0540a4321.png)
提示更新但是点不了按钮。。。被任务栏挡住了

**Comment by EpLiar** [comment]
换个大点的显示器就好了…… 这个和 Qv 毫无关系

**Comment by DuckSoft** [comment]
按下你键盘的空格键。

**Comment by cpdyj** [comment]
你可以通过在窗口中按下 `Ctrl + C` 获取窗口中的文字，并通过Tab键切换选中的按钮。至少在Windows系统下，大多数对话框皆可如此处理
