### ISSUE TITLE
使用疑问：「运行报错failed to load system root certificate > SecTrustSettingsCopyCertificates error: -25300」

### ISSUE THREAD

**Issue by lbylbtlbylbt** [Qv2ray/Qv2ray#1226]
*简要描述你的最原始的目的。*
Qv2ray报错：
Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://1.0.0.1/wb2ray):  > x509: failed to load system roots and no roots provided; SecTrustSettingsCopyCertificates error: -25300 v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://1.0.0.1/wb2ray):  > dial tcp 1.0.0.1:443: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

2021/01/17 11:05:16 [Error] v2ray.com/core/transport/internet/tls: failed to load system root certificate > SecTrustSettingsCopyCertificates error: -25300

前一晚还是可以正常运行的，同环境下的手机也可以正常连接服务器。

### 你目前试了啥？
尝试更新、重装了服务器和本地的core文件，并未解决。（还尝试加入电报组。。但是点错了验证答案。。。）

求解答协助，谢谢

**Comment by DuckSoft** [comment]
1. 这是核心的报错，不是 Qv2ray 的报错
2. `failed to load system root certificate > SecTrustSettingsCopyCertificates error: -25300` 这看起来是无法正确加载 Windows 的系统证书存储，建议你修复一下操作系统。
