### ISSUE TITLE
Mac big sur 下打开软件无响应

### ISSUE THREAD

**Issue by WEIFZH** [Qv2ray/Qv2ray#1229]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
在Mac big sur 系统下，软件突然打不开了，前几天还能用，版本2.6.3 和2.6.1 都尝试过。

## 如何触发这个 Bug：

1. 
2. 
3. 
4. 

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 
编译信息：
额外编译信息：
```

### 操作系统

- macOS

### 安装来源

- Github Release / Scoop / Chocolatey

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
@WEIFZH 重启

**Comment by WEIFZH** [comment]
> @WEIFZH 重启

谢谢，重启后问题已解决！

**Comment by shuiRong** [comment]
我也遇到相同问题一段时间了，补充些说明：那是一个普通的中午...

我和同事去吃饭，回来后也没动电脑，电脑就会进入**睡眠模式**。下午两点等我再打开电脑时，电脑从睡眠模式唤醒，mac(big sur)自动打开睡眠模式前的应用，然后我就发现qv2ray的软件在Dock栏一直跳，发现它是未响应状态，关掉软件重新打开一样。

重启有时能解决，有时不能解决。不能解决的话，再打开qv2ray，不会出现未响应问题，而是出现下图的问题。

> 能解决的话，我感觉是因为我重启后手动启动qv2ray软件的速度够快，在它自动重启前就打开的话，就正常。

我就奇怪，我并没有在软件里选择“登录时启动”，软件进程为什么在登录时启动呢？而且这个启动并没有启动GUI，只是启动了个没有壳子“进程”（我对进程的理解不一定对），这个进程我通过`ps -ef|grep qv2ray`命令可以看到。
```bash
~ » ps -ef|grep qv2ray    
  501   581     1   0 10:03上午 ??         0:02.54 /Applications/qv2ray.app/Contents/MacOS/qv2ray
  501  1303   730   0 10:09上午 ttys000    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox qv2ray
```
1. 如果我杀掉581，再打开qv2ray，问题依旧如下图。
2. 1303进程 用`sudo kill 1303`杀不掉，不知道这是什么。

![image](https://user-images.githubusercontent.com/16076993/105930853-29045a00-6085-11eb-8586-459f166f7826.png)

**Comment by U-v-U** [comment]
@shuiRong 1. 你只杀掉了 Qv2ray, V2Ray 核心没有杀掉
2. 那是 grep 不是 Qv2ray

**Comment by shuiRong** [comment]
@U-v-U 
我又试了下，通过`ps -ef|grep v2ray`找到v2ray-core，然后杀掉。发现它会自动重启。
又通过` launchctl list | grep 'v2ray'`找到守护进程，通过` launchctl remove yanue.v2rayu.v2ray-core` （的确是yanue.v2rayu.v2ray-core这个名字，感觉很奇怪，我之前安装过v2rayU，但好一段时间再用了，可能是它那边的守护进程一直在的原因）删掉后，问题解决了。再打开qv2ray正常了。

2. 我知道那是grep，没影响，截图是说明我删掉了其他`qv2ray`相关进程，就剩下一个无关的grep了。

**Comment by DuckSoft** [comment]
又是 v2rayU 残留引起的问题……哎……

**Comment by forfuns** [comment]
我是新用户，macos bigsur 11.1 (20C69) , 且是 apple silicon 平台，下载了好几个版本，包括最新的2.7.0-pre2 / Homebrew 版本 都是在dock栏里头跳动，最后停留在无响应状态。请问我该如何解决，需要我提供什么信息吗

**Comment by DuckSoft** [comment]
> 我是新用户，macos bigsur 11.1 (20C69) , 且是 apple silicon 平台，下载了好几个版本，包括最新的2.7.0-pre2 �/ Homebrew 版本 都是在dock栏里头跳动，最后停留在无响应状态。请问我该如何解决，需要我提供什么信息吗

重启
