### ISSUE TITLE
如何编译Windows ARM64版本？

### ISSUE THREAD

**Issue by hmsjy2017** [Qv2ray/Qv2ray#1231]
### 你想做啥？
因为ARM64模拟x86/x64效率比较低，软件运行不流畅，想要编译ARM64原生应用。

### 你目前试了啥？
文档里关于Windows编译的内容是这样的：
> 你可以从 Qv2ray-deps (opens new window) 这个仓库 Release 中下载 gRPC dependency package - x64 (opens new window) 或者 gRPC dependency package - x86 (opens new window)，然后解压到 libs/x**-windows/ 目录, 其中 ** 是 86 或 64；或者：
> 你可以使用 vcpkg install grpc 在 Windows 上通过 MSVC 手动构建 gRPC, 不过这通常会花点时间，且需要稳定的网络环境（没梯子就算了）。

并没有提及ARM64

### 其他要补充的信息？
gRPC似乎已经支持Windows on ARM

**Comment by DuckSoft** [comment]
如你所见，`vcpkg installl grpc` 就可以了。
有其他编译问题欢迎加群 https://t.me/qv2ray 。

**Comment by MarksonHon** [comment]
@hmsjy2017 目前V2Ray/Xray皆提供了 Windows armv7 版本的内核，这是原生的 32 位程序，能够提升运行效率，文档中亦有说明。
