### ISSUE TITLE
使用疑问：「订阅中若只含单个服务配置 ，则订阅无法成功」

### ISSUE THREAD

**Issue by Masterchiefm** [Qv2ray/Qv2ray#1232]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

### 你想做啥？
*简要描述你的最原始的目的。*
我自己搭梯子，为了方便我设置了订阅，所以订阅里只含一个服务器。但是订阅总是显示发现1个，却被过滤掉

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
经测试，我的订阅中若只含1个配置，则在更新订阅后，首先显示发现一个entry，“1 entrie(s) have been found from the subscription source, do you want to continue?” 在继续后，该entry被过滤，显示“1 out of 1 entrie(s) have been filtered out, do you want to continue?” 该情况仅发生在新装的qv2ray上。若qv2ray已有其他entry，则不会发生上述情况。并且，我将我的entry复制一份放入订阅中，即订阅里有2个entry，则订阅能成功。

*简单地说，就是全新安装的qv2ray在更新只含1个entry的订阅时，无法正常添加。*

### 其他要补充的信息？
*使用的测试订阅内容：*
```
dm1lc3M6Ly9ldzBLSUNBaWRpSTZJQ0l5SWl3TkNpQWdJbkJ6SWpvZ0l1YTFpK2l2bFNJc0RRb2dJQ0poWkdRaU9pQWlaWGhoYlhCc1pTNWpiMjBpTEEwS0lDQWljRzl5ZENJNklDSTBORE1pTEEwS0lDQWlhV1FpT2lBaU5HRmpaRFF3T1dNdFl6RTBaUzAwWXpZMkxXSTJZVEF0TWpjM1pUZGxZakZoWkRZMklpd05DaUFnSW1GcFpDSTZJQ0l3SWl3TkNpQWdJbTVsZENJNklDSjNjeUlzRFFvZ0lDSjBlWEJsSWpvZ0ltNXZibVVpTEEwS0lDQWlhRzl6ZENJNklDSmxlR0Z0Y0d4bExtTnZiU0lzRFFvZ0lDSndZWFJvSWpvZ0lpOWxlR0Z0Y0d4bElpd05DaUFnSW5Sc2N5STZJQ0owYkhNaURRcDkNCg==
```
订阅内容放在本地127.0.0.1/v2ray测试，不存在网络连接问题。

![屏幕截图 2021-01-19 012941](https://user-images.githubusercontent.com/35951734/104948591-83a01500-59f8-11eb-9d1c-12c5fcafd157.png)

![屏幕截图 2021-01-19 013030](https://user-images.githubusercontent.com/35951734/104948623-931f5e00-59f8-11eb-9d67-8e3f3753a9a9.png)

![屏幕截图 2021-01-19 013054](https://user-images.githubusercontent.com/35951734/104948643-97e41200-59f8-11eb-8601-c5e9c9a6bd67.png)

**Comment by DuckSoft** [comment]
有意而为之，并不是没成功，而是订阅到的节点数量少到离谱的时候会提醒用户。
有的时候机场下发的节点会突然少很多，但是少的节点并不是全都挂掉，是出于这点考虑的。

期待一下别的思路，或者加个选项，当节点数过少时请不要警告我。
