### ISSUE TITLE
功能请求：<建议增加“复制-组”功能>

### ISSUE THREAD

**Issue by heiyutian** [Qv2ray/Qv2ray#1234]
请尽可能清晰简洁地描述问题。

1. 由于组管理界面删除节点之后不点OK也会被删除，所以希望能让一个组保留下历史节点。因为我每次都是删除一个组的所有节点，然后才更新节点，避免出现混乱。
我知道有把单一个节点复制拷贝出一个新节点的功能，我希望在此基础上增加一个复制组的功能，让之前整个组的节点得以保留。

2. 前置代理使用我还有点疑问顺便问下，我在首选项里面填写了前置代理为本地ssr的127.0.0.1和端口1080，然后去节点右键点击编辑，然后在窗口右边勾选了“使用前置代理“，然后为什么不能上网，是我理解和操作的不对吗？
我本以为这样操作可以让当前的v2节点流量先经过ssr的代理，我试过在ssr客户端上面的前置代理功能我是用v2的端口这么操作，都可以走v2的。

**Comment by DuckSoft** [comment]
更新订阅时，上游删除的节点，会要求你确认是保留还是删除，所以不会出现混乱。
前置代理功能受到 V2Ray 核心的限制，只支持部分协议的部分情况，具体参见上游文档: https://v2fly.org/
如果想用真正的代理链功能，可以使用复杂配置中的“代理链”选项。

另外，复制分组功能暂时不会考虑，因为我们正在重写新的用户界面，重写新的设置后端。
