### ISSUE TITLE
使用疑问：「怎么配置哪些域名不适用代理？」

### ISSUE THREAD

**Issue by yifan2333** [Qv2ray/Qv2ray#1235]
怎么配置哪些域名不适用代理？

**Comment by 2014CAIS01** [comment]
@yifan2333 请参考 Qv2ray 官方文档
https://qv2ray.net/manual/route.html#%E5%85%A8%E5%B1%80%E8%B7%AF%E7%94%B1%E8%A7%84%E5%88%99

**Comment by DuckSoft** [comment]
* [起步——更多——调整路由方案](https://qv2ray.net/getting-started/step5.html#%E8%B0%83%E6%95%B4%E8%B7%AF%E7%94%B1%E6%96%B9%E6%A1%88)
* [手册——高级路由设置——全局路由规则](https://qv2ray.net/manual/route.html#%E5%85%A8%E5%B1%80%E8%B7%AF%E7%94%B1%E8%A7%84%E5%88%99)

**Comment by yifan2333** [comment]
我是小白，看不懂文档，能给截图展示一下吗？

**Comment by yifan2333** [comment]
> @yifan2333 请参考 Qv2ray 官方文档
> https://qv2ray.net/manual/route.html
我是小白，看不懂文档，能给截图展示一下吗？

**Comment by U-v-U** [comment]
不能

**Comment by yifan2333** [comment]
> 请读文档。
> 
> * [起步——更多——调整路由方案](https://qv2ray.net/getting-started/step5.html#%E8%B0%83%E6%95%B4%E8%B7%AF%E7%94%B1%E6%96%B9%E6%A1%88)
> * [手册——高级路由设置——全局路由规则](https://qv2ray.net/manual/route.html#%E5%85%A8%E5%B1%80%E8%B7%AF%E7%94%B1%E8%A7%84%E5%88%99)

我是小白，看不懂文档，能给截图展示一下吗？

**Comment by DuckSoft** [comment]
非常抱歉，Qv2ray 不面向小白开发，也不向小白提供基础的支持。

**Comment by DuckSoft** [comment]
必须明确，开发者没有义务付出大量精力培养小白，也没有任何义务保证软件的可用性/易用性/适销性甚至任何其他特性。
满足开发者自身的需求是开发的核心驱动力，包括但不限于满足自身使用需求和满足技术探索方面的需求。

**Qv2ray 维持到现在，靠的是能干实事的开发者，而不是白嫖伸手的小白。**
