### ISSUE TITLE
使用疑问：「 更新之后突然核心启动失败 」

### ISSUE THREAD

**Issue by Un-KnownCode** [Qv2ray/Qv2ray#1237]
2021/01/23 13:34:45 [Info] v2ray.com/core/main/jsonem: Reading config: /home/unknowncode/.config/qv2ray/generated/config.gen.json
main: failed to read config files: [/home/unknowncode/.config/qv2ray/generated/config.gen.json] > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load geoip: private > v2ray.com/core/infra/conf: country not found in geoip.dat: private

显示这串报错信息，这个有什么解决办法吗？

**Comment by 2014CAIS01** [comment]
@Un-KnownCode 请提供 v2ray-core 版本 和 qv2ray 版本

**Comment by Un-KnownCode** [comment]
@2014CAIS01 v2ray版本是4.34.0-1 qv2ray版本是2.6.3-12

**Comment by sixg0000d** [comment]
从此处下载更新后再做尝试？
 [geoip.dat](https://github.com/v2fly/geoip/releases/latest/download/geoip.dat)

**Comment by Un-KnownCode** [comment]
@2014CAIS01 我用qv2ray检测了核心文件，又说没有问题，时间也没有延迟，就是一连就说我超出什么限制，然后显示核心启动失败。。

**Comment by Un-KnownCode** [comment]
@sixg0000d 我现在尝试一下

**Comment by Un-KnownCode** [comment]
@2014CAIS01 @sixg0000d  我把所有配置文件删了，重新安装了一下，现在显示V2Ray 资源文件路径不可用。这个问题可以解决吗？之前说的那个方法行不通，我去下载了geoip.dat了之后还是那样

**Comment by DuckSoft** [comment]
> V2Ray 资源文件路径不可用

这已经告诉你原因了呀，那个目录下面没有 geoip.dat / geosite.dat 就会这样。
