### ISSUE TITLE
什么时候支持Shadowsocks AEAD二次加密啊？

### ISSUE THREAD

**Issue by sunjuwen** [Qv2ray/Qv2ray#1238]
如题！Trojan Go设置了Shadowsocks二次加密。Qv2ray无法使用啊！
https://p4gefau1t.github.io/trojan-go/advance/aead/

**Comment by DuckSoft** [comment]
早就支持了啊。至少读一下插件首页的说明吧。
https://github.com/qv2ray/qvplugin-trojan-go

`trojan-go://f@uck.me/?sni=microsoft.com&type=ws&path=%2Fgo&encryption=ss%3Baes-256-gcm%3Afuckgfw`
你觉得这个例子像不像二次加密的？

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/105616830-978eb100-5e14-11eb-8381-8c5602507bb0.png)
![图片](https://user-images.githubusercontent.com/7822648/105616842-ac6b4480-5e14-11eb-95a8-2024e8dd92ac.png)
