### ISSUE TITLE
ubuntu18.04,unity-desktop下，UI界面无法显示

### ISSUE THREAD

**Issue by ianhitlgang** [Qv2ray/Qv2ray#1239]
ubuntu18.04,unity-desktop环境，直接运行appimages，UI界面无法正常显示

![2021-01-24 17-14-08屏幕截图](https://user-images.githubusercontent.com/25071804/105626171-275e4a80-5e69-11eb-96f3-d9f709852619.png)

**Comment by DuckSoft** [comment]
检查环境变量和系统设置，很有可能设置了负缩放。
另外，Ubuntu 18.04 推荐从 Snapcraft 安装。
