### ISSUE TITLE
Trojan: SSL Handshake Failed With xxx: Certificate Verify Failed

### ISSUE THREAD

**Issue by qihang518887** [Qv2ray/Qv2ray#1241]
进群问题回答错了。。。我进不去tg群了
###你有什么问题
在Qv2ray上使用trojan节点的时候会提示 SSL handshake failed with ***: certificate verify failed

### 你目前试了啥？
使用clash测试节点没有问题
更新Qv2ray到3.0也没有解决

**Comment by DuckSoft** [comment]
证书校验失败，检查几点原因：
1. 是否正确签发证书
2. 证书是否已过期
3. 两端时间是否正确
4. 握手参数（如SNI等）是否设置正确

**Comment by DuckSoft** [comment]
已经私聊了，原因是机场没有下发 `sni`，导致证书校验失败。
