### ISSUE TITLE
无法更新GFWList

### ISSUE THREAD

**Issue by alwzying** [Qv2ray/Qv2ray#1242]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
更新GFWList时发生，显示promiseReactionJob@[native code]，XHR Request Timed Out

## 如何触发这个 Bug：

1.在透明代理选项卡下点击更新GFWList

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？

非连接问题

### 相关截图或日志

![image](https://user-images.githubusercontent.com/26023755/105697903-23e9c280-5f40-11eb-92d9-b1d315dc38b6.png)

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.0.0-1
```

### 操作系统

- Openwrt Koolshare mod V2.36 r14941-67f6fa0a30

### 安装来源

- Github Release / Scoop / Chocolatey

### 已安装的插件、版本及安装来源

无

**Comment by DuckSoft** [comment]
你好像发错地方了？
