### ISSUE TITLE
路由ipifnonmatch模式bug反馈

### ISSUE THREAD

**Issue by DLGum** [Qv2ray/Qv2ray#1243]
win10 20h2 
qv是actions构建的最新64位

【问题描述】
昨晚开始ipifnonmatch模式出现不代理谷歌的bug
但我原来一直用的就是这个模式并且正常使用。
![R WQQPGGR(PV@4HVK LQ_JQ](https://user-images.githubusercontent.com/45528130/105801353-ed5d8780-5fd3-11eb-9a9f-78ad9b3a3c3f.png)
![UR YVAVGUISL)N( {NI_)JS](https://user-images.githubusercontent.com/45528130/105801354-ee8eb480-5fd3-11eb-9e15-b7a1e0773405.png)

【尝试过的解决方法】
把xray核心重新下载。失败。
重启大法。失败。
最后尝试把路由模式改asls就好了。
但再改ipifnonmatch会再次出现同样情况。问题还在。
线路较多麻烦没重装qv测试。

【可能的复现方法】
猜测可能为改变网络，也可能是电脑休眠过造成的。
我昨天就是在外面用的好好的，电脑盖起来（休眠）回家揭开问题就出现了。

【问题复现过】
这个问题之前也遇见过，
当时没空看问题所在，扭头开clash用了两天。
两天后发现xray更新，试了试发现qv又能正常使用了。
上次xray是4天前我是追的更的最易应该无关。

**Comment by U-v-U** [comment]
@DLGum 检查 DNS 污染情况

**Comment by DLGum** [comment]
> @DLGum 检查 DNS 污染情况

试过的。上面写漏了。

**Comment by DuckSoft** [comment]
请勿勾选“使用本地DNS”即可。

**Comment by DLGum** [comment]
> 请勿勾选“使用本地DNS”即可。

确实好了。感谢。
