### ISSUE TITLE
Windows版(2.7.0-pre-1)主界面上重命名后无法同步更新配置编辑中显示的名称

### ISSUE THREAD

**Issue by chacha20** [Qv2ray/Qv2ray#1244]
- [ ] **I'm sure I've tried to reproduce the problem several times and will provide the system environment, each software and its version that is involved in the problem.**

## How to trigger this bug：

1. 主界面上选择一个节点，右键点击“重命名”
2. 主界面上选择该节点，右键点击“编辑”
3. 这时就能看到显示的依旧是原来的名字。并没有同步更新。
4. 重新启动qv，名称依旧，即使杀掉进程再重新启动也是这个旧名字。

### Related screenshots or logs

<details>

```
Please paste your Qv2ray log here:


```

</details>

### Open Preferences -> About, and enter the following info

```
Version: 2.7.0-pre1:6039
Build info: 
Extra build info: Qv2ray built from Github Action
```

### Operating systems

- [ ] Linux
- [ ] macOS
- [+] Windows
 
### Installation source
 
- [ ] ArchLinuxCN - Stable
- [ ] ArchLinuxCN - Dev-git
- [ ] ArchLinux AUR - Stable
- [ ] ArchLinux AUR - Development
- [ ] Fedora - Stable
- [ ] Fedora - Preview
- [ ] openSUSE - Stable
- [ ] openSUSE - Preview
- [ ] Flathub
- [ ] Snap
- [ ] Homebrew Cask
- [+] Scoop / Chocolatey / Github Release
- [ ] Compile manually

## Additional Info

*Please hide your server address and UUID if you wish to post the vmess string or your connection setting.*

**Comment by DuckSoft** [comment]
F2

**Comment by DuckSoft** [comment]
或者右键，重命名。

**Comment by chacha20** [comment]
这么说的话，标签其实我可以不用去管它的吧，主要是用名称哪里的名字。

**Comment by DuckSoft** [comment]
@chacha20 ✅
