### ISSUE TITLE
开启Qv2ray tor浏览器 无法连接网络

### ISSUE THREAD

**Issue by t-o-n-y-w** [Qv2ray/Qv2ray#1246]

**Comment by 2014CAIS01** [comment]
@t-o-n-y-w Please describe in detail the steps you took to reproduce this problem and what you have tried. We cannot locate the problem based on the your information.

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/106086031-4bb57200-615c-11eb-9f8b-bf79b66047af.png)

大哥，你这啥也没写啊，还是找个算卦的帮你看一下吧，我看不明白……
