### ISSUE TITLE
请求出一个一键透明代理，或者自动生成iptables规则的功能

### ISSUE THREAD

**Issue by NicholasIrving** [Qv2ray/Qv2ray#1247]
请求出一个一键透明代理，或者自动生成iptables规则的功能，因为对于很多小白来说透明代理不是一键容易的事情，非常希望能够出一个这样的功能

**Comment by U-v-U** [comment]
@NicholasIrving See https://github.com/springzfx/cgproxy

**Comment by librenix** [comment]
之前的版本有这个功能，但因为某些原因去掉了。iptables规则见[新 V2Ray 白话文指南](https://guide.v2fly.org/app/tproxy.html)。
