### ISSUE TITLE
Feature Request: Convert socks to PPTP? 

### ISSUE THREAD

**Issue by 517030910405** [Qv2ray/Qv2ray#1250]
**Is your feature request related to a problem? Please describe.**
Some softwares do not use the `http_proxy` or `https_proxy` or `all_proxy` values in the environment. 
For example, APT and Docker do not use either of them. 
So `export https_proxy='http://127.0.0.1:8889'` does not work. 

Though APT problem can be fixed with setting the proxy in APT (`/etc/apt/apt.conf.d/80proxy`), it is still inconvenient to do that for a large number of softwares. Also, some software does not have a proxy setting like apt. 

**Describe the solution you'd like**

Add a `VMESS -> PPTP` or `socks -> PPTP` conversion. So Linux, Windows and IOS can use the default "VPN" setting to force the connection to use the proxy. 

**Describe alternatives you've considered**

Not sure. 

**Additional context**

**Comment by DuckSoft** [comment]
https://github.com/eycorsican/go-tun2socks

**Comment by DuckSoft** [comment]
https://github.com/springzfx/cgproxy

**Comment by 517030910405** [comment]
> That's not what Qv2ray is focusing on. It's a GUI shell rather than a network converter.
> Try this: https://github.com/eycorsican/go-tun2socks

Thanks.
