### ISSUE TITLE
请问下,出现这个情况是怎么回事

### ISSUE THREAD

**Issue by kerfans** [Qv2ray/Qv2ray#1251]
![截图录屏_选择区域_20210129141438](https://user-images.githubusercontent.com/20582469/106238887-920cde80-61f9-11eb-968f-f0d56446ddaa.png)

2021/01/29 14:18:45 [Info] v2ray.com/core/main/jsonem: Reading config: /home/kerfans/.config/qv2ray/generated/config.gen.json
main: failed to read config files: [/home/kerfans/.config/qv2ray/generated/config.gen.json] > v2ray.com/core/infra/conf: unknown cipher method: aes-256-cfb

提示的是不支持aes-256-cfb  这种加密方式.请问用哪个版本可以支持,或者应该怎么做才能解决呢?

**Comment by DuckSoft** [comment]
先说现象：V2Ray 核心新版全面抛弃了对 Shadowsocks 不安全的流密码的支持。
再说原因：

以下摘自 https://gfw.report/blog/ss_tutorial/zh/


Q: 我应该用Shadowsocks的stream cipher吗?
A: 完全不应该。因为Shadowsocks的stream cipher有着不可接受的安全隐私漏洞，并且可以被准确的主动探测。如Figure 10所示，即使是最新版的Shadowsocks-libev，在使用stream cipher时同样可以被准确识别。更具灾难性的是，在不需要密码的情况下，攻击者可以完全解密被记录下来的Shadowsocks会话。

Q: 但为什么我用的机场仍在使用stream cipher?
A: 这清楚地说明你的机场缺乏安全意识和安全措施。请把这篇教程，这个演讲，和这篇总结，分享给你的机场主。

**Comment by DuckSoft** [comment]
Reference: https://github.com/net4people/bbs/issues/24
