### ISSUE TITLE
v2ray核心返回空字符串

### ISSUE THREAD

**Issue by zhouhuagfu** [Qv2ray/Qv2ray#1252]
设计q2ray客户端的大神们好，我刚入手qv2ray，在为qv2ray配置v2ray内核时，程序总是会卡住，不一会显示未响应，并且提示我v2ray核心显示空字符串，本来不想来这里麻烦各位大神，但网上和youtube实在没有解决我的问题，故来求助各位大神，望不吝赐教

**Comment by MarksonHon** [comment]
@zhouhuagfu 加入 Telegram 群组求助：
<https://t.me/qv2ray>

**Comment by zhouhuagfu** [comment]
![无标题](https://user-images.githubusercontent.com/67571932/106374102-dabfc580-63ba-11eb-8ac1-5bec563315f5.png)
大致就是这样

**Comment by 2014CAIS01** [comment]
@zhouhuagfu 让你选择v2ray核心，不是 v2rayN.exe

**Comment by FANminiworld** [comment]
@zhouhuagfu https://t.me/qv2ray_dev/205
