### ISSUE TITLE
启动节点后，不能停止，程序无法正常退出

### ISSUE THREAD

**Issue by bobwang3** [Qv2ray/Qv2ray#1253]
MACOS High Sierra，版本10.13.6
先是安装了v2.7.0-pre1预览版，导入节点并启动后打开网页功能都正常，但是发现这个时候程序就无法再继续操作了，Command-Tab无法切换到QV2RAY窗口。（经过我的测试，这个状态下耗电量明显会增加）
唯一能做的强行退出程序。
强退后safir的代理设置需要把http https socks三个被程序勾上的代理勾去掉才能正常使用。
我卸载后重新安装了v2.6.3，发现情况是一样的。

**Comment by DuckSoft** [comment]
10.13 要用 Legacy 包，否则 grpc 会 CPU 100%。
当然，你也可以在首选项中关闭 API 子系统，只不过这样就没有统计数据了。

RIP macOS 10.13

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/106375584-3d6b8e00-63c8-11eb-82c1-fd59b3c18c42.png)
