### ISSUE TITLE
功能请求：建议加入快捷键连接功能

### ISSUE THREAD

**Issue by Thomitics** [Qv2ray/Qv2ray#1254]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

因为使用一部分软件时挂着代理就无法使用（UWP通病），每次使用时要断开连接，使用完了这个软件再连接，每次从任务栏上连接就很麻烦

**简单描述你预期的解决方案？**

加入一个快捷键连接功能，按一个快捷键就连接，再按就断开

**你有想到其他比较容易实现的解决方案吗？**

好像没有

**Comment by cpdyj** [comment]
针对UWP的话， 存在一个工具可以接触localhost回环连接限制

**Comment by DuckSoft** [comment]
You may be interested: https://qv2ray.net/getting-started/step4.html#%E4%BD%BF%E7%94%A8%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86

![图片](https://user-images.githubusercontent.com/7822648/106383631-1cc02a00-6402-11eb-9c33-14f6ca635587.png)

**Comment by Thomitics** [comment]
不只是UWP其实……
使用终端的时候（Linux上）SSL证书会有问题

**Comment by Thomitics** [comment]
> You may be interested: https://qv2ray.net/getting-started/step4.html#%E4%BD%BF%E7%94%A8%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86
> 
> ![图片](https://user-images.githubusercontent.com/7822648/106383631-1cc02a00-6402-11eb-9c33-14f6ca635587.png)

Thanks!

**Comment by 2014CAIS01** [comment]
> 谢谢，不过不只是UWP其实……
> 使用终端的时候（Linux上）SSL证书会有问题

可能是因为你断开连接之后仍然设置了 `HTTP_PROXY` 等相关的环境变量引起的。这个需要你手动把相关环境变量去掉，或者你应该使用一些针对你的 shell 的自动设置 proxy 相关环境变量的插件。
