### ISSUE TITLE
使用疑问：「 公司内连接VPN后无法使用Qv2ray 」

### ISSUE THREAD

**Issue by liveroute** [Qv2ray/Qv2ray#1256]
在公司内连接公司L2TP VPN（Client IP 172.16.0.22），运行Qv2ray后无法正常上网。监听地址改为0.0.0.0也无法正常使用。

**Comment by Janet-Baker** [comment]
日志呢？日志呢？？日志呢？？？
--------------

- 可能是你配置的问题，VPN没有正确设置
- 可能是公司VPN的问题。公司的VPN大多数是用来访问内网资源的，没有允许访问公司外的网络。
- 可能是你的v2ray没有正确配置
- 可能是你的防火墙没有正确配置
----------------------

既然你不贴日志，那就自己折腾吧……

**Comment by DuckSoft** [comment]
信息量太少了。无法使用是怎么个无法使用？浏览器的请求发到v2ray里了吗？v2ray的请求出去了吗？
v2ray 的请求成功了吗？这些都需要实际的操作结合对应的日志加以说明。

**Comment by liveroute** [comment]
浏览器请求没到Qv2ray。
V2Ray 4.34.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.6 windows/amd64)
A unified platform for anti-censorship.
2021/02/01 10:19:39 [Info] v2ray.com/core/main/jsonem: Reading config: D:/Qv2ray/config/generated/config.gen.json
2021/02/01 10:19:39 [Warning] v2ray.com/core: V2Ray 4.34.0 started
2021/02/01 10:19:39 127.0.0.1:51487 accepted tcp:127.0.0.1:0 [_QV2RAY_API_]
2021/02/01 10:19:42 172.16.0.22:51493 accepted http://ipv6.msftconnecttest.com/connecttest.txt [outBound_PROXY]
2021/02/01 10:19:42 172.16.0.22:51494 accepted http://www.msftconnecttest.com/connecttest.txt [outBound_PROXY]
2021/02/01 10:19:44 [Warning] [1188852125] v2ray.com/core/proxy/http: failed to read response from ipv6.msftconnecttest.com > io: read/write on closed pipe

**Comment by DuckSoft** [comment]
那就是浏览器的问题喽。装个 SwitchyOmega 显式指定一下代理到 V2Ray 的入站看看？

**Comment by liveroute** [comment]
SwitchyOmega可以。

**Comment by DuckSoft** [comment]
那应该考虑一下系统代理配置被劫持了的情况，毕竟浏览器是从系统那里先读取到的代理配置的。
很有可能是 L2TP VPN 把你的系统代理设置清空/锁定了，然后导致浏览器获取到的系统代理发生了异常。

如果不关心具体的行为，直接 SwitchyOmega 不失为一种好办法。

**Comment by dyhkwong** [comment]
这个也是和拨号代理同样的问题 https://github.com/Qv2ray/Qv2ray/issues/873 ，请尝试使用 Actions 编译版 https://github.com/Qv2ray/Qv2ray/actions/runs/520993723
