### ISSUE TITLE
功能请求：将(批量)测速方式改为真实连接延迟和下载速度

### ISSUE THREAD

**Issue by xuerui911** [Qv2ray/Qv2ray#1257]
我个人觉得，”测试延迟“，按ping值意义不大，一是现在的GFW，能ping通不一定能打开google，二是好多国内中转的节点，有可能ping值很低，但是实际真连接延迟很高，因为国内连国内的节点很快，那个中转节点连它境外的节点却很慢。

现在”测试真实连接“只在当前激活节点可选，其它节点为灰色，批量选中多个节点时此选项也为灰色。

我觉得应该保留”测试真连接延迟“和”测试下载速度“两种测速方式，一般需求是浏览网页，这种情况按真实连接延迟排序比较合理，二是有些节点可能延迟稍微高些但是带宽很大下载速度很快，在需要下载某些大文件时，可以按照此种方式排序。

最好别只在当前激活节点可以测速，最好能在多选的所有节点都能同时测速(真连接延迟和下载速度)

**Comment by U-v-U** [comment]
We will not add such feature officially, someone who is interested in may wish to open a PR with a clean implementation is always welcomed.
