### ISSUE TITLE
2个暗色调主题下，日志的访问地址看不到或者看不清

### ISSUE THREAD

**Issue by oneness629** [Qv2ray/Qv2ray#1258]
Built-in Darkmode主题下日志的地址文字直接是黑色看不到！
psblack主题下日志地址文字和背景太接近，基本看不清！

**Comment by U-v-U** [comment]
@oneness629 首选项第二个

**Comment by oneness629** [comment]
> @oneness629 首选项第二个

我看到那2个暗色调选项了，也勾上了，没用，还是看不清。就像这样！黑文字+黑背景
![image](https://user-images.githubusercontent.com/10450814/106463470-5d19b980-648f-11eb-8b71-241b613aa02b.png)

**Comment by U-v-U** [comment]
@oneness629 重启试试

**Comment by oneness629** [comment]
> @oneness629 重启试试

好的好的，重启解决了，谢谢大佬~
