### ISSUE TITLE
是否考虑出安卓客户端?

### ISSUE THREAD

**Issue by csgowdnmd** [Qv2ray/Qv2ray#1260]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

`QV_ISSUE_FEATUREREQUEST_TEMPLATE_PLACEHOLDER`

-----------------

**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

请尽可能清晰简洁地描述问题。

**简单描述你预期的解决方案？**

请尽可能清晰简洁描述问题。

**你有想到其他比较容易实现的解决方案吗？**

请简单清晰描述。 

**补充内容**
请在此附加任何你认为对你的描述有所帮助的内容。

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/106834544-a1e06300-66d0-11eb-9bb3-84b3360d6e4d.png)
