### ISSUE TITLE
功能请求：启用/关闭系统代理时右下角图标变化更明显一些

### ISSUE THREAD

**Issue by atest1** [Qv2ray/Qv2ray#1262]
目前只是在右下角图标上显示一个蓝色/绿色的小点，这个变化实在不太明显
对比SSR/V2rayN，那都是整个图标的颜色发生变化。
我觉得这个还是改得醒目一些更好。

**Comment by Delcas** [comment]
同感, 盯着看的时候有时分不清是蓝色还是绿色

**Comment by Amos-Dan** [comment]
居然没注意这个变化

**Comment by U-v-U** [comment]
Duplicated, closing, see #551 for more information.
