### ISSUE TITLE
公告: 有关 v2.7.0-pre1+ 后续版本的 macOS 支持

### ISSUE THREAD

**Issue by U-v-U** [Qv2ray/Qv2ray#1263]
公告: 有关 `v2.7.0-pre1+` 后续版本的 macOS 支持

# 直接原因: 
~~我们太菜了~~
我们已经在 macOS 上花费了大量的维护成本, 并且不想继续掏出自己的肝送给 macOS
我们没有属于自己的 macOS 设备
    
# 其他原因:
macOS 有很多奇怪的设计，所有从 Internet 下载的程序都会被苹果公司贴上这样的标签: "你不安全" 并尝试阻止程序的运行, 如果想上架 AppStore 走正规途径, 开发者不得不进行金钱交易并发送源码进行审核.
所有其他的包都会认为是 "我不能相信你". 这使得多数零收入开发者头大

此外, macOS 奇怪的 CI 权限问题也值得深思: AppleScript 无法通过控制台执行 (原因竟是在询问用户是否继续), 这直接导致 CI 超时
    
# 我以后怎么办:
我们不会再在 Release 文件中包含 macOS 编译, 但
  1. GitHub Actions 中仍保留 macOS 包
  2. 你可以自己编译运行, 但是与 macOS 相关的问题我们几乎无法解决 (见直接原因)

# 或者
欢迎想接手维护 macOS 支持的人在本帖直接留言。
Qv2ray 在 macOS 的未来就交给你了！
> "我现在真的对苹果没啥好话可以说了🤪"

**Comment by liurusi** [comment]
linux版才是正道。

**Comment by librenix** [comment]
如果不考虑M1芯片的Mac，我愿意维护macOS版。

**Comment by U-v-U** [comment]
@librenix  The three major problems:

1. https://github.com/Qv2ray/Qv2ray/issues/993
2. macOS System Proxy utility is using a deprecated API, it'll be better to replace it.
3. macdeployqt sometimes stops working, the phenomenon is `PlugIns` subdir is not copied into the app bundle.

**Comment by librenix** [comment]
@U-v-U 1不是一个大问题，不影响软件使用，优先级低，2和3的优先级高一些。

**Comment by U-v-U** [comment]
@librenix Problem 3 has been resolved.

**Comment by gujiangjiang** [comment]
我还在用2.6.3 Mac版本，没什么问题，挺好的，希望能一直支持下去

**Comment by U-v-U** [comment]
update: to @librenix and to whom it may concern: https://github.com/Qv2ray/macdeployqt-patched has a patched version of `macdeplyqt` where ignores the `isDebugLib` check.

**Do not redistribute the source code, only use it to package Qv2ray.**

**Comment by mclovin-2k** [comment]
Better Just drop it.
Apple users had made their choice when they bought that black box called "Mac".
Besides, They can always go to "Genius Bar" for answers.

**Comment by FlameMida** [comment]
我现在用着也没什么问题啊，希望继续支持下去。要不然mac就没有好用的客户端了

**Comment by ztony0712** [comment]
mac端几乎只剩你们在支持vless订阅了，如果有困难可以制作收费版或者发起捐助请求，相信mac用户能为你们尽一份力。希望能继续对mac支持下去，加油。

**Comment by FANminiworld** [comment]
@ztony0712 @ducksoft 说过，本项目永远不会收费，永远不接受捐赠

**Comment by DuckSoft** [comment]
> GitHub Actions 中仍保留 macOS 包
莫慌，包还会在，只是有些 macOS 特色问题只能由 macOS 魔法师来解决。
我们这种手无寸 Mac 的人请恕难以隔空气打牛。

**Comment by ztony0712** [comment]
非常抱歉冒犯到您，下次会注意

**Comment by DuckSoft** [comment]
@ztony0712 无需抱歉，有用户理解并支持我们，比那些只会张嘴伸手的**不知道好到哪里去了。
感谢你的回复。

**Comment by librenix** [comment]
@DuckSoft 建议继续给 macOS 打包，因为 [act](https://github.com/nektos/act)
 暂时只支持 Linux。我在本地打包发现跟官方的有些不同，11.2 编译的 app 不支持在更低版本（10.15）运行。

**Comment by mlboy** [comment]
关于 『Internet 下载的程序都会被苹果公司贴上这样的标签: "你不安全" 并尝试阻止程序的运行』的问题可以通过下面命令去掉标签

```
sudo spctl --master-disable
sudo xattr -d com.apple.quarantine /Applications/XXX.app
```

**Comment by GossipRanR** [comment]
现在公司和生活中 mac 电脑的比例越来越高，尤其是做技术的，至少在我们公司里开发团队都是清一色的 macbook。
个人认为 macOS app 的使用率是会越来越高的，而且是很重要的一个平台。
现在 mac 平台的翻墙软件都很弱鸡（至少我这么觉得），难得有 qv2ray 这么好用更新频率这么快的软件。
并且现在小白很多，翻墙的大多不懂技术，专业的事儿还是应该专业的人来做，希望可以继续发布 macOS 的 app。
如果缺资金，可以进行捐赠，希望采纳建议。

**Comment by AkinoKaede** [comment]
@GossipRanR 开发者明确说过不接受捐赠，你可以贡献代码

**Comment by DuckSoft** [comment]
@GossipRanR 莫慌，对于懂行的人，只是换了个地方下载而已

> GitHub Actions 中仍保留 macOS 包

**Comment by GossipRanR** [comment]
> @GossipRanR 莫慌，对于懂行的人，只是换了个地方下载而已
> 
> > GitHub Actions 中仍保留 macOS 包

我的所有软件都是使用 Homebrew 进行管理，希望后续也能看到在 Homebrew 中的更新。

**Comment by DuckSoft** [comment]
如果记得没错的话，Homebrew 是不收 prelease 包的。相应的功能可能需要通过自己维护 TAP 来实现。
我个人是没有 macOS 设备的，否则我肯定会维护一个的。

**Comment by librenix** [comment]
> 如果记得没错的话，Homebrew 是不收 prelease 包的。相应的功能可能需要通过自己维护 TAP 来实现。
> 我个人是没有 macOS 设备的，否则我肯定会维护一个的。

@GossipRanR @DuckSoft Done.
https://github.com/Qv2ray/homebrew-qv2ray

**Comment by 2014CAIS01** [comment]
> > 如果记得没错的话，Homebrew 是不收 prelease 包的。相应的功能可能需要通过自己维护 TAP 来实现。
> > 我个人是没有 macOS 设备的，否则我肯定会维护一个的。
> 
> @GossipRanR @DuckSoft Done.
> https://github.com/Qv2ray/homebrew-qv2ray

@librenix It may be duplicated to the cap [here](https://github.com/kidonng/homebrew-malt/tree/master/Casks
) maintained by @kidonng, and it is also avalible on the document.

By the way, we also need to package plugins into the homebrew tap.

**Comment by GossipRanR** [comment]
> 如果记得没错的话，Homebrew 是不收 prelease 包的。相应的功能可能需要通过自己维护 TAP 来实现。
> 我个人是没有 macOS 设备的，否则我肯定会维护一个的。

是的 只收 release 包。Homebrew 和 app store 搭配是现在技术圈内主要的软件管理方式吧？希望能继续在 Homebrew 放更新

**Comment by w-tim** [comment]
对我而言，可能是最好的mac版客户端了，不希望放弃支持

**Comment by Antoniolee801** [comment]
MAC端 VPN类软件 这款软件是最骚气的了，功能强大稳定拓展性强，骚的飞起。不反对大大在这个版本后停止支持，但还请能给个稳定的终结版本让我们这群MAC鸡能继续坚持使用。虽然你说过不接受捐助，要不然这样吧，你开个捐助通道，我们这群MAC用户给你众筹一台MAC吧以便支持大大继续开发。。。

**Comment by FlameMida** [comment]
> MAC端 VPN类软件 这款软件是最骚气的了，功能强大稳定拓展性强，骚的飞起。不反对大大在这个版本后停止支持，但还请能给个稳定的终结版本让我们这群MAC鸡能继续坚持使用。虽然你说过不接受捐助，要不然这样吧，你开个捐助通道，我们这群MAC用户给你众筹一台MAC吧以便支持大大继续开发。。。

众筹mac更离谱。。。。

**Comment by DuckSoft** [comment]
莫慌，对于懂行的人，只是换了个地方下载而已

    GitHub Actions 中仍保留 macOS 包

**Comment by RyoHina** [comment]
花了两天时间，把 Windows 的编译环境搞好了。 macOS平台折腾三天了，没有头绪， 有没有人给点思路，不需要太详细，谢谢啦~~~

**Comment by cubercsl** [comment]
@RyoHina https://qv2ray.net/hacking/manuallybuild.html

**Comment by Yansre** [comment]
能不能提供以前mac的编译参数，我将在mac m1上尝试进行打包并希望能长期进行相关的测试

**Comment by RyoHina** [comment]
> 能不能提供以前mac的编译参数，我将在mac m1上尝试进行打包并希望能长期进行相关的测试

我放弃了， 准备Electron一把梭， 自己搞吧，反正都是封装 v2ay(xray)核心。 目前能出一个Demo了。
