### ISSUE TITLE
功能请求：请求win10界面添加一键下载vraycore，或者设置为相对路径

### ISSUE THREAD

**Issue by wuweilin12345** [Qv2ray/Qv2ray#1264]
请尽可能清晰简洁地描述问题。
1、对于小白用户，不熟悉gayhub的用户去下载core并进行部署,具有一定难度。比如我把客户端分享给运营同事，他们就不太会自助完成整个初始化流程。

2、对于问题1，我想到的解决办法是我初始化完成之后，打一个包推送给运营。但看到v2raycore的路径是个绝对路径，猜测把A机器上面qv2ray打包放到另外一台机器上，不能马上使用

**简单描述你预期的解决方案？**

针对1：提供一个按钮，自动在qv2ray的安装路径下载core，并自动填充路径
针对2：路径可以采取相对路径的方式

**补充内容**
环境 windows10
客户端 qv2ray 2.6.3

**Comment by EpLiar** [comment]
> 请求win10界面添加一键下载vraycore

放心，这个是不会做的

**Comment by EpLiar** [comment]
> 对小白友好对这个社区不会有太大的帮助
