### ISSUE TITLE
Linux 桌面中卸载 Qv2ray 所在的桌面环境并切换到另一桌面环境后无法唤出驻留后台的实例

### ISSUE THREAD

**Issue by glyh** [Qv2ray/Qv2ray#1265]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

Qv2ray 启动成功，但没有任何图形UI

## 如何触发这个 Bug：

1. 安装i3wm
2. 在i3wm中运行qv2ray
3. 卸载i3wm回到原有的桌面环境
4. 运行qv2ray

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

非连接问题

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：
……打不开软件

```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3-3.1
编译信息：(不好意思真找不到了，图形界面根本打不开）
额外编译信息：同上
```

### 操作系统

- Linux anonymous 5.10.12-arch1-1 #1 SMP PREEMPT Sun, 31 Jan 2021 00:41:06 +0000 x86_64 GNU/Linux

- ### 安装来源

- ArchLinux AUR - 稳定版

### 已安装的插件、版本及安装来源

未安装插件

## 附加信息

*请注意打码隐私相关信息。*

`qv2ray --debug`:
```
[INIT]: Qv2ray PreInitialization: OK
static Qv2ray::Qv2rayPreInitResult Qv2ray::Qv2rayApplication::PreInitialize(int, char**):494 [INIT]: High DPI scaling is enabled.
[INIT]: Qv2ray 2.6.3 on Arch Linux x86_64
Qv2ray::Qv2rayApplication::Qv2rayApplication(int&, char**):36 [INIT]: Qv2ray Start Time: 43610843
Qv2ray::Qv2rayApplication::Qv2rayApplication(int&, char**):37 [QV2RAY_BUILD_INFO]: Qv2ray for Arch Linux CN
Qv2ray::Qv2rayApplication::Qv2rayApplication(int&, char**):38 [QV2RAY_BUILD_EXTRA_INFO]: (Official Build) 5.9.4-arch1-1 x86_64
Qv2ray::Qv2rayApplication::Qv2rayApplication(int&, char**):39 [QV2RAY_BUILD_NUMBER]: 5841
QStringList Qv2ray::common::QvTranslator::GetAvailableLanguages():40 [CORE-UI]: Found translations: en_US ja_JP zh_CN zh_TW
bool Qv2ray::common::QvTranslator::InstallTranslation(const QString&):50 [CORE-UI]: Found en_US in folder: /usr/share/qv2ray/lang
[CORE-UI]: Successfully installed a translator for en_US
```

**Comment by DuckSoft** [comment]
这……好像是预期行为……这种奇葩的场景我也不知道怎么修复，没有任何思路。
cc @U-v-U @ymshenyu

**Comment by glyh** [comment]
> 这……好像是预期行为……这种奇葩的场景我也不知道怎么修复，没有任何思路。
> cc @U-v-U @ymshenyu

重新安装也没用，但是我用TimeShift可以修好. 个人感觉是Qv2ray的配置文件出问题了

**Comment by U-v-U** [comment]
Issue closed since the problem was solved.

**Comment by U-v-U** [comment]
https://unix.stackexchange.com/questions/120444/how-to-move-a-window-from-one-window-manager-to-another-running-wm
