### ISSUE TITLE
Please treat the QR-Code scanner part as a module instead of binding it to Qv2ray

### ISSUE THREAD

**Issue by Fe3O4-Git** [Qv2ray/Qv2ray#1266]
It takes too much time to clone zxing-cpp while building Qv2ray from AUR. It's terrible and the QR-Code scanner isn't a need for most people.

**Comment by U-v-U** [comment]
@Fe3O4-Git Don't worry, it's been removed.

**Comment by DuckSoft** [comment]
This module is now removed. Cheers!

**Comment by DuckSoft** [comment]
The change is made on dev branch, so it's normal for you to have the question. So case closed.
