### ISSUE TITLE
"Use local DNS" should not be on by default

### ISSUE THREAD

**Issue by wangzheqie** [Qv2ray/Qv2ray#1268]
您好，我想请教一下 Qv2ray 开启之后终端里可以访问 github.com 例如proxychains wget github.com , 但是访问不了 raw.githubusercontent.com 。 我尝试了很多方式 依然无法在命令行里访问 raw.githubusercontent.com
如前辈们知道怎么在 Qv2ray 里配置强制使用代理访问，或者配置config.json 访问，还请不吝赐教

## 说明
其他网站基本都可以在终端里访问，就这个 raw.githubusercontent.com 一直访问不了

## 例如运行如下命令:
qie@qie-server:/opt/catkin_ws$ proxychains wget https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml

## 返回结果:
qie@qie-server:/opt/catkin_ws$ proxychains wget https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
ProxyChains-3.1 (http://proxychains.sf.net)
--2021-02-06 22:08:20--  https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... |S-chain|-<>-127.0.0.1:1089-<>-127.0.0.1:1089-<>-127.0.0.1:8889-<><>-0.0.0.0:443-<><>-OK
connected.
Unable to establish SSL connection.

## 查看Qv2ray log：
* 发现 该域名并没有经过代理， 而是 `outBound_DIRECT` 了
![捕获](https://user-images.githubusercontent.com/16536572/107121200-1a5f4380-68cc-11eb-821e-4a2b3d8757c6.PNG)

## proxychains.conf 配置如下
```shell
socks4 127.0.0.1 1089
socks5 127.0.0.1 1089
http 127.0.0.1 8889
https 127.0.0.1 8889
```

**Comment by EpLiar** [comment]
DNS 被污染了

**Comment by DuckSoft** [comment]
首选项——连接设置——使用本地DNS——关

**Comment by database64128** [comment]
The option "Use local DNS" was somehow changed to be on by default, which is a really bad idea. We should change it ASAP. @DuckSoft @U-v-U

**Comment by DuckSoft** [comment]
Yes. I think so.

**Comment by wangzheqie** [comment]
I close the local dns enable, and still can not access to that site

![Screenshot from 2021-02-06 23-13-04](https://user-images.githubusercontent.com/16536572/107122202-36b1af00-68d1-11eb-814f-52d748cd7d23.png)

## the local dns
qie@qie-server:~$ cat /etc/resolv.conf
nameserver 127.0.0.53
options edns0 trust-ad
search lan

## local dns is changed each time when Qv2ray start
because I have set the system proxy
![Screenshot from 2021-02-06 23-16-48](https://user-images.githubusercontent.com/16536572/107122236-7ed0d180-68d1-11eb-975c-782af554d5d9.png)

**Comment by DuckSoft** [comment]
假设你的 HTTP 端口在 8889，请尝试在终端执行以下命令：

```bash
curl -x http://127.0.0.1:8889 -sSLv https://raw.githubusercontent.com/kidonng/scoop-install/fastgit/install.ps1
```

**Comment by U-v-U** [comment]
@database64128 I'll make it `false` by default.

**Comment by U-v-U** [comment]
it's now `false` by default, case closed.
