### ISSUE TITLE
使用疑问：「 请问如何使用http和https？ 」

### ISSUE THREAD

**Issue by wilsonxu123** [Qv2ray/Qv2ray#1273]
请问如何使用http和https？

**Comment by U-v-U** [comment]
@wilsonxu123 啥

**Comment by DuckSoft** [comment]
哦，我的老兄，这真是太不幸了，我准备把你送出去反省一下。

**Comment by EpLiar** [comment]
你想表达的是 `http_proxy` 和 `https_proxy` 么

**Comment by DuckSoft** [comment]
> 你想表达的是 `http_proxy` 和 `https_proxy` 么

我觉得他想找人给他补课。
