### ISSUE TITLE
Ubuntu 20.04 LTS KDE，通过官网下载的 Steam 的系统代理问题

### ISSUE THREAD

**Issue by ghost** [Qv2ray/Qv2ray#1276]
### 你想做啥？
linux 环境，想用 Qv2ray 的系统代理直接代理到 steam

看日志没连steam，系统代理是钩上启动的，规则是全局。

Qv2ray 设置的自启动和自动连接。

![](https://telegra.ph/file/1cac19474e166a2ba6246.png)
![](https://telegra.ph/file/5fb5d930bf9c95cffb0d5.png)
![](https://telegra.ph/file/48246364bd63cff913200.png)

**Comment by 2014CAIS01** [comment]
@naoko8964 https://qv2ray.net/getting-started/step4.html#使用系统代理

**Comment by DuckSoft** [comment]
我在 KDE Plasma 桌面和 GNOME 桌面环境下均测试通过。
不知道你具体是啥环境。

**Comment by naoko8964** [comment]
> 我在 KDE Plasma 桌面和 GNOME 桌面环境下均测试通过。
> 不知道你具体是啥环境。

咦，我是 kde ubuntu 。

**Comment by DuckSoft** [comment]
打开你的系统代理设置看看？去你的系统设置中心找找，找到之后给咱们截个图看看？

**Comment by DuckSoft** [comment]
我个人猜测是 gsettings 的问题。如果你在命令行打 gsettings 没有任何显示，那估计 Steam 也不会读到你的系统代理设置。Steam 一般是遵循 gsettings 里指定的系统代理的，你可以想法儿整一个 gsettings 装上，然后重启一下 Steam，重新连接一下节点，让 Qv2ray 通过 gsettings 指定一下代理或许就 OK 了。

**Comment by naoko8964** [comment]
我有 gsettings 2.64.6 ，刚换了个网络还是不行。

还没试别的全局代理软件

**Comment by Janet-Baker** [comment]
@naoko8964 ……直接SocksCap64或者透明代理吧
不用折腾了。。

**Comment by zhihuiyuze** [comment]
请使用https://github.com/springzfx/cgproxy 开启透明代理

**Comment by naoko8964** [comment]
@zhihuiyuze 
我 Qv2ray 没点透明代理，是要我去用透明代理走全局吗？

**Comment by zhihuiyuze** [comment]
如果您是想代理的只是steam客户端的话，您可以使用[proxychains](https://qv2ray.net/getting-started/step4.html#%E4%BD%BF%E7%94%A8-proxychains)
如果您是想用v2ray加速游戏的话，您可以参考https://github.com/springzfx/cgproxy.注意:您的v2ray节点必须是低延迟的QUIC/TCP节点，而不是第七层协议节点如WS等

**Comment by naoko8964** [comment]
先回报一下日志。已删除时间、IP 等，默认 Qv2ray 点了启动系统代理，版本 2.6.3 。
系统代理看了下 使用手动配置 HTTP SSL SOCKS FTP 都自动填进去了。

首先 firefox 的行为很诡异，about:preferences 里面走系统代理可以翻墙，但是关闭 Qv2ray 的系统代理也可以翻墙。确认后是 Qv2ray 点不点都改不了系统代理的配置（未尝试重启）。

然后 telegram debug 走系统代理看日志。
**TCP log**
`[] HTTP Info: sending 40 len request`
`[] HTTP Info: sending 40 len request`
`[] TCP Error 0, restarting! - Connection refused`
`[] HTTP Error 1, restarting! - Connection refused`
`[] HTTP Error 1, restarting! - Connection refused`
`[] TCP Error 0, restarting! - Connection refused`

**LOG**
`[] Debug logs started. (application.cpp : )`
`[] Connection Info: Connecting to x with x test connections. (session_private.cpp : )`
`[] TCP Info: dc:1 - Connecting to 'xxx.xxx.xxx.xxx:443' (connection_tcp.cpp : )`
`[] TCP Info: dc:1 - Connecting to 'xxx.xxx.xxx.xxx:443' (connection_tcp.cpp : )`
`[] HTTP Info: dc:1 - Sending fake req_pq to 'http://xxx.xxx.xxx.xxx:80/api' (connection_http.cpp : )`
`[] HTTP Info: dc:1 - Sending fake req_pq to 'http://xxx.xxx.xxx.xxx:80/api' (connection_http.cpp : )`
`[] TCP Error: socket connection refused - Connection refused`
`[] HTTP Error: connection refused - Connection refused`
`[] TCP Error: socket connection refused - Connection refused`
`[] HTTP Error: connection refused - Connection refused`
`[] MTP Info: restarting Connection (session_private.cpp : )`
`[] MTP Info: restart timeout: ****ms (session_private.cpp : )`
`[] MTP Info: restarting Connection (session_private.cpp : )`
`[] MTP Info: restart timeout: ****ms (session_private.cpp : )`
`[] Connection Info: Connecting to x with x test connections. (session_private.cpp : )`

**Qv2ray debug log**
`V2Ray 4.34.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.6 linux/amd64)`
`A unified platform for anti-censorship.`
` [Info] v2ray.com/core/main/jsonem: Reading config: /home/maybe/.config/qv2ray/generated/config.gen.json`
`[Debug] v2ray.com/core/app/log: Logger started`
`[Info] v2ray.com/core/app/dns: DNS: created UDP client inited for 1.1.1.1:53`
`[Info] v2ray.com/core/app/dns: DNS: created UDP client inited for 8.8.8.8:53`
`[Info] v2ray.com/core/app/dns: DNS: created UDP client inited for 8.8.4.4:53`
`[Debug] v2ray.com/core/app/stats: create new counter` `inbound>>>_QV2RAY_API_INBOUND_>>>traffic>>>uplink`
`[Debug] v2ray.com/core/app/stats: create new counter` `inbound>>>_QV2RAY_API_INBOUND_>>>traffic>>>downlink`
`[Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:15490`
`[Debug] v2ray.com/core/app/stats: create new counter inbound>>>http_IN>>>traffic>>>uplink`
`[Debug] v2ray.com/core/app/stats: create new counter inbound>>>http_IN>>>traffic>>>downlink`
`[Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:1146`
`[Debug] v2ray.com/core/app/stats: create new counter inbound>>>socks_IN>>>traffic>>>uplink`
`[Debug] v2ray.com/core/app/stats: create new counter inbound>>>socks_IN>>>traffic>>>downlink`
`[Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:1145`
`[Debug] v2ray.com/core/app/stats: create new counter outbound>>>WS>>>traffic>>>uplink`
`[Debug] v2ray.com/core/app/stats: create new counter outbound>>>WS>>>traffic>>>downlink`
`[Debug] v2ray.com/core/app/stats: create new counter outbound>>>outBound_DIRECT>>>traffic>>>uplink`
`[Debug] v2ray.com/core/app/stats: create new counter outbound>>>outBound_DIRECT>>>traffic>>>downlink`
`[Debug] v2ray.com/core/app/stats: create new counter outbound>>>outBound_BLACKHOLE>>>traffic>>>uplink`
`[Debug] v2ray.com/core/app/stats: create new counter outbound>>>outBound_BLACKHOLE>>>traffic>>>downlink`
`[Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:15490`
`[Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1146`
`[Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1145`
`[Info] v2ray.com/core/transport/internet/udp: listening UDP on 127.0.0.1:1145`
`[Warning] v2ray.com/core: V2Ray 4.34.0 started`
`[Debug] [1655146975] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:56930`
`[Info] [1655146975] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:56930`
`127.0.0.1:56930 accepted tcp:127.0.0.1:0 [_QV2RAY_API_]`
`[Info] [1655146975] v2ray.com/core/app/dispatcher: taking detour [_QV2RAY_API_] for [tcp:127.0.0.1:0]`
**`[Info] [1750395283] v2ray.com/core/proxy/socks: TCP Connect request to tcp:xxx.xxx.xxx.xx:443`**
`[Info] [1750395283] v2ray.com/core/app/dispatcher: default route for tcp:xxx.xxx.xxx.xx:443`
`[Info] [1750395283] v2ray.com/core/transport/internet/websocket: creating connection to tcp:xxx.xxx.xxx.xxx:443`
`tcp:127.0.0.1:35514 accepted tcp:xxx.xxx.xxx.xxx:443 [WS]`
`[Info] [1750395283] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:xxx.xxx.xxx.xxx:443 via tcp:xxx.xxx.xxx.xxx:443`
`[Info] [1750395283] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled`
`[Info] [1750395283] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled`

Telegram 和 V2ray 的日志有时间差，我多次重试连接后才走 v2ray 输出  **`[Info] [1750395283] v2ray.com/core/proxy/socks: TCP Connect request to tcp:xxx.xxx.xxx.xx:443*`**

应该就这些吧，感觉看不出什么，挺诡异的。
还需要什么吗？ @DuckSoft

**Comment by DuckSoft** [comment]
信息不足，事主已销号跑路……先咕了
