### ISSUE TITLE
使用疑问：「 无法关闭http_proxy 」

### ISSUE THREAD

**Issue by mzr1996** [Qv2ray/Qv2ray#1278]
### 你想做啥？
我想关闭Qv2ray的系统代理设置。现在系统即使不启动Qv2ray,也会开机设置上http_proxy、https_proxy、ftp_proxy等一系列环境变量。

### 你目前试了啥？
我在“首选项”-“入站设置”里关闭了HTTP设置、SOCKS设置、“设置系统代理”设置、进行重新连接，都没法清除http_proxy环境变量。我在/etc, /usr, /home等目录下搜索http_proxy设置，也没有找到设置文件。

### 其他要补充的信息？
系统Manjaro
软件版本Qv2ray 2.7.0-pre1 on Manjaro Linux x86_64

**Comment by DuckSoft** [comment]
你用的啥桌面环境啊？难不成是 Deepin 吗？

**Comment by DuckSoft** [comment]
兄弟，你人呢？问完问题就跑路了，也不回一下，这怎么成呀

**Comment by DuckSoft** [comment]
如果是 Deepin UOS 桌面用户，早在 2020 年 5 月 10 号的时候，我们就向上游提过相关的 bug 了：
- https://github.com/linuxdeepin/go-lib/issues/15
- https://xmuli.tech/posts/60b2fbd8/

如果是其他桌面环境的用户，请详细留言。当前的信息量还是太少了，没法做出判断。

**Comment by mzr1996** [comment]
不是，我问完又去接着试了，还是不行。
桌面系统是i3wm

**Comment by mzr1996** [comment]
> 
> 
> 你用的啥桌面环境啊？难不成是 Deepin 吗？

桌面环境是i3wm

**Comment by DuckSoft** [comment]
我非常肯定以及确信这个行为与 Qv2ray 没有任何关系，因为 Qv2ray 不会直接覆写你的任何有关环境变量相关的配置，他只会通过调用 KDE 和 GNOME 的设置后端去设置/清除系统代理。然而，就算是 KDE 和 GNOME 自带的系统代理，他们也不会通过强制劫持环境变量的方式完成“代理”的设置动作。

你可能需要仔细检查系统的其他部分。

**Comment by 2014CAIS01** [comment]
@mzr1996 检查一下是不是在 .xinitrc .bashrc .bash_profile 等各种会在i3wm启动前执行的脚本中是否export了对应的环境变量

**Comment by mzr1996** [comment]
> 我非常肯定以及确信这个行为与 Qv2ray 没有任何关系，因为 Qv2ray 不会直接覆写你的任何有关环境变量相关的配置，他只会通过调用 KDE 和 GNOME 的设置后端去设置/清除系统代理。然而，就算是 KDE 和 GNOME 自带的系统代理，他们也不会通过强制劫持环境变量的方式完成“代理”的设置动作。
> 
> 你可能需要仔细检查系统的其他部分。

看到你提到Gnome后端，我去检查了一圈，发现只有gnome系的软件会设置自动代理，最后发现了问题出在gnome-setting里，使用`gsettings set org.gnome.system.proxy mode 'none'`就能关闭自动代理了。不过不知道为什么Qv2ray里的“入站设置”里修改http端口的设置对gnome是有效的，但是关闭系统代理的设置似乎并没有对gnome的设置key起到什么效果。这也是之前我一直关不掉代理的原因

**Comment by DuckSoft** [comment]
好，很有意思，有空我去整个 Manjaro i3 看看是什么情况。

**Comment by skiy** [comment]
Ubuntu 20.04 也无法关闭 https 代理：   
打开终端时，```echo $https_proxy  或 $http_proxy``` 都有值，如图：   
![image](https://user-images.githubusercontent.com/3362147/109449624-e5d24800-7a83-11eb-9b2c-d1d7f1288803.png)

但是，**入站设置**里明明没有选择**系统代理**，也没有选择 **HTTP设置**:   
![image](https://user-images.githubusercontent.com/3362147/109449708-174b1380-7a84-11eb-927c-90100e3deb3f.png)
