### ISSUE TITLE
[可能是BUG] [需要帮助] GNOME里qv2ray不会在通知区域里显示图标

### ISSUE THREAD

**Issue by cloudwindy** [Qv2ray/Qv2ray#1280]
**我遇到的问题**

当前版本的Qv2ray在按下右上角的关闭按钮之后直接消失，再次启动需要在GNOME左侧菜单重新选择Qv2ray才能打开之前的窗口。*我其实也不清楚到底是Qv2ray没有实现通知区域还是实现了但是出了bug。。。*

**简单描述你预期的解决方案？**

Qv2ray按下关闭按钮时隐藏到右上角的通知区域，而不是直接消失。

**你有想到其他比较容易实现的解决方案吗？**

可以参考Linux版网易云，Linux版Qbittorrent之类的的实现，他们都是隐藏到右上角通知区域的。

**补充内容**

* 系统：Ubuntu 20.04
* 内核：Linux 5.8.0-41-generic（`uname -a`）
* 桌面：GNOME Shell 3.36.4（`gnome-shell --version`）
* 我正在使用的Qv2ray：qv2ray 2.6.3（`qv2ray --version`）

**Comment by cloudwindy** [comment]
我看了一下其他的issues提到了这个程序似乎在Windows下面是有**右下角通知图标**的，那么这个issue**非常有可能是一个bug反馈而不是功能请求**。

问题重现步骤：

* 安装Ubuntu 20.04测试环境
* `apt update && apt upgrade`升级所有软件（包括GNOME）
* 从Ubuntu官方软件源安装Qv2ray：`apt install qv2ray`
* 打开qv2ray：`qv2ray`
* 在新打开的窗口上按下右上角的 关闭按钮
* **窗口直接消失了，右上角没有出现通知图标**

我个人推测可能的原因所在（还没去看过源代码）：

* GNOME 3.26版本移除了系统托盘，可能是qv2ray仍然依赖系统托盘？

**Comment by cloudwindy** [comment]
我看了一下源代码，说说我的分析（对Qt和C++不太了解，不一定对）

这里qv2ray初始化`Qv2rayApplication`的时候会实例化类`QSystemTrayIcon`并赋值给`hTray`属性

https://github.com/Qv2ray/Qv2ray/blob/380049ecfad4fd65ca845b6f0af26bec7a2a706d/src/Qv2rayApplication.cpp#L40

在头文件里我们得知类`Qv2rayApplication`里可以使用`GetTrayIcon`方法获得刚才的`hTray`对象

https://github.com/Qv2ray/Qv2ray/blob/380049ecfad4fd65ca845b6f0af26bec7a2a706d/src/Qv2rayApplication.hpp#L95-L98

最后，定义了宏`qvAppTrayIcon`来调用`GetTrayIcon`（实际上还是用来拿刚才的`hTray`的）

https://github.com/Qv2ray/Qv2ray/blob/380049ecfad4fd65ca845b6f0af26bec7a2a706d/src/Qv2rayApplication.hpp#L126

当主窗口加载的时候真正地使用上述的方法创建图标

https://github.com/Qv2ray/Qv2ray/blob/380049ecfad4fd65ca845b6f0af26bec7a2a706d/src/ui/windows/w_MainWindow.cpp#L243

看到这里为止似乎没发现什么问题

**Comment by cloudwindy** [comment]
有可能是上游错误

一个在GitHub上可能有关的issue。。。nextcloud/desktop/issues/1977（他们说是Ubuntu的AppIndicator的锅，hhh）

在网上搜索了一下，有一个可能的解决方案：https://www.medo64.com/2019/07/qsystemtrayicon-not-showing-under-ubuntu/
（还没测试），示例代码如下：

```c++
_tray = new QSystemTrayIcon(this);
connect(_tray, SIGNAL(activated(QSystemTrayIcon::ActivationReason)),
         this, SLOT(onTrayActivate(QSystemTrayIcon::ActivationReason)));

QMenu* trayMenu = new QMenu(this);;
trayMenu->addAction("&Show", this, SLOT(onTrayShow()));
trayMenu->addSeparator();
trayMenu->addAction("E&xit", this, SLOT(onTrayExit()));
_tray->setContextMenu(trayMenu);

_tray->setIcon(trayIcon);
_tray->setToolTip(QCoreApplication::applicationName());
_tray->show();
```

**Comment by MarksonHon** [comment]
@cloudwindy 其实在原始 Gnome 下安装 AppIndicator 应该是可以的，但是 Ubuntu 自己搞了个 Ubuntu 会话🤣，我自己实测这样一来就不行了。

**Comment by cloudwindy** [comment]
@MarksonHon 那有啥办法么，现在我每次需要改配置文件的时候都需要手动开一遍，麻烦死了

除了Qv2ray以外还有Wine也不支持那个AppIndicator，会弹出一个小窗口“Wine System Tray”

我现在根本无法理解AppIndicator到底是怎么工作的，似乎装了跟没装没啥区别

**Comment by DuckSoft** [comment]
上游问题，爱莫能助。

**Comment by cloudwindy** [comment]
虽然这个问题已经确定是上游问题了，但是我刚才还是找到了一个临时解决方案，给有需要的人使用

使用GNOME扩展TopIconsPlus之后Qv2ray就可以显示在屏幕上方了
