### ISSUE TITLE
使用默认的“绕过中国大陆模式”无法播放优酷（网页版）

### ISSUE THREAD

**Issue by BrunuhVille** [Qv2ray/Qv2ray#1281]
软件版本：Qv2ray v2.7.0-pre1 预览版
“首选项”里的“连接设置”均为默认，未改动，默认设置自带“绕过中国大陆模式”
无法播放优酷网页版，
然后将“首选项”》“高级路由设置”的域名策略，逐次修改为 "AsIs"，"IPIfNonMatch"，"IPOnDemand"
再测试，依然无法播放优酷视频

求助，如何解决这个问题

**Comment by DuckSoft** [comment]
观察日志很重要。
网页开优酷，日志里刷出来优酷了吗？
改域名策略无效，是不是偶然用了“复杂配置”，导致其分流规则完全独立，不受首选项控制？

**Comment by MarksonHon** [comment]
@DuckSoft 你需要更新一下内核及其附带的两个dat文件，Qv2ray作为皮肤是没法决定内核最后的行为的

**Comment by BrunuhVille** [comment]
> @DuckSoft 你需要更新一下内核及其附带的两个dat文件，Qv2ray作为皮肤是没法决定内核最后的行为的

感谢指点，内核更新刀4.34，然后https://github.com/Loyalsoldier/v2ray-rules-dat使用这个更新了dat文件，
目前出现的状况是播放优酷/切换剧集 时会有一段至少十几秒甚至几十秒的停滞。
换到v2rayN最新版4.11（去除pac模式，换为路由设置）也存在播放类似的问题，
而使用v2rayN旧版3.29（有pac模式）大概只有几秒的停滞，目前就使用这个了

**Comment by DuckSoft** [comment]
你要配置 DNS 分流，否则远程 DNS 解析当然会卡你。
这里给你个参考方案，直接照抄即可：

![图片](https://user-images.githubusercontent.com/7822648/107462842-f20b6980-6b97-11eb-9574-c1ec7da4fe9e.png)

![图片](https://user-images.githubusercontent.com/7822648/107462875-07809380-6b98-11eb-8f2a-099115192158.png)
![图片](https://user-images.githubusercontent.com/7822648/107462883-0b141a80-6b98-11eb-9ac9-41f7b1e71eba.png)
