### ISSUE TITLE
关于入站设置 - HTTP设置的bug反馈

### ISSUE THREAD

**Issue by DLGum** [Qv2ray/Qv2ray#1285]
平台：最新win10 64位
问题描述：可能影响部分软件联网。目前发现崩坏3提示联网失败。
问题确认：退出qv或关闭http代理后崩坏3联网正常。开启后崩坏3一直联网失败。
其他确认：火绒扫描网络诊断显示IE代理异常。修复后会关闭win10的系统代理，使用qv后会再自动打开。
![V`B)YCOH{@AQJ`PJ}D25351](https://user-images.githubusercontent.com/45528130/107657848-85d85500-6cc0-11eb-88b1-88f897d63c3c.png)

关闭代理前崩坏3弹窗
![000](https://user-images.githubusercontent.com/45528130/107659039-b371ce00-6cc1-11eb-87e2-c5009a04d3f9.png)

**Comment by 2014CAIS01** [comment]
开启系统代理后，你的游戏也会遵循系统代理的话就应该是你的节点问题，请根据日志分析。此处 Qv2ray 的软件行为似乎都符合预期，并不存在 bug。

**Comment by DLGum** [comment]
> 开启系统代理后，你的游戏如果遵循系统代理的话，出现连接失败就确实是连接问题，请根据日志分析。此处 Qv2ray 的软件行为似乎都符合预期，并不存在 bug。

不怎么会看log。我尝试使用clash跑trojan的话崩坏3正常登陆。换回qv不行。
不存在bug就难办了。问题在哪呢。

**Comment by MarksonHon** [comment]
@DLGum 问题要你自己去找，日志要你自己去看。
