### ISSUE TITLE
使用疑问：「 所以 v2.7.0-pre2 更新了什么啊 」

### ISSUE THREAD

**Issue by heiyutian** [Qv2ray/Qv2ray#1287]
我看到提示更新v2.7.0-pre2 ，但是我没看到像v2.7.0-pre1 那样的详细更新说明，所以我有必要更新到v2.7.0-pre2 吗

**Comment by flylai** [comment]
浏览 [commit log](https://github.com/Qv2ray/Qv2ray/commits/v2.7.0-pre2) 获取更多信息

**Comment by heiyutian** [comment]
> 浏览 [commit log](https://github.com/Qv2ray/Qv2ray/commits/v2.7.0-pre2) 获取更多信息

我尝试从下面的地址找到你上面的链接入口，找了半天没找到。
https://github.com/Qv2ray/Qv2ray
只能通过你的这个链接点击才能进去，请问下面这个链接怎么才能自己从项目主页找到啊。
https://github.com/Qv2ray/Qv2ray/commits/v2.7.0-pre2

**Comment by flylai** [comment]
在 [Releases](https://github.com/Qv2ray/Qv2ray/releases) 中找到你需要的版本，在左侧有个书签的图标和当前版本的tag，点击他就好了

**Comment by heiyutian** [comment]
> 在 [Releases](https://github.com/Qv2ray/Qv2ray/releases) 中找到你需要的版本，在左侧有个书签的图标和当前版本的tag，点击他就好了

在Releases页面点击左侧的v2.7.0-pre2之后，进入了下面的地址
https://github.com/Qv2ray/Qv2ray/tree/v2.7.0-pre2
然后还是没找到怎么进入下面的地址入口
https://github.com/Qv2ray/Qv2ray/commits/v2.7.0-pre2

**Comment by flylai** [comment]
进入那个地址之后点击 **2,906 commits** 就行了
Releases 界面中，你可以点击那个小书签底下的 `compare` 然后选择相应版本，这样也许会更直观

**Comment by heiyutian** [comment]
> 进入那个地址之后点击 **2,906 commits** 就行了
> Releases 界面中，你可以点击那个小书签底下的 `compare` 然后选择相应版本，这样也许会更直观

感谢总算找到了，是有2906条更改吗，那也太费劲了，你们修改起来很麻烦，我们这些外行可能连主要修改了什么都看不出来。
