### ISSUE TITLE
功能请求：插件目录为Qv2ray同级目录或可配置。

### ISSUE THREAD

**Issue by 0x0004** [Qv2ray/Qv2ray#1288]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

打包复制整个文件夹到新电脑后插件丢失。

**简单描述你预期的解决方案？**

插件目录默认为Qv2ray同级目录，或可配置。

**你有想到其他比较容易实现的解决方案吗？**

把插件目录硬编码写死为同级目录。

**补充内容**

我的v2ray核心路径为./vcore/v2ray.exe，v2ray资源目录为./vcore。都是同级目录，压缩打包后就很方便不用重新下载。

**Comment by MarksonHon** [comment]
如果你使用7zip压缩包版本，那么插件就是在Qv2ray的配置目录里面啊，，压缩的时候不漏掉即可。

**Comment by xiajinz** [comment]
![U88EOQX~IUF{PPNZFFPD EF](https://user-images.githubusercontent.com/70129487/107872034-35d8d880-6ee2-11eb-9113-d143062474b8.png)
What's going on

**Comment by 0x0004** [comment]
> 如果你使用7zip压缩包版本，那么插件就是在Qv2ray的配置目录里面啊，，压缩的时候不漏掉即可。

7z解压后，默认插件目录打开是 C:\Users\用户名\AppData\Local\qv2ray\plugins
