### ISSUE TITLE
总感觉“绕过大陆”模式有弊端

### ISSUE THREAD

**Issue by byteslaves** [Qv2ray/Qv2ray#1290]
绕过中国大陆网站，那么只要国内的网站接一个gfw提供的国外ip探测api就死定了，双ip必然是挂梯子了，瑟瑟发抖啊。
另外，我前几天的vless+xtls+转外贸网站的鸡仔被掐死了，可怜我的年付才用了一个多月，心累。

**Comment by EpLiar** [comment]
因噎废食

**Comment by byteslaves** [comment]
> 因噎废食

哈哈，只是突然不小心想到这个问题罢了。可能gfw已经推行了这个方法，只需要在几个大型网站挂上，一钓一个准。哎，真太难了啊，其他倒无所谓，只是编程的时候会使用到国外的资源，就像之前用flutter时，环境配置简直和玄学差不多，而且不走梯子访问gayhub也很慢，想看看大佬的代码都难。

**Comment by EpLiar** [comment]
> 哈哈，只是突然不小心想到这个问题罢了。可能gfw已经推行了这个方法

比起毫无依据的猜测，更严重的是你实名上网吧……

**Comment by byteslaves** [comment]
> > 哈哈，只是突然不小心想到这个问题罢了。可能gfw已经推行了这个方法
> 
> 比起毫无依据的猜测，更严重的是你实名上网吧……

有道理，安分守己方为真国人。
想不到作者大佬会回复，还以为是社区网友呢，新年快乐啊，大佬。

**Comment by U-v-U** [comment]
在人没有安全意识的情况下，任何技术都不能保证安全性
更重要的是在访问网站的时候时刻保持小心

> 技术防不住人心叵测

**Comment by byteslaves** [comment]
> 在人没有安全意识的情况下，任何技术都不能保证安全性
> 更重要的是在访问网站的时候时刻保持小心
> 
> > 技术防不住人心叵测



> 在人没有安全意识的情况下，任何技术都不能保证安全性
> 更重要的是在访问网站的时候时刻保持小心
> 
> > 技术防不住人心叵测

的确如此，但有时候Google查资料的时候当然是以最相似答案的文章点击，多无奈啊。
只是突然想到这个问题感到我们这些在功夫网下爬行的虫子很悲哀罢了，都怪那些反动势力。
另外，也祝大佬新年快乐。

**Comment by byteslaves** [comment]
下机了，出去骚一会，难得过年。@所有人  新年快乐
