### ISSUE TITLE
重启时一定机率无法正常关闭直到超时

### ISSUE THREAD

**Issue by mjysci** [Qv2ray/Qv2ray#1291]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
重启或关机时一定机率会卡在`A stop job is running for Session 2 of user...`然后开始90秒倒计时，直到超时才强制关闭。  
执行`journalctl -p5`查看日志如下：  
```
2月 15 20:38:27 ubuntu systemd[1]: session-2.scope: Stopping timed out. Killing.
2月 15 20:38:27 ubuntu systemd[1]: session-2.scope: Killing process 3121 (qv2ray) with signal SIGKILL.
2月 15 20:38:27 ubuntu systemd[1]: session-2.scope: Failed with result 'timeout'.
```
可见是qv2ray无法正常关闭，最后超时强制关闭。

## 如何触发这个 Bug：

1.  执行`Qv2ray.v2.6.3.linux-x64.AppImage`
2. 打开`Preferences - General Settings`，在`Behavior`处启用开机自启`Launch at Login`。
2. 重启或关机一定机率触发

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
不是连接问题

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：
Qv2ray日志正常，不是连接问题。

```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.ubuntu-16.04
```

### 操作系统

- Linux (Ubuntu 18.04)

### 安装来源

- Github Release / Scoop / Chocolatey (Qv2ray.v2.6.3.linux-x64.AppImage)

### 已安装的插件、版本及安装来源
无插件

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
AppImage 版本有已知的会话管理问题，请选用原生包。
