### ISSUE TITLE
功能请求：窗口大小的记忆功能

### ISSUE THREAD

**Issue by QyQj** [Qv2ray/Qv2ray#1292]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

最大化窗口关闭后再从托盘打开就会回到默认的窗口大小，虽然拉大窗口不会这样，重启系统后仍会恢复默认的窗口大小

**补充内容**
平台是windows10 20H2

**Comment by atest1** [comment]
对，每次重启后都会恢复原状，这点很讨厌。另外建议重启后恢复上一次的站点排列次序选项

**Comment by 2014CAIS01** [comment]
This is a known issue. Due to the existence of complex situations such as multiple displays, this feature has been temporarily removed. We will fix it in the near future.
