### ISSUE TITLE
测试真连接延迟时结果错误输出

### ISSUE THREAD

**Issue by Fangliding** [Qv2ray/Qv2ray#1293]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
在尝试选中多个节点测试真延迟时候，只会用当前连接节点测试多次真延迟并输出在不同的节点上

## 如何触发这个 Bug：

1. 在软件中添加多个节点
2. 随便选中一个并连接
3. 选中包括当前连接节点在内的多个节点
4. 将鼠标移至当前连接的节点并右击测试真延迟

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

nope

### 相关截图或日志

https://i.imgur.com/89k1XgK.png
在最上面那个节点是联不通的，但是仍测出结果，由此可以推测出这个测试走的是当前正在连接的节点
```
请从此行下面的行开始粘贴 Qv2ray 日志：

2021/02/17 14:42:53 127.0.0.1:5722 accepted //www.google.com:443 [PROXY]
2021/02/17 14:42:53 127.0.0.1:5723 accepted //www.google.com:443 [PROXY]
2021/02/17 14:42:53 127.0.0.1:5724 accepted //www.google.com:443 [PROXY]
2021/02/17 14:42:53 127.0.0.1:5727 accepted //www.google.com:443 [PROXY]
2021/02/17 14:42:53 127.0.0.1:5728 accepted //www.google.com:443 [PROXY]
每多选中一条节点 连接谷歌的纪录便会多五条
```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.7.0-pre2:6150
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-4cc95cb2f686250c899a04969e1a220af449908d-ci.windows-latest
```

### 操作系统

- Windows 10

### 安装来源

- Github Release / Scoop / Chocolatey

### 已安装的插件、版本及安装来源
https://i.imgur.com/XetoWwB.png
均是在GitHub Realese下载的最新版本
## 附加信息

如果鼠标右击的地方不是正在连接的节点 则测试真连接延迟按钮为灰色

之前的版本中并没有这个BUG 如果选中多个 右击未连接的节点 结果如上 如果是右击正在连接的节点 便可以测试真延迟 但是只会测试一次并输出到正在连接的那个节点上

之前就想QV2ray像v2rayN一样添加一个批量测试真延迟，但想到V2rayN都做了这么久了Qv2ray还没做或许是有各种其他原因，也就没问过，不过这次这个样子肯定是个BUG了，就提交上来了

**Comment by DuckSoft** [comment]
当前没有多选测试真延迟功能，若有大佬不吝PR，感激不尽。

**Comment by Fangliding** [comment]
> 当前没有多选测试真延迟功能，若有大佬不吝PR，感激不尽。

我看过更新知道没有多选测试真延迟，所以选中多个节点并右击时候 测试真延迟的按钮应该是**灰色的**，但是可以看到我给出的图片里如果右键**当前的连接的节点**，这个按钮可点，但是点了也只会测试出当前连接的节点，如果是这样，那还算不上BUG，重要的是相较于之前的版本，它会把**同一节点**的延迟**测试多次**并把这个节点的测试结果输出到**其他节点**上，我发现这个BUG的原因是它会将延迟输出到**根本无法连接**的节点(就是我给的图片的第一个节点)上，正常情况下它应该要么没用反映要么输出错误
