### ISSUE TITLE
使用疑问：「 arch linux上连接节点后无法使用 」

### ISSUE THREAD

**Issue by lyh970817** [Qv2ray/Qv2ray#1300]
### 你想做啥？
*简要描述你的最原始的目的。*
科学上网

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

我通过aur和archlinuxcn安装了v2ray-core和Qv2ray，在Qv2ray上添加了订阅地址，选择了节点连接。连接后log提示

V2Ray 4.34.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.6 linux/amd64)
A unified platform for anti-censorship.
2021/02/20 12:49:44 [Info] v2ray.com/core/main/jsonem: Reading config: /home/lyh970817/.config/qv2ray/generated/config.gen.json
2021/02/20 12:49:44 [Warning] v2ray.com/core: V2Ray 4.34.0 started
2021/02/20 12:49:45 127.0.0.1:36744 accepted tcp:127.0.0.1:0 [_QV2RAY_API_]

在浏览器中打开网页后log没有变化，之后仍然无法连上外网

**Comment by MarksonHon** [comment]
1. 阅读文档：
<https://qv2ray.net>
2. 进群求助：
<https://t.me/qv2ray>
