### ISSUE TITLE
关闭系统代理无效

### ISSUE THREAD

**Issue by wk989898** [Qv2ray/Qv2ray#1301]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
在首选项中关闭`设置系统代理`选项后系统代理并没有关闭

## 如何触发这个 Bug：

1. 已开启系统代理
2. 首选项中关闭系统代理
3. 系统设置中查看系统代理并没有关闭

### 打开首选项 -> 关于，填写以下信息

```
版本: 
编译信息：
额外编译信息：
```

### 操作系统

- Windows

### 安装来源

- ArchLinuxCN - 稳定版
- ArchLinuxCN - 开发版
- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版
- Fedora - 稳定版
- Fedora - 开发版
- openSUSE - 稳定版
- openSUSE - 开发版
- Flathub 包
- Snap 包
- Homebrew Cask
- Github Release / Scoop / Chocolatey
- 手动编译

## 附加信息

*请注意打码隐私相关信息。*

**Comment by TsXor** [comment]
这个不是bug，是个语文阅读理解问题 ;)
关闭“设置系统代理” 是 Qv2Ray停止设置系统代理 而不是 Qv2Ray关掉系统代理
区别在哪？
关闭“设置系统代理”前：在Qv2Ray启动前关闭系统代理的开关，启动Qv2Ray的时候再去看，发现它被自动打开了
关闭“设置系统代理”后：在Qv2Ray启动前关闭系统代理的开关，启动Qv2Ray的时候再去看，它还是关闭的

**Comment by DuckSoft** [comment]
首选项的是每次连接时的行为，托盘菜单才是实际的一次性动作。
