### ISSUE TITLE
Question: how to force all applications to use proxy?

### ISSUE THREAD

**Issue by SamadiPour** [Qv2ray/Qv2ray#1302]
### Describe You Purpose
Recently I realized that qv2ray doesn't work in the terminal or cmd. It works fine in the browser and telegram. Not tested for all applications yet, but I definitely need it for terminal :D

### Describe What Have You Tried
I have tried:
- Enabling system proxy as instructed in https://qv2ray.net/en/getting-started/step4.html#using-system-proxy
- Using  environment variables
- Force direct for all connection (no app works after enabling this option)

**Comment by U-v-U** [comment]
@SamadiPour For Windows, you may need extra applications, e.g. Proxifier
For Linux, we'd suggest using cgproxy: https://github.com/springzfx/cgproxy

**Comment by SamadiPour** [comment]
@U-v-U Thanks for the response. What about macOS?

**Comment by U-v-U** [comment]
@SamadiPour I'm not familiar with macOS, perhaps someone else may give a help.

**Comment by dyhkwong** [comment]
You can use tun2socks (like [this](https://github.com/eycorsican/go-tun2socks)) or some of its wrappers on most platforms.

**Comment by Ahmadreza-sharif** [comment]
> @U-v-U Thanks for the response. What about macOS?

did you find solution?
