### ISSUE TITLE
macOS报错：当前用户没有 V2Ray 核心控制文件的可执行权限。Qv2ray 尝试设置，但由于权限不足，操作已失败。

### ISSUE THREAD

**Issue by xsy2004** [Qv2ray/Qv2ray#1303]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

使用Releases中的macOS版本Qv2ray更换xray内核报错：当前用户没有 V2Ray 核心控制文件的可执行权限。Qv2ray 尝试设置，但由于权限不足，操作已失败，但是使用v2ray内核没有问题

## 如何修复这个 Bug：

1. 命令行打开qv2ray目录/Applications/qv2ray.app
2. 进入Contents/MacOS目录
3. sudo ./qv2ray
4. 输入密码给予高权限即可解决
### 打开首选项 -> 关于，填写以下信息

```
版本: 2.7.0-pre2:6150
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-4cc95cb2f686250c899a04969e1a220af449908d-ci.macos-latest
```

### 操作系统

- macOS bigSur 11.2.1

### 安装来源

- Github Release / Scoop / Chocolatey

**Comment by 2014CAIS01** [comment]
你不是修复了吗？

**Comment by MarksonHon** [comment]
<https://qv2ray.net/faq/v2ray-core.html#linux-macos-%E6%B2%A1%E6%9C%89%E5%8F%AF%E6%89%A7%E8%A1%8C%E5%B1%9E%E6%80%A7>

**Comment by xsy2004** [comment]
> https://qv2ray.net/faq/v2ray-core.html#linux-macos-%E6%B2%A1%E6%9C%89%E5%8F%AF%E6%89%A7%E8%A1%8C%E5%B1%9E%E6%80%A7

尝试过，但是并没有用

**Comment by MarksonHon** [comment]
@xsy2004 <https://t.me/qv2ray>

进群聊
