### ISSUE TITLE
Qv2ray未启动时，浏览网页时提示“代理服务器拒绝连接”

### ISSUE THREAD

**Issue by TsXor** [Qv2ray/Qv2ray#1304]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**
## 简单描述这个 Bug:
Qv2ray未启动时，浏览网页时提示“代理服务器拒绝连接”（标题）
只要Qv2ray启动过一次，即使再关闭，此bug也不会再次出现
将Firefox设为“自动检测此网络的代理设置”，Qv2ray失效，此bug不出现
关掉系统代理开关（电脑设置--网络--代理--手动设置代理--使用代理服务器），此bug不出现

## 如何触发这个 Bug：
1. 不设置QV2Ray开机自启，开机/重新启动
2. 打开Firefox
3. 访问一个Internet网页

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
不是连接问题，但在V2RayN中未出现过

### 相关截图或日志
此问题发生在Qv2Ray未启动时，所以没有相关日志

## 系统信息
- Windows 8.1 专业版

### 打开首选项 -> 关于，填写以下信息
版本: 2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.windows-latest

### 操作系统
- Windows(8.1)

### 安装来源
- Github Release / Scoop / Chocolatey

### 已安装的插件、版本及安装来源
Trojan-GFW Plugin --github release
SSR Plugin --github release
Trojan-Go Plugin --github release
SS Plugin --github release

## 附加信息
暂无

**Comment by DuckSoft** [comment]
这是系统代理没有清除的状态下的预期行为。
请使用正确的方式清除系统代理即可。

**Comment by TsXor** [comment]
我已经自己解决了这个问题：
1.打开Qv2ray的“设置系统代理”
2.将这条命令：
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyEnable  /t REG_DWORD /d 0 /f
存入“DisableProxy.bat”并设置它开机启动
这样就可以开机自动关闭系统代理

但是我希望Qv2ray可以在关闭时自动清除 ;)

**Comment by 2014CAIS01** [comment]
@TsXor 请问为啥需要开机自动关闭系统代理呢

**Comment by DuckSoft** [comment]
实际上，Qv2ray 在我的测试环境下，在正常退出时是能自动清除系统代理设置的。
这可能是因为 Qt 的 SessionManager 没有正确检测到系统的关机/注销等会话结束事件，也可能是因为系统直接将程序杀死，没有来得及清除系统代理设置。具体原因等有空再排查吧。

**Comment by NinjaUmbra** [comment]
我觉得你可以设置一下关机时等待程序关闭后在关机
也就是不要使用优化软件把不等待程序关闭即关机 不清楚你是否做过这个优化 大部分垃圾清理优化软件都会优化这一项达到快速关机的目的

**Comment by TsXor** [comment]
@NinjaUmbra 
我确认了一下，没做过这个优化。
v2rayN也能正常清

**Comment by ghost** [comment]
这bug挺烦的，每次使用必现
