### ISSUE TITLE
Auto Select Best Ping server in group and Some Features

### ISSUE THREAD

**Issue by Ja7adR** [Qv2ray/Qv2ray#1305]
Hi

**1.**
Qv2ray is very good , But need Auto Select Best Ping server or High availability server.
Shadowsocks Windows have this feature and good choice.

https://github.com/shadowsocks/shadowsocks-windows

**2.**
Remove Timeouted servers with onetap click in group.

**3.**
Import and Export Feature , All server in one file for Qv2ray

**4.**
add Clash method support

**Comment by U-v-U** [comment]
1. As I've known, shadowsocks-windows is planning to remove the high-availability option.
2. Defining a node as "timed-out" is difficult, it depends on the current network status.
3. Qv2ray is portable, you may carry the `config` directory and go anywhere you want.
4. Unfortunately Qv2ray is a front-end for V2Ray but not Clash, however, a plugin is always welcomed.
