### ISSUE TITLE
snap 安装 2.7.0 pre2 6150 启动服务会报错

### ISSUE THREAD

**Issue by XuanJiAndroid** [Qv2ray/Qv2ray#1306]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
snap 安装 2.7.0 pre2 6150 版本，启动服务会报如下错误

```
其他进程占用了启动连接所需的端口：

端口: 127.0.0.1:15490 for inbound: "QV2RAY_API_INBOUND"
端口: 127.0.0.1:8889 for inbound: "http_IN"
端口: 127.0.0.1:1089 for inbound: "socks_IN"

```

## 如何触发这个 Bug：

1. sudo snap install qv2ray --beta 
2. 安装后替换核心为  Xray 1.2.1 (Xray, Penetrates Everything.) Custom (go1.15.6 linux/amd64)
3. 导入服务json配置
4. 右键点击连接到此服务即报错

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
使用github releases 上的 Appimage版本一切正常

### 相关截图或日志

![截图](https://user-images.githubusercontent.com/21168212/108944539-e474da00-7695-11eb-9107-760c1c3fec12.png)

```
请从此行下面的行开始粘贴 Qv2ray 日志：
没有任何日志显示

```

## 系统信息
UOS 20 个人版

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.7.0-pre2:6150
编译信息：Qv2ray from manual build
额外编译信息：2.7.0-pre2:6150
```

### 操作系统

Linux

### 安装来源

 Snap 包

### 已安装的插件、版本及安装来源
原来自带的Builtin Protocol Support 和Builtin Subscription Support 没有安装其他插件

## 附加信息

*请注意打码隐私相关信息。*

**Comment by MarksonHon** [comment]
@XuanJiAndroid 不要同时运行两个Qv2ray，或者修改其中一个版本的默认端口号。

**Comment by flylai** [comment]
详细信息可加群 https://t.me/Qv2ray 讨论
