### ISSUE TITLE
win7不能显示速度

### ISSUE THREAD

**Issue by smartnikocj** [Qv2ray/Qv2ray#1309]
### 你想做啥？
*简要描述你的最原始的目的。*
一直使用qv2ray 2.63版本， 4.26core，win7，trojan链接，谢谢！但是最近什么都没有改变，正常使用发现实时速度图像、右下角速度显示及左侧名称下面的流量统计都不会动了。任何设置都没有改变！可正常使用！

本人另一台win7，使用同样版本，可正常显示。

![image](https://user-images.githubusercontent.com/20366111/109100457-e1deb700-775f-11eb-9ca9-99f5eafe9a24.png)

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
重装2.63版本问题依然存在，设置内核设置里面分站统计也一样不行。
![image](https://user-images.githubusercontent.com/20366111/109100716-5fa2c280-7760-11eb-93aa-df71020a335c.png)

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by MarksonHon** [comment]
@smartnikocj 我们搞不清楚你想表达什么，进群聊吧：
<https://t.me/Qv2ray>
