### ISSUE TITLE
功能请求：增加启动后最小化至托盘功能

### ISSUE THREAD

**Issue by GossipRanR** [Qv2ray/Qv2ray#1312]
由于生活和工作的原因，需要在使用电脑时全程保持翻墙状态。
所以对于代理软件我都会设置成开机启动，并设置启动后自动连接到某一节点。
现在qv2ray启动后都会显示主界面，造成每次开机进入桌面后都要关闭qv2ray的主窗口。
希望能添加这个功能。（之前用v2ray和ss的代理软件都是默认这样设置的。）
我主用macOS，偶尔使用windows，希望两个平台的客户端都支持这个特性。
谢谢！

**Comment by DuckSoft** [comment]
你好，在新版你可以在首选项直接找到这个选项：
![图片](https://user-images.githubusercontent.com/7822648/109116253-317eac00-777b-11eb-89aa-2d73c18bdaed.png)

另外，我们对启动但未设置自动连接的节点的情形，仍然会继续显示主窗口。
