### ISSUE TITLE
macOS 11 Big Sur 菜单栏图标状态显示错误

### ISSUE THREAD

**Issue by GossipRanR** [Qv2ray/Qv2ray#1313]
![image](https://user-images.githubusercontent.com/59172555/109116247-2fb4e880-777b-11eb-840c-2bef219491c8.png)
如图。
今天更新了 macOS 11 Big Sur （11.2.1 (20D75)）发现菜单栏右上角的图标状态不会随着是否连接了节点而改变。现在一直显示了连接到节点的小绿点。
我是从 macOS 10.15 升级上来的，之前未连接节点时没有小绿点

**Comment by DuckSoft** [comment]
感谢反馈。
这是已知问题之一，三个平台的用户都有报告，排查了很长时间，问题始终不明确，好在不影响实际使用。
开发者最近比较忙，可能无暇顾及这块的问题。欢迎有志之士提交补丁。

**Comment by U-v-U** [comment]
Closing, see #551 for future updates.
