### ISSUE TITLE
使用疑问：「 Windows10上的开发，编译，调试的集成开发环境信息 」

### ISSUE THREAD

**Issue by qianbaidugg** [Qv2ray/Qv2ray#1314]
### 你想做啥？
我想要Windows10的开发编译环境搭建信息 

### 你目前试了啥？
*我想在Windows 10，visual studio2019上编译Windows64版本，以此来研究Qv2ray；
已在Windows10上安装visual studio2019和qt5，根据编译错误，猜测大概是qt版本不对，*

### 其他要补充的信息？
想要一份你们在使用的Windows 开发，编译，调试的集成开发环境信息及对应的版本；
谢谢~

**Comment by 2014CAIS01** [comment]
你可能需要参考文档的内容 https://qv2ray.net/hacking/manuallybuild.html。

欢迎加群讨论，https://t.me/Qv2ray

**Comment by qianbaidugg** [comment]
> 你可能需要参考文档的内容 https://qv2ray.net/hacking/manuallybuild.html 。
> 
> 欢迎加群讨论，https://t.me/Qv2ray

非常感谢，我先对着文档研究下。
另，由于网络限制，进群失败了

**Comment by U-v-U** [comment]
@qianbaidugg The doc has been updated 
https://github.com/Qv2ray/qv2ray.github.io/commit/eda4e0d8200a2b30e035609183c5dfdee6243ac2
https://github.com/Qv2ray/qv2ray.github.io/commit/72f741d5285de248bd6e0044b76fdf5f62699e6b
https://github.com/Qv2ray/qv2ray.github.io/commit/24df418d87f18e10b9df76c40a2162404c5b1e12

**Comment by RyoHina** [comment]
```
Microsoft Windows [版本 10.0.19042.844]
(c) 2020 Microsoft Corporation. 保留所有权利。

G:\Qv2ray>mkdir build

G:\Qv2ray>cd build

G:\Qv2ray\build>cmake ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.28.29910.0
-- The CXX compiler identification is MSVC 19.28.29910.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE

Qv2ray Version: 2.6.3
Qv2ray Build Version: 5841
|-------------------------------------------------|
| Qv2ray, A Cross Platform v2ray Qt GUI Client.   |
| Licenced under GPLv3                            |
|                                                 |
| You may only use this program to the extent     |
| permitted by local law.                         |
|                                                 |
| See: https://www.gnu.org/licenses/gpl-3.0.html  |
|-------------------------------------------------|
| Project Homepage: https://github.com/Qv2ray     |
| Welcome to contribute!                          |
|-------------------------------------------------|


```

我在这部卡了1个多小时了， 不知道是为什么？ 我的cpu是Intel(R) Xeon(R) CPU E3-1281 v3 @ 3.70GHz   3.70 GHz

**Comment by qianbaidugg** [comment]
> 
> 我在这部卡了1个多小时了， 不知道是为什么？ 我的cpu是Intel(R) Xeon(R) CPU E3-1281 v3 @ 3.70GHz 3.70 GHz

根据你提供日志看，这个还没开始编译呢。应该是你的第三方依赖库和头文件路径不对，
我之前没搞过cmake，根据 @2014CAIS01 你可能需要参考文档的内容 https://qv2ray.net/hacking/manuallybuild.html 。提供的信息，然后再通过在cmake list中添加日志【message("|-----|" +  CMAKE_CURRENT_LIST_LINE)】，最终已经编译成功了。
你应该需要如下的信息【 grpc-x64-windows.7z解压后】：
 E:\src_code\Qv2ray\libs\x64-windows> ls -r |more
    目录: E:\src_code\Qv2ray\libs\x64-windows
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2021/2/23      9:29                installed
d-----        2021/2/23      9:30                scripts
-a----        2021/2/23      9:30              0 .vcpkg-root
-a----        2021/2/24     14:28        1521012 curl-x64-windows.7z
-a----        2021/2/24     14:30      117488925 grpc-x64-windows.7z
-a----        2021/2/24     14:26        8920752 openssl-x64-windows.7z
-a----        2021/3/12     16:11           1593 README.x64-windows.txt
    目录: E:\src_code\Qv2ray\libs\x64-windows\installed
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2021/2/23      9:29                vcpkg
d-----        2021/2/23      9:30                x64-windows
    目录: E:\src_code\Qv2ray\libs\x64-windows\installed\vcpkg
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2021/2/23      9:30                info
    目录: E:\src_code\Qv2ray\libs\x64-windows\installed\vcpkg\info
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2021/2/23      9:29          18946 abseil_2020-09-23_x64-windows.list
-a----        2021/2/23      9:29           3908 c-ares_1.17.1_x64-windows.list
-a----        2021/2/23      9:30          15986 grpc_1.33.1_x64-windows.list
-a----        2021/2/23      9:30           5177 openssl_1.1.1i_x64-windows.list
-a----        2021/2/23      9:30           8622 protobuf_3.14.0_x64-windows.list
-a----        2021/2/23      9:30            700 re2_2020-10-01_x64-windows.list
-a----        2021/2/23      9:30           1854 upb_2020-08-19_x64-windows.list
-a----        2021/2/23      9:30            642 zlib_1.2.11_x64-windows.list

**Comment by qianbaidugg** [comment]
> @qianbaidugg The doc has been updated
> [Qv2ray/qv2ray.github.io@eda4e0d](https://github.com/Qv2ray/qv2ray.github.io/commit/eda4e0d8200a2b30e035609183c5dfdee6243ac2)
> [Qv2ray/qv2ray.github.io@72f741d](https://github.com/Qv2ray/qv2ray.github.io/commit/72f741d5285de248bd6e0044b76fdf5f62699e6b)
> [Qv2ray/qv2ray.github.io@24df418](https://github.com/Qv2ray/qv2ray.github.io/commit/24df418d87f18e10b9df76c40a2162404c5b1e12)
thanks very much~

**Comment by RyoHina** [comment]
> > 我在这部卡了1个多小时了， 不知道是为什么？ 我的cpu是Intel(R) Xeon(R) CPU E3-1281 v3 @ 3.70GHz 3.70 GHz
> 
> 根据你提供日志看，这个还没开始编译呢。应该是你的第三方依赖库和头文件路径不对，
> 我之前没搞过cmake，根据 @2014CAIS01 “你可能需要参考文档的内容 [https://qv2ray.net/hacking/manuallybuild.html“](https://qv2ray.net/hacking/manuallybuild.html%E2%80%9C) 提供的信息，然后再通过在cmake list中添加日志【message("|-----|" + CMAKE_CURRENT_LIST_LINE)】，最终已经编译成功了。
> 你应该需要如下的信息【 grpc-x64-windows.7z解压后】：
> E:\src_code\Qv2ray\libs\x64-windows> ls -r |more
> 目录: E:\src_code\Qv2ray\libs\x64-windows
> Mode LastWriteTime Length Name
> d----- 2021/2/23 9:29 installed
> d----- 2021/2/23 9:30 scripts
> -a---- 2021/2/23 9:30 0 .vcpkg-root
> -a---- 2021/2/24 14:28 1521012 curl-x64-windows.7z
> -a---- 2021/2/24 14:30 117488925 grpc-x64-windows.7z
> -a---- 2021/2/24 14:26 8920752 openssl-x64-windows.7z
> -a---- 2021/3/12 16:11 1593 README.x64-windows.txt
> 目录: E:\src_code\Qv2ray\libs\x64-windows\installed
> Mode LastWriteTime Length Name
> d----- 2021/2/23 9:29 vcpkg
> d----- 2021/2/23 9:30 x64-windows
> …………………………

使用 dev 分支最后编译成功了， 刚开始用的master分支。
