### ISSUE TITLE
功能请求：希望qv2ray的订阅配置可以直接导入Clash proxy-provider的节点信息

### ISSUE THREAD

**Issue by jacklee789** [Qv2ray/Qv2ray#1317]
免费节点池有上千个节点，需要通过Clash proxy-provider进行筛选。

然后通过边缘转换，才能将节点信息导入v2rayn。

希望qv2ray的订阅配置可以直接导入Clash proxy-provider的节点信息。

winxray已实现这个功能，供参考。

**Comment by DuckSoft** [comment]
抱歉，俺没兴趣做，这个重任就交给你了
