### ISSUE TITLE
更新订阅后，托盘图标会发生改变，变成系统的信息提示图标

### ISSUE THREAD

**Issue by longgangfan** [Qv2ray/Qv2ray#1318]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

更新订阅后，托盘图标会发生改变，变成系统的信息提示图标

## 如何触发这个 Bug：

1. 更新订阅即可触发

### 相关截图或日志

<details>

https://user-images.githubusercontent.com/11954551/109444131-70607a80-7a77-11eb-9b00-d68c72e29713.mp4

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5841
编译信息：Qv2ray for ArchlinuxCN
额外编译信息：(Official Build)5.9.4-arch1-1x86_64
```

### 操作系统

- Linux

### 安装来源

- ArchLinuxCN - 稳定版

### 已安装的插件、版本及安装来源

Qv2ray Command Plugin v2.0.0.linux-x64.so from github

## 附加信息

*请注意打码隐私相关信息。*

**Comment by U-v-U** [comment]
@longgangfan 一个可能的原因是你的 DE 没有正确处理 Desktop Notifications

**Comment by longgangfan** [comment]
> @longgangfan 一个可能的原因是你的 DE 没有正确处理 Desktop Notifications

怎么去排查？我的是xfce4

**Comment by DuckSoft** [comment]
这个显然是你桌面环境的问题，而非我们 Qv2ray 的问题。
目前没有收到其他 Xfce 用户的报告。
