### ISSUE TITLE
功能请求：取消强制本地地址走outBound_DIRECT

### ISSUE THREAD

**Issue by ryanInf** [Qv2ray/Qv2ray#1319]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
需要v2ray代理局域网地址

请尽可能清晰简洁地描述问题。
我需要10.1.1.1 ip通过代理访问，但是不论怎么改都是 [outBound_DIRECT]
2021/03/01 18:26:56 tcp:127.0.0.1:7020 accepted tcp:10.1.1.1:8443 [outBound_DIRECT]
2021/03/01 18:27:07 tcp:127.0.0.1:7040 accepted tcp:10.1.1.1:443 [outBound_DIRECT]
2021/03/01 18:27:07 tcp:127.0.0.1:7041 accepted tcp:10.1.1.1:443 [outBound_DIRECT]

**简单描述你预期的解决方案？**
需要个选项，让v2ray可以代理任意目标地址

**Comment by 2014CAIS01** [comment]
<img width="211" alt="图片" src="https://user-images.githubusercontent.com/22931465/109490931-e2f74780-7ac3-11eb-8944-24cdb898378d.png">
把首选项的绕过私有地址的勾去掉

**Comment by ryanInf** [comment]
> <img alt="图片" width="211" src="https://user-images.githubusercontent.com/22931465/109490931-e2f74780-7ac3-11eb-8944-24cdb898378d.png">
> 
> 把首选项的绕过私有地址的勾去掉

无该选项
版本：
Qv2ray.v2.6.3.Windows-x64.7z
![image](https://user-images.githubusercontent.com/19621374/109497114-86e4f100-7acc-11eb-85a3-35e96a232d7a.png)

**Comment by 2014CAIS01** [comment]
@ryanInf https://github.com/Qv2ray/Qv2ray/releases/tag/v2.7.0-pre2 下载最新版本即可。
