### ISSUE TITLE
網域(10.*.*.*)要如何透過Qv2ray proxy連接

### ISSUE THREAD

**Issue by HowardWhile** [Qv2ray/Qv2ray#1320]
### 你想做啥？
我想連上區網的網頁伺服器(http://10.57.97.197)

### 你目前试了啥？
我發現10開頭的網域都不會經由proxy來連線如下圖所示
![image](https://user-images.githubusercontent.com/18715360/109623488-2612f280-7b78-11eb-99e2-4cb0e16ab5fe.png)

我嘗試在高級路由設定中使用
1. 空白方案
2. v2rayN方案
3. 直接在代理IP欄位輸入`10.57.97.197`
4. 直接在代理IP欄位輸入`10.0.0.0/8`
![image](https://user-images.githubusercontent.com/18715360/109624239-f0bad480-7b78-11eb-81df-e9193ff1ea6e.png)

也是如此

所以想來問問看是否設定上有其他細節要注意

### 其他要补充的信息？
我的作業系統是ubuntu18.04
v2ray版本是https://github.com/v2fly/v2ray-core/releases/tag/v4.34.0 `v2ray-linux-64.zip`
qv2ray版本是https://github.com/Qv2ray/Qv2ray/releases/tag/v2.6.3 `Qv2ray.v2.6.3.linux-x64.AppImage`

**Comment by DuckSoft** [comment]
新版有这样一个选项：
![Uploading 图片.png…]()

去除勾选即可。
