### ISSUE TITLE
Ubuntu20使用问题

### ISSUE THREAD

**Issue by ymmz** [Qv2ray/Qv2ray#1321]
我使用的是Ubuntu官方最新的开源系统。
我按照流程，下载，赋予允许权限，设置核心位置，添加订阅，开启系统代理。
可以正常测试节点，链接节点后延迟也很低，但是firefox仍然无法链接google。
在Qv2ray界面可以看到正常连接。
但是ifirefox似乎无法使用，无法访问外网。

**Comment by DuckSoft** [comment]
日志有吗？试试这个？

```bash
curl -x http://127.0.0.1:8889 -sSLv https://www.google.com/
```

**Comment by ymmz** [comment]
> 日志有吗？试试这个？
> 
> ```shell
> curl -x http://127.0.0.1:8889 -sSLv https://www.google.com/
>

**Comment by ymmz** [comment]
> 日志有吗？试试这个？
> 
> ```shell
> curl -x http://127.0.0.1:8889 -sSLv https://www.google.com/
> ```

谢谢帮忙。我重新下载了最新的pre版本后，重启电脑，现在已经可以正常访问外网了
