### ISSUE TITLE
[Bug?] 局域网代理出现服务器到客户端流量激增

### ISSUE THREAD

**Issue by 517030910405** [Qv2ray/Qv2ray#1322]
- [Y] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
（有可能不是 Qv2ray 而是 v2ray 的问题，但是不清楚是哪里的问题）
服务器为设备A，计算机客户端设备B，手机为设备C。
AB 之间通过 VMess + TLS 连接，C 使用局域网内 http 代理和B连接。
A 向 B 发送数据速率过快，B 向 C 发送数据较慢，导致 A 向 B 发送数据总量比需要传输的大很多，AB间 100Mbps 跑满，BC 间
8Mbps。浪费了很多流量。
发现计算机收到带宽大于发送带宽，并且收到累计流量也远远大于发送累计流量。
![image](https://user-images.githubusercontent.com/42196261/109701394-e971e600-7bcd-11eb-8baa-e21dbf24d2e5.png)

**_猜测疑似是计算机端收到过多的服务器发来的数据，在发给手机前被丢弃了。在本情景中，内网反而是带宽瓶颈。_**

## 如何触发这个 Bug：

1. 局域网 http 代理
2. 用苹果手机 safari 打开 YouTube 视频
3. 发现计算机收到带宽大于发送带宽，并且收到累计流量也远远大于发送累计流量
![image](https://user-images.githubusercontent.com/42196261/109701394-e971e600-7bcd-11eb-8baa-e21dbf24d2e5.png)

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

这个不知道

### 相关截图或日志

![image](https://user-images.githubusercontent.com/42196261/109701394-e971e600-7bcd-11eb-8baa-e21dbf24d2e5.png)
日志正常没有出现问题

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.ubuntu-16.04
```

### 操作系统

- Linux 
```bash
~ $ uname -a
Linux Lenovo 4.15.0-136-generic #140~16.04.1-Ubuntu SMP Wed Nov 11 11:11:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### 安装来源
- Github Release

### 已安装的插件、版本及安装来源
- v2ray-core 4.34.0

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
在写了这么多之前，你需要明确一个事实：Qv2ray 本体没有任何代理能力，**一切代理能力均由 V2Ray 内核及内核插件（如 SSR、Trojan 等）完成**，因而对于代理功能上的疑问，还请您移步上游询问。
