### ISSUE TITLE
使用疑问：「 版本2.6.3.5840 ubuntu 20.04 非root用户无法设置核心文件 」

### ISSUE THREAD

**Issue by soundghost** [Qv2ray/Qv2ray#1324]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

### 你想做啥？
*简要描述你的最原始的目的。*

系统是ubuntu 20.04，qv2ray版本为2.6.3.5840

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
分别尝试了ubuntu商店的版本，release页面的AppImage和deb版本，均出现“当前用户没有v2ray核心控制文件的可执行权限。qv2ray尝试设置，但由于权限不足，操作已失败。”

### 其他要补充的信息？
我的登陆用户为"abc"，检查了路径的权限和用户组的，均属于"abc",即使将所有权限改为777也是同样的错误。

**Comment by soundghost** [comment]
补充一下，切换到root用户也是这样的错误

**Comment by DuckSoft** [comment]
全新安装 Ubuntu 20.04，2.6.3 / 2.7.0-pre2 的 deb / Snapcraft 全部试过，未能复现。
也许你需要进群聊聊 https://t.me/qv2ray。
