### ISSUE TITLE
macos版本中如何设置Xray-VLESS+TCP+XTLS？

### ISSUE THREAD

**Issue by qingbol** [Qv2ray/Qv2ray#1325]
### 你想做啥？
在服务端参考: https://v2raytech.com/xray-one-click-script/ 
使用xray一键脚本。安装Xray-VLESS+TCP+XTLS 

在macbook中使用Qv2ray V2.7.0-pre2作为客户端。 我按照windows版本的教程设置了Qv2ray。但是依然无法联网。

![image](https://user-images.githubusercontent.com/45025489/109816463-b8e08980-7c6b-11eb-85b6-6dec4fdaf335.png)

{
    "outbounds": [
        {
            "_QV2RAY_USE_GLOBAL_FORWARD_PROXY_": false,
            "mux": {
                "concurrency": 1,
                "enabled": null
            },
            "protocol": "vless",
            "sendThrough": "0.0.0.0",
            "settings": {
                "vnext": [
                    {
                        "address": "35.233.14x.xxx",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "flow": "xtls-rprx-direct",
                                "id": "cb11703a-dfb8-4d2e-9410-51c4f1c*****"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "security": "xtls",
                "sockopt": {
                    "mark": 0
                },
                **"tcpSettings"**: {
                    "header": {
                        "request": {
                            "headers": {
                            },
                            "path": [
                            ]
                        },
                        "response": {
                            "headers": {
                            }
                        },
                        **"type": "none"**
                    }
                },
                "**xtlsSettings**": {
                    "alpn": [
                    ]
                }
            },
            "tag": "gcp_xray_orgeon"
        }
    ]
}

错误信息如下：
tcpsetting中type为none时
V2Ray 4.31.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 darwin/amd64)
A unified platform for anti-censorship.
2021/03/04 16:33:00 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
v2ctl> Read config:  /Users/tarus/Library/Preferences/qv2ray/generated/config.gen.json
2021/03/04 16:33:00 [Warning] v2ray.com/core: V2Ray 4.31.0 started
2021/03/04 16:33:01 127.0.0.1:55915 accepted tcp:127.0.0.1:0 [QV2RAY_API]
2021/03/04 16:33:07 127.0.0.1:55919 accepted //p45-caldav.icloud.com:443 [gcp_xray_orgeon]
2021/03/04 16:33:07 127.0.0.1:55921 accepted //p45-caldav.icloud.com:443 [gcp_xray_orgeon]
2021/03/04 16:33:07 [Warning] [2045276278] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic 
    > v2ray.com/core/proxy/vless/outbound: connection ends 
    > v2ray.com/core/proxy/vless/outbound: **failed to decode response header** 
    > v2ray.com/core/proxy/vless/encoding: **failed to read response version > tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config**

tcpsetting中type为http时
V2Ray 4.31.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 darwin/amd64)
A unified platform for anti-censorship.
2021/03/04 16:26:34 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
v2ctl> Read config:  /Users/tarus/Library/Preferences/qv2ray/generated/config.gen.json
2021/03/04 16:26:34 [Warning] v2ray.com/core: V2Ray 4.31.0 started
2021/03/04 16:26:34 127.0.0.1:55648 accepted tcp:127.0.0.1:0 [QV2RAY_API]
2021/03/04 16:26:41 127.0.0.1:55649 accepted //p45-caldav.icloud.com:443 [gcp_xray_orgeon]
2021/03/04 16:26:42 [Warning] [1569915889] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic 
    > v2ray.com/core/proxy/vless/outbound: **failed to use xtls-rprx-direct, maybe "security" is not "xtls"**

### 你目前试了啥？
我在iphone中使用shadowrocket客户端，成功了实现了扶墙。所以服务器的设置是正确的。
懂macos中如何设置的大佬帮我下，谢谢

**Comment by 2014CAIS01** [comment]
https://qv2ray.net/ 请读文档

**Comment by qingbol** [comment]
已解决

**Comment by Conankids** [comment]
> 已解决

你是怎么解决的，我也遇到了同样的问题😅

**Comment by Conankids** [comment]
> 已解决

@qingbol 你是怎么解决的，我也遇到了同样的问题😅
