### ISSUE TITLE
功能请求：能否将“测试真实延迟”功能从仅限测试当前已连接节点开放为可多选多个节点同时测试

### ISSUE THREAD

**Issue by xuerui911** [Qv2ray/Qv2ray#1326]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

使用机场，所有节点均是从国内某个节点中转（假设IP 6.6.6.6为国内的中转机），
6.6.6.6:30000对应香港节点，
6.6.6.6:30001对应日本节点，
6.6.6.6:30002对应美国节点，
6.6.6.6:30003对应英国节点，
6.6.6.6:30004对应澳洲节点，
实际使用上，香港日本节点的延迟应该在几十毫秒，美国100+，欧洲澳洲200+，
而不使用测试真实连接的话，这些节点的延迟都应该是一样的，都是国内这个节点个位数毫秒的延迟，无法正确排序。

我同时买了5个机场，300+个节点。某机场实际得有一半节点是维护中，机场的用户管理面板显示这些节点是灰色维护中，连不上但是能ping通，不测试真实连接的话，那些连不上但是能ping通的节点延迟还不高总是能排前面，自己从前往后连，打开网页一个一个试，试到能打开油管为止。而同时有些节点又是禁ping的，但实际是能连上的，这些节点我一看ping不通又不会去连接它打开网页测试。
假如多选多个节点同时测试真连接延迟的话，那些连不上但是能ping通的节点就会被直接排除，那些禁ping但是实际能用的节点又会被留下，这样的话根据延迟排序前几个就一定是最好的节点。

**简单描述你预期的解决方案？**

取消“测试真实延迟”功能仅限测试当前已连接节点的限制，开放为可多选多个节点同时测试

**你有想到其他比较容易实现的解决方案吗？**

暂无

**补充内容**
我之前在 #1257 提过，UvU说不会考虑这个但是欢迎PR，我本身学了点儿JAVA和Scala干大数据分析的，大部分时间写SQL，写代码也是打包Jar包传到服务器上Linux黑窗口跑，C++和图形界面开发实在无能为力。我猜欢迎PR肯定主要是测试下载速度功能，因为测试真实连接这个功能本身你们已经实现完了，只是加了限制仅限当前已连接节点，能否取消这个限制，允许多选多个节点同时测试

**Comment by 12101111** [comment]
如果你懂一些网络知识你就知道为什么这不是一个“限制”， 因为ping就是给节点的IP发一个ICMP报文，是不需要实际建立链接的，而测试真实延迟则必须先连接上节点，然后再测试访问其他网站的延迟。所以不可能在没有连接到节点的情况下测试真实延迟的。

**Comment by xuerui911** [comment]
> 如果你懂一些网络知识你就知道为什么这不是一个“限制”， 因为ping就是给节点的IP发一个ICMP报文，是不需要实际建立链接的，而测试真实延迟则必须先连接上节点，然后再测试访问其他网站的延迟。所以不可能在没有连接到节点的情况下测试真实延迟的。

我指的是自己手动操作的啊，QV软件本身可以在测速时候去连接一下节点，在我手动选择节点之前告诉我哪个节点能打开油管并且延迟最低就行，V2RayN和Winxray有类似的功能，应该借鉴一下优点。

**Comment by DuckSoft** [comment]
一句话：太菜了，不会写，谁会谁来。
这不是一个“解除限制”能完成的事情，这需要把需要测试的节点的出站生成到一个配置文件中，然后进行逐端口的测试。

**Comment by xuerui911** [comment]
> 一句话：太菜了，不会写，谁会谁来。
> 这不是一个“解除限制”能完成的事情，这需要把需要测试的节点的出站生成到一个配置文件中，然后进行逐端口的测试。

大佬，我丝毫没有说你们菜的意思，而且你们自己写完代码直接开源，免费共享出来，这都是相当高尚的行为了。

我个人电脑系统直接从Windows换成ArchLinux+KDE了，Linux用不了V2RayN和WinXray，我只能用QV2ray，所以我才会对QV2ray多说两句，对QV2Ray的发展健壮很关心，如果有捐助渠道我也愿意捐助几百。

V2RayN能多选测真实延迟，WinXray不用自己手动去测可以自动测自动切换节点，V2RayN是用C#写的，WinXray是用比较冷门的aardio写的，反正V2RayN和WinXray也都是开源的，如果恰巧有人也会C#或者aardio，也会C++和QT，看到了我这个建议，就去看看这两个软件的源码，看看逻辑是怎么实现的，抄一下，回来用C++和QT实现一下，然后发个pull request，这是事半功倍的事。

我只是提建议，丝毫没有道德绑架。

最后，再次感谢大佬们。
