### ISSUE TITLE
使用疑问：「  如何在ubuntu下安装该软件」

### ISSUE THREAD

**Issue by godlovehill** [Qv2ray/Qv2ray#1327]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

`QV_ISSUE_QUESTION_TEMPLATE_PLACEHOLDER`

### 你想做啥？
*简要描述你的最原始的目的。*

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by Nozom124** [comment]
编辑高级路由设置，具体看文档 https://qv2ray.net/manual/route.html#%E5%85%A8%E5%B1%80%E8%B7%AF%E7%94%B1%E8%A7%84%E5%88%99
