### ISSUE TITLE
macos 内核设置错误

### ISSUE THREAD

**Issue by lonelyfish** [Qv2ray/Qv2ray#1328]
core executable file /usr/local/bin/v2ray is too short to be executed

version: 2.7.0-pre1:6039

**Comment by DuckSoft** [comment]
`du -h /usr/local/bin/v2ray`

**Comment by 2014CAIS01** [comment]
May be introduced by https://github.com/Homebrew/homebrew-core/pull/72476

**Comment by NickCao** [comment]
You can set core to /usr/local/Cellar/v2ray/<version>/libexec/v2ray as a temporary workaroud.

**Comment by kidonng** [comment]
使用 Qv2ray 2.7.0-pre2 之前版本的 macOS 用户，使用 Homebrew 升级 v2ray 到 4.34.0_1 之后，请指定核心位置为 /usr/local/opt/v2ray/libexec/v2ray
