### ISSUE TITLE
mac big sur打不开软件

### ISSUE THREAD

**Issue by lijingchun0** [Qv2ray/Qv2ray#1333]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
最近稳定版和最新预览版在big sur 11.2.1 中打不开，在启动栏跳了几下就没反应了 

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

## 系统信息
![image](https://user-images.githubusercontent.com/26979634/110095137-8c498080-7dd7-11eb-9d00-e8adc44865eb.png)

### 打开首选项 -> 关于，填写以下信息

```
版本: 
编译信息：
额外编译信息：
```

### 操作系统

- macOS

### 安装来源

- Github Release

## 附加信息

*请注意打码隐私相关信息。*

**Comment by 2014CAIS01** [comment]
https://github.com/Qv2ray/Qv2ray/issues/1263

BTW，我与你列举的环境一致，无法复现你所述的问题，请仔细阅读文档。

**Comment by DuckSoft** [comment]
重启

**Comment by librenix** [comment]
运行
```
/Applications/qv2ray.app/Contents/MacOS/qv2ray
```
查看输出。
