### ISSUE TITLE
添加ss加密选项none

### ISSUE THREAD

**Issue by l3617** [Qv2ray/Qv2ray#1337]
安装shadowsocks-rust＋gost-plugin或者xray-plugin时，可以选择none不加密＋ws＋tls协议（一些配置低的小鸡速度真的提升好多），但是shadowsocks-windows客户端不支持不加密协议，我跟他们反应过了，但是还在商讨没下落。。所以我想是不是这边可以添加这个功能，当然只是建议而已，如果不采用就算了

**Comment by dyhkwong** [comment]
core 是支持的

**Comment by U-v-U** [comment]
We explicitly discourage this value since it's not secure. I think the encryption overhead of shadowsocks would not be more than that of TLS.
