### ISSUE TITLE
Feature Request: <Kill Switch for unexpected IP leaks>

### ISSUE THREAD

**Issue by avangardistic** [Qv2ray/Qv2ray#1338]
kill the internet connection when there is an interruption between client and server to avoid unexpected IP leaks

(internet kill switch)[![image](https://user-images.githubusercontent.com/13473492/110211203-62529580-7e8d-11eb-8d54-1082101126c2.png)]

**Comment by MarksonHon** [comment]
@avangardistic Qv2ray IS NOT an VPN software, this feature cannon add to Qv2ray at the  moment.
