### ISSUE TITLE
插件对话框按钮-插件文件夹指向问题

### ISSUE THREAD

**Issue by NinjaUmbra** [Qv2ray/Qv2ray#1339]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
单击打开本地插件目录 弹出 \deployment\config\plugins 文件夹
而不是正确的  \deployment\plugins

## 如何触发这个 Bug：

正常使用

## 系统信息

```
版本: 2.7.0-pre2:6150
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-4cc95cb2f686250c899a04969e1a220af449908d-ci.windows-latest
```

### 操作系统

- Windows 10

### 安装来源

- Github Release

### 已安装的插件、版本及安装来源
Builtin Protocol Support
Builtin Subscription Support
SSR Plugin

## 附加信息

绿色版bug 安装最新构建的安装版正常

**Comment by U-v-U** [comment]
@NinjaUmbra This is expected behavior where users should and should only place their plugins under configuration path, other places are used by the package managers.
