### ISSUE TITLE
使用疑问：「macOS无法设置v2ray kernel  」

### ISSUE THREAD

**Issue by SleepyLogan** [Qv2ray/Qv2ray#1340]
### Issue
升级v2ray至4.35.1后，qv2ray客户端无法完成kernel setting

### I've tried
1. 升级v2ray后，修改kernel setting中的core executable path至4.35.1/bin/v2ray，设置失败，提示“too short to execute...”
2. 修改core executable path至4.35.1/libexec/v2ray，设置失败，提示“core control file is lacking executable permission...”

### Info
macOS Big Sur 11.2.2, v2ray 4.35.1 installed by homebrew, Qv2ray app 2.6.3:5840

### Update
2.7.0-pre1:6039 seems work

**Comment by SleepyLogan** [comment]
<img width="907" alt="qv2ray-bin" src="https://user-images.githubusercontent.com/3294882/110268980-a1075d80-7ffd-11eb-815a-136f2f524570.png">
<img width="905" alt="qv2ray-libexec" src="https://user-images.githubusercontent.com/3294882/110268983-a2d12100-7ffd-11eb-9e32-c4c6ae9db8e2.png">

**Comment by 2014CAIS01** [comment]
https://github.com/Qv2ray/Qv2ray/issues/1328

**Comment by DuckSoft** [comment]
Homebrew 打包有问题，你可以：
1. 换核心路径到 `/usr/local/opt/v2ray/libexec/v2ray`
2. 或者：升级到 Qv2ray v2.7.0-pre2

**Comment by Eason0210** [comment]
@DuckSoft 我设置了核心路径 `/usr/local/opt/v2ray/libexec/v2ray`

但是提示下面这个错误，请问下要怎么操作？
![image](https://user-images.githubusercontent.com/47546452/111037558-8f8bde80-845f-11eb-84d4-214862d04978.png)

**Comment by DuckSoft** [comment]
看起来你正在使用旧版的 Qv2ray。请考虑升级到 Qv2ray 2.7.0-pre2。

**Comment by Eason0210** [comment]
👍升级到最新版已经解决，多谢。
