### ISSUE TITLE
使用疑问： 一启动连接就提示： “V2ray core settings is incorrect.The error is :V2ray core executable not found”

### ISSUE THREAD

**Issue by sunrainxyz** [Qv2ray/Qv2ray#1341]
无论下载的Qv2ray.v2.7.0-pre1.Windows-x64，还是Qv2ray.v2.6.3.Windows-x64 都是这样
－－－－－－－－－－－
已经搞定了，看了详细教程，把v2ray解压到/config/vcore目录了

**Comment by 2014CAIS01** [comment]
@sunrainxyz 配置 V2Ray 核心
