### ISSUE TITLE
Shadowsocks 加密方式自动切换。

### ISSUE THREAD

**Issue by Arctic-Xiangjian** [Qv2ray/Qv2ray#1342]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 如何触发这个 Bug：

1. 新建连接方式，类型Shadowsocks；
2. 加密方式选择除chacha20-ietf-poly1305以外的；
3. 随后发现无法连接，重新点开编辑发现加密方式自动变为chacha20-ietf-poly1305；
4. 再次手动编辑后问题解决。

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.7.0-pre2:6150
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-4cc95cb2f686250c899a04969e1a220af449908d-ci.windows-latest
```

### 操作系统

- Windows

### 安装来源

- Github Release 

## 附加信息

*请注意打码隐私相关信息。*

**Comment by U-v-U** [comment]
Tested using `aes-256-gcm` `aes-128-gcm` and `chacha20-ietf-poly1305`
Cannot reproduce.

**Comment by dyhkwong** [comment]
已经修了 https://github.com/Qv2ray/Qv2ray/pull/1286
