### ISSUE TITLE
功能请求：自定义绕过规则

### ISSUE THREAD

**Issue by wittyneko** [Qv2ray/Qv2ray#1347]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

希望加入自定义绕过规则。
另外【连接设置】里的绕过中国大陆的优先级太低了，比如在【高级路由设置】如果配置了代理`geosite:cn`和绕过规则重复，绕过就失效了。

**简单描述你预期的解决方案？**

比如代理配置 `geosite:apple`但是这时候又要`icloud`不走代理，能够自定义绕过规则并且绕过规则优先于高级路由设置就很好解决。

**你有想到其他比较容易实现的解决方案吗？**

连接设置或高级路由设置提供自定义绕过规则

**补充内容**
无

**Comment by NICOLE1224** [comment]
纯路人，你可以去qv2ray.org搜索一番。

**Comment by dyhkwong** [comment]
duplicate, closed.
