### ISSUE TITLE
q2v2ray + xray core subscription

### ISSUE THREAD

**Issue by ortonomy** [Qv2ray/Qv2ray#1351]
### Describe You Purpose

Trying to use xray core type vless servers with q2vray

### Describe What Have You Tried

1. download `xray-core` release using homebrew: (https://github.com/N4FA/homebrew-xray)

`brew tap N4FA/xray`
`brew install xray-core`

2. set v2ray kernel in q2v2ray

![image](https://user-images.githubusercontent.com/6688676/110887611-957da480-8325-11eb-8e32-0cda4c728f0f.png)

3. error
![image](https://user-images.githubusercontent.com/6688676/110887631-9d3d4900-8325-11eb-8854-c0896bcbb325.png)

### Any Other Thing

q2v2ray version: `2.6.3:5840`

**Comment by ortonomy** [comment]
FYI: xray core only has one executable : `xray-core` no `xray-core-ctl` like `v2ray-ctl`

**Comment by ortonomy** [comment]
Ok, it's working. Just make sure you use the pre-release release: https://github.com/Qv2ray/Qv2ray/releases/tag/v2.7.0-pre2

**Comment by U-v-U** [comment]
Yes, the prerelease version skips checks for the `ctl` executable.
