### ISSUE TITLE
使用疑问：「 Windows 没有通知提醒了？可能是Windows更新所致？ 」

### ISSUE THREAD

**Issue by tasty0tomato** [Qv2ray/Qv2ray#1352]
### 你想做啥？
*简要描述你的最原始的目的。*

在以往（不确定具体哪天前）的使用中，每次启用系统代理（或者禁用系统代理）都会有Windows的消息提醒，但现在没有了。也由于现在没有了，没法截图应该出现的场面。

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

1. 阅读了文档，似乎没有相关介绍。
2. 阅读了软件设置，似乎没有相关介绍。
3. 查看了Windows设置，似乎没有_Qv2ray_（这是反常的）。
4. 查看了已存在的issue，似乎没有与我相似的问题。
5. 重新安装了（在卸载后也删除了配置文件夹）_Qv2ray_，问题并没有解决。
### 其他要补充的信息？
*在此附加其他需要补充的信息。*
Windows相应的设置的截图
![2021-03-12 12_33_49-Microsoft Store](https://user-images.githubusercontent.com/48764449/110892570-43418100-832f-11eb-874f-e594256a191f.png)
并没有截完，不过大致上就是根本没有_Qv2ray_，所以也不存在我关闭了_Qv2ray_的通知的可能性。

**Comment by U-v-U** [comment]
![image](https://user-images.githubusercontent.com/59914293/110892850-c531aa00-832f-11eb-8d09-ab5fb2abd1cc.png)

检查一下首选项右侧的 “Quiet Mode”

**Comment by tasty0tomato** [comment]
> ![image](https://user-images.githubusercontent.com/59914293/110892850-c531aa00-832f-11eb-8d09-ab5fb2abd1cc.png)
> 
> 检查一下首选项右侧的 “Quiet Mode”

这可能是一个bug？我确认初始状态是未选择的，但是在我选上了后又取消选择后，这个问题就解决了……如果这不是一个bug，应该就可以close了。
