### ISSUE TITLE
使用疑问：「 建议说明已经可以使用相对路径 」

### ISSUE THREAD

**Issue by TsXor** [Qv2ray/Qv2ray#1355]
### 你想做啥？
*简要描述你的最原始的目的。*
希望文档说明已经可以使用相对路径设置核心路径

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
Qv2ray目录：D:\Qv2ray
1.V2Ray核心目录：D:\Qv2ray\v2ray-core
设置资源目录：./v2ray-core，设置核心可执行文件路径：./v2ray-core/v2ray.exe
结果：配置检查通过
2.NaiveProxy核心目录：D:\Qv2ray\core4plugins\naiveproxy-core
设置Kernel Path：./core4plugins/naiveproxy-core/naive.exe
结果：Test Run可以检测到
3.Trojan-go核心目录：D:\Qv2ray\core4plugins\trojan-go-core
设置Kernel Path：./core4plugins/trojan-go-core/trojan-go.exe
结果：无测试按钮

事实证明，各类核心的路径均可设置为相对于qv2ray.exe的路径

### 其他要补充的信息？
*在此附加其他需要补充的信息。*
#1264

**Comment by DuckSoft** [comment]
欢迎完善文档：https://github.com/qv2ray/qv2ray.github.io
