### ISSUE TITLE
功能请求：适配小荧幕设备

### ISSUE THREAD

**Issue by happyeggchen** [Qv2ray/Qv2ray#1356]
对于rpi3.5寸的屏幕，qv2ray的窗口不能能好的适应它，请求让窗口可调节最小大小

**Comment by DuckSoft** [comment]
确实 3.5 寸的屏幕太小了，没法正确显示。
目前我们没有适配这个的打算。如果你有能力，可以帮我们发 Pull Request（或者自己 Fork 出来一个）。我们非常欢迎。
