### ISSUE TITLE
连接服务器后无法访问google PR_END_OF_FILE_ERROR

### ISSUE THREAD

**Issue by zhouguannan** [Qv2ray/Qv2ray#1358]
# 以下是日志
V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/amd64)
A unified platform for anti-censorship.
2021/03/14 21:07:51 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /home/kevin/.config/qv2ray/generated/config.gen.json
2021/03/14 21:07:51 [Warning] v2ray.com/core: V2Ray 4.27.0 started
2021/03/14 21:07:52 127.0.0.1:49544 accepted tcp:127.0.0.1:0 [_QV2RAY_API_]
2021/03/14 21:08:03 127.0.0.1:36480 accepted http://detectportal.firefox.com/success.txt [outBound_PROXY]
2021/03/14 21:08:03 127.0.0.1:36484 accepted //content-signature-2.cdn.mozilla.net:443 [outBound_PROXY]
2021/03/14 21:08:03 127.0.0.1:36488 accepted //firefox.settings.services.mozilla.com:443 [outBound_PROXY]
2021/03/14 21:08:03 tcp:127.0.0.1:53078 accepted tcp:35.161.219.80:443 [outBound_PROXY]
2021/03/14 21:08:03 127.0.0.1:36494 accepted //firefox.settings.services.mozilla.com:443 [outBound_PROXY]
2021/03/14 21:08:05 [Warning] [1603736812] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:05 127.0.0.1:36502 accepted //firefox.settings.services.mozilla.com:443 [outBound_PROXY]
2021/03/14 21:08:05 [Warning] [184002028] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:05 [Warning] [52629831] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:05 127.0.0.1:36506 accepted //firefox.settings.services.mozilla.com:443 [outBound_PROXY]
2021/03/14 21:08:05 [Warning] [874701443] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:05 [Warning] [874701443] v2ray.com/core/proxy/http: failed to read response from detectportal.firefox.com > io: read/write on closed pipe
2021/03/14 21:08:05 127.0.0.1:36512 accepted http://detectportal.firefox.com/success.txt [outBound_PROXY]
2021/03/14 21:08:06 [Warning] [3107777938] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:06 127.0.0.1:36516 accepted //snippets.cdn.mozilla.net:443 [outBound_PROXY]
2021/03/14 21:08:07 [Warning] [1190763943] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:07 [Warning] [1190763943] v2ray.com/core/proxy/http: failed to read response from detectportal.firefox.com > io: read/write on closed pipe
2021/03/14 21:08:07 127.0.0.1:36520 accepted http://detectportal.firefox.com/success.txt [outBound_PROXY]
2021/03/14 21:08:07 127.0.0.1:36524 accepted //www.google.com:443 [outBound_PROXY]
2021/03/14 21:08:08 127.0.0.1:36530 accepted //www.google.com:443 [outBound_PROXY]
2021/03/14 21:08:08 [Warning] [211414364] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:08 127.0.0.1:36534 accepted //firefox.settings.services.mozilla.com:443 [outBound_PROXY]
2021/03/14 21:08:08 [Warning] [1750445589] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:08 127.0.0.1:36538 accepted //snippets.cdn.mozilla.net:443 [outBound_PROXY]
2021/03/14 21:08:08 [Warning] [2267119328] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:08 [Warning] [2267119328] v2ray.com/core/proxy/http: failed to read response from detectportal.firefox.com > io: read/write on closed pipe
2021/03/14 21:08:08 127.0.0.1:36542 accepted http://detectportal.firefox.com/success.txt [outBound_PROXY]
2021/03/14 21:08:09 [Warning] [3107840127] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:09 [Warning] [2970693818] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:09 127.0.0.1:36548 accepted //incoming.telemetry.mozilla.org:443 [outBound_PROXY]
2021/03/14 21:08:09 [Warning] [3594940320] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:09 127.0.0.1:36552 accepted //incoming.telemetry.mozilla.org:443 [outBound_PROXY]
2021/03/14 21:08:09 127.0.0.1:36560 accepted //incoming.telemetry.mozilla.org:443 [outBound_PROXY] 
2021/03/14 21:08:09 127.0.0.1:36558 accepted //incoming.telemetry.mozilla.org:443 [outBound_PROXY] 
2021/03/14 21:08:09 127.0.0.1:36554 accepted //incoming.telemetry.mozilla.org:443 [outBound_PROXY] 
2021/03/14 21:08:09 127.0.0.1:36556 accepted //incoming.telemetry.mozilla.org:443 [outBound_PROXY]
2021/03/14 21:08:10 [Warning] [1113198539] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:10 127.0.0.1:36572 accepted //firefox.settings.services.mozilla.com:443 [outBound_PROXY]
2021/03/14 21:08:10 [Warning] [1622937874] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:10 [Warning] [1622937874] v2ray.com/core/proxy/http: failed to read response from detectportal.firefox.com > io: read/write on closed pipe
2021/03/14 21:08:10 127.0.0.1:36576 accepted http://detectportal.firefox.com/success.txt [outBound_PROXY]
2021/03/14 21:08:10 tcp:127.0.0.1:53166 accepted tcp:35.161.219.80:443 [outBound_PROXY]
2021/03/14 21:08:11 [Warning] [3115631888] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:11 [Warning] [64871032] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:11 [Warning] [668961826] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:11 [Warning] [3168816815] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:11 [Warning] [3004519547] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:11 [Warning] [611673374] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:11 [Warning] [1033815486] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:11 127.0.0.1:36586 accepted //incoming.telemetry.mozilla.org:443 [outBound_PROXY]
2021/03/14 21:08:11 [Warning] [1417347889] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:11 [Warning] [1417347889] v2ray.com/core/proxy/http: failed to read response from detectportal.firefox.com > io: read/write on closed pipe
2021/03/14 21:08:11 127.0.0.1:36590 accepted http://detectportal.firefox.com/success.txt [outBound_PROXY]
2021/03/14 21:08:11 [Warning] [807027645] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:13 [Warning] [2635631769] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:13 [Warning] [2635631769] v2ray.com/core/proxy/http: failed to read response from detectportal.firefox.com > io: read/write on closed pipe
2021/03/14 21:08:14 [Warning] [3408546940] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:21 tcp:127.0.0.1:53192 accepted tcp:35.161.219.80:443 [outBound_PROXY]
2021/03/14 21:08:23 [Warning] [6677596] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:08:43 tcp:127.0.0.1:53226 accepted tcp:54.148.233.111:443 [outBound_PROXY]
2021/03/14 21:08:44 [Warning] [994969006] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:09:03 127.0.0.1:36692 accepted http://detectportal.firefox.com/success.txt [outBound_PROXY]
2021/03/14 21:09:04 [Warning] [2724134707] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:09:04 [Warning] [2724134707] v2ray.com/core/proxy/http: failed to read response from detectportal.firefox.com > io: read/write on closed pipe
2021/03/14 21:09:04 127.0.0.1:36698 accepted http://detectportal.firefox.com/success.txt [outBound_PROXY]
2021/03/14 21:09:05 [Warning] [3988271781] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:09:05 [Warning] [3988271781] v2ray.com/core/proxy/http: failed to read response from detectportal.firefox.com > io: read/write on closed pipe
2021/03/14 21:09:05 127.0.0.1:36702 accepted http://detectportal.firefox.com/success.txt [outBound_PROXY]
2021/03/14 21:09:06 [Warning] [1671978520] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:09:06 [Warning] [1671978520] v2ray.com/core/proxy/http: failed to read response from detectportal.firefox.com > io: read/write on closed pipe
2021/03/14 21:09:06 127.0.0.1:36708 accepted http://detectportal.firefox.com/success.txt [outBound_PROXY]
2021/03/14 21:09:07 [Warning] [2157970933] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:09:07 [Warning] [2157970933] v2ray.com/core/proxy/http: failed to read response from detectportal.firefox.com > io: read/write on closed pipe
2021/03/14 21:09:07 127.0.0.1:36712 accepted http://detectportal.firefox.com/success.txt [outBound_PROXY]
2021/03/14 21:09:09 [Warning] [2886637028] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:09:09 [Warning] [2886637028] v2ray.com/core/proxy/http: failed to read response from detectportal.firefox.com > io: read/write on closed pipe
2021/03/14 21:09:09 127.0.0.1:36718 accepted http://detectportal.firefox.com/success.txt [outBound_PROXY]
2021/03/14 21:09:10 [Warning] [3949812066] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2021/03/14 21:09:10 [Warning] [3949812066] v2ray.com/core/proxy/http: failed to read response from detectportal.firefox.com > io: read/write on closed pipe

**Comment by DuckSoft** [comment]
在 WebSocket 传输模式下，`websocket: close 1000 (normal)` 一般是内层协议身份认证失败的时候才会抛出的错误。
大概有这样几种情形：
1. 使用的凭据被服务器拒绝。例如，你号被服务器删了，或者UUID不对；
2. （VMess 常见）本地时间与远程服务器时间相差过大；
3. AlterID 设置错误（或 VMessAEAD / VMess 旧版不匹配）

无论何种情形，代理功能均由 V2Ray 核心提供，与 Qv2ray 本体并无关系。
如有疑问，建议 https://github.com/v2fly/v2ray-core/issues 见。
