### ISSUE TITLE
2.7.0速度图像不显示

### ISSUE THREAD

**Issue by GloryBoy239** [Qv2ray/Qv2ray#1360]
- **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
针对 Qv2ray Preview 版本的累积更新这个版本，速度图像不显示！

## 如何触发这个 Bug：
1. 更新后，这个版本就不显示速度图像
2. 卸载重装后，也不显示速度图像
3. 重新安装Qv2ray v2.6.3，也不显示了速度图像（原来是显示的）
4. Tr，V2都是这样

### 相关截图或日志
![QQ截图20210316163740](https://user-images.githubusercontent.com/68975045/111280360-b1ab7980-8676-11eb-9106-6a75b6182735.png)

## 系统信息
版本: 2.7.0-pre2:6150
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-4cc95cb2f686250c899a04969e1a220af449908d-ci.windows-latest

### 操作系统

windows 10

### 安装来源
- Github Release

**Comment by xyzhou-1** [comment]
我也遇到了相似的问题,开发者帮我解决了，我来传个火，你看能不能解决。
先确定一下是不是同样的问题，你看一下qv2ray的配置文件，windows好像是`~/Appdata/local/q2ray`,打开`Qv2ray.conf`，查看`    "uiConfig": {
        "graphConfig": {
            "colorConfig": {` 下面的值，大概是是这样，`$2`前面还有一个 `$0,$1`。
![image](https://user-images.githubusercontent.com/47747466/111286142-dc003580-867c-11eb-8b25-9ada347158c1.png)
你看一下style的值分别是什么

**Comment by GloryBoy239** [comment]
> 我也遇到了相似的问题，开发者帮我解决了，我来传个火，你看能不能解决。
> 先确定一下是不是同样的问题，你看一下qv2ray的配置文件，windows好像是`~/Appdata/local/q2ray`，打开`Qv2ray.conf`，查看` "uiConfig": { "graphConfig": { "colorConfig": {`下面的值，大概是是这样，前面`$2`还有一个`$0,$1`。 你看一下style的值分别是什么
> ![图像](https://user-images.githubusercontent.com/47747466/111286142-dc003580-867c-11eb-8b25-9ada347158c1.png)

                "$0": {
                    "value1": {
                        "B": 63,
                        "G": 196,
                        "R": 134,
                        "style": 0
                    },
                    "value2": {
                        "B": 255,
                        "G": 153,
                        "R": 50,
                        "style": 0
                    }
                },
                "$1": {
                    "value1": {
                        "B": 63,
                        "G": 196,
                        "R": 134,
                        "style": 0
                    },
                    "value2": {
                        "B": 255,
                        "G": 153,
                        "R": 50,
                        "style": 0
                    }
                },
                "$2": {
                    "value1": {
                        "B": 240,
                        "G": 210,
                        "R": 0,
                        "style": 3
                    },
                    "value2": {
                        "B": 42,
                        "G": 220,
                        "R": 235,
                        "style": 3
                    }

**Comment by GloryBoy239** [comment]
我的S0，S1，S2是这样的：

                "$0": {
                    "value1": {
                        "B": 63,
                        "G": 196,
                        "R": 134,
                        "style": 0
                    },
                    "value2": {
                        "B": 255,
                        "G": 153,
                        "R": 50,
                        "style": 0
                    }
                },
                "$1": {
                    "value1": {
                        "B": 63,
                        "G": 196,
                        "R": 134,
                        "style": 0
                    },
                    "value2": {
                        "B": 255,
                        "G": 153,
                        "R": 50,
                        "style": 0
                    }
                },
                "$2": {
                    "value1": {
                        "B": 240,
                        "G": 210,
                        "R": 0,
                        "style": 3
                    },
                    "value2": {
                        "B": 42,
                        "G": 220,
                        "R": 235,
                        "style": 3
                    }

**Comment by GloryBoy239** [comment]
我的应该不是S2引起的错误。
在楼上兄弟的提示下，我找到了解决办法，成功解决！

解决方法：程序卸载是不会删除~/Appdata/local/q2ray文件夹下一系列配置文件（所以即便那你卸载后在安装，你的节点信息都是还在的）。所以卸载后手动把这个qv2ray主文件夹删除。然后重新安装，你会发现节点信息全部没有了，添加节点信息，连接，速度图像就正常显示了！
