### ISSUE TITLE
能否添加“不改变系统 代理”选项

### ISSUE THREAD

**Issue by fengchen-github** [Qv2ray/Qv2ray#1361]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
不设置系统代理 ，手动开启系统代理，代理会无效

**简单描述你预期的解决方案？**
能否像v2rayN那样添加不改变系统代理选项

**你有想到其他比较容易实现的解决方案吗？**
没有

**补充内容**
个人觉得有些网页即使使用代理直连也会有问题，需要在系统代理设置白名单，所以有此需求

**Comment by dyhkwong** [comment]
你的意思是启用/禁用代理时不应该修改代理设置的“例外”列表？

**Comment by fengchen-github** [comment]
> 你的意思是启用/禁用代理时不应该修改代理设置的“例外”列表？

对，禁用代理貌似会关闭系统代理

**Comment by dyhkwong** [comment]
现在启用/禁用系统代理时不会覆盖例外列表了 https://github.com/Qv2ray/Qv2ray/commit/89f187d61d4c7f260b9623eba52a8c7f349cf48a
