### ISSUE TITLE
使用疑问：「Ubuntu18.04环境下， Qv2ray重新连接之后，会更改系统网络代理中HTTP代理\HTTPS代理内内容 」

### ISSUE THREAD

**Issue by LiuZhenyao** [Qv2ray/Qv2ray#1363]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

`QV_ISSUE_QUESTION_TEMPLATE_PLACEHOLDER`

### 你想做啥？
*简要描述你的最原始的目的。*

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by DuckSoft** [comment]
根据这里的代码判断，Ubuntu 系统代理设置应该是通过 gsetting 修改的：
https://code.qv2ray.net/dev/qv2ray/src/components/proxy/QvProxyConfigurator.cpp.html#299

设置系统代理相关的代码在这里：
https://code.qv2ray.net/dev/qv2ray/src/ui/widgets/windows/w_MainWindow_extra.cpp.html#_ZN10MainWindow16MWSetSystemProxyEv

其中的 address 直接来自 127.0.0.1 等地址，并未拼接 http:// 等字样。
请明察。

**Comment by DuckSoft** [comment]
另外，如果您提到的是 http_proxy 环境变量而非 gsetting 中的一项配置，那么我们非常确定以及肯定：我们没有这种强制覆盖用户的环境变量的逻辑。还请您自己仔细排查一下。
