### ISSUE TITLE
manjaro libprotobuf.so.26: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by siyuanpan** [Qv2ray/Qv2ray#1365]
- [ x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
系统: manjaro
在命令行执行 qv2ray得到如下报错
qv2ray: error while loading shared libraries: libprotobuf.so.26: cannot open shared object file: No such file or directory

### 打开首选项 -> 关于，填写以下信息

```
版本: 
编译信息：
额外编译信息：
```

### 操作系统

- Linux

### 安装来源

- ArchLinux AUR - 稳定版

## 附加信息

*请注意打码隐私相关信息。*

**Comment by U-v-U** [comment]
@siyuanpan https://t.me/qv2ray_outpost/294

**Comment by DuckSoft** [comment]
这不是 Bug。

请参考 #1085 #1073 #1069 #1059 #1047 #1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032 等 Issue，建议放弃幻想，欢迎安装 Arch Linux。

![图片](https://user-images.githubusercontent.com/7822648/98437041-3ced8f00-211a-11eb-8b4e-cbc3cfa55046.png)
