### ISSUE TITLE
使用疑问：「有什么办法可以固定Qv2Ray的更新来源？  」

### ISSUE THREAD

**Issue by NichtsVonChaos** [Qv2ray/Qv2ray#1366]
我使用Manjaro，并且从AUR安装Qv2Ray，但是每当执行`yay -Syu`时，都会从Archlinux CN下载新版本并覆盖掉AUR版本，是否有办法可以固定Qv2Ray的更新源为AUR而不是Archlinux CN？

**Comment by MarksonHon** [comment]
@NichtsVonChaos 估计没办法的，除非不用CN源

**Comment by 2014CAIS01** [comment]
请参考 #1085 #1073 #1069 #1059 #1047 #1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032 等 Issue，建议放弃幻想，欢迎安装 Arch Linux。

![图片](https://user-images.githubusercontent.com/22931465/111641770-6ccf4080-8838-11eb-851e-cdfb586dc154.png)

**Comment by oldherl** [comment]
你可以把自己打的AUR的包版本号改成 9999 之类的大数，这样就不会被覆盖掉了。

当然，在 manjaro 上面使用 archlinuxcn 源，这本来就是不受支持的用法。

**Comment by DuckSoft** [comment]
```shell
yay -S qv2ray --aur
# yay -S qv2ray-dev-git --aur
```
