### ISSUE TITLE
Ubuntu 2010 显示问题

### ISSUE THREAD

**Issue by neuliyiping** [Qv2ray/Qv2ray#1368]
Ubuntu 界面显示不全
[https://gitee.com/neuliyiping/images/raw/master/img/Screenshot from 2021-03-18 20-55-20.png](https://gitee.com/neuliyiping/images/raw/master/img/Screenshot from 2021-03-18 20-55-20.png)

**Comment by axionl** [comment]
> Ubuntu 界面显示不全
> [https://gitee.com/neuliyiping/images/raw/master/img/Screenshot from 2021-03-18 20-55-20.png](https://gitee.com/neuliyiping/images/raw/master/img/Screenshot from 2021-03-18 20-55-20.png)

你所访问的页面不存在！

**Comment by 2014CAIS01** [comment]
> > Ubuntu 界面显示不全
> > [https://gitee.com/neuliyiping/images/raw/master/img/Screenshot from 2021-03-18 20-55-20.png](https://gitee.com/neuliyiping/images/raw/master/img/Screenshot from 2021-03-18 20-55-20.png)
> 
> 你所访问的页面不存在！

[https://gitee.com/neuliyiping/images/raw/master/img/Screenshot from 2021-03-18 20-55-20.png](https://gitee.com/neuliyiping/images/raw/master/img/Screenshot%20from%202021-03-18%2020-55-20.png)

**Comment by DuckSoft** [comment]
看起来是设置了错误的 QT 缩放参数导致的。
Ubuntu 20.10 请考虑使用原生 Debian 包：
* https://qv2ray.net/debian
* https://qv2ray.net/debian-dev

有关 QT 缩放的环境变量问题，请在 Issue 区搜索 Qt 环境变量 两个关键词。
