### ISSUE TITLE
使用疑问：「二维码扫描  」

### ISSUE THREAD

**Issue by ckbkdj** [Qv2ray/Qv2ray#1369]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

`QV_ISSUE_QUESTION_TEMPLATE_PLACEHOLDER`

### 你想做啥？
*简要描述你的最原始的目的。*
我使用windows 发现导入只能复制粘贴连接 不能扫描二维码
![image](https://user-images.githubusercontent.com/9382231/111862859-fb57d500-8992-11eb-888b-451e3300495e.png)

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
我搜索了google等地方都没有找到相关资料,都是直接可以用. 目前版本是2.7.0-pre2:6150

### 其他要补充的信息？
无

**Comment by cubercsl** [comment]
https://github.com/Qv2ray/Qv2ray/commit/a09f2aee0adfe1ecf234e39b73f49bb9b18f7d58 这个功能应该是在新的版本里被移除了

**Comment by ckbkdj** [comment]
...
