### ISSUE TITLE
使用疑问：组编辑器-导入过滤器

### ISSUE THREAD

**Issue by JianJunYuan** [Qv2ray/Qv2ray#1370]
版本：2.6.3:5840
需求：过滤指定字符的订阅地址
问题：使用组编译器-导入过滤器可以过滤第一个字符，但是后续的字符无法进行过滤，请问字符间隔是什么？

**Comment by cubercsl** [comment]
是换行，每行一个要过滤的字符串。

**Comment by JianJunYuan** [comment]
谢谢，可以过滤了
