### ISSUE TITLE
vless报错

### ISSUE THREAD

**Issue by lsh1215225** [Qv2ray/Qv2ray#1371]
main: failed to read config files: [D:/QV2RAY/config/generated/config.gen.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  D:/QV2RAY/config/generated/config.gen.json
v2ray.com/core/infra/conf: VLESS users: "flow" is not available in this version > exit status 4294967295

**Comment by DuckSoft** [comment]
应该是上游的 V2Ray Core 炸掉了这个选项。我先排除一下。

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/112084844-6fc58a80-8bc4-11eb-8691-4ffb51e1569c.png)
确认 Qv2ay v2.7.0-pre2 的 Tree Shaking 功能没有问题。
你可能是用了 V2Ray 核心并开启了上游已经停止支持的 XTLS flow 选项。
如果确实需要使用该选项，请自行换用 XRay Core

**Comment by lsh1215225** [comment]
是直接用xray core替换掉v2ray core嘛？

**Comment by lsh1215225** [comment]
> ![图片](https://user-images.githubusercontent.com/7822648/112084844-6fc58a80-8bc4-11eb-8691-4ffb51e1569c.png)
> 确认 Qv2ay v2.7.0-pre2 的 Tree Shaking 功能没有问题。
> 你可能是用了 V2Ray 核心并开启了上游已经停止支持的 XTLS flow 选项。
> 如果确实需要使用该选项，请自行换用 XRay Core

是直接用xray core替换掉v2ray core嘛？

**Comment by DuckSoft** [comment]
可以直接替换，也可以再下载一份，然后改掉核心可执行文件路径/核心资源文件路径

**Comment by lsh1215225** [comment]
> 可以直接替换，也可以再下载一份，然后改掉核心可执行文件路径/核心资源文件路径

好的 我试一下

**Comment by afotohi12** [comment]
i have same problem in ubuntu 22 on vless protocol.

**Comment by Fangliding** [comment]
@afotohi12 ?

**Comment by afotohi12** [comment]
> @afotohi12 ?

I can't connect on Ubuntu 22 and v2ray version x-ray 1.8.1 pre . 
![IMG_20230519_225819.png](https://github.com/Qv2ray/Qv2ray/assets/73761020/a06e27bb-e239-479b-8da7-902eff3ecec3)
