### ISSUE TITLE
功能请求：Windows安装程序增加UTF-8支持

### ISSUE THREAD

**Issue by 1900011604** [Qv2ray/Qv2ray#1373]
![图片](https://user-images.githubusercontent.com/65082432/112145286-205b7a80-8c15-11eb-8db9-d605ba2d3498.png)

如图，我在Windows上启用了UTF-8支持结果它显示成这样
```
PS C:\Users\19000> chcp
Active code page: 65001
```

**Comment by U-v-U** [comment]
@1900011604 对于 NSIS 安装器的本地化支持，我们目前无能为力（并且不知道该怎么处理）

**Comment by DuckSoft** [comment]
嗯，这个安装程序的名字叫 Nullsoft Installer（NSIS）。
您可以考虑去上游发起一个功能请求，或者您可以告诉我们应该怎么做（因为我们也不知道该怎么处理）。

**Comment by 1900011604** [comment]
或许你们可以选择用……Unicode NSIS

https://github.com/jimpark/unsis
