### ISSUE TITLE
ubuntu 18.06 error

### ISSUE THREAD

**Issue by mengchaoheng** [Qv2ray/Qv2ray#1375]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
In VMware's ubuntu virtual machine, Qv2ray often fails after using it for a period of time. Especially after shutting down the virtual machine and restarting, Qv2ray can no longer connect.

## 如何触发这个 Bug：

1. In VMware's ubuntu virtual machine, open Qv2ray and link to the server
2. Suspend the client in vmware
3. Restore client
4. see error

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

no

### 相关截图或日志
![Ubuntu-2021-03-24-10-01-29](https://user-images.githubusercontent.com/43166007/112243104-f8f1c580-8c87-11eb-9bb9-fbbc47587d08.png)

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：

V2Ray 4.31.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
A unified platform for anti-censorship.
2021/03/24 09:48:07 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
v2ctl> Read config:  /home/mch/.config/qv2ray/generated/config.gen.json


```

</details>

## 系统信息

ubuntu 18.06

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.7.0-pre2:6150
编译信息：
额外编译信息：
```

### 操作系统

- Linux

### 安装来源

- GitHub Releases Binary

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
Qv2ray 本体不提供代理功能，你所说的问题实际上是 V2Ray 内核在 freeze 之后无法恢复代理功能。
非常抱歉，这不是我们能解决的问题。
