### ISSUE TITLE
ubuntu 终端命令没有效果

### ISSUE THREAD

**Issue by libxengine** [Qv2ray/Qv2ray#1376]
..不走代理 为啥?
ubuntu20.04
qv2ray2.6.3
我是下载的git上发布的软件包,不是自己编译和通过apt安装的
没有用root用户配置运行
连接上后 我看系统代理也设置了,但是我终端运行命令啥效果都没的
比如git pull ......

**Comment by flyawayazure** [comment]
@libxengine 终端命令行工具一般不会使用系统代理，这是正常现象
git命令的代理应该可以通过更改git的配置指定，或者你可以了解透明代理

**Comment by libxengine** [comment]
我记得我以前都用起了,怪事了..忘记是杂用的了

**Comment by DuckSoft** [comment]
你也许还需要稍微了解一些 Linux 系统的常识。
考虑使用 http_proxy、https_proxy 环境变量和/或 proxychains 解决。
