### ISSUE TITLE
使用疑问：「 linux mint上的qv2ray会出现权限不足，无法访问核心文件 」

### ISSUE THREAD

**Issue by po888375** [Qv2ray/Qv2ray#1379]
我已经设置了最高的权限了，但是还是显示当前用户没有权限。qv2ray是按照官网的文档，使用sudo apt-get install qv2ray安装的。

这是提示的截图：https://ftp.bmp.ovh/imgs/2021/03/ca4e14c62ee0bcaf.png
这是权限的截图：https://ftp.bmp.ovh/imgs/2021/03/c5d740c6d72f72c4.png

求大佬解惑

**Comment by DuckSoft** [comment]
换源：https://qv2ray.net/debian-dev

**Comment by po888375** [comment]
> 换源：https://qv2ray.net/debian-dev
> Qv2ray v2.6.3 不支持 Xray，得用预览版。

大佬，我就是用这里面的源，我看了下版本号是：2.6.3:5840，这个不是最新的吗

**Comment by Alasmercer** [comment]
> > 换源：https://qv2ray.net/debian-dev
> > Qv2ray v2.6.3 不支持 Xray，得用预览版。
> 
> 大佬，我就是用这里面的源，我看了下版本号是：2.6.3:5840，这个不是最新的吗

我在用archlinux，遇到同样的问题。我发现如果同时安装了xray和v2ray，在qv2ray 2.6.3中设置核心路径到xray就可以使用。移除v2ray后就报没有执行权限。等于半支持xray，可以用。
