### ISSUE TITLE
功能请求：Linux 版本增加像是 Windows 的那样的压缩包版本

### ISSUE THREAD

**Issue by 517030910405** [Qv2ray/Qv2ray#1380]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

-----------------

**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**

请尽可能清晰简洁地描述问题。

_**Windows 版本节点配置直接在文件夹里面，可执行文件通过相对路径获取配置信息。文件夹压缩后可以直接复制到另一个机器上面，很方便。但是 Linux 版本 AppImage 的配置文件不能类似地复制过去后使用相对路径，比较麻烦。**_

**简单描述你预期的解决方案？**

请尽可能清晰简洁描述问题。

_**发布 release 版本包含压缩后的可执行目录版本。**_

**你有想到其他比较容易实现的解决方案吗？**

请简单清晰描述。 

**补充内容**
请在此附加任何你认为对你的描述有所帮助的内容。

**Comment by cubercsl** [comment]
Linux 发行版一般可以通过包管理安装，配置文件为啥不直接复制 `XDG_CONFIG_HOME/qv2ray` 下的配置呢？

**Comment by 517030910405** [comment]
这样不支持同一台设备多个配置的 Qv2ray 同时存在

**Comment by 517030910405** [comment]
不是特别方便

**Comment by 517030910405** [comment]
> 这样不支持同一台设备多个配置的 Qv2ray 同时存在

我指的是完全隔离的两组配置文件

此外一个 tar gz 文件复制过去更加方便

**Comment by kidonng** [comment]
请问你的具体需求是什么？

**Comment by cubercsl** [comment]
@517030910405 你可以使用 QV2RAY_CONFIG_PATH 这个环境变量来指定 Qv2ray 读取配置的文件夹。
