### ISSUE TITLE
使用疑问：「 mac系统无法访问淘宝及电商平台的推广页面 」

### ISSUE THREAD

**Issue by nathanxie** [Qv2ray/Qv2ray#1381]
本人使用的MacBook pro 16寸，系统为最新11.2.3
由于本人从事电商行业，需要经常访问电商平台的推广模块，都是无法打开（显示无法建立安全链接）。今天致电苹果客服解决这个问题。通过设置-网络-添加新位置就可以解决这个问题。
但是Qv2ray就失效了，换节点或者重启Qv2ray又能科学上网，之前的推广模块又打不开了。
是不是两者有什么冲突？
后来切换小飞机，问题就解决了，能打开推广模块，又能科学上网。不冲突。
但是小飞机只支持ss和ssr协议，有点蛋疼，我还是想用Qv2ray，请问有解决办法吗？
![1616752436942](https://user-images.githubusercontent.com/49366818/112614526-550d4300-8e5c-11eb-8b94-14e213581477.jpg)

**Comment by DuckSoft** [comment]
首选项——高级路由设置——域名/阻断——去掉 geosite:category-ads-all——重连
