### ISSUE TITLE
Ubuntu 不显示托盘图标 日志颜色异常

### ISSUE THREAD

**Issue by ruoyu2000** [Qv2ray/Qv2ray#1384]
系统：
Ubuntu 20.04

问题1：
系统重启后不显示托盘图标

问题2：
系统重启后，日志颜色异常，如图
![Screenshot](https://user-images.githubusercontent.com/29647511/112765869-d3770a00-9041-11eb-8695-3e1c2fadf393.png)

**Comment by cubercsl** [comment]
@ruoyu2000 1. http://qv2ray.net/faq/#behavior-appearance-issues

**Comment by ruoyu2000** [comment]
> @ruoyu2000 1. http://qv2ray.net/faq/#behavior-appearance-issues
> 
> 1. 首选项中适应暗色主题相关选项调整后重启Qv2ray。

感谢，问题已解决。

补充下：
安装gnome-tweaks
在系统扩展应用中，开启Ubuntu AppIndicators，重新运行程序即可显示任务栏图标

如果Qv2ray主题不是内置黑暗模式，不要勾选适应黑暗主题，我以为会自动适应。
