### ISSUE TITLE
Question: <Your Awesome Question>

### ISSUE THREAD

**Issue by ebxcto** [Qv2ray/Qv2ray#1385]
### Describe You Purpose
不明白为什么如此多的报错
### Describe What Have You Tried
2021/03/29 09:18:44 [Info] [312635252] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > write tcp 127.0.0.1:7890->127.0.0.1:50685: wsasend: An established connection was aborted by the software in your host machine.
2021/03/29 09:18:44 [Info] [312635252] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: connection ends > context canceled
[2021-03-29 09:18:44] [INFO] 127.0.0.1:50690 disconnected, 4285 bytes received, 517 bytes sent, lasted for 1 seconds
2021/03/29 09:18:44 [Info] [3735653123] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > write tcp 127.0.0.1:7890->127.0.0.1:50688: wsasend: An established connection was aborted by the software in your host machine.
2021/03/29 09:18:44 [Info] [3735653123] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: connection ends > context canceled
[2021-03-29 09:18:44] [INFO] 127.0.0.1:50693 disconnected, 4285 bytes received, 517 bytes sent, lasted for 1 seconds
2021/03/29 09:18:44 [Info] [531231117] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > write tcp 127.0.0.1:7890->127.0.0.1:50687: wsasend: An established connection was aborted by the software in your host machine.
2021/03/29 09:18:44 [Info] [531231117] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: connection ends > context canceled
[2021-03-29 09:18:44] [INFO] 127.0.0.1:50692 disconnected, 4285 bytes received, 517 bytes sent, lasted for 1 seconds
2021/03/29 09:18:44 [Info] [3628896286] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > write tcp 127.0.0.1:7890->127.0.0.1:50689: wsasend: An established connection was aborted by the software in your host machine.
2021/03/29 09:18:44 [Info] [3628896286] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: connection ends > context canceled
[2021-03-29 09:18:44] [INFO] 127.0.0.1:50694 disconnected, 4285 bytes received, 517 bytes sent, lasted for 1 seconds
2021/03/29 09:18:44 [Info] [4145058924] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > write tcp 127.0.0.1:7890->127.0.0.1:50686: wsasend: An established connection was aborted by the software in your host machine.
2021/03/29 09:18:44 [Info] [4145058924] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: connection ends > context canceled
[2021-03-29 09:18:44] [INFO] 127.0.0.1:50691 disconnected, 4285 bytes received, 517 bytes sent, lasted for 1 seconds
2021/03/29 09:18:45 [Info] [624800566] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > context canceled
2021/03/29 09:18:45 [Info] [624800566] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: connection ends > context canceled
[2021-03-29 09:18:45] [INFO] 127.0.0.1:50669 disconnected, 4165 bytes received, 2153 bytes sent, lasted for 4 seconds

**Comment by U-v-U** [comment]
Closing due to insufficient information given.
