### ISSUE TITLE
Qv2ray.v2.7.0-pre2.linux-x64.AppImage版本保存不了内核

### ISSUE THREAD

**Issue by po888375** [Qv2ray/Qv2ray#1386]
每次重启电脑都要重新设置内核。想知道这个怎么解决，谢谢各位大佬

**Comment by cubercsl** [comment]
你怎么重启的电脑？Qv2ray 的设置是否正确保存？请确保正确关闭了 Qv2ray 后再重启。

**Comment by po888375** [comment]
> 你怎么重启的电脑？Qv2ray 的设置是否正确保存？请确保正确关闭了 Qv2ray 后再重启。

就是我已经在设计里设置了内核，并且已经连接了节点，但是重启后只有节点在，首选项被重置了

**Comment by cubercsl** [comment]
Qv2ray 的首选项修改不是在点 OK 时保存的，是在正常退出时才写入磁盘的。

appimage 版在系统关闭时，貌似和 session manager 接不上来着。

解决方案：
1.换deb版；
2.改完首选项后记得手动退出一次；
~~3. 交pr，让qv2ray在点OK时也向磁盘写入修改。~~

**Comment by ruoyu2000** [comment]
碰到同样的问题，我的解决方法是，把v2ray-core放入Qv2ray默认配置目录，即/.confg/qv2ray/vcore (Ubuntu下)

**Comment by po888375** [comment]
> Qv2ray 的首选项修改不是在点 OK 时保存的，是在正常退出时才写入磁盘的。
> 
> appimage 版在系统关闭时，貌似和 session manager 接不上来着。
> 
> 解决方案：
> 1.换deb版；
> 2.改完首选项后记得手动退出一次；
> ~3. 交pr，让qv2ray在点OK时也向磁盘写入修改。~

感谢，已经用2方法解决了，谢谢

**Comment by po888375** [comment]
> 碰到同样的问题，我的解决方法是，把v2ray-core放入Qv2ray默认配置目录，即/.confg/qv2ray/vcore (Ubuntu下)

这个没办法，我是用xray，而且其他设置也会被重置，我设置后手动退出一次，然后再打开就保存了。
