### ISSUE TITLE
不能连接outlook

### ISSUE THREAD

**Issue by dzhl** [Qv2ray/Qv2ray#1387]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

使用qv2ray,连接设置中勾选了绕过私有地址和绕过中国大陆(相当于pac模式)，无法连接outlook office365 桌面版，同样节点和geoip.dat和geosite.dat,trojan-qt5使用pac模式就可以顺利连接outlook，试过很多次，每次都是这样。即便个别时候使用qv2ray连接上outlook，也过不了多久就会掉线，然后又连接不上，猜测能连接一段时间可能是缓存的问题

## 如何触发这个 Bug：

1. 勾选了绕过私有地址和绕过中国大陆
2. 开启代理
3. 打开outlook，会发现无法连接

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

trojan-qt5里是正常的

### 相关截图或日志
日志里显示走的网址都是走的节点，在路由里把网址改为都是直连，也无法连接，关闭代理后，开启outlook也能很快连接，或者使用trojan-qt5也能很快连接
<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息
试过多个版本，都是如此
```
版本: 2.7.0-pre2:6150
编译信息：2.7.0-pre2:6150
额外编译信息：qt5.15.0-4cc95cb2f686250c899a04969e1a220af449908d-ci.windows-latest
```

### 操作系统

- Windows

### 安装来源

- Github Release / Scoop / Chocolatey

### 已安装的插件、版本及安装来源
官网插件库，trojan-go插件，
官方Xray内核和官方V2ray内核，都试过，一样问题

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
UWP回环隔离问题

**Comment by dzhl** [comment]
> UWP回环隔离问题
那我该如何设置解决呢？

**Comment by jbxiaoyu** [comment]
> UWP回环隔离问题

outlook桌面版不是UWP应用吧？
