### ISSUE TITLE
obfs-local:买的SS订阅需要obfs-local支持，大佬怎么搞？

### ISSUE THREAD

**Issue by SpecterTaoist** [Qv2ray/Qv2ray#1390]
买的SS订阅需要obfs-local支持，大佬怎么搞？

**Comment by DuckSoft** [comment]
不知道呀，俺也不会～
你买的订阅不给你提供客户端的吗，不给你提供你找他退款呀～

**Comment by SpecterTaoist** [comment]
> 不知道呀，俺也不会～
> 你买的订阅不给你提供客户端的吗，不给你提供你找他退款呀～

嗯，是给的有客户端，但是不想用他们呢给的。

**Comment by SpecterTaoist** [comment]
> 不知道呀，俺也不会～
> 你买的订阅不给你提供客户端的吗，不给你提供你找他退款呀～
> 
> # 啥时候开发者成了机场的免费客服了？

你没发现现在好多SS都是需要这个插件的么。

**Comment by DuckSoft** [comment]
想用也不是不行，就是配置起来特别麻烦：
1. 安装 QvPlugin-SS 插件
2. 安装 simple-obfs 系列，并放置在 PATH 下
3. 直接导入节点即可使用

如果还是不明白，强烈建议你放弃折腾。

**Comment by SpecterTaoist** [comment]
> 想用也不是不行，就是配置起来特别麻烦：
> 
> 1. 安装 QvPlugin-SS 插件
> 2. 安装 simple-obfs 系列，并放置在 PATH 下
> 3. 直接导入节点即可使用
> 
> 如果还是不明白，强烈建议你放弃折腾。

好的，多谢大佬，我研究研究。

**Comment by SpecterTaoist** [comment]
> 想用也不是不行，就是配置起来特别麻烦：
> 
> 1. 安装 QvPlugin-SS 插件
> 2. 安装 simple-obfs 系列，并放置在 PATH 下
> 3. 直接导入节点即可使用
> 
> 如果还是不明白，强烈建议你放弃折腾。

卧槽，大佬果然是大佬，可以了，非常感谢。
