### ISSUE TITLE
Python pip 连接问题

### ISSUE THREAD

**Issue by luyiming** [Qv2ray/Qv2ray#1393]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

开启 Qv2ray 系统代理后，所有 pip install 命令都出现代理连接错误，如下所示：
![image](https://user-images.githubusercontent.com/15070842/113376722-f76d7f00-93a4-11eb-9f30-58fcb94df60b.png)

Qv2ray 日志如下：
![image](https://user-images.githubusercontent.com/15070842/113376761-0eac6c80-93a5-11eb-8937-a14f0bbb8031.png)

**Comment by DuckSoft** [comment]
export https_proxy=http://127.0.0.1:8889

等号后面没s

**Comment by EpLiar** [comment]
@luyiming 看起来你提 issue 的时候没有给出详细的环境信息，难不成你在用 deepin？

**Comment by DuckSoft** [comment]
Windows: Python Bug: https://bugs.python.org/issue42627

**Comment by cubercsl** [comment]
正如 DuckSoft 所说，这是 Python 的 bug，目前可能的解决方案是关闭系统代理，并手动设置 pip 的代理。

**Comment by luyiming** [comment]
我是 windows 10，确实，设置环境变量 https_proxy 以后解决了，没想到竟然是 python 的 bug

**Comment by luyiming** [comment]
另外有个尴尬的请求，我刚刚看到有 qv2ray user group 的 telegram 群组，进入的时候问我 qv2ray 用啥开发的，我随手选了个 QT，人傻了，应该是 C++，现在他提示 private group 加入不了了。我的用户名是 eamondovis，不知道可不可以再拉我进去 😭

**Comment by po888375** [comment]
> 另外有个尴尬的请求，我刚刚看到有 qv2ray user group 的 telegram 群组，进入的时候问我 qv2ray 用啥开发的，我随手选了个 QT，人傻了，应该是 C++，现在他提示 private group 加入不了了。我的用户名是 eamondovis，不知道可不可以再拉我进去

哈哈，我也是选错了，好像选错了过一段时间再加入就可以了

**Comment by sixg0000d** [comment]
> 另外有个尴尬的请求，我刚刚看到有 qv2ray user group 的 telegram 群组，进入的时候问我 qv2ray 用啥开发的，我随手选了个 QT，人傻了，应该是 C++，现在他提示 private group 加入不了了。我的用户名是 eamondovis，不知道可不可以再拉我进去

入群解封 / Unblocking: @QvUnblockMe_bot
