### ISSUE TITLE
功能请求：Snapcraft 包同捆 Trojan 插件

### ISSUE THREAD

**Issue by feier0908** [Qv2ray/Qv2ray#1396]
![2021-04-07 16-00-10 的屏幕截图](https://user-images.githubusercontent.com/31612688/113831964-bcab8280-97ba-11eb-9a0b-504fa9bf6a99.png)

**Comment by DuckSoft** [comment]
Ubuntu 系统为啥要用 AppImage 包呢……
请使用我们的 apt 源
https://qv2ray.net/debian-dev/

**Comment by feier0908** [comment]
里面自带的只支持v2ray协议的，也就是vmess

**Comment by DuckSoft** [comment]
> 里面自带的只支持v2ray协议的，也就是vmess

“以前的版本”——

很久很久以前，@ymshenyu 打包的 Snapcraft 某些版本中，附送了 Trojan 插件和 SSR 插件。
不过现在的确是没有了（因为维护不动了）。

**Comment by DuckSoft** [comment]
看看维护者 @ymshenyu 本人的意愿吧。

**Comment by ymshenyu** [comment]
@feier0908 重新加回去了，晚点可以用 edge channel 的包试试看。
