### ISSUE TITLE
Release Tag 與二進制文件命名問題

### ISSUE THREAD

**Issue by M1Screw** [Qv2ray/Qv2ray#1397]
現在 Release 裏面的二進制包有兩種命名方式

qv2ray-2.7.0-pre2-win64.exe

和

Qv2ray.v2.7.0-pre2.macOS-x64.dmg

同時實際的 Release Tag 為

v2.7.0-pre2

建議統一 Tag 名與包的命名規則，這樣就不用單獨為 Qv2ray 寫一個客戶端拉取方式= =

**Comment by DuckSoft** [comment]
Dealing with it now. In fact, this release asset is manually transferred from GitHub Actions.
Thanks for reporting in.

**Comment by DuckSoft** [comment]
Changes made! Check'em out!
