### ISSUE TITLE
在最新版 gcc 中构建单元测试失败，建议更新 test/catch.hpp

### ISSUE THREAD

**Issue by sixg0000d** [Qv2ray/Qv2ray#1398]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

由于一系列变化在使用最新版 libc 时 catch.hpp v2.13.4 及以下版本会编译失败，详见 https://github.com/catchorg/Catch2/issues/2178
现 catch2 已修复该问题并发布新版本 [v2.13.5](https://github.com/catchorg/Catch2/releases/tag/v2.13.5) ，建议该项目及其他使用了该头文件的项目更新 [catch.hpp](https://github.com/Qv2ray/Qv2ray/blob/dev/test/catch.hpp)

## 如何触发这个 Bug：

```
cmake -DBUILD_TESTING=ON
cmake --build .
```

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 
编译信息：
额外编译信息：
```

### 操作系统

- Linux
- macOS
- Windows

### 安装来源

- ArchLinuxCN - 稳定版
- ArchLinuxCN - 开发版
- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版
- Fedora - 稳定版
- Fedora - 开发版
- openSUSE - 稳定版
- openSUSE - 开发版
- Flathub 包
- Snap 包
- Homebrew Cask
- Github Release / Scoop / Chocolatey
- 手动编译

## 附加信息

gcc version: 11.0.1
glibc version: 2.33.9000

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
Thank you for the report! I will handle this later tonight.

**Comment by sixg0000d** [comment]
pr has been merged, close now.
