### ISSUE TITLE
功能请求：<完整的支持xray的trojan协议以及添加分组的负载均衡和故障转移>

### ISSUE THREAD

**Issue by Xaster** [Qv2ray/Qv2ray#1399]
1、请求完整的支持xray的trojan协议，xray已经实现trojan+tcp+xtls，但是目前支持xray的GUI好像没有一个支持的，希望能跟进。
2、请求添加分组的负载均衡和故障转移功能，这样可以充分的利用多个vps或者同vps下的多个协议。

**Comment by U-v-U** [comment]
@Xaster for xray-related problems, we'd expect a pull request.

**Comment by dyhkwong** [comment]
1. Duplicate https://github.com/Qv2ray/Qv2ray/issues/1126. IMHO it requires many hacks to support Trojan without breaking compatibility with QvPlugin-Trojan, unless some breaking changes / new architecture design are achieved.
2. load balance and failover should be implemented by the core rather than a GUI.

**Comment by Xaster** [comment]
> 
> 
>     1. Duplicate #1126. IMHO it requires many hacks to support Trojan without breaking compatibility with QvPlugin-Trojan, unless some breaking changes / new architecture design are achieved.
> 
>     2. load balance and failover should be implemented by the core rather than a GUI.

1、并不需要，xray的trojan协议是xray核心支持的协议，功能上完全不需要trojan插件，如果是担心名称冲突，这个协议完全可以命名为xray-trojan之类的以示区分，所以这与插件完全没有关系。
2、核心或许能够实现同一vps下它所支持的不同协议的负载均衡和故障转移，但不能支持实现跨核心的负载均衡和故障转移，所以核心来实现其实是意义不大的，不如按现在的方向做好路由。而最具价值的多个vps的各种协议的负载均衡和故障转移以及有一定价值的同一vps跨核心的负载均衡和故障转移，这个核心是无法很好的来实现的，只能由GUI来扩展支持了。

**Comment by DuckSoft** [comment]
Maybe you are correct, hmm... But sorry, I personally don't have time for this.
If you can do it, just send a pull request, and this will be great.

About the load balancing and failover thing: it's WIP and scheduled in Qv2ray v3.0. We don't do this in Qv2ray v2.
