### ISSUE TITLE
「 如何添加类似PAC的功能，绕过内网 」

### ISSUE THREAD

**Issue by zxfszane** [Qv2ray/Qv2ray#1400]
### 如何添加类似PAC的功能
*公司这边有自己的dns和内部网站，勾选绕过中国大陆选项后，内网还是走的代理，导致不能上网了。另外百度之类的内网也走了代理。 win上的nv2ray好像不会这样。*

**Comment by EpLiar** [comment]
你可以在浏览器里用 SwitchyOmega 控制部分域名不走代理

**Comment by cubercsl** [comment]
@zxfszane 你可以在高级路由设置里自行设置直连/代理/阻断的域名和IP地址。https://qv2ray.net/manual/route.html#global-routing-rules

**Comment by zxfszane** [comment]
> SwitchyOmega

谢谢，我知道了

**Comment by dyhkwong** [comment]
Try to append DNS from your company to the DNS servers list as well.
