### ISSUE TITLE
qv2ray没办法使用了，显示configuration Error，该怎么做？

### ISSUE THREAD

**Issue by GaoSimon** [Qv2ray/Qv2ray#1406]
系统是Ubuntu18，之前的Qv2ray2.7.0-alpha1:5931用起来都好好的，但是我看新版本2.7.0-pre2:6150发布了，于是在没有关掉原来appimage的情况下直接打开了后一个版本的appimage，然后当时报了一个什么错，我没注意。之后再连接的时候就都是连接错误，然后现在连连接都没办法连接了，总是给我报如下错误：
![image](https://user-images.githubusercontent.com/44992796/114483370-b0f1fe80-9bb4-11eb-871c-5651f93a29b8.png)
![image](https://user-images.githubusercontent.com/44992796/114483390-b9e2d000-9bb4-11eb-921b-2ca310f9b5b4.png)
请问一下我该怎么解决呢？

**Comment by cubercsl** [comment]
@GaoSimon 检查核心的 geoip.dat 文件是否损坏。

**Comment by GaoSimon** [comment]
> @GaoSimon 检查核心的 geoip.dat 文件是否损坏。[Qv2ray/qv2ray.github.io#92](https://github.com/Qv2ray/qv2ray.github.io/pull/92)

非常感谢您的帮助。问题已解决！之前还以为要重新更换一个虚拟机了，配置过很多东西，如果重新更换将耗费巨大精力，真的非常非常感谢您！！！
