### ISSUE TITLE
连接节点报错

### ISSUE THREAD

**Issue by yjs0370** [Qv2ray/Qv2ray#1407]
版本：Qv2ray.v2.7.0-pre2.macOS-x64
日志：
V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 darwin/amd64)
A unified platform for anti-censorship.
main: failed to read config files: [/Users/yang.s.jin/Library/Preferences/qv2ray/generated/config.gen.json] 
    > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. 
    > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl:
v2ctl> Read config:  /Users/yang.s.jin/Library/Preferences/qv2ray/generated/config.gen.json
v2ray.com/core/infra/conf: VLESS users: "flow" is not available in this version > exit status 255

弹窗提示：
main: failed to read config files: [/Users/yang.s.jin/Library/Preferences/qv2ray/generated/config.gen.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  /Users/yang.s.jin/Library/Preferences/qv2ray/generated/config.gen.json
v2ray.com/core/infra/conf: VLESS users: "flow" is not available in this version > exit status 255

Qv2ray 遇到未知异常： 
请通过 GitHub 报告该文件的错误信息： 

/Users/yang.s.jin/Library/Preferences/qv2ray/bugreport/QvBugReport_1618278949.stacktrace

**Comment by DuckSoft** [comment]
两个问题混在一起：
1. 使用 V2Ray 的核心，但在 flow 中开启了 XTLS
2. 插件版本发生了混用，注意各插件适配的本体版本
