### ISSUE TITLE
使用疑问：「AppImage版可否增加对Solus4.2的支持？」

### ISSUE THREAD

**Issue by redfrog999** [Qv2ray/Qv2ray#1408]
对linux用户来说AppImage实在是太方便了，但是非常遗憾的是，我在Solus 4.2中无法使用，点击了没有任何反应，其他的distro都是完美运行。非常期待作者能修补一下对Solus的支持呀，万分感谢，感谢万分。

**Comment by DuckSoft** [comment]
感谢反馈。请在终端中尝试执行该 AppImage，并附上其日志输出，以让我们更好地定位问题。

**Comment by redfrog999** [comment]
非常感谢，这是日志输出的文字版，我在live模式下跑的：

live@solus ~ $ chmod a+x *.AppImage
live@solus ~ $ ./Brave.AppImage
Gtk-Message: 05:59:53.411: Failed to load module "canberra-gtk-module"
Gtk-Message: 05:59:53.421: Failed to load module "canberra-gtk-module"
[4986:4986:0413/055954.745250:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
live@solus ~ $ ./qv2.AppImage
qv2ray: error while loading shared libraries: libkeyutils.so.1: cannot open shared object file: No such file or directory

作为对比，我用了Brave浏览器的AppImage来测试，输出有错误但是能运行。Qv2ray直接就是没有任何反应。

**Comment by wallena3** [comment]
@redfrog999 尝试在solus安装keyutils再看看？

**Comment by redfrog999** [comment]
> @redfrog999 尝试在solus安装keyutils再看看？

非常感谢，确实有效，在软件中心搜索keyutils找到两个相关的文件，安装完就可以用了。至此问题彻底解决，感谢开发者和提供帮助的朋友。也为Solus用户提供一个参考。
