### ISSUE TITLE
使用疑问：「无法连接到服务期  」

### ISSUE THREAD

**Issue by fountainer** [Qv2ray/Qv2ray#1409]
我的系统是ubuntu 20.10, 下载的客户端是Qv2ray.v2.7.0-pre2.linux-x64.AppImage， 运行程序后配置V2Ray核心，检查可以通过，但无法连接到服务期，选项为灰色，无法连接，不知道少了哪一步?

![IMG_1817](https://user-images.githubusercontent.com/5546074/114526649-c54bff00-9c79-11eb-8cf9-3bbdd679a25e.jpg)

**Comment by DuckSoft** [comment]
这是分组，不是服务器。

**Comment by fountainer** [comment]
明白了，谢谢

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/114528868-f88f8d80-9c7b-11eb-998e-8ca3d151dc44.png)

另外，下次记得不要直接传原始图片上来，里面有 EXIF 信息……
这次帮你干掉了。

**Comment by fountainer** [comment]
> 另外，下次记得不要直接传原始图片上来，里面有 EXIF 信息……
> 这次帮你干掉了。

谢谢啦，没想到照片中还有这些信息。
