### ISSUE TITLE
功能请求：<添加允许本地局域网使用代理>

### ISSUE THREAD

**Issue by Jayj1997** [Qv2ray/Qv2ray#1411]
wls2 与 wsl1实现的方式改变了，linux变成与windows平级的系统，无法再像以前使用代理，通过搜索被告知打开v2ray的允许局域网使用代理，但是没在这里看见。so 可以加个嘛 or 是有我没找到吗？？

thx

**Comment by DuckSoft** [comment]
#### 让网络上的其他设备使用代理

默认情况下，Qv2ray的代理配置是只监听`127.0.0.1`的地址，即其代理只有本机能够使用，如需让网络上的其他设备使用代理，需要修改这一配置：

- 若希望局域网（内网ip环境）或互联网（公网ip环境）中的所有设备都能够使用本机的Qv2ray提供的代理，则在“首选项-入站设置-监听地址”里，把默认的`127.0.0.1`改成`0.0.0.0`即可。
- 若希望几个具有特定ip的设备能够使用本机的Qv2ray提供的代理，由于v2ray的限制，同一个入站不支持监听多个指定的ip，可以有两种方式解决这个问题：
  - 通过复杂配置，建立多个不同的入站来实现，每个入站分别监听其中的一个ip。
  - Qv2ray的入站监听所有ip（`0.0.0.0`），在本机设置防火墙，只允许特定ip访问Qv2ray的代理的端口。

例子：若ip为`192.168.0.100`的设备希望使用代理，本机的ip为`192.168.0.50`。若本机的Qv2ray配置了一个端口为`12345`的http入站，监听ip`0.0.0.0`或`192.168.0.100`，则在`192.168.0.100`的设备上，可通过

```
export http_proxy="http://192.168.0.50:12345"
export https_proxy="http://192.168.0.50:12345"
```

使用此http代理（其他使用方式也类似）。

注意事项：

- 为让其他设备使用本机的Qv2ray提供的代理，除了本机的Qv2ray的代理需要监听目标设备的ip之外，还需要让目标设备能通过本机ip及代理端口访问到本机。因此，若本机设置了防火墙，则需要让防火墙放行对应端口；局域网环境里，可能需要关闭“内网隔离”“AP隔离”之类的设置，否则内网ip之间也无法互相访问。
- 如果本机没有设置防火墙，将Qv2ray的代理监听的ip设为`0.0.0.0`，且局域网没有设置“内网隔离”，则意味着局域网里所有的设备都能通过本机的ip及代理端口使用本机的Qv2ray提供的代理；如果本机是处于公网ip环境里，则意味着整个互联网中所有设备都能通过本机的ip及代理端口使用本机的Qv2ray提供的代理。因此，如确需在非可信任的局域网环境或公网ip环境中开启此种配置，最好配合防火墙，或配合代理身份验证，以防止本机的代理被滥用。

**Comment by qins** [comment]
请问设置192.168.0.100时, 本机192.168.0.50不可以使用代理吗?

**Comment by EpLiar** [comment]
> 请问设置192.168.0.100时, 本机192.168.0.50不可以使用代理吗?

这种尝试一下就能得出结果的问题，就不要挖坟了

欢迎来 https://t.me/Qv2ray_chat 进行提问
