### ISSUE TITLE
请问mac 吗使用疑问：「  」

### ISSUE THREAD

**Issue by Derek-createlab** [Qv2ray/Qv2ray#1414]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

`QV_ISSUE_QUESTION_TEMPLATE_PLACEHOLDER`

### 你想做啥？
*简要描述你的最原始的目的。*

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by Firekylinxiang** [comment]
V2.6.3很稳，也能完美适配M1
