### ISSUE TITLE
使用疑问：「 请问mac m1芯片是否有相应的arm版本更新（在2.7.0中没找到） 」

### ISSUE THREAD

**Issue by Derek-createlab** [Qv2ray/Qv2ray#1415]
**请删掉下面一行内容，未删掉的 Issue 将会直接被 bot 关闭**

`QV_ISSUE_QUESTION_TEMPLATE_PLACEHOLDER`

### 你想做啥？
*简要描述你的最原始的目的。*

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by dyhkwong** [comment]
显然是没有的 https://github.com/Qv2ray/Qv2ray/issues/1263

**Comment by Derek-createlab** [comment]
> 显然是没有的 #1263

好的谢谢
