### ISSUE TITLE
使用疑问：「 报错：无效的透明代理IPv4监听地址 」

### ISSUE THREAD

**Issue by November-12** [Qv2ray/Qv2ray#1416]
### 你想做啥？

<img width="644" alt="WX20210419-112453@2x" src="https://user-images.githubusercontent.com/10138778/115177735-687d9800-a102-11eb-8291-321ef362c1a4.png">

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by November-12** [comment]
你目前试了啥？
 
删除重装无效。
下载最新的v2.7.0-pre2版本也有同样提示。

**Comment by cubercsl** [comment]
@November-12 检查一下你的入站设置里的任意门设置

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/115178209-649e4580-a103-11eb-9590-5073026dff0b.png)
这个问题在修了

**Comment by DuckSoft** [comment]
修了。

**Comment by November-12** [comment]
感谢两位，问题已解决:）
