### ISSUE TITLE
开机未联网时仍然更新订阅

### ISSUE THREAD

**Issue by IlO0OlI** [Qv2ray/Qv2ray#1422]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
设置了一天更新一次订阅。工作场地没有无线网，笔记本电脑上网需要手动插网线，经常出现开机未联网时订阅，然后提示0条，是否删除。

## 如何触发这个 Bug：

1. 
2. 
3. 
4. 

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
只有q2ray有着问题

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.7.0-pre2:6150
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-4cc95cb2f686250c899a04969e1a220af449908d-ci.windows-latest
```

### 操作系统

- Windows

### 安装来源

- Github Release 
## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
首先这个问题恐怕只有在开机自动启动、并且开启了“安静模式”时才会有这个问题。
在开启安静模式的情况下，更新订阅不会询问用户是否要更新，而是会直接进行更新：
https://code.qv2ray.net/dev/qv2ray/src/ui/widgets/windows/w_MainWindow_extra.cpp.html#157

这个情况实属预期。

建议您关闭安静模式，或者不要设置开机自动启动，即可解决此问题。
或者若您有更好的思路，欢迎直接提交代码。
