### ISSUE TITLE
why this section havent select sign?

### ISSUE THREAD

**Issue by dawoodiran** [Qv2ray/Qv2ray#1426]
hi 
why this section havent tick ?

*Please hide your server address and UUID if you wish to post the vmess string or your connection setting.*
![Untitled2](https://user-images.githubusercontent.com/34414138/115774910-6c8e0c00-a3c7-11eb-85e2-a039a5d2194a.png)
![Untitled](https://user-images.githubusercontent.com/34414138/115774927-70ba2980-a3c7-11eb-8e3d-437f37986d4d.png)

**Comment by DuckSoft** [comment]
It's one-time action, not a status indicator.
Qv2ray doesn't know what the exact status of your system, and refrains from looking at your system proxy settings all the time.
