### ISSUE TITLE
When a DNS is defined in Qv2ray, it does not work, it is ignored.

### ISSUE THREAD

**Issue by talesam** [Qv2ray/Qv2ray#1428]
I'm using version 2.7.0-pre2: 6195. It does not work with the stable version 2.6. I have already tested several times to configure the DNS and always take the DNS from the server and do not take the DNS defined locally in Qv2ray.

**Comment by DuckSoft** [comment]
Respect is mutual. If you don't spend a few minutes carefully filling in detailed information based on the template that can help the developer reproduce the situation you describe, the developer will not spend a second on your problem. 

——Victoria Raymond
