### ISSUE TITLE
DNS settings do not work in Qv2ray

### ISSUE THREAD

**Issue by talesam** [Qv2ray/Qv2ray#1429]
**Please, if there is any information missing, be cordial, I am willing to help, tell me the information you need and I will give it to you.**

I'm using version 2.7.0-pre2: 6195. It does not work with the stable version 2.6. I have already tested several times to configure the DNS and always take the DNS from the server and do not take the DNS defined locally in Qv2ray.

**DNS set to 1.1.1.1**
![Captura de tela de 2021-04-22 20-57-51](https://user-images.githubusercontent.com/981368/115798959-d8fc1180-a3ad-11eb-9fa4-92727cecdfbb.png)

**Service started**
![Captura de tela de 2021-04-22 20-58-19](https://user-images.githubusercontent.com/981368/115798983-e0bbb600-a3ad-11eb-970e-ab2f3c8b0e66.png)

**DNS being used is not the one configured, as shown on the website below:** (http://www.whatsmydnsserver.com/)
![Captura de tela de 2021-04-22 20-59-36](https://user-images.githubusercontent.com/981368/115798997-e87b5a80-a3ad-11eb-8744-dd927ca5955e.png)

**Comment by DuckSoft** [comment]
There are two types of configuration: Simple Configuration and Complex Configuration.
Simple Configuration is created by: 1) importing/subscribing nodes from url; 2) manual input
Complex Configuration is created by importing a JSON file directly.

Complex Configuration is standalone and is not affected by Global DNS Settings.
So that explains why.

**Comment by talesam** [comment]
> Existem dois tipos de configuração: Configuração Simples e Configuração Complexa.
> A configuração simples é criada: 1) importando / assinando nós do url; 2)
> A configuração complexa de entrada manual é criada: 1) importando um arquivo JSON diretamente; 2) entrada manual
> 
> A configuração complexa é autônoma e não é afetada pelas configurações globais de DNS.
> Isso explica o porquê.

The .json file has been imported and appears as a complex configuration and there is no DNS definition in it, the DNS is coming straight from the server.

**Comment by talesam** [comment]
I found a bug in version 2.7, but I will not post or I will remove it, it is not possible to import the .joson file. When the "import" button is clicked, the window to search for the file is not opened.
I can make a video showing this, by image there is no way to see it.

**Comment by DuckSoft** [comment]
@talesam It's a known one. We are working on a fix.

**Comment by DuckSoft** [comment]
So it works like that: if you want to use external JSON file, then you use the whole external JSON file.
You may customize DNS according to https://www.v2fly.org/en_US/config/dns.html, or you can do it graphically with Complex Config editor.

Or better switch to simple config. Support for Complex Config is only meant for advanced users.

**Comment by talesam** [comment]
Now I understand, thank you!
DNS only works if I use the simple configuration directly in Qv2ray, if I import the file the DNS must be configured directly on it.
