### ISSUE TITLE
使用qv2ray后无法连接signal

### ISSUE THREAD

**Issue by cephaszhu** [Qv2ray/Qv2ray#1430]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
Mac用户，signal重度使用者。但是Mac版的qv2ray连接后，其他都正常，唯有signal无法连接。换过xray、trojan-go、v2ray等协议均无效。但使用别的vpn客户端的时候可以。

## 如何触发这个 Bug：

1. 连接qv2ray上任意代理
2. 仅signal无法连接
3. 
4. 

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
没有试过其他都v2ray客户端

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 
编译信息：
额外编译信息：
```

### 操作系统

- macOS
-

### 安装来源

- Github Release / Scoop / Chocolatey

### 已安装的插件、版本及安装来源
trojan-go

## 附加信息

*请注意打码隐私相关信息。*

**Comment by dyhkwong** [comment]
according to the result from search engines, signal does not follow system proxy https://github.com/signalapp/Signal-Desktop/issues/4446

**Comment by DuckSoft** [comment]
Also, Signal banned us from their GitHub. We refuse

**Comment by xiaokangwang** [comment]
You can use the equivalent of transparent proxy in Mac OS to force buggy software to respect your proxy setting. You should report this bug to Signal and Apple.

**Comment by U-v-U** [comment]
With the defect of refusing to read system proxy settings from the OS, users are forced to use the weak, unsecured, vulnerable and detect-able [Signal-TLS-Proxy](https://github.com/signalapp/Signal-TLS-Proxy), where, however, not surprisingly, the proxy itself has been proven to be leaky many times. We have reported the problem but received lots of nonconstructive responses.

Who can tell for now if the protocol weakness is not an intended design, and who else can tell if the irrationality from the maintainers is intended or not?

**The Internet is build for people, not for profiting.**
