### ISSUE TITLE
Qv2ray不是在NTP支持下构建的

### ISSUE THREAD

**Issue by handsomeyzz** [Qv2ray/Qv2ray#1431]
## Qv2ray不是在NTP支持下构建的
系统win10,时间校正一样，但是联网对时时，发现了这个错误，暂时没有在其他的地方找到好的解决方案。请大佬们帮忙解决指正一下。

**Comment by cubercsl** [comment]
这不是错误，只是 Qv2ray 内置的时间校正功能已经被移除。如需使用，可以自行打开相关编译参数。

**Comment by handsomeyzz** [comment]
好的   谢谢您。我在检查一下错误。

**Comment by handsomeyzz** [comment]
> 这不是错误，只是 Qv2ray 内置的时间校正功能在默认情况下已默认禁用，即官方构建的版本没有内置时间校正功能。如需使用，可以自行打开相关编译参数自行构建。或者直接使用系统的时间校正。



> 这不是错误，只是 Qv2ray 内置的时间校正功能在默认情况下已默认禁用，即官方构建的版本没有内置时间校正功能。如需使用，可以自行打开相关编译参数自行构建。或者直接使用系统的时间校正。

好的 谢谢您。我重新检查一下错误。
