### ISSUE TITLE
使用疑问：「更新以后节点可使用 无法复制到其他组 错误代码sni does not exist」

### ISSUE THREAD

**Issue by stationofldyc** [Qv2ray/Qv2ray#1432]
想要正常使用节点
没有类似的issue，版本是actions里最新的win64版

**Comment by DuckSoft** [comment]
猜测是 Trojan-Go 节点的 SNI 项目没填。请右键点有问题的节点，然后把域名复制粘贴进SNI的框框里点确定即可。

**Comment by stationofldyc** [comment]
> 猜测是 Trojan-Go 节点的 SNI 项目没填。请右键点有问题的节点选编辑，然后把域名复制粘贴进SNI的框框里点确定即可。

是vmess，而且填上了还是一样

**Comment by DuckSoft** [comment]
请提供首选项——关于窗口中的版本信息。
