### ISSUE TITLE
提示当前用户没有V2Ray核心控制文件的可执行权限

### ISSUE THREAD

**Issue by jinxiangwzh** [Qv2ray/Qv2ray#1434]
我通过chmod +x v2ray 添加权限 还是报这个错误

**Comment by U-v-U** [comment]
@jinxiangwzh try chmod against v2ctl

**Comment by DuckSoft** [comment]
1. 若使用 Xray 核心，记得至少升级到 v2.7.0-pre2，因为 v2.6.3 的稳定版刚出来的时候还没有 Xray Core 这个东西呢。
2. 若使用 V2Ray 核心，核心控制文件是 `v2ctl`，不是 `v2ray`。
