### ISSUE TITLE
linux版默认分组删除后下次开启会加回来

### ISSUE THREAD

**Issue by leoxxx** [Qv2ray/Qv2ray#1441]
## 系统信息
 Kernel: 5.4.0-72-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Xfce 4.14.2 
           tk: Gtk 3.24.13 wm: xfwm4 dm: LightDM Distro: Linux Mint 20.1 Ulyssa 
           base: Ubuntu 20.04 focal

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray from manual build
额外编译信息：Qv2ray 2.6.3:5840
```

### 操作系统

- Linux Mint 20.1 Ulyssa 

### 安装来源
Github Release / https://github.com/Qv2ray/Qv2ray/releases/download/v2.6.3/qv2ray_2.6.3-1stable1_amd64.deb

**Comment by DuckSoft** [comment]
有意而为之，目前节点不能脱离分组而存在。你可以把默认分组改名，但不能删除默认分组。
