### ISSUE TITLE
2.6.3无法导入VLESS连接

### ISSUE THREAD

**Issue by leoxxx** [Qv2ray/Qv2ray#1443]
简单描述这个 Bug:
如图
![QQ截图20210501100625](https://user-images.githubusercontent.com/5364709/116767823-2db22300-aa65-11eb-953a-1eb8ce59e427.png)

https://github.com/XTLS/Xray-core/issues/91
连接用的是这里的。另外测试过网上找到的一些连接，结果一样。连接在安卓的其它软件里能正常导入。

**Comment by AkinoKaede** [comment]
@leoxxx 请使用 2.7.0-pre2

**Comment by DuckSoft** [comment]
大哥，2.6.3 的时候，Xray 还没出生咧....
请使用2.7.0-pre2及以后版本获得更好的使用体验。

**Comment by leoxxx** [comment]
Qv2ray v2.6.3
本次更新重点：

    新增 VLESS 协议配置
    修复部分启动问题和崩溃问题
    显式静态链接了 libuvw

问题修复

    修复 Core 权限弹窗 QStringBuilder 溢出问题
    修复 Windows退出时崩溃问题
    修复导入链接时乱续问题
    修复新版 KDE 的 XDG_SESSION_DESKTOP 无法识别问题
    修复新版 vmess:// 分享链接解析器细节问题
    修复网络异常时检查更新导致的崩溃问题
    修复首选项 “最近连接数量” 设置 UI 数据不正确问题
    修改 Enable Proxy 文案为 Force Direct for All Connections
    修复 PreInitializationFailed
    修复避免重复弹出 “找不到语言文件” 问题

新增内容

    新增 Log 窗口现已使用等宽字体
    新增 SS 插件，支持更多协议和 SIP003
    新增 V2Ray 核心输出检查，避免将其他核心设置在这里
    新增 VLESS 协议支持
    新增 zh_TW 翻译
    新增一键折叠所有组
    新增组编辑器新建组后即选中组

这个CHANGELOG里说的啥意思？另外我看V2RAY也有写着加入了VLESS。

**Comment by AkinoKaede** [comment]
@leoxxx 没有支持 VLESS 分享链接

**Comment by DuckSoft** [comment]
您请注意，支持VLESS不等同于当时VLESS的分享链接标准已经推出并获支持。这个分享链接的方案是我提出的不假，也是我自己在后续的版本里加入的支持，请予理解。
