### ISSUE TITLE
Bug Report: 按照指引安装并配置后依然没有连接成功(log没有报错)

### ISSUE THREAD

**Issue by LeopoldACC** [Qv2ray/Qv2ray#1450]
### Summary
按照指引安装并配置后依然没有连接成功

### Expected behavior
解决连接问题

### How to Reproduce
我的系统环境
```
ubuntu20.04 
```
我的安装步骤
- 通过snap安装
```shell
sudo snap install qv2ray
```
- 配置v2ray核并验证
![image](https://user-images.githubusercontent.com/44536699/116806309-a21cbd00-ab5e-11eb-8d50-faa8c047881f.png)
![image](https://user-images.githubusercontent.com/44536699/116806315-aea11580-ab5e-11eb-9593-e4e4f6677c60.png)
![image](https://user-images.githubusercontent.com/44536699/116806167-e0fe4300-ab5d-11eb-8737-9f3618197f18.png)
- 配置连接配置文件
![image](https://user-images.githubusercontent.com/44536699/116806263-671a8980-ab5e-11eb-85d2-423a9c4b1bc1.png)
![image](https://user-images.githubusercontent.com/44536699/116806273-7994c300-ab5e-11eb-8160-2f3b82756cb1.png)
- 设置代理
![image](https://user-images.githubusercontent.com/44536699/116806386-3c7d0080-ab5f-11eb-8e06-0a64741839a3.png)
![image](https://user-images.githubusercontent.com/44536699/116806393-4999ef80-ab5f-11eb-9916-a7676a8c272e.png)

### Add info
我的连接配置和我windows上是一致的，windows上可以连接成功

**Comment by DuckSoft** [comment]
请在连接到节点的情况下使用此命令，并将输出或截图贴上：
```bash
curl -x http://127.0.0.1:8889 -sSLv https://www.google.com/
```
