### ISSUE TITLE
V2ray-core

### ISSUE THREAD

**Issue by 18108474247** [Qv2ray/Qv2ray#1454]
点击检查 V2Ray 核心设置按钮后，显示当前用户没有 V2Ray 核心控制文件的可执行权限。Qv2ray 尝试设置，但由于权限不足，操作已失败。

**Comment by DuckSoft** [comment]
您这操作系统、软件版本也不说，俺可不会算命。
Issue 仅用于报告 Bug，使用疑问请移步 Discussion。
