### ISSUE TITLE
Bug Report: Snapcraft GNOME System Proxy doesn't take effect

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#1467]
### Summary
Ubuntu 21.04 (Hirsute Hippo), Snapcraft `beta` channel, GNOME Desktop Environment. 
System Proxy will not apply.

### Expected behavior
System Proxy should have applied.

### How to Reproduce
1. Right click Tray Menu.
2. System Proxy -> Set System Proxy.
3. Open GNOME Settings - System Proxy is NOT set.

### Screenshots
* Qv2ray Logs when setting up proxy: ![图片](https://user-images.githubusercontent.com/7822648/117573355-f3eab780-b109-11eb-9c72-852f0fee624b.png)
* `gsettings` output after setting up proxy: 
![图片](https://user-images.githubusercontent.com/7822648/117573364-05cc5a80-b10a-11eb-80e8-abec1898fa9e.png)

### Additional Info
Native version from https://qv2ray.net/debian-dev/ works fine. I guess there is something wrong with that Snapcraft Sandbox Isolation.

**Comment by lzyang2000** [comment]
affected user here, happy to provide any details

**Comment by ymshenyu** [comment]
@lzyang2000 Please check out whether the `network-manager` interface is connected with `snap connections qv2ray`

**Comment by lzyang2000** [comment]
Yes, the outputs are:
```
network                qv2ray:network          :network                        -
network-bind           qv2ray:network-bind     :network-bind                   -
network-control        qv2ray:network-control  :network-control                -
network-manager        qv2ray:network-manager  :network-manager                -

```

**Comment by ymshenyu** [comment]
It might be an upstream issue related to snapd (or ubuntu?). Please follow up on this [topic](https://forum.snapcraft.io/t/network-manager-interface-not-work-properly-on-ubuntu-21-04/24339) at the snapcraft forum.

**Comment by ypo777** [comment]
I am also affected but not on ubuntu using MacOS Qv2ray client. When I enable system proxy, it enables proxy without assigning host address only port number in system preferences. 
Qv2ray Version : 2.6.3:5840

**Comment by DuckSoft** [comment]
> I am also affected but not on ubuntu using MacOS Qv2ray client. When I enable system proxy, it enables proxy without assigning host address only port number in system preferences. 
> 
> Qv2ray Version : 2.6.3:5840

This is a different and duplicate issue and is already resolved  in the dev branch by @dyhkwong. Usually, this is caused by turning off HTTP inbound manually. Re-enabling HTTP inbound can be a makeshift plan for old version users. Extra details can be discussed in Discussion.

**Comment by cxiaolng** [comment]
这个问题啥时候能解决。同样版本，同样环境，同样的问题
