### ISSUE TITLE
Bug Report: Plugin Loader will error on *.conf

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#1470]
### Summary
Qt automatically generates *.conf for builtin plugin DLLs on Windows. Every time Qv2ray runs, the file is automatically generated and next time you open Qv2ray, the error will occur.

### Expected behavior
Don't load *.conf files.

### How to Reproduce
1. Download a clean release and extract.
2. Run it, then close it.
3. Run it --- the dialog appears.

### Screenshots
![图片](https://user-images.githubusercontent.com/7822648/117642813-54d1c880-b1ba-11eb-8ca3-b4ffef8a0fee.png)

### Additional Info
_Add any other context about the problem here._

**Comment by DuckSoft** [comment]
This can be fixed by https://github.com/Qv2ray/Qv2ray/pull/1472.
Thanks @dyhkwong.

**Comment by dyhkwong** [comment]
For the record the affected user is not using the proper version of plugins.
