### ISSUE TITLE
Bug Report: qv2ray: error while loading shared libraries: libprotobuf.so.26: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tranhoangcore** [Qv2ray/Qv2ray#1484]
**Distro**
Archlinux
https://aur.archlinux.org/packages/qv2ray-dev-git/

``
qv2ray: error while loading shared libraries: libprotobuf.so.26: cannot open shared object file: No such file or directory
``

Protobuf has upgraded to the new version.
https://archlinux.org/packages/extra/x86_64/protobuf/
Thank you.

**Comment by cubercsl** [comment]
@tranhoangcore If you manually build qv2ray-dev-git from aur, you have to rebuild it after soversion bump of protobuf.

```
❯ ldd /usr/bin/qv2ray | grep libprotobuf
        libprotobuf.so.27 => /usr/lib/libprotobuf.so.27 (0x00007f723e30e000)
```

Or you can install our official [prebuild binary](https://repo.archlinuxcn.org/x86_64/qv2ray-dev-git-2.7.0.6216.r2998.8a91348a-1-x86_64.pkg.tar.zst
) in [archlinuxcn](https://github.com/archlinuxcn/repo).

**Comment by DuckSoft** [comment]
It is common sense that you should rebuild your own -git AUR packages, and should never flag out of date for -git package.
