### ISSUE TITLE
Bug Report: qv2ray did not quit normally

### ISSUE THREAD

**Issue by tlsalex** [Qv2ray/Qv2ray#1487]
### Summary
_A clear and concise description of what the bug is._
When I quit Qv2ray from GUI, it still runs in background. I can see it by  ps -ef | grep v2ray , and my connection is still proxied.

### Expected behavior
_A clear and concise description of what you expected to happen._
qv2ray will stop running completely

### How to Reproduce
_Steps to reproduce the behavior._
start Qv2ray , then click on qv2ray icon on top left location , it will pop up a menu , then click quit.

### Screenshots
_If applicable, add screenshots to help explain your problem._

![issue](https://user-images.githubusercontent.com/36788337/118365423-568ef800-b5cf-11eb-81d8-dc9079beb6a9.png)

### Additional Info
_Add any other context about the problem here._
```
Init] High DPI scaling is enabled. 
[BaseApplication] Qv2ray 2.7.0-pre2 on Fedora 34 (Workstation Edition) x86_64 
[BaseApplication] Qv2ray Start Time:  80575383 
[BaseApplication] QV2RAY_BUILD_INFO Qv2ray built from Github Action 
[BaseApplication] QV2RAY_BUILD_EXTRA_INFO qt5.15.0-4cc95cb2f686250c899a04969e1a220af449908d-ci.ubuntu-16.04 
[BaseApplication] QV2RAY_BUILD_NUMBER 6150 
[BaseApplication] This program comes with ABSOLUTELY NO WARRANTY.
```

**Comment by MarksonHon** [comment]
@tlsalex http://qv2ray.net/faq/#behavior-appearance-issues

You should quit Qv2ray by Tray Menu or Ctrl + Q

**Comment by tlsalex** [comment]
Ctrl + Q works , but not quite get this way "quit Qv2ray by Tray Menu" , Hope some one could provide me a screenshot.

**Comment by dyhkwong** [comment]
Some desktop environments like vanilla GNOME have no tray support. In fact, Qv2ray minimizes to tray instead of exiting when the close button clicked (or the "quit" clicked). Install a tray extension yourself or check this commit e38bae093a5517004d78da12225cf654bafb8b89 instead.
