### ISSUE TITLE
Bug Report: port is occupied by another process

### ISSUE THREAD

**Issue by ahbanavi** [Qv2ray/Qv2ray#1502]
### Summary
Qv2ray says port is occupied by another process but i can't find it with netstat

### Expected behavior
It should starts correctly

### Screenshots
![image](https://user-images.githubusercontent.com/39927312/119215730-d7288980-bae4-11eb-9708-48213bf6b0a3.png)
  
![image](https://user-images.githubusercontent.com/39927312/119215754-ec9db380-bae4-11eb-8873-ff9fe7ba9c39.png)

**Comment by MarksonHon** [comment]
@ahbanavi Set socks port and HTTP port to over 10000, such as 10086, 12306, this is a problem of windows 10

**Comment by ahbanavi** [comment]
Thx, that fixed this issue for now.
I wonder if that is OK when i restart my pc.
