### ISSUE TITLE
macOS "V2Ray 核心设置不正确。"

### ISSUE THREAD

**Issue by raginghimalaya** [Qv2ray/Qv2ray#1512]
通过brew安装。
版本 2.6.3:5840
核心 4.39.2
其实核心版本早就开始不正确了（4.34.0 是可用的，但是我不想回滚，嘿嘿），似乎是因为v2ray文件在某次更新后变小了（是非常小），然后判定为不合法？
另一台Windows并没有这个问题。

**Comment by Sinofine** [comment]
duplicate of #1340

**Comment by cubercsl** [comment]
你应该使用 `2.7.0-pre2` 版的 qv2ray. 因为众所周知的原因, homebrew 不收 pre-release 包,你需要从 https://github.com/kidonng/homebrew-malt 找 beta 版的 qv2ray.

**Comment by raginghimalaya** [comment]
哦哦，搜素没搜到，我的，关了
