### ISSUE TITLE
Bug Report: not user it's browser issue or qv2ray issue -- strange url appears in qv2ray

### ISSUE THREAD

**Issue by tlsalex** [Qv2ray/Qv2ray#1514]
### Summary
_A clear and concise description of what the bug is._
Each time I start qv2ray , then connect to my server , then start my browser to do web browsing , it will pop up bellow error in the log area.
```
2021/05/28 22:25:23 [Warning] [2689119830] proxy/http: failed to read response from yooklqtdyxulpc > io: read/write on closed pipe
2021/05/28 22:25:23 [Warning] [2126989354] proxy/http: failed to read response from hxgdafs > io: read/write on closed pipe
2021/05/28 22:25:23 127.0.0.1:37800 accepted //edge.activity.windows.com:443 [PROXY]
2021/05/28 22:25:24 [Warning] [3546635048] proxy/http: failed to read response from mmrhbdpmwx > io: read/write on closed pipe
```

### Expected behavior
_A clear and concise description of what you expected to happen._
no error logs should occur.

### How to Reproduce
_Steps to reproduce the behavior._
env: Fedora 34 , microsoft edge browser.

start qv2ray , then connect to my server , then start my browser to do web browsing

### Screenshots
_If applicable, add screenshots to help explain your problem._
![error](https://user-images.githubusercontent.com/36788337/119999924-dcb23200-c004-11eb-83a6-50a1f52c1a86.png)

### Additional Info
_Add any other context about the problem here._

**Comment by Sinofine** [comment]
@tlsalex is your browser edge?
If that's true, it's edge that's to blame.
Chromium-based browsers tried random url connection to check DNS poisonings.
It's normal.

**Comment by dyhkwong** [comment]
This is a Chromium "feature", not a Qv2ray bug. https://unix.stackexchange.com/a/363513
