### ISSUE TITLE
ss其中加密方法中没有xchacha20-ietf-poly1305 2.6.3

### ISSUE THREAD

**Issue by PoseidonLi0514** [Qv2ray/Qv2ray#1519]
ss其中加密方法中没有xchacha20-ietf-poly1305 2.6.3

**Comment by Sinofine** [comment]
@adehcby 请安装sip003插件，谢谢

**Comment by PoseidonLi0514** [comment]
> @adehcby 请安装sip003插件，谢谢

哦好我去看看

**Comment by PoseidonLi0514** [comment]
> @adehcby 请安装sip003插件，谢谢

https://github.com/Qv2ray/QvPlugin-SS/releases/download/v1.3/QvPlugin-SS.v1.3.linux-x64.so 用的就是这个也加载了

**Comment by Sinofine** [comment]
@adehcby 在节点类型那里不要选shadowsocks，选SIP003

**Comment by PoseidonLi0514** [comment]
> @adehcby 在节点类型那里不要选shadowsocks，选SIP003

哦好可以了谢谢
