### ISSUE TITLE
Bug Report: OpenSUSE TumbleWeed qv2ray: symbol lookup error:

### ISSUE THREAD

**Issue by dxyzx0** [Qv2ray/Qv2ray#1527]
### Summary
_A clear and concise description of what the bug is._
qv2ray 无法启动。
qv2ray: symbol lookup error:

### Expected behavior
_A clear and concise description of what you expected to happen._
正常启动。

### How to Reproduce
_Steps to reproduce the behavior._
sudo zyyper dup
更新到最新版 opensuse-tumbleweed-20210601
使用的是 qv2ray-dev
经过实验 kde 和 xfce 都挂了。

### Screenshots
_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/28868457/120703243-a0d90a00-c4e7-11eb-94cb-44d4c286553d.png)

### Additional Info
_Add any other context about the problem here._

**Comment by zzndb** [comment]
是由于 0527 开始使用 gcc11 构建而 qv 的直接依赖 gPRC 没能构建成功带来的问题，目前 gRPC 的构建已[修复](https://build.opensuse.org/package/rdiff/devel:tools/grpc?linkrev=base&rev=96) ，修复变更也已[提交](https://build.opensuse.org/request/show/897022)进入到 Factory。不过目前（Fri Jun  4 07:24:25 2021）新版的 gRPC 构建暂时[受阻](https://build.opensuse.org/package/show/openSUSE:Factory/grpc)（受其依赖），想来也不会等太久就是了，等待之后的更新就好。

---

建议留意一些可能的通知渠道：
https://suse.org.cn/%E6%9B%B4%E6%96%B0%E9%80%9A%E5%91%8A/2021/06/03/Tumbleweed-%E9%87%8D%E8%A6%81%E6%9B%B4%E6%96%B0%E9%80%9A%E5%91%8A.html
https://forum.suse.org.cn/t/topic/13923
https://lists.opensuse.org/archives/list/users-zh@lists.opensuse.org/thread/2FWRHY5CV7AEFVC6CRBSIHRR7SDZYUNW/

**Comment by zzndb** [comment]
已恢复构建，大概更新一下就好了，如果遇到依赖问题……大概就需要等一下个快照了（大概是0602？）
