### ISSUE TITLE
Bug Report: Build Failed under gcc11.1.0

### ISSUE THREAD

**Issue by TomCC7** [Qv2ray/Qv2ray#1532]
### Summary
Build failed under gcc11.1.0.
The key failure is
```bash
../3rdparty/zxing-cpp/core/src/oned/ODRowReader.h:179:37: error: ‘numeric_limits’ is not a me
mber of ‘std’
```
### Expected behavior
Build success.

### How to Reproduce
Under gcc11.1.0
```
cmake .. \
  -DCMAKE_INSTALL_PREFIX=${pkgdir}/usr \
  -DQV2RAY_ZXING_PROVIDER="module" \
  -DQV2RAY_TRANSLATION_PATH="/usr/share/qv2ray/lang" \
  -DQV2RAY_DEFAULT_VASSETS_PATH="/usr/share/v2ray" \
  -DQV2RAY_DEFAULT_VCORE_PATH="/usr/bin/v2ray" \
  -DQV2RAY_DISABLE_AUTO_UPDATE=on \
  -DCMAKE_BUILD_TYPE=Release \
  -GNinja
ninja
```

### Additional Info
My temporary solution is open the ODRowReader.h file and add header
```c++
#include <limit>
```

**Comment by cubercsl** [comment]
@TomCC7 #1494

Upstream has fixed this problem.

Some affected packaging scripts have been patched and the dev branch now has deprecated zxing-cpp.

We may not fix this issue again.
