### ISSUE TITLE
使用pacman更新2.6.3-27后，提示缺少动态库

### ISSUE THREAD

**Issue by sharkocha** [Qv2ray/Qv2ray#1535]
使用pacman更新2\.6\.3\-27后，打开出现error，提示缺少libgrpc\+\+\.so\.1\.38

**Comment by cubercsl** [comment]
请提供你的操作系统，安装 qv2ray 的方式和来源。以及不要只更新 qv2ray 不更新 grpc。

@lfishRhungry 求助者日常失踪，还是我热脸贴冷屁股？

**Comment by sharkocha** [comment]
> 请提供你的操作系统，安装 qv2ray 的方式和来源。以及不要只更新 qv2ray 不更新 grpc。
> 
系统是manjaro 使用pacman更新 我本想使用pacman更新grpc 但是pacman中的grpc没有这么新的版本

**Comment by ghost** [comment]
建议使用 [Manjaro CN 源](https://github.com/manjarocn/repo) 或者使用 AUR 构建.

**Comment by cubercsl** [comment]
请参考 #1365 #1085 #1073 #1069 #1059 #1047 #1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032 等 Issue。不要在 manjaro 中使用 archlinuxcn 仓库。

**Comment by sharkocha** [comment]
> 请参考 #1365 #1085 #1073 #1069 #1059 #1047 #1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032 等 Issue。不要在 manjaro 中使用 archlinuxcn 仓库。

好的 我明天试试 感谢

**Comment by tyn1998** [comment]
## 涉及到的版本
现在是2021年6月9日下午4点，软件源中的最新版本是：
- qv2ray 2.6.3-27（archlinuxcn）
- grpc 1.36.4-2（Manjaro官方）
- protobuf 3.16.0-1（Manjaro官方）

亲测可用版本组合：
- qv2ray 2.6.3-**22**（archlinuxcn）
- grpc 1.36.4-2（Manjaro官方）
- protobuf 3.**15.6-1**（Manjaro官方）

## 用本地余留的旧包降级
1. 进入旧包目录：/var/cache/pacman/pkg
2. 找到对应版本的以`.zst`结尾的包，双击可以调用系统的软件管理器进行降级

## 成功后别忘了给权限
我是配合cgproxy用透明代理的，下面这个可能不管用不用透明代理都要：
`sudo setcap "cap_net_admin,cap_net_bind_service=ep" /usr/bin/v2ray`

## 再说点
可能你的本地旧包版本不一样，但是如果之前qv2ray能用的话，肯定有个可行的组合，多试试！

祝你成功！
