### ISSUE TITLE
Bug Report: 无法加载插件： /usr/share/qv2ray/plugins/QvPlugin-SS.v1.3.linux-x64.so

### ISSUE THREAD

**Issue by vivalavida54** [Qv2ray/Qv2ray#1538]
无法加载插件： 
/usr/share/qv2ray/plugins/QvPlugin-SS.v1.3.linux-x64.so

系统是archlinux 
软件aur仓库的dev版

**Comment by cubercsl** [comment]
@indigoch 经典插件版本与软件版本不匹配，请从正确渠道安装适配版本的插件。

**Comment by vivalavida54** [comment]
原来是这么回事,要下载dev版的插件
