### ISSUE TITLE
网站添加CDN后订阅地址无法更新出节点

### ISSUE THREAD

**Issue by xiaozhu0232** [Qv2ray/Qv2ray#1544]
**Summary**
网站添加CDN后订阅地址无法更新节点
显示都是0
测试了2.7 和2.6 都不可以更新出节点
版本2.6.3:5840

同样的订阅地址   IOS 小飞机和v2rayN-Core 可以更新出节点！！！

**Comment by xiaozhu0232** [comment]
> 网站添加CDN后订阅地址无法更新出节点
> 几点显示都是0
> 测试了2.7 和2.6 都不可以更新出节点
> 同样的订阅地址 IOS 小飞机和v2rayN-Core 可以更新出节点！！！

**Comment by ardenwick** [comment]
咋关了 issue，问题解决了吗？

**Comment by xiaozhu0232** [comment]
> 咋关了问题，问题解决了吗？
不会操作，没有解决！更新不出订阅地址的节点

**Comment by ardenwick** [comment]
其他客户端都能订阅，Qv2ray 应该也可以的。进 [Qv2ray 群](https://t.me/Qv2ray_chat)  来看看。

**Comment by ardenwick** [comment]
先检查两个设置：
1、订阅分组的订阅类型：
![image](https://user-images.githubusercontent.com/50256182/121113281-58ea1800-c844-11eb-8796-9dffd5b778e3.png)

2、代理设置，如果订阅链接本身需要翻墙才能访问的话，需要设置这个：
![image](https://user-images.githubusercontent.com/50256182/121113211-37892c00-c844-11eb-8189-c42465d61e24.png)

**Comment by xiaozhu0232** [comment]
Qv2ray代理 使用系统代理，开其他代理，可以更新出节点。
如果不使用代理，不开其他代理软件。更新不了节点。

**Comment by ardenwick** [comment]
"
Qv2ray代理 使用系统代理，并打开其他代理软件，Qv2ray可以更新出节点。
如果不使用代理，不开其他代理软件。更新不了节点。
"
是这个意思吧。

你想想，Qv2ray 为什么要加这个设置功能，而其他代理软件没有？
（心好累，你在群里问问题，别人都开始帮你诊断了，给点反馈啊老哥。）

**Comment by xiaozhu0232** [comment]
单独使用Qv2ray，订阅地址更新不了节点的。
使用V2rayN可以的
开启V2rayN， 配置Qv2ray系统代理，可以更新节点了。
是域名被禁了吗？
域名使用CDN了。
