### ISSUE TITLE
Bug Report: 在windows左下角，这里使用了绿色和蓝色，但是因为图标显示非常小，某些显示器上不仔细看，看不出来是什么颜色，建议修改成不同的位置，例如：全局模式的点在图形的左上角。

### ISSUE THREAD

**Issue by kimkata** [Qv2ray/Qv2ray#1552]
![图片](https://user-images.githubusercontent.com/20291320/121796139-7f93be80-cc49-11eb-81cc-aaf8a4e07d0f.png)

### Summary
_A clear and concise description of what the bug is._

### Expected behavior
_A clear and concise description of what you expected to happen._

### How to Reproduce
_Steps to reproduce the behavior._

### Screenshots
_If applicable, add screenshots to help explain your problem._

### Additional Info
_Add any other context about the problem here._

**Comment by dyhkwong** [comment]
duplicate #551 and contributions welcome.

**Comment by ardenwick** [comment]
建议更新到 dev 版本，托盘图标是这样的
![image](https://user-images.githubusercontent.com/50256182/121837565-7f0e2d00-cd08-11eb-9926-07b8be241a1c.png)
