### ISSUE TITLE
Bug Report: 更新Manjaro后依赖关系出错

### ISSUE THREAD

**Issue by OnionCutter** [Qv2ray/Qv2ray#1554]
qv2ray: error while loading shared libraries: libabsl_hash.so.2103.0.1: cannot open shared object file: No such file or directory

**Comment by cubercsl** [comment]
@teojoy 请参考 #1365 #1085 #1073 #1069 #1059 #1047 #1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032 等 Issue。不要在 manjaro 中使用 archlinuxcn 仓库。

**Comment by cubercsl** [comment]
> @teojoy 请参考 #1365 #1085 #1073 #1069 #1059 #1047 #1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032 等 Issue。不要在 manjaro 中使用 archlinuxcn 仓库。

使用 AUR 请自己重新编译。

**Comment by OnionCutter** [comment]
> @teojoy 请参考 #1365 #1085 #1073 #1069 #1059 #1047 #1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032 等 Issue。不要在 manjaro 中使用 archlinuxcn 仓库。
感谢您的解决方案！
