### ISSUE TITLE
搭建好了 用不了 看看什么毛病？求解惑 failed to read response from ctldl.windowsupdate.com > io: read/write on closed pipe

### ISSUE THREAD

**Issue by uiydfd** [Qv2ray/Qv2ray#1555]
021/06/16 02:36:29 127.0.0.1:51767 accepted //browser.360.cn:443 [proxy]
2021/06/16 02:37:17 [Warning] [3119145197] github.com/v2fly/v2ray-core/v4/proxy/http: failed to read response from ctldl.windowsupdate.com > io: read/write on closed pipe
2021/06/16 02:42:17 127.0.0.1:51792 accepted http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/authrootstl.cab?05f4bd596e68d59e [proxy]
2021/06/16 02:43:17 [Warning] [2381912060] github.com/v2fly/v2ray-core/v4/proxy/http: failed to read response from ctldl.windowsupdate.com > io: read/write on closed pipe
2021/06/16 02:46:38 127.0.0.1:51815 accepted http://bg5.v4.emdl.ws.microsoft.com/emdl/d/2018/07/abm_e00bd13d03c2b269ef5bba9693ec93495980bfe1.cab [proxy]
2021/06/16 02:47:34 127.0.0.1:51824 accepted http://foodanddrink.tile.appex.bing.com/api/feed/?view-name=data&name=livetile&market=zh-CN&version=2_0&format=xml [proxy]
2021/06/16 02:47:34 127.0.0.1:51825 accepted http://zh-cn.appex-rf.msn.com/cgtile/v1/zh-CN/HealthAndFitness/Home.xml?cgversion=v6 [proxy]
2021/06/16 02:47:39 [Warning] [1198355339] github.com/v2fly/v2ray-core/v4/proxy/http: failed to read response from bg5.v4.emdl.ws.microsoft.com > io: read/write on closed pipe
2021/06/16 02:47:39 127.0.0.1:51829 accepted http://bg4.v4.emdl.ws.microsoft.com/emdl/d/2019/11/abm_a46a2d8229926a0b9b9b9e8a46c8dd9a5f94fcbe.cab [proxy]
2021/06/16 02:48:35 [Warning] [600260470] github.com/v2fly/v2ray-core/v4/proxy/http: failed to read response from foodanddrink.tile.appex.bing.com > io: read/write on closed pipe
2021/06/16 02:48:35 [Warning] [168518609] github.com/v2fly/v2ray-core/v4/proxy/http: failed to read response from zh-cn.appex-rf.msn.com > io: read/write on closed pipe
2021/06/16 02:48:35 [Warning] [600260470] github.com/v2fly/v2ray-core/v4/app/proxyman/inbound: connection ends > github.com/v2fly/v2ray-core/v4/proxy/http: connection ends > github.com/v2fly/v2ray-core/v4/proxy/http: failed to write response > write tcp 127.0.0.1:2334->127.0.0.1:51824: wsasend: An existing connection was forcibly closed b

**Comment by MarksonHon** [comment]
请加入以下两个群组之一来交流搭建问题，此issue与Qv2ray无关，即将关掉。
<https://t.me/v2fly_chat>
<https://t.me/projectXray>
