### ISSUE TITLE
Bug Report: AppImage客户端按钮图标消失

### ISSUE THREAD

**Issue by NewtMa** [Qv2ray/Qv2ray#1559]
### Summary
Ubuntu 20 04上运行2.6.3 AppImage, 在误触了 "首选项" -- 关于 -- 忽略版本旁边的取消按钮后, 重启AppImage, 客户端上的所有按钮图标消失

### Expected behavior
我不太清楚那个按钮是做什么的, 但是有没有办法把那个图标弄回来??

### How to Reproduce
1. "首选项" -- 关于 -- 忽略版本旁边的取消按钮后;
2. 重启AppImage;
3. 客户端上的所有按钮图标消失.

### Screenshots

![图片](https://user-images.githubusercontent.com/48610536/122169214-ba972b80-ceaf-11eb-8f9d-18a213e6eaca.png)

![2021-06-16_14-31](https://user-images.githubusercontent.com/48610536/122169058-92a7c800-ceaf-11eb-83ba-0b763c3711ee.png)

### Additional Info
无

**Comment by dyhkwong** [comment]
无法复现。恢复方式：取消勾选“使用浅色界面图标”

ps. 请不要报告非最新 commit 版本所发生的问题
