### ISSUE TITLE
Bug Report: 在windows11中安装程序无法启动

### ISSUE THREAD

**Issue by Lynricsy** [Qv2ray/Qv2ray#1561]
### Summary
在windows11中安装程序无法启动

### Expected behavior
双击安装程序，出现NSIS error：error launching installer.

### How to Reproduce
在windows11中打开安装程序。

### Screenshots
![Snipaste_2021-06-18_16-55-23](https://user-images.githubusercontent.com/62173814/122535296-fff55d80-d055-11eb-8a99-841463a1e83e.png)

### Additional Info
_Add any other context about the problem here._

**Comment by vickwv** [comment]
这个系统都没正式发布。。。

**Comment by Lynricsy** [comment]
> 这个系统都没正式发布。。。

可是镜像已经有了，而且有不少人在用啊

**Comment by AkinoKaede** [comment]
试试 7z 的档案，不用 Installer

**Comment by dyhkwong** [comment]
已尝试可以正常安装。如果有稳定复现的环境与方法，请提供详细信息。
