### ISSUE TITLE
Bug Report: mac os12打开闪退

### ISSUE THREAD

**Issue by ivoidcat** [Qv2ray/Qv2ray#1563]
Process:               qv2ray [2776]
Path:                  /Applications/qv2ray.app/Contents/MacOS/qv2ray
Identifier:            com.github.qv2ray
Version:               2.7.0-pre2 (2.7.0-pre2)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2021-06-19 18:18:14.8249 +0800
OS Version:            macOS 12.0 (21A5248p)
Report Version:        12
Anonymous UUID:        4614992A-5F1A-F00D-A31B-00EDD1D75166

Time Awake Since Boot: 1400 seconds

System Integrity Protection: enabled

Notes:
Failed to extract dyld error info: The size of the data is not what is expected

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 9 
Assertion failed: (idx < _usedCount), function operator[], file Array.h, line 61.

Application Specific Information:

Error Formulating Crash Report:
Failed to extract dyld error info: The size of the data is not what is expected

Thread 0 Crashed:
0   dyld                          	       0x10a2feeba __abort_with_payload + 10
1   dyld                          	       0x10a314dcf abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x10a314e01 abort_with_payload + 9
3   dyld                          	       0x10a2c5199 dyld4::halt(char const*) + 375
4   dyld                          	       0x10a314595 abort_report_np + 173
5   dyld                          	       0x10a3145d2 __assert_rtn + 61
6   dyld                          	       0x10a312b3f invocation function for block in dyld4::Loader::applyFixupsGeneric(Diagnostics&, dyld4::RuntimeState&, dyld3::Array<void const*> const&, dyld3::Array<void const*> const&, bool, dyld3::Array<dyld4::Loader::MissingFlatLazySymbol> const&) const + 33
7   dyld                          	       0x10a2cef88 invocation function for block in dyld4::Loader::applyFixupsGeneric(Diagnostics&, dyld4::RuntimeState&, dyld3::Array<void const*> const&, dyld3::Array<void const*> const&, bool, dyld3::Array<dyld4::Loader::MissingFlatLazySymbol> const&) const + 233
8   dyld                          	       0x10a2f745c dyld3::MachOAnalyzer::forEachBind_OpcodesWeak(Diagnostics&, dyld3::MachOLoaded::LinkEditInfo const&, dyld3::MachOFile::SegmentInfo const*, void (char const*, dyld3::MachOLoaded::LinkEditInfo const&, dyld3::MachOFile::SegmentInfo const*, bool, bool, unsigned int, int, unsigned int, unsigned char, unsigned long long, unsigned char, char const*, bool, bool, unsigned long long, bool, bool&) block_pointer, void (char const*) block_pointer) const + 604
9   dyld                          	       0x10a2f6836 dyld3::MachOAnalyzer::forEachBindUnified_Opcodes(Diagnostics&, bool, void (unsigned long long, dyld3::MachOAnalyzer::BindTargetInfo const&, bool&) block_pointer, void (unsigned long long, dyld3::MachOAnalyzer::BindTargetInfo const&, bool&) block_pointer) const + 818
10  dyld                          	       0x10a2f7f9d dyld3::MachOAnalyzer::forEachBindLocation_Opcodes(Diagnostics&, void (unsigned long long, unsigned int, bool&) block_pointer, void (unsigned long long, unsigned int, bool&) block_pointer) const + 105
11  dyld                          	       0x10a2cebf3 dyld4::Loader::applyFixupsGeneric(Diagnostics&, dyld4::RuntimeState&, dyld3::Array<void const*> const&, dyld3::Array<void const*> const&, bool, dyld3::Array<dyld4::Loader::MissingFlatLazySymbol> const&) const + 407
12  dyld                          	       0x10a2d1716 dyld4::JustInTimeLoader::applyFixups(Diagnostics&, dyld4::RuntimeState&, dyld4::DyldCacheDataConstLazyScopedWriter&, bool) const + 534
13  dyld                          	       0x10a2c0c6d dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 1708
14  dyld                          	       0x10a2c04b4 start + 388

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x000000010864a168  rdx: 0x000000010864a5d0
  rdi: 0x0000000000000006  rsi: 0x0000000000000009  rbp: 0x000000010864a1b0  rsp: 0x000000010864a168
   r8: 0x000000010864a1d0   r9: 0x0000000000000000  r10: 0x0000000000000014  r11: 0x0000000000000246
  r12: 0x0000000000000014  r13: 0x000000010864a5d0  r14: 0x0000000000000009  r15: 0x0000000000000006
  rip: 0x000000010a2feeba  rfl: 0x0000000000000246  cr2: 0x000000010a2feeb0
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
       0x10a2bb000 -        0x10a322fff dyld (*) <4e207376-cc5d-3986-a0bd-4d09f4217e68> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=823.0M resident=0K(0%) swapped_out_or_unallocated=823.0M(100%)
Writable regions: Total=9300K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9300K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                            16.7M      293 
__DATA_CONST                      11.3M      183 
__DATA_DIRTY                       472K       86 
__FONT_DATA                          4K        1 
__LINKEDIT                       618.3M       52 
__OBJC_RO                         80.3M        1 
__OBJC_RW                         3008K        1 
__TEXT                           204.8M      311 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
shared memory                        8K        1 
===========                     =======  ======= 
TOTAL                              1.0G      936 

Model: MacBookPro11,4, BootROM 427.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2.2 GHz, 16 GB, SMC 2.29f24
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1703.6)
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi 2, AirPort, en0
Network Service: iPhone, Ethernet, en14
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
USB Device: EML-AL00
USB Device: 4-Port USB 2.0 Hub
USB Device: iPhone
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by dyhkwong** [comment]
与 #1545 重复，尝试手动编译 grpc 以及 Qv2ray？

**Comment by dyhkwong** [comment]
没有回应，且与 #1545 重复，本 issue 关闭。
