### ISSUE TITLE
Bug Report: Quiet mode doesn't work on KDE Desktop Environment

### ISSUE THREAD

**Issue by dxyzx0** [Qv2ray/Qv2ray#1566]
### Summary
On all distros with KDE installed, Qv2ray will pop up the window even if Quiet Mode is selected. on Xfce and Gnome Qv2ray works well.

### Expected behavior
Qv2ray runs in the background.

### How to Reproduce
Just start the os.

### Screenshots
![image](https://user-images.githubusercontent.com/28868457/122845856-2c9bc480-d337-11eb-9e38-9340379ec5a4.png)
Not only on OpenSUSE KDE TumbleWeed but also all of the distros with KDE installed. I tried: Debian 10, Ubuntu 20.04 LTS, Manjaro.

### Additional Info
I use Qv2ray-preview.

**Comment by cubercsl** [comment]
KDE will login with the last session by default. Please try to modify the setting to login with an empty session, enable automatic startup of qv2ray and configure the automatic connection correctly.

**Comment by dxyzx0** [comment]
@cubercsl If I want to restore the previous session, is there a way to keep Qv2ray in the background?
