### ISSUE TITLE
The plugin cannot be loaded

### ISSUE THREAD

**Issue by Yuhani20** [Qv2ray/Qv2ray#1571]
The plugin cannot be loaded:
/usr/share/qv2ray/plugins/libQvSSRPlugin.so

This plugin was built against a different version of the plugin Interface. Please contact the plugin provider or report the issue to Qv2ray Workgroup.

我的系统是arch linux，我想使用ssr代理，qv2ray稳定版本build失败，在安装了qv2ray-dev-git (aur)和qv2ray-plugin-ssr-git (aur)后, 程序提示这条信息

**Comment by MarksonHon** [comment]
@Yuhani20 你装错了 SSR 插件，用带 dev 字样的那个

**Comment by Yuhani20** [comment]
> @Yuhani20 你装错了 SSR 插件，用带 dev 字样的那个

多谢你！问题解决了
