### ISSUE TITLE
Bug Report: ubuntu下闪退

### ISSUE THREAD

**Issue by Crane-Mocker** [Qv2ray/Qv2ray#1574]
无论是点击还是tty中./x运行都立即闪退，报错unexpected error

------- BEGIN QV2RAY CRASH REPORT -------
Active Kernel Instances:
[]
Current Connection:
{"connectionId":"null","groupId":"null"}

Plugins:

GlobalConfig:
{"advancedConfig":{"setAllowInsecure":false,"setSessionResumption":false,"testLatencyPeriodcally":false},"autoStartBehavior":0,"autoStartId":{"connectionId":"null","groupId":"000000000000"},"config_version":14,"defaultRouteConfig":{"connectionConfig":{"bypassBT":false,"bypassCN":true,"dnsIntercept":false,"enableProxy":true,"v2rayFreedomDNS":false,"withLocalDNS":false},"dnsConfig":{"clientIp":"","hosts":{},"servers":[{"QV2RAY_DNS_IS_COMPLEX_DNS":false,"address":"1.1.1.1","domains":[],"expectIPs":[],"port":53},{"QV2RAY_DNS_IS_COMPLEX_DNS":false,"address":"8.8.8.8","domains":[],"expectIPs":[],"port":53},{"QV2RAY_DNS_IS_COMPLEX_DNS":false,"address":"8.8.4.4","domains":[],"expectIPs":[],"port":53}],"tag":""},"forwardProxyConfig":{"enableForwardProxy":false,"password":"","port":8008,"serverAddress":"127.0.0.1","type":"http","useAuth":false,"username":""},"overrideConnectionConfig":false,"overrideDNS":false,"overrideForwardProxyConfig":false,"overrideRoute":false,"routeConfig":{"domainStrategy":"AsIs","domains":{"block":[],"direct":[],"proxy":[]},"ips":{"block":[],"direct":[],"proxy":[]}}},"inboundConfig":{"httpSettings":{"account":{"pass":"","user":""},"port":8889,"sniffing":false,"useAuth":false},"listenip":"127.0.0.1","socksSettings":{"account":{"pass":"","user":""},"enableUDP":true,"localIP":"127.0.0.1","port":1089,"sniffing":false,"useAuth":false},"systemProxySettings":{"setSystemProxy":true},"tProxySettings":{"hasTCP":true,"hasUDP":false,"mode":"tproxy","port":12345,"tProxyIP":"127.0.0.1","tProxyV6IP":""},"useHTTP":true,"useSocks":true,"useTPROXY":false},"kernelConfig":{"enableAPI":true,"statsPort":15490,"v2AssetsPath_linux":"/media/cm/a508df67-fffc-4dc7-a57a-72fc8acab7a6/network/v2ray","v2AssetsPath_macx":"","v2AssetsPath_win":"","v2CorePath_linux":"/media/cm/a508df67-fffc-4dc7-a57a-72fc8acab7a6/network/v2ray/v2ray","v2CorePath_macx":"","v2CorePath_win":""},"lastConnectedId":{"connectionId":"dgucsbffqihn","groupId":"000000000000"},"logLevel":3,"networkConfig":{"address":"127.0.0.1","latencyTestingMethod":18903520,"port":8000,"proxyType":0,"type":"http","userAgent":"Qv2ray/$VERSION WebRequestHelper"},"outboundConfig":{"mark":255},"pluginConfig":{"pluginStates":{},"portAllocationStart":15000,"v2rayIntegration":true},"tProxySupport":false,"uiConfig":{"graphConfig":{"colorConfig":{"$0":{"value1":{"B":63,"G":196,"R":134,"style":1,"width":1.5},"value2":{"B":255,"G":153,"R":50,"style":1,"width":1.5}},"$1":{"value1":{"B":63,"G":196,"R":134,"style":1,"width":1.5},"value2":{"B":255,"G":153,"R":50,"style":1,"width":1.5}},"$2":{"value1":{"B":240,"G":210,"R":0,"style":3,"width":1.5},"value2":{"B":42,"G":220,"R":235,"style":3,"width":1.5}}},"hasDirectStats":false,"useOutboundStats":false},"language":"zh_CN","maxJumpListCount":20,"maximumLogLines":500,"quietMode":true,"recentConnections":[{"connectionId":"dgucsbffqihn","groupId":"000000000000"},{"connectionId":"jcdcdfrbjzub","groupId":"000000000000"},{"connectionId":"lfwxddfrxgwu","groupId":"000000000000"},{"connectionId":"nzngfmwyvsne","groupId":"000000000000"},{"connectionId":"yrozbsvzdypo","groupId":"000000000000"},{"connectionId":"dbwzkugnmpkz","groupId":"000000000000"},{"connectionId":"gemzwgibphwu","groupId":"000000000000"},{"connectionId":"oqinzilsipgl","groupId":"000000000000"},{"connectionId":"uyvyiwmytgjx","groupId":"000000000000"},{"connectionId":"pfwisztjmkdw","groupId":"000000000000"},{"connectionId":"ikyxupwfrnhu","groupId":"000000000000"},{"connectionId":"hfwubogjjfim","groupId":"000000000000"},{"connectionId":"fddaqrqkqpey","groupId":"000000000000"},{"connectionId":"dsfjtrpzehca","groupId":"000000000000"},{"connectionId":"gonpylnreivi","groupId":"000000000000"},{"connectionId":"zptyxajffmcl","groupId":"000000000000"},{"connectionId":"ovynocbzuuzm","groupId":"000000000000"},{"connectionId":"sucwksaarhri","groupId":"000000000000"},{"connectionId":"vbcsshpfqjog","groupId":"000000000000"},{"connectionId":"pkrocxyvxiyt","groupId":"000000000000"}],"theme":"Fusion","useDarkTheme":false,"useDarkTrayIcon":true,"useOldShareLinkFormat":true},"updateConfig":{"ignoredVersion":"2.6.3","updateChannel":0}}
------- END OF QV2RAY CRASH REPORT -------

**Comment by dyhkwong** [comment]
信息不足，且请不要报告旧版本出现的问题

ps. 
> "latencyTestingMethod":18903520
