### ISSUE TITLE
启动不起来

### ISSUE THREAD

**Issue by Fcukcpp** [Qv2ray/Qv2ray#1580]
### Summary

qv2ray: error while loading shared libraries: libprotobuf.so.28: cannot open shared object file: No such file or directoryBug Report: 

### Expected behavior
_A clear and concise description of what you expected to happen._

### How to Reproduce
_Steps to reproduce the behavior._

### Screenshots
_If applicable, add screenshots to help explain your problem._

![image](https://user-images.githubusercontent.com/66298978/124153329-e416a080-dac6-11eb-800f-b16b647b7cbc.png)
![image](https://user-images.githubusercontent.com/66298978/124153392-f1cc2600-dac6-11eb-8a63-5bd8e1adad0c.png)

### Additional Info
_Add any other context about the problem here._

**Comment by dyhkwong** [comment]
请参考 #1554 #1535 #1365 #1085 #1073 #1069 #1059 #1047 #1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032 等 Issue。不要在 manjaro 中使用 archlinuxcn 仓库。使用 AUR 请自己重新编译。

**Comment by sixg0000d** [comment]
https://forum.manjaro.org/t/my-qv2ray-can-not-run-because-not-have-libprotobuf-so-28/71687

建议尝试使用 https://github.com/manjarocn/repo
