### ISSUE TITLE
Bug Report: python pip异常

### ISSUE THREAD

**Issue by playgithub** [Qv2ray/Qv2ray#1581]
https://github.com/v2fly/v2ray-core/discussions/1112

> Qv2ray 设置系统代理的格式是 '127.0.0.1:port'，手动改成 'http://127.0.0.1:port' 形式的就没问题了。否则，Python 会把 https 协议转发到 'https://127.0.0.1:port'，然而这是个 http 代理。

**Comment by cubercsl** [comment]
@playgithub https://bugs.python.org/issue42627
https://github.com/python/cpython/pull/26307

**Comment by playgithub** [comment]
duplicate
