### ISSUE TITLE
Bug Report: macOS MoJave 不能自动设置系统代理

### ISSUE THREAD

**Issue by zmyLiuFeng** [Qv2ray/Qv2ray#1586]
不能自动设置系统代理，需要手动勾选系统设置/httpproxy/httpsproxy前面的复选框

操作系统：macOS MoJave
qv2ray版本：release per2最新版

复现方式：系统托盘中点鼠标右键，enable system proxy，
期望：能够根据preferences中设置https代理ip:port等，自动设置到系统中去
结果：没有自动设置，需要手动打开网络设置自己填写信息、勾选复选框

错误详情:
普通打开:** Error: Command requires admin privileges.
** Error: Command requires admin privileges.
** Error: Command requires admin privileges.
** Error: Command requires admin privileges.
** Error: Command requires admin privileges.
** Error: Command requires admin privileges.
[COMPONENT-PROXY]: Setting proxy for interface: ALK Mobile Boardband

root 打开则没问题

已经执行如下命令
sudo security authorizationdb write system.services.systemconfiguration.network allow

返回
YES (0)   问题依旧

**Comment by dyhkwong** [comment]
> 已经执行如下命令
> sudo security authorizationdb write system.services.systemconfiguration.network allow
> 
> 返回
> YES (0)

此处可能需要重启？

手动执行 `networksetup  -setwebproxystate 网卡名 on` 能设置上 HTTP 代理吗？

**Comment by zmyLiuFeng** [comment]
> > 已经执行如下命令
> > sudo security authorizationdb write system.services.systemconfiguration.network allow
> > 返回
> > YES (0)
> 
> 此处可能需要重启？
> --- 执行完之后 我就重启了  问题依旧
> 手动执行 `networksetup -setwebproxystate 网卡名 on` 能设置上 HTTP 代理吗？
-- 不加sudo的话 就报** Error: Command requires admin privileges.
执行sudo networksetup -setwebproxystate 网卡名 on 就可以正常设置一个HTTP 代理

**Comment by dyhkwong** [comment]
Qv2ray 只是调用系统命令执行 networksetup 进行系统代理的设置，如果 networksetup 不管用，那便不是 Qv2ray 可以解决的问题
