### ISSUE TITLE
Bug Report: 新版2.7.0 p2 选绕过中国大陆后仍有很多国内网站走代理

### ISSUE THREAD

**Issue by SYDW** [Qv2ray/Qv2ray#1587]
新版2.7.0 p2 选绕过中国大陆后仍有很多网站走代理
这些网站iP以及域名都是国内,但还是走了代理
2.6版本虽然会出现这种问题,但大部分都是IP或者域名是在香港澳门等地(阿里云)
这对我们做外贸的有点麻烦,要重新添加很多个网址

**Comment by Sinofine** [comment]
@SYDW 上游问题
请找他们

**Comment by dyhkwong** [comment]
为什么不是你自己的配置问题呢
