### ISSUE TITLE
Bug Report: 订阅h2链接时sni name字段未自动填写为host name

### ISSUE THREAD

**Issue by gy6221** [Qv2ray/Qv2ray#1591]
### Summary
以base64格式订阅传输协议为http的链接时SNI name字段未自动填写为host name

### Expected behavior
订阅后生成的传输协议为http的链接项自动设置好SNI name，如同传输协议为ws的一样

### How to Reproduce

使用订阅添加一个传输协议为http的链接
未测试SIP008是否有同样问题

### Screenshots

N/A

### Additional Info
_Add any other context about the problem here._

qv2ray version: 2.7.0-pre2:6220 (downloaded from github action)
同样问题也存在于pre-release中的2.7.0-pre2版本

**Comment by dyhkwong** [comment]
HTTP Host header **不是** SNI。某些软件把 HTTP Host header 填充到 SNI 里的做法大概是为了兼容 VMess 早期（以及现在）群魔乱舞的分享链接标准。
