### ISSUE TITLE
Bug Report: Opensuse cannot install Qv2ray-preview

### ISSUE THREAD

**Issue by dxyzx0** [Qv2ray/Qv2ray#1592]
### Summary
_A clear and concise description of what the bug is._
`sudo zypper in Qv2ray-preview` will give the following error:
![image](https://user-images.githubusercontent.com/28868457/124573508-30256480-de7c-11eb-9059-0227c84ceb0f.png)

### Expected behavior
_A clear and concise description of what you expected to happen._
Install Qv2ray normally.

### How to Reproduce
_Steps to reproduce the behavior._

### Screenshots
_If applicable, add screenshots to help explain your problem._

### Additional Info
_Add any other context about the problem here._
I use Opensuse Xfce.
![image](https://user-images.githubusercontent.com/28868457/124573692-5e0aa900-de7c-11eb-8725-3afc76eee787.png)

**Comment by MarksonHon** [comment]
Join the group:
<https://t.me/qv2ray_chat>

**Comment by dxyzx0** [comment]
![image](https://user-images.githubusercontent.com/28868457/124578125-8399b180-de80-11eb-86a9-a9ef2fe78d4a.png)
I solve the problem. Enable Autorefresh of the repo will work.
