### ISSUE TITLE
能够订阅，也更新了很多节点出来，但是每换一个节点就会报错。检查V2ray核心也是可以通过，核对过时间。但是速度图像一直没有显示，速度和数据一直为零。相同的节点在win10下面也能够用。

### ISSUE THREAD

**Issue by gcc-hub** [Qv2ray/Qv2ray#1615]
能够订阅，也更新了很多节点出来，但是每换一个节点就会报错。检查V2ray核心也是可以通过，核对过时间。但是速度图像一直没有显示，速度和数据一直为零。相同的节点在win10下面也能够用。

**Comment by gcc-hub** [comment]
![2021-07-20 14-52-36屏幕截图](https://user-images.githubusercontent.com/76736867/126277818-75dc55dd-799c-4056-b1df-7113736d49dc.png)
![2021-07-20 15-10-29屏幕截图](https://user-images.githubusercontent.com/76736867/126277826-c8577835-d54b-468c-9a0f-7f9317056450.png)

**Comment by dyhkwong** [comment]
不要报告上古版本发生的问题

**Comment by ardenwick** [comment]
为啥把标题写得那么长？
