### ISSUE TITLE
Bug Report: 最小完美哈希匹配器导致核心意外终止

### ISSUE THREAD

**Issue by requireCool** [Qv2ray/Qv2ray#1617]
### Summary
_A clear and concise description of what the bug is._

当路由匹配器选择最小完美哈希匹配器时，Qv2ray主程序会提示配置错误，然后会提示核心意外终止。
日志中仅有以下这一条
`[Info] main/jsonem: Reading config: C:/Users/10197/AppData/Local/qv2ray/generated/config.gen.json`
我使用的Qv2ray版本为`2.7.0-pre2:6220`，核心版本是`V2Ray 4.40.1`，域名匹配策略为`IPIfNonMatch`

### Expected behavior
_A clear and concise description of what you expected to happen._

MPH匹配器应当正常工作

### How to Reproduce
_Steps to reproduce the behavior._

在输入若干条高级路由策略后启用最小完美哈希匹配器就会出现问题

### Screenshots
_If applicable, add screenshots to help explain your problem._

![image](https://user-images.githubusercontent.com/55184050/126525224-45611790-8586-4768-b84c-bef025df1cc2.png)
![image](https://user-images.githubusercontent.com/55184050/126525279-d0b68262-d505-4773-90d4-b624e4a72317.png)

### Additional Info
_Add any other context about the problem here._

如果需要更多信息请告知

**Comment by ardenwick** [comment]
我还没见过 MPH 相关的BUG，不妨来 [Telegram 群组](https://t.me/Qv2ray_chat)，方便讨论。

**Comment by requireCool** [comment]
是我的问题，在mph匹配器里不能出现以`#`开头的注释信息。我直接导入了原始匹配器的路由设置到里面所以出现了问题

**Comment by x636** [comment]
俺也出现这样问题跟第2张图片一样咋解决，最好带附图来解决
