### ISSUE TITLE
Bug Report: wifi 掉了之后连接新 wifi 后崩溃

### ISSUE THREAD

**Issue by adlternative** [Qv2ray/Qv2ray#1622]
### Summary
_A clear and concise description of what the bug is._

每天晚上从实验室回寝室后，发现 Qv2ray 不能正常工作，
点击一个订阅连接会导致整个 Qv2ray 崩溃。

### Expected behavior
_A clear and concise description of what you expected to happen._

Qvray2 不崩溃。

### How to Reproduce
_Steps to reproduce the behavior._

粗估让电脑休眠并切换 wifi 。

### Screenshots
_If applicable, add screenshots to help explain your problem._
无。

### Additional Info
_Add any other context about the problem here._
无。

**Comment by MarksonHon** [comment]
@adlternative wiki（维基）怎么会掉？

**Comment by MarksonHon** [comment]
加入群聊：
<t.me/qv2ray_chat>
