### ISSUE TITLE
vless+grpc+tls只有上传数据，没有下载数据。

### ISSUE THREAD

**Issue by kmy-4Q** [Qv2ray/Qv2ray#1626]
vless+grpc+tls只有上传数据，没有下载数据。

**Comment by ghost** [comment]
You might refer to [an issue with core](https://github.com/v2fly/v2ray-core/issues/772), which has been solved.

If so, please use the latest version (download from [here](https://github.com/v2fly/v2ray-core/actions/workflows/release.yml?query=branch%3Amaster)).

**Comment by MarksonHon** [comment]
进群聊：
<https://t.me/qv2ray_chat>
