### ISSUE TITLE
V2Ray 核心退出代码: 255

### ISSUE THREAD

**Issue by natee** [Qv2ray/Qv2ray#1628]
### Summary

按照文档试用 brew 安装软件，下载最新v2ray-core，进行内核设置时一直提示“V2Ray 核心退出代码: 255”

### Expected behavior

提示正常

### Screenshots

<img width="877" alt="1" src="https://user-images.githubusercontent.com/4928035/127427134-60cc0673-8710-4008-bee1-f941ab325e9e.png">

![2](https://user-images.githubusercontent.com/4928035/127427162-eae716bd-fecd-4711-854d-771d4fd3239f.png)

### Additional Info
macOS big sur: 11.4
Qv2ray: 2.6.3:5840
v2ray-core: v4.40.1

**Comment by MarksonHon** [comment]
进群聊：
<https://t.me/qv2ray_chat>

**Comment by natee** [comment]
> 进群聊：
> https://t.me/qv2ray_chat

@MarksonHon 答错了进不去了，This group is private

**Comment by ruattd** [comment]
@natee 等2小时冷却吧
同时那个问题的答案应该是 散列（就md5/sha256那些东西）

**Comment by natee** [comment]
> @natee 等2小时冷却吧
> 同时那个问题的答案应该是 散列（就md5/sha256那些东西）

@maxelblack 7h了还是不能加入

**Comment by cubercsl** [comment]
@natee check it again
