### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by csjke** [Qv2ray/Qv2ray#1633]
qv2ray: error while loading shared libraries: libprotobuf.so.26: cannot open shared object file: No such file or directory

### Summary
_A clear and concise description of what the bug is._

### Expected behavior
_A clear and concise description of what you expected to happen._

### How to Reproduce
_Steps to reproduce the behavior._

### Screenshots
_If applicable, add screenshots to help explain your problem._

### Additional Info
_Add any other context about the problem here._

**Comment by cubercsl** [comment]
@csjke 请参考 #1554 #1365 #1085 #1073 #1069 #1059 #1047 #1046 #1041 #1040 #1039 #1038 #1037 #1035 #1034 #1033 #1032 等 Issue。不要在 manjaro 中使用 archlinuxcn 仓库。

**Comment by MarksonHon** [comment]
join group:
<t.me/qv2ray_intl>

**Comment by csjke** [comment]
系统是archlinux,升级系统后就打不开qv2ray了
