### ISSUE TITLE
Bug Report: 随机tag的问题

### ISSUE THREAD

**Issue by lonble** [Qv2ray/Qv2ray#1634]
### Summary
在tag缺省的情况下会使用随机tag，在配置里显得格格不入

### Expected behavior
默认使用"PROXY"作为tag

### How to Reproduce
不写tag

### Additional Info
在生成的配置文件里，不管是各种入站、直连、dns都有默认的tag，唯独用户设置的出站规则没有。
即使复杂配置里有多个自定义出站规则，那配置的人自己肯定会写tag，和简单配置（一般配置）没有关系。简单配置下，只有一个出站，并且就是用户期望的代理，tag设置在这里就显得很多余。
分享链接不包含tag（只测试了vless），通过链接导入的配置就是没有tag的，这说明一般情况下出站配置不会写tag。
tag在log里是非常重要的，比如"DIRECT"、"QV2RAY_API"都非常明显的提供了连接信息，而默认出站的随机tag却让人不知所云，把随机tag改成与"DIRECT"对应的"PROXY"显然更合适。

**Comment by database64128** [comment]
Done in https://github.com/moodyhunter/QvPersonal/commit/822c613991f6dd7d8e969bf204d906a31ba808ca.
