### ISSUE TITLE
插件

### ISSUE THREAD

**Issue by ligonfei** [Qv2ray/Qv2ray#1672]
那些插件是不是没法用了啊

**Comment by ghost** [comment]
能用，找找自己的原因

**Comment by ligonfei** [comment]
旧版插件可以在dev版的qv2上用？问什么我提示插件有问题啊

tdjnodj ***@***.***> 于2022年10月4日周二 18:20写道：

**Comment by Firekylinxiang** [comment]
插件要配合和是的版本才能使用
