### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by mahdigh99** [Qv2ray/Qv2ray#1674]
### Summary
Can't connect to server in macOS Big Sur 11.6.7

### Expected behavior
I can connect with others v2ray clients but i want VPN Mode( or send all traffic over proxy) not system proxy, and i try using Qv2ray but it cannot connect.

### Screenshots
<img width="836" alt="Screen Shot 1401-07-11 at 15 19 04" src="https://user-images.githubusercontent.com/24169864/193570651-cc31a031-c9fa-4f45-8891-6405f0f842a5.png">

**Comment by MarksonHon** [comment]
@mahdigh99 Qv2ray IS NOT a VPN client, and it based on v2ray

**Comment by mahdigh99** [comment]
> @mahdigh99 Qv2ray IS NOT a VPN client, and it based on v2ray

OK but it not connected at all in my device. 
Error is in screenshot.

**Comment by oozeRyze** [comment]
Please refer to the documentation https://qv2ray.net/getting-started/step2.html

**Comment by mahdigh99** [comment]
fixed:
i run ` brew install v2ray` command then it fixed.
