### ISSUE TITLE
Bug Report: v2ray core failed with an exit code :2

### ISSUE THREAD

**Issue by AwJHub** [Qv2ray/Qv2ray#1675]
v2ray core failed with an exit code :2
i tried 2 core releases and install & uninstall many times but didnt fixed 

![image](https://user-images.githubusercontent.com/76947375/194052265-87054e39-6843-45c3-af75-cedd6339c7ae.png)

**Comment by oozeRyze** [comment]
Click `Check V2Ray Core Settings` to check the version of v2ray-core.
If you use `Qv2ray 2.7.0`, use `v2ray-core v4.45.2` instead of `v2ray-core v5`.

**Comment by AwJHub** [comment]
thank you it worked .
