### ISSUE TITLE
Bug Report: mac 无法运行客户端，一直无响应，是何道理

### ISSUE THREAD

**Issue by bayma888** [Qv2ray/Qv2ray#1682]
### Summary
_A clear and concise description of what the bug is._

### Expected behavior
_A clear and concise description of what you expected to happen._

### How to Reproduce
_Steps to reproduce the behavior._

### Screenshots
_If applicable, add screenshots to help explain your problem._

### Additional Info
_Add any other context about the problem here._

**Comment by EpLiar** [comment]
请提供系统版本 Qv 版本以及 V2Ray 内核版本
