### ISSUE TITLE
V2Ray kernel failed to start

### ISSUE THREAD

**Issue by afshin-ir** [Qv2ray/Qv2ray#1683]
Hello.

I use Linux Mint 21 with Cinnamon desktop.
When I run `Qv2ray-v2.7.0-linux-x64.AppImage`, I get this error:

`V2Ray kernel failed to start: V2Ray core executable not found.`

![image](https://user-images.githubusercontent.com/14938202/202113874-b8326bc6-32f6-42b2-bc20-0564bf9ea5c0.png)

**Comment by zedifen** [comment]
As it said, "V2Ray core executable not found".

Maybe you can try placing a compatible v2ray-core executable in some designated places?

V2ray core can be found in official repository: https://github.com/v2fly/v2ray-core

Referring to Qv2ray Documents: http://qv2ray.xyz/ (temporary site)

**Comment by afshin-ir** [comment]
I downloaded  `v2ray-android-arm64-v8a.zip `and extracted it and placed `v2ray` in below path:
`/home/neesti/.config/qv2ray/vcore`

and when I run Qv2ray, I get this error:
`V2Ray kernel failed to start: V2Ray assets path is not valid.`

**Comment by zedifen** [comment]
Both the core path and the asset path should be set in Qv2ray settings. Usually the assets comes together with the core, once you extract the zip file you get the core and the assets. Put them in the same directory is okay.

By the way, are you sure `android-arm64` is your platform? Usually it should be `linux-64` in your cases, I think.

**Comment by afshin-ir** [comment]
You are right. 
I puted  `v2ray-linux-64.zip` content in this path:
`/home/neesti/.config/qv2ray/vcore/`

and I get this error:
`V2Ray kernel failed to start: V2Ray core failed with an exit code: 2`

**Comment by zedifen** [comment]
Can you try running this executable in terminal and see what happened?

**Comment by afshin-ir** [comment]
I entered this command:
`./v2ray run `

and get this output:
```
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
A unified platform for anti-censorship.
2022/11/17 07:51:16 Using default config:  /home/neesti/.config/qv2ray/vcore/config.json
2022/11/17 07:51:17 [Warning] V2Ray 5.1.0 started

```

**Comment by zedifen** [comment]
Looks like you're using V2ray V5. I remember this version of Qv2ray doesn't support V5 core.

You can try using a V4 core e.g. https://github.com/v2fly/v2ray-core/releases/tag/v4.45.2 , or using some other port of Qv2ray

**Comment by afshin-ir** [comment]
The problem solved when I puted V2ray 4.45.2 core. 

Thank you so much.

**Comment by lnxpy** [comment]
@zedifen I'm having the same issue on Mac. It looks Qv2ray does not support the latest version of `v2ray-core` that is available on `brew` meaning I can't download and install the older releases of `v2ray-core` using `brew`. Any solutions for me? :)

**Comment by zedifen** [comment]
@lnxpy Is downloading assets from [v2ray-core GitHub Release (v4.45.2)](https://github.com/v2fly/v2ray-core/releases/tag/v4.45.2) (as mentioned before) okay for you?

Or if you'd like to use v5 cores, you can try this [Qv2ray from Shadowsocks-NET](https://github.com/Shadowsocks-NET/Qv2ray) or [the one from dyhkwong (which is a fork of former one)](https://github.com/dyhkwong/Qv2ray). But you may probably need to build them from source yourself, since currently the build for macOS and Linux on GitHub Action doesn't include Qt libraries.

**Comment by sinalalebakhsh** [comment]
I get this :
when I want to connect:

V2Ray core settings is incorrect.

The error is: 
V2Ray core executable not found.

**Comment by lnxpy** [comment]
@zedifen Yes, it is. I have to use 4.45.2 but there is no way to install this specific version on my system using any of the package managers like `brew` as such. Now, I'm using the v2ray-core 4.45.2 executable within the repo directory downloaded in my `~/Downloads`. I wish I could have it installed globally on my system though.

**Comment by lnxpy** [comment]
@sinalalebakhsh You need to download `v2ray-core` any of releases before 4.45.2 I believe. Then, set the executable file and path in the app and you're good to go.

**Comment by sinalalebakhsh** [comment]
> @sinalalebakhsh You need to download `v2ray-core` any of releases before 4.45.2 I believe. Then, set the executable file and path in the app and you're good to go.

I need more than this explain for install in Ubuntu. step by step

**Comment by zedifen** [comment]
@sinalalebakhsh I'm not sure what your architecture is, so let's assume it's `amd64`. 

Then you visit v2ray-core's GitHub Release page, scroll down when you find a release whose version is less than 4.45.2 (Here's [a link to v4.45.2](https://github.com/v2fly/v2ray-core/releases/tag/v4.45.2) for convenience).

Then you find assets corresponding to your system and architecture under that release, in this case it should be `v2ray-linux-64.zip` (for most of the Linux distribution `linux` would be fine, and `64` means `amd64` if it comes with `arm64`; sometimes it also comes as `amd64` or `x86_64`).

Then you download this asset and unzip it under a directory, for example, `~/Downloads/v2ray-core/`. Test it by running `~/Downloads/v2ray-core/v2ray --help`. If there's no error then it should be okay.

Last, add this path to v2ray core as "executable path" and the path where it lies as the "asset path" to Qv2ray .

**Comment by sinalalebakhsh** [comment]
> @sinalalebakhsh I'm not sure what your architecture is, so let's assume it's `amd64`.
> 
> Then you visit v2ray-core's GitHub Release page, scroll down when you find a release whose version is less than 4.45.2 (Here's [a link to v4.45.2](https://github.com/v2fly/v2ray-core/releases/tag/v4.45.2) for convenience).
> 
> Then you find assets corresponding to your system and architecture under that release, in this case it should be `v2ray-linux-64.zip` (for most of the Linux distribution `linux` would be fine, and `64` means `amd64` if it comes with `arm64`; sometimes it also comes as `amd64` or `x86_64`).
> 
> Then you download this asset and unzip it under a directory, for example, `~/Downloads/v2ray-core/`. Test it by running `~/Downloads/v2ray-core/v2ray --help`. If there's no error then it should be okay.
> 
> Last, add this path to v2ray core as "executable path" and the path where it lies as the "asset path" to Qv2ray .

Ubuntu 22.04.2 LTS

**Comment by sinalalebakhsh** [comment]
> Last, add this path to v2ray core as "executable path" and the path where it lies as the "asset path" to Qv2ray .

in this line you say:
Last, add this path to v2ray core as "executable path" and the path where it lies as the "asset path" to Qv2ray .

I do not know what is that!  "executable path"  than I create and run it.

I am beginner

**Comment by zedifen** [comment]
@sinalalebakhsh Maybe you can refer to the documentation <https://qv2ray-net.pages.dev/getting-started/step2.html#configure-v2ray-core-in-qv2ray>

**Comment by sinalalebakhsh** [comment]
> @sinalalebakhsh Maybe you can refer to the documentation https://qv2ray-net.pages.dev/getting-started/step2.html#configure-v2ray-core-in-qv2ray

Thanks for attention but,
for opening this link I need to vpn runing before! I am in Iran and this Government filter everything!!!! I can open this link.

**Comment by zedifen** [comment]
@sinalalebakhsh Then here's a copy:

> ### Configure V2Ray Core in Qv2ray
>
> Open Qv2ray and go to Preference Window. In [Kernel Settings](qv2ray://open/preference/kernel), configure the following options:
>
> - **Core Executable Path**: Set this to where your V2Ray executable exists. This can be the full path of your `v2ray.exe` on Windows, or that `v2ray` executable file on Linux / macOS.
> - **V2Ray Assets Directory**: Set this to where `geoip.dat` and `geosite.dat` are located.
>
> After configuring, you can click on **Check V2Ray Core Settings** button to validate your V2Ray core settings. Repeat trying until you get the check passed.

By the way, you may want newer `geoip.dat` and `geosite.dat`, they can be found seperately at:

- GeoIP: <https://github.com/v2fly/geoip/releases>
- GeoSite: <https://github.com/v2fly/domain-list-community/releases> (The files you may find in the release assets would be named as `dlc.dat` instead of `geosite.dat`, just rename it back to `geosite.dat` after downloading it.)

**Comment by sinalalebakhsh** [comment]
> @sinalalebakhsh Then here's a copy:
> 
> > ### Configure V2Ray Core in Qv2ray
> > Open Qv2ray and go to Preference Window. In Kernel Settings, configure the following options:
> > 
> > * **Core Executable Path**: Set this to where your V2Ray executable exists. This can be the full path of your `v2ray.exe` on Windows, or that `v2ray` executable file on Linux / macOS.
> > * **V2Ray Assets Directory**: Set this to where `geoip.dat` and `geosite.dat` are located.
> > 
> > After configuring, you can click on **Check V2Ray Core Settings** button to validate your V2Ray core settings. Repeat trying until you get the check passed.
> 
> By the way, you may want newer `geoip.dat` and `geosite.dat`, they can be found seperately at:
> 
>     * GeoIP: https://github.com/v2fly/geoip/releases
> 
>     * GeoSite: https://github.com/v2fly/domain-list-community/releases (The files you may find in the release assets would be named as `dlc.dat` instead of `geosite.dat`, just rename it back to `geosite.dat` after downloading it.)

Thanks a lot my friend. I cant configured  it, I need tutorial video for this complicated network running , step by step for beginner. I research another way thank you

**Comment by couzhei** [comment]
@sinalalebakhsh  I'm not sure if this helps you or someone else! But if someone has the same problem on Ubuntu 22.04, here's how you proceed:
`which v2ray`
will give you the executable path you need to set at V2Ray Core Settings, if there the above didn't give you any output, you might as well install it using:
`apt install v2ray`
As of now, it'll install the latest version for you.
For the assets try one of these:
`/etc/v2ray/` or `/usr/share/v2ray/`
If none worked, for the last resort try:
`sudo find -type d -name 'v2ray'`
then while you are still at Preferences> Kernel Settings, click on Check V2Ray Core Settings, if it shows you information about the version of your v2ray, then it has been successful.

**Comment by adelbordbari** [comment]
> Looks like you're using V2ray V5. I remember this version of Qv2ray doesn't support V5 core.
> 
> You can try using a V4 core e.g. https://github.com/v2fly/v2ray-core/releases/tag/v4.45.2 , or using some other port of Qv2ray

Worked for me after downgrading to 4 as well. thank you.

**Comment by Drjacky** [comment]
> @zedifen I'm having the same issue on Mac. It looks Qv2ray does not support the latest version of `v2ray-core` that is available on `brew` meaning I can't download and install the older releases of `v2ray-core` using `brew`. Any solutions for me? :)

Download https://github.com/v2fly/v2ray-core/releases/tag/v4.45.2 and put the whole folder (rename it to v2ray) under `/opt/homebrew/opt/` for Apple Silicon or under `/usr/local/opt` for macOS Intel
<img width="296" alt="Screenshot 2024-08-18 at 10 23 30" src="https://github.com/user-attachments/assets/d2073329-0724-4d86-89ac-6b89f88e704c">

**Comment by chalist** [comment]
Doesn't work with V5. Just download version 4 and use it https://github.com/v2fly/v2ray-core/releases/tag/v4.45.2

**Comment by 1769588795** [comment]
邮件已收到，谢谢！！！O(∩_∩)O~~~
