### ISSUE TITLE
consider storing configurations in database

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#169]
current version of qv2ray will store configurations as files, which has caused many problems about security and safety. 

it would be better if we can store configurations in a local database, for example, sqlite.

I know old mechanisms are hard to dispose, but in the long run a stable unified configuration center will definitely benefit our development.

**Comment by thebadgateway** [comment]
I think there is no difference how to store data. If someone already controls your computer, then he takes over the data in any case.

**Comment by lhy0403** [comment]
No recent considerations about this yet

**Comment by DuckSoft** [comment]
Well, I am working on it. Stay tuned.
@lhy0403

**Comment by Qv2ray-dev** [comment]
Is this thread still active?

**Comment by DuckSoft** [comment]
@Qv2ray-dev y

**Comment by Qv2ray-dev** [comment]
Is this thread still active? x2

**Comment by Qv2ray-dev** [comment]
How about moving it onto the Qv2ray v3 if it still exist till that time?
@DuckSoft
