### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by HosseinShahverdi** [Qv2ray/Qv2ray#1693]
### Summary
Hello dear developers, i have a issue with enabaling "Allow Insecure Certificate".

### Expected behavior
_A clear and concise description of what you expected to happen._

### How to Reproduce
_Steps to reproduce the behavior._

### Scree
![Screenshot 2023-01-10 115912](https://user-images.githubusercontent.com/70755266/211501292-192311d1-b327-4ccc-92cc-2d4e81fa66be.jpg)
nshots
_If applicable, add screenshots to help explain your problem._

### Additional Info
_Add any other context about the problem here._

**Comment by Elshepl** [comment]
Any Updates?

**Comment by mosys2** [comment]
Please right ckick on config and cllick Edit as json and add  "allowInsecure": true, to tlsSettings sample:
![image](https://github.com/user-attachments/assets/c88beb0a-34d5-48cf-aaa0-cba67a850f76)


"streamSettings": {
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": true,
                    "alpn": [
                        "h3",
                        "h2",
                        "http/1.1"
                    ],
                    "serverName": "divarcdn.com"
                }
            },
