### ISSUE TITLE
No Connection to Whatsapp and Bluestacks 

### ISSUE THREAD

**Issue by andhracse** [Qv2ray/Qv2ray#1694]
No Internet Connection 

No Connection to Whatsapp and Bluestacks , uploaded default Settings screenshots.  i use vless server

![image](https://user-images.githubusercontent.com/121793145/211557182-2e2d762f-ee56-4aab-9585-c41cc6678840.png)
![image](https://user-images.githubusercontent.com/121793145/211557392-71bab507-31b2-4df7-931f-d23f935e17ab.png)
![image](https://user-images.githubusercontent.com/121793145/211557434-2838d861-4b0f-4d2b-9c9b-69573a22a52a.png)
![image](https://user-images.githubusercontent.com/121793145/211557543-6f470dcc-735c-42dc-a787-31479c7b15c4.png)

**Comment by Alireza2317** [comment]
I have this similar problem.

**Comment by mrtabaa** [comment]
Have you found a solution for this mate? Issue with Telegram as well.

**Comment by mrtabaa** [comment]
The issue for me was GNOME on Fedora. Ubuntu GNOME and Debian KDE (MX Linux) work fine with no issue.
