### ISSUE TITLE
Macbook only work on browser

### ISSUE THREAD

**Issue by A2DNEW** [Qv2ray/Qv2ray#1705]
I use Qv2ray on my macbook.
But proxy work on browsers only.
Other application don't use it.
How can I use proxy for whole my system?

**Comment by zedifen** [comment]
Some GUI applications and most command-line tools won't pick up your proxy settings in system. These apps needed to be manually configured to use proxies.

If you'd like to take over whole system's traffic, some kind of technologies like TUN or VPN might suit your needs.
