### ISSUE TITLE
Install QV2RAY on macOS High Sierra

### ISSUE THREAD

**Issue by srezaei129** [Qv2ray/Qv2ray#1708]
I installed qv2ray from Github correctly. I downloaded .dmg file and zip file of core and checked the core was passed. I imported a file of vmess but when I click on "connect to this", it becomes connect but nothings run on the software and still I couldn't open some sites. What I am doing wrong?

**Comment by zedifen** [comment]
Have you set the System Proxy? If not, many of the apps won't be able to know that there's an proxy running kn the computer, so one thing is to configure the System Proxy. 

You can follow the instructions on <https://qv2ray-net.pages.dev/getting-started/step4.html#general-methods>. Generally, you can:

For Windows and macOS users, almost all of the applications will follow the system proxy settings. For Linux users, some applications such as Firefox and Chromium, but not all, will read and obey the proxy configurations in GNOME/KDE Settings.

Currently, automatic setting of system proxy is supported by Qv2ray, including Windows, macOS and Linux (GNOME/KDE). You may find System Proxy options of Qv2ray in the following positions:

Qv2ray Tray Menu.

1. Right click on the tray icon.
2. In the popup menu, choose **System Proxy** -> **Enable/Disable System Proxy**.

Qv2ray Preference Window.

1. Click **Preferences** button in the main window.
1. In **Preference Window**, choose the tab **Inbound Settings**.
1. Check the option **Set System Proxy**.
1. Click **OK** to apply the settings.

**Comment by ghost** [comment]
if you use v2ray version 5 and after, please try this
https://github.com/iamqk/Qv2ray/releases/tag/v2.8.0-pre23

**Comment by xuexijiaoben** [comment]
> if you use v2ray version 5 and after, please try this https://github.com/iamqk/Qv2ray/releases/tag/v2.8.0-pre23

我试了下，似乎不行呀，试了好几个V5版本，

**Comment by ghost** [comment]
> > if you use v2ray version 5 and after, please try this https://github.com/iamqk/Qv2ray/releases/tag/v2.8.0-pre23
> 
> 我试了下，似乎不行呀，试了好几个V5版本，

能详细说下哪里不行吗？
我试了一下可以的

**Comment by xuexijiaoben** [comment]
> > > if you use v2ray version 5 and after, please try this https://github.com/iamqk/Qv2ray/releases/tag/v2.8.0-pre23
> > 
> > 
> > 我试了下，似乎不行呀，试了好几个V5版本，
> 
> 能详细说下哪里不行吗？ 我试了一下可以的

刚又试了下，从v4.45.2到最新的v5.6.0，都显示不可执行还是啥的，
v2.8.0-pre23这个下载下来之后，软件关于里面显示的版本号是2.7.0:7001
系统是ventura 13.3，不知道是不是新系统不支持

**Comment by ghost** [comment]
> > > > if you use v2ray version 5 and after, please try this https://github.com/iamqk/Qv2ray/releases/tag/v2.8.0-pre23
> > > 
> > > 
> > > 我试了下，似乎不行呀，试了好几个V5版本，
> > 
> > 
> > 能详细说下哪里不行吗？ 我试了一下可以的
> 
> 刚又试了下，从v4.45.2到最新的v5.6.0，都显示不可执行还是啥的， v2.8.0-pre23这个下载下来之后，软件关于里面显示的版本号是2.7.0:7001 系统是ventura 13.3，不知道是不是新系统不支持

我就是用的ventura最新的13.4

qv2ray
首选项-内核设置 那里
重新选择一下可执行路径和资源目录

ps：ventura也需要在
设置-隐私与安全-允许执行

**Comment by xuexijiaoben** [comment]
> > > > > if you use v2ray version 5 and after, please try this https://github.com/iamqk/Qv2ray/releases/tag/v2.8.0-pre23
> > > > 
> > > > 
> > > > 我试了下，似乎不行呀，试了好几个V5版本，
> > > 
> > > 
> > > 能详细说下哪里不行吗？ 我试了一下可以的
> > 
> > 
> > 刚又试了下，从v4.45.2到最新的v5.6.0，都显示不可执行还是啥的， v2.8.0-pre23这个下载下来之后，软件关于里面显示的版本号是2.7.0:7001 系统是ventura 13.3，不知道是不是新系统不支持
> 
> 我就是用的ventura最新的13.4
> 
> qv2ray 首选项-内核设置 那里 重新选择一下可执行路径和资源目录
> 
> ps：ventura也需要在 设置-隐私与安全-允许执行

已经搞定，原来是在windows下解压v2ray插件都有问题，改成在mac下直接解压就可以了，
另外，qv2ray支持的那些插件感觉好老了，有没有途径更新呀，能否支持reality，谢谢啦
