### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Mashiro-shi** [Qv2ray/Qv2ray#1715]
连接不上服务器，显示核心意外终止。
下面是日志
[Init] High DPI scaling is enabled.
[BaseApplication] Qv2ray 2.7.0-pre2 on Windows 10 Version 2009 x86_64
[BaseApplication] Qv2ray Start Time:  442724
[BaseApplication] QV2RAY_BUILD_INFO Qv2ray built from Github Action
[BaseApplication] QV2RAY_BUILD_EXTRA_INFO qt5.15.0-4cc95cb2f686250c899a04969e1a220af449908d-ci.windows-latest
[BaseApplication] QV2RAY_BUILD_NUMBER 6150
[BaseApplication] This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
Copyright (c) 2019-2021 Qv2ray Development Group.
Third-party libraries that have been used in this program can be found in the About page.

![image](https://github.com/Qv2ray/Qv2ray/assets/136623068/ceee3aef-369a-4fa9-99e9-d3e7445e4357)

**Comment by iseki0** [comment]
`内核设置 -> V2Ray 核心可执行文件路径` 应该指向 v2ray 核心的路径，请不要再次指向 Qv2ray.exe
