### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Mashiro-shi** [Qv2ray/Qv2ray#1716]
核心检测通过但是并没有成功显示版本号
![image](https://github.com/Qv2ray/Qv2ray/assets/136623068/4e6ad575-185c-4af4-9cbe-f0d8637471f9)
连接服务器也显示失败，核心意外终止
![image](https://github.com/Qv2ray/Qv2ray/assets/136623068/42fdbc02-b58a-4407-a7a7-c17b7c27b570)

**Comment by cubercsl** [comment]
@DOGZZY 你核心路径错了 不要指向自己

**Comment by Mashiro-shi** [comment]
什么意思，能详细解释下吗

**Comment by Mashiro-shi** [comment]
ok我解决了，谢谢。
