### ISSUE TITLE
除了降级v2ray到5.1,还有别的办法吗?

### ISSUE THREAD

**Issue by aavamin** [Qv2ray/Qv2ray#1717]
2023/06/21 17:03:35 [Info] features: You are using a deprecated feature: root fakedns settings. Please update your config file with latest configuration format, or update your client software.

**Comment by blackteahamburger** [comment]
应该只是一条消息，没有影响。
但如果用[v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat)并且设置高级路由设置或者用trojan-go插件就会弹出这条消息的对话框，然后核心意外终止。
