### ISSUE TITLE
Bug Report: 新电脑w11，旧电脑w10使用正常，把旧电脑的包弄到新电脑来就显示核心意外终止，让看核心日志，不知道怎么弄

### ISSUE THREAD

**Issue by ddhhtt271** [Qv2ray/Qv2ray#1726]
### Summary
_A clear and concise description of what the bug is._

### Expected behavior
_A clear and concise description of what you expected to happen._

### How to Reproduce
_Steps to reproduce the behavior._

### Screenshots
_If applicable, add screenshots to help explain your problem._

### Additional Info
_Add any other context about the problem here._

**Comment by sewaide** [comment]
xray只能用1.7.5版本以下吧

**Comment by hiiiha** [comment]
> xray只能用1.7.5版本以下吧

我这里可以用 1.8.4. 题主大概率是没有配置好核心/忘了改默认核心/没有下载核心

**Comment by sewaide** [comment]
你的意思是Qv2ray 2.7.0 可以使用最新的xray1.8.4版本的核心吗？

**Comment by hiiiha** [comment]
我用 release 里下载的版本，至少在我的 Windows 笔记本 和 Manjaro 台式机上，是可以使用 xray 1.8.4 的

**Comment by ddhhtt271** [comment]
> > xray只能用1.7.5版本以下吧
> 
> 我这里可以用 1.8.4. 题主大概率是没有配置好核心/忘了改默认核心/没有下载核心

我自己也不太清楚我的是哪个版本的，大概两年前装的，在w10上用一切正常，w11上面用就不行，想找找新版本，但是第一次用github啥都看不懂，找不到，想问问应该去哪找

**Comment by ddhhtt271** [comment]
> 我用 release 里下载的版本，至少在我的 Windows 笔记本 和 Manjaro 台式机上，是可以使用 xray 1.8.4 的

我想问问这个现在是停止更新了吗，找新版本的时候有看到过

**Comment by ddhhtt271** [comment]
纯小白，账号还是为了找这个被迫注册的，根本不会用，不知道上哪找😿

**Comment by DirectorL** [comment]
> 纯小白，账号还是为了找这个被迫注册的，根本用不到，不知道上哪找😿
windows就用v2rayN吧，这个项目太久不更新了，没能力自己改bug自己编译，不如换一个，我windows上一直在用v2rayn，mac和linux在用clash，少折腾
