### ISSUE TITLE
想自己开发编译有什么指南么？

### ISSUE THREAD

**Issue by bihell** [Qv2ray/Qv2ray#1728]
这两天想弄REALITY，但是软件里面并没有这个选项，Qv2ray，我真的挺喜欢的，官方不开发的话我想知道自己开发要怎么弄。

**Comment by johnan0528** [comment]
可以直接Json 导入使用, 我现在就是Json 导入使用的Reality , 就是不能链接分享

**Comment by johnan0528** [comment]
![微信截图_20231203110252](https://github.com/Qv2ray/Qv2ray/assets/66048352/405df347-15c8-4060-b393-e3a092ea60a0)

**Comment by bihell** [comment]
> 可以直接Json 导入使用, 我现在就是Json 导入使用的Reality , 就是不能链接分享

这操作骚啊，然后fingerprint uTLS，这个哪里配置知道么？我也没找到，也只用json？

**Comment by johnan0528** [comment]
你直接导入即可, 就不需要管这些东西了, 直接用了

**Comment by johnan0528** [comment]
![微信截图_20231203110224](https://github.com/Qv2ray/Qv2ray/assets/66048352/c81c9ca6-1c0b-46c1-a778-fb51b42b967a)

**Comment by bihell** [comment]
> 你直接导入即可, 就不需要管这些东西了, 直接用了

搞定了，这下方便了，以后xray再怎么更新也不怕了

**Comment by xuexijiaoben** [comment]
你们用的是哪个版本的qv2ray呀，在哪儿下载的呀

**Comment by bihell** [comment]
> 你们用的是哪个版本的qv2ray呀，在哪儿下载的呀

就release的版本哇，n个月前的那个

**Comment by Firekylinxiang** [comment]
> > 你们用的是哪个版本的qv2ray呀，在哪儿下载的呀
> 
> 就release的版本哇，n个月前的那个

2.6.3很稳定，也能完美适配m1和m2芯片

**Comment by saymyname77** [comment]
> > > 你们用的是哪个版本的qv2ray呀，在哪儿下载的呀
> > 
> > 
> > 就release的版本哇，n个月前的那个
> 
> 2.6.3很稳定，也能完美适配m1和m2芯片

2.6.3之后的新版呢，肿么不用

**Comment by Firekylinxiang** [comment]
qv2ray要配合对应的插件版本的，我用最新版的2.7.0尝试了好多版本的插件都失败了，你知道最新版对应的各插件版本好吗？我可以是试试发自我的 iPad ProOn Aug 13, 2024, at 15:01, saymyname ***@***.***> wrote:﻿



你们用的是哪个版本的qv2ray呀，在哪儿下载的呀

就release的版本哇，n个月前的那个

2.6.3很稳定，也能完美适配m1和m2芯片

2.6.3之后的新版呢，肿么不用
