### ISSUE TITLE
Exec format error: Unable to run appimage files on ubutu 16.04 and lubuntu 18Bug Report: 

### ISSUE THREAD

**Issue by aliniko79** [Qv2ray/Qv2ray#1732]
I've been trying to run Qv2ray and other programs on Ubuntu 16.04 and Lubuntu 18, but I always get this error: "cannot execute binary file: Exec format error".

Here's the article that I've red in order to run appimage files: https://askubuntu.com/questions/774490/what-is-an-appimage-how-do-i-install-it

I tried these steps: 1-Installing fuse: sudo apt install libfuse2 2-Making the file executable in properties(Checked). 3-Double clicking on the file.

Another file with a weird name appeared next to it, but the program was not executed, and also when I try to run it I get this error: "cannot execute binary file: Exec format error".
My system is 32bit.

**Comment by hiiiha** [comment]
Qv2ray 2.7.0 cannot run on 32 bit systems.
