### ISSUE TITLE
@RichardPeng0624 杀一下残留进程即可：怎么杀呀

### ISSUE THREAD

**Issue by Precola** [Qv2ray/Qv2ray#1735]
@RichardPeng0624 杀一下残留进程即可

_Originally posted by @EpLiar in https://github.com/Qv2ray/Qv2ray/issues/889#issuecomment-671965598_

**Comment by EpLiar** [comment]
Windows 在任务管理器里找 Qv2ray，Linux 用 ps 找后 `kill -9`
