### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by VincentMa66** [Qv2ray/Qv2ray#1743]
### Summary
_A clear and concise description of what the bug is._
V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 darwin/amd64)
A unified platform for anti-censorship.
2024/08/12 16:57:10 [Info] main/jsonem: Reading config: /Users/luomajie01/Library/Preferences/qv2ray/generated/config.gen.json
2024/08/12 16:57:10 [Warning] V2Ray 4.44.0 started
2024/08/12 16:57:10 127.0.0.1:63104 accepted tcp:127.0.0.1:0 [QV2RAY_API]
2024/08/12 16:57:13 127.0.0.1:63105 accepted //internal-api-security.feishu.cn:443 [DIRECT]
2024/08/12 16:57:16 127.0.0.1:63109 accepted //mesu.apple.com:443 [PROXY]
2024/08/12 16:57:17 tcp:127.0.0.1:63111 accepted tcp:ccm-frontier-hl.feishu.cn:443 [DIRECT]
2024/08/12 16:57:27 127.0.0.1:63115 accepted //internal-api-space.feishu.cn:443 [DIRECT]
2024/08/12 16:57:27 127.0.0.1:63117 accepted //internal-api-space.feishu.cn:443 [DIRECT]
2024/08/12 16:57:31 [Warning] [1706346807] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://pcroute.sparkgame.com.cn/SparkGame-Office): > EOF transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://pcroute.sparkgame.com.cn/SparkGame-Office): > dial tcp: operation was canceled] > common/retry: all retry attempts failed
2024/08/12 16:57:31 tcp:127.0.0.1:63119 accepted tcp:ccm-frontier.feishu.cn:443 [DIRECT]
2024/08/12 16:57:37 tcp:127.0.0.1:63121 accepted tcp:ccm-frontier.feishu.cn:443 [DIRECT]
2024/08/12 16:57:40 tcp:127.0.0.1:63123 accepted tcp:ccm-frontier.feishu.cn:443 [DIRECT]
2024/08/12 16:57:53 127.0.0.1:63125 accepted //jghxp86f0w.feishu.cn:443 [DIRECT]
2024/08/12 16:57:56 127.0.0.1:63127 accepted //optimizationguide-pa.googleapis.com:443 [PROXY]
2024/08/12 16:57:57 127.0.0.1:63129 accepted //www.google.com.hk:443 [PROXY]
2024/08/12 16:57:57 127.0.0.1:63131 accepted //optimizationguide-pa.googleapis.com:443 [PROXY]
2024/08/12 16:58:18 [Warning] [1006520888] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://pcroute.sparkgame.com.cn/SparkGame-Office): > EOF] > common/retry: all retry attempts failed
2024/08/12 16:58:18 127.0.0.1:63145 accepted //optimizationguide-pa.googleapis.com:443 [PROXY]
2024/08/12 16:58:19 [Warning] [2889450044] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://pcroute.sparkgame.com.cn/SparkGame-Office): > EOF] > common/retry: all retry attempts failed
2024/08/12 16:58:19 127.0.0.1:63147 accepted //www.google.com.hk:443 [PROXY]
2024/08/12 16:58:19 [Warning] [485744934] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://pcroute.sparkgame.com.cn/SparkGame-Office): > EOF] > common/retry: all retry attempts failed
2024/08/12 16:58:19 127.0.0.1:63149 accepted //optimizationguide-pa.googleapis.com:443 [PROXY]
2024/08/12 16:58:27 127.0.0.1:63155 accepted http://www.gstatic.com/generate_204 [PROXY]

### Expected behavior
可以正常链接外网。

### How to Reproduce
_Steps to reproduce the behavior._

### Screenshots
![image](https://github.com/user-attachments/assets/c0adf2de-0197-44a8-9a3a-2464e3b84013)._

### Additional Info
_Add any other context about the problem here._

**Comment by hiiiha** [comment]
节点问题请不要在 qv2ray 发 issue
