### ISSUE TITLE
关于 GFWList 自动下载的透明性问题

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#198]
当前版本的 GFWList 下载界面：
![图片](https://user-images.githubusercontent.com/7822648/71538484-cf53cc80-2966-11ea-8f60-8592c91e125e.png)

存在以下几个问题：
1. GFWList 的镜像源地址不透明。用户只知道下载源的名称，看不到具体的 URL。
2. GFWList 的下载过程不透明。用户不知道下载过程进行到何种程度。
3. GFWList 的下载按钮在下载过程中可以被多次点击。可能会造成非预期的结果。

**Comment by lhy0403** [comment]
Target: Qv2ray v2.1 or future version.
https://github.com/lhy0403/Qv2ray/commit/54c109695368fdc6e6a2375910c8788d01c6595b added some basic UI effect when downloading the file.

**Comment by lhy0403** [comment]
[54c1096](https://github.com/lhy0403/Qv2ray/commit/54c109695368fdc6e6a2375910c8788d01c6595b) Fixed issue number 3

**Comment by lhy0403** [comment]
https://github.com/lhy0403/Qv2ray/issues/207#issuecomment-569594885 
Qv2ray v2 RC 2 将重点解决 PAC 体验问题

**Comment by kingskill** [comment]
pac目前最大的问题和yt有关，yt上视频都可以看，没问题，但是所有视频在页面上的预览图加载特别慢，甚至不加载。关闭pac后，直接用代理，就没这个问题。估计是gfwlist的问题吧？

**Comment by DuckSoft** [comment]
就咱个人的日常使用来说，v2ray 自带的分流机制要远远优于 PAC。
PAC 技术已经事实过时了。

若您对 GFWList 提供的 PAC 规则有不满，请反馈至 GFWList 上游。
Qv2ray 恕不对其提供的内容负责。

**Comment by Qv2ray-dev** [comment]
Actually, although Qv2ray supports GFWList, it's not suggested to use it. Closing.
