### ISSUE TITLE
建议增加自定义TLS SNI的功能

### ISSUE THREAD

**Issue by 9h5ej** [Qv2ray/Qv2ray#209]
v2ray内核已经支持自定义TLS SNI，但目前本软件并不支持(i2ray支持)。利用自定义TLS SNI可以在外层TLS和内层websocket中使用不同域名，实现域前置(domain fronting),达到更好的抗封锁效果。

**Comment by lhy0403** [comment]
Need more information, cc @DuckSoft thanks.

**Comment by DuckSoft** [comment]
已经将本 Issue 的一部分拆分到 #208。

**Comment by DuckSoft** [comment]
> v2ray内核已经支持自定义TLS SNI，但目前本软件并不支持(i2ray支持)。利用自定义TLS SNI可以在外层TLS和内层websocket中使用不同域名，实现域前置(domain fronting),达到更好的抗封锁效果。

方便的话，可以提供更多技术信息，以方便开发者进行实现吗？
再或者，若您能提供一个功能性的 Pull Request，我们将感激不尽。

**Comment by DuckSoft** [comment]
目前只在 `v2ray-core` 中的 https://github.com/v2ray/v2ray-core/issues/639 搜索到关于 SNI 的名词。
没有文档，没有头绪。我在网上也无法找到关于 SNI 的说明资料。

等待 Issue 作者回应。

**Comment by lhy0403** [comment]
那只是一个出站（或者入站） tag ？

**Comment by 9h5ej** [comment]
`{
  "inbounds": [
    {
      "port": 1080,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "123.231.132.213",
            "port": 443,
            "users": [
              {
                "id": "42852b93-4138-7232-c603-57f6a8e26712",
                "alterId": 64
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "/4598hgjrewiphgtrwbh",
          "headers": {
            "Host": "www.123.com"
          }
        },
       "tlsSettings": {
            "serverName": "www.microsoft.com",
           "allowInsecure": false
        }
      }
    }
  ]
}`
比如这样，外层的TLS SNI使用域名www.microsoft.com，内层的websocket请求头使用www.123.com,可以在访问www.123.com时让第三者觉得你在访问www.microsoft.com。目前微软的azure cdn支持这种做法，当vps套了azure cdn时可以实现更好的隐藏效果。

**Comment by DuckSoft** [comment]
请核收。@lhy0403

**Comment by lhy0403** [comment]
ACK, Will do after fixing Subscription update.

**Comment by 9h5ej** [comment]
另外还有一个问题就是"请修复取消勾选“绕过中国大陆”时DNS仍然不通过代理直接查询的问题"

上述配置可以确保DNS查询全部通过代理，而本软件经过抓包测试，无论如何设置，总会有一部分DNS请求不经过代理直接发送，在访问比较敏感的网站时非常危险，建议修复此问题。

**Comment by lhy0403** [comment]
我们能做到的只有这些，DNS请求是浏览器或者系统发送的，v2ray的管理范围只能仅限于把（系统发送到代理服务器的DNS请求重定向到指定的DNS服务器），而（系统直接发出的DNS请求）不会经由v2ray处理

**Comment by 9h5ej** [comment]
我用火狐浏览器(启用SOCKS5代理加上勾选代理DNS查询)使用上面的配置，可以确保DNS全部通过代理；而用qv2ray生成的配置时发现有些DNS请求直接发送了。

造成这一问题的主要原因应该是国内外分流设置不当。v2ray把收到的部分DNS请求直接发出去了。请看看分流策略里面是否有本地解析的因素 。

说实话，我非常讨厌分流功能，因为DNS解析是个难以解决的问题。本地解析会把浏览的网站泄露给ISP，远程解析会把国内网站解析到国外，预置数据库无法保证准确性。不知道为什么这些软件普遍默认开启分流，而且普遍不考虑DNS泄漏的问题。我现在用火狐浏览器开双实例，一个用于正常上网，另一个接入全局代理用于科学上网，感觉这样更安全。

**Comment by lhy0403** [comment]
> 我想说的问题是本软件生成的配置无论如何都会让v2ray把收到的DNS请求不经过代理直接发出去，这应该是分流方面设置不当造成的
> 
> 我用火狐浏览器(启用SOCKS5代理加上勾选代理DNS查询)使用上面的配置，可以确保DNS全部通过代理；而用qv2ray生成的配置时发现有些DNS请求直接发送了。
> 
> 造成这一问题的主要原因应该是国内外分流设置不当。v2ray把收到的部分DNS请求直接发出去了。请看看分流策略里面是否有本地解析的因素 。
> 
> 说实话，我非常讨厌分流功能，因为DNS解析是个难以解决的问题。本地解析会把浏览的网站泄露给ISP，远程解析会把国内网站解析到国外，预置数据库无法保证准确性。不知道为什么这些软件普遍默认开启分流，而且普遍不考虑DNS泄漏的问题。我现在用火狐浏览器开双实例，一个用于正常上网，另一个接入全局代理用于科学上网，感觉这样更安全。

你可以关闭分流功能试一下，帮助我们排除这个bug的可能性

**Comment by 9h5ej** [comment]
试过。抓包数据显示关闭分流功能时依然会有DNS请求被直接发送。

**Comment by DuckSoft** [comment]
已在最新的 dev 分支中实现。
![图片](https://user-images.githubusercontent.com/7822648/73612139-e64fa380-4623-11ea-908c-4731c33563fe.png)

Closing.
