### ISSUE TITLE
[v1] backporting high memory consumption fix for lts versions

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#211]

**Comment by lhy0403** [comment]
It's should not be the leaking of memory, but the consumption way too much of it instead.

**Comment by Qv2ray** [comment]
Added a limit of maximum line, please have a test.

**Comment by Qv2ray** [comment]
V1 is not supported since v2 is coming soon.

**Comment by DuckSoft** [comment]
Closing now!
