### ISSUE TITLE
Support multiple share link formats.

### ISSUE THREAD

**Issue by ghost** [Qv2ray/Qv2ray#252]
https://github.com/v2fly/vmessping/blob/master/vmess/vmess.go

Especially: 
https://github.com/v2fly/vmessping/blob/master/vmess/vmess.go#L278

**Comment by lhy0403** [comment]
That'll include:

1. Import auto-recognition.
2. Export/share options.

**Comment by Qv2ray-dev** [comment]
WIP, which will be (at lease) in the Qv2ray 2.1 version.

**Comment by Qv2ray-dev** [comment]
At the same time: https://github.com/shadowsocks/shadowsocks-org/issues/89

**Comment by Qv2ray-dev** [comment]
https://github.com/v2ray/discussion/issues/720

**Comment by Qv2ray-dev** [comment]
Assigned @DuckSoft

**Comment by Qv2ray-dev** [comment]
The standard mentioned in https://github.com/v2ray/discussion/issues/720 has been implemented.
