### ISSUE TITLE
Application closes when trying to close the preference dialog opened from system tray

### ISSUE THREAD

**Issue by HeavenlyChorus** [Qv2ray/Qv2ray#255]
To reproduce:
![image](https://user-images.githubusercontent.com/13861429/72605521-eaa76b80-3957-11ea-963e-c2cc523e4418.png)
Open *Preference* from system tray.

Whole application will be closed along with the *Preference* dialog.

**Comment by lhy0403** [comment]
There used to be a bug, and it was quite difficult to reproduce, can you provide a step, with which options you changed after opening the Preference window, made it crash.

**Comment by HeavenlyChorus** [comment]
hmm so it runs fine for u i assume?
I dont think i did anything that triggers this bug.
It seems that this has always been the case, for me.

**Comment by DuckSoft** [comment]
Cannot reproduce on Arch Linux x86_64 5.4.12, Qt 5.14, Qv2ray 1.99.5.2830.
Try provide with us your exact environment.

**Comment by HeavenlyChorus** [comment]
> Cannot reproduce on Arch Linux x86_64 5.4.12, Qt 5.14, Qv2ray 1.99.5.2830.
> Try provide with us your exact environment.

Windows 10 10.0.18362 and lastest release

**Comment by DuckSoft** [comment]
RCVD. Assigning to @lhy0403.

**Comment by DuckSoft** [comment]
This is soon going to be fixed by #305.

**Comment by Qv2ray-dev** [comment]
你好，经测试，这个问题已经在 https://github.com/Qv2ray/Qv2ray/actions/runs/35386393 中修复。
您可以尝试我们的 dev 版本（链接里即可下载）或等待一周后的 Qv2ray 2.1 版本
