### ISSUE TITLE
开启透明代理时不检测"~/.config/qv2ray/vcore"文件夹是否存在

### ISSUE THREAD

**Issue by codexvn** [Qv2ray/Qv2ray#275]
在开启透明代理时，软件会尝试将v2ray核心复制到文件夹"~/.config/qv2ray/vcore"，如果此时文件夹不是已有的，复制过程就会发生错误

**如何复现这个bug：**
1. 在文件夹"~/.config/qv2ray/vcore"不存在的情况下开启透明代理

**Qv2ray 本应该是怎样工作的？**
当此目录不存在时先创建一个此目录

**相关截图或日志**
![2020-01-24_00-51](https://user-images.githubusercontent.com/24852067/73005344-ca8a1780-3e43-11ea-9fab-c030bae92b50.png)
![2020-01-24_00-51_1](https://user-images.githubusercontent.com/24852067/73005348-cbbb4480-3e43-11ea-8179-fe5a7919e6de.png)

**系统信息**
 - 系统类型（windows, linux, macos）
    -  linux
 - 是从release下载的还是自己编译的
    - release
 - 首选项里的版本号：
    - v1.99.7.3082

**Comment by Qv2ray-dev** [comment]
@DuckSoft Please have a test of the latest dev branch with QV2RAY_DEFUALT_VCORE_PATH macro, it should be fixed now.

**Comment by DuckSoft** [comment]
问题修复了。
Closing.
