### ISSUE TITLE
Enable(set) system proxy will break gnome terminal

### ISSUE THREAD

**Issue by ymshenyu** [Qv2ray/Qv2ray#279]
![image](https://user-images.githubusercontent.com/39402395/73080577-046d2380-3f01-11ea-8e54-46726f02364f.png)
![image](https://user-images.githubusercontent.com/39402395/73080690-37afb280-3f01-11ea-9be6-02671f8695ac.png)

**Comment by DuckSoft** [comment]
Investigation in Progress.
