### ISSUE TITLE
WINDOWS下核心文件是不是只需要v2ray.exe即可？

### ISSUE THREAD

**Issue by leoxxx** [Qv2ray/Qv2ray#281]
如题

**Comment by DuckSoft** [comment]
需要四个文件。
geoip.dat   geosite.dat   v2ctl   v2ray

**Comment by leoxxx** [comment]
> 
> 
> 需要四个文件。
> geoip.dat geosite.dat v2ctl v2ray

了解了，谢谢。

**Comment by DuckSoft** [comment]
希望您在使用前仔细阅读使用说明。
https://github.com/Qv2ray/Qv2ray/wiki/Getting-Started-step0_zh

另外，若有其它问题，可考虑加入 https://t.me/qv2ray 用户群组讨论。

**Comment by haohowey** [comment]
> 希望您在使用前仔细阅读使用说明。
> https://github.com/Qv2ray/Qv2ray/wiki/Getting-Started-step0_zh
> 
> 另外，若有其它问题，可考虑加入 https://t.me/qv2ray 用户群组讨论。

按照https://github.com/Qv2ray/Qv2ray/wiki/Getting-Started-step0_zh配置核心，检测核心配置时报错：“核心退出代码255”

**Comment by haohowey** [comment]
我的是MAC系统

**Comment by Qv2ray-dev** [comment]
https://github.com/v2ray/v2ray-core/releases

你需要在这里下载 core

**Comment by haohowey** [comment]
> https://github.com/v2ray/v2ray-core/releases
> 
> 你需要在这里下载 core

是这下载的，只是必须要放到系统磁盘里才能执行
已解决，谢谢

**Comment by Qv2ray-dev** [comment]
好的
