### ISSUE TITLE
[建议]截图识别二维码时，最小化软件界面或者在托盘区图标中的右键菜单中加入截图功能

### ISSUE THREAD

**Issue by leoxxx** [Qv2ray/Qv2ray#283]
以避免遮档二维码。
顺便说一下，新版本CONFIG支持相对路径好评，可以便携化。

**Comment by DuckSoft** [comment]
收到。

**Comment by DuckSoft** [comment]
您好，请尝试使用软件自带的延迟截屏功能：
![图片](https://user-images.githubusercontent.com/7822648/73130451-6f1e7c00-4033-11ea-836f-a6e2029133e2.png)

**Comment by leoxxx** [comment]
> 
> 
> 您好，请尝试使用软件自带的延迟截屏功能：
> ![图片](https://user-images.githubusercontent.com/7822648/73130451-6f1e7c00-4033-11ea-836f-a6e2029133e2.png)

刚试了一下，非常不好用。

**Comment by DuckSoft** [comment]
> > 您好，请尝试使用软件自带的延迟截屏功能：
> > ![图片](https://user-images.githubusercontent.com/7822648/73130451-6f1e7c00-4033-11ea-836f-a6e2029133e2.png)
> 
> 刚试了一下，非常不好用。

您可另开一 Issue 反馈关于延迟截屏的体验问题。
自动最小化界面正在开发中。

**Comment by DuckSoft** [comment]
dispatched to @Qv2ray-Bot.

**Comment by leoxxx** [comment]
> 
> 
> > > 您好，请尝试使用软件自带的延迟截屏功能：
> > > ![图片](https://user-images.githubusercontent.com/7822648/73130451-6f1e7c00-4033-11ea-836f-a6e2029133e2.png)
> > 
> > 
> > 刚试了一下，非常不好用。
> 
> 您可另开一 Issue 反馈关于延迟截屏的体验问题。
> 自动最小化界面正在开发中。

我等新功能出来。

**Comment by leoxxx** [comment]
@Qv2ray-Bot 
gRPC已测。勾上HIDE后能正确识别二维码并转换成VMESS连接，但是点击导入后连接消失，连接未被导入。
顺便问一下，这个选项需要每次都手动勾选？不会记住上次设置？

**Comment by DuckSoft** [comment]
连接未被导入，很有可能是机场主没有遵循 Vmess 规范，自己瞎 ×× 写的 Vmess String。
这种情况下，烦请加入 https://t.me/qv2ray 用户交流群，私戳群主发送链接以便调试。
为了安全起见，您可在发送之后立即去机场更换订阅链接，防止链接被滥用。
我们也保证不会滥用测试链接。

**Comment by DuckSoft** [comment]
关于“记住二维码截图时隐藏窗口”的设定，将另外开启一个 Issue 用于跟踪。

**Comment by DuckSoft** [comment]
当前 Issue 已经解决，即将关闭。
若有其它问题，请另外开启 Issue。

**Comment by leoxxx** [comment]
> 
> 
> 连接未被导入，很有可能是机场主没有遵循 Vmess 规范，自己瞎 ×× 写的 Vmess String。
> 这种情况下，烦请加入 https://t.me/qv2ray 用户交流群，私戳群主发送链接以便调试。
> 为了安全起见，您可在发送之后立即去机场更换订阅链接，防止链接被滥用。
> 我们也保证不会滥用测试链接。

然而这个VMESS并不是你说的那样的问题。用HIDE截取的无法导入，但是用普通或延时的可以正常导入。二维码是同一个。
`vmess://eyJhZGQiOiJhdXRvLmZyZWV2Mi50b3AiLCJmaWxlIjoiIiwiaWQiOiJiOGFkNTBhZS1iNjY4LTRlMmQtYjdiNi1jNzU0NmNhYzM5YmQiLCJuZXQiOiJ0Y3AiLCJob3N0IjoiIiwicG9ydCI6IjE0ODY3IiwicHMiOiJmcmVldjIub3JnIiwidGxzIjoiIiwidiI6MiwiYWlkIjoxLCJ0eXBlIjoibm9uZSJ9Cg==`
