### ISSUE TITLE
qv2ray更新2.0之后配置错误

### ISSUE THREAD

**Issue by 178me** [Qv2ray/Qv2ray#286]
**简单描述这个 bug：**
使用Archlinux的pacman更新2.0后打开qv2ray就提示配置错误的对话框 
在之前代理连接没有问题

**如何复现这个bug：**
1. 
2. 
3. 
4. 

**Qv2ray 本应该是怎样工作的？**

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**
![UTOOLS1580122185032.png](http://yanxuan.nosdn.127.net/601756b1b57e1501b3b0a75c55c24c75.png)
```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - ArchLinux
 - 是从release下载的还是自己编译的
    - archlinux pacman 
 - 首选项里的版本号：
    - v2.0.0.3095

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*
我朋友跟我同样版本同样配置  他的代理使用正常
-

**Comment by 178me** [comment]
<img src="http://yanxuan.nosdn.127.net/601756b1b57e1501b3b0a75c55c24c75.png" alt="UTOOLS1580122185032.png" title="UTOOLS1580122185032.png" />
补上图

**Comment by DuckSoft** [comment]
图片不是很清楚。
您可删除 `/home/yzl178me/.qv2ray` 文件夹，再试启动一次。

**Comment by EvanMeek** [comment]
# 第一步
备份/home/yzl178me/.qv2ray目录下的vcore目录
> cp -r /home/yzl178me/.qv2ray/vcore /home/yzl178me/vcore
# 第二步
删除/home/yzl178me/.qv2ray
> rm -r /home/yzl178me/.qv2ray
# 第三步
重启qv2ray
> killall qv2ray && qv2ray
# 第四步
复制备份过的vcore至/home/yzl178me/.config/qv2ray内
> cp -r /home/yzl178me/vcore /home/yzl178me/.config/qv2ary
# 第五步
修改核心可执行文件路径为/home/yzl178me/.config/qv2ray/vcore
![test](https://user-images.githubusercontent.com/27056033/73170610-d6265880-4139-11ea-9bd3-0a9762014711.png)

**Comment by 178me** [comment]
我把加目录的配置文件删掉了 新的配置文件自动生成在.config下，然后把vcore目录copy进去  修改了常规选项的核心文件到vcore下。至此解决了问题
