### ISSUE TITLE
macOS 下系统代理切换功能失效

### ISSUE THREAD

**Issue by Eintler** [Qv2ray/Qv2ray#291]
**简单描述这个 bug：**
系统代理->启用系统代理
系统代理->禁用系统代理

无效,需要手动在macOS的代理选项勾选,才能生效

**系统信息**
 - 系统类型（windows, linux, macos）
    - macOS 10.15.3
 - 是从release下载的还是自己编译的
    - release
 - 首选项里的版本号：
    - v2.0.1.3100

**Comment by DuckSoft** [comment]
已核收。将分配 @Qv2ray-Bot 处理。

**Comment by Eintler** [comment]
@Qv2ray-Bot 如何查看简单配置类型?可以看到提示,但是无法通过Qv2ray设置成功,macOS 是10.15.3.

**Comment by DuckSoft** [comment]
> @Qv2ray-Bot 如何查看简单配置类型?可以看到提示,但是无法通过Qv2ray设置成功,macOS 是10.15.3.

您可加入我们的 Telegram 用户群组进行常规问题的讨论。
GitHub Issues 若用于解决一些常规问题，其往来通讯会令其他项目组成员的邮箱爆炸。
此外，交流也并不十分方便。

Telegram 群组（@qv2ray）：https://t.me/qv2ray

**Comment by Eintler** [comment]
@Qv2ray-Bot  谢谢您的及时跟进,我测试了一下,http的可以了,但是sock的代理还是不能设置成功.

**Comment by Eintler** [comment]
@Qv2ray-Bot  感谢🙏

**Comment by DuckSoft** [comment]
This is now fixed. Closing!!!!
