### ISSUE TITLE
某些二维码无法识别

### ISSUE THREAD

**Issue by leoxxx** [Qv2ray/Qv2ray#293]
比如这个
![vmess_70Aan](https://user-images.githubusercontent.com/5364709/73586041-26f3d380-44e3-11ea-9cf3-a4a8bb993087.png)
无论扫描还是从图片都无法识别，提示如下图。
![TIM截图20200201110857](https://user-images.githubusercontent.com/5364709/73586061-5dc9e980-44e3-11ea-91d6-f0d5d6e99930.png)
我用其它可识别的软件得出的VMESS连接可以手工导入到QV2RAY.

**Comment by DuckSoft** [comment]
皇帝的新二维码？

**Comment by DuckSoft** [comment]
调查结论：`zxing` 库对于大分辨率 QRCode 的处理有问题。
说人话：你把图片缩小点再扫描就能扫上了。
![图片](https://user-images.githubusercontent.com/7822648/73586564-f95e5880-44e9-11ea-9d3d-2ce69147ce81.png)

**Comment by leoxxx** [comment]
> 
> 
> 调查结论：`zxing` 库对于大分辨率 QRCode 的处理有问题。
> 说人话：你把图片缩小点再扫描就能扫上了。
> ![图片](https://user-images.githubusercontent.com/7822648/73586564-f95e5880-44e9-11ea-9d3d-2ce69147ce81.png)

https://github.com/zxing/zxing是这个吗？
但是我试了一下Barcode Scanner 4.7.8，在手机上随便扫一下就能识别。

**Comment by DuckSoft** [comment]
Barcode Scanner 和我们用的库是不一样的，它用的应该是 zbar 库，而我们用的 zxing 库可能对大图处理效果比较差劲。在电脑上，您可将图片缩小之后再进行扫描，以暂时规避这个问题。

我们正积极与上游取得联系，并且若有必要，将考虑更换 QRCode 后端。

**Comment by DuckSoft** [comment]
暂且关闭本 Issue。
若上游长时无反馈，吾等将考虑更换后端，届时重开。

**Comment by Qv2ray-dev** [comment]
已经确认上游修复了此问题（至少本 issue 中的二维码可以正确扫描）
