### ISSUE TITLE
PAC自定义

### ISSUE THREAD

**Issue by idweball** [Qv2ray/Qv2ray#297]
系统：Windows 10 X86_64 专业版
软件:  Qv2ray-refs.tags.v2.0.1-win64-gRPC.7z
是否编译安装: 否

问题:
1. 请问怎么自定义PAC？

**Comment by DuckSoft** [comment]
您可加入 Qv2ray User Group 与我们一起讨论。
Telegram 连接：https://t.me/qv2ray

顺便，这不是一个 bug，请不要使用 "bug" 类型的 Issue。
