### ISSUE TITLE
首次启动qv2ray会弹出警告框"Translation Failed"

### ISSUE THREAD

**Issue by adgnaf** [Qv2ray/Qv2ray#298]
**简单描述这个 bug：**

在Windows 10环境中，启动qv2ray.exe, 会弹出警告框"Cannot load translatino for en-US, English is now used."。

**如何复现这个bug：**
1. 在Win 10 环境中，启动qv2ray.exe。

**Qv2ray 本应该是怎样工作的？**
不弹出警告框。

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - Windows 10 
 - 是从release下载的还是自己编译的
    - release
 - 首选项里的版本号：
    - v2.0.1.3100

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by DuckSoft** [comment]
收到。分派给 @Qv2ray-Bot 调查。

**Comment by DuckSoft** [comment]
问题已修复。

**Comment by DuckSoft** [comment]
另外，这个问题不是永久出现的，也不会影响软件的正常使用。
我们将在 Release Info 中对此进行说明，减少对新用户的用户体验影响。

您可加入我们的 Telegram 用户群，与开发者和用户们一起讨论：
https://t.me/qv2ray
