### ISSUE TITLE
希望能有节点负载均衡的功能，如果一个节点失效了，可以自动切换节点

### ISSUE THREAD

**Issue by Jaytive** [Qv2ray/Qv2ray#299]
在ssr的pc工具用过这个功能，感觉很好用，一个节点失效后，会自动切换到另一个节点，并且自动屏蔽失效节点

**Comment by DuckSoft** [comment]
节点的负载均衡功能已经实现，在“复杂配置”功能中。
下图是我正在用的一个配置：
![图片](https://user-images.githubusercontent.com/7822648/73639138-c1e8db00-46a6-11ea-9baa-0c5e997ad019.png)

但是非常遗憾，v2ray 的负载均衡并没有你说的那个功能，v2ray 的负载均衡只是一个简单的随机目标选择器。

**Comment by DuckSoft** [comment]
不过，由于 v2ray 提供了统计信息接口，日后我们可以考虑间接实现这一功能。
即：对于一个现有的负载均衡实现，我们统计该负载均衡中节点的数据传输量、数据传输速度等信息，将信息反馈给用户，作为是否采用该节点进行负载均衡的参考。

限于 v2ray 核心的实际功能，我们能做的只有这么多。若您认为这个功能非常有必要在核心功能中实现，请反馈 https://github.com/v2fly/v2ray-core 项目。

**Comment by DuckSoft** [comment]
人话：
1. 简单的负载均衡，v2ray 本身支持
2. Qv2ray 已经实现 v2ray 的简单负载均衡功能
3. 节点失效自动切换节点功能，因 v2ray 本身限制，恐无法实现
4. 日后会针对已创建的负载均衡提供统计功能，让用户自己做决定 (Issue #300)

欢迎加入在 Telegram 上的 Qv2ray 用户组：
https://t.me/qv2ray

本 Issue 暂时关闭。
