### ISSUE TITLE
【建议or疑问】局域网代理功能似乎没有？

### ISSUE THREAD

**Issue by kingskill** [Qv2ray/Qv2ray#301]
想用局域网其他机子连接开了qv2ray的本机，本以为设置了http端口就可以了，没想到根本连不上。本机设了http端口10809，局域网地址192.168.1.9，ipad mini4设http代理连接不上。wifi处于同一网段。是不是qv2ray的代理功能仅限于本机？局域网连接是没有开发，还是说哪里的设置需要打开？

**Comment by DuckSoft** [comment]
在 Qv2ray 的首选项中找到入站设置，将监听地址从 127.0.0.1 改为 0.0.0.0 即可。

**Comment by DuckSoft** [comment]
#### 让网络上的其他设备使用代理

默认情况下，Qv2ray的代理配置是只监听`127.0.0.1`的地址，即其代理只有本机能够使用，如需让网络上的其他设备使用代理，需要修改这一配置：

- 若希望局域网（内网ip环境）或互联网（公网ip环境）中的所有设备都能够使用本机的Qv2ray提供的代理，则在“首选项-入站设置-监听地址”里，把默认的`127.0.0.1`改成`0.0.0.0`即可。
- 若希望几个具有特定ip的设备能够使用本机的Qv2ray提供的代理，由于v2ray的限制，同一个入站不支持监听多个指定的ip，可以有两种方式解决这个问题：
  - 通过复杂配置，建立多个不同的入站来实现，每个入站分别监听其中的一个ip。
  - Qv2ray的入站监听所有ip（`0.0.0.0`），在本机设置防火墙，只允许特定ip访问Qv2ray的代理的端口。

例子：若ip为`192.168.0.100`的设备希望使用代理，本机的ip为`192.168.0.50`。若本机的Qv2ray配置了一个端口为`12345`的http入站，监听ip`0.0.0.0`或`192.168.0.100`，则在`192.168.0.100`的设备上，可通过

```
export http_proxy="http://192.168.0.50:12345"
export https_proxy="http://192.168.0.50:12345"
```

使用此http代理（其他使用方式也类似）。

注意事项：

- 为让其他设备使用本机的Qv2ray提供的代理，除了本机的Qv2ray的代理需要监听目标设备的ip之外，还需要让目标设备能通过本机ip及代理端口访问到本机。因此，若本机设置了防火墙，则需要让防火墙放行对应端口；局域网环境里，可能需要关闭“内网隔离”“AP隔离”之类的设置，否则内网ip之间也无法互相访问。
- 如果本机没有设置防火墙，将Qv2ray的代理监听的ip设为`0.0.0.0`，且局域网没有设置“内网隔离”，则意味着局域网里所有的设备都能通过本机的ip及代理端口使用本机的Qv2ray提供的代理；如果本机是处于公网ip环境里，则意味着整个互联网中所有设备都能通过本机的ip及代理端口使用本机的Qv2ray提供的代理。因此，如确需在非可信任的局域网环境或公网ip环境中开启此种配置，最好配合防火墙，或配合代理身份验证，以防止本机的代理被滥用。

**Comment by DuckSoft** [comment]
https://github.com/Qv2ray/Qv2ray/wiki/Getting-Started-step4_zh#%E8%AE%A9%E7%BD%91%E7%BB%9C%E4%B8%8A%E7%9A%84%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E4%BD%BF%E7%94%A8%E4%BB%A3%E7%90%86

建议您通读用户指南。

**Comment by DuckSoft** [comment]
人话：

Q：局域网代理功能似乎没有？
A：有。默认没开。自己根据上面的说明调一下。

本问题暂时关闭。另外，关于软件使用方法的问题，建议您加入我们的 Telegram 用户群进行交流：
https://t.me/qv2ray

**Comment by kingskill** [comment]
谢谢。非常感谢。

**Comment by yuanzigsa** [comment]
非常感谢！永远支持！

**Comment by FashionGod** [comment]
> 出于安全性等原因考虑，Qv2ray 提供的代理，默认只有本机能使用。
> 
> 若您想分享给局域网的用户，请在 Qv2ray 的首选项中找到入站设置，将监听地址从 127.0.0.1 （即仅本机）改为 0.0.0.0 （即全部地址）即可。

如果设置了0.0.0.0还是不起作用呢？

**Comment by StarOnTheSky** [comment]
@FashionGod 检查一下本机的防火墙

**Comment by FashionGod** [comment]
![image](https://user-images.githubusercontent.com/53985999/229263315-05f58cf6-df1e-4932-b8f6-22f2948ad4e8.png)
感谢即时回答！  但是试了全部关掉了还是不行怎么办呀 @StarOnTheSky

**Comment by EpLiar** [comment]
印象中 Windows 会检查特定应用是否允许传入连接，检查过这个之后还是不行的话，那就只能抓包或者检查发起端的设置了

> 感谢即时回答！  但是试了全部关掉了还是不行怎么办呀 @StarOnTheSky

**Comment by FashionGod** [comment]
![image](https://user-images.githubusercontent.com/53985999/229263377-8868cbb0-ea8c-4926-b2d7-cc953694a0ea.png)
@DuckSoft @StarOnTheSky@EpLiar 大佬们看一下这是我配置的节点和首选项信息、是否有问题。

**Comment by StarOnTheSky** [comment]
@FashionGod 你的网络环境是什么样的？部分路由器开了 AP 隔离，使得内网间各个机器不能互相访问，可以排查一下这个。

**Comment by FashionGod** [comment]
> @FashionGod 你的网络环境是什么样的？部分路由器开了 AP 隔离，使得内网间各个机器不能互相访问，可以排查一下这个。

网络环境指的是什么 我感觉可能不是这个的问题？因为 我clash开允许局域网连接手机是可以用的。但是q2ray 设置0.0.0.0不行，我只知道区别是在clash上用的vmess节点 q2ray用的vless节点

**Comment by FashionGod** [comment]
会不会是节点应该用vmess？跟这个有关系吗？

> @FashionGod 你的网络环境是什么样的？部分路由器开了 AP 隔离，使得内网间各个机器不能互相访问，可以排查一下这个。

**Comment by EpLiar** [comment]
没有

> 会不会是节点应该用vmess？跟这个有关系吗？

你提到了 clash 打开局域网后可以，那你可以检查是否允许了特定应用的传入连接

**Comment by FashionGod** [comment]
> 没有
> 
> > 会不会是节点应该用vmess？跟这个有关系吗？
> 
> 你提到了 clash 打开局域网后可以，那你可以检查是否允许了特定应用的传入连接

  我查看了、q2ray相关的都是允许的状态、另外把防火墙全部关闭也试了、还是不行、是设置0.0.0.0后手机直接连路由器的wifi就行嘛？手机需要配置局域网的什么代理ip吗？

**Comment by EpLiar** [comment]
> 我查看了、q2ray相关的都是允许的状态、另外把防火墙全部关闭也试了、还是不行、是设置0.0.0.0后手机直接连路由器的wifi就行嘛？手机需要配置局域网的什么代理ip吗？

如果不配置，它没法得知你在那有个代理

顺带，检查的应该是 `v2ray.exe` 而不是 `qv2ray.exe`

**Comment by FashionGod** [comment]
![image](https://user-images.githubusercontent.com/53985999/229264356-27090659-39bf-41ad-accf-b4d3d04825d8.png)


> > 我查看了、q2ray相关的都是允许的状态、另外把防火墙全部关闭也试了、还是不行、是设置0.0.0.0后手机直接连路由器的wifi就行嘛？手机需要配置局域网的什么代理ip吗？
> 
> 如果不配置，它没法得知你在那有个代理
> 
> 顺带，检查的应该是 `v2ray.exe` 而不是 `qv2ray.exe`

查啦、顺带问一下如何配置局域网ip 如何查看qv2ray代理的ip是多少呀、 clash直接显示在界面上有个直接复制就行，但是qv2ray我不太会找🙌

**Comment by EpLiar** [comment]
> 查啦、顺带问一下如何配置局域网ip 如何查看qv2ray代理的ip是多少呀、 clash直接显示在界面上有个直接复制就行，但是qv2ray我不太会找🙌

看系统的网络设置

**Comment by FashionGod** [comment]
> > 查啦、顺带问一下如何配置局域网ip 如何查看qv2ray代理的ip是多少呀、 clash直接显示在界面上有个直接复制就行，但是qv2ray我不太会找🙌
> 
> 看系统的网络设置

感谢大佬细心给小白讲解！我琢磨明白了！谢谢以上回复的好心人！感谢有这样带领小白入门的互联网大环境！❤

**Comment by FashionGod** [comment]
> > 查啦、顺带问一下如何配置局域网ip 如何查看qv2ray代理的ip是多少呀、 clash直接显示在界面上有个直接复制就行，但是qv2ray我不太会找🙌
> 
> 看系统的网络设置

sorry我又来打扰、如果配置之后浏览器可以用 但是Instagram这种软件无法使用是为什么。抱歉小白问题比较多😂

**Comment by FashionGod** [comment]
> 

试了 国外的 手机应用app都不能用 只有safari浏览器可以访问谷歌

**Comment by EpLiar** [comment]
> sorry我又来打扰、如果配置之后浏览器可以用 但是Instagram这种软件无法使用是为什么。抱歉小白问题比较多😂

按照控制变量法来说，可以断定 Instagram 不认你的设置

**Comment by FashionGod** [comment]
> 

这就很头疼、又有新的问题、app不能用、浏览器可以用、qv2ray有没有什么全局代理的地方是不是没开启、0.0.0.0是不是就代表是全局代理了，感觉也不应该吧、有点想不明白不认设置是什么原因。

**Comment by EpLiar** [comment]
> 这就很头疼、又有新的问题、app不能用、浏览器可以用、qv2ray有没有什么全局代理的地方是不是没开启、0.0.0.0是不是就代表是全局代理了，感觉也不应该吧、有点想不明白不认设置是什么原因。

这个是 Instagram 自身的行为，如果它没有开放设置，用户无法干预
