### ISSUE TITLE
对 KCP 协议的主机使用 TCPing 导致延迟检测失败

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#302]
> 来自 Qv2ray User Group 的问题反馈

![图片](https://user-images.githubusercontent.com/7822648/73660423-1f931c80-46d3-11ea-9534-e944af861404.png)

**Comment by AshineDone** [comment]
Kcp is not security, prefer  use websocket to replace

**Comment by Qv2ray-dev** [comment]
WIP

**Comment by Qv2ray-dev** [comment]
Fixed by #621
