### ISSUE TITLE
从托盘打开首选项应用闪退

### ISSUE THREAD

**Issue by Beamze** [Qv2ray/Qv2ray#303]
**简单描述这个 bug：**
从托盘图标右键打开首选项，设置完成确定后，程序自动退出。

**如何复现这个bug：**
1. 托盘图标右键打开首选项
2. 打开入站设置选项卡
3. 勾选或取消设置系统代理（不限于这个设置，其他部分设置以然有效）
4. 点击"OK"
5.程序自动退出（BUG发生）

**Qv2ray 本应该是怎样工作的？**
不应退出，应重新连接

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 
未测试

**相关截图或日志**

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - windows
 - 是从release下载的还是自己编译的
    - release下载
 - 首选项里的版本号：
    - v2.0.1.3100

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by Qv2ray-dev** [comment]
你好，经测试，这个问题已经在 https://github.com/Qv2ray/Qv2ray/actions/runs/35386393 中修复。
您可以尝试我们的 dev 版本（链接里即可下载）或等待一周后的 Qv2ray 2.1 版本

**Comment by DuckSoft** [comment]
Fixed. Closing.
