### ISSUE TITLE
new mainwindow user interface plan

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#304]
some designs from @axionl:
![Qv2ray_UI_Draft-01](https://user-images.githubusercontent.com/7822648/75368066-25f46d00-58fc-11ea-9c37-4acf8ef8aa2f.png)

![Qv2ray_UI_Draft-02](https://user-images.githubusercontent.com/7822648/75368068-27259a00-58fc-11ea-8110-f7a4a111c938.png)

![Qv2ray_UI_Draft-03](https://user-images.githubusercontent.com/7822648/75368071-2856c700-58fc-11ea-9ee2-8a0f75b39a97.png)

![Qv2ray_UI_Draft-04](https://user-images.githubusercontent.com/7822648/75368073-2987f400-58fc-11ea-9ec5-446b599094dd.png)

![Qv2ray_UI_Draft-05](https://user-images.githubusercontent.com/7822648/75368082-2b51b780-58fc-11ea-8357-5478cfbf589e.png)

**Comment by Qv2ray-dev** [comment]
![5A80A57D-00C9-424B-BAD1-658EFE487229](https://user-images.githubusercontent.com/59914293/75095609-ae5bd080-55d1-11ea-8d61-134a9871dfe8.jpeg)

Just a temporary screenshot, things may change

**Comment by Qv2ray-dev** [comment]
I believe this can be marked as completed, for now, closing.
