### ISSUE TITLE
复杂模式编辑器中，按钮文字typo

### ISSUE THREAD

**Issue by yuguorui** [Qv2ray/Qv2ray#311]
**简单描述这个 bug：**

在进行编辑路由时（也即复杂模式），按钮的说明文字有一个typo。

**如何复现这个bug：**
1. 新建一个连接配置
2. 右键点击该配置文件后，编辑为复杂模式。

**Qv2ray 本应该是怎样工作的？**
下图中，入站区域下方的“添加出站”，应改为“添加入站”。

**相关截图或日志**
![图片](https://user-images.githubusercontent.com/6182414/74086876-32866200-4ac2-11ea-8082-40964b5fa6de.png)

**Comment by Qv2ray-dev** [comment]
@yuguorui @DuckSoft 翻译问题吧？

**Comment by DuckSoft** [comment]
完全抄收。

不过翻译问题要等到下一个 Release 才能合并。
先挂在这里吧。

**Comment by Qv2ray-dev** [comment]
Fixed in #305

**Comment by Qv2ray-dev** [comment]
@Qv2ray-dev 错了错了

**Comment by Qv2ray-dev** [comment]
Fixed
