### ISSUE TITLE
Qv2ray意料外的关闭

### ISSUE THREAD

**Issue by yuguorui** [Qv2ray/Qv2ray#312]
**简单描述这个 bug：**
在成功启动Qv2ray后，通过托盘图标打开“首选项”菜单后关闭窗口，会导致整个daemon退出（包括v2ray进程）。

PS: 通过主菜单打开“首选项”菜单不会触发这个bug。

**如何复现这个bug：**
1. 启动Qv2ray
2. 通过托盘图标打开“首选项”菜单后，关闭“首选项”窗口
3. daemon退出

**Qv2ray 本应该是怎样工作的？**
关闭首选项菜单不应导致后台进程的退出。

**相关截图或日志**
![1](https://user-images.githubusercontent.com/6182414/74087202-f3a5db80-4ac4-11ea-8022-49bef7b812c3.gif)

**系统信息**
 - 系统类型（windows, linux, macos）
    - Windows
 - 是从release下载的还是自己编译的
    - Release
 - 首选项里的版本号：
    - v2.0.1.3100

**Comment by DuckSoft** [comment]
Duplicate of #303 and #255.
已经修复过了，近日会发布。

> 经测试，这个问题已经在 https://github.com/Qv2ray/Qv2ray/actions/runs/35386393 中修复。

**Comment by Qv2ray-dev** [comment]
@yuguorui 这个问题已经修复，并将会在一周后的新版本中发布
建议提出问题之前先搜索一下相关issue

**Comment by yuguorui** [comment]
我错了，😂

**Comment by DuckSoft** [comment]
目前正临近新版本发布，您可使用 GitHub Actions 中的最新版本。

https://github.com/Qv2ray/Qv2ray/actions

**Comment by yuguorui** [comment]
Thanks.

**Comment by DuckSoft** [comment]
顺便，您可考虑加入我们的 Telegram 用户群组一同交流：

> https://t.me/qv2ray
