### ISSUE TITLE
路由编辑器中“规则标签”控件中的文字在编辑中无法完全删除

### ISSUE THREAD

**Issue by yuguorui** [Qv2ray/Qv2ray#313]
**简单描述这个 bug：**
在路由编辑器中，编辑“规则标签”对应的QLineEdit控件时，文字删除功能表现不正常。
- 使用Backspace删除时，会剩下最后一个字符。
- 使用全选+Backspace删除时，则完全无反应。

**如何复现这个bug：**
1. 创建新连接配置文件，右键选择“编辑为复杂配置”；
2. 点击“添加路由”创建一个新规则，并使用鼠标点击并选中规则；
3. 在右侧“规则设置”中的“规则标签”进行删除操作，会发现文字不能完全被删除。

**Qv2ray 本应该是怎样工作的？**
删除功能应正常运行，原有的标签文字应能完全删除。

**相关截图或日志**
![1](https://user-images.githubusercontent.com/6182414/74087893-51d5bd00-4acb-11ea-81da-2666bd7c8c12.gif)

**bug分析**
https://github.com/Qv2ray/Qv2ray/blob/master/src/ui/w_RoutesEditor.cpp#L823
问题在于，RouteEditor::on_ruleTagLineEdit_textEdited函数的处理上，当文本为空时会自动恢复之前的标签文本，使得文字删除功能表现异常。

```c++
void RouteEditor::on_ruleTagLineEdit_textEdited(const QString &arg1)
{
    if (arg1.isEmpty()) {
        ruleTagLineEdit->setText(CurrentRule.QV2RAY_RULE_TAG);
        return;
    }

    RenameItemTag(RENAME_RULE, CurrentRule.QV2RAY_RULE_TAG, arg1);
}
```

**Comment by Qv2ray-dev** [comment]
@yuguorui 这个是之前问题的临时解决方案，如果有rule tag 为空则会出现部分问题，暂时没有找到其他规避措施

**Comment by DuckSoft** [comment]
@yuguorui 的确有损用户体验。您若有好方法，欢迎 PR。

**Comment by huyizheng** [comment]
> @yuguorui 的确有损用户体验。您若有好方法，欢迎 PR。

qt里应该有“控件失去焦点”这个事件的吧。
我觉得“检测到文本框为空时恢复之前的文本”这个动作应该放在“文本框失去焦点”这个事件里执行，这样就既能保证这个文本框不会保存出空白的文本到配置里，也能保证用户随意编辑（因为用户删光文本时焦点还在文本框上，没有失去焦点）。

**Comment by Qv2ray-dev** [comment]
@huyizheng 我们当前的新计划是取消实时修改，添加 “重命名” 按钮。感谢您的建议

**Comment by Qv2ray-dev** [comment]
It should be fixed in the `dev` branch. Please check it out!

**Comment by Qv2ray-dev** [comment]
已经在即将发布的 Qv2ray v2.1 中进行了修复，谢谢您的反馈
