### ISSUE TITLE
QvAutoLaunch GenericName problem

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#324]
https://github.com/Qv2ray/Qv2ray/blob/a42eca7ff7a720717bfe9b5e1349e3ed1ca61fd6/src/components/autolaunch/QvAutoLaunch.cpp#L169

https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

<dl>
<dt>GenericName</dt>
<dd>Generic name of the application, for example "Web Browser".</dd>
</dl>

I think `v2ray frontend` is better.

**Comment by Qv2ray-dev** [comment]
They are copied by ShadowClash authors and then copied by @lhy0403 originally, who might forget to change it.

**Comment by DuckSoft** [comment]
confirmed.
