### ISSUE TITLE
IPv6 PAC Address is not handled

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#328]
https://github.com/Qv2ray/Qv2ray/blob/a42eca7ff7a720717bfe9b5e1349e3ed1ca61fd6/src/ui/w_MainWindow_extra.cpp#L95

**Comment by Qv2ray-dev** [comment]
I think... users should write a proper IPv6 address if they want to.

**Comment by DuckSoft** [comment]
> I think... users should write a proper IPv6 address if they want to.

I mean, you need to `[ ]` ipv6 addrs.

**Comment by Qv2ray-dev** [comment]
We'll suggest users add a pair of `[ ]` themselves in the Preference Window, and to build a backup plan, we will check if an IPv6 address has the bracket and add it if the user forgets to do so.

**Comment by Qv2ray-dev** [comment]
We will force check if an inbound listening IP is valid or not when accepting the Preference QDialog.
Existing users still need to change the settings since there's no such validity check within MainWindow.

Fixed.

**Comment by Qv2ray-dev** [comment]
Fixed in the preference window. Now closing, MainWindow is not touched to prevent duplicated checks.
