### ISSUE TITLE
proxyAddress is overriding inbound setting

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#329]
https://github.com/Qv2ray/Qv2ray/blob/a42eca7ff7a720717bfe9b5e1349e3ed1ca61fd6/src/ui/w_MainWindow_extra.cpp#L111

Whatever host you have in inbound, this is overridden into `localhost`.

**Comment by Qv2ray-dev** [comment]
Well inbound settings are for `listening` address, you don't want to set your system proxy to connect to some server at: `0.0.0.0`

Since Qv2ray and V2ray runs on the local PC, `localhost` is enough for now.
