### ISSUE TITLE
return value of SetSystemProxy is discarded

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#330]
https://github.com/Qv2ray/Qv2ray/blob/a42eca7ff7a720717bfe9b5e1349e3ed1ca61fd6/src/ui/w_MainWindow_extra.cpp#L125-L127

whether successful or not, this code reports success to user, leaving the `bool` return value of `SetSystemProxy` alone. This isn't good.

-------
tips: try use C++17 `[[nodiscard]]` modifier.

**Comment by Qv2ray-dev** [comment]
There's nothing to do with the return value if everything works properly, I meant properly tested before release since the runtime enviornment is relatively stable (compared to the tProxy one). 

Changing to `void`
