### ISSUE TITLE
Build failed: Failure to find: /xxx/Qv2ray/libs/gen/v2ray_geosite.pb.cc & .h

### ISSUE THREAD

**Issue by alluLinger** [Qv2ray/Qv2ray#332]
**简单描述这个 bug：**

**qmake output:**
```
WARNING: Failure to find: /home/linger/Src/Qv2ray/libs/gen/v2ray_geosite.pb.cc
WARNING: Failure to find: /home/linger/Src/Qv2ray/libs/gen/v2ray_geosite.pb.h
```

**make output:**

```
../src/components/geosite/QvGeositeReader.cpp:2:10: fatal error: libs/gen/v2ray_geosite.pb.h: No such file or directory
 #include "libs/gen/v2ray_geosite.pb.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:17317: recipe for target 'QvGeositeReader.o' failed
```

**如何复现这个bug：**
1. `lrelease ./Qv2ray.pro `
2. `mkdir build && cd build`
3. `qmake ../`
4. `make`

**系统信息**
 - 系统类型（windows, linux, macos）
    - LinuxMint 19.3, QT 5.14.1
 - 是从release下载的还是自己编译的
    - build from dev  [commit 102c3d6](https://github.com/Qv2ray/Qv2ray/tree/102c3d606f5400649a951e150419abfadd0e5d52)

**Comment by DuckSoft** [comment]
Check these:
```
tools/unix-generate-api.sh
tools/unix-generate-geosite.sh
```

**Comment by ymshenyu** [comment]
@alluLinger 由于你使用的是基于Debian的系统 请按照[Debian control](https://github.com/Qv2ray/Distribution/blob/master/debian/control)来补全依赖

**Comment by alluLinger** [comment]
Thanks, fixed by install [https://github.com/Qv2ray/Distribution/blob/master/debian/control]( https://github.com/Qv2ray/Distribution/blob/master/debian/control)

**Comment by DuckSoft** [comment]
consider joining Qv2ray User Group @ Telegram:
https://t.me/qv2ray
