### ISSUE TITLE
选取BUG

### ISSUE THREAD

**Issue by leoxxx** [Qv2ray/Qv2ray#333]
详见GIF
![1](https://user-images.githubusercontent.com/5364709/74141812-94fe7000-4c32-11ea-870b-e8703c009d0e.gif)

**Comment by DuckSoft** [comment]
版本号？

**Comment by leoxxx** [comment]
> 
> 
> 版本号？

v2.0.1.3100

**Comment by DuckSoft** [comment]
临近新版本发布，烦请帮我们测试目前的最新快照（v2.0.1.3847）：
https://github.com/Qv2ray/Qv2ray/actions/runs/36899503

若此版本中无问题，您可关闭本 Issue。
若问题持续，请在此详细描述复现过程。

感谢。

**Comment by DuckSoft** [comment]
根据 @ymshenyu 的报告，已确定 Windows 版本存在此问题。

**Comment by leoxxx** [comment]
---------------------------
qv2ray.exe - 系统错误
---------------------------
无法启动此程序，因为计算机中丢失 api-ms-win-crt-runtime-l1-1-0.dll。尝试重新安装该程序以解决此问题。 
---------------------------
确定   
---------------------------
尴尬。

**Comment by Qv2ray-dev** [comment]
@leoxxx 建议安装 msvc 运行库

**Comment by ymshenyu** [comment]
@DuckSoft Nope 我的问题

**Comment by DuckSoft** [comment]
可能需要安装 MSVC 2019 运行库。

**Comment by leoxxx** [comment]
> 
> 
> @leoxxx 建议安装 msvc 运行库

![TIM截图20200210184218](https://user-images.githubusercontent.com/5364709/74143128-2cfd5900-4c35-11ea-9e8f-cdf16d7467fa.png)
我觉得是我这边缺少某个补丁，我是关闭自动更新的。之前有些游戏也是不能玩。已装2019。

**Comment by Qv2ray-dev** [comment]
https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

**Comment by leoxxx** [comment]
> 
> 
> https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows
任何DOWNLOAD连接都是404。我是WIN7X64。

**Comment by Qv2ray-dev** [comment]
Try this? https://www.microsoft.com/en-us/download/details.aspx?id=48234

**Comment by Qv2ray-dev** [comment]
经过调查，这个应该不是 MSVC 运行库的一部分，反而应该是 Windows 10 中启用的 Windows Universal C Runtime，即为 Windows 通用 C 运行时，

所有 Windows 10+ OS 都应该包含了这个文件，Windows 7 和 Windows 8(.1) 用户应该安装 https://www.microsoft.com/en-us/download/details.aspx?id=48234 这个更新 (KB 2999226)

FYI: https://www.computerworld.com/article/2992476/what-happened-to-windows-patches-kb-2999226-and-kb-3083710.html

请尝试

**Comment by Qv2ray-dev** [comment]
另外，这个 bug 应该在 https://github.com/Qv2ray/Qv2ray/commit/6a3aed46608ed3070cf5c16cb0a131abfa404660 这里已经进行了修复

**Comment by leoxxx** [comment]
https://github.com/Qv2ray/Qv2ray/suites/447849593/artifacts/1710216
测试通过。
请关闭。

**Comment by DuckSoft** [comment]
Thank you!
Closing.
