### ISSUE TITLE
vmess + ws + tls 方式加 sock5 前置代理 失败，在链接编辑中取消勾选前置代理可以正常使用

### ISSUE THREAD

**Issue by Qv2ray-dev** [Qv2ray/Qv2ray#337]
vmess + ws + tls 方式加 sock5 前置代理 失败，在链接编辑中取消勾选前置代理可以正常使用
 纯的 vmess 加 sock5 前置代理 成功
版本： Qv2ray-refs.tags.v2.0.1-win64-libqvb 
版本： V2Ray 4.22.1
@Qv2ray-dev
似乎是这个问题 https://github.com/v2ray/v2ray-core/issues/1736#issuecomment-568294665

_Originally posted by @rubnet in https://github.com/Qv2ray/Qv2ray/issues/266#issuecomment-584556206_

**Comment by Qv2ray-dev** [comment]
Upstream error
前置代理会忽略 StreamSettings @rubnet

**Comment by gudong321** [comment]
Marked

**Comment by Qv2ray-dev** [comment]
Closed due to inactivity.
BTW it's an upstream issue.
