### ISSUE TITLE
Leaky catch found in src/core/connection/Serialization.cpp

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#338]
This catch block does not free the caught exception, thereby leaking memory.
https://github.com/Qv2ray/Qv2ray/blob/e893fbe05b22671b4c17cbd1364f205f46f3fa53/src/core/connection/Serialization.cpp#L265-L269

**Comment by Qv2ray-dev** [comment]
@DuckSoft WIP

**Comment by DuckSoft** [comment]
Fixed. Closing.
