### ISSUE TITLE
v2.1.1 的 AppImage 在未安装 GCC7 或以上版本的运行库的 Linux 系统上爆炸

### ISSUE THREAD

**Issue by Refuel-ZL** [Qv2ray/Qv2ray#345]
/opt/Qv2ray.v2.1.1.linux-x64.qt5.14.1.AppImage: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /opt/Qv2ray/Qv2ray.v2.1.1.linux-x64.qt5.14.1.AppImage)

**Comment by DuckSoft** [comment]
Seems that we need process that AppImage issues.
@Qv2ray-dev

**Comment by zendo** [comment]
openSUSE gnome v2.1.1 启动正常

**Comment by Qv2ray-dev** [comment]
@Refuel-ZL 需要您提供一下 Distro 信息，尤其是 uname -a 的输出

**Comment by DuckSoft** [comment]
`Linux duckarch 5.5.2-zen1-1-zen #1 ZEN SMP PREEMPT Tue, 04 Feb 2020 18:56:23 +0000 x86_64 GNU/Linux` 启动正常。

@Refuel-ZL 请提供您所使用的操作系统的版本信息，以及内核版本。
您可使用命令 `uname -a` 查看。

**Comment by Refuel-ZL** [comment]
Linux zl-PC 5.5.1-050501-generic #202002011032 SMP Sat Feb 1 10:34:22 UTC 2020 x86_64 GNU/Linux

**Comment by ymshenyu** [comment]
@Refuel-ZL 由于appimage不包含c++运行时 请按照此[安装说明](https://snapcraft.io/docs/installing-snap-on-debian)安装snapd, 然后使用 ```sudo snap install qv2ray --edge --devmode``` 安装最新版本的Qv2ray

**Comment by DuckSoft** [comment]
问题已定位。正在修复中。

**Comment by Qv2ray-dev** [comment]
Should be fixed by this release: https://github.com/Qv2ray/Qv2ray/releases/tag/v2.1.2

**Comment by ymshenyu** [comment]
close
