### ISSUE TITLE
为什么每次弹窗提示有新版本之后都要自动退出正在运行的程序？

### ISSUE THREAD

**Issue by VDerGoW** [Qv2ray/Qv2ray#349]
如题，新版本弹窗提示有新版后，点Yes就会自动退出当前正在运行的Qv2ray程序。

如果我想更新，就要到GitHub下载新版，但是下载速度大家懂的，要开代理才能下载，这就又要去文件夹里找可执行文件重新打开qv2ray，还得忽略它再次弹出的新版提示。

**Comment by Qv2ray-dev** [comment]
请，，详细描述一下您遇到的问题？

**Comment by DuckSoft** [comment]
收到。处理中。

**Comment by VDerGoW** [comment]
> 请，，详细描述一下您遇到的问题？
> 请包括 OS版本，Qv2ray 版本号（可在首选项中找到） 和实际进行的操作
> 
> 您可以到 [release 页面](https://github.com/Qv2ray/Qv2ray/releases) 找到旧版 Qv2ray 下载进行复现

**问题的详细描述：**
以qv2ray v2.0.1为例，运行应用，几秒后应用会弹窗提示更新：
![image](https://user-images.githubusercontent.com/11539008/74416877-b9e82280-4e80-11ea-92b6-5a4827935451.png)

此时无论我是选择**Yes**、**No**或者**Ignore**，当前正在运行的qv2ray应用都会结束，不知道是自动退出还是异常退出。

+ qv2ray版本：1.99、2.*版本都有此问题
+ 操作系统：Windows 10 专业版64位，多台电脑上都有此问题

**Comment by Qv2ray-dev** [comment]
@VDerGoW 收到

**Comment by Qv2ray-dev** [comment]
您可以尝试使用 https://github.com/Qv2ray/Qv2ray/actions/runs/38214562 里面的版本来检测 v2.1.1 吗？
我们在 2.1.0 中修改了一些参数，但是 v2.1.0 

另外，烦请使用 cmd 用以下参数启动 Qv2ray （2.1.0）：

```
qv2ray.exe > log.txt
```

并在运行，bug产生之后，发送一下产生的 log.txt

**Comment by VDerGoW** [comment]
> 您可以尝试使用 https://github.com/Qv2ray/Qv2ray/actions/runs/38214562 里面的版本来检测 v2.1.1 吗？
> 我们在 2.1.0 中修改了一些参数，但是 v2.1.0
> 
> 另外，烦请使用 cmd 用以下参数启动 Qv2ray （2.1.0）：
> 
> ```
> qv2ray.exe > log.txt
> ```
> 
> 并在运行，bug产生之后，发送一下产生的 log.txt

使用上面链接中的版本运行后一切正常，没有出现自动退出应用的情况。

**Comment by DuckSoft** [comment]
@VDerGoW 那看来是修了

**Comment by Qv2ray-dev** [comment]
那么，此问题可以被关闭
如果您有新的问题，可以提交一个新的 issue 
感谢您的反馈！
