### ISSUE TITLE
开机， 点击忽略更新后，应用没有自动启动

### ISSUE THREAD

**Issue by Solar-Lancelo** [Qv2ray/Qv2ray#350]
版本：
- v2.0.0.3095
- Ubuntu 18.04

Bug描述：
- 开机，软件提示更新，点击忽略更新后，应用没有如往常自动启动。

**Comment by Qv2ray-dev** [comment]
Duplicated #349

**Comment by Qv2ray-dev** [comment]
#349 已经关闭，表示 Qv2ray 2.1.1 中已经没有此问题

那么，此问题可以被关闭
如果您有新的问题，可以提交一个新的 issue
感谢您的反馈！
