### ISSUE TITLE
能否支持mac的较低版本，谢谢

### ISSUE THREAD

**Issue by hexd2019** [Qv2ray/Qv2ray#360]

**Comment by DuckSoft** [comment]
您好，理论上是可以的。

目前我们的 macOS 发行使用的是 GitHub Actions 提供的 macOS 镜像，因此，对于操作系统的版本上，我们无法进行选择，默认只能使用其提供的最新版本。

若您确实有需要，您可告知我们您操作系统的版本（如 macOS Catalina）。我们会寻找有意向的志愿者为您进行编译。您也可以尝试在您的系统上进行手动编译。

ps: Qv2ray 全体开发人员没有任何一个人拥有 macOS 设备（大概是穷的）。

**Comment by hexd2019** [comment]
我的OSX EI Capitan，因为多数都不支持这种老一点的系统，所以拜托了，可用的话可以赞助点。另外我的mac很便宜，国外买的，国内编程各种神仙一般喜欢自己熟悉的系统环境吧，哈哈，再次感谢你们的付出！
