### ISSUE TITLE
订阅故障

### ISSUE THREAD

**Issue by MarksonHon** [Qv2ray/Qv2ray#361]
**简单描述这个 bug：**
添加多个订阅时，输入第二个订阅的链接之时会把第一个订阅的链接替换掉，然后第二个订阅里面不会有订阅链接。

**如何复现这个bug：**
1. 添加一个订阅
2. 添加第二个订阅，输入的链接会替换掉第一个订阅的，且第二个订阅不会保存链接。
3. 
4. 

**Qv2ray 本应该是怎样工作的？**
订阅的重命名与更新应当分开，不同订阅之间不能互相干扰。

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - 
 - 是从release下载的还是自己编译的
    - 
 - 首选项里的版本号：
    - 

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by DuckSoft** [comment]
要更新订阅。

**Comment by DuckSoft** [comment]
暂时关闭本 Issue。

Qv2ray 正在计划对用户界面进行一次较大的优化，届时会改善该方面的体验。

**Comment by Qv2ray-dev** [comment]
Should be fixed within the new ConnectionManagement model.
