### ISSUE TITLE
【提议】对trojan、ss、ssr的支持

### ISSUE THREAD

**Issue by strsikin** [Qv2ray/Qv2ray#362]
现在好多都链接不稳定，经常换来换去的，软件太多了。
能否逐渐支持其它的。
比如最新的trojan，linux系统都考虑纳入了，所以能否考虑加入，好在win上使用

**Comment by DuckSoft** [comment]
你好。首先感谢您的提议。咱先说人话：
* 已经支持 Shadowsocks 了（因为 v2ray-core 支持）
* 不支持 ShadowsockR （因为 v2ray-core 不支持）
* 日后可能会支持 Trojan（如果 v2ray-core 打算支持的话）

下面是鬼话：
我们 Qv2ray 作为 v2ray-core 的一个直接的图形前端，受制于核心本身的功能。
如果您认为这些支持有必要，可向上游 v2ray-core 反映。

最后，感谢您的反馈。

**Comment by strsikin** [comment]
你好，
Trojan的协议比v2ray还要简单，只有三项。
同样Trojan也是像v2ray-core一样，是没有图形界面的，所以觉得实现起来比较简单吧。
大概就是一个重启+换内核

**Comment by Qv2ray-dev** [comment]
@strsikin 你好，据我所知，Trojan 有一个 GUI

**Comment by DuckSoft** [comment]
> 你好，
> Trojan的协议比v2ray还要简单，只有三项。
> 同样Trojan也是像v2ray-core一样，是没有图形界面的，所以觉得实现起来比较简单吧。
> 大概就是一个重启+换内核

您好，Qv2ray 的定位不在于支持 Trojan 等各种其他内核，希望您能理解。

**Comment by strsikin** [comment]
我也只是一个期望，就算不做我也同样喜欢这个项目的

**Comment by Qv2ray-dev** [comment]
Reopened as a future tracker.

**Comment by Qv2ray-dev** [comment]
Together with the introduction of the Plugin subsystem, multi-kernel connection configs will be supported by Qv2ray.

The functionality will come with Qv2ray v3.0

**Comment by Qv2ray-dev** [comment]
@strsikin Please wait for a prerelease of Qv2ray v2.5.0-pre1 recently.

The plugin system has SSR/Trojan support already.

**Comment by gudong321** [comment]
在新特性中，Trojan支持前置代理吗？

**Comment by Qv2ray-dev** [comment]
> 在新特性中，Trojan支持前置代理吗？

目前来看还是不支持的，不过我不明白您所说的前置代理的集体实现方法，如果有相关文档的话，我们很愿意进行研究

**Comment by Qv2ray-dev** [comment]
Qv2ray 2.5.0-pre1 已经实现支持 Trojan/ssr，v2ray 自带部分ss支持，issue 关闭
