### ISSUE TITLE
Remove Qt version from release files

### ISSUE THREAD

**Issue by kidonng** [Qv2ray/Qv2ray#363]
Hello, lukesampson/scoop-extras#3582 is adding Qv2ray to [Scoop](http://github.com/lukesampson/scoop) (Windows package manager like Chocolatey and Homebrew)'s package repository, but Qt version in release files will prevent manifests from auto updating.
Could you please remove Qt version from release files, and mention them in other place (like release notes)? This should be a trivial change, but feel free to reject it if you have other concerns.

**Comment by Qv2ray-dev** [comment]
Sorry I didn't quite get your point.
Did you mean to remove "qt-5.14.1" from the file name or to eliminate Qt dlls from the release zipball?

**Comment by zendo** [comment]
就是文件名，scoop 脚本能识别发布的版本号，但对后面版本不一的qt文件名就没办法。
scoop 通常这样写的：
https://github.com/h404bi/dorado/blob/master/bucket/clash-for-windows.json

**Comment by skt041959** [comment]
@Qv2ray-dev 
> * remove "qt-5.14.1" from the file name
Yes, just remove the Qt version from file name. Since you have bundled Qt dlls in the package, the Windows users just don't need to care about the Qt version.

**Comment by kidonng** [comment]
> * remove "qt-5.14.1" from the file name

That's what I mean, sorry for elaborating on what does "removing" mean. "Renaming" may sound better.

**Comment by Qv2ray-dev** [comment]
Thanks a lot, @kidonng and @skt041959 .
From now on, the Qv2ray release will only contains qt5.13.2 so I may able to remove the qt version string.

Do you think a filename like `Qv2ray.v2.1.2.Windows-x64.7z` would help? If so, I'd love to change it.

**Comment by kidonng** [comment]
> Do you think a filename like `Qv2ray.v2.1.2.Windows-x64.7z` would help? If so, I'd love to change it.
> 
> Generally speaking, the file name structure will be: `Qv2ray.$TAG.Windows-{x86, x64}.7z`

👌

**Comment by Qv2ray-dev** [comment]
Great, @kidonng 
For now I just leave this issue open to track the progress, it'll be closed after changes are made.

**Comment by DuckSoft** [comment]
- [ ] reformat for the current win32/64 releases
- [ ] adjust the push-build / prerelease-build automation accordingly

**Comment by DuckSoft** [comment]
This shall be fixed now. Closing!

**Comment by Qv2ray-dev** [comment]
@kidonng @zendo @skt041959 

The new file name in the release will be here: https://github.com/Qv2ray/Qv2ray/releases/tag/vTest

Where vTest will be replaced with v2.2.0 when we release and the filename becomes:

`Qv2ray.v2.2.0.Windows-x86.7z`
`Qv2ray.v2.2.0.Windows-x64.7z`


Are they good to go?
