### ISSUE TITLE
v2ray core close_waiting depletes all ports

### ISSUE THREAD

**Issue by sunchaothu** [Qv2ray/Qv2ray#364]
**简单描述这个 bug：**

不确定是不是 QV2Ray 还是V2ray 内核。
其中 1.64.250.60 是应该是我的代理地址，233是端口；从截图可以看到 close_waiting 用光了所有端口，然后其他需要网络服务的会报 `由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。`
![image](https://user-images.githubusercontent.com/14788898/74645945-d1dae180-51b3-11ea-8903-709b3c0fafa2.png)

![image](https://user-images.githubusercontent.com/14788898/74646259-6e04e880-51b4-11ea-892b-f964a168db91.png)

**如何复现这个bug：**
1. 
2. 
3. 
4. 

**Qv2ray 本应该是怎样工作的？**

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - windows
 - 是从release下载的还是自己编译的
    - release 下载的
 - 首选项里的版本号：
    - v2.0.1.3100

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by sunchaothu** [comment]
关掉 QV2ray 就好了

**Comment by DuckSoft** [comment]
应该是内核问题。
你用 `netstat -anp` 看看是哪个进程。

**Comment by DuckSoft** [comment]
https://github.com/v2ray/v2ray-core/issues/398
https://github.com/v2ray/v2ray-core/issues/370

**Comment by DuckSoft** [comment]
您可能使用了过于古老的 v2ray 内核版本。

**Comment by sunchaothu** [comment]
好，谢谢，既然不是新问题 我关了吧
