### ISSUE TITLE
Can not run the Linux version.

### ISSUE THREAD

**Issue by fire7night** [Qv2ray/Qv2ray#367]
Error:
  qv2ray: symbol lookup error: /usr/lib/x86_64-linux-gnu/libGL.so.1: undefined symbol: g_PrlGBMApi

1. version: v2.1.2
2. file: Qv2ray.v2.1.2.linux-x64.qt5.13.2.AppImage
3. system: Ubuntu Lts 18.04
4. gcc version: 7.4.0

The version v2.1.1 is working.

**Comment by DuckSoft** [comment]
cc @ymshenyu

**Comment by ymshenyu** [comment]
![image](https://user-images.githubusercontent.com/39402395/74745050-3ecaa600-529e-11ea-8f33-223bdb934edd.png)
working well on my ubuntu 18.04

**Comment by DuckSoft** [comment]
Please provide with us the output of the following command:
`readelf -s /usr/lib/x86_64-linux-gnu/libGL.so.1`

**Comment by DuckSoft** [comment]
Cannot reproduce.

**Comment by fire7night** [comment]
emmm.....That‘s weird. This is true on both virtual machines, is it a virtual machine problem？

**Comment by fire7night** [comment]
output of  
                 readelf -s /usr/lib/x86_64-linux-gnu/libGL.so.1   :
[log.txt](https://github.com/Qv2ray/Qv2ray/files/4220315/log.txt)

**Comment by DuckSoft** [comment]
There are strange symbols in your `libGL.so.1`.
Maybe you are using a timed third-party graphic driver?
Anyway, you may try compiling Qv2ray on Ubuntu yourself, or use the [snap](https://snapcraft.io/qv2ray) from @ymshenyu.

**Comment by fire7night** [comment]
I create the virtual machine by Parallels Desktop. There maybe something wrong with it. OK, I will try in other way.

**Comment by flymaxty** [comment]
You need to disable **3D acceleration** on parallels preference（your-virtual-system Configuration->Graphics)

Looks like Prallels has a customize graphics driver for ubuntu, which can provide 3D acceleration, but less compatibility.

Disable **3D acceleration** will make your virtual ubuntu system to use LLVM instead of Parallels Griphics driver.

**Comment by DuckSoft** [comment]
> You need to disable **3D acceleration** on parallels preference（your-virtual-system Configuration->Graphics)
> 
> Looks like Prallels has a customize graphics driver for ubuntu, which can provide 3D acceleration, but less compatibility.
> 
> Disable **3D acceleration** will make your virtual ubuntu system to use LLVM instead of Parallels Griphics driver.

Good answer is never late! Appreciate!

**Comment by fire7night** [comment]
cool~

**Comment by edimetia3d** [comment]
I encountered the same error lately when using ubuntu 18/20 in PD.

it seems that it was the appimage bundled wrong qt lib.

install from .deb file solved the issue

**Comment by waitingyou** [comment]
> You need to disable **3D acceleration** on parallels preference（your-virtual-system Configuration->Graphics)
> 
> Looks like Prallels has a customize graphics driver for ubuntu, which can provide 3D acceleration, but less compatibility.
> 
> Disable **3D acceleration** will make your virtual ubuntu system to use LLVM instead of Parallels Griphics driver.

Cool~~~Thank you very much ！
