### ISSUE TITLE
可否隐藏掉程序坞上的软件图标?

### ISSUE THREAD

**Issue by HelloXiaoxi** [Qv2ray/Qv2ray#370]
就是只要打开软件,程序坞就会驻留软件图标,可否隐藏呢?
<img width="228" alt="截屏2020-02-19下午2 10 51" src="https://user-images.githubusercontent.com/25526254/74806691-a4ac4180-5321-11ea-842b-f6d1c3053817.png">

**Comment by Qv2ray-dev** [comment]
好的，我们会调查此问题

**Comment by whoisnian** [comment]
https://github.com/keepassxreboot/keepassxc/issues/1334
可以试试在Info.plist里把LSUIElement改成1，似乎会有一些副作用。

**Comment by Qv2ray-dev** [comment]
@whoisnian 这个问题需要主窗口的 hide 函数配合，修改 info plist 会直接禁用掉 dock 上面的 icon

**Comment by Qv2ray-dev** [comment]
For tracker: see #408

**Comment by DuckSoft** [comment]
迟来的更新：将于下一版本中解决此问题。
敬请期待。

**Comment by BMAN-CJ** [comment]
一个图标过小问题，但是是发生gnome top bar上，
环境：
- 2k分辨率，系统100%缩放，字体1.5缩放
- Qv2ray version：v2.4.0.5000

**Comment by DuckSoft** [comment]
> 一个图标过小问题，但是是发生gnome top bar上，
> 环境：
> 
>     * 2k分辨率，系统100%缩放，字体1.5缩放
> 
>     * Qv2ray version：v2.4.0.5000

1. 本 Issue 是关于 Mac OS 的 Dock 问题的
2. gNoMe 顶栏应该是他自己的问题，你也许该看看别的方案，或者和顶栏作者反馈 bug

**Comment by Qv2ray-dev** [comment]
fixed, so closing!
:heart:

**Comment by ZHOUXING1997** [comment]
配置里面哪一项可以实现这个效果？
