### ISSUE TITLE
May I disable update notice?

### ISSUE THREAD

**Issue by libook** [Qv2ray/Qv2ray#371]
**Briefly describe this bug：**
Hi, thanks for your work on Qv2ray.
I am using Arch Linux and using AUR to manage Qv2ray. So I don't need the native update notice. All I need is updating all packages with my package manager.
Would you please show me a way to disable the native update notice?

**How can I trigger this bug：**

1. While there is a new update.
2. Boot OS and log in.
3. Then you can see the native update notice.

**What is expected to happen**
Anyone can find a switch in Preferences that can control the native update notice.

**Screenshots**
If you need one, please tell me which kind do you need.

**System Information**

 - OS Type: Linux
 - Self build. Using yay package manager download from [AUR](https://aur.archlinux.org/packages/qv2ray/) and automatically build.
 - v2.1.1.3861

**Other Info**

Thanks for your reviewing.

*Please hide your server address and UUID if you wish to post the vmess string or your connection setting.*

**Comment by Qv2ray-dev** [comment]
Yes, but not currently available.
We may consider adding a DISABLE_AUTO_UPDATE flag in the build system, to let package managers handle the updates themselves.

BTW you may want to use the `qv2ray` package within the `archlinuxcn` repo instead of building AUR by self.

**Comment by libook** [comment]
Okay, I am happy to wait this new feature.

About `archlinuxcn` . It seems a good choice. But I am not using vanilla version of Arch Linux. I have to build by myself for lots of packages. So this source may not suit me.
Thanks for your advice.
