### ISSUE TITLE
加入对 ssd:// 协议的支持

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#372]
Specs: https://github.com/TheCGDF/SSD-Windows/wiki/HTTP%E8%AE%A2%E9%98%85%E5%8D%8F%E5%AE%9A

**Comment by DuckSoft** [comment]
Draft completed. 
坑可能还很多，准备提交。

**Comment by Qv2ray-dev** [comment]
SSD protocol has some conflicts with our current connection import model.
We'll try to make them compatible.

**Comment by Qv2ray-dev** [comment]
Added, closing.
