### ISSUE TITLE
Always error, the error is: V2ray core executable not found

### ISSUE THREAD

**Issue by StephenYoungYang** [Qv2ray/Qv2ray#375]
Always pop-up an error message, V2ray core executable not found. My os is ubuntu 19.10. Does anyone else encounter this problem?

**Comment by DuckSoft** [comment]
Need some help?

You may refer to that documentation: https://github.com/Qv2ray/Qv2ray/wiki
Or, join us at Telegram: https://t.me/qv2ray

FYI: Qv2ray itself does not come with v2ray-core.

**Comment by StephenYoungYang** [comment]
I've got that doc. So I closed this issue. Thanks for your replay.

**Comment by acgtyrant** [comment]
我 Arch Linux，已安装 v2ray、v2ray-geoip 和 v2ray-domain-list-community，但依然遇到这错误，不得不在 Preference 去手动修改相关目录。

**Comment by Qv2ray-dev** [comment]
It's a known bug that default paths are not being applied when initializing the config file.
@acgtyrant

**Comment by DuckSoft** [comment]
@acgtyrant 你可能是旧版配置的受害者

**Comment by DuckSoft** [comment]
Arch Linux 版本会自动帮你配置核心路径，不需要人工干预。默认核心应该在/usr/bin/v2ray或者/usr/lib/v2ray/v2ray，资源文件夹在/usr/lib/v2ray。
