### ISSUE TITLE
Windows10白色主题下托盘图标难以看清

### ISSUE THREAD

**Issue by unnamed42** [Qv2ray/Qv2ray#376]
版本：v2.1.2.3861
来源：Github release
操作系统：Windows 10 1909
第三排第一个就是qv2ray
![批注 2020-02-23 123849](https://user-images.githubusercontent.com/14161220/75103714-7ab49100-5639-11ea-9701-8bb61a0da478.png)

**Comment by DuckSoft** [comment]
您好，首选项中可以调节托盘图标颜色主题。
设置后请重启软件以充分应用。

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/75103758-34abfd00-563a-11ea-9f2e-5ddec4957408.png)
将此处的“深色模式托盘图标”禁用即可。

**Comment by unnamed42** [comment]
@DuckSoft 已解决，谢谢
