### ISSUE TITLE
因机场设置不存在的 tcp 混淆方式 wechat-video 导致 Qv2ray 异常一例

### ISSUE THREAD

**Issue by wowsonsun** [Qv2ray/Qv2ray#378]
![深度截图_20200225010940](https://user-images.githubusercontent.com/23351005/75180010-42669d00-5776-11ea-87b6-805a901f11b0.png)

不支持传输协议(network)下的伪装类型（type）导致报错了。

deepin 15.11 系统

**Comment by DuckSoft** [comment]
您好，可以更明确地描述您的问题吗？

**Comment by DuckSoft** [comment]
您好，tcp 下原本就没有 wechat-video 的混淆选项。
wechat-video 混淆选项属于 QUIC 协议。

以下信息供您参考：
1. https://v2ray.com/chapter_02/transport/quic.html#headerobject
2. https://v2ray.com/chapter_02/transport/tcp.html#httpheaderobject

**Comment by DuckSoft** [comment]
另：欢迎加入 Qv2ray 用户组 Telegram 群与我们一同讨论。
https://t.me/qv2ray

**Comment by wowsonsun** [comment]
谢谢回答，谢谢你提供的这个软件。请允许我说出我的疑惑。

1. win 版和 Android 版的 `v2rayN` 是可以用我这个服务的
2. 看了你给出的文档，确实没有说明 `tcp` 下 `wechat-video` 是可选的混淆，但也没有说明这是不可选的
3. 谢谢

**Comment by Qv2ray-dev** [comment]
您好，由于你的报错来自于 v2ray 内核而非 Qv2ray，（即以上截图内容是v2ray生成的），我们建议您跟机场方面联系

**Comment by DuckSoft** [comment]
咱有眉目了。可能是 Vmess 导入的时候我们的分析错误。
为避免泄漏您的隐私信息，您可否加群与开发者私聊呢？

**Comment by DuckSoft** [comment]
您好，请问能否提供一个用于复现问题的 Vmess 连接？
cc @Qv2ray-dev

**Comment by DuckSoft** [comment]
非常神奇。就算写的是 tcp，v2rayN 竟然能正常识别这种连接，导出还是 tcp。
MAGIC！

TODO: Fix This Magic

**Comment by wowsonsun** [comment]
非常期待修复，现在用的Linux就你们这个工具比较方便可用了

**Comment by Qv2ray-dev** [comment]
@wowsonsun It's been fixed within the `dev` branch. If you want early-access, you may download the fix from the Github Acrion

**Comment by wowsonsun** [comment]
问题还是有

![深度截图_选择区域_20200315170801](https://user-images.githubusercontent.com/23351005/76698587-d07fd480-66df-11ea-8e07-7ac99fec7518.png)

**Comment by Qv2ray-dev** [comment]
给个链接？  @wowsonsun

**Comment by wowsonsun** [comment]
![image](https://user-images.githubusercontent.com/23351005/76698625-45530e80-66e0-11ea-8a9d-5da3604fcb41.png)
版本 2.2.0.4710

**Comment by Qv2ray-dev** [comment]
我们需要一个用于复现问题的 vmess

**Comment by DuckSoft** [comment]
您好，请您至少提供一个有此问题的 vmess 链接给我们。
若您认为 GitHub 不安全，您可：
1. 使用您认为安全的邮件服务，发送邮件到 qv2ray@protonmail.com。
2. 加入我们在 Telegram 的 [Qv2ray 开发群组](https://t.me/qv2ray)，将链接 PM 给开发人员。

**Comment by DuckSoft** [comment]
@wowsonsun 请您复查最新版本是否仍有此情况。

**Comment by Qv2ray-dev** [comment]
The latest `master` branch version respects the transport protocol more than the obfs type.
Closing.
