### ISSUE TITLE
将 vmess:// 地址作为订阅地址导入导致失败一例

### ISSUE THREAD

**Issue by YJHelloWorld** [Qv2ray/Qv2ray#379]
**简单描述这个 bug：**
Ubuntu 16.04 , 安装最新版本的qv2ray（通过snap和appimage两种途径）， 然后在subscriptions里面输入 

`vmess://eyJhZGQiOiJqcDAxLmlwdjIu... `

地址，会出现

` Failed to process the result from the upstream, please check your Url.`

但这个地址在安卓手机的v2rayNG软件上是可以用的。

**相关截图或日志**
![image](https://user-images.githubusercontent.com/17077627/75307230-31a54c80-5886-11ea-9aaf-c34cf8e2e47a.png)

**Comment by DuckSoft** [comment]
@YJHelloWorld 您好，vmess请直接使用主窗口的添加功能导入。订阅是订阅，vmess是vmess。

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/75307846-be9cd580-5887-11ea-95af-148fa588d6c2.png)
图文教程。

**Comment by DuckSoft** [comment]
另外提示：Qv2ray 自带中文。
您可前往 Preference（首选项）调整 Language 语言为 zh_CN（简体中文）。

**Comment by YJHelloWorld** [comment]
@DuckSoft 多谢。现在连通了。
但是我按照下面配置chrome浏览器switchomega插件之后，连不了网， 直接是 no internet...
请问是哪里出了问题呢？

![image](https://user-images.githubusercontent.com/17077627/75308538-afb72280-5889-11ea-8c24-c4b7ef3e1132.png)

![image](https://user-images.githubusercontent.com/17077627/75308558-c1002f00-5889-11ea-9b97-295d808d6f94.png)

**Comment by DuckSoft** [comment]
你注意，Qv2ray 里面你设置的 SOCKS5 端口是 1088，而 SwitchyOmega 里面的是 1080。
这能连上才稀奇咧！

**Comment by YJHelloWorld** [comment]
这。。。 我以为默认的都是1080。 非常感谢，现在连上了。

**Comment by DuckSoft** [comment]
欢迎加入我们在 Telegram 上的 Qv2ray 用户群：
https://t.me/qv2ray
