### ISSUE TITLE
修改连接的tag后，自动生成的config.gen.json部分条目没有随之改变

### ISSUE THREAD

**Issue by Amaterasu33** [Qv2ray/Qv2ray#380]
**简单描述这个 bug：**

在不勾选绕过中国大陆的情况下，修改连接的tag后，自动生成的config.gen.json部分条目没有改变，导致v2ray报告[Warning] v2ray.com/core/app/dispatcher: non existing tag: outBound_PROXY

**如何复现这个bug：**
1. 将某连接的tag改为其他值（默认为outbound_PROXY）
2. 首选项-连接设置-取消勾选绕过中国大陆
3. 检查config/generated/config.gen.json文件，routing条目下涉及中国的规则仍然被导向outbound_PROXY这个tag，v2ray报告[Warning] v2ray.com/core/app/dispatcher: non existing tag: outBound_PROXY

**Qv2ray 本应该是怎样工作的？**
config.gen.json里outbound_PROXY应变成当前连接的tag

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

```
v2ray日志：
2020/02/26 12:47:12 [Warning] v2ray.com/core/app/dispatcher: non existing tag: outBound_PROXY
2020/02/26 12:47:12 tcp:127.0.0.1:56499 accepted tcp:github.githubassets.com:443 [op_vps]
2020/02/26 12:47:13 tcp:127.0.0.1:56497 accepted tcp:github.com:443 [op_vps] 
2020/02/26 12:47:13 tcp:127.0.0.1:56498 accepted tcp:github.com:443 [op_vps]
2020/02/26 12:48:12 [Warning] v2ray.com/core/app/dispatcher: non existing tag: outBound_PROXY
2020/02/26 12:48:13 tcp:127.0.0.1:56517 accepted tcp:github.com:443 [op_vps] 
2020/02/26 12:48:13 tcp:127.0.0.1:56516 accepted tcp:github.com:443 [op_vps]
2020/02/26 12:48:23 [Warning] v2ray.com/core/app/dispatcher: non existing tag: outBound_PROXY
```
```
gui日志：

[COMPONENT-PROXY]: Cleaning system proxy settings.
[CORE-UI]: Clearing System Proxy
[CORE-UI]: Stopping PAC server
[CORE-UI]: Stopped successfully.
[CORE-UI]: Loading new GlobalConfig
[CORE-VCORE]: Connecting to: ***
[CORE-CONNECTION]: Inserting default values to simple config
[CORE-CONNECTION]: allocation is not used here.
[CORE-VCORE]: V2ray output: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 windows/386);A unified platform for anti-censorship.
[COMPONENT-PROXY]: PAC Local IP is empty, default to 127.0.0.1
[COMPONENT-PROXY]: Starting PAC listener
[CORE-UI]: Preparing to set system proxy
[COMPONENT-PROXY]: System proxy uses PAC
[CORE-UI]: Setting system proxy for simple config.
[COMPONENT-PROXY]: Qv2ray will set system proxy to use PAC file
[COMPONENT-PROXY]: Windows proxy string: http://127.0.0.1:10810/pac
[COMPONENT-PROXY]: System default proxy info:
[COMPONENT-PROXY]: http://127.0.0.1:10810/pac
[COMPONENT-PROXY]: PROXY_TYPE_DIRECT
[COMPONENT-PROXY]: http://localhost:10809
[COMPONENT-PROXY]: Setting system proxy for PAC
[COMPONENT-PROXY]: System default proxy info:
[COMPONENT-PROXY]: http://127.0.0.1:10810/pac
[COMPONENT-PROXY]: PROXY_TYPE_AUTO_PROXY_URL
[COMPONENT-PROXY]: PROXY_TYPE_DIRECT
[COMPONENT-PROXY]: http://localhost:10809

```
![QQ截图20200226125116](https://user-images.githubusercontent.com/28757641/75313079-c021ca00-5896-11ea-906b-cb36db20cbd4.png)

**系统信息**
 - 系统类型（windows, linux, macos）
    - windows
 - 是从release下载的还是自己编译的
    - release
 - 首选项里的版本号：
    - v2.1.2.3861

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by Qv2ray-dev** [comment]
Will investigate, thanks for your contribution!

**Comment by Qv2ray-dev** [comment]
Bug located: https://github.com/Qv2ray/Qv2ray/blob/ae9a883076b0e18d8c7eb5e4bd974bcdda526626/src/core/connection/Generation.cpp#L27 where it was a historical issue. 

The earlier version of Qv2ray didn't have the feature to rename the outbound tag, where https://github.com/Qv2ray/Qv2ray/blame/354f3ca7504a8aa7c79415dc23602d75213de722/src/ui/editors/w_OutboundEditor.cpp#L440 added this feature.

This bug existed nearly 4 months while nobody found it. Thanks a lot!

**Comment by Amaterasu33** [comment]
> Bug located:
> 
> https://github.com/Qv2ray/Qv2ray/blob/ae9a883076b0e18d8c7eb5e4bd974bcdda526626/src/core/connection/Generation.cpp#L27
> 
> where it was a historical issue.
> The earlier version of Qv2ray didn't have the feature to rename the outbound tag, where https://github.com/Qv2ray/Qv2ray/blame/354f3ca7504a8aa7c79415dc23602d75213de722/src/ui/editors/w_OutboundEditor.cpp#L440 added this feature.
> 
> This bug existed nearly 4 months while nobody found it. Thanks a lot!

这个小bug也不怎么影响使用，多谢开发者的努力ヾ(•ω•`)o

**Comment by Qv2ray-dev** [comment]
Hello, this has been fixed within the latest `dev` branch. Please wait for the recent release.

If things are urgent, you may want to download the `dev` version from the Github Action.

Thanks for reporting this!
