### ISSUE TITLE
Proposal: Cross-Platform Portable Configuration

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#382]
Direct file sharing of Qv2ray configuration will mostly cause the vcore being unavailable (except for macOS and Linux). 
A separated vcore configuration store mechanism is suggested.

---
cc @Qv2ray-dev 
 - [ ] tracker

**Comment by DuckSoft** [comment]
Since Great M$ Bugdows use native encoding instead of de facto UTF-8, a enforcement to store the configuration files using UTF-8 is a must.
---
- [ ] tracker

**Comment by Qv2ray-dev** [comment]
Blocker #381

**Comment by Qv2ray-dev** [comment]
Blocker resolved, WIP

**Comment by Qv2ray-dev** [comment]
It's already been done within `dev` branch.
