### ISSUE TITLE
failed to process outbound traffic

### ISSUE THREAD

**Issue by cnpog** [Qv2ray/Qv2ray#383]
**Briefly describe this bug：**
When I select a server from my Wannaflix subscription list, connect and then edit my firefox proxy settings to the one's shown in qv2ray inbound settings, I can't access any websites anymore.
**How can I trigger this bug：**
1. Select server from wannaflix subscription 
2. click Connect 
3. edit proxy settings in firefox to http: 127.0.0.1:8888 and socks to 127.0.0.1:1089

**What is expected to happen**
That I can surf the web normally like with v2rayNG on windows
**System Information**

 - OS Type: Linux: 5.4.18-1-MANJARO x86_64
 - Built from the source (the dev version from AUR)
 - Version v2.1.2.3862
log:
`tcp:127.0.0.1:41022 accepted tcp:[***edited by myself***]:443 [outBound_PROXY]
2020/02/27 14:22:55 [Warning] [4249055424] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF`

**Comment by DuckSoft** [comment]
您好，先看时间是否正常。Vmess协议依赖正确的系统时间。

**Comment by DuckSoft** [comment]
另外，你可考虑加入我们在 Telegram 上的 Qv2ray 用户群，与我们进行即时的讨论：https://t.me/qv2ray

**Comment by cnpog** [comment]
> 您好，先看时间是否正常。Vmess协议依赖正确的系统时间。
That was it. Thank you!

**Comment by afishwithdream** [comment]
> 您好，先看时间是否正常。Vmess协议依赖正确的系统时间。
你好,系统时间指的是? 服务端时间还是客户端时间

**Comment by DuckSoft** [comment]
> > 您好，先看时间是否正常。Vmess协议依赖正确的系统时间。
> > 你好,系统时间指的是? 服务端时间还是客户端时间

两者均是。请勿挖坟。
