### ISSUE TITLE
复杂编辑时默认出站被重置为freedom，并且连接时不会自动配置系统代理了

### ISSUE THREAD

**Issue by Amaterasu33** [Qv2ray/Qv2ray#385]
**简单描述这个 bug：**
进行复杂编辑时，存在某些情况，保存的时候默认出站会被重置为freedom
---------补充发现：复杂配置下，连接时不会自动启动系统代理

**如何复现这个bug：**
1. 打开路由编辑器
2. 不做改动直接点击确认
3. 再打开路由编辑器，发现默认出站已经被重置。该主机对应的conf文件中freedom也变成了outbound的第一项。

**Qv2ray 本应该是怎样工作的？**

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

```
日志：
[CORE-UI]: INFO: Opening route editor.

[CORE-SETTINGS]: Saving a config named: vultr
[CORE-UI]: Stopped successfully.
[CORE-UI]: Loading new GlobalConfig
[CORE-UI]: Unknown outbound entry: freedom, cannot deduce host and port.
[CORE-UI]: Unknown outbound entry: freedom, cannot deduce host and port.
[CORE-UI]: Unknown outbound entry: freedom, cannot deduce host and port.
[CORE-VCORE]: Connecting to: vultr
[CORE-CONNECTION]: Processing an existing routing table.
[CORE-CONNECTION]: allocation is not used here.
[CORE-VCORE]: V2ray output: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 windows/amd64);A unified platform for anti-censorship.
[CORE-VCORE]: API has been disabled by the global config option
[CORE-UI]: Unknown outbound entry: freedom, cannot deduce host and port.

```
![test](https://user-images.githubusercontent.com/28757641/75530603-c78bd380-5a4e-11ea-8913-d70211b0e05a.gif)

---------补充：不自动配置代理
![test2](https://user-images.githubusercontent.com/28757641/75536952-15094000-5a51-11ea-9399-48163238a26a.gif)

**系统信息**
 - 系统类型（windows, linux, macos）
    - windows
 - 是从release下载的还是自己编译的
    - release
 - 首选项里的版本号：
    - v2.1.2.3861

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by Qv2ray-dev** [comment]
您好，复杂配置不会自动设置系统代理

**Comment by Qv2ray-dev** [comment]
Partial duplicate of #347

**Comment by Amaterasu33** [comment]
> 您好，复杂配置不会自动设置系统代理

好的谢谢
