### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [Qv2ray/Qv2ray#387]
[An extra null pointer check is not needed in a function](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like [the destructor for the class “APIWorkder”](https://github.com/Qv2ray/Qv2ray/blob/19d77c7171b145935b244045781a13bbcc56d785/src/core/kernel/APIBackend.cpp#L47 "Update candidate").

**Comment by Qv2ray-dev** [comment]
Thanks, sir, it's now fixed and I may close the issue now.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Qv2ray/Qv2ray/commit/d4be3a987ef3bfa0efba338045671d289dc4ca9e "Removal of an unnecessary check").
