### ISSUE TITLE
Urge the great gods to add support for the Trojan agreement in the future

### ISSUE THREAD

**Issue by even790403** [Qv2ray/Qv2ray#388]
The Trojan protocol is becoming more and more popular now. It can be an excellent v2ray partner. The combination of the two makes people have more choices and is the most secure at present. However, Trojan does not currently have a complete client. If the great gods join Trojan The support is the most perfect proxy client at present. If there is no one, it will be very hot. Hope to achieve it soon. Thank you very much.

**Comment by Qv2ray-dev** [comment]
@even790403 We all know the Trojan is now becoming a new proxy client.

However, Qv2ray is a direct V2ray frontend, in other words, it means we currently have no thoughts adding another/other proxy client support, there was an SSR implementation before but limited to Linux only, and it's not being merged into the mainline.

Please wait and standby to see if things change. If you want to contribute, feel free to open a PR.

**Comment by DuckSoft** [comment]
说人话：能做，得等，欢迎 Pull Request。

**Comment by even790403** [comment]
嗯，追随大神

**Comment by TheWanderingCoel** [comment]
Trojan do have a complete client now :)

**Comment by DuckSoft** [comment]
@even790403 https://github.com/TheWanderingCoel/Trojan-Qt5
不妨看看楼上写的 Trojan-Qt5，也很不错哦

**Comment by TheWanderingCoel** [comment]
> @even790403 https://github.com/TheWanderingCoel/Trojan-Qt5
> 不妨看看楼上写的 Trojan-Qt5，也很不错哦

@DuckSoft 感谢大佬推荐= v =

**Comment by DuckSoft** [comment]
Now we have a great Trojan client [Trojan-Qt5](https://github.com/TheWanderingCoel/Trojan-Qt5) by @TheWanderingCoel! Closing this now!
