### ISSUE TITLE
关于 Qv2ray 在 Ubuntu 16.04 上启动方法的讨论

### ISSUE THREAD

**Issue by smartadpole** [Qv2ray/Qv2ray#391]
**简单描述这个 bug：**
最近突然出现软件无法启动，但是运行后会占用端口；
@DuckSoft 
版本：Qv2ray-refs.tags.v1.3.8.0-linux
依次执行命令，及其输出信息：
```
./v2ray # 界面并未启动
```
>V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2020/03/05 10:15:04 [Warning] v2ray.com/core: V2Ray 4.20.0 started

`./v2ray`   
>V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1080 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:1080 > listen tcp 127.0.0.1:1080: bind: address already in use

`lsof -i:1080`
>COMMAND   PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
v2ray   29467  hao    4u  IPv4 28589923      0t0  TCP localhost:socks (LISTEN)

**Comment by DuckSoft** [comment]
您好。请提供更多信息。

**Comment by DuckSoft** [comment]
您好，您应该运行 appimage 文件，而非 v2ray 核心本体。

**Comment by DuckSoft** [comment]
另外，您所使用的版本太过古老，已经不受支持。
建议您使用最新版本的 Qv2ray。
您可在此下载：
https://github.com/Qv2ray/Qv2ray/releases/tag/v2.1.2

**Comment by smartadpole** [comment]
我以前都是这么执行的 就没问题。。。。。。我先试试新版吧，`appimage` 运行总有依赖问题；

**Comment by DuckSoft** [comment]
请您提供您的发行版名称以及版本号。
如：Ubuntu 18.04。

**Comment by DuckSoft** [comment]
您可考虑加入我们的 Telegram 用户组与我们一同讨论。
https://t.me/qv2ray

**Comment by smartadpole** [comment]
ubuntu 16.04.12

**Comment by DuckSoft** [comment]
您好，Ubuntu 18.04 之前的版本建议使用 snap 方式安装。

**Comment by smartadpole** [comment]
> 您可考虑加入我们的 Telegram 用户组与我们一同讨论。
> https://t.me/qv2ray

链接打不开

**Comment by DuckSoft** [comment]
> > 您可考虑加入我们的 Telegram 用户组与我们一同讨论。
> > https://t.me/qv2ray
> 
> 链接打不开

您也可直接在 Telegram 中搜索 `@qv2ray`

**Comment by DuckSoft** [comment]
刚才确认过了，Ubuntu 16.04 应该是能使用我们的 AppImage 的。
使用方法如下：
1. 下载，解压，得到一个 `xxxx.AppImage` 文件
2. 执行命令：`chmod +x xxxx.AppImage`
3. 点击运行即可

**Comment by smartadpole** [comment]
> 您好，Ubuntu 18.04 之前的版本建议使用 snap 方式安装。
> Ubuntu 16.04 的 glibc 版本过低，不再受支持。

..........我抽空升级系统吧

**Comment by smartadpole** [comment]
好的，我试试

**Comment by Qv2ray-dev** [comment]
No support on EOL distros and/OS OS versions. 
e.g. Windows 7, Ubuntu 16.04=-, Debian 8=-
