### ISSUE TITLE
在 Ubuntu Linux 上从源代码安装 Qv2ray 的问题

### ISSUE THREAD

**Issue by resplendent-star** [Qv2ray/Qv2ray#392]
但是Q2ray/tools里面根本找  不  到教程中的那个.sh文件，这该怎么办呢
**相关截图或日志**
![Uploading 2020-03-05 20-44-09屏幕截图.png…]()
![2020-03-05 20-45-54屏幕截图](https://user-images.githubusercontent.com/41502003/75982818-5f436300-5f22-11ea-8209-1cca2f850782.png)

**Comment by resplendent-star** [comment]
/home/lzw/桌面/2020-03-05 20-44-09屏幕截图.png 这个里面并没有教程里面需要的那个.sh

**Comment by resplendent-star** [comment]
![2020-03-05 20-44-09屏幕截图](https://user-images.githubusercontent.com/41502003/75986453-1216bf80-5f29-11ea-9790-fb629ebdb939.png)

**Comment by DuckSoft** [comment]
您好。新版只需配齐 Qt 工具链以及相关依赖，直接使用 qmake 构建即可。
参考构建步骤：
```shell
mkdir build
qmake 'CONFIG += use_grpc' ..
make
```

**Comment by DuckSoft** [comment]
若您仍有疑问，欢迎加入我们在 Telegram 上的用户交流群，与我们开发者一同沟通：
https://t.me/qv2ray

**Comment by DuckSoft** [comment]
Closed due to no response.
