### ISSUE TITLE
Porting build system from qmake to cmake

### ISSUE THREAD

**Issue by Qv2ray-dev** [Qv2ray/Qv2ray#393]
These steps are required: 
- [x] Writing CMakeLists.txt for existing Qv2ray source code @ymshenyu 
- [x] Implementing existing `qmake` `CONFIG` options with `cmake` `--with-*` args. @ymshenyu 
- [x] Fix Github Actions @Qv2ray-dev 
- [x] Remove QMake scripts.
- [x] Changing upstream 3rdparty dependencies to `cmake`-compatible. @Qv2ray-dev 
- [x] Link upstream CMakeLists.txt to the Qv2ray project. @ymshenyu 
- [x] Test for Linux/Windows x86 x64/macOS build status. @DuckSoft @ymshenyu @Qv2ray-dev 
- [x] Merge into dev branch @Qv2ray-dev 
- [x] Notify ALL downstream packagers about ongoing the `dev`-package release. @DuckSoft  @axionl 
   - [x] Arch Linux: `archlinuxcn` @axionl 
   - [x] Snapcraft @ymshenyu @DuckSoft 
   - [x] Ubuntu PPA @ymshenyu 
   - [x] Flatpak @ymshenyu 
   - [x] openSUSE
- [x] Notify ALL downstream packagers about ongoing `qmake` to `cmake` changes. @DuckSoft  @axionl

**Comment by DuckSoft** [comment]
@Qv2ray-dev Hooooly crap

**Comment by Qv2ray-dev** [comment]
CMake Development branch is now merged into major development branch.

**Comment by DuckSoft** [comment]
Well done, comrades!

All credit goes to:
* @ymshenyu 
* @Qv2ray-dev 
* @DuckSoft 
* @axionl 
* and other contributors!

Closing!
