### ISSUE TITLE
[dev] speed graph expand/contract tooltip misplace

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#397]
![图片](https://user-images.githubusercontent.com/7822648/76155818-94230600-612c-11ea-8c2d-5069cf75f09d.png)

**Comment by DuckSoft** [comment]
done. closing.

**Comment by iamwwc** [comment]
@DuckSoft 
![image](https://user-images.githubusercontent.com/24750337/81653479-611c2c00-9467-11ea-892e-8f010b78de6f.png)

Why my speed graph is always empty  even though Log showing connection detail?

![image](https://user-images.githubusercontent.com/24750337/81653570-87da6280-9467-11ea-985b-c5b9344e4d44.png)

**Comment by DuckSoft** [comment]
Referenced in new issue #603.
Please, do not necropost.
