### ISSUE TITLE
subscription: add custom proxy pass

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#402]
Qt 使用的 QNetworkAccessManager 支持透过 SOCKS5 进行网络请求，并且在设定 QNetworkProxy::HostNameLookupCapability FLAG 的情况下，会将域名 SOCKS5 进行解析。

有些情况下，部分机场的面板订阅 URL 不能直连。此功能应非常有帮助。

**Comment by Qv2ray-dev** [comment]
Will add a global connection setting for Qv2ray.

**Comment by Qv2ray-dev** [comment]
Resolved by https://github.com/Qv2ray/Qv2ray/commit/796ada817da6dda4aa41d83a0adc98a3b7a68d17

**Comment by EricLion** [comment]
that is good idea
