### ISSUE TITLE
adding a graphic editor for v2ray geoip/geosite rules

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#404]

**Comment by Qv2ray-dev** [comment]
Rules order:
```
block
proxy
direct
then check if CN is being bypassed
```

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/76994244-0abfcf00-6989-11ea-9f02-8c09a6f9fc95.png)
A Crude Scratch

**Comment by Qv2ray-dev** [comment]
This has been done. So close currently.
