### ISSUE TITLE
dev 版本当 PAC 开启后会卡死

### ISSUE THREAD

**Issue by 330079598** [Qv2ray/Qv2ray#405]
**简单描述这个 bug：**
打开qv2ray之后,只能通过查看进程才能看到v2ray的信息,软件打开后不显示,面板中也没有显示,无法进行一系列的设置,系统的system monitor无法关闭,只能通过kill -9杀死后台

稳定版的我也无法使用,下面是错误信息:
You are running a lower version of Qv2ray compared to the current config file.
Please check if there's an issue explaining about it.
Or submit a new issue if you think this is an error.

Qv2ray will now exit.

**如何复现这个bug：**
1. 每次打开都是这样
2. 
3. 
4. 

**Qv2ray 本应该是怎样工作的？**
打开后出现设置界面,以及状态栏有图标

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - archLinux
 - 是从release下载的还是自己编译的
    - 
 - 首选项里的版本号：
    - [Qv2ray]: v2.1.2.4600
      [QV2RAY_BUILD_INFO]: Qv2ray for Arch Linux CN
      [QV2RAY_BUILD_EXTRA_INFO]: (Official Build) 5.5.6-arch1-1 x86_64
  - 这个是v2ray的版本:
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14 linux/amd64)
A unified platform for anti-censorship.

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

- 请问还需要提供其他信息么?用的是arch,每天都有更新的习惯,所有软件包都是在aur中下载, 或者是再官方源中下载,尝试过使用Release中发布的:Qv2ray.v2.1.2.linux-x64.qt5.13.2.AppImage,错误信息:
You are running a lower version of Qv2ray compared to the current config file.
Please check if there's an issue explaining about it.
Or submit a new issue if you think this is an error.

Qv2ray will now exit.

系统信息:
OS: Arch Linux x86_64
Kernel: 5.5.8-arch1-1
DE: Plasma
WM: KWin
桌面kde

**Comment by DuckSoft** [comment]
@330079598 对于 Arch Linux 用户，请使用 archlinuxcn 官方源提供的 qv2ray 和 qv2ray-dev-git 提供的软件包。

**Comment by DuckSoft** [comment]
@330079598 此外，目前的 dev 版本并未迁移完成，PAC 功能存在缺陷。
---
PAC 解决方案：
未开启自动链接的，可以直接到首选项进行关闭
开启了自动链接的，需要退出 Qv2ray， 手动编辑配置文件 Qv2ray.conf "enablePAC": true, 改为 "enablePAC": false, 并重新启动

**Comment by DuckSoft** [comment]
@Qv2ray-dev 需要谢罪

**Comment by DuckSoft** [comment]
Updates:
@Qv2ray-dev 停下了吃炸鸡，正在紧急修复

---
欢迎加入 Qv2ray 开发交流群：https://t.me/qv2ray 云监工

**Comment by 330079598** [comment]
> Updates:
> @Qv2ray-dev 停下了吃炸鸡，正在紧急修复
> 
> 欢迎加入 Qv2ray 开发交流群：https://t.me/qv2ray 云监工
棒棒棒,处理速度太赞了!!

**Comment by DuckSoft** [comment]
发布了一个补丁，暂时修复了，但有内存泄漏的风险。
准备重构。

**Comment by 330079598** [comment]
> 发布了一个补丁，暂时修复了，但有内存泄漏的风险。
> 准备重构。

那我最近就不升级了,先这样用着呗!

**Comment by DuckSoft** [comment]
@330079598 （其实漏内存刚刚也修了

**Comment by DuckSoft** [comment]
本问题已经修复。编译机打包启动中。

**Comment by 330079598** [comment]
> 本问题已经修复。编译机打包启动中。
OK,那完美啦

**Comment by DuckSoft** [comment]
没完呢。请查收你的软件包。
[qv2ray-dev-git-2.1.2.4601+grpc-1-x86_64.pkg.tar.gz](https://github.com/Qv2ray/Qv2ray/files/4305317/qv2ray-dev-git-2.1.2.4601%2Bgrpc-1-x86_64.pkg.tar.gz)
