### ISSUE TITLE
GNOME 3.35.91 + appindicator = super ugly tray icon

### ISSUE THREAD

**Issue by St-kai** [Qv2ray/Qv2ray#406]
**Briefly describe this bug：**
topicon error
**How can I trigger this bug：**

1.
2. 
3. 
4. 

**What is expected to happen**

**Screenshots**
If appropriate, please attach some screenshots.
![image](https://user-images.githubusercontent.com/24271418/76229387-13175c00-625d-11ea-86a6-7400b52ca8aa.png)

**System Information**

 - OS Type:Linux
 - Built from the source or download from the release?
Archlinuxcn repo
 - Version string in the Preferences Window
v2.1.2.4600
**Other Info**

You may want to write anything if you think it helps us to fix the bug.
Archlinux+Gnome3.35.91+appindicator
*Please hide your server address and UUID if you wish to post the vmess string or your connection setting.*

**Comment by Qv2ray-dev** [comment]
@St-kai i

**Comment by DuckSoft** [comment]
This is confirmed as a vanilla GNOME bug. 
We will try our best to solve this, but we have no idea what happened here.
:sad:

**Comment by DuckSoft** [comment]
Investigation In Progress.

**Comment by DuckSoft** [comment]
已经确认，此为 GNOME bug。
请静候上游修复。

Closing！
