### ISSUE TITLE
4K屏幕 显示效果问题

### ISSUE THREAD

**Issue by l-we** [Qv2ray/Qv2ray#407]
**简单描述这个 bug：**
4K片路右侧布局不合理 如图
![image](https://user-images.githubusercontent.com/6325345/76272843-5999a480-62b7-11ea-9677-130467ab63e2.png)

![image](https://user-images.githubusercontent.com/6325345/76273009-bd23d200-62b7-11ea-9954-800de5842b17.png)

**如何复现这个bug：**
1. 
2. 
3. 
4. 

**Qv2ray 本应该是怎样工作的？**

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - Windows
 - 是从release下载的还是自己编译的
    - dev
 - 首选项里的版本号：
    - 

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by DuckSoft** [comment]
似已解决。
@Qv2ray-dev

**Comment by l-we** [comment]
no， 最大化后，右下侧的依然有很大的空隙，

**Comment by DuckSoft** [comment]
> no， 最大化后，右下侧的依然有很大的空隙，

您认为正常情况应该如何？

**Comment by l-we** [comment]
log以底为边界吧。
![image](https://user-images.githubusercontent.com/6325345/76294417-c62f9600-62ed-11ea-8f5a-e6168ce16251.png)

**Comment by DuckSoft** [comment]
cc @Qv2ray-dev

**Comment by DuckSoft** [comment]
此问题应已在 8f4e9ec7528dbae317b2cab127ab03f9676619b9 的提交中修复。
若有兴致，您可尝试 GitHub Actions 中的相应预览版程序。

**Comment by DuckSoft** [comment]
Closing!
