### ISSUE TITLE
windows10 

### ISSUE THREAD

**Issue by WangYeCoder** [Qv2ray/Qv2ray#410]
**简单描述这个 bug：**

![image](https://user-images.githubusercontent.com/43713316/76384216-40692480-6399-11ea-8c79-83d87db55ce0.png)

请问这是什么情况= = 

我翻遍了Issue 没找到同样的问题呢

**Comment by DuckSoft** [comment]
收悉。

你可能没有下载并配置 v2ray-core。
请参考 https://github.com/Qv2ray/Qv2ray/wiki/Getting-Started-step2_zh 完成配置。
若有其它问题，欢迎加入 Qv2ray Telegram 用户交流群：
https://t.me/qv2ray

**Comment by WangYeCoder** [comment]
我查看了设置面板 如下图

![image](https://user-images.githubusercontent.com/43713316/76384456-d8670e00-6399-11ea-8c00-9898c154aecd.png)

但是在目录中却找不到对应的 v2ray.exe文件，如下图

![image](https://user-images.githubusercontent.com/43713316/76384446-d1400000-6399-11ea-97a1-3bb85ba0884f.png)

**Comment by WangYeCoder** [comment]
> 收悉。
> 
> 你可能没有下载并配置 v2ray-core。
> 请参考 https://github.com/Qv2ray/Qv2ray/wiki/Getting-Started-step2_zh 完成配置。
> 若有其它问题，欢迎加入 Qv2ray Telegram 用户交流群：
> https://t.me/qv2ray

感谢您的指导 我的问题得到了解决
