### ISSUE TITLE
蜜汁系列问题之一

### ISSUE THREAD

**Issue by atzlinux** [Qv2ray/Qv2ray#411]
**简单描述这个 bug：**

Debian 10.3 ，安装了v2ray core 版本：

[CORE-VCORE]: V2ray output: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64);A unified platform for anti-censorship.

在界面配置中，指定了 v2ray core 命令的执行路径和 配置文件路径，检查也是OK。

**如何复现这个bug：**
1. 手工输入 vmess 的配置
2. 启动链接
3. 弹出报错框
```
main: failed to read config file: /home/atzlinux/.config/qv2ray/generated/config.gen.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > v2ray.com/core/infra/conf: failed to open file: geoip.dat > open /usr/bin/geoip.dat: no such file or directory
```

 > exit status 25

请问下，还需要手工指定  v2ctl 命令的位置吗？如何指定？

4. 

**Qv2ray 本应该是怎样工作的？**

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

```
日志：
 [QV2RAY_BUILD_INFO]: Qv2ray built from Github Action
[QV2RAY_BUILD_EXTRA_INFO]: qt5.13.2-05b2b5ccaffe67a05335202e52495d643811daa3
[INIT]: Qv2ray v2.1.2.3861 running on Debian GNU/Linux 10 (buster) x86_64

[CORE-UI]: Installing a tranlator from OS: zh_CN -- OK
[LICENCE]: 
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

Copyright (c) 2019-2020 Qv2ray Development Group.


Libraries that have been used in Qv2ray are listed below (Sorted by date added):
Copyright (c) 2020 dridk (@dridk): X2Struct (Apache)
Copyright (c) 2011 SCHUTZ Sacha (@dridk): QJsonModel (MIT)
Copyright (c) 2020 Nikolaos Ftylitakis (@ftylitak): QZXing (Apache2)
Copyright (c) 2016 Singein (@Singein): ScreenShot (MIT)
Copyright (c) 2016 Nikhil Marathe (@nikhilm): QHttpServer (MIT)
Copyright (c) 2020 Itay Grudev (@itay-grudev): SingleApplication (MIT)
Copyright (c) 2020 paceholder (@paceholder): nodeeditor (QNodeEditor modified by lhy0403) (BSD-3-Clause)
Copyright (c) 2019 TheWanderingCoel (@TheWanderingCoel): ShadowClash (launchatlogin) (GPLv3)
Copyright (c) 2020 Ram Pani (@DuckSoft): QvRPCBridge (WTFPL)
Copyright (c) 2019 ShadowSocks (@shadowsocks): libQtShadowsocks (LGPLv3)
Copyright (c) 2015-2020 qBittorrent (Anton Lashkov) (@qBittorrent): speedplotview (GPLv2)


[INIT]: Qv2ray Start Time: 61939008
[INIT]: Found Translator: en_US.qm
[INIT]: Found Translator: ja_JP.qm
[INIT]: Found Translator: ru_RU.qm
[INIT]: Found Translator: zh_CN.qm
[INIT]: Application exec path: /tmp/.mount_Qv2rayA0ux2j/usr/bin
[INIT]: Path: /tmp/.mount_Qv2rayA0ux2j/usr/bin/config/ does not contain a valid config file.
QFile::open: File (/home/atzlinux/.config/qv2ray/Qv2ray.conf) already open
[CORE-SETTINGS]: Path: /home/atzlinux/.config/qv2ray/ contains a config file, in version 8
[INIT]: Using /home/atzlinux/.config/qv2ray/ as the config path.
[INIT]: Removed system translations
[INIT]: Successfully installed a translator for zh_CN
[COMMON-NETWORK]: Current OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
[INIT CORE-UI]: Setting Qv2ray UI themes: Fusion
QObject::connect: No such slot Qv2ray::core::kernel::api::APIWorkder::errorString(QString)
QMetaObject::connectSlotsByName: No matching signal for on_action_RCM_ShareQR_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_action_StartThis_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_action_RCM_EditJson_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_action_RCM_ConvToComplex_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_action_RCM_RenameConnection_triggered()
[CORE-UI]: Loading new GlobalConfig
[COMMON-NETWORK]: Network request errcode: 0
[COMPONENT-UPDATE]: Received update info, Latest: 2.1.2 Current: 2.1.2.3861 Ignored: 
QMetaObject::connectSlotsByName: No matching signal for on_spPortSB_valueChanged(int)
[CORE-VCORE]: V2ray output: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64);A unified platform for anti-censorship.
[CORE-UI]: Loading new GlobalConfig
[CORE-VCORE]: Connecting to: t
[CORE-CONNECTION]: Inserting default values to simple config
[CORE-CONNECTION]: allocation is not used here.
[CORE-VCORE]: V2ray output: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64);A unified platform for anti-censorship.
QMetaObject::connectSlotsByName: No matching signal for on_spPortSB_valueChanged(int)
```

**系统信息**
 - 系统类型（windows, linux, macos）
Debian 10.3
    - 
 - 是从release下载的还是自己编译的
    Qv2ray.v2.1.2.linux-x64.qt5.13.2.AppImage 

 - 首选项里的版本号：
    - v2.1.2.3861
**其他信息**
- 

我的 v2ray 软件，是在 https://www.atzlinux.com/allpackages.htm 这里用 apt 安装的。

**Comment by DuckSoft** [comment]
这是因为你的 v2ray-core 可执行文件虽然设置正确，但是 v2ray assets 文件夹指定的有误。
v2ray-core 无法在 v2ray assets 文件夹下找到 geoip.dat 和 geosite.dat，导致的问题。

请检查相关配置。

**Comment by DuckSoft** [comment]
https://github.com/Qv2ray/Qv2ray/wiki/Getting-Started-step2_zh

这篇文章可能对您有所帮助。

**Comment by atzlinux** [comment]
> 这是因为你的 v2ray-core 可执行文件虽然设置正确，但是 v2ray assets 文件夹指定的有误。
> v2ray-core 无法在 v2ray assets 文件夹下找到 geoip.dat 和 geosite.dat，导致的问题。
> 
> 请检查相关配置。

我手工把那 4 个文件拷贝到软件的默认目录下，启动是不报错误了。
但是连接日志，报如下错误：

V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
A unified platform for anti-censorship.
2020/03/11 17:45:45 [Warning] v2ray.com/core: V2Ray 4.22.1 started
2020/03/11 17:46:19 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/03/11 17:46:22 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/03/11 17:46:24 [Warning] v2ray.com/core/app/router: resolve ip for klyfnvpiv > v2ray.com/core/app/dns: invalid domain name
2020/03/11 17:46:24 [Warning] v2ray.com/core/app/router: resolve ip for klyfnvpiv > v2ray.com/core/app/dns: invalid domain name
2020/03/11 17:46:24 tcp:127.0.0.1:51198 accepted tcp:klyfnvpiv:80 [t]
2020/03/11 17:46:24 [Warning] v2ray.com/core/app/router: resolve ip for prnukpkfqhjqoe > v2ray.com/core/app/dns: invalid domain name
2020/03/11 17:46:24 [Warning] v2ray.com/core/app/router: resolve ip for prnukpkfqhjqoe > v2ray.com/core/app/dns: invalid domain name
2020/03/11 17:46:24 tcp:127.0.0.1:51202 accepted tcp:prnukpkfqhjqoe:80 [t] 
2020/03/11 17:46:24 [Warning] v2ray.com/core/app/router: resolve ip for melltrlpemvup > v2ray.com/core/app/dns: invalid domain name
2020/03/11 17:46:24 [Warning] v2ray.com/core/app/router: resolve ip for melltrlpemvup > v2ray.com/core/app/dns: invalid domain name
2020/03/11 17:46:24 tcp:127.0.0.1:51200 accepted tcp:melltrlpemvup:80 [t]
2020/03/11 17:46:25 [Warning] [696062570] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/03/11 17:46:25 [Warning] [1992426276] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/03/11 17:46:25 [Warning] [867430336] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF

是 vmess 配置有误吗？我就只填了 v2ray 服务器的 ＩＰ，端口　和　client-id 。

**Comment by DuckSoft** [comment]
你可能忘了指定传输协议。

**Comment by atzlinux** [comment]
> 你可能忘了指定传输协议。

我默认使用的是 TCP 协议。请问还需要在配置界面选择哪个协议？

**Comment by DuckSoft** [comment]
```
2020/03/11 17:46:24 [Warning] v2ray.com/core/app/router: resolve ip for melltrlpemvup > v2ray.com/core/app/dns: invalid domain name
```

melltrlpemvup 是个什么神奇的东西？

**Comment by atzlinux** [comment]
> ```
> 2020/03/11 17:46:24 [Warning] v2ray.com/core/app/router: resolve ip for melltrlpemvup > v2ray.com/core/app/dns: invalid domain name
> ```
> 
> melltrlpemvup 是个什么神奇的东西？

我也不清楚这些奇怪的域名解析是如何来的。

**Comment by DuckSoft** [comment]
直接入群吧，这里效率太低。
https://t.me/qv2ray

**Comment by Qv2ray-dev** [comment]
@atzlinux 这个无论如何也解析不了啊（至少得有个后缀

**Comment by DuckSoft** [comment]
请考虑加入 Qv2ray 在 Telegram 的交流群：
https://t.me/qv2ray
若无法打开链接，在搜索栏直接搜索 `@qv2ray` 也可。

本 Issue 原问题已经解决，将关闭。
