### ISSUE TITLE
请问是否能支持允许局域网连接选项

### ISSUE THREAD

**Issue by Cherrison** [Qv2ray/Qv2ray#414]
很多时候某些设备所在的平台没有办法直接部署 V2ray 服务，所以只能采用间接的方案诸如刷路由器来解决，但刷路由器需要精力，某些设置也需要调试.

在V2ray 安卓客户端 V2rayNG 的最新版本中，有一个“局域网的连接端口”选项，这样其它设备就无需安装代理软件 , 在局域网中就可以直接连接代理

**Comment by DuckSoft** [comment]
您好，早已实现。

https://github.com/Qv2ray/Qv2ray/wiki/Getting-Started-step4_zh#%E8%AE%A9%E7%BD%91%E7%BB%9C%E4%B8%8A%E7%9A%84%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E4%BD%BF%E7%94%A8%E4%BB%A3%E7%90%86

**Comment by jiqing112** [comment]
首选项  -  入站设置  -  把监听地址从127.0.01改成0.0.0.0

![](https://pic.downk.cc/item/5f32058814195aa59478c729.jpg)

**Comment by smithCoderLeo** [comment]
> 首选项 - 入站设置 - 把监听地址从127.0.01改成0.0.0.0
> 
> ![](https://camo.githubusercontent.com/1b041a2c9ef40e0cdd96f6a08519d958b15e278f57c07c120c27b6981a61d61f/68747470733a2f2f7069632e646f776e6b2e63632f6974656d2f3566333230353838313431393561613539343738633732392e6a7067)

it works! very useful!
