### ISSUE TITLE
Multiple vmess import

### ISSUE THREAD

**Issue by idnsunset** [Qv2ray/Qv2ray#417]
**Briefly describe this bug：**
If I am not wrong Qv2ray supports multiple vmess URLs import, right? I attempted to import a bunch of vmess URLs into Qv2ray but only the first one got parsed.

**How can I trigger this bug：**

1. Copy a bunch of vmess URLs 
2. Click on "Add" button and switch to the "VMess/QR Code" tab
3. Paste the copied into the "Share Link" box

**What is expected to happen**

All URLs get parsed correctly.

**System Information**

 - OS Type: **Linux**
 - Built from the source or download from the release? **pre-built release**
 - Version string in the Preferences Window: **v2.1.2.3861**

**Comment by DuckSoft** [comment]
@Qv2ray-dev We need to investigate in this.

**Comment by Qv2ray-dev** [comment]
Urgent.

**Comment by Qv2ray-dev** [comment]
@idnsunset Can you please provide the log? that is, the output when you run `qv2ray.AppImage` from the terminal?

**Comment by Qv2ray-dev** [comment]
Firstly, please verify if all your `vmess://` connections have the same alias or connection name in other words.

**Comment by DuckSoft** [comment]
Cannot repeat on Arch Linux 5.5.8, KDE Plasma 5.18.3, Qv2ray v2.1.2.4631 built from Arch Linux CN Repository.
Please kindly provide with us your problematic `vmess://` links, if applicable.

In consideration of privacy, you may join us at Qv2ray User Group (https://t.me/qv2ray, on Telegram) and send private messages to us.

A new version of release is drawing near, and we expect you to respond as soon as possible.

**Comment by idnsunset** [comment]
> Firstly, please verify if all your `vmess://` connections have the same alias or connection name in other words.

This is the exact problem, all my URLs share the same aliases as they are published by a Telegram channel. I try to pasted two URLs from different channels (with different aliases for sure) then it works. However, when i am on Windows using V2rayN or with my cell phone using V2rayNG, they never produce such problem. Could you please find a way to sort it out?

**Comment by Qv2ray-dev** [comment]
@idnsunset There was someone reporting the issue weeks ago and it has been fixed within the dev and version-v2 branch, which will be release within few days, (tomorrow or the day after.). Please wait patiently or directly use the AppImage from Github Action if that

**Comment by idnsunset** [comment]
No hurry, I am gonna be waiting for the new release. Thanks a lot for quick response from you guys!

**Comment by idnsunset** [comment]
I've tested the new release and confirmed this bug is fixed.

**Comment by Qv2ray-dev** [comment]
Thanks for reporting this!

**Comment by arvinEsm** [comment]
why when im trying import my vlesses i get this error : Unsupported share link format, and how can i fix this?

**Comment by 1769588795** [comment]
邮件已收到，谢谢！！！O(∩_∩)O~~~
