### ISSUE TITLE
向 Qv2ray 中导入 HTTP/2 协议的 vmess:// 链接问题

### ISSUE THREAD

**Issue by Roger-WIN** [Qv2ray/Qv2ray#421]
**简单描述这个 bug：**
我把通过 V2Ray 安装脚本生成的 Vmess 链接添加到 Qv2ray 中，启动连接后发现无法翻出去。打开编辑窗口后发现传输协议处选的是 `tcp`，改为 `http` 后就正常了。

**如何复现这个bug：**
1. 使用 [wulabing 的 V2Ray 一键安装脚本](https://github.com/wulabing/V2Ray_ws-tls_bash_onekey/)安装 V2Ray
2. 传输协议选择 HTTP/2
3. 将安装完成生成的 Vmess 链接添加到 Qv2ray
4. 打开编辑窗口，发现传输协议是 `tcp`

**Qv2ray 本应该是怎样工作的？**
应当识别为 HTTP/2 协议，从而将传输协议选择为 `http`。

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 
[V2RayN](https://github.com/2dust/v2rayN/) 和 [V2RayNG](https://github.com/2dust/v2rayNG/) 都能将传输协议正常识别为 `h2`。

**相关截图或日志**

```
日志：

```

![image](https://user-images.githubusercontent.com/25821208/76718988-61ec5680-6773-11ea-8679-2150139969a6.png)

**系统信息**
 - 系统类型（windows, linux, macos）
    - Linux
 - 是从release下载的还是自己编译的
    - Release
 - 首选项里的版本号：
    - 2.2.1.4715

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

- 使用 JSON 查看该连接，可以看到 `"network": "h2"` 这一项。我想就是因为这个没有正确处理，才会选错传输协议的。

**Comment by DuckSoft** [comment]
收悉。
cc @Qv2ray-dev

**Comment by DuckSoft** [comment]
您好，请问您能否提供一个样例 vmess 链接，无论有效无效均可。

**Comment by Roger-WIN** [comment]
> *在提供自己的 vmess 或者配置文件时，注意隐藏好服务器地址和 uuid*

我不知道怎么隐藏。🤣

**Comment by DuckSoft** [comment]
那这样吧，加一下我们的 Telegram 群组：
https://t.me/qv2ray

然后 PM 管理员。

**Comment by DuckSoft** [comment]
问题已经定位。准备修复。

**Comment by Roger-WIN** [comment]
```
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogInd1bGFiaW5nX3NnLmVjcy5yb2dlcmt1bmctd2luLnRvcCIsDQogICJhZGQiOiAiMTI3LjAuMC4xIiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogImUwMzg5NTQ5LTBiOTYtNGVjNS04ZDUzLWZjYWVhMmJmZGZmYyIsDQogICJhaWQiOiAiMiIsDQogICJuZXQiOiAiaDIiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiLzIyOGFjYTdmLyIsDQogICJ0bHMiOiAidGxzIg0KfQ==
```
刚准备了一个无效的链接。🤣

**Comment by DuckSoft** [comment]
> ```
> vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogInd1bGFiaW5nX3NnLmVjcy5yb2dlcmt1bmctd2luLnRvcCIsDQogICJhZGQiOiAiMTI3LjAuMC4xIiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogImUwMzg5NTQ5LTBiOTYtNGVjNS04ZDUzLWZjYWVhMmJmZGZmYyIsDQogICJhaWQiOiAiMiIsDQogICJuZXQiOiAiaDIiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiLzIyOGFjYTdmLyIsDQogICJ0bHMiOiAidGxzIg0KfQ==
> ```
> 
> 刚准备了一个无效的链接。rofl

收到。bug 即将修复。

**Comment by DuckSoft** [comment]
自动构建工作流正在运行中。构建结束后，您可从中取用对应您系统的文件。
若您是 archlinux / manjaro 用户，请您在此留言，我将直接发布打好的包。

https://github.com/Qv2ray/Qv2ray/actions/runs/56440229

**Comment by Roger-WIN** [comment]
不是 ，我用的 Deepin（Debian 系）。

**Comment by DuckSoft** [comment]
我们将于 1 小时内 Release 一个新的版本。
请您稍作等待。

**Comment by Roger-WIN** [comment]
辛苦了，多谢。

**Comment by Qv2ray-dev** [comment]
fixed and closing.

**Comment by Roger-WIN** [comment]
反而不能联网了。
我想是不是这两处 commit 冲突：
![image](https://user-images.githubusercontent.com/25821208/76736336-9119bc80-67a1-11ea-9747-1474cb11e412.png)

提供一个有效的 Vmess 链接供测试：
```
vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJ3dWxhYmluZ19kZW1vLnZwcy5yb2dlcmt1bmctd2luLnRvcCIsCiAgImFkZCI6ICJkZW1vLnZwcy5yb2dlcmt1bmctd2luLnRvcCIsCiAgInBvcnQiOiAiNDQzIiwKICAiaWQiOiAiMTg4ZGRlNzEtOTAzOC00Y2JkLTlkMGQtZjNlNDNiZGNmZmVkIiwKICAiYWlkIjogIjIiLAogICJuZXQiOiAiaDIiLAogICJ0eXBlIjogIm5vbmUiLAogICJwYXRoIjogIi85NDQ1NTIxZC8iLAogICJ0bHMiOiAidGxzIgp9Cg==
```

**Comment by DuckSoft** [comment]
@Roger-WIN 收到

**Comment by DuckSoft** [comment]
@DuckSoft 你可能，需要删掉导入前的链接，然后用新版再导入一次？

**Comment by DuckSoft** [comment]
> 反而不能联网了。
> 我想是不是这两处 commit 冲突：
> ![image](https://user-images.githubusercontent.com/25821208/76736336-9119bc80-67a1-11ea-9747-1474cb11e412.png)
> 
> 提供一个有效的 Vmess 链接供测试：
> 
> ```
> vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJ3dWxhYmluZ19kZW1vLnZwcy5yb2dlcmt1bmctd2luLnRvcCIsCiAgImFkZCI6ICJkZW1vLnZwcy5yb2dlcmt1bmctd2luLnRvcCIsCiAgInBvcnQiOiAiNDQzIiwKICAiaWQiOiAiMTg4ZGRlNzEtOTAzOC00Y2JkLTlkMGQtZjNlNDNiZGNmZmVkIiwKICAiYWlkIjogIjIiLAogICJuZXQiOiAiaDIiLAogICJ0eXBlIjogIm5vbmUiLAogICJwYXRoIjogIi85NDQ1NTIxZC8iLAogICJ0bHMiOiAidGxzIgp9Cg==
> ```

这两处分别对应 Vmess 导出和导入。应该是正常的。

**Comment by DuckSoft** [comment]
Any Updates?

**Comment by Roger-WIN** [comment]
@DuckSoft 能翻出去访问 Google 吗？

我测试的时候在 v2.2.1 和 v2.2.2 之间来回切换，每次都删掉先前的链接再重新导入：

- 对于 v2.2.1，删除原有链接、导入链接、手动修改传输协议为 `http`，可以正常连外网。

  此时导出链接为

  ```
  vmess://eyJhZGQiOiJkZW1vLnZwcy5yb2dlcmt1bmctd2luLnRvcCIsImFpZCI6MiwiaG9zdCI6IiIsImlkIjoiMTg4ZGRlNzEtOTAzOC00Y2JkLTlkMGQtZjNlNDNiZGNmZmVkIiwibmV0IjoiaHR0cCIsInBhdGgiOiIvOTQ0NTUyMWQvIiwicG9ydCI6NDQzLCJwcyI6Ind1bGFiaW5nX2RlbW8udnBzLnJvZ2Vya3VuZy13aW4udG9wIiwidGxzIjoidGxzIiwidiI6Mn0=
  ```

- 对于 v2.2.2，删除原有链接、导入链接，不可正常连外网。

  此时导出链接为

  ```
  vmess://eyJhZGQiOiJkZW1vLnZwcy5yb2dlcmt1bmctd2luLnRvcCIsImFpZCI6MiwiaG9zdCI6IiIsImlkIjoiMTg4ZGRlNzEtOTAzOC00Y2JkLTlkMGQtZjNlNDNiZGNmZmVkIiwibmV0IjoiaDIiLCJwYXRoIjoiLzk0NDU1MjFkLyIsInBvcnQiOjQ0MywicHMiOiJ3dWxhYmluZ19kZW1vLnZwcy5yb2dlcmt1bmctd2luLnRvcCIsInRscyI6InRscyIsInYiOjJ9
  ```

此外，如果在前面提到的 v2.2.1 正常使用的情况下，切换到 v2.2.2，不重新导入，使用原有的链接，可以连外网。如果如前所述，删掉了重新导入，则不可连外网。

**Comment by DuckSoft** [comment]
咱这的情况是：上面的链接正确，但是链接会报错误。
看情况是上游 nginx 没有做相关配置，或者说提供的验证凭据有误。
```
2020/03/16 17:12:33 [Warning] [3511263105] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status404] > v2ray.com/core/common/retry: all retry attempts failed
```

**Comment by Roger-WIN** [comment]
真是见鬼。我导入链接之后，如果直接启动连接，是不能连外网的；如果打开连接编辑器查看一下（不做更改），再**点 OK 按钮退出**，就能正常用了。🤣

**Comment by DuckSoft** [comment]
> 真是见鬼。我导入链接之后，如果直接启动连接，是不能连外网的；如果打开连接编辑器查看一下（不做更改），再**点 OK 按钮退出**，就能正常用了。rofl

@Qv2ray-dev :rofl:

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/76745920-9aab2080-67b1-11ea-9651-898f46330d95.png)
查出问题了。 cc @Qv2ray-dev

**Comment by DuckSoft** [comment]
问题已经定位。真是麻烦您了，陪我们 debug 了半天。

**Comment by DuckSoft** [comment]
修了。等这个跑完，然后你就可以直接拿更新后的 AppImage 包了。
https://github.com/Qv2ray/Qv2ray/actions/runs/56631056

**Comment by Roger-WIN** [comment]
> 修了。等这个跑完，然后你就可以直接拿更新后的 AppImage 包了。
> https://github.com/Qv2ray/Qv2ray/actions/runs/56631056

能正常用了。👌

**Comment by Qv2ray-dev** [comment]
@Roger-WIN Thanks!
