### ISSUE TITLE
v2.2.3 under hiDPI screen 'Configuration Details' has wrong line height 

### ISSUE THREAD

**Issue by ttys3** [Qv2ray/Qv2ray#425]
**Briefly describe this bug：**

v2.2.3 under hiDPI screen 'Configuration Details' has wrong line height like this:

![image](https://user-images.githubusercontent.com/41882455/76780523-2cce1b80-67e8-11ea-8ae5-481f814a3f14.png)

everything works good except 'Configuration Details' 

**How can I trigger this bug：**

just exec:
```
./Qv2ray.v2.2.3.linux-x64.AppImage
```

**What is expected to happen**

`Configuration Details` should show correctly

**Screenshots**

![image](https://user-images.githubusercontent.com/41882455/76780523-2cce1b80-67e8-11ea-8ae5-481f814a3f14.png)

**System Information**

 - OS Type: Linux
 - download from the release
 - v2.2.3.4718

**Other Info**

4K display with 200% scale under Gnome3 desktop environment:

![image](https://user-images.githubusercontent.com/41882455/76781099-24c2ab80-67e9-11ea-863d-5f8c5b8bc30f.png)

**Comment by DuckSoft** [comment]
Have you tried with `--hiDPI` argument?

**Comment by ttys3** [comment]
> Have you tried with `--hiDPI` argument?

Yes. but not work:
```
/Qv2ray.v2.2.3.linux-x64.AppImage --debug --hiDPI 
[CORE-UI]: Found en_US in folder: /tmp/.mount_Qv2rayW8VKfq/usr/share/qv2ray/lang
Qv2ray::common::CommandLineParseResult Qv2ray::common::QvCommandArgParser::ParseCommandLine(QString*):63 [INIT]: hiDPI is set.
QCommandLineParser: option not defined: "force-hiDPI"
```

**Comment by DuckSoft** [comment]
Investigation in progress.

**Comment by DuckSoft** [comment]
try run with environment variable `QT_AUTO_SCREEN_SCALE_FACTOR=1` and see what happens

**Comment by ttys3** [comment]
thanks. put env `QT_AUTO_SCREEN_SCALE_FACTOR=1` the app works good. :+1: 

also I've found some interesting document may be help me understand this:
> Qt 5.6 supports cross-platform high-DPI scaling for legacy applications, similar to the scaling done natively in macOS. This allows applications written for low DPI screens to run unchanged on high DPI devices. This feature is opt-in, and can be enabled using the following environment variables:

> `QT_AUTO_SCREEN_SCALE_FACTOR` [boolean] enables automatic scaling, based on the monitor's pixel density. This won't change the size of point-sized fonts, since point is a physical measurement unit. Multiple screens may get different scale factors.
> `QT_SCALE_FACTOR` [numeric] defines a global scale factor for the whole application, including point-sized fonts.
> `QT_SCREEN_SCALE_FACTORS` [list] specifies scale factors for each screen. This won't change the size of point-sized fonts. The environment variable is mainly useful for debugging, or to work around monitors with wrong EDID information(Extended Display Identification Data).

**Comment by DuckSoft** [comment]
All right. Case closed.
Have fun with Qv2ray!
