### ISSUE TITLE
如果有可能的话，能不能适配高分屏

### ISSUE THREAD

**Issue by Minghan1992** [Qv2ray/Qv2ray#426]
**简单描述这个 bug：**
高分屏 3K
某些文字就显示不全了
情人节更新可以通过拉大面板可以避免这个为

**如何复现这个bug：**
1.  有一个高分屏的笔记本 自己使用的是xps 13 9360
2.  Elementary OS 调整到两倍像素大小
3.  文字就会显示不全了
4. 

**Qv2ray 本应该是怎样工作的？**

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - 
 - 是从release下载的还是自己编译的
    - 
 - 首选项里的版本号：
    - 

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by DuckSoft** [comment]
https://github.com/Qv2ray/Qv2ray/issues/425#issuecomment-599655358

**Comment by Minghan1992** [comment]
That works
Appreciate
