### ISSUE TITLE
Windows 4K HiDPI 两倍缩放下字体显示异常

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#427]
![图片](https://user-images.githubusercontent.com/7822648/76921893-13bd8b80-690a-11ea-9438-98495d6abb72.png)

**Comment by Qv2ray-dev** [comment]
Just wondering if [this commit](https://github.com/Qv2ray/Qv2ray/commit/1d488b0e38ec8a4d65b72f4bec90700157b59a33) will fix the issue.

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/76992406-2ecde100-6986-11ea-9679-6d8ac7ea2fec.png)
完 美 解 决
