### ISSUE TITLE
Windows 下关闭系统代理时不会重设 HTTP 代理设定

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#441]
RT

**Comment by Qv2ray-dev** [comment]
Acknowledged

**Comment by WXpiero** [comment]
遇到同样问题，好像不止一个版本了。ping正常，lookup正常，dns正常，就是尼玛打不开网页，只有电报，qq，微信电脑版能用。到处找原因。后来打开qv2ray就能上网了，不打开的话，甚至连群晖和路由器的管理网页都打不开

**Comment by Qv2ray-dev** [comment]
See #551
