### ISSUE TITLE
New Plugin: V2Ray Remote Control

### ISSUE THREAD

**Issue by mervynsword** [Qv2ray/Qv2ray#442]
RT

**Comment by DuckSoft** [comment]
我相信这大概要非常非常久远的版本之后了。
插件系统完善之后，我们也许可以开一个库专门做这个插件，以及这个插件对应的后端。

敬请期待。

**Comment by Qv2ray-dev** [comment]
We may need a public API which Qv2ray can exchange data with existing data sources.

**Comment by Qv2ray-dev** [comment]
@mervynsword 你好，请问所谓  “V2ray 远程控制插件” 是什么意思呢？
需要控制远程 V2ray 服务器吗？

**Comment by mervynsword** [comment]
@Qv2ray-dev 不是控制服务器，是使用V2RAY开放的API实现添加删除代理、用户等功能，并没有要上升到控制服务器的程度。

**Comment by Qv2ray-dev** [comment]
@mervynsword  其实 V2ray 的 API 并不足以支撑这些功能，我们需要更好的解决方案
