### ISSUE TITLE
[cleanup] header guard is missing

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#443]
missing `#pragma once`. multiple imports can occur.

https://github.com/Qv2ray/Qv2ray/blob/9598a8d388b31360ddd89670113df9db04192d08/src/core/connection/Generation.hpp#L1-L5

https://github.com/Qv2ray/Qv2ray/blob/9598a8d388b31360ddd89670113df9db04192d08/src/core/settings/SettingsBackend.hpp#L1-L4

**Comment by Qv2ray-dev** [comment]
fixed
