### ISSUE TITLE
[cleanup] avoid unsafe invocation to std::localtime

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#445]
https://github.com/Qv2ray/Qv2ray/blob/9598a8d388b31360ddd89670113df9db04192d08/src/common/QvHelpers.hpp#L101-L109

The time related functions fill data into shared memory and then returns a pointer to that memory. If the function is called from multiple places in the same program, and especially if it is called from multiple threads in the same program, then the calls will overwrite each other's data.

Solution: replace calls to `localtime` with `localtime_r`.

**Comment by Qv2ray-dev** [comment]
fixed
