### ISSUE TITLE
是没有切换全局代理的选项吗?

### ISSUE THREAD

**Issue by natonzyh** [Qv2ray/Qv2ray#446]
有时候路由规则里面没有的网站也想走代理，有什么办法吗

**Comment by DuckSoft** [comment]
这是两个问题呀。

先回答 Issue 正文的问题：https://v2ray.com/chapter_02/03_routing.html#ruleobject

**Comment by DuckSoft** [comment]
再回答 Issue 标题的问题：没有。不过：

* Windows / macOS 系统下，大部分程序都会遵循系统代理设定，你只需要在设置（或者右键托盘）中启用系统代理即可。
* Linux 下情况变得非常复杂。您可以参考这篇文章：https://github.com/Qv2ray/Qv2ray/wiki/Getting-Started-step4_zh

最后，您可考虑加入 Qv2ray 的 Telegram 群组：https://t.me/qv2ray
本 Issue 因为不符合规范，在此先行关闭。
