### ISSUE TITLE
V2ray Assets 路径不可用

### ISSUE THREAD

**Issue by sundayle** [Qv2ray/Qv2ray#452]
![image](https://user-images.githubusercontent.com/14009345/77517721-92d93380-6eb7-11ea-942d-7e5856031548.png)
V2ray Assets 路径不可用 报错

**Comment by DuckSoft** [comment]
V2Ray 资源目录处请填写 `D:/Qv2ray.v2.3.2.Windows-x64/deployment/config/vcore/`

**Comment by sundayle** [comment]
依旧报错。
![image](https://user-images.githubusercontent.com/14009345/77518076-1430c600-6eb8-11ea-86a9-da6763604fca.png)

**Comment by DuckSoft** [comment]
能否打开 D:/Qv2ray.v2.3.2.Windows-x64/deployment/config/vcore/ 文件夹，截个图让我看看里面都有啥文件呢？

**Comment by DuckSoft** [comment]
https://github.com/Qv2ray/Qv2ray/wiki/Getting-Started-step2_zh#2-%E8%AE%A9-qv2ray-%E4%BD%BF%E7%94%A8%E5%AE%89%E8%A3%85%E5%A5%BD%E7%9A%84v2ray%E6%A0%B8%E5%BF%83%E5%B7%A5%E4%BD%9C

另外，此文档供您参考。

**Comment by sundayle** [comment]
好了。谢谢。将所有v2ray所有放进去就可以了。
