### ISSUE TITLE
win平台下，如何更方便升级？

### ISSUE THREAD

**Issue by halk947** [Qv2ray/Qv2ray#453]
> 在linux环境下下，执行文件和配置文件分离，直接`yay`或者`apt`命令就可以完成升级。

在windows下每次升级都比较麻烦：
1. 下载新版本
2. 导出订阅和连接信息
3. 删除旧版本，重新配置，重新导入连接信息

特别是第三步，很耗时麻烦

曾经尝试过备份`config`目录，但可能是前向兼容的问题，无效

有没有更简单快捷的升级方式，或者说正确的升级方式是什么？

**Comment by DuckSoft** [comment]
有。我们正在和 Scoop （一个 Windows 的包管理器）做联动。
Scoop 能自动处理 V2Ray 核心和 Qv2ray 的安装和升级。

敬请期待。

**Comment by Qv2ray-dev** [comment]
你好，现在的配置文件是向前兼容的，不知道您在手动备份 config 文件夹时出现了什么问题？

**Comment by Qv2ray-dev** [comment]
更新步骤只需要讲新版本发布包解压缩到同文件夹并替换重复文件即可

或者您可以把 config 文件夹放到 `C:\Users\用户名\.qv2ray` 即可

**Comment by DuckSoft** [comment]
无关内容：
1. 若您觉得 Qv2ray 好用，不妨给我们点个免费的 star。
2. 欢迎加入我们位于 Telegram 的 [Qv2ray User Group](https://t.me/qv2ray)。

**Comment by halk947** [comment]
> 更新步骤：
> 只需要把新版本发布包 解压缩 到同文件夹，并替换重复文件即可
> 
> 或者您可以把 config 文件夹放到 `C:\Users\用户名\.qv2ray` 避免替换文件

感谢各位的及时回复。 @DuckSoft 

请问如果要采用 `C:\Users\用户名\.qv2ray` 这种方式，还需要其他额外配置吗，还是直接创建这个目录，然后剪切config目录到这个目录下就可以？

**Comment by Qv2ray-dev** [comment]
@halk947 是的，直接创建目录并把配置文件放进去即可，文件目录结构与 config 文件夹相同

注意： .qv2ray 目录优先级低于 exe 同目录的 config 子文件夹，使用时请确保删除 config 文件夹

**Comment by halk947** [comment]
> @halk947 是的，直接创建目录并把配置文件放进去即可，文件目录结构与 config 文件夹相同
> 
> 注意： .qv2ray 目录优先级低于 exe 同目录的 config 子文件夹，使用时请确保删除 config 文件夹

测试了一下，没有实现预期结果
1. 退出qv2ray应用
2. 在个人目录下创建 `.qv2ray`目录，将config目录剪切到这里
![home config](https://user-images.githubusercontent.com/1014928/77527220-b788d780-6ec6-11ea-96f7-52240505fb73.png)
3. 重新打开qv2ray应用
- 预期结果: 读取个人目录下的配置
- 实际结果: 程序自动在exe目录下，创建了config目录，原有配置都没了
![f_config](https://user-images.githubusercontent.com/1014928/77527329-e4d58580-6ec6-11ea-85e2-d0a575229a20.png)

**Comment by Qv2ray-dev** [comment]
你好， .qv2ray 里面不需要再添加 config 目录，直接 `C:\Users\USER\.qv2ray\Qv2ray.conf` 即可

**Comment by halk947** [comment]
@Qv2ray-dev  Done
谢谢

**Comment by DuckSoft** [comment]
Case Closed!
