### ISSUE TITLE
关于路由功能：希望在为所有简单连接配置路由规则的面板内加入修改域名解析策略的选项

### ISSUE THREAD

**Issue by ACERLZ** [Qv2ray/Qv2ray#456]
查看设置发现域名解析策略（domainStrategy）默认设置为“IPIfNonMatch”，且不能在默认设置文件里更改，尝试修改在启动后会自行修正。
一般“AsIs”是v2ray的默认设置，而且我希望域名未匹配时尽量减少路由解析。
所以希望能在“首选项”→“高级路由设置”中添加域名解析策略的修改选项，能选择切换“AsIs”,"IPIfNonMatch","IPOnDemand","UseIP","UseIPv4","UseIPv6"。

**Comment by DuckSoft** [comment]
收到。计划将于本周六的更新版本中放出。
敬请期待。

**Comment by DuckSoft** [comment]
另：欢迎加入我们的 Telegram 群组（Qv2ray User Group）在线监工。
https://t.me/qv2ray

**Comment by Qv2ray-dev** [comment]
@ACERLZ 你好，请问 `,"UseIP","UseIPv4","UseIPv6"` 这三个选项是在哪里能找到呢？

**Comment by ACERLZ** [comment]
> @ACERLZ 你好，请问 `,"UseIP","UseIPv4","UseIPv6"` 这三个选项是在哪里能找到呢？

是我的失误，重新查看了一下，根据v2fly的官方文档"UseIP","UseIPv4","UseIPv6"仅在“Freedom”出站中的"domainStrategy"可填，没有在"routing"中找到这三项；
"routing"里的"domainStrategy"可填“AsIs”,"IPIfNonMatch","IPOnDemand"，谢谢指正。

**Comment by Qv2ray-dev** [comment]
好的，感谢您的配合

**Comment by ACERLZ** [comment]
@DuckSoft 谢谢，期待Qv2ray的项目越做越好。

**Comment by Qv2ray-dev** [comment]
It should be fixed within the `dev` branch. 
For archlinuxcn, you may want to use `qv2ray-dev-git` to access the fix for now.

A new weekly release will be published on Saturday.

**Comment by DuckSoft** [comment]
更改已经合并到 dev 分支，但目前因为依赖变更原因，原有 PKGBUILD 尚不可用。
请等待修复。

**Comment by DuckSoft** [comment]
已修复。您可以直接从 AUR 中构建，也可等待 ArchLinuxCN 自动构建结束后再 pacman -Sy qv2ray-dev-git。
