### ISSUE TITLE
两个有关 socks 连接的小 bug

### ISSUE THREAD

**Issue by unknowndev233** [Qv2ray/Qv2ray#457]
**简单描述这两个 bug：**
在新增 socks 节点连接时没有设置密码，确定新增后编辑节点会用户与密码字段会出现 username 和 password字样

因为上一个 bug 出现的 bug（根据配置看，关系不大）：
哪怕把密码删掉也不能连接没有任何验证的 socks 节点连接

**如何复现这个bug：**
1. 新建一个 socks 节点连接
2. 确定没有输入任何密码后确认新建
3. 看到了不应该出现的 username 和 password

**Qv2ray 本应该是怎样工作的？**

用户与密码是空的，并且可以连接无验证的 socks

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

很抱歉，在 v2rayN/v2rayNG 没有遇到

**相关截图或日志**
![2020-03-26_15-22](https://user-images.githubusercontent.com/52807407/77622818-ed3ac880-6f79-11ea-8ef7-d0f1a2697b82.png)
![2020-03-26_15-26](https://user-images.githubusercontent.com/52807407/77622851-fe83d500-6f79-11ea-8bc2-12f338da5444.png)

```
日志：没有日志，也不需要

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - Arch
 - 是从release下载的还是自己编译的
    - archlinuxcn 仓库
 - 首选项里的版本号：
    - 2.3.2.4957

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

- 本地 socks 节点的配置文件很简单（

**Comment by Qv2ray-dev** [comment]
@unknowndev233 Please try out https://github.com/Qv2ray/Qv2ray/commit/a17d6f280297cce6b906bb791a2122de46a12afc ?

**Comment by DuckSoft** [comment]
已经在 dev 分支中修复。将于不日后 release 一个测试版本。
您可以直接从 AUR 中构建，也可等待 ArchLinuxCN 自动构建结束后再 pacman -Sy qv2ray-dev-git。
