### ISSUE TITLE
在Windows下设置系统代理时能提供自定义例外地址的选项吗？

### ISSUE THREAD

**Issue by ijglb** [Qv2ray/Qv2ray#458]
图中红框的地方
![截图](https://user-images.githubusercontent.com/31527814/77718078-f29d1f00-701c-11ea-8735-3af0f6ae217e.jpg)

**Comment by Qv2ray-dev** [comment]
可以

**Comment by DuckSoft** [comment]
@Qv2ray-dev 计划到下一个版本，还是周六的版本？

**Comment by Qv2ray-dev** [comment]
@DuckSoft Next release

**Comment by DuckSoft** [comment]
Roger that. Holding this.

**Comment by Qv2ray-dev** [comment]
See #551

**Comment by DuckSoft** [comment]
为不打扰大家，后续讨论请去 #551。
本 Issue 先行关闭。
