### ISSUE TITLE
QvHelpers.cpp:20:25: error: ‘QRandomGenerator’ has not been declared

### ISSUE THREAD

**Issue by hylyq** [Qv2ray/Qv2ray#459]
**简单描述这个 bug：**
arch linux系统中，aur 仓库安装 qv2ray 或 qv2ray-dev-git 均出现该错误。

CMakeFiles/qv2ray.dir/src/common/QvHelpers.cpp.o -MF CMakeFiles/qv2ray.dir/src/common/QvHelpers.cpp.o.d -o CMakeFiles/qv2ray.dir/src/common/QvHelpers.cpp.o -c ../src/common/QvHelpers.cpp
../src/common/QvHelpers.cpp: In function ‘const QString Qv2ray::common::GenerateRandomString(int)’:
../src/common/QvHelpers.cpp:20:25: error: ‘QRandomGenerator’ has not been declared
   20 |             uint rand = QRandomGenerator::system()->generate();
      |                         ^~~~~~~~~~~~~~~~
[46/231] Building CXX object CMakeFiles/q...dir/qv2ray_autogen/mocs_compilation.cpp.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
Error making: qv2ray-dev-git

**相关截图或日志**

CMakeFiles/qv2ray.dir/src/common/QvHelpers.cpp.o -MF CMakeFiles/qv2ray.dir/src/common/QvHelpers.cpp.o.d -o CMakeFiles/qv2ray.dir/src/common/QvHelpers.cpp.o -c ../src/common/QvHelpers.cpp
../src/common/QvHelpers.cpp: In function ‘const QString Qv2ray::common::GenerateRandomString(int)’:
../src/common/QvHelpers.cpp:20:25: error: ‘QRandomGenerator’ has not been declared
   20 |             uint rand = QRandomGenerator::system()->generate();
      |                         ^~~~~~~~~~~~~~~~
[46/229] Building CXX object CMakeFiles/q...dir/qv2ray_autogen/mocs_compilation.cpp.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
Error making: qv2ray

**系统信息**
 - 系统类型（windows, linux, macos）
    - linux
 - 是从release下载的还是自己编译的
    - aur库
 - 首选项里的版本号：
aur/qv2ray-dev-git 2.3.2.4981+grpc-1 (+2 0.38%) 
    Cross-platform V2ray Client written in Qt (Development Release)
aur/qv2ray 2.2.0-1 (+5 1.21%) 
    Cross-platform V2ray Client written in Qt (Stable Release)

**其他信息**

- arch linux 系统安装的Qt开发环境版本为 Qt 5.14

**Comment by Qv2ray-dev** [comment]
你的 Qt 版本是？

**Comment by DuckSoft** [comment]
@hylyq 上古Qt版本

**Comment by hylyq** [comment]
> 你的 Qt 版本是？

5.14

**Comment by DuckSoft** [comment]
@hylyq pacman -Q qt5-base

**Comment by hylyq** [comment]
> @hylyq pacman -Q qt5-base

$ pacman -Q qt5-base
qt5-base 5.14.1-3

**Comment by DuckSoft** [comment]
简而言之，你的系统Qt被污染了。
cc @ymshenyu

**Comment by ymshenyu** [comment]
@hylyq 能截一张cmake-gui的图片吗？ 我需要看一下构建变量。

**Comment by DuckSoft** [comment]
先直接解决问题。
https://github.com/Qv2ray/Qv2ray/actions/runs/64040846

自取自动构建的包。

**Comment by hylyq** [comment]
> @hylyq 能截一张cmake-gui的图片吗？ 我需要看一下构建变量。

![image](https://user-images.githubusercontent.com/22679780/77721583-452f0900-7026-11ea-8bbf-1de8d135e621.png)

是这个么

**Comment by ymshenyu** [comment]
> > @hylyq 能截一张cmake-gui的图片吗？ 我需要看一下构建变量。
> 
> ![image](https://user-images.githubusercontent.com/22679780/77721583-452f0900-7026-11ea-8bbf-1de8d135e621.png)
> 
> 是这个么

对

**Comment by DuckSoft** [comment]
关于您系统构建环境被污染的问题，若您有兴趣处理，可以加入我们的 telegram 群组（https://t.me/qv2ray）与我们交流。

若您只是想拿个包，运行一下 Qv2ray，您可就地关闭本 issue。

**Comment by DuckSoft** [comment]
调查结束。Anaconda 劫持。

**Comment by hylyq** [comment]
> 调查结束。Anaconda 劫持。

关闭conda 虚拟环境后已解决，非常感谢～
