### ISSUE TITLE
Please add a hotkey to mimimize the main window to the tray icon immediately

### ISSUE THREAD

**Issue by acgtyrant** [Qv2ray/Qv2ray#463]
The hotkey can be ctrl+q or exit. Having to click the tray icon every time is boring.

**Comment by Qv2ray-dev** [comment]
@acgtyrant By closing the MainWindow, you can have Qv2ray hidden into system tray.

**Comment by acgtyrant** [comment]
What I need is a hotkey... I use Arch Linux and i3 where the window has not closing button in window title.

Okay, now I find out that the default hotkey of i3, used to close any window, also works. You can reopen this issue if you decide to add this feature.

**Comment by Qv2ray-dev** [comment]
@acgtyrant Do you think Esc could help?

**Comment by acgtyrant** [comment]
Esc is more convenient than `ctrl-q` or my i3 default hotkey `super-q` anyway, and I thought many people will agree with it too.

**Comment by Qv2ray-dev** [comment]
@acgtyrant Thanks! We’ll make Esc a hotkey to close the mainwindow.

**Comment by Qv2ray-dev** [comment]
Please wait for https://github.com/Qv2ray/Qv2ray/pull/465 to be merged

**Comment by DuckSoft** [comment]
Added. Closing.
