### ISSUE TITLE
将Mux和TFO移到全局设置

### ISSUE THREAD

**Issue by Bit0r** [Qv2ray/Qv2ray#464]
希望将**Mux并发**和**TCP快速打开**移到全局的**连接设置**中，那样就不用一个个去打开这个选项了。如果配置在单个连接上，每次**订阅更新**又需要**重新设置**，非常麻烦

**Comment by DuckSoft** [comment]
久等了。即将在 2.7.0-pre1 / -rc1 中支持此功能。
后续进展请参见 #859.
