### ISSUE TITLE
Mac下v2ray设置无效，无法推测v2ray类型

### ISSUE THREAD

**Issue by happier233** [Qv2ray/Qv2ray#467]
**简单描述这个 bug：**
在首选项里设置了v2ray的核心可执行文件路径和V2ray资源目录
检查核心设置时提示无法推测核心可执行文件类型

**如何复现这个bug：**
1. 新安装一遍
2. 设置一下
3. 点击检查

**Qv2ray 本应该是怎样工作的？**
正常工作

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 
无关

**相关截图或日志**

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - 
 - 是从release下载的还是自己编译的
    - release
 - 首选项里的版本号：
    - 2.4.0.5000

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by DuckSoft** [comment]
收到。检查问题中。

**Comment by DuckSoft** [comment]
问题已定位。数分钟后将放出修复版本。
为 macOS 用户带来的不便表示歉意（实在是没有 macOS 设备测试）

**Comment by DuckSoft** [comment]
https://github.com/Qv2ray/Qv2ray/actions/runs/65703407

问题已修复。自动构建已启动。
您可稍候片刻（约 5 分钟左右），然后从上面的链接取得已经修复的更新。

**Comment by DuckSoft** [comment]
自动构建工作已经完成。您现可取用已修复的软件。

**Comment by DuckSoft** [comment]
https://github.com/Qv2ray/Qv2ray/releases/download/v2.4.0/Qv2ray.v2.4.0+hotfix1.macOS-x64.tar.gz
您也可直接从此处下载。
