### ISSUE TITLE
请问一下2.4.0的Appimage版本去哪儿了？

### ISSUE THREAD

**Issue by catfishjones** [Qv2ray/Qv2ray#469]
我想问一下2.4.0版的Appimage版本在哪里下载，我的Fedora用不了deb和arch的包。

**Comment by DuckSoft** [comment]
@catfishjones 收到。处理中。

**Comment by DuckSoft** [comment]
https://github.com/Qv2ray/Qv2ray/actions/runs/65661748

您可查看此处。稍后将上传 AppImage 到 Release。
可能是自动构建出了点问题。

**Comment by DuckSoft** [comment]
已经补到 Release 里了。
应该是数小时前的一个维护操作误删了 .AppImage。
