### ISSUE TITLE
macOS 初次启动界面风格异常

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#472]
![2DFBA0FF-D80F-40CE-B70B-18875EF865AD](https://user-images.githubusercontent.com/7822648/77854785-e7b1dc80-721e-11ea-94f0-f0faf15f7c15.jpeg)

**Comment by Qv2ray-dev** [comment]
should have been fixed by #478

**Comment by DuckSoft** [comment]
Can someone test this?

**Comment by DuckSoft** [comment]
Assuming Fixed.
