### ISSUE TITLE
[critical] 复杂配置忘记取名则无法新增

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#473]
复现方法：
1. 添加->打开路由编辑器
2. 随便编辑，确定
3. 啥也没发生

期望：
3. 列表里多了个复杂配置

原因：默认名字是空的，但是 Qv2ray 在空名字的时候并没有阻止这一行为
建议：如果真是空名字，弹一个 QInputBox 临时问一下，免得出毛病

**Comment by Qv2ray-dev** [comment]
ack

**Comment by Qv2ray-dev** [comment]
fixed

**Comment by DuckSoft** [comment]
ACK. CLOSING.
