### ISSUE TITLE
Mac 10.14系统，提示需要10.15系统才能安装

### ISSUE THREAD

**Issue by zhangjinhua0308** [Qv2ray/Qv2ray#475]

**Comment by DuckSoft** [comment]
这个问题是因为 GitHub 给我们提供的打包机只有 10.15 系统的。
Qv2ray 开发组无任何一人拥有 macOS 设备，我们也很想修复这个问题。

可能得等一个大神帮我们处理一下这个问题了。

**Comment by LianYangCn** [comment]
我帮忙瞅瞅

**Comment by Qv2ray-dev** [comment]
We are testing to install xCode on Github Action. See: https://github.com/Qv2ray/Qv2ray/commit/d6c28c96e6c5e9b88164c861e21fb60474d5efc2

**Comment by Qv2ray-dev** [comment]
@LianYangCn Thanks!

**Comment by Qv2ray-dev** [comment]
@zhangjinhua0308  你好，请测试一下这里 https://github.com/Qv2ray/Qv2ray/actions/runs/66271051 的 macOS 包

**Comment by DuckSoft** [comment]
更新：@ymshenyu + @DuckSoft + @Qv2ray-dev 奋战一晚，已经基本解决此问题。
将于下次更新中放出。

**Comment by LianYangCn** [comment]
牛逼~

**Comment by Qv2ray-dev** [comment]
@zhangjinhua0308 你好，请尝试一下这里的版本： https://github.com/Qv2ray/Qv2ray/actions/runs/67374756

**Comment by DuckSoft** [comment]
> @zhangjinhua0308 你好，请尝试一下这里的版本： https://github.com/Qv2ray/Qv2ray/actions/runs/67374756

好消息，此包 macOS 10.14.4 测试一切正常！

**Comment by DuckSoft** [comment]
已经确认问题修复。Closing！

PS: Xcode 已经把我们折腾的死去活来

**Comment by zhangjinhua0308** [comment]
不好意思，我没看邮件。没帮你们测试ヽ(*´з｀*)ﾉ

**Comment by DuckSoft** [comment]
问题不大，问题不大。周六再说。

**Comment by cc978** [comment]
10.13 直接从release 下载安装后，根本无法运行，打开就报错闪退，原来是这样啊。
作者单独编译 10.14  10.13  10.15三个版本吧

**Comment by ymshenyu** [comment]
> 10.13 直接从release 下载安装后，根本无法运行，打开就报错闪退，原来是这样啊。
> 作者单独编译 10.14 10.13 10.15三个版本吧

目前已修复 请等待下一个版本或下载最新的artifact
