### ISSUE TITLE
Windows 10 Pro 2004 在启动 Qv2ray 后崩溃重启

### ISSUE THREAD

**Issue by LinHeLurking** [Qv2ray/Qv2ray#476]
**简单描述这个 bug：**
启动Qv2ray时Windows崩溃重启.  

**如何复现这个bug：**
复现该bug有两种方法.  
1.  设置Qv2ray自动启动, 然后重启Windows  
2.  关闭Qv2ray自动启动, 手动启动之  

经过反复的实验的确发现操作系统崩溃重启是和Qv2ray的启动有明显相关性的(但是Windows崩溃后的那一次重启可以让Qv2ray正常启动).

**Qv2ray 本应该是怎样工作的？**

正常启动, 不导致Windows崩溃.

**相关截图或日志**
由于启动后即崩溃, 没有办法提供截图或者程序日志.

**系统信息**
 - 系统类型（windows, linux, macos）
    - Windows 10 Pro, version 2004 (build 19041.172)
 - 是从release下载的还是自己编译的
    - release页面下载
 - 首选项里的版本号：
    - v2.4.0.5000

**Comment by DuckSoft** [comment]
这……怎么复现？

**Comment by Qv2ray-dev** [comment]
你可以提供一下 Windows 崩溃时的 MEMORY.DMP

**Comment by DuckSoft** [comment]
所以，崩溃重启有什么日志之类的吗？这个样子我们也没法调查呀。
另外，咱找了一个志愿者，全新安装的 Windows 10，打上了所有升级，没有任何问题。

检查一下主机本身的情况？

**Comment by DuckSoft** [comment]
Any Updates?

**Comment by DuckSoft** [comment]
问题反馈者没动静，也没给出复现方法，开发者和志愿者都未能成功复现。
束手无策，暂时关闭本 Issue。

若您有更新，可加群 https://t.me/qv2ray 直接和开发者贴脸输出。

以上。
