### ISSUE TITLE
win10 1903 无法打开Qv2ray

### ISSUE THREAD

**Issue by JunerLee** [Qv2ray/Qv2ray#482]
**简单描述这个 bug：**
双击Qv2ray图标无任何反应，也无任何报错
我的系统版本为win10 1903 (18362.535)
Qv2ray版本为2.4.0

**如何复现这个bug：**
1. 双击图标即可
2. 
3. 
4. 

**Qv2ray 本应该是怎样工作的？**

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 
其他客户端如v2rayN运行良好

**相关截图或日志**

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - 
 - 是从release下载的还是自己编译的
    - 
 - 首选项里的版本号：
    - 

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by Qv2ray-dev** [comment]
你好，你需要提供一下在 cmd 里面运行 `qv2ray.exe > log.txt` 之后的 log.txt 文件

**Comment by DuckSoft** [comment]
@JunerLee 很迷，win10 1903工作正常

**Comment by JunerLee** [comment]
[CORE-UI]: Found zh_CN in folder: lang
[QV2RAY_BUILD_INFO]: Qv2ray built from Github Action
[QV2RAY_BUILD_EXTRA_INFO]: qt5.14.2-53bdc2f5a3ac93d0c87759b093fc7ac2c83b7179-ci.windows-latest
[INIT]: Qv2ray v2.4.0.5000 running on Windows 10 Version 1903 x86_64
[INIT]: High DPI scaling is enabled.
[CORE-UI]: Found zh_CN in folder: lang
[CORE-UI]: Installing a tranlator from OS: zh_CN -- OK
[LICENCE]: 

This program comes with ABSOLUTELY NO WARRANTY.

This is free software, and you are welcome to redistribute it

under certain conditions.



Copyright (c) 2019-2020 Qv2ray Development Group.



Libraries that have been used in Qv2ray are listed below (Sorted by date added):

Copyright (c) 2020 xyz347 (@xyz347): X2Struct (Apache)

Copyright (c) 2011 SCHUTZ Sacha (@dridk): QJsonModel (MIT)

Copyright (c) 2020 Nikolaos Ftylitakis (@ftylitak): QZXing (Apache2)

Copyright (c) 2016 Singein (@Singein): ScreenShot (MIT)

Copyright (c) 2020 Itay Grudev (@itay-grudev): SingleApplication (MIT)

Copyright (c) 2020 paceholder (@paceholder): nodeeditor (Qv2ray group modified version) (BSD-3-Clause)

Copyright (c) 2019 TheWanderingCoel (@TheWanderingCoel): ShadowClash (launchatlogin) (GPLv3)

Copyright (c) 2020 Ram Pani (@DuckSoft): QvRPCBridge (WTFPL)

Copyright (c) 2019 ShadowSocks (@shadowsocks): libQtShadowsocks (LGPLv3)

Copyright (c) 2015-2020 qBittorrent (Anton Lashkov) (@qBittorrent): speedplotview (GPLv2)

Copyright (c) 2020 yhirose (@yhirose): cpp-httplib (MIT)




[INIT]: Qv2ray Start Time: 38386460
[INIT]: Application exec path: D:/Qv2ray-2.4.0/deployment
[INIT]: Path: D:/Qv2ray-2.4.0/deployment/config/ does not contain a valid config file.
[INIT]: Path: C:/Users/jun.li/AppData/Local/qv2ray does not contain a valid config file.
[INIT]: Path: C:/Users/jun.li/.qv2ray/ does not contain a valid config file.
[INIT]: Set D:/Qv2ray-2.4.0/deployment/config/ as the config path.
[INIT]: Created initial config file.
[INIT]: Created config generation dir at: D:/Qv2ray-2.4.0/deployment/config/generated/
[COMMON-FILEIO]: Some comments have been removed from the json.
[CORE-UI]: Found zh_CN in folder: D:/Qv2ray-2.4.0/deployment/lang
[INIT]: Removed translations
[INIT]: Successfully installed a translator for zh_CN
[COMMON-NETWORK]: Current OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
[CORE-UI]: Using built-in theme.
[CORE-UI]: Loading data...
[COMMON-NETWORK]: Start checking update for channel ID: 0
[COMPONENT-UPDATE]: Received update info, Latest: 2.4.0 Current: 2.4.0.5000 Ignored: 
[QV2RAY-CORE]: VCore is not started, not disconnecting
[QV2RAY-CORE]: Triggering save settings from destructor
[CORE-VCORE]: API thread stopped
[INIT]: Quitting normally

**Comment by JunerLee** [comment]
> 你好，你需要提供一下在 cmd 里面运行 `qv2ray.exe > log.txt` 之后的 log.txt 文件

最新进展

1. 我用cmd命令行输入qv2ray.exe > log.txt 后发现能启动qv2ray
2. 我右键‘用管理员身份运行’依旧打不开
3. 必须要用管理员的cmd命令行才能开启qv2ray

**Comment by DuckSoft** [comment]
@JunerLee 很迷，因为本地没法复现这个问题。

**Comment by JunerLee** [comment]
> @JunerLee 很迷，因为本地没法复现这个问题。

1.如果我用非管理员下的cmd命令行打开qv2ray.exe，提示拒绝访问
2.用管理员的cmd则成功运行
3.双击图标或者右键管理员运行暂时还是无任何反应

**Comment by Qv2ray-dev** [comment]
您不妨加入Telegram 群组与我们直接讨论：https://t.me/qv2ray

**Comment by DuckSoft** [comment]
玄学问题，救不了了。先关了。
