### ISSUE TITLE
HTTP 前置代理添加非常规 Header

### ISSUE THREAD

**Issue by anysoft** [Qv2ray/Qv2ray#483]
**简单描述这个 bug：**

在连接V2ray服务器之前先连接一个HTTP或者Sock5/4的代理服务器，再通过该代理服务器连接V2ray服务器。
在ss和SSR的客户端都有实现叫前置代理，也就是代理链。可以通过多次代理跳转。
1、实现前置代理功能，其中支持配置代理类型，代理IP端口，代理认证信息，代理header自定义(混淆自定义header项或者有些HTTP代理需要Base auth的request header项)

**如何复现这个bug：**

目前只能直接client直连接V2ray服务端，一些情况下导致V2ray对外暴露，容易封闭。
另外一些情况下，本地网络只能通过http代理访问外网，这时候就没法直接连接v2ray服务器了。

**Qv2ray 本应该是怎样工作的？**

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - 
 - 是从release下载的还是自己编译的
    - 
 - 首选项里的版本号：
    - 

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by DuckSoft** [comment]
@anysoft 你好，请仔细阅读设置窗口。

**Comment by Qv2ray-dev** [comment]
你好， Qv2ray 现已支持前置代理设置，不过需要注意这个问题：
https://github.com/Qv2ray/Qv2ray/issues/337

**Comment by anysoft** [comment]
> 你好， Qv2ray 现已支持前置代理设置，不过需要注意这个问题：
> #337

十分感谢，已经看到前置代理，但是有个问题，我这边前置代理是需要认证的，不是basic auth，而是需要在header中指定proxy_auth:123456789 项才能通过验证。
我想请教一下 Qv2ray这边，或者说v2ray-core的前置代理是否支持自定义header？

**Comment by DuckSoft** [comment]
@anysoft 看样子v2ray核心是不支持这个的。我在官方文档中没找到相关内容，抱歉哦～

**Comment by anysoft** [comment]
> @anysoft 看样子v2ray核心是不支持这个的。我在官方文档中没找到相关内容，抱歉哦～

我看官方的在http协议对象中有header对象和requst对象，不知道在配置http代理时候能否配置这个对象。有空尝试一下。对V2ray刚接触，多谢两位耐心解答 :-) 
等我尝试之后结果反馈上来我再关闭这个issue

**Comment by DuckSoft** [comment]
@anysoft 好的，若试验成功，请务必告知，我们会加上！
感谢反馈！

**Comment by DuckSoft** [comment]
情况如何？有无新进展？

**Comment by anysoft** [comment]
> @anysoft 好的，若试验成功，请务必告知，我们会加上！
> 感谢反馈！

经过测试和阅读v2ray-core源码及说明文档：前置代理不支持自定义header的方式。
v2ray-core针对http的出入站规则极其简陋，按照官方文档说法是因为http的不安全性问题，所以在这块官方没花费过多力气去做。针对http协议只支持security和tls的settings配置。
-----------------------------------------------------------
解决方案：
1. 可以自行修改源码编译core核心后实现。修改proxy/http/client.go 中setUpHttpTunnel 方法入参以及相关调用处，传入httpsettings对象
2. 可自行修改config.json文件用替代方案实现

我的替代方案是利用客户端的http伪装(服务器无需伪装)，将http代理地址和v2ray服务器地址互换。
连接逻辑流程：
1、因为修改v2ray服务器地址为http代理服务器地址，故新建tcp连接时候会向http代理服务器建立连接
2、因为客户端做了http伪装，在和http代理服务器建立连接后，会发送伪装http信息到http代理服务器
3、http代理服务器收到伪装的http请求信息(CONNECT 方式连接)，经过分析http request的header信息完成认证过程(这个伪装时候可以自定义)。
4、http代理服务器认证成功后会自动去连接伪装信息中的path地址，即真实的v2ray服务器，http代理服务器与v2ray服务器建立tcp连接后，http代理服务器向客户端返回HTTP 200的response，
5、至此整个代理链建立稳定连接完成。
6、客户端通过此连接发送v2ray的认证信息，经过http代理服务器转发后，客户端与v2ray服务器建立完整的vmess通道。


此原理主要利用http代理服务器在转发时候采用http path作为传输真实地址。通过v2ray和http服务器地址互换完成等价于http前置代理的效果。

【注意】：
服务端不需要配置http伪装！ 也不能配！
服务端不需要配置http伪装！也不能配！
服务端不需要配置http伪装！也不能配！

具体配置如下：
本范例中
http代理服务器为：192.168.0.1 端口： 8080

v2ray服务器为： vmess.anysoft.tk 端口：1080
id为：97a3ae04-d700-5c23-acc7-084412939931
alterId为：64

```json
{
	"policy": null,
	"log": {
		"access": "",
		"error": "",
		"loglevel": "warning"
	},
	"inbounds": [{
		"tag": "proxy",
		"port": 10808,
		"listen": "0.0.0.0",
		"protocol": "socks",
		"sniffing": {
			"enabled": true,
			"destOverride": [
				"http",
				"tls"
			]
		},
		"settings": {
			"auth": "noauth",
			"udp": true,
			"ip": null,
			"address": null,
			"clients": null
		},
		"streamSettings": null
	}],
	"outbounds": [{
			"tag": "proxy",
			"protocol": "vmess",
			"settings": {
				"vnext": [{
					"address": "192.168.0.1",
					"port": 8080,
					"users": [{
						"id": "97a3ae04-d700-5c23-acc7-084412939931",
						"alterId": 64
					}]
				}],
				"servers": null,
				"response": null
			},
			"streamSettings": {
				"network": "tcp",
				"tcpSettings": {
					"header": {
						"type": "HTTP",
						"request": {
							"version": "1.1",
							"method": "CONNECT",
							"path": ["vmess.anysoft.tk:1080"],
							"headers": {
								"Host": ["vmess.anysoft.tk:1080"],
								"Proxy-Authorization": [
									"xxxxx"
								],
								"Proxy-Connection": [
									"keep-alive"
								],
								"Authorization": [
									"Basic dXNlcm5hbWU6cGFzc3dvcmQ="
								]
							}
						},
						"response": {
							"version": "1.1",
							"status": "200",
							"reason": "OK",
							"headers": {
								"Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],
								"Transfer-Encoding": ["chunked"],
								"Connection": ["keep-alive"],
								"Pragma": "no-cache"
							}
						}
					}
				}
			}
		},
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {
				"vnext": null,
				"servers": null,
				"response": null
			},
			"streamSettings": null,
			"mux": null
		},
		{
			"tag": "block",
			"protocol": "blackhole",
			"settings": {
				"vnext": null,
				"servers": null,
				"response": {
					"type": "http"
				}
			},
			"streamSettings": null,
			"mux": null
		}
	],
	"stats": null,
	"api": null,
	"dns": null,
	"routing": {
		"domainStrategy": "IPIfNonMatch",
		"rules": [{
			"type": "field",
			"port": null,
			"inboundTag": "api",
			"outboundTag": "api",
			"ip": null,
			"domain": null
		}]
	}
}
```

经过实测，可以完美实现经过代理服务器时候加上自定义header。
此处headers中可以自行添加json格式的字段作为自定义header字段。
`"Authorization": [
		"Basic dXNlcm5hbWU6cGFzc3dvcmQ="
]`

便是添加的header  Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=
