### ISSUE TITLE
按钮控件上的图案不显示

### ISSUE THREAD

**Issue by Noah-Developer** [Qv2ray/Qv2ray#487]
**简单描述这个 bug：**

按钮控件上的图案不显示
GNOME桌面

**如何复现这个bug：**
1. 下载QV2Ray
2. 打开
3. 用你的眼睛盯着他

**Qv2ray 本应该是怎样工作的？**
应该显示的

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 
没有呢

**相关截图或日志**

```
日志：
我觉得没必要
```

**系统信息**
 - 系统类型（windows, linux, macos）
    - Fedora 31
 - 是从release下载的还是自己编译的
    - 下载的
 - 首选项里的版本号：
    - 

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by DuckSoft** [comment]
打开设置，有两个选项你需要注意：
![图片](https://user-images.githubusercontent.com/7822648/78065765-53827980-73c6-11ea-9252-d994989ed91f.png)

**Comment by DuckSoft** [comment]
若你使用深色主题，请启用深色主题图标。
反之，禁用深色主题图标。
退出重开软件生效。
