### ISSUE TITLE
About the automatical TCPing...

### ISSUE THREAD

**Issue by ACERLZ** [Qv2ray/Qv2ray#491]
Qv2ray has its tcping process triggered every one minute automatically.
This function cannot be closed or modified on the very new version and below.
For the reason that constant tcping could bring unexpected harm to a server node(I guess from your conversation in the TG channel), I hope that the official can add a switch on it, or even better a option-box / tab-strip by minute if possible.
Thanks for you considering.
Yours sincerely,
Product User

**Comment by Qv2ray-dev** [comment]
Thanks, we'll definitely add a switch to let users adjust this behavior.

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/79123932-d72c6500-7dcd-11ea-8ba7-052f5d2e1e33.png)
久 等 了

**Comment by ACERLZ** [comment]
@DuckSoft 感谢鸭鸭大佬，比心~

**Comment by DuckSoft** [comment]
> @DuckSoft 感谢鸭鸭大佬，比心~

咱没做什么，感谢 @Qv2ray-dev
