### ISSUE TITLE
Windows 快速关机 / 启动概率性丢失配置文件

### ISSUE THREAD

**Issue by Sodacooky** [Qv2ray/Qv2ray#492]
**简单描述这个 bug：**
在正常关机后，再次启动有几率丢失(清空)配置文件(/config/Qv2ray.conf)。

丢失后能明显地发现这个文件的修改时间是上次关机时间，被清空(显示0kb)。

ps.正常关机时qv2ray仍在后台，我期望通过关机结束它。

**如何复现这个bug：**
1. 正常关机后概率出现

**Qv2ray 本应该是怎样工作的？**

关机结束qv2ray时不应该修改配置文件(/config/Qv2ray.conf) ?

**系统信息**
 - 系统类型（windows, linux, macos）
    - Windows10 x64 Home
 - 是从release下载的还是自己编译的
    - 从release
 - 首选项里的版本号：
    - v2.4.0.5000

**其他信息**

Windows系统快速启动开启。

qv2ray随系统启动。

**Comment by DuckSoft** [comment]
@Sodacooky 调查中。

**Comment by rainyl** [comment]
同，前几天发生过一次，不过就这一次，基本情况相同

**Comment by LuXts** [comment]
同，发生了两次，第一次的版本号记不清楚了。
大部分情况相同：
### 系统信息

- 系统类型
  - Windows 10 X64 专业版

- 是从release下载的还是自己编译的
  - 从release

- 首选项里的版本号：
  - v2.3.2.4957

### 其他信息

- Windows系统快速启动关闭。

- qv2ray随系统启动。

**Comment by AIrSkycc** [comment]
昨天发生过一次同样问题，正常关机，开机后配置丢失。

**Comment by Qv2ray-dev** [comment]
https://github.com/Qv2ray/Qv2ray/actions/runs/77684196

这个问题我们正在着手修复，如果方便的话请各位试一下上面的开发版本，看看是否还会有类似问题出现。

（因为此次issue是概率性出现，烦请大家多测试几天）

**Comment by Soowin** [comment]
同，最近一周发生过两次

**Comment by Qv2ray-dev** [comment]
> 同，最近一周发生过两次

https://github.com/Qv2ray/Qv2ray/actions/runs/77684196

试一下这个版本？

**Comment by Qv2ray-dev** [comment]
@Sodacooky @Soowin @AIrSkycc @rainyl @LuXts 
请确认 v2.5.0-pre1 是否还有此类问题

**Comment by Sodacooky** [comment]
> @Sodacooky @Soowin @AIrSkycc @rainyl @LuXts
> 请确认 v2.5.0-pre1 是否还有此类问题

在使用了pre1后，3天大概开关机10来次，暂时没有发现丢配置的情况了。

**Comment by AIrSkycc** [comment]
测试一天后暂未复现此问题, 但更新2.5.0后, Vagrant Proxy代理无法使用了.

https://github.com/Qv2ray/Qv2ray/issues/526

@Qv2ray-dev

**Comment by LuXts** [comment]
> @Sodacooky @Soowin @AIrSkycc @rainyl @LuXts
> 请确认 v2.5.0-pre1 是否还有此类问题

使用后大概关机3次，暂时没有复现。

**Comment by Qv2ray-dev** [comment]
@LuXts 好的 👌

**Comment by Soowin** [comment]
此问题不再复现。谢谢开发者！

**Comment by DuckSoft** [comment]
Seems to be fixed. Feel free to **open new issues** if things still go wrong in newer versions (>=2.5.0-pre1).
