### ISSUE TITLE
[critical] cancel on qrcode image file choose dialog cause immediate crash

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#493]
Cancel case is not handled correctly.

https://github.com/Qv2ray/Qv2ray/blob/37dc46bd1335261aaa7cc9723f49148eb023ddc0/src/ui/w_ImportConfig.cpp#L210-L231

Bug exists up to 5 months ago. Urgent.

---
cc @Qv2ray-dev

**Comment by Qv2ray-dev** [comment]
This will not affect the older version with qzxing since it will check if the buffer is empty.
It now becomes an issue with zxing-cpp

**Comment by DuckSoft** [comment]
Seemed a fix is issued. 
Was that tested? @Qv2ray-dev 
If tested, close this plz.
