### ISSUE TITLE
【建议】添加可选每月月初自动清除流量统计数据

### ISSUE THREAD

**Issue by OnlyFor** [Qv2ray/Qv2ray#495]
功能已经非常强大了，UI也很漂亮，
如果能支持一下流量统计数据定期归零就更好了，

谢谢

**Comment by DuckSoft** [comment]
收到。这个功能听起来不错，但是我们还是要照顾更多用户呀。
比如说，有的用户的机场是流量月初重置，有的用户的机场是流量购买日后30日重置；还有的用户的机场是年初重置、360日后重置；甚至还有的机场完全是用户自行购买流量……

我们其实很早就想加这个功能，不过就目前来说，还在进行权衡。毕竟自动化的东西做不好，反而会给用户带来一定的麻烦。目前的一个折衷方案，应该是在组的右键菜单加入一个“清除本组所有统计数据”的选项，让用户手动去重置。

敬请期待。

**Comment by OnlyFor** [comment]
谢谢，考虑全面的话会细致一些，比如在首选项的常规设置中添加‘自动清除统计数据’，默认关闭，下拉可选：每月初，每月末，每xx天，等等，这样就是会开发周期长一些。。。

**Comment by Qv2ray-dev** [comment]
Partially resolved this issue.
You can now clear data usage by right click the group entry.
