### ISSUE TITLE
使用路由设置中的预置规则时会报错

### ISSUE THREAD

**Issue by MGPlastic** [Qv2ray/Qv2ray#498]
**简单描述这个 bug：**
启用了预置规则之后启动就会报错

**相关截图或日志**
![Screenshot_20200406_174927](https://user-images.githubusercontent.com/20658780/78545819-028fdc80-782f-11ea-95fe-e6836f79d1f5.png)

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - ArchLinux
 - 是从release下载的还是自己编译的
    - release
 - 首选项里的版本号：
    - 2.4.1

**Comment by MGPlastic** [comment]
删掉geosite:speedtest之后就可以用了

**Comment by DuckSoft** [comment]
你可能没有使用最新的 v2ray-domain-list（geoip.dat 和 geosite.dat），导致了规则无法找到的问题。
v2rayN 内置的规则仅供参考，若有出错，删除即可，无需介意。
