### ISSUE TITLE
透明代理这个功能是怎么使用的？

### ISSUE THREAD

**Issue by yeyir** [Qv2ray/Qv2ray#502]

**Comment by DuckSoft** [comment]
你好，这个功能是 Qv2ray 1.0 时代的遗物，由于原作者已经销声匿迹，~我们其实也不知道怎么用~。
无视就可以了。

PS：本功能重写计划中

**Comment by yechs** [comment]
@yeyir 可以读一下 [透明代理(REDIRECT) · V2Ray 配置指南|V2Ray 白话文教程](https://toutyrater.github.io/app/transparent_proxy.html)

qv2ray（似乎）只是提供了v2ray中的配置；还要自己配置客户端的 iptables 实现
