### ISSUE TITLE
建议：allowInsecure默认true或可在首选项中配置

### ISSUE THREAD

**Issue by torgitor** [Qv2ray/Qv2ray#506]
目前导入配置后allowInsecure默认值为false，订阅更新后需手工更改。其它如v2rayNG、BifrostV、v2rayN的默认值均为true，添加自建服务比较方便。
建议导入订阅或配置时allowInsecure默认为true，或允许在首选项中配置allowInsecure的默认值。

**Comment by DuckSoft** [comment]
为用户安全考虑，我们会坚持默认不允许 insecure。
有计划在导入/更新订阅时配置 allowInsecure 选项，但可能不会将此项加入首选项中。
或者我们考虑开一个分立的设置页面，起名为“危险操作”。

我们正在憋一个新版本。敬请期待。

**Comment by torgitor** [comment]
是我考虑不周，导入/更新订阅时指定，并明确告知为“危险操作”更合适。

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/79123543-fd9dd080-7dcc-11ea-9279-d0be9a3e68f3.png)
开发版本中已修复。请期待本周末即将放出的新版更新。

**Comment by hitzhangjie** [comment]
现在是不是不能设置了啊？当前使用版本是2.7.0:7000，发现订阅链接导入的默认没有allowInsecure=true这个选项，

看到这个公告：https://qv2ray.net/manual/general.html#advanced-behavior:~:text=Set%20AllowInsecure%20by%20Default%3A%20All%20new%20connections%20imported%20via%20subscription%20/%20QR%20code%20/%20VMess%20protocol%20link%20will%20be%20enabled%20by%20default%20to%20allow%20insecure%20certificates.，这里好像是说是默认打开的呀。

现在只能手动编辑json来解决。
