### ISSUE TITLE
Windows 代理设置问题

### ISSUE THREAD

**Issue by AIrSkycc** [Qv2ray/Qv2ray#507]
**简单描述这个 bug：**
目前Windows开启代理后会自动设置代理地址http://localhost

但部分程序无法识别, 如Uplay, Rockstar

手动将代理地址修改为http://127.0.0.1后, 程序可以正常识别.

还有请问"请勿将代理服务器用于本地地址"选项是否有必要自动勾选?

**如何复现这个bug：**
1. 托盘 系统代理 -> 启用系统代理

**Qv2ray 本应该是怎样工作的？**
自动设置代理地址 http://localhost

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 
是

**相关截图或日志**
![1](https://user-images.githubusercontent.com/8086189/79033382-6e33ca00-7be0-11ea-9db5-1907ba7073cc.png)

```
日志：

```
无需日志

**系统信息**
 - 系统类型（windows, linux, macos）
    - Windows
 - 是从release下载的还是自己编译的
    -  Release
 - 首选项里的版本号：
    - 2.4.1

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

- 建议将代理地址修改为 http://127.0.0.1

**Comment by DuckSoft** [comment]
ACK. cc @Qv2ray-dev

**Comment by DuckSoft** [comment]
问题已定位：

https://github.com/Qv2ray/Qv2ray/blob/f7b1a1fdb5387b61d2679fa9914bb639863ca9ed/src/components/proxy/QvProxyConfigurator.cpp#L171-L180

**Comment by DuckSoft** [comment]
https://github.com/Qv2ray/Qv2ray/blob/f28ae1e9e6eda8ee0e991d043803aaa2a1a06975/src/ui/w_MainWindow_extra.cpp#L44-L51

**Comment by DuckSoft** [comment]
@Qv2ray-dev 我们可能需要在这 hack 一下，因为监听地址有可能是
* `0.0.0.0`
* `127.0.0.1`
* `::1`
* `::`
* 以及任何本机 IP

我们可能需要对 IPv4/IPv6 入站地址进行区别对待。

**Comment by Qv2ray-dev** [comment]
这个地方的 localhost 不是监听地址吧
https://github.com/Qv2ray/Qv2ray/issues/507#L50

**Comment by Qv2ray-dev** [comment]
`请勿将代理服务器用于本地地址` 由于 V2ray 已经处理了 LAN IP，所以不需要特殊处理

**Comment by DuckSoft** [comment]
Windows 下有一些奇怪的软件就会出现写 localhost 连不上的问题。
可能得写 127.0.0.1 或者 ::1 了。

**Comment by Qv2ray-dev** [comment]
对于 localhost 问题， @AIrSkycc 请检查 hosts 文件

**Comment by DuckSoft** [comment]
> 对于 localhost 问题， @AIrSkycc 请检查 hosts 文件

我记得新版 Windows HOSTS 里有这样一句话：
# localhost name resolution is handled within DNS itself.

**Comment by Qv2ray-dev** [comment]
但是这不应影响 localhost 的解析

**Comment by DuckSoft** [comment]
那大概是Ubi之类的软件偷懒了。提前解析成 127.0.0.1 / ::1 也无妨吧。

**Comment by DuckSoft** [comment]
问题已在开发分支中修复。请期待本周的新版本更新。
