### ISSUE TITLE
更新订阅返回空白列表一例

### ISSUE THREAD

**Issue by Solar-Lancelo** [Qv2ray/Qv2ray#509]
**简单描述这个 bug：**
之前用2020.2.14号的版本，订阅链接可以正常更新vmess节点，最近重装了系统，用最新版本的Qv2ray更新订阅链接，结果显示空白。
手动导入的vmess分享节点可以正常使用.

**如何复现这个bug：**
1. 
2. 
3. 
4. 

**Qv2ray 本应该是怎样工作的？**

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - ubuntu 18 LTS
 - 是从release下载的还是自己编译的
    - release下载
 - 首选项里的版本号：
    - Version: 2.4.1

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by DuckSoft** [comment]
大概率是 DNS 污染等原因导致上游面板无法正常访问。
请先尝试使用 curl 等手段对上游面板的可达性做一初步检测。

例如，您的订阅地址为 https://a.com/sub?me=3，您可使用下面的命令测试：

```shell
curl -L 'https://a.com/sub?me=3'
```

注意使用英文单引号包裹。

**Comment by DuckSoft** [comment]
另外，对于这种使用上的问题，建议您加入我们的 Telegram 群进行讨论。

群组链接：https://t.me/qv2ray

**Comment by Solar-Lancelo** [comment]
在windows 中使用v2rayN 订阅正常，使用curl 可以的到返回值

**Comment by DuckSoft** [comment]
请问您的 curl 是在原 Ubuntu 环境中执行的吗？

**Comment by Solar-Lancelo** [comment]
elementary OS 
 build on ubuntu

**Comment by DuckSoft** [comment]
若您能访问 Telegram，建议加入我们的 Telegram 群组与我们直接对话。
GitHub Issue 不是个聊天的好地方。

https://t.me/qv2ray

**Comment by Solar-Lancelo** [comment]
等会下载

**Comment by DuckSoft** [comment]
问题已经查明了。上游面板返回的数据会根据 User-Agent 的不同而变化。
当 User-Agent 是 `Mozilla/5.0 (rv:71.0) Gecko/20100101 Firefox/71.0` 时，上游返回数据解码后类似于：

```
vmess://YXV0...vbTo0NDM=?remarks=%E5%9C...%B6&obfsParam=&path=/ray&obfs=websocket&tls=1&peer=&cert=
```

当 User-Agent 是其他时（如 `v2rayN` `Qv2ray` 等），返回结果正常：
```
vmess://eyJhZ...uZSJ9
```

**Comment by DuckSoft** [comment]
@Qv2ray-dev 
https://github.com/Qv2ray/Qv2ray/blob/0d709d49888fffd762228193b7f802209eb75a72/src/core/connection/Serialization_vmess.cpp#L82-L83

之后，这种取巧的做法就会栽在第一种格式的 vmess 链接里，导致解析失败。

**Comment by DuckSoft** [comment]
正在准备修复……

**Comment by DuckSoft** [comment]
魔幻的事情发生了：前段解码后返回的数据不是一个 JSON，而是：
```
auto:00ba0916-85cb-4237-8fe2-7284cd35892f@nimasile.shabi.caonima.com:443
```
（相关敏感信息已经隐去）

怀疑这个根本不是标准的 Vmess 格式订阅。

**Comment by DuckSoft** [comment]
由于贵机场上游面板过于坑爹，我决定……
![图片](https://user-images.githubusercontent.com/7822648/79054684-78ee6d80-7c79-11ea-86df-fb2d2b28b07a.png)

单独给你定制一个版本。

**Comment by violetu** [comment]
啊这

> 由于贵机场上游面板过于坑爹……
> 我决定……
> 
> ![图片](https://user-images.githubusercontent.com/7822648/79054684-78ee6d80-7c79-11ea-86df-fb2d2b28b07a.png)
> 
> 单独给你定制一个版本。
> 
> 构建已启动，不久就会完成。
> 你可以直接从 https://github.com/Qv2ray/Qv2ray/actions/runs/76121743 的 Artifact 中下载。

啊这，老哥真好。
