### ISSUE TITLE
建议添加关闭sniffing功能选项（流量探测）

### ISSUE THREAD

**Issue by invoker-kael** [Qv2ray/Qv2ray#510]
**简单描述这个 bug：**

这个问题出现在使用TOR的情况下，由于sniffing默认开启，导致无法链接，修改配置文件后会被程序刷掉
好像确实没有关的地方？我没找到……目前只能手工使用v2ray-core解决

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

v2rayN中可以关闭sniffing（流量探测功能）

**Comment by DuckSoft** [comment]
很奇怪，我这边用 Tor，使用 SOCKS5 代理，没有这样的问题。
不过添加这个 sniffing 的切换选项，是可以接受的。

感谢反馈。

**Comment by Qv2ray-dev** [comment]
@invoker-kael 请问你使用的是复杂配置还是简单配置？
![image](https://user-images.githubusercontent.com/59914293/79069553-bbf42380-7d01-11ea-9584-2e2f426a8317.png)

**Comment by DuckSoft** [comment]
这边看 V2Ray Core 上游的代码，默认这个功能是打开的，是我们这边欠考虑了。
将会在全局选项中补上。敬请期待。

https://github.com/v2ray/v2ray-core/blob/6276bfa508b64d9491c98e6201476d6cb3ce36a8/app/proxyman/config.go#L17-L39

**Comment by invoker-kael** [comment]
> @invoker-kael 请问你使用的是复杂配置还是简单配置？
> ![image](https://user-images.githubusercontent.com/59914293/79069553-bbf42380-7d01-11ea-9584-2e2f426a8317.png)

我是直接找到了这个文件进行修改……然后重新连接会被刷新……是还有其他的操作方式吗？复杂配置好像没找到修改这一项功能的地方

**Comment by DuckSoft** [comment]
在 Qv2ray 中右键这个节点，选择作为 JSON 编辑，在这里修改并保存。

**Comment by DuckSoft** [comment]
着手修复中……

**Comment by invoker-kael** [comment]
复杂配置写入后，虽然设置了端口，但右上角显示0
如果是从全局导入则没有问题，可以显示端口
Emmm，不清楚是真的没有还是显示bug
另，配置json加入sniffing设置还是无效，不知道是不是被全局设置覆盖了

![2020-04-12 21-45-44屏幕截图](https://user-images.githubusercontent.com/63380399/79070251-1e035780-7d07-11ea-8053-29cfbdc8e6e0.png)

**Comment by okudayukiko** [comment]
看LIVE（如Facebook Live、TV LIVE）一定要关闭Sniffing，否则会视频卡顿。

**Comment by Qv2ray-dev** [comment]
https://github.com/Qv2ray/Qv2ray/blob/dev/src/core/connection/Generation.cpp#L311

fixed in the dev branch. closing.

**Comment by mycodesuck** [comment]
关闭sniffing,且使用socks代理后还是无法连上的，你大概率需要更换新的bridge。
tor browser本身提供了bridgeDB的功能选项。
我这里是通过以上方式连上的。
socks代理和bridgeDB的功能可以同时使用
