### ISSUE TITLE
他 又 改 回 去 了

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#511]
他改变了 v2ray：https://github.com/v2ray/domain-list-community/issues/285
他又改回去了：https://github.com/v2ray/domain-list-community/pull/333

**Comment by DuckSoft** [comment]
不过鉴于只是补上了 Speedtest 本家的域名，并未实现各种 Speedtest 节点的匹配，暂不考虑加回去。
此帖留念。

**Comment by Qv2ray-dev** [comment]
Priority: P(-1)
Reason: Wait and see if they will change another time.
