### ISSUE TITLE
Windows 关于设置 SOCKS 系统代理的疑问

### ISSUE THREAD

**Issue by okudayukiko** [Qv2ray/Qv2ray#512]
**简单描述这个 bug：**
~~1、建议添加 关闭sniffing选项，看视频（尤其是直播）必须关闭sniffing。~~
2、在“首选项”关闭HTTP代理后，自动设置IE代理的功能会出错。SOCKS代理比HTTP代理性能好。

**如何复现这个bug：**
1. 
2. 
3. 
4. 

**Qv2ray 本应该是怎样工作的？**

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**
![屏幕截图(107)](https://user-images.githubusercontent.com/17502357/79113038-8f4c1480-7db2-11ea-9093-8866dde68ad0.png)
![屏幕截图(106)](https://user-images.githubusercontent.com/17502357/79113101-b4408780-7db2-11ea-862f-4e1b3d2fb56f.png)
![屏幕截图(108)](https://user-images.githubusercontent.com/17502357/79113327-3fba1880-7db3-11ea-9188-6d88d1cbdb49.png)

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - Windows 10
 - 是从release下载的还是自己编译的
    - 最新版
 - 首选项里的版本号：
    - 

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by DuckSoft** [comment]
Sniffing see: #510

**Comment by DuckSoft** [comment]
我复述一下你的问题，是“关闭HTTP入站、开启SOCKS5入站”之后设置系统代理出错吗？

**Comment by okudayukiko** [comment]
> 我复述一下你的问题，是“关闭HTTP入站、开启SOCKS5入站”之后设置系统代理出错吗？

对

**Comment by DuckSoft** [comment]
> > 我复述一下你的问题，是“关闭HTTP入站、开启SOCKS5入站”之后设置系统代理出错吗？
> 
> 对

@Qv2ray-dev 请确认此情形。我没有可用于复现的 Windows 环境。

**Comment by DuckSoft** [comment]
另外我插一句，Windows 的那个系统代理 SOCKS 用的是 SOCKS4，会漏 DNS 查询流量，所以我记得我们默认设置系统代理的时候是设置的 HTTP 代理，以避免泄漏用户隐私。如果你的确有相关需求，你可以在浏览器中进行直接设置，或者使用第三方代理切换插件等。

**Comment by DuckSoft** [comment]
另外我插一句，Windows 的那个系统代理 SOCKS 用的是 SOCKS4，会漏 DNS 查询流量，所以我记得我们默认设置系统代理的时候是设置的 HTTP 代理，以避免泄漏用户隐私。如果你的确有相关需求，你可以在浏览器中进行直接设置，或者使用第三方代理切换插件等。

@Qv2ray-dev 表示他最近有点事情，不能帮助我们复现这个问题。下面转给我来处理。

**Comment by DuckSoft** [comment]
问题已经确认。锁定一行可疑代码：
https://github.com/Qv2ray/Qv2ray/blob/cca5a56643aeb6beeb1adafc0b884e8a0f214fa1/src/components/proxy/QvProxyConfigurator.cpp#L215

@Qv2ray-dev 接锅

**Comment by DuckSoft** [comment]
> > 我复述一下你的问题，是“关闭HTTP入站、开启SOCKS5入站”之后设置系统代理出错吗？
> 
> 对

由于负责这部分开发的鸽子在吃食，我没有 Windows 环境，无法复现此问题。
请问是设置代理时提示失败，还是说代理设置的有问题，导致无法连接呢？

能否将具体现象予以告知？例如，弹出的窗口的截图等。

**Comment by okudayukiko** [comment]
> > > 我复述一下你的问题，是“关闭HTTP入站、开启SOCKS5入站”之后设置系统代理出错吗？
> > 
> > 
> > 对
> 
> 由于负责这部分开发的鸽子在吃食，我没有 Windows 环境，无法复现此问题。
> 请问是设置代理时提示失败，还是说代理设置的有问题，导致无法连接呢？
> 
> 能否将具体现象予以告知？例如，弹出的窗口的截图等。

代理设置有Bug。另外还是用虚拟机跑Windows 10吧。

**Comment by DuckSoft** [comment]
有 Bug 归有 Bug，具体表现是啥，能麻烦您告知一下吗？
我这电脑低压 i5，带不动虚拟机。

**Comment by okudayukiko** [comment]
> 有 Bug 归有 Bug，具体表现是啥，能麻烦您告知一下吗？
> 我这电脑低压 i5，带不动虚拟机。

For Windows软件还是要用Windows开发。
根据我的经验，如果觉得正版Windows 10 Home（100 USD）贵，可以用正版Windows 8.1或正版Windows 7。
低压i5加大内存可以跑Linux虚拟机。

**Comment by DuckSoft** [comment]
~~老哥，我这电脑底配 XPS13 9360，内存焊死的不能升级。~~

我们还是说正事吧：这个 bug 具体怎么表现的？
举个例子（以下均为杜撰）：
1. 右键点击托盘图标，点击设置系统代理
2. 弹出一个对话框：系统代理设置失败：xxxxxx

**Comment by okudayukiko** [comment]
> ~老哥，我这电脑底配 XPS13 9360，内存焊死的不能升级。~
> 
> 我们还是说正事吧：这个 bug 具体怎么表现的？
> 举个例子（以下均为杜撰）：
> 
> 1. 右键点击托盘图标，点击设置系统代理
> 2. 弹出一个对话框：系统代理设置失败：xxxxxx

或者用一台二手桌面电脑。Windows下更改代理设置是通过更改注册表实现，如图是将系统代理设置设为HTTP+SOCKS两种协议。

**Comment by DuckSoft** [comment]
老哥，我投降了。这个 bug 我处理不了。
您看看能不能帮我们修复一下，先行谢过了。

**Comment by MarksonHon** [comment]
Microsoft Windows 系统只能使用 HTTP 代理，你把 HTTP 代理关了，又想要设置系统代理，可能么？！

**Comment by okudayukiko** [comment]
> Microsoft Windows 系统只能使用 HTTP 代理，你把 HTTP 代理关了，又想要设置系统代理，可能么？！

Windows 代理设置（inetcpl.cpl）可以用SOCKS代理，见图。

**Comment by Qv2ray-dev** [comment]
@okudayukiko 你试试这个：　https://github.com/Qv2ray/Qv2ray/actions/runs/77107186

**Comment by Qv2ray-dev** [comment]
@okudayukiko 你好，我们需要能复现问题的详细步骤，包括应出现的情况和出现的问题

**Comment by DuckSoft** [comment]
Qv2ray 放弃修复本 Issue。锁了。
