### ISSUE TITLE
mac版本字体模糊，求修复。

### ISSUE THREAD

**Issue by Think-Me** [Qv2ray/Qv2ray#513]
**简单描述这个 bug：**
mac版本字体模糊

**相关截图或日志**
<img width="860" alt="image" src="https://user-images.githubusercontent.com/28859254/79121684-6fbfe680-7dc8-11ea-8d2e-9b0c2a79a5e0.png">

**系统信息**
 - 系统类型（windows, linux, macos）
    - macOS
 - 是从release下载的还是自己编译的
    - 直接下载的dmg包
 - 首选项里的版本号：
    - 2.4.1版本

**Comment by Qv2ray-dev** [comment]
您好，此问题已经在开发版本中修复
您可以等待一个新版本发布，或者在 Action （例如此处： https://github.com/Qv2ray/Qv2ray/actions/runs/77107186 ）下载一个开发版本使用

注意：开发版本部分功能暂不稳定
