### ISSUE TITLE
建议加入导入插件功能

### ISSUE THREAD

**Issue by DuckVador** [Qv2ray/Qv2ray#514]
**简单描述这个 bug：**
插件初次使用时如果不看源码，完全不知道插件应该放在哪里。

**Qv2ray 本应该是怎样工作的？**
导入插件功能应该是用户选择一个已下载的插件后，Qv2ray复制该插件到Qv2ray config文件夹下的plugins目录。

**Comment by Qv2ray-dev** [comment]
Acknowledged
