### ISSUE TITLE
how to config obfs for shadowsocks

### ISSUE THREAD

**Issue by RichardFido** [Qv2ray/Qv2ray#516]
**Briefly describe this bug：**
i used justmysocks, and i have a config like this: some.net | obfs=tls, aes-256-gcm, no udp.
it should use plugin like simple-obfs, but i don't know how to use this plugin with qv2ray.
i use json like this:
~~~
"plugin":"simple-obfs"
"plugin_opts“:"obfs=tls"
~~~
but it doesn't work.

**What is expected to happen**

**Screenshots**
If appropriate, please attach some screenshots.

**System Information**

 - OS Type: (Windows, Linux or macOS) `ubuntu18.04`
 - Built from the source or download from the release? `software center`
 - Version string in the Preferences Window `2.4.1`

**Other Info**

You may want to write anything if you think it helps us to fix the bug.

*Please hide your server address and UUID if you wish to post the vmess string or your connection setting.*

**Comment by DuckSoft** [comment]
we do not currently support that. take a look here:
https://github.com/v2ray/v2ray-core/issues/485

**Comment by DuckSoft** [comment]
It would be a pleasure if you have an interest to kindly help us implement this feature.
Currently we focus ourselves on improvements of V2Ray protocols. 
For Shadowsocks protocols the support is limited. Please understand.

**Comment by RichardFido** [comment]
ok. thx.
