### ISSUE TITLE
Customizing system proxy configuration (QvProxyConfigurator)

### ISSUE THREAD

**Issue by ghost** [Qv2ray/Qv2ray#518]
Please consider making the "set system proxy" function configurable by the end user. It would be nice if I can tell qv2ray to only configure the socks proxy parameter with the system and leave everything else blank.

The rationale behind this is that Firefox prefers the http proxy if there are multiple types of proxies configured in the system, and there is no way to change this priority in Firefox. This essentially breaks DoH in Firefox since it only works over socks.

I know this can be easily resolved by simply configuring firefox to use only socksv5, but I'd prefer to leave the proxy config in firefox as "use system proxy" so I don't have to change it back and forth depending on whether qv2ray is running or not.

OS: Linux
Desktop Environment: KDE

**Comment by Qv2ray-dev** [comment]
Currently, you can temporarily disable HTTP inbound. 
We will add such a setting in a future version, it's probably after `v2.5.0-pre1` but definitely before `v2.5.0` final release.

**Comment by kvywo** [comment]
Thanks. I've got some new findings here. Assuming only the "SOCKS Proxy" field in KDE System Settings is set and the port number was correct:

1. Firefox doesn't seem to like the `socks://127.0.0.1` URL configured by qv2ray and will report "Unable to find the proxy server". Changing it to `127.0.0.1` has no effect whateoever.

2. Changing the URL to `localhost` will make Firefox treat the option as a HTTP proxy for some reason (???), indicated by the flood of `unknown Socks version: XX` printed by v2ray-core.

I'm completely out of ideas now, this means we can't make ff use socksv5 by only setting the "SOCKS Proxy" field. 

Firefox version: 75.0

**Comment by Qv2ray-dev** [comment]
Yes indeed, in the Firefox PreferenceWindow, Proxy settings page.
![image](https://user-images.githubusercontent.com/59914293/79408097-14ab1100-7fcd-11ea-9edb-6e0704ce0893.png)

You cannot set SOCKS proxy standalone, where HTTP proxy string is a mandatory option.

I'm not sure SwitchyOmega handles this.

BTW firefox has its own DoH option:
![image](https://user-images.githubusercontent.com/59914293/79408349-adda2780-7fcd-11ea-8182-adc67b7ba759.png)
I believe it's reading SystemProxy's SOCKS settings.

**Comment by kvywo** [comment]
I was referring to KDE's **system settings menu** while testing those URLs, Firefox was always configured to "use system proxy" during those tests. Apparently it's both Firefox and KDE's fault, there isn't much we can do about it unfortunately. I guess I'll just have to use a plugin to make my life easier, sigh.

By the way, the HTTP proxy field is not mandatory in Firefox, you can use socksv5 only and it'll still work just fine :)

**Comment by DuckSoft** [comment]
It seems that we need a completely rewrite of system proxy configuration module.
@Qv2ray-dev what do you guys think

**Comment by Qv2ray-dev** [comment]
@DuckSoft I think it's cool and necessary, but takes time.

**Comment by DuckSoft** [comment]
System Proxy Subsystem Rework Scheduled.

**Comment by Qv2ray-dev** [comment]
See #551

**Comment by DuckSoft** [comment]
Merged into Tracker #551
