### ISSUE TITLE
Lingering v2ray core process after logout

### ISSUE THREAD

**Issue by kvywo** [Qv2ray/Qv2ray#519]
If I log out and log back in again, qv2ray will not be able to start a new v2ray process until I do `killall v2ray`. The old v2ray process is still lingering around for some reason. I suggest adding a feature to kill existing v2ray processes started by qv2ray on startup to get around this problem. 

Maybe we can filter the binary path of the processes to avoid interfering with users' other potential v2ray instances.

OS: Linux
qv2ray version: v2.4.1
Desktop Environment: KDE

Edit: "Launch at Login" is enabled.

**Comment by Qv2ray-dev** [comment]
How about trying this: https://github.com/Qv2ray/Qv2ray/actions/runs/77684196

**Comment by kvywo** [comment]
Nope. I made sure to kill the v2ray process and restart it from qv2ray before logging out, but qv2ray will still fail to start after logging back in.

**Comment by Qv2ray-dev** [comment]
Can the `stop` button in Mainwindow correctly terminate v2ray process in normal circumstance?

If so, please try `nohup /path/to/qv2ray > ~/qv2ray.log &`, start a connection, then logout and login back to check what's the last 10 lines of the `qv2ray.log`.

**Comment by kvywo** [comment]
Here you go:

```
[CORE-UI]: Preparing to set system proxy
[COMPONENT-PROXY]: Setting up system proxy.
[CORE-UI]: Setting system proxy for simple config.
[COMPONENT-PROXY]: Setting up System Proxy
[COMPONENT-PROXY]: Qv2ray will set system proxy to use HTTP
[COMPONENT-PROXY]: Qv2ray will set system proxy to use SOCKS
[COMPONENT-PROXY]: KDE detected
[CORE-UI]: OnConnected signal received for: xxxxxxxxxxxx
[CORE-UI]: Setting current item.
[COMMON-NETWORK]: Start checking update for channel ID: 0
[COMMON-NETWORK]: Network request error string: HostNotFoundError
[COMMON-NETWORK]: Stop the test on the first long connect()
The X11 connection broke (error 1). Did the X11 server die?
```

**Comment by Qv2ray-dev** [comment]
It'll be a QtX11 or QWayland's fault.

When a `SIGTERM`, `SIGINT` or even `SIGKILL` arrived. There'll be a log says: 

```
Qv2ray: Interrupt signal ( SIGNAL_CODE ) received.
```
But it doesn't exist here. I guess Qv2ray haven't been notified about the ongoing session termination, since cannot call `StopConnection` to terminate v2ray core process.

Please search about the `The X11 connection broke (error 1). Did the X11 server die?` error string since it's not from Qv2ray itself.

**Comment by kvywo** [comment]
Tried googling this but didn't find anything useful. I'll report back if I ever figure it out in the future, closing for now.
