### ISSUE TITLE
Feature: Ctrl + Q for quitting qv2ray

### ISSUE THREAD

**Issue by ghost** [Qv2ray/Qv2ray#520]
Sometimes the context menu will refuse to appear when I right-click on the icon in the system tray, so I have to restart qv2ray by doing a `killall`. Please consider implementing Ctrl + Q for quitting qv2ray.

(I assume this is a wayland related problem but I'm not 100% sure, which is why I didn't report this as a UI bug)

**Comment by Qv2ray-dev** [comment]
Fixed, closing.
