### ISSUE TITLE
新版使用pac，连不上外网

### ISSUE THREAD

**Issue by zleiwang** [Qv2ray/Qv2ray#521]
# 简单描述这个 bug:
用sock和http代理可以连外网，但内网速度会很慢。切换成pac模式，退出软件再连，直接连不上外网。上上个版本没这个问题，感觉那个界面也比较合理，测试按钮很容易找出，现在搞的几个板块有点乱

# 如何复现这个bug：

1. 
2. 
3. 
4. 

### 相关截图或日志

<details>

```
Qv2ray 日志
```

</details>

### 受影响的 Qv2ray 安装平台

- [x] Linux
- [ ] macOS
- [ ] Windows

### 受影响的 Qv2ray 安装源

- [ ] ArchLinuxCN
- [ ] Homebrew Cask
- [ ] Scoop
- [ ] 手动编译
- [x] Github Release

### 首选项 -> 关于信息：

```
版本号: 
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by Qv2ray-dev** [comment]
你好，请不要使用pac
这个功能已经过时，V2ray自带分流功能

**Comment by zleiwang** [comment]
> 你好，请不要使用pac
> 这个功能已经过时，V2ray自带分流功能

自带的，访问国内有些网站会很慢。就那个百度首页新冠肺炎的数据页，都要等10多秒，感觉用pac时没啥延迟吧

**Comment by zleiwang** [comment]
Ubuntu 18系统。是v2.1.2.3861  这个版本直接用pac连没问题。相应的内核不能用最新的，不然会错误

**Comment by Qv2ray-dev** [comment]
慢的原因在于将dns请求从代理发送，以防止污染和隐私泄漏。
如果你的梯子延迟比较大，这种roundtrip可能会非常明显。

分流规则中不可能包括所有中国站点的域名，因此v2ray在拿不准的时候都会走一次解析。

若你确实有需要，你可以在高级路由设置中设置分流策略为 AsIs 以强迫 v2ray 不要对未知的域名使用ip再分流。
gfwlist等pac方案也是一丘之貉。

Forwarded from @DuckSoft

**Comment by DuckSoft** [comment]
慢的原因在于将dns请求从代理发送，以防止污染和隐私泄漏。如果你的梯子延迟比较大，这种roundtrip可能会非常明显。分流规则中不可能包括所有中国站点的域名，因此v2ray在拿不准的时候都会走一次解析。若你确实有需要。你可以在高级路由设置中设置分流策略为 AsIs 以强迫 v2ray 不要对未知的域名使用ip再分流。值得一提的是，gfwlist等pac方案也是一丘之貉。所以如果你想提前分流，建议使用switchyomega等插件提前在浏览器端完成分流操作，减小解析损失。

**Comment by DuckSoft** [comment]
对国内外分流有强需求的，建议使用switchyomega等浏览器插件规则完成。

**Comment by zleiwang** [comment]
好的，谢谢你们
