### ISSUE TITLE
Inbound中”设置系统代理” 无法 影响更新订阅时“使用系统代理更新“

### ISSUE THREAD

**Issue by godspeed1989** [Qv2ray/Qv2ray#524]
# 简单描述这个 bug:
我的订阅地址**必须**使用代理才能正常更新。
但是我发现，即使在Inbound设置中选择了”设置系统代理”，更新订阅时，选择“使用系统代理更新“也没有效果。

我看了下代码，”设置系统代理”的相关代码应该是`SetSystemProxy()`这个函数（Xfce桌面，非KDE）
https://github.com/Qv2ray/Qv2ray/blob/0761cab8a9005672a7a18484a2edcac856ec4cd7/src/components/proxy/QvProxyConfigurator.cpp#L244
通过终端中输入
`gsettings get org.gnome.system.proxy.socks host或port`
显示设置正常。

订阅更新时，使用了这个函数进行更新
https://github.com/Qv2ray/Qv2ray/blob/0761cab8a9005672a7a18484a2edcac856ec4cd7/src/common/HTTPRequestHelper.cpp#L39
在这个函数中，使用`QNetworkProxyFactory::systemProxyForQuery()`获得系统代理相关信息。
通过调试，我发现该Qt函数没有返回设置好的系统代理。
原因是，根据该函数文档，Linux系统中Qt是通过http_proxy环境变量获取的系统代理，而不是gsettings里面的东西。我没有KDE环境，但我认为同样会有影响。
![image](https://user-images.githubusercontent.com/2350713/79642494-6079d800-81d0-11ea-95a1-711bef40e571.png)

### 解决方法的建议
方法1：`syncget()`不使用`QNetworkProxyFactory::systemProxyForQuery()`，使用其它方法订阅时获取系统代理。但是这个函数应该在非Linux系统里工作正常？
方法2：Inbound设置中如果选择了”设置系统代理”，`SetSystemProxy()`函数设置http_proxy环境变量，保证`QNetworkProxyFactory::systemProxyForQuery()`正常运行。

### 受影响的 Qv2ray 安装平台
- [x] Linux

### 受影响的 Qv2ray 安装源
- [x] ArchLinuxCN

### 首选项 -> 关于信息：
```
版本号: 2.5.0-pre1
```

**Comment by DuckSoft** [comment]
2.5.0-pre1 已修复。
![图片](https://user-images.githubusercontent.com/7822648/79642852-6e305d00-81d2-11ea-8b4b-8dac44852378.png)

**Comment by DuckSoft** [comment]
carbon copy @Qv2ray-dev

**Comment by godspeed1989** [comment]
谢谢，测试可用。
希望界面、文档和用户体验可以更加完善。

**Comment by DuckSoft** [comment]
@godspeed1989 奈何人手不足，核心开发人员仅3人。若有意加入，非常欢迎～

**Comment by DuckSoft** [comment]
Marked as fixed. Closing.
