### ISSUE TITLE
代理局域网里面其他设备（比如PS4）全局接收VPN流量

### ISSUE THREAD

**Issue by NicholasIrving** [Qv2ray/Qv2ray#529]
我试过用squid做代理服务器，代理局域网里面其他设备（比如PS4）接收VPN流量

问题复现：
1. 监听设为0.0.0.0，HTTP代理端口为8888，sqiud端口为3128
2. PS4 代理IP为电脑的网卡IP，端口为8888，能上Google，可是游戏里面依然使用大陆IP
3. PS4 代理IP为电脑的网卡IP，端口为3128，不能上Google，游戏里面使用大陆IP

我的系统是Ubuntu 18.04， 如果想要PS4里面的游戏也接收VPN流量，应该怎么做？

**Comment by DuckSoft** [comment]
您好，使用问题请加群讨论。Issue 区主要用于反馈 bug 和提建议。

https://t.me/qv2ray
