### ISSUE TITLE
no response from Open Local Plugin Folder 

### ISSUE THREAD

**Issue by libation** [Qv2ray/Qv2ray#530]
after clicking the **Open Local Plugin Folder** in the **Plugin Manager**, there's no response or pop up window to add plugin, what is the path supposed to be? maybe I could add it manually
 - OS Type
     macOS
 - Built from the source or download from the release?
     release, v2.5.0-pre1

thanks

**Comment by Qv2ray-dev** [comment]
Thanks for reporting this issue.

It's been fixed in the latest `dev` branch.

**Comment by libation** [comment]
> Thanks for reporting this issue.
> 
> It's been fixed in the latest `dev` branch.

thanks for your quick response, guess I'll try that first

**Comment by Qv2ray-dev** [comment]
There'll be a v2.5.0-pre2 releasing recently.
Feel free to report anything that goes wrong in the future.

Thanks.
