### ISSUE TITLE
Debian setcap 路径/权限问题

### ISSUE THREAD

**Issue by Wings-Fantasy** [Qv2ray/Qv2ray#531]
首选项里透明代理支持功能不可用

### 相关截图或日志

<details>
[CORE-UI]: Calling pkexec and setcap...<br>
Cannot run program setcap: No such file or directory<br>
[CORE-UI]: WARN: setcap exits with code: 127<br>
<img src="https://s1.ax1x.com/2020/04/22/JNYzHH.png"/>
</details>

### 受影响的 Qv2ray 安装源

Github Release

### 首选项 -> 关于信息：

```
版本号: 2.4.1
编译信息：Qv2ray from manual build
其它编译信息：Qv2ray 2.4.1:5150
```

**其他信息**

我认为是没有找到setcap命令。我在/usr/bin下也没有找到setcap命令，但是在/usr/sbin下找到了setcap命令，或许软件需要执行sudo setcap而不是直接执行setcap

**Comment by hosiet** [comment]
Deb 系发行版的普通用户默认将 sbin 排除在 PATH 之外。Qv2ray 可以考虑同时搜索固定路径 /usr/sbin 寻找 setcap 命令。

另外打包时应当将提供 setcap 命令的软件包列为可选依赖（Deb 系为 libcap2-bin）。

**Comment by Wings-Fantasy** [comment]
我认为不太需要添加可选依赖，libcap2-bin软件包应该默认安装在了deb系的系统上了。

软件提示我需要手动执行setcap，具体需要执行什么命令却没有说明。我需要一个临时的解决方案，手动执行一下这个命令

**Comment by Qv2ray-dev** [comment]
https://github.com/Qv2ray/Qv2ray/blob/master/src/ui/w_PreferencesWindow.cpp#L558
其中 kernelPath 是你的 V2ray core 可执行路径

**Comment by Qv2ray-dev** [comment]
fixed in `master` branch,.....
