### ISSUE TITLE
On Linux Mint 19 :Tells dependency is not satisfiable:libprotobuf17 

### ISSUE THREAD

**Issue by clssw1004** [Qv2ray/Qv2ray#533]
* Use deb pkg install Qv2ray with pkg download from release page: **qv2ray_2.5.0.pre1-1_amd64.deb**
* System OS: Linux Mint 19.3

**Comment by Qv2ray-dev** [comment]
As far as I can tell, you need to find `protobuf` package somewhere from the package manager, otherwise please use `AppImage`

**Comment by DuckSoft** [comment]
您好，不是所有的 Debian 系发行版都有 libprotobuf17。
若您的发行版无此包，请考虑使用 AppImage，~~或者从其他发行版移植一个~~。
