### ISSUE TITLE
一连v2ray 内核就崩

### ISSUE THREAD

**Issue by yunmi323** [Qv2ray/Qv2ray#536]
# 简单描述这个 bug:
The kernel terminated unexpectedly:
V2ray kernel crashed.
To solve the problem, read the kernel log in the log text browser.

### 受影响的 Qv2ray 安装平台

- [ ] Windows

### 受影响的 Qv2ray 安装源

- [ ] Github Release

### 首选项 -> 关于信息：

```
版本号: 2.5.0
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
v2ray 版本号: 4.23.1 winx64

**Comment by Qv2ray-dev** [comment]
@yunmi323 @DuckSoft

**Comment by DuckSoft** [comment]
您好。出现这种情况一般是有其他程序占用了您的 V2Ray 入站端口。
您可：
* 在首选项——入站设置中更换对应端口，防止冲突
* 找出占用端口的程序并结束

---
附：Windows 下查找占用端口的程序：
使用管理员权限运行命令提示符，键入以下命令并回车：
```bat
netstat -aon | findstr 1088
```
注：此处的 1088 为你需要检测的端口号。请根据实际情况自行替换。

您将得到的输出可能会类似于下图：
![图片](https://user-images.githubusercontent.com/7822648/80154277-daa3c580-85f1-11ea-9ee2-0ad57b832b2a.png)

请记住最后一列的数字，例如在上图中为 14936。之后运行下面的命令：
```bat
tasklist | findstr 14936
```
可能的输出如下：
![图片](https://user-images.githubusercontent.com/7822648/80154370-feffa200-85f1-11ea-9fbd-b0c91d11108f.png)

如此，您便发现了占用该端口的应用程序。

**Comment by DuckSoft** [comment]
暂时关闭本 Issue。

若按上述方法仍无法解决，您可加入我们的 Telegram 讨论群组：
    https://t.me/qv2ray
与我们一同讨论。

**Comment by rosewu550** [comment]
我也有相同问题，换端口号也没有用

**Comment by MarksonHon** [comment]
请先看官方文档，这个问题有说明的。

**Comment by kamilmirza** [comment]
was facing this issue after a restart
workaround #2 fixed my issue
