### ISSUE TITLE
Add "Ping All" to Group Context Menu

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#539]
![图片](https://user-images.githubusercontent.com/7822648/80158274-ab458680-85fa-11ea-817d-57ad7ddd88e8.png)

It would be better if we have a "Ping All" here.

**Comment by DuckSoft** [comment]
@Qv2ray-dev will this be implemented?

**Comment by Qv2ray-dev** [comment]
@DuckSoft Yes, before v2.5.0

**Comment by Qv2ray-dev** [comment]
Fixed, closing/

**Comment by DuckSoft** [comment]
@Qv2ray-dev Damn I need to update translation for this. Hold on

**Comment by DuckSoft** [comment]
Done. for good.
