### ISSUE TITLE
无法同时开启两个连接

### ISSUE THREAD

**Issue by uebian** [Qv2ray/Qv2ray#542]
# 简单描述这个 bug:
在开启一个链接的情况下打开第二个链接第一个链接会被关闭，尽管入站端口不冲突

# 如何复现这个bug：

1. 新建两个复杂配置，配置不同的入站端口和出站路由
2. 启动其中的一个配置
3. 启动其中的另一个配置，发现第一个配置断开

### Qv2ray 本应该是怎样工作的？
在端口不冲突的情况下可以开启任意多个链接

### 相关截图或日志

<details>

```
Qv2ray 日志
```

</details>

### 受影响的 Qv2ray 安装平台

- [x] Linux
- [x] macOS
- [x] Windows

### 受影响的 Qv2ray 安装源

- [x] ArchLinuxCN
- [x] Homebrew Cask
- [x] Scoop
- [x] 手动编译
- [x] Github Release

### 首选项 -> 关于信息：

```
版本号: 2.4.1
编译信息：Qv2ray for Arch Linux CN
其它编译信息：(Official Build) 5.5.6-arch1-1 x86_64
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by Qv2ray-dev** [comment]
你好，我们并没有多开链接的计划

**Comment by DuckSoft** [comment]
你好，假设你是 Qv2ray 的开发者，你会如何实现“在端口不冲突的情况下可以开启任意多个链接”这一功能呢？

**Comment by DuckSoft** [comment]
既已使用复杂配置，您可设置两套独立的入站和出站，并单独进行连接。
经测试，完全可以正常使用。

参考配置：
![图片](https://user-images.githubusercontent.com/7822648/80235183-efcd3280-868b-11ea-9314-4ab91afa529c.png)

**Comment by uebian** [comment]
感谢
