### ISSUE TITLE
导入将 path 写在 host 的奇葩 Vmess ws 链接失败

### ISSUE THREAD

**Issue by toaoman** [Qv2ray/Qv2ray#544]
# 简单描述这个 bug:

v2rayN 2.31能成功扫描导入的二维码使用Qv2ray扫描导入失败。
错误列表显示：1:path does not exist

vmess://eyJwcyI6Ilt5b3VuZWVkLndpbl1yYXkuZWFzdC1jdS4xLjkwcG9ybi5zaXRlIiwiYWRkIjoicmF5LmVhc3QtY3UuMS45MHBvcm4uc2l0ZSIsInBvcnQiOiI4MDAyIiwiaWQiOiI5YzE0N2I0NS0zMTcxLTNkMjktOTkyZC0wYTgyMDdmMjg5MDIiLCJhaWQiOiIwIiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsImhvc3QiOiIveWFib3Zpc3MiLCJ0bHMiOiIifQ==

# 如何复现这个bug：

1. 
2. 
3. 
4. 

### 相关截图或日志
https://s1.ax1x.com/2020/04/25/JrTlmd.jpg

<details>

```
Qv2ray 日志
```

</details>

### 受影响的 Qv2ray 安装平台

- [x] Linux
- [x] macOS
- [x] Windows

### 受影响的 Qv2ray 安装源

- [x] ArchLinuxCN
- [x] Homebrew Cask
- [x] Scoop
- [x] 手动编译
- [x] Github Release

### 首选项 -> 关于信息：

```
版本号: Qv2ray.v2.4.1.Windows-x64  Qv2ray.v2.5.0-pre2.Windows-x64
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by DuckSoft** [comment]
问题已定位：上述 Base64 解码后所得结果为：
```
{"ps":"[youneed.win]xxxxxx.site","add":"ray.east-cu.1.90porn.site","port":"8002","id":"9c1xxxxxxxxxf28902","aid":"0","net":"ws","type":"none","host":"/yaboviss","tls":""}⏎
```

该 Vmess 中将 addr（地址）写在了 host（主机名）的位置，导致 Qv2ray 无法识别。
将随后修复此问题。

**Comment by DuckSoft** [comment]
v2rayN 导入正常，显示如下：
![图片](https://user-images.githubusercontent.com/7822648/80241005-66baf900-8695-11ea-9344-64ba22a57e87.png)
似乎是自动改正了此错误。

**Comment by DuckSoft** [comment]
Assigning to @Qv2ray-dev.

**Comment by DuckSoft** [comment]
把 v2rayN 的代码拉了下来，仔仔细细看了一遍，眼要瞎了……
问题在 v2rayN 里面的一个 `UpgradeServerVersion` 函数：
https://github.com/2dust/v2rayN/blob/737d563ebb66d44504c3a9f51b7dcbb382991dfd/v2rayN/v2rayN/Handler/ConfigHandler.cs#L710-L724

```csharp
case "ws":
    //*ws(path+host),它们中间分号(;)隔开
    arrParameter = vmessItem.requestHost.Replace(" ", "").Split(';');
    if (arrParameter.Length > 0)
    {
        path = arrParameter[0];
    }
    if (arrParameter.Length > 1)
    {
        path = arrParameter[0];
        host = arrParameter[1];
    }
    vmessItem.path = path;
    vmessItem.requestHost = host;
    break;
```

非常魔性。人家规定就是 host 里面又写 path 又写 host，还用分号隔开的。
（话说，我非常想知道，如果path里面带分号会怎么样……）

**Comment by DuckSoft** [comment]
本 bug 修复预计将会包含在 2.5.0-rc1 预览版中。
抱歉为你带来的不便。敬请关注更新。

**Comment by DuckSoft** [comment]
Upstream Tracker: https://github.com/2dust/v2rayN/issues/737

**Comment by Qv2ray-dev** [comment]
There's nothing standard when coming onto the `vmess` share link.

https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)

**Comment by Qv2ray-dev** [comment]
No documents provided.

**Comment by Qv2ray-dev** [comment]
We'll update the vmess tracker via #252 , but that is not as part of the Qv2ray v2.5.0-rc1.

> How dare the service provider put `path` into the `host` field?

**Comment by Qv2ray-dev** [comment]
> v2rayN 导入正常，显示如下：
> ![图片](https://user-images.githubusercontent.com/7822648/80241005-66baf900-8695-11ea-9344-64ba22a57e87.png)
> 似乎是自动改正了此错误。

图里面 / wiki 已经解释的很清楚，path 就是 ws 的 path， 那么 host 里面就不得出现其他内容

closing

**Comment by DuckSoft** [comment]
挖坟：dev分支已修复。请静待 2.6.0
