### ISSUE TITLE
无法使用。所有订阅链接都无法更新，返回是0，怎么试都没用。

### ISSUE THREAD

**Issue by VergilChin** [Qv2ray/Qv2ray#545]
# 简单描述这个 bug:
无法使用。所有订阅链接都无法更新，返回是0，怎么试都没用。

# 如何复现这个bug：

1. 无法使用。所有订阅链接都无法更新，返回是0，怎么试都没用。
2. 
3. 
4. 

### 相关截图或日志

<details>

```
Qv2ray 日志
```

</details>

### 受影响的 Qv2ray 安装平台

- [ ] Linux
- [ ] macOS
- [x] Windows

### 受影响的 Qv2ray 安装源

- [ ] ArchLinuxCN
- [ ] Homebrew Cask
- [ ] Scoop
- [ ] 手动编译
- [x] Github Release

### 首选项 -> 关于信息：

```
版本号: 
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by Qv2ray-dev** [comment]
请问你使用的是什么版本？

另外这个问题在 dev 已经修复，你可以试一下 https://github.com/Qv2ray/Qv2ray/actions/runs/86487475

**Comment by DuckSoft** [comment]
使用问题建议加群直接沟通解决。
Telegram 群链接：https://t.me/qv2ray

**Comment by Qv2ray-dev** [comment]
Should be fixed within Qv2ray v2.5.0-rc1
