### ISSUE TITLE
PAC 插件上不了 Telegram

### ISSUE THREAD

**Issue by h1xy** [Qv2ray/Qv2ray#547]
# 简单描述这个 bug:
其他网站可以，就telegram不行，用了PAC插件。应如何设置？

# 如何复现这个bug：

1. 
2. 
3. 
4. 

### 相关截图或日志

<details>

```
Qv2ray 日志
```

</details>

### 受影响的 Qv2ray 安装平台

- [ ] Linux
- [ ] macOS
- [ ] Windows

### 受影响的 Qv2ray 安装源

- [ ] ArchLinuxCN
- [ ] Homebrew Cask
- [ ] Scoop
- [ ] 手动编译
- [ ] Github Release

### 首选项 -> 关于信息：

```
版本号: 
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by DuckSoft** [comment]
你好，请填写 Qv2ray 版本号、操作系统名称等环境信息。
此外，Telegram 代理配置情况，烦请截图。

**Comment by h1xy** [comment]
搞定了，tele里面设置sock5代理指向qv2ray里面设置

**Comment by DuckSoft** [comment]
all right. solved.
