### ISSUE TITLE
linux下建议加入32位和arm的版本。

### ISSUE THREAD

**Issue by 9h5ej** [Qv2ray/Qv2ray#548]
有些老机器上可能安装的是32位的linux，树莓派安装的是arm的linux，x64版本的软件无法在这些平台上运行。自己编译又太麻烦。

**Comment by DuckSoft** [comment]
其实我们没说……我们支持 ARM 架构。
目前可以直接从 snap 安装。

另外 x86 架构也应该是支持的，只不过没有放出来。
我相信仍在使用 32 位 Linux 的用户有基本的能力去编译。

或者，您也可以考虑为我们贡献一个 32 位的打包脚本，在此先行谢过了。

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/80295355-ad4b4900-87a4-11ea-9acf-9c93808bc789.png)
附注：有相关特殊架构需要的可以直接从 snap 安装。
