### ISSUE TITLE
在linux命令行下无法优雅的后台运行？

### ISSUE THREAD

**Issue by needhourger** [Qv2ray/Qv2ray#549]
# 简单描述这个 bug
* 系统：kali linux 5.5.0
*  Qv2ray：2.5.0
* v2ray：4.23.1
* 使用命令：
```
nohup ./Qv2ray.AppImage >./dev/null 2>/dev/null &
```
运行程序，一旦关闭命令行，Qv2ray也自我停止了

# 如何复现这个bug：

1. 打开命令行
2. nohup ./Qv2ray.AppImage >./dev/null 2>/dev/null &
3. 关闭命令行
4. 后台程序停止

### Qv2ray 本应该是怎样工作的？
期望可以使用命令行后台运行，也可能是我太菜了，没有发现可行到办法，还望大佬指正

### 相关截图或日志

<details>

```
Qv2ray 日志
```

</details>

### 受影响的 Qv2ray 安装平台

- [x] Linux
- [ ] macOS
- [ ] Windows

### 受影响的 Qv2ray 安装源

- [ ] ArchLinuxCN
- [ ] Homebrew Cask
- [ ] Scoop
- [ ] 手动编译
- [x] Github Release

### 首选项 -> 关于信息：

```
版本号: 
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by DuckSoft** [comment]
This is not related to Qv2ray itself, nor shall it be considered as a bug.

**Comment by DuckSoft** [comment]
You can consult this problem in a random Linux society. 
This issue is about to be closed immediately.
