### ISSUE TITLE
Under OSX, system crashes as soon as click on connect

### ISSUE THREAD

**Issue by higgssinglet** [Qv2ray/Qv2ray#550]
**Briefly describe this bug：**

OSX, already issued chmod +x on v2ray and v2ctl under core.  V2ray core passed the check test

**How can I trigger this bug：**

1.  When a node is selected, click on connect, all ss, ssr, v2ray and trojan same results
[qv2ray crash.txt](https://github.com/Qv2ray/Qv2ray/files/4534768/qv2ray.crash.txt)

2. 
3. 
4. 

**What is expected to happen**

**Screenshots**
If appropriate, please attach some screenshots.

**System Information**

 - OS Type: OSX 10.13.6
 - Built from the source or download from the release? Download from release
 - Version string in the Preferences Window  Version 2.5.0-rc1

**Other Info**

You may want to write anything if you think it helps us to fix the bug.

*Please hide your server address and UUID if you wish to post the vmess string or your connection setting.*

**Comment by DuckSoft** [comment]
thanks for your report. received. investigation in progress. 
ps: since us Qv2ray developers have no device running macOS, this can take up to weeks.

**Comment by Qv2ray-dev** [comment]
https://github.com/Qv2ray/QvPlugin-Trojan/actions/runs/88073642
https://github.com/Qv2ray/QvPlugin-SSR/actions/runs/88073410

Please test these 2 builds once they are completed. Thanks

**Comment by higgssinglet** [comment]
Thanks for the quick response, I unzipped the files one is Qvssr and one is Qvtrojan both are Plugin.so files, May I ask where to copy them to?  I put them in the plug-in directory and results are the same so I assume I copied them into the wrong location.

**Comment by Qv2ray-dev** [comment]
Just replace the existing 2 plugins, and restart Qv2ray. See if things changed

**Comment by higgssinglet** [comment]
Hi, I replaced the two libQvssr and libQvtrojan plugins under the /$HOME/library/preferences/q2ray/plugins directory. Still crashes.  attached is the crash report
[qv2ray crash 2.txt](https://github.com/Qv2ray/Qv2ray/files/4534807/qv2ray.crash.2.txt)

**Comment by Qv2ray-dev** [comment]
See also: https://github.com/trojan-gfw/trojan/issues/352
We feel sorry that this may affect your experience, but this is actually from the Upstream (macOS).

We cannot resolve this issue for now, the only solution is to update your OS since 10.13 is currently out-of-date.

**Comment by Qv2ray-dev** [comment]
You may want to remove those plugin files to make sure the V2ray feature works properly.

**Comment by DuckSoft** [comment]
Closed due to inability.
