### ISSUE TITLE
功能建议：win平台Protable化，将所有配置文件保存在当前应用程序目录下

### ISSUE THREAD

**Issue by lostinfever** [Qv2ray/Qv2ray#552]
目前程序安装运行后，会自动在AppData\Local下创建一个qv2ray文件夹用来保存和读取配置文件。

订阅、插件等配置都保存在这个文件夹内，更换新的环境需要单独复制qv2ray文件夹到AppData\Local才能读取配置，不能在便携设备或云端直接使用。

建议让程序第一次运行时，自动查找当前目录下是否存在config文件夹，如果存在，将从此文件夹内读取和修改配置文件，如果当前目录不存在config文件夹，再去AppData\Local下创建qv2ray文件夹。

这样可以实现在便携设备或云端直接使用本程序，不用再重新设置，望采纳！

**Comment by ACERLZ** [comment]
@lostinfever  有portal版的，7z压缩包那个

**Comment by lostinfever** [comment]
> @lostinfever 有portal版的，7z压缩包那个，那个就是解压即用，读取解压目录下的config文件夹里的配置，不会在AppData\Local下创建qv2ray文件夹

感谢，我下载了7z那个，但是因为没创建config文件夹，所以还是从AppData\Local读取配置文件了
