### ISSUE TITLE
ubuntu18.04无法使用么？ 多次安装出现依赖问题， 无法修复

### ISSUE THREAD

**Issue by huangsiyuan924** [Qv2ray/Qv2ray#553]
![2](https://user-images.githubusercontent.com/47273722/80357605-cbe93700-88ad-11ea-8e13-4a1fdfa2d445.png)
![1](https://user-images.githubusercontent.com/47273722/80357611-d0155480-88ad-11ea-99e8-27d3e671e614.png)
![3](https://user-images.githubusercontent.com/47273722/80357617-d1df1800-88ad-11ea-9375-16b9803aa1a1.png)

**Comment by Qv2ray-dev** [comment]
Assigned to @ymshenyu

**Comment by ymshenyu** [comment]
deb包仅支持19.04及以上的系统，详情请看[wik](https://qv2ray.github.io/getting-started/step1.html#github-release-%E4%BA%8C%E8%BF%9B%E5%88%B6%E6%96%87%E4%BB%B6)i
