### ISSUE TITLE
vantage "v2rayN" VMess v1 support

### ISSUE THREAD

**Issue by choohoo** [Qv2ray/Qv2ray#555]
I have a subscription.It can be updated successfully in the old version.But in the v2.5.0,When I update this subscription,"Last updated" can be updated,but "connection list" is empty.And no message was displayed during this process.
Is it related to dropping support for vmess: // v1？

**Comment by Qv2ray-dev** [comment]
https://github.com/Qv2ray/Qv2ray/blob/991547bc4ab24394f6ce20f8833bec938cc802f7/src/core/connection/Serialization_vmess.cpp#L109

Should we check for the value in `v` instead of checking its existance?

**Comment by Qv2ray-dev** [comment]
@DuckSoft

**Comment by DuckSoft** [comment]
> @DuckSoft

negative. since that's a REQUIRED field of v2 vmess.

**Comment by DuckSoft** [comment]
问题查明，的确是机场上游面板过于老旧，还在使用 v1 格式的 vmess 连接。
不过，这个问题的确不能怪用户。准备单独定制一版。

**Comment by mini536** [comment]
> 问题查明，的确是机场上游面板过于老旧，还在使用 v1 格式的 vmess 连接。
> 不过，这个问题的确不能怪用户。准备单独定制一版。

我这里好像出现了一个问题：订阅链接显示0节点问我是否继续，但是其它的v2ray客户端显示有20个，不知道是不是因为这个问题

**Comment by DuckSoft** [comment]
> > 问题查明，的确是机场上游面板过于老旧，还在使用 v1 格式的 vmess 连接。
> > 不过，这个问题的确不能怪用户。准备单独定制一版。
> 
> ## 我这里好像出现了一个问题：订阅链接显示0节点问我是否继续，但是其它的v2ray客户端显示有15个，不知道是不是因为这个问题
> 
> 切换到2.4.1就没有问题了

你好，你可能是旧版 vmess 的受害者。
由于旧版 vmess 没有文档，而且格式极其混乱，我们尽量整理。预计在 2.5.1 发布修复版本。

**Comment by Qv2ray-dev** [comment]
Tracker as #252

**Comment by Qv2ray-dev** [comment]
fixed in #609
