### ISSUE TITLE
Sorting nodes manually

### ISSUE THREAD

**Issue by idnsunset** [Qv2ray/Qv2ray#559]
I've noticed that there is a small button on the right top corner of the node list for sorting nodes depending on alphabetical order, data and latency. However, it would be better to allow users to sort nodes manually. I have a long list of nodes and I want to put the most used ones on the top without having to scroll down to find them.

**Comment by DuckSoft** [comment]
You've got sharp eyes. This will be implemented in Qv2ray v2.7.0. Be Patient.
