### ISSUE TITLE
Support manual sorting?

### ISSUE THREAD

**Issue by madjxatw** [Qv2ray/Qv2ray#561]
Hi, dear qv2ray developers, this is not a bug report but a trivial feature suggestion. Would you consider adding manual sorting on connections? Some connections may not working currently but would be back working later, I need to move them to the bottom of the list. Sorting them by name, data or latency is not what I am exactly expecting.

**Comment by madjxatw** [comment]
Same to #561

**Comment by Qv2ray-dev** [comment]
Yes definately.
Manually sorted list is more friendly for users who has huge amout of connections and we have already added into our checklist.

Since the change will break the existing configuration model. We have added it into our v2.7 TODO list.
