### ISSUE TITLE
在校使用随E行连接网络后无法翻墙

### ISSUE THREAD

**Issue by nishino94** [Qv2ray/Qv2ray#563]
- [x] 我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的每个软件及其版本。
- [x] 我已知晓如果未能提供有效信息（譬如正确填写以下内容），Qv2ray 工作组会视情况关闭此 Issue

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:

在学校使用“随E行”连接网络无法翻墙
在家可以正常翻墙
同一节点使用v2rayN在学校也可以正常翻墙
在学校使用随E行连接网络后使用qv2ray连接节点后流量似乎并不走qv2ray除连接节点时有日志，用Chrome或火狐试图打开YouTube等网页时日志都没变过

# 如何复现这个 Bug：

1. 在学校用随E行连接网络
2. 
3. 
4. 

### 如果是连接问题，在其他 v2ray 客户端里出现过吗？ 

无

### 相关截图或日志
![1](https://user-images.githubusercontent.com/64535086/80596516-122ec980-8a59-11ea-99f8-0339a3e18b1a.png)
![2](https://user-images.githubusercontent.com/64535086/80596562-296db700-8a59-11ea-9c29-71fa0c8dd5c0.png)
![3](https://user-images.githubusercontent.com/64535086/80597507-874ece80-8a5a-11ea-8feb-57dab07562c0.png)
![4](https://user-images.githubusercontent.com/64535086/80597517-89b12880-8a5a-11ea-90eb-fda82058e640.png)

<details>

```
Qv2ray 日志：

V2Ray 4.22.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2020/04/29 20:24:18 [Info] v2ray.com/core/app/dns: DNS: created udp client inited for 8.8.4.4:53
2020/04/29 20:24:18 [Info] v2ray.com/core/app/dns: DNS: created udp client inited for 1.1.1.1:53
2020/04/29 20:24:18 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:15490
2020/04/29 20:24:18 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:8888
2020/04/29 20:24:18 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1088
2020/04/29 20:24:18 [Info] v2ray.com/core/transport/internet/udp: listening UDP on 127.0.0.1:1088
2020/04/29 20:24:18 [Warning] v2ray.com/core: V2Ray 4.22.0 started
2020/04/29 20:24:18 [Info] [3384231913] v2ray.com/core/app/dispatcher: taking detour [_QV2RAY_API_] for [tcp:127.0.0.1:0]
```

</details>

### 受影响的 Qv2ray 安装平台

- Windows

### 受影响的 Qv2ray 安装源

- Github Release

### 已安装的插件 & 插件安装源：
无

### 首选项 -> 关于信息：

```
版本号: 2.4.1
内部版本号：
编译信息：Qv2ray built from Github Action
其它编译信息：qt5.14.2-30a99e596c6bcaac9ac93b8c0c93fe305fc00ea6-ci.windows-latest
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by Qv2ray-dev** [comment]
你好，请确认 “随e行” 的链接是否为 “拨号链接” 或 “VPN” 链接，
Qv2ray 目前不支持对这样的网络设置系统代理，请在 Firefox 内手动设置

**Comment by nishino94** [comment]
可能是 拨号连接 或 VPN连接 吧
我不是很清楚，不过应该也只有这个可能了
毕竟v2rayN,ssr都可以使用，笔记本打开无线出来给手机用也可以翻
就是qv2ray不行TAT

**Comment by nishino94** [comment]
> 
> 
> 你好，请确认 “随e行” 的链接是否为 “拨号链接” 或 “VPN” 链接，
> Qv2ray 目前不支持对这样的网络设置系统代理，请在 Firefox 内手动设置

可能是 拨号连接 或 VPN连接 吧
我不是很清楚，不过应该也只有这个可能了
毕竟v2rayN,ssr都可以使用，笔记本打开无线出来给手机用也可以翻
就是qv2ray不行TAT

**Comment by DuckSoft** [comment]
应该是是个烟雾弹。你先检查以下内容:
1. 启动系统代理之后，浏览器随便开几个页面。此时注意观察 Qv2ray 日志窗口，有无对应网站域名刷出来。如果没刷出来，就是系统代理设置的问题。
2. 如果刷出来域名了，则检查是否有持续的错误日志。某些机场可能会开一些奇怪的证书（比如自签名），Qv2ray 为了你的菊花安全默认不允许，你可能需要手动启用之后才能正常连接。
3. 如果还没解决，请检查系统时间是否与网络同步。如果还不行，我可以直接 Teamviewer 远程解决。

**Comment by nishino94** [comment]
> 
> 
> 应该是是个烟雾弹。你先检查以下内容:
> 
>     1. 启动系统代理之后，浏览器随便开几个页面。此时注意观察 Qv2ray 日志窗口，有无对应网站域名刷出来。如果没刷出来，就是系统代理设置的问题。
> 
>     2. 如果刷出来域名了，则检查是否有持续的错误日志。某些机场可能会开一些奇怪的证书（比如自签名），Qv2ray 为了你的菊花安全默认不允许，你可能需要手动启用之后才能正常连接。
> 
>     3. 如果还没解决，请检查系统时间是否与网络同步。如果还不行，我可以直接 Teamviewer 远程解决。

qv2ray日志无网站域名刷出来
时间与网络基本同步，相差几秒
应该是作者所说的原因，因为在家可以正常使用qv2ray

**Comment by DuckSoft** [comment]
嗯。那这种情况下，你可以考虑使用 SwitchyOmega 之类的浏览器插件，把浏览器流量强制定向到 Qv2ray 的 HTTP/SOCKS 入站即可。

**Comment by nishino94** [comment]
> 
> 
> 嗯。那这种情况下，你可以考虑使用 SwitchyOmega 之类的浏览器插件，把浏览器流量强制定向到 Qv2ray 的 HTTP/SOCKS 入站即可。

使用 SwitchyOmega 已经搞好可以成功翻墙了
