### ISSUE TITLE
failed to compile from aur on manjaro linux

### ISSUE THREAD

**Issue by Xusine1131** [Qv2ray/Qv2ray#568]
- [X] 我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的每个软件及其版本。
- [X] 我已知晓如果未能提供有效信息（譬如正确填写以下内容），Qv2ray 工作组会视情况关闭此 Issue

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:

环境为5.4.35-1-MANJARO x86_64，直接在AUR上拉取，编译会报错。
报错提示为：

```
/bin/ld: CMakeFiles/qv2ray.dir/v2ray_geosite.pb.cc.o: undefined reference to symbol '_ZN6google8protobuf8internal17UnknownFieldParseEjPNS1_25InternalMetadataWithArenaEPKcPNS1_12ParseContextE'
/bin/ld: /usr/lib/libprotobuf.so.22: error adding symbols: DSO missing from command line
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```

我认为是Linux的CMake中没有link libprotobuf.so的问题。

# 如何复现这个 Bug：

1. 使用AUr拉取后编译。

### 如果是连接问题，在其他 v2ray 客户端里出现过吗？ 

非连接问题

### 相关截图或日志

<details>

```
Qv2ray 日志：


```

</details>

### 受影响的 Qv2ray 安装平台

- Linux

### 受影响的 Qv2ray 安装源

- ArchLinux AUR - 稳定版 

只测试了这一个源。

### 首选项 -> 关于信息：

```
版本号: 
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

我截取了最后连接的部分命令行：

```
-o qv2ray  /usr/lib/libQt5Widgets.so.5.14.2  /usr/lib/libQt5Network.so.5.14.2  /usr/local/lib/libprotobuf.a  -lgrpc++  -lgrpc  -laddress_sorting  -lupb  -lcares  -lz  -lgpr  -labsl_bad_optional_access  -labsl_str_format_internal  -labsl_strings  -labsl_strings_internal  -labsl_base  -labsl_spinlock_wait  -labsl_dynamic_annotations  -labsl_int128  -labsl_throw_delegate  -labsl_raw_logging_internal  -labsl_log_severity  -lssl  -lcrypto  -lZXingCore  /usr/lib/libQt5Gui.so.5.14.2  /usr/lib/libQt5Core.so.5.14.2  -lpthread
```
一个比较显眼地方是链接时确实引用了 `/usr/local/lib/libprotobuf.a`, 但是没有最后 -llibprotobuf。

**Comment by DuckSoft** [comment]
Investigating.

**Comment by Qv2ray-dev** [comment]
You need to check your protobuf version, see here: https://github.com/clearlinux-pkgs/protobuf/blob/master/symbols#L3164

**Comment by DuckSoft** [comment]
无法复现于 Arch Linux x86_64 5.6.8-arch1-1。
你应知晓 AUR 在 Manjaro 上的支持有限，可能会出现问题。

请考虑使用 archlinuxcn 直接编译的版本，或者，你可自行研究解决。

**Comment by DuckSoft** [comment]
Rebuilt using clang/clang++ version 10.0.0 and everything is okay.
Check your environment?

**Comment by DuckSoft** [comment]
你好，我们刚刚在你的日志中发现了一处异常：
```
/usr/local/lib/libprotobuf.a
```

据我所知，Arch 系的发行版的 /usr/local/lib 都是空的。CMake 找到这里的可能原因，大概率是你之前误操作运行了 make install 之类的神奇命令却没有手动限制一下 PREFIX，导致自己的系统环境被污染。

FYI。

**Comment by Xusine1131** [comment]
@DuckSoft Thanks! 我一直都是用AUR来管理lib的，我把那个位置清理一下然后再试一下！

**Comment by Xusine1131** [comment]
@DuckSoft I think I have fixed the problem. Previously I installed the Torch C++ Library and its libraries are put at /usr/local/lib, which includes the libprotobuf.a.
It would be appreciated if you can change the protobuf library type to dynamic so that CMake would find the correct one. Just a suggestion.
