### ISSUE TITLE
mac 上打开后无界面

### ISSUE THREAD

**Issue by wsz7777** [Qv2ray/Qv2ray#569]
- [x] 我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的每个软件及其版本。
- [ ] 我已知晓如果未能提供有效信息（譬如正确填写以下内容），Qv2ray 工作组会视情况关闭此 Issue

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:
mac 上打开后无界面，我已经在安全中点击 “仍要打开” 了

# 如何复现这个 Bug：

1. 如描述

### 受影响的 Qv2ray 安装平台
- macOS

### 受影响的 Qv2ray 安装源

- Github Release

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
mac最新版本 10.15.4

**Comment by Qv2ray-dev** [comment]
再试一次？

**Comment by wsz7777** [comment]
我试过多次了

**Comment by DuckSoft** [comment]
对于此类使用问题，你可加入我们的 Telegram 群组 https://t.me/qv2ray 进行讨论。
在 GitHub Issues 上进行讨论往往信息量不足而低效，很难解决问题。

**Comment by wsz7777** [comment]
![image](https://user-images.githubusercontent.com/33828341/80907961-03dcf800-8d4e-11ea-9d46-2df3a07b4a2b.png)

**Comment by wsz7777** [comment]
![image](https://user-images.githubusercontent.com/33828341/80907966-1ce5a900-8d4e-11ea-92ca-54f2fd234a28.png)

**Comment by Qv2ray-dev** [comment]
![image](https://user-images.githubusercontent.com/59914293/80907980-3edf2b80-8d4e-11ea-8482-fe7d52aef787.png)
你可以点击 “报告” 然后将其内容发送过来

**Comment by DuckSoft** [comment]
Closing This Issue: Not Following Template.

**Comment by wsz7777** [comment]
需要重启电脑。。。。千年不重启真是「手动狗头」

**Comment by zp260** [comment]
> 需要重启电脑。。。。千年不重启真是「手动狗头」

重启后就行了？
