### ISSUE TITLE
会不会出DOCKER版本，或者群晖版本？

### ISSUE THREAD

**Issue by czxinshui** [Qv2ray/Qv2ray#573]
会不会出DOCKER版本，或者群晖版本？

**Comment by DuckSoft** [comment]
应该不会，毕竟本质上是一个运行在客户端的图形界面的应用程序。

**Comment by DuckSoft** [comment]
群晖等平台有更好的专用解决方案，我们的 Qv2ray 的受众不是智能路由设备，而是实际的用户终端。
在这种情况下，Qv2ray 可能很难满足你的使用需求。
