### ISSUE TITLE
改善既有的 VMess ”v2rayN" V2 Parser 的鲁棒性

### ISSUE THREAD

**Issue by tleydxdy** [Qv2ray/Qv2ray#575]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:
更改json中key的顺序，或者有的项目有缺省会导致导入失败，订阅会显示导入了但是实际没有

# 如何复现这个 Bug：

1. 改变订阅里的vmess链接的key的顺序
2. 刷新
3.该条目消失 

### 如果是连接问题，在其他 v2ray 客户端里出现过吗？ 
kitsunebi 可导入

### 相关截图或日志

<details>

```
Qv2ray 日志：


```

</details>

### 受影响的 Qv2ray 安装平台

- Linux

### 受影响的 Qv2ray 安装源

- ArchLinux AUR - 开发版
- Fedora - 稳定版

### 首选项 -> 关于信息：

```
版本号: 
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by TheWanderingCoel** [comment]
Describe your issue, please.

**Comment by tleydxdy** [comment]
手机页面抽风不知怎么的就发出去了：（

**Comment by DuckSoft** [comment]
你好，请问有样例 vmess 可助我等重现问题吗？

**Comment by DuckSoft** [comment]
首先请确认你的 vmess 的版本不是 v1 版本的 vmess。
确认方法为：查看你的 vmess 解码后的 json，若无 "v":"2" 或 "v":2 字段，即为 v1 版本的 vmess。

关于 v1 版本的 vmess：此版本 vmess 行为极其诡异，我们暂时在 2.5.0 中取消了对其的支持。
目前正在逐字逐句啃上游 v2rayN 的代码，以期对其进行兼容。

**Comment by tleydxdy** [comment]
是v2的，刚刚重试了一下好像顺序是没问题的，但是比如说把host项去掉就不能导入，哪怕是quic的链接

**Comment by DuckSoft** [comment]
你好，这个问题提的非常好。上游 v2rayN 只提供了一个简陋的 wiki 为我们解说 VMess 标准：
https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)

我们当然也希望在保证正确性的前提下，加强我们 VMess Parser 的鲁棒性。
若不介意，请至少提供对应的一些正负样例及其对应的期待/实际结果，以便于我们进行重构/重写。

或者，你也可以直接帮助我们：
https://github.com/Qv2ray/Qv2ray/blob/dev/src/core/connection/Serialization_vmess.cpp

**Comment by tleydxdy** [comment]
那我直接提pr吧，谢谢。

**Comment by DuckSoft** [comment]
> 那我直接提pr吧，谢谢。

非常感谢~
另外，由于我们的开发速度相对较快，强烈建议加入我们的 Telegram 群组，与我们一同讨论开发中的事宜。

群组链接：https://t.me/qv2ray

**Comment by DuckSoft** [comment]
本 Issue 留作本系列问题的 Tracker。

**Comment by Qv2ray-dev** [comment]
Close #252

**Comment by tleydxdy** [comment]
我没有telegram :( 最近都是用matrix。虽说可以桥接。

我先试着参照v2ray的文档添加每个key的默认值，看起来不是很复杂。

**Comment by DuckSoft** [comment]
Closed Due To Dated. Open Pull Requests instead.
