### ISSUE TITLE
建议&bug

### ISSUE THREAD

**Issue by yunmi323** [Qv2ray/Qv2ray#576]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug1:

程序长时间在前台显示有机会闪退！

# 如何复现这个 Bug1：

不知道

# 简单描述这个 Bug2:

上次提到的一连v2ray 内核就崩 #536 

# 如何复现这个 Bug2：

不限#536 那种解决方法

v2ray内核所在文件夹名必须为v2ray-core，否则一连就崩

### 受影响的 Qv2ray 安装平台

- Windows

### 受影响的 Qv2ray 安装源

- Github Release

### 首选项 -> 关于信息：

```
版本号: 2.5.0
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

建议：

1增加自动更新订阅功能

2增加检测v2ray内核是否运行，如果正在运行结束v2ray内核进程。如果程序闪退内核还在运行，会导致下次运行程序是不能连接到v2ray，必须杀掉v2ray内核进程再连接

**Comment by Qv2ray-dev** [comment]
cc @DuckSoft

**Comment by DuckSoft** [comment]
1. 目前 @Qv2ray-dev 在调整订阅和分组功能，我目前无法进行实现，等待中。
2. 将拆分到新 Issue 追踪，代号 QvKernelTerminator。

另外关于端口占用问题，有一种情况是无法解决的：
https://support.microsoft.com/eu-es/help/4074588/windows-10-update-kb4074588

暂时关闭本 Issue。

**Comment by DuckSoft** [comment]
中文参考材料：https://juejin.im/post/5de4fafee51d4530e9129b27
