### ISSUE TITLE
QvKernelTerminator: 尝试自动结束正在运行的内核

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#578]
> The Cure for #536 #576.
- [x] 准备工作
- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] 整合
- [ ] 测试
- [ ] 发布

**Comment by unknowndev233** [comment]
可能要考虑一个问题：如何知道哪些 v2ray 进程是 Qv2ray 启动的

**Comment by Qv2ray-dev** [comment]
@unknowndev233 可以根据进程监听端口判断，一般情况下api端口是 Qv2ray 自己设置的

**Comment by hosiet** [comment]
如果要百分百准确追踪的话 Linux 下很容易，进程树或者 cgroups 都可以追踪；不过大概代码逻辑得调整一下了

**Comment by unknowndev233** [comment]
> 如果要百分百准确追踪的话 Linux 下很容易，进程树或者 cgroups 都可以追踪；不过大概代码逻辑得调整一下了

但是除了 Linux 之外都没有 cgroups，不过追踪 Qv2ray 产生的 v2ray 进程应该用不上这么重量级的工具
感觉记录 pid 已经足够了

**Comment by unknowndev233** [comment]
> 如果要百分百准确追踪的话 Linux 下很容易，进程树或者 cgroups 都可以追踪；不过大概代码逻辑得调整一下了



> @unknowndev233 可以根据进程监听端口判断，一般情况下api端口是 Qv2ray 自己设置的

只检查 api 端口是被名为 v2ray 占用的吗？

**Comment by Qv2ray-dev** [comment]
@unknowndev233 是的，Qv2ray 的 15490 api 端口一般情况下不会有其他程序使用

**Comment by unknowndev233** [comment]
> @unknowndev233 是的，Qv2ray 的 15490 api 端口一般情况下不会有其他程序使用

太直接了（

**Comment by studentmain** [comment]
父子进程？

> 
> 
> 可能要考虑一个问题：如何知道哪些 v2ray 进程是 Qv2ray 启动的

**Comment by unknowndev233** [comment]
> 父子进程？
> 
> > 可能要考虑一个问题：如何知道哪些 v2ray 进程是 Qv2ray 启动的

上一个 Qv2ray 已经死了啊

**Comment by DuckSoft** [comment]
@unknowndev233 可能有带 Qv2ray 的 config.gen.json cmdline

**Comment by unknowndev233** [comment]
> @unknowndev233 可能有带 Qv2ray 的 config.gen.json cmdline

文件的绝对路径？

**Comment by Qv2ray-dev** [comment]
是的

**Comment by Qv2ray-dev** [comment]
So, are you currently working on this feature? @DuckSoft

**Comment by DuckSoft** [comment]
@Qv2ray-dev WIP

**Comment by kslr** [comment]
可以输出一个 pid

**Comment by U-v-U** [comment]
Closing, since it's unnecessary to do this on the Qv2ray side.
