### ISSUE TITLE
deepin 15.11无法打开本地插件目录

### ISSUE THREAD

**Issue by zss192** [Qv2ray/Qv2ray#580]
当尝试打开插件目录时会打开一个文件管理夹，但并不会自动打开名为plugins的目录，望解答

**Comment by DuckSoft** [comment]
Deepin 15.11 => AppImage => @ymshenyu

**Comment by DuckSoft** [comment]
本问题已在 #571 中提出，并已在最新的提交 527820ee5ffdf7dcb837c52f064dd3692e028969 中修复。
目前已包含在 dev 分支中。

若你急切需要 bug 修复，你可自行从 GitHub Actions 中取用 dev 分支的预览版本。
若不是很急，请静待我们的新版本。

**Comment by DuckSoft** [comment]
本问题暂时关闭。若你需要进一步的技术支持，请考虑加入我们在 Telegram 的用户群组，与开发者直接对话：
https://t.me/qv2ray
