### ISSUE TITLE
qv2ray如何设置shadowsocks的obfs

### ISSUE THREAD

**Issue by gearfox** [Qv2ray/Qv2ray#582]
请问各位qv2ray如何设置shadowsocks的obfs？？

**Comment by Qv2ray-dev** [comment]
@gearfox ss 暂不支持 obfs 插件

**Comment by DuckSoft** [comment]
由于 Qv2ray 目前的 Shadowsocks 功能由 V2Ray Core 提供支持，上游没有支持 obfs 的选项，故暂时无法使用 obfs。

我们有打算做一个全功能的 shadowsocks 插件，敬请期待。

**Comment by ZEYAX** [comment]
同求obfs 感谢大佬

**Comment by Qv2ray-dev** [comment]
https://github.com/Qv2ray/Qv2ray/issues/584

@gearfox @ZEYAX

**Comment by YFTX2015** [comment]
弄好希望能支持justmysocks 3号跟4号服务器

**Comment by allbutone** [comment]
> 弄好希望能支持justmysocks 3号跟4号服务器

just my socks 3 号 v2ray 在 qV2ray 不支持吗? 我这里实测是支持的, 只是 3 号速度不理想.

**Comment by YFTX2015** [comment]
qv2ray不是不支持obfs插件么？而3号跟4号需要这个插件。我不晓得你是咋个弄的插件。

**Comment by PeppaCat** [comment]
问下各位现在在linux环境下能使用just my socks3/4号的带obfs插件的工具有哪些呢？
