### ISSUE TITLE
支持Shadowsocks SIP003插件

### ISSUE THREAD

**Issue by studentmain** [Qv2ray/Qv2ray#584]
## 目的

兼容正在广泛使用的Shadowsocks插件标准[SIP003](https://shadowsocks.org/en/spec/Plugin.html)。

## 要点

- 连接时启动插件，并传递`SS_REMOTE_HOST`, `SS_REMOTE_PORT`, `SS_LOCAL_HOST`, `SS_LOCAL_PORT`, `SS_PLUGIN_OPTIONS`环境变量以设置插件
- Shadowsocks客户端（此时是v2ray-core）向 `SS_LOCAL_HOST:SS_LOCAL_PORT` 而非实际的服务器（`SS_REMOTE_HOST:SS_REMOTE_PORT`）发起连接
- 当插件程序退出时需断开连接
- 断开连接时关闭插件程序

## 方案

v2ray-core没有SIP003支持，因此相关操作需要由Qv2ray执行（或者给v2ray-core开issue）。当Shadowsocks连接包含插件时，由Qv2ray本体启动SIP003插件并传递所需环境变量，将v2ray配置文件中的服务器地址和端口设置为SIP003插件的监听地址和端口进行连接。

## 设想

可否使用v2ray-core模拟Shadowsocks v2ray-plugin。

**Comment by wallena3** [comment]
@studentmain 想问下这个现在有进展么

**Comment by Qv2ray-dev** [comment]
@wallena3 We will be working on this since it's left opened.

**Comment by DuckSoft** [comment]
已 经 支 持 了
