### ISSUE TITLE
Windows 自动更新重启会弄坏 Qv2ray 配置文件

### ISSUE THREAD

**Issue by LuXts** [Qv2ray/Qv2ray#585]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

# 简单描述这个 Bug:

离开位置喝杯水，回来一看Windows自动更新重启了，然后重启完成后就复现了。
>Windows幸福时刻（x）

# 如何复现这个 Bug：
> 我出现bug的流程
1. 更新Windows
2. 不重启
3. 等待自动重启
4. 重启完成后配置文件丢失

### 受影响的 Qv2ray 安装平台

- Windows

### 受影响的 Qv2ray 安装源

- Github Release qv2ray-2.5.0-win64.exe

### 已安装的插件 & 插件安装源：

无

### 首选项 -> 关于信息：

```
版本号: 2.5.0
内部版本号：
编译信息：Qv2ray built from Github Action
其它编译信息：qt5.14.2-83ade3638aee6588e32f43baf4c8c7820fd5e1f8-ci.windows-latest
```

**其他信息**

配置文件目前大小为18KB，以16进制编辑器打开后发现内容为18KB的0

**Comment by Qv2ray-dev** [comment]
收到，近期应该会修改文件保存方式

**Comment by MSG-maniac** [comment]
建议只进行一次读取，不要长时间占用文件打开。
写入后也关闭文件句柄

我这边遇到的问题就是同步盘不断同步失败，原因就是文件被占用，感谢发开者

**Comment by DuckSoft** [comment]
> 建议只进行一次读取，不要长时间占用文件打开。
> 写入后也关闭文件句柄
> 
> 我这边遇到的问题就是同步盘不断同步失败，原因就是文件被占用，感谢发开者

感谢你的宝贵建议！
cc @Qv2ray-dev

**Comment by Qv2ray-dev** [comment]
should be fixed in https://github.com/Qv2ray/Qv2ray/commit/6d788d04c5b50849e4fcdaf27196eb080930852d

**Comment by DuckSoft** [comment]
最新版本大概不会了。
暂时关闭～
