### ISSUE TITLE
功能建议：增加批量查看真实延迟

### ISSUE THREAD

**Issue by MSG-maniac** [Qv2ray/Qv2ray#587]
## 增加真实延迟

建议增加批量查看真实延迟，设置放在 “常规设置” -> 高级行为

[*] 定时测试真实延迟

并且真实延迟和定时测试延迟为互斥性

真是延迟产品逻辑：
1. 通过代理请求Google
2. 返回延迟数值

---
产品需求：

可以直观看到服务器的延迟情况和可用性。

感谢开发同学付出的努力

**Comment by DuckSoft** [comment]
你好，由于 Qv2ray 仅为 V2Ray 核心的一个前端，上述这些操作若要实现，将需要频繁地打开/关闭大量 V2Ray 核心进程，消耗大量系统资源，并且产生特征极其明显的数据流。

就开发者的角度来讲，实现这个功能不是非常困难；但就 Qv2ray 团队本身的价值观来说，我们可能不会加入这个功能。

建议：不要过度依赖延迟检定/可用性检定功能。

**Comment by MSG-maniac** [comment]
非常感谢您的回复

**Comment by csyezheng** [comment]
不能够批量测试真实延迟，还是不太方便，ICMP Ping/TCP Ping延迟低并不能说明可用于翻墙，没太大意义，建议还是增加批量测试真实延迟的功能
