### ISSUE TITLE
有关于设置代理这一块,开启v2系统代理,qq快速登录失效的问题！

### ISSUE THREAD

**Issue by X-Crack** [Qv2ray/Qv2ray#592]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:

这不属于bug，可以说是缺陷吧。

建议，增加一个设置选项。排除xxxxxxxxx地址进行代理，如下截图。

因为网页QQ快速登录是需要浏览器和本地qq进行通讯的。基于http协议。

但是v2阻断了带端口的地址。

![image](https://user-images.githubusercontent.com/45416520/81462241-b0eac100-91e3-11ea-9b20-bd2802209b62.png)

![image](https://user-images.githubusercontent.com/45416520/81462178-3a4dc380-91e3-11ea-8de8-73f36d40455b.png)

操作系统：Windows10
使用版本：最新发行版

顺便建议增加，系统关闭，软件没有关闭的时候，下次开机随着系统启动，这个几句代码就能实现。

避免关机时，或意外停电，导致代理异常，从而导致网页打不开等一系列原因！

**Comment by DuckSoft** [comment]
了解。已将“系统代理例外地址”并入系统代理重构进程中。
请耐心等待新版本～

ps: 开机随系统启动可直接在软件内进行设置。

**Comment by anaivebird** [comment]
请问修复了吗
