### ISSUE TITLE
界面优化杂论

### ISSUE THREAD

**Issue by Steve789** [Qv2ray/Qv2ray#593]
操作系统：ubuntu.
1、服务启动后右键菜单第一行不能切换为“断开服务”。
2、状态栏小图标系统代理建议增加一个当前状态的对勾。
最后，谢谢作者的奉献！

**Comment by DuckSoft** [comment]
你好，

1. 当前托盘菜单第一行是显示/隐藏 Qv2ray，断开链接在下面：
![图片](https://user-images.githubusercontent.com/7822648/81494610-c55eb480-92dc-11ea-8aab-9bd5fde9a707.png)

2. 系统代理正在重写。状态追踪见 #551。

项目组人手不足，加之近期忙于他事，进度缓慢，敬请谅解。
最后，感谢你的反馈～

**Comment by Steve789** [comment]
上述第一个我说的是主界面左边的服务器，不是托盘那个。

**Comment by DuckSoft** [comment]
> 上述第一个我说的是主界面左边的服务器，不是托盘那个。

你好，这是有意而为之的。节点列表无论右键点击哪个节点选择“连接”，都是断开当前连接，再连接指定节点。

**Comment by Steve789** [comment]
如果想要连接其他服务器，这样是合理的，但对于当前服务和者只有一个服务时，逻辑不恰，这是一个用户交互的问题。

**Comment by X-Crack** [comment]
其实托盘, 启用系统代理为绿色没问题，但是断开了系统代理应该为黄色，停止连接为红色。 这样刚好，哈哈哈。

**Comment by fantasynoff** [comment]
借楼,小建议(win)
* 左侧列表文字可以调小一点,机场多了翻起来很累
* 取消服务器排序(订阅中有剩余流量xx这种伪链接,顺序会乱)
* 可以加一个当日某服务器流量的统计,现在只有全部的,有时候需要考虑是否超量使用了
* 自动更新订阅
* 开机自启动,无法定位相对路径上的v2ray.exe

**Comment by rome753** [comment]
这个断开连接隐藏得很好。建议日志框做大一点铺满下面，日志一般都比较长。

**Comment by strsikin** [comment]
我也来补充一点

服务器列表里，鼠标可以拖动里面的某个链接，根据自己的需要来排序

**Comment by strsikin** [comment]
我也来补充一点

服务器列表里，鼠标可以拖动里面的某个链接，根据自己的需要来排序

**Comment by 2utv** [comment]
支持楼上左栏字体过大和日志过小的提法。
右侧配置、速度、日志可能的话，建议做成收起 / 展开的方式，要么鼠标随意调整间距。
其实速度图像意义不大，干脆去除。炫技还是蛮酷的。
其实分组意义也不大。最重要的就是区分国别，解锁geo-lock。再就是TG，编辑时加上 [US] [HK] [TG] 等等就好，排序还方便。

编辑标签有问题。尽管编辑中标签更改了，但主界面分组栏显示还是最初链接导入时的参数。这一点也很奇怪，标签载入的不是分组名，不是服务器名，却是”outBound_PROXY“，但分组栏显示的却往往是协议参数或混淆参数。

**Comment by Qv2ray-dev** [comment]
@2utv 欢迎加入 qv2ray 群进行讨论 @qv2ray

**Comment by EpLiar** [comment]
> 支持楼上左栏字体过大和日志过小的提法。
> 右侧配置、速度、日志可能的话，建议做成收起 / 展开的方式，要么鼠标随意调整间距。
> 其实速度图像意义不大，干脆去除。炫技还是蛮酷的。
> 其实分组意义也不大。最重要的就是区分国别，解锁geo-lock。再就是TG，编辑时加上 [US] [HK] [TG] 等等就好，排序还方便。
> 
> 编辑标签有问题。尽管编辑中标签更改了，但主界面分组栏显示还是最初链接导入时的参数。这一点也很奇怪，标签载入的不是分组名，不是服务器名，却是”outBound_PROXY“，但分组栏显示的却往往是协议参数或混淆参数。

云开发者的云编程

**Comment by cangyin** [comment]
> 支持楼上左栏字体过大和日志过小的提法。
> 右侧配置、速度、日志可能的话，建议做成收起 / 展开的方式，要么鼠标随意调整间距。
> 其实速度图像意义不大，干脆去除。炫技还是蛮酷的。
> 其实分组意义也不大。最重要的就是区分国别，解锁geo-lock。再就是TG，编辑时加上 [US] [HK] [TG] 等等就好，排序还方便。
> 
> 编辑标签有问题。尽管编辑中标签更改了，但主界面分组栏显示还是最初链接导入时的参数。这一点也很奇怪，标签载入的不是分组名，不是服务器名，却是”outBound_PROXY“，但分组栏显示的却往往是协议参数或混淆参数。

1、左侧分组栏字体大，鼠标滚动速度快，这个在 Windows 下体验的确不太顺滑。所以我也赞同改小字体，减慢滚动速度。至于日志栏的问题，其实你真想阅读日志，可以把窗口调整成这样
![image](https://user-images.githubusercontent.com/50256182/87231000-06ab3780-c3e6-11ea-9881-595dd8da417a.png)
2、右侧配置、速度、日志这三个栏目中，只有配置信息是不可收起的，另外两个都可收起/展开。
3、 从上图可以看出，现在的 Qv2ray 已经支持统计不同类型的流量，区分代理/直连流量之后，这个速度图像已经快很有参考价值了。因为它可以记录**过去一段时间**的速度信息。
4、分组意义不大？emmm，不好说，可能你的使用方式比较迥异。并且在我看来 **区分国别** 才是意义不大的特性，因为几乎所有我见过的机场节点的名字中都有标注国家/区域。你要说我见过的机场少，请看下图
![image](https://user-images.githubusercontent.com/50256182/87231143-3149c000-c3e7-11ea-8e10-a65bab58c434.png)

5、抱歉没看懂你前半句说的啥。但是这个 outBound_PROXY 改成当前连接的节点名，也是可有可无的特性。

**Comment by cangyin** [comment]
> 其实托盘, 启用系统代理为绿色没问题，但是断开了系统代理应该为黄色，停止连接为红色。 这样刚好，哈哈哈。

issue #745
