### ISSUE TITLE
2.5.0 抛弃 v1 vmess 导致机场链接无法导入

### ISSUE THREAD

**Issue by toaoman** [Qv2ray/Qv2ray#596]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:
不能解析v1版本的vmess(现在网络提供的V1版本的VMESS还是很普遍的)，手工转json能导入，但不能正常使用。

# 如何复现这个 Bug：

0. vmess://eyJwcyI6Ilt5b3VuZWVkLndpbl13ZW5lZWRmcmVlZG9tLm1sIiwiYWRkIjoid2VuZWVkZnJlZWRvbS5tbCIsInBvcnQiOiI0NDMiLCJpZCI6IjI2OTUxYjUwLTkyOTEtMTFlYS1iZTY1LTU2MDAwMmJmMDk1MyIsImFpZCI6IjAiLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwiaG9zdCI6Ii9hOWZRT2lCNS8iLCJ0bHMiOiJ0bHMifQ==
转json后为：
{
    "add": "weneedfreedom.ml",
    "aid": "0",
    "host": "/a9fQOiB5/",
    "id": "26951b50-9291-11ea-be65-560002bf0953",
    "net": "ws",
    "port": "443",
    "ps": "[youneed.win]weneedfreedom.ml",
    "tls": "tls",
    "type": "none"
}
1. https://s1.ax1x.com/2020/05/10/Y3ObKH.jpg
2. https://s1.ax1x.com/2020/05/10/Y3Oqrd.jpg
3. https://s1.ax1x.com/2020/05/10/Y3OLqA.jpg

### 相关截图或日志

<details>

 https://s1.ax1x.com/2020/05/10/Y3ObKH.jpg
https://s1.ax1x.com/2020/05/10/Y3Oqrd.jpg
https://s1.ax1x.com/2020/05/10/Y3OLqA.jpg
Qv2ray 日志：

```

</details>


## 系统信息 （请删掉不符合的项）

### 受影响的 Qv2ray 安装平台

- Linux
- macOS
- Windows

### 受影响的 Qv2ray 安装源

- ArchLinuxCN - 稳定版
- ArchLinuxCN - 开发版
- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版
- Fedora - 稳定版
- Fedora - 开发版
- openSUSE - 稳定版
- openSUSE - 开发版
- Flathub 包
- Snap 包
- Homebrew Cask
- Scoop
- 手动编译
- Github Release

### 已安装的插件 & 插件安装源：


### 首选项 -> 关于信息：

```
版本号: Qv2ray v2.5.0
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by DuckSoft** [comment]
你好，2.5.0 抛弃了对 v1 vmess 的支持，预计会在 2.6.0 加回。
若你确实需要 v1 vmess，请使用 2.4.1 愚人节版本（不保证稳定性）。

此外，VMess 经解码之后的 JSON 并不是实际的 V2Ray JSON 格式。请不要以这种方式导入。

**Comment by DuckSoft** [comment]
看起来这个订阅是来自机场上游的，你没有办法进行干预。
如果你确实着急，我可以根据你机场的现状给你定制特殊版本。

**Comment by toaoman** [comment]
> 看起来这个订阅是来自机场上游的，你没有办法进行干预。
> 如果你确实着急，我可以根据你机场的现状给你定制特殊版本。

不是很着急的事，现在主力还在用v2rayN,但是很看好这个qV2ray项目，希望早日普及成功。

**Comment by DuckSoft** [comment]
感谢支持。你可加入 Qv2ray 的 Telegram 群组 https://t.me/qv2ray 与用户、开发者们进行沟通，也可以选择订阅 https://t.me/qv2ray_outpost 频道关注 Qv2ray 的开发动向。由于项目主力只有三个人，还望耐心等待～

**Comment by 19317362** [comment]
建议要支持V1版本.服务器方给的是V1,用不成很无助
UBUNTU下 GUI 做得比较好用的就这个了

**Comment by DuckSoft** [comment]
@19317362 2.6.0：我们加回来了

**Comment by DuckSoft** [comment]
> 建议要支持V1版本.服务器方给的是V1,用不成很无助
> UBUNTU下 GUI 做得比较好用的就这个了

你好，我们已经在 Qv2ray 2.6.0 版本加回了对 VMess V1 版本的支持。目前的行为是，支持导入 VMess V1 链接，但导出时仍导出为 VMess V2 格式。Qv2ray 2.6.0 版本目前仍在测试中，若你是使用 snap（或者 Ubuntu 自带的使用 snap 的应用商店）安装的 Qv2ray，你可以通过使用 `snap install qv2ray --edge` 命令（有可能需要使用 sudo）安装并使用我们的预览版。若你使用的是 AppImage 等其他分发途径，直接下载并更新即可。

最后，不要回复这种坟帖，因为整个帖子的其他无关当事人都会收到一封邮件，会造成一定的干扰。
若有其它问题，欢迎加群 https://t.me/qv2ray 与我们讨论。
