### ISSUE TITLE
ssr怎么运行 ubuntu 18.04

### ISSUE THREAD

**Issue by zleiwang** [Qv2ray/Qv2ray#598]
ssr插件放到了plugins文件夹下，也按照json格式配置了，此处本地端口设置的1080，然后怎么运行呢？
我看到首选项下插件内核设置的栏目，端口号从15000起？这是啥意思？
入站设置处，有socks和http两个端口，跟我在json里设置的本地地址127.0.0.1，本地端口1080，有啥关系？

**Comment by DuckSoft** [comment]
你好，使用问题请加群讨论：https://t.me/qv2ray
