### ISSUE TITLE
Qv2ray not working on my manjaro linux machine

### ISSUE THREAD

**Issue by shenqizhi** [Qv2ray/Qv2ray#601]
Hi, developer

The Qv2ray is not working on my machine. 
I installed it by `yay -S qv2ray` successfully.  I check the time setting, and it is right. But I still  get a wrong connection message from Firefox. I'm sure the v2ray configures are working on my Windows PC.  
Can you HELP me?

Thank you! 

issue info:
![image](https://user-images.githubusercontent.com/32361081/81533004-fbad3a00-9397-11ea-89b7-8f7fd723b8fd.png)

My system info:
![image](https://user-images.githubusercontent.com/32361081/81532889-c274ca00-9397-11ea-8976-c74d8856be75.png)

Firefox setting:
![image](https://user-images.githubusercontent.com/32361081/81532345-cf44ee00-9396-11ea-92cd-186c9b1d5e32.png)

Qv2ray general setting:
![image](https://user-images.githubusercontent.com/32361081/81532434-f13e7080-9396-11ea-8e1c-ba7badb5f9ae.png)

Qv2ray inbound setting:
![image](https://user-images.githubusercontent.com/32361081/81532482-06b39a80-9397-11ea-9188-4670efa5a776.png)

Qv2ray kernel setting:
![image](https://user-images.githubusercontent.com/32361081/81532760-85103c80-9397-11ea-8e88-000f02cdeb57.png)

**Comment by DuckSoft** [comment]
You configuration looks clean and nice. 

Did you notice the output of your log window, and the change of that speed curve?
![图片](https://user-images.githubusercontent.com/7822648/81534764-264cc200-939b-11ea-8ae9-9bf4194de731.png)

What have this told you?

**Comment by DuckSoft** [comment]
BTW for usage problems, why not join Qv2ray User Group @ Telegram:
 - https://t.me/qv2ray

**Comment by shenqizhi** [comment]
Hi, DuckSoft
Thanks for your respond
The log like below. Everything looks normal. But the speed is zero!

![image](https://user-images.githubusercontent.com/32361081/81538982-18e70600-93a2-11ea-8308-6b8976b2a0e8.png)

**Comment by Qv2ray-dev** [comment]
Marked as solved, issue closing.
