### ISSUE TITLE
软件没有托盘

### ISSUE THREAD

**Issue by l17es** [Qv2ray/Qv2ray#602]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:
软件已打开，但是托盘找不到图标

# 如何复现这个 Bug：

1. 
2. 
3. 
4. 

### 相关截图或日志
![image](https://user-images.githubusercontent.com/20061353/81628239-abcf8100-9432-11ea-822a-2aaed8703d50.png)

<details>

```
Qv2ray 日志：


```

</details>

### 受影响的 Qv2ray 安装平台

- Linux
- macOS
- Windows

### 受影响的 Qv2ray 安装源

- ArchLinuxCN - 稳定版
- ArchLinuxCN - 开发版
- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版
- Fedora - 稳定版
- Fedora - 开发版
- openSUSE - 稳定版
- openSUSE - 开发版
- Flathub 包
- Snap 包
- Homebrew Cask
- Scoop
- 手动编译
- Github Release

### 首选项 -> 关于信息：

```
版本号: 
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**
![image](https://user-images.githubusercontent.com/20061353/81628304-e3d6c400-9432-11ea-810b-8c6614cf2a77.png)

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by DuckSoft** [comment]
无法复现。看来是 Buggy Deepin 的问题。
请向上游反馈。

**Comment by ChungZH** [comment]
![image](https://user-images.githubusercontent.com/42088872/81643357-04654500-9458-11ea-8199-50a1a8d32bf8.png)

Arch + DDE V20

但是托盘图标正常。

:smile:

**Comment by DuckSoft** [comment]
> ![image](https://user-images.githubusercontent.com/42088872/81643357-04654500-9458-11ea-8199-50a1a8d32bf8.png)
> 
> Arch + DDE V20
> 
> 但是托盘图标正常。
> 
> smile

@l17es 看来不是 Qv2ray 本身的问题。请好好检查自己的系统配置。
本问题先行关闭。

**Comment by DuckSoft** [comment]
参考链接：
- Arch Linux CN Telegram 讨论群组：https://t.me/archlinuxcn_group
- Deepin CN Telegram 讨论群组：https://t.me/deepin_cn
- Arch Wiki 上的 Deepin Desktop Environment 页面：https://wiki.archlinux.org/index.php/Deepin_Desktop_Environment
- Deepin Bug Tracker：https://github.com/linuxdeepin/developer-center/issues

**Comment by DuckSoft** [comment]
另外，欢迎加入 Qv2ray User Group @ Telegram：
https://t.me/qv2ray
