### ISSUE TITLE
Empty Speed Graph Issue

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#603]
@DuckSoft 
![image](https://user-images.githubusercontent.com/24750337/81653479-611c2c00-9467-11ea-892e-8f010b78de6f.png)

Why my speed graph is always empty  even though Log showing connection detail?

![image](https://user-images.githubusercontent.com/24750337/81653570-87da6280-9467-11ea-985b-c5b9344e4d44.png)

_Originally posted by @iamwwc in https://github.com/Qv2ray/Qv2ray/issues/397#issuecomment-627172982_

**Comment by DuckSoft** [comment]
请提供具体的、有助于我们重现该问题的信息，例如操作系统、操作系统版本、Qv2ray 版本、相关设置截图等。

 @iamwwc

**Comment by iamwwc** [comment]
都在这里，回复效率真高！

![image](https://user-images.githubusercontent.com/24750337/81654411-236bd300-9468-11ea-9a9f-bdeb06fb9c80.png)
![image](https://user-images.githubusercontent.com/24750337/81654569-3b435700-9468-11ea-9701-ad2dd968978b.png)
![image](https://user-images.githubusercontent.com/24750337/81655019-88272d80-9468-11ea-8327-f2e07d40c43e.png)
![image](https://user-images.githubusercontent.com/24750337/81655059-8f4e3b80-9468-11ea-9b2c-440e5898dbd0.png)
![image](https://user-images.githubusercontent.com/24750337/81655082-92492c00-9468-11ea-85a9-eca85e91bc57.png)
![image](https://user-images.githubusercontent.com/24750337/81655096-94ab8600-9468-11ea-9bd8-82ec1144b809.png)
![image](https://user-images.githubusercontent.com/24750337/81655118-97a67680-9468-11ea-90a9-00b7cc77d120.png)

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/81655432-d0465000-9468-11ea-9c9d-a8aab8b58a23.png)
API Subsystem is not enabled. Please enable this and restart Qv2ray.

**Comment by DuckSoft** [comment]
What about now? Any Updates?

**Comment by iamwwc** [comment]
@DuckSoft 可以了，十分感谢，可以将其写入文档，因为从API这个词里面推不出和speed graph的关系，所以有人（比如我）就会自以为是的关掉

没想到软件自身也会使用API port，名字会被误解成给第三方准备的

**Comment by DuckSoft** [comment]
> @DuckSoft 可以了，十分感谢，可以将其写入文档，因为从API这个词里面推不出和speed graph的关系，所以有人（比如我）就会自以为是的关掉
> 
> 没想到软件自身也会使用API port，名字会被误解成给第三方准备的

已在 Pull Request #604 中修复。感谢你的反馈。
