### ISSUE TITLE
Windows 7 使用 PAC 插件导致崩溃一例

### ISSUE THREAD

**Issue by 1353604736** [Qv2ray/Qv2ray#607]
![图片](https://user-images.githubusercontent.com/7822648/81797577-9137fd80-9541-11ea-96e8-4f98eb36d8f2.png)
![图片](https://user-images.githubusercontent.com/7822648/81797611-9bf29280-9541-11ea-9254-802b36820bf7.png)

**Comment by DuckSoft** [comment]
你好，请提供能让我们重现此问题的详细信息。
例如，操作系统，操作系统版本，Qv2ray 版本，安装了哪些插件等。

**Comment by DuckSoft** [comment]
此外，你说的崩溃是什么崩溃？是 Qv2ray 软件自身闪退，还是说，Qv2ray 弹出提示框说：V2Ray 核心已崩溃（如下图所示）？
![图片](https://user-images.githubusercontent.com/7822648/81797210-0e16a780-9541-11ea-881a-8d696c7a46e1.png)

**Comment by DuckSoft** [comment]
最后，若在此提交 Issue，请务必按 Issue 模板格式进行反馈。
我们 Qv2ray 项目组会认真对待每一个 Issue，前提是用户也要认真填写他们的 Issue。

以上。

**Comment by MarksonHon** [comment]
在文档里面有的东西就别在这问了

**Comment by 1353604736** [comment]
windows7系统64，2.5.0.5225，截图 链接: https://pan.baidu.com/s/1FAyRt46plqtTTUPS1aYzNg 提取码: 1234

**Comment by DuckSoft** [comment]
你好，删除 PAC 插件即可解决。

**Comment by DuckSoft** [comment]
在此重申：PAC 插件仅用于自己已经维护了巨量 PAC 规则、迁移有困难的的高级用户。
分流功能，Qv2ray 本身自带，无需 PAC 插件协助。

**Comment by DuckSoft** [comment]
https://qv2ray.github.io/getting-started/step5.html#%E8%B0%83%E6%95%B4%E8%B7%AF%E7%94%B1%E6%96%B9%E6%A1%88

建议仔细阅读文档，不要安装不必要的功能。

**Comment by 1353604736** [comment]
> 你好，删除 PAC 插件即可解决。

禁用PAC插件后，所有崩溃问题消失，问题已解决 ！！谢谢
