### ISSUE TITLE
配置高级路由提示：country not found:APPIUM.IO

### ISSUE THREAD

**Issue by chazhongbao** [Qv2ray/Qv2ray#610]
# 简单描述这个 Bug:
在【首选项--高级路由设置】中配置域名，重新连接，提示country not found:APPIUM.IO

# 如何复现这个 Bug：

1. 启动软件
2. 在【首选项--高级路由设置--域名--代理】输入框内填入：geosite:appium.io
3.重新连接服务器
4、弹出报错提示

### 相关截图或日志
 
Qv2ray 日志：

![image](https://user-images.githubusercontent.com/43258262/82006985-a5900d80-969b-11ea-9d03-235b1970c68b.png)
 

</details>

## 系统信息 （请删掉不符合的项）
window 10专业版

### 首选项 -> 关于信息：

```
版本：2.5.0
构建时间Apr272020122153
编译信息Qv2 ray built from Github Action
额外编译信息qt5.142-16b22386257916ed9de0b77845c875b062b5776- ci. windows-latest
插件接口版本：1
```

**Comment by DuckSoft** [comment]
https://v2ray.com/chapter_02/03_routing.html#ruleobject

**Comment by DuckSoft** [comment]
`domain:appium.io`

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/82007416-bee58980-969c-11ea-85d3-736e5f3261b3.png)
