### ISSUE TITLE
centos7不能使用这个AppImage

### ISSUE THREAD

**Issue by evilemperorF** [Qv2ray/Qv2ray#611]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:

[root@localhost ~]# chmod a+x Qv2ray-refs.tags.v1.99.6-linux.AppImage 
[root@localhost ~]# ./Qv2ray-refs.tags.v1.99.6-linux.AppImage 
fuse: device not found, try 'modprobe fuse' first

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
[root@localhost ~]#

**Comment by DuckSoft** [comment]
你好，看起来你的操作系统不支持 AppImage。
转交给 @ymshenyu 。

**Comment by ymshenyu** [comment]
@evilemperorF 请使用[snap](https://snapcraft.io/docs/installing-snap-on-centos), 除此之外无解。

**Comment by Qv2ray-dev** [comment]
@evilemperorF Qv2ray.AppImage --appimage-extract

**Comment by evilemperorF** [comment]
> @evilemperorF Qv2ray.AppImage --appimage提取

这个我试过了，并不能安装成功

**Comment by DuckSoft** [comment]
你好，你的操作系统过于古老，像 @ymshenyu 所说，除了使用 Snap 方式安装之外，无解。

**Comment by DuckSoft** [comment]
https://qv2ray.github.io/getting-started/step1.html#snapcraft
请参考这里。

**Comment by evilemperorF** [comment]
@DuckSoft 执行了snap install qv2ray
error: system does not fully support snapd: cannot mount squashfs image using "squashfs": mount:
       /tmp/sanity-squashfs-433369878: failed to setup loop device: No such file or directory

**Comment by DuckSoft** [comment]
下面是 Snap 官方提供的安装 FUSE 的方法：

```bash
yum --enablerepo=epel -y install fuse-sshfs # install from EPEL
user="$(whoami)"
usermod -a -G fuse "$user" 
```

**Comment by ymshenyu** [comment]
@evilemperorF 请打开centos 7 squashfs模块 详情[请见](https://forums.centos.org/viewtopic.php?t=71485)

**Comment by DuckSoft** [comment]
若仍有问题，请加入我们的 Telegram 讨论群与我们交流：https://t.me/qv2ray
另外，强烈建议你换一个更为现代的 Linux 桌面系统使用我们的软件。
感谢你对 Qv2ray 的支持。
