### ISSUE TITLE
IDM无法下载YouTube视频？

### ISSUE THREAD

**Issue by 1353604736** [Qv2ray/Qv2ray#612]
换ssr就可以正常下载

**Comment by 1353604736** [comment]
网页可以访问

**Comment by DuckSoft** [comment]
这是旧版的 Bug，已经在最新版本中修复。
暂时你可以通过这个方式解决问题：
![图片](https://user-images.githubusercontent.com/7822648/82055737-87ee9280-96f3-11ea-800d-95335d9955f2.png)

**Comment by DuckSoft** [comment]
若还有什么不明白的，欢迎加 Telegram 群 https://t.me/qv2ray 交流。

**Comment by conray002** [comment]
突然之间发现，IDM下载youtube的时候，提示无下载。更新了IDM各种版本软件，设置了代理，各种尝试还是不行。

后来无意中发现，原来是chrome的广告插件屏蔽了youtube的广告。

下载youtube视频，看一看youtube的广告合情合理。所以大家知道怎么办了。把youtube放到广告的白名单上（之后停止运行屏蔽软件，我的是Adguard）即可解决。

最后还是回到原来的层面来看这个问题，世间万物为一个整体，你中有我，我中有你。任何人在特别极端的情况下都不能形成合理的稳定结构。

捡别人家的鸡蛋，先喂点粮食不过分吧。

下载最新的IDM破解版本https://www.cmdpe.com/post/53.html

https://macace.lanzouc.com/b0131835c
导出代码：29cx
