### ISSUE TITLE
V2ray assets 路径不可用

### ISSUE THREAD

**Issue by DanLiu0809** [Qv2ray/Qv2ray#614]
-  **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

# 简单描述这个 Bug:
在配置v2ray内核时提示“V2ray assets 路径不可用”
![image](https://user-images.githubusercontent.com/40844774/82112795-0e9e8080-9783-11ea-870d-89819564ab7d.png)

# 如何复现这个 Bug：

1. 操作系统是win10专业版，使用的包是Qv2ray.v2.5.0.Windows-x64.7z
![image](https://user-images.githubusercontent.com/40844774/82112809-44dc0000-9783-11ea-9578-7ef412a7a9af.png)
2. 解压后放在非系统盘内，启动.exe文件
3. 设置订阅并成功，进入首选项并设置v2ray内核
4. 设置完成路径后报错
![image](https://user-images.githubusercontent.com/40844774/82112837-81a7f700-9783-11ea-81cf-a2efbcb19784.png)

### 如果是连接问题，在其他 v2ray 客户端里出现过吗？ 
在相同Windows系统情况下，使用2.3.1版本，无法正常加载订阅地址
我在Ubuntu 16.04 运行，使用2.3.1版本，使用正常且节点可用

### 受影响的 Qv2ray 安装平台
Windows 10 专业版

### 首选项 -> 关于信息：

```
版本号: 2.5.0
内部版本号：
编译信息：Qv2ray built from Github Action
其它编译信息：qt5.14.2-16b22386257916edf9de0b77845c875b062b5776-ci.windows-latest
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
放在非系统盘的无中文目录中也是一样的情况，但是没有测试放在C盘中是否可行

**Comment by TheWanderingCoel** [comment]
@DanLiu0809 是目录啊，不要选中exe

**Comment by DanLiu0809** [comment]
@TheWanderingCoel 如果不选中exe，那一项该怎么填呢？

**Comment by GoldJohnKing** [comment]
参考：
![image](https://user-images.githubusercontent.com/26923626/82113019-31ca2f80-9785-11ea-950f-a3c9ae51a14c.png)

**Comment by ymshenyu** [comment]
@DanLiu0809 请阅读[wik](https://qv2ray.github.io/getting-started/step2.html#%E4%B8%8B%E8%BD%BD-v2ray-%E6%A0%B8%E5%BF%83%E6%96%87%E4%BB%B6)i
