### ISSUE TITLE
Fedora 32下系统代理失效

### ISSUE THREAD

**Issue by catfishjones** [Qv2ray/Qv2ray#620]
# 简单描述这个 Bug:
今天我刚从Fedora31升级到Fedora32, 31下系统代理正常使用，32下系统代理失效，Firefox中设置使用系统代理无法翻墙，设置手动代理可以使用。请问是Fedora32的某个更新把系统代理功能弄坏了吗？使用的是最新的Qv2ray 2.5.0

**Comment by DuckSoft** [comment]
没有足够的信息量。你所使用的桌面系统为？

**Comment by catfishjones** [comment]
KDE

**Comment by catfishjones** [comment]
![Screenshot_20200518_234943](https://user-images.githubusercontent.com/35189999/82233753-0f8e0880-9963-11ea-92b7-95d563644f24.png)
![Screenshot_20200518_235013](https://user-images.githubusercontent.com/35189999/82233763-13218f80-9963-11ea-9067-74afb2ea8b58.png)
![Screenshot_20200518_235022](https://user-images.githubusercontent.com/35189999/82233767-14eb5300-9963-11ea-8cce-c69b2a528e4b.png)
![Screenshot_20200518_235036](https://user-images.githubusercontent.com/35189999/82233777-174dad00-9963-11ea-914c-530eaf54e920.png)
![Screenshot_20200518_235101](https://user-images.githubusercontent.com/35189999/82233788-1a489d80-9963-11ea-8bb8-9c9da58e3d90.png)
![Screenshot_20200518_235240](https://user-images.githubusercontent.com/35189999/82233795-1caaf780-9963-11ea-8d57-89f738694ea1.png)

**Comment by catfishjones** [comment]
![Screenshot_20200518_235726](https://user-images.githubusercontent.com/35189999/82234000-61369300-9963-11ea-903b-497c424fc972.png)

**Comment by DuckSoft** [comment]
你好，KDE 的系统代理基本上没有软件会遵守。
建议使用 SwitchyOmega 之类的浏览器插件，从源头上解决问题～

**Comment by catfishjones** [comment]
没事了切了一下DE现在好了，是个glitch

**Comment by arkylin** [comment]
> 没事了切了一下DE现在好了，是个glitch

请问是怎么解决的，现在也遇到了相同的问题，难受

**Comment by catfishjones** [comment]
> 
> 
> > 没事了切了一下DE现在好了，是个glitch
> 
> 请问是怎么解决的，现在也遇到了相同的问题，难受

切换回gnome，在gnome里面打开用一会，然后再切回kde
