### ISSUE TITLE
无法启动 v2ray核心可执行文件没找到

### ISSUE THREAD

**Issue by easyasd** [Qv2ray/Qv2ray#623]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:

你好，我是直接安装了2.5.0版本的exe文件，出现这个问题，我该怎么把那个核心文件添加进去啊

# 如何复现这个 Bug：

1. 
2. 
3. 
4. 

### 相关截图或日志

<details>

```
Qv2ray 日志：


```

</details>

### 受影响的 Qv2ray 安装平台

- Linux
- macOS
- Windows

### 受影响的 Qv2ray 安装源

- ArchLinuxCN - 稳定版
- ArchLinuxCN - 开发版
- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版
- Fedora - 稳定版
- Fedora - 开发版
- openSUSE - 稳定版
- openSUSE - 开发版
- Flathub 包
- Snap 包
- Homebrew Cask
- Scoop
- 手动编译
- Github Release

### 首选项 -> 关于信息：

```
版本号: 
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by Qv2ray-dev** [comment]
@easyasd 有仔细阅读过文档吗？ https://qv2ray.github.io

**Comment by ymshenyu** [comment]
请看[wiki](https://qv2ray.github.io/getting-started/step2.html)
