### ISSUE TITLE
Snap 代理？

### ISSUE THREAD

**Issue by TsingWei** [Qv2ray/Qv2ray#624]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

# 简单描述这个 Bug:
在Ubuntu上只要运行过Qv2ray一次后，无论是否关闭Qv2ray，是否手动将系统设置中的代理关闭，在应用商店中都无法下载安装软件，但是搜索还是可以的。
在三台设备上都有这个问题。（包括一台ARM架构的）
2.3.1，2.5.0都有这个问题

软件商店的提示信息为
> unsupported proxy configured: localhost://10888  

因为一般端口号和前面的冒号间是不会有双斜杠的，所以我怀疑可能是Qv2ray把系统哪里的代理配置搞错了
### 如果是连接问题，在其他 v2ray 客户端里出现过吗？ 
由于ubuntu上只有Qv2ray有图形界面，所以没有尝试其他的。

### 受影响的 Qv2ray 安装平台

- Linux

### 受影响的 Qv2ray 安装源

- Snap 包
- Github Release

**Comment by DuckSoft** [comment]
正在下载 Ubuntu 18.04 以复现

**Comment by ymshenyu** [comment]
![image](https://user-images.githubusercontent.com/39402395/82555880-3c2c6500-9b9b-11ea-86a4-1f4c4d53b10b.png)
请确保你填写了正确的代理设置，打开Qv2ray的设置系统代理是没有办法影响snap store的。

**Comment by TsingWei** [comment]
![Screenshot from 2020-05-21 20-03-15](https://user-images.githubusercontent.com/28723968/82557486-67648380-9b9e-11ea-8129-d9b9643d27fd.png)

**Comment by TsingWei** [comment]
ctl使用snap是没问题的，就是图形界面有问题。

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/82558071-7f88d280-9b9f-11ea-9ea7-fcbe7ff2e7f3.png)

**Comment by TsingWei** [comment]
![Screenshot from 2020-05-21 20-18-01](https://user-images.githubusercontent.com/28723968/82558435-2ff6d680-9ba0-11ea-89c8-7ee29e3e18f7.png)

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/82559168-b5c75180-9ba1-11ea-9610-bbb761c154bb.png)
我这没啥问题，很稳定？能否提供你安装系统所使用的 ISO 的文件名？

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/82559302-f7f09300-9ba1-11ea-9b63-21aac140ac16.png)
我觉得，是你的其他配置问题……

**Comment by TsingWei** [comment]
安装包是下载自清华tuna提供的"常用发行版iso: Ubuntu18.04.4
可是真的就是刚刚安装的系统，先从软件商店装了个vscode，没问题，再安装Qv2ray运行后就木大了，代理配置也是Qv2ray自动配好的我没动。 另：我是把整个v2ray-core文件夹拷入vcore目录里的，不知正常来说是怎样操作？

**Comment by DuckSoft** [comment]
正在下载你所说的 ISO 以重现问题。

---

> 我是把整个v2ray-core文件夹拷入vcore目录里的，不知正常来说是怎样操作？
这样即可。

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/82563036-e959aa00-9ba8-11ea-973c-fecfa2f29924.png)
装好了。开幕雷击，我什么都没做。现在用 snap 装一下 Qv2ray 试试看。

**Comment by TsingWei** [comment]
> ![图片](https://user-images.githubusercontent.com/7822648/82563036-e959aa00-9ba8-11ea-973c-fecfa2f29924.png)
> 装好了。开幕雷击，我什么都没做。现在用 snap 装一下 Qv2ray 试试看。

这个可能是运营商网络问题，比如dns污染什么的，我这边地处深圳+教育网，可能裸连比较友好

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/82564855-10fe4180-9bac-11ea-8d3b-2107fbd1c8f8.png)
So far so good.

**Comment by TsingWei** [comment]
安装能成功么？我重启一次商店后就不能安装了。当然搜索还是正常的，CLI的snap也正常。就GUI不能安装。

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/82565185-941f9780-9bac-11ea-9816-83d356b7ebff.png)
安装非常成功……

**Comment by DuckSoft** [comment]
我重启一次商店，再换一个软件安装试试。

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/82565333-d3e67f00-9bac-11ea-8c70-31e141774eec.png)
![图片](https://user-images.githubusercontent.com/7822648/82565358-db0d8d00-9bac-11ea-9b72-190149838da7.png)
![图片](https://user-images.githubusercontent.com/7822648/82565407-f5476b00-9bac-11ea-8892-a096312e9e75.png)
![图片](https://user-images.githubusercontent.com/7822648/82565446-07290e00-9bad-11ea-87f9-d3c43d01a86a.png)
![图片](https://user-images.githubusercontent.com/7822648/82565502-2031bf00-9bad-11ea-8b6b-7f60eb431321.png)
安装非常成功，没有任何毛病，软件也能正常运行。

**Comment by TsingWei** [comment]
鹅。辛苦了，看来是我自己什么地方出了差错。我自己排查下吧。

**Comment by DuckSoft** [comment]
我觉得……你可能是做了某些神秘操作，导致你的整个系统不正常的。
Kubuntu 18.04 测试正常，按照你所说 Ubuntu 18.04.4 也测试正常，应该不是 Qv2ray 的问题。

若有其它问题，欢迎加群 https://t.me/qv2ray 与我们一起讨论。
本 Issue 先行关闭。

**Comment by TsingWei** [comment]
我也发现了，在我的测试机这里退出Qv2ray后就能正常使用了，但是开着Qv2ray的话就会出错。
原来的机子应该是为了解决这个问题动过一些配置导致Qv2ray退出后仍然出错。

**Comment by TsingWei** [comment]
> 我觉得……你可能是做了某些神秘操作，导致你的整个系统不正常的。
> Kubuntu 18.04 测试正常，按照你所说 Ubuntu 18.04.4 也测试正常，应该不是 Qv2ray 的问题。
> 
> 若有其它问题，欢迎加群 https://t.me/qv2ray 与我们一起讨论。
> 本 Issue 先行关闭。

看图片里应该是退出Qv2ray后进行的操作，你打开Qv2ray在安装个东西试试，应该可以复现。当然现在对我来说这个问题是解决了（关掉Qv2ray就好了）。

**Comment by DuckSoft** [comment]
图片中没有退出 Qv2ray，顶栏图标消失是 GNOME 的 bug。

**Comment by TsingWei** [comment]
ok，那应该是我的神秘操作了

**Comment by xxyangyoulin** [comment]
snap无法和命令行设置http_proxy，以及系统设置全局代理正常工作。这个不是Qv2ray的原因。
snap要这样设置才能正常工作
`
$ sudo snap set system proxy.http="http://<proxy_addr>:<proxy_port>"
$ sudo snap set system proxy.https="http://<proxy_addr>:<proxy_port>"
`
并且snap只代理走它服务器的链接，其他链接都会直连，BUG

**Comment by Guicai996** [comment]
请问解决了吗？出现同样问题，而且换了系统后还是出现。
