### ISSUE TITLE
未知原因无法更新订阅

### ISSUE THREAD

**Issue by 911211606** [Qv2ray/Qv2ray#625]
我不确定是什么原因，同样的链接，其他的软件可以订阅成功，Qv2ray不行

**Comment by Qv2ray-dev** [comment]
你好，能否提供更加详细的信息？

**Comment by DuckSoft** [comment]
你好，请提供下面这些信息，我们需要这些信息以重现你所说的问题：
1. 操作系统/版本。例：Windows 10 1903
2. Qv2ray 版本。例：2.5.0
3. 您的订阅类型。例：V2Ray / Trojan / SSR / 其他

**Comment by ruvuoai** [comment]
我也遇到了订阅的问题。
在Qv2ray中，Trojan类型的订阅链接订阅失败。
同一个订阅链接用Trojan-Qt5是可以订阅成功的

**Comment by DuckSoft** [comment]
你好，可否提供订阅链接，或者用网页浏览器直接打开订阅链接，将其中的敏感内容抹去之后再发上来？

> 我也遇到了订阅的问题。
> 在Qv2ray中，Trojan类型的订阅链接订阅失败。
> 同一个订阅链接用Trojan-Qt5是可以订阅成功的

**Comment by MarksonHon** [comment]
建议你报上 Qv2ray 版本、Qv2ray Trojan 插件版本，方便开发者解决问题。

**Comment by ruvuoai** [comment]
> 你好，可否提供订阅链接，或者用网页浏览器直接打开订阅链接，将其中的敏感内容抹去之后再发上来？
> 
> > 我也遇到了订阅的问题。
> > 在Qv2ray中，Trojan类型的订阅链接订阅失败。
> > 同一个订阅链接用Trojan-Qt5是可以订阅成功的

因涉及敏感信息，订阅信息已经发送到您github资料中的gmail邮箱 @DuckSoft

**Comment by 911211606** [comment]
就是Trojan订阅链接，开始我以为是订阅链接的事情 结果我的网页可以打开，其他的订阅链接同样可以订阅，vmess链接就没这问题。但是你一开始装好软件 装好插件的时候 Trojan订阅链接是没有问题的。我重新安装了 结果好了 不知道以后还会不会遇到哦

**Comment by 911211606** [comment]
操作系统/版本。Windows 7
Qv2ray 版本。2.5.0
订阅类型。Trojan

**Comment by DuckSoft** [comment]
你好，经查，你所发送的邮件的订阅 Base64 是损坏的。请核对完整性再发送，或者你可以直接发送订阅链接。如下图：
![图片](https://user-images.githubusercontent.com/7822648/82571325-63902b80-9bb5-11ea-99e3-caf854f133ba.png)


> > 你好，可否提供订阅链接，或者用网页浏览器直接打开订阅链接，将其中的敏感内容抹去之后再发上来？
> > > 我也遇到了订阅的问题。
> > > 在Qv2ray中，Trojan类型的订阅链接订阅失败。
> > > 同一个订阅链接用Trojan-Qt5是可以订阅成功的
> 
> trojan 插件文件 ：QvTrojanPlugin.v1.0.1.Windows-x64.dll
> 因涉及敏感信息，订阅信息已经发送到您github资料中的gmail邮箱 @DuckSoft

**Comment by DuckSoft** [comment]
> > 你好，可否提供订阅链接，或者用网页浏览器直接打开订阅链接，将其中的敏感内容抹去之后再发上来？
> > > 我也遇到了订阅的问题。
> > > 在Qv2ray中，Trojan类型的订阅链接订阅失败。
> > > 同一个订阅链接用Trojan-Qt5是可以订阅成功的
> 
> trojan 插件文件 ：QvTrojanPlugin.v1.0.1.Windows-x64.dll
> 因涉及敏感信息，订阅信息已经发送到您github资料中的gmail邮箱 @DuckSoft

@ruvuoai 测试结果：你上游机场的订阅链接被墙了。
请使用首选项中的“Qv2ray代理”功能为订阅设置代理再更新。
![图片](https://user-images.githubusercontent.com/7822648/82573108-f03be900-9bb7-11ea-994b-48692170f1fd.png)

**Comment by DuckSoft** [comment]
> 就是Trojan订阅链接，开始我以为是订阅链接的事情 结果我的网页可以打开，其他的订阅链接同样可以订阅，vmess链接就没这问题。但是你一开始装好软件 装好插件的时候 Trojan订阅链接是没有问题的。我重新安装了 结果好了 不知道以后还会不会遇到哦

收到。近期众所周知原因，可能订阅上游不是很稳定。
暂且关闭本 Issue。有其他问题，欢迎加群讨论：
https://t.me/qv2ray
