### ISSUE TITLE
【建议】关于流量统计数据的统计范围

### ISSUE THREAD

**Issue by gears233** [Qv2ray/Qv2ray#626]
Windows 平台下，软件右下角有个流量统计。
但是我观察下来貌似是将 代理和直连的流量都纳入到了统计范围内，建议能否添加个设置选项，让用户选择只统计代理流量功能。

PS：windows 平台下感觉软件界面和易用性方面做得真的很不错了，感谢作者的付出！

**Comment by DuckSoft** [comment]
你好，流量统计功能由上游 V2Ray 核心提供。上游没有给我们分出站统计的接口，因而这个要求无法实现，这也是 Qv2ray 至今没有开发更加高级的流量统计功能的原因之一。你可以向上游 V2Ray Core (https://github.com/v2ray/v2ray-core) 项目进行反馈，以期尽速得到解决。

感谢你对 Qv2ray 项目的支持。

**Comment by DuckSoft** [comment]
欢迎加群 https://t.me/qv2ray 以与 Qv2ray 的用户/开发者们交流。
本 Issue 即将关闭。
