### ISSUE TITLE
建议：v2ray核心路径支持相对变量

### ISSUE THREAD

**Issue by glsname** [Qv2ray/Qv2ray#630]
# 问题
目前的核心路径是固定死的，只能在首次运行时可以自动检测填充。再次移动位置或者打包分发时，路径固定不变使得核心查找失败，无法成功运行。

# 当下权宜之计
把config目录下的Qv2ray.conf删除后打包，移动路径或更换电脑后才自动检测生成正确的核心路径。

# 期望
后续版本加入相对变量检测机制

**Comment by Qv2ray-dev** [comment]
其实是支持相对路径的，你可以试试

**Comment by glsname** [comment]
能否在后续的版本中更改下机制：**默认检测填充为相对路径**。用户自己选择路径时则为全路径！

**Comment by glsname** [comment]
> 其实是支持相对路径的，你可以试试

测试了一下是可以的。

能否在后续的版本中更改下机制：**默认填充为相对路径**。如用户自己选择路径时则为全路径！

**Comment by DuckSoft** [comment]
> > 其实是支持相对路径的，你可以试试
> 
> 测试了一下是可以的。
> 
> 能否在后续的版本中更改下机制：**默认填充为相对路径**。如用户自己选择路径时则为全路径！

你好，你可以帮我们实现一下，发一个 Pull Request，感谢哦
