### ISSUE TITLE
加入IDM之类的软件代理下载

### ISSUE THREAD

**Issue by Lancelatz** [Qv2ray/Qv2ray#631]
有的时候会使用IDM下载YTB视频，貌似不能调用，也没有PAC或者全局模式的选项，希望加入这个功能

**Comment by DuckSoft** [comment]
IDM 问题：
![图片](https://user-images.githubusercontent.com/7822648/83059713-ea994400-a08c-11ea-85dc-e7ce0fa99108.png)

默认绕过中国大陆，不需要 PAC。要开全局，请在首选项禁用绕过中国大陆即可。

**Comment by DuckSoft** [comment]
另外，若你还没有读过官方入门指引，建议通读。
https://qv2ray.github.io/getting-started

**Comment by Lancelatz** [comment]
好的，非常感谢！我还是按照之前的代理软件设置，所以没成功，我读读入门指引
