### ISSUE TITLE
mac使用V2ray直接闪退毫无提示

### ISSUE THREAD

**Issue by vcan** [Qv2ray/Qv2ray#632]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:

崩溃

# 如何复现这个 Bug：

1. mac下配置好v2ray core测试通过后
2. 输入vmss地址，点击连接直接闪退？？？
3. 每次必现
4. 

### 相关截图或日志

<details>

```
Qv2ray 日志：


```

</details>

### 受影响的 Qv2ray 安装平台

- Linux
- macOS √
- Windows

### 受影响的 Qv2ray 安装源

- ArchLinuxCN - 稳定版
- ArchLinuxCN - 开发版
- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版
- Fedora - 稳定版
- Fedora - 开发版
- openSUSE - 稳定版
- openSUSE - 开发版
- Flathub 包
- Snap 包
- Homebrew Cask
- Scoop
- 手动编译
- Github Release

### 首选项 -> 关于信息：

```
版本号: 
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
体验太糟糕了，哥哥们多做点测试再发版吧，这么折腾是真的浪费时间

**Comment by vcan** [comment]
不知道是不是因为端口占用导致的，端口占用弹个窗口提示下不行吗？

**Comment by DuckSoft** [comment]
版本？有无插件？macOS 版本？

**Comment by DuckSoft** [comment]
未遵循 Issue 模板，关了。
