### ISSUE TITLE
一直提示找不到v2ray核心，我下载了安装到Qv2ray 里面的config和vcore都测试了。

### ISSUE THREAD

**Issue by bbhxwl** [Qv2ray/Qv2ray#633]
一直提示找不到v2ray核心，我下载了安装到Qv2ray 里面的config和vcore都测试了。不知道怎么解决了。无法连接

**Comment by cangyin** [comment]
你按照[这里](https://qv2ray.github.io/getting-started/step2.html#%E4%B8%8B%E8%BD%BD-v2ray-%E6%A0%B8%E5%BF%83%E6%96%87%E4%BB%B6)的提示一步一步操作了吗？最好是在配置核心路径之后点击 **检查 V2Ray 核心设置** 按钮来验证你的 V2Ray 核心设置。 重复尝试，直到你通过了检查。

**Comment by MarksonHon** [comment]
请进入 Telegram 群组<https://t.me/qv2ray>获取帮助，你所遇见的不是 bug，只是你自己没设置好。

**Comment by DuckSoft** [comment]
信息量不够呀。你是下的哪个版本，操作系统是啥，操作系统是什么版本……这些信息存在于原来的 Issue Template 里，但是被你删掉了。请酌情补全信息。

**Comment by bbhxwl** [comment]
解决了，是需要去首选项设置，我以为直接在软件根目录放了，顺便问一下这个是全局代理还是只代理网页，有没有办法简单点让别人设置路径，比如这两个路径存在哪里。注册表么

**Comment by DuckSoft** [comment]
请先通读文档：https://qv2ray.github.io/getting-started
若问题未解决，欢迎加入我们的 Telegram 群与我们直接交流：https://t.me/qv2ray
