### ISSUE TITLE
订阅会打乱订阅节点顺序

### ISSUE THREAD

**Issue by FANminiworld** [Qv2ray/Qv2ray#635]
- [x]   **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:
在版本为  2.6.0-rc3:5544  中的Qv2ray中更新订阅会导致节点顺序被打乱（并不是上游机场订阅问题，因为我测试了我所有的订阅链接（包括ss，ssr，vmess，trojan），均可复现出此问题）
# 如何复现这个 Bug：

去 `分组/订阅` 中点击 `Update Subscription` 即可复现

### 如果是连接问题，在其他 v2ray 客户端里出现过吗？ 

非连接问题，在其他客户端中不会复现

### 相关截图或日志

<details>

```
Qv2ray 日志：

此问题应该不需要日志

```

</details>

<details>

截图：

![Bug 反馈 1](https://user-images.githubusercontent.com/49353343/83343689-551dde80-a330-11ea-81e5-1b39014296ac.png)

![Bug 反馈 2](https://user-images.githubusercontent.com/49353343/83343770-500d5f00-a331-11ea-9579-8855553c60b9.png)

![Bug 反馈 3](https://user-images.githubusercontent.com/49353343/83343799-ad091500-a331-11ea-81b0-6e8f6e52ed64.png)

</details>

### 受影响的 Qv2ray 安装平台

- Windows  （仅测试了Windows 10）

### 受影响的 Qv2ray 安装源

- Github Release

### 已安装的插件 & 插件安装源：
1. SSR Plugin [https://github.com/Qv2ray/QvPlugin-SSR/releases/tag/v2.0.0-pre2](url)
2. Trojan Plugin [https://github.com/Qv2ray/QvPlugin-Trojan/releases/tag/v2.0.0-pre2](url)
### 首选项 -> 关于信息：

![版本信息](https://user-images.githubusercontent.com/49353343/83343918-1b9aa280-a333-11ea-8703-be0b53967cb3.png)

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by DuckSoft** [comment]
你好，这个 Bug 的确存在，我们已在着手修复。
感谢你的反馈～

**Comment by DuckSoft** [comment]
@Qv2ray-dev 目前此问题应已在最新的 dev 分支版本中修复。
@FANminiworld 你可以尝试一下。

**Comment by FANminiworld** [comment]
@DuckSoft 经测试已修复

**Comment by hzdrro** [comment]
@DuckSoft SSD订阅在2.6.0-rc3:5605 qt5.14.2-c2ec33571d73940530be3574a7d7c0ee65f162d8-ci.windows-latest版本上仍然是乱序。

**Comment by Qv2ray-dev** [comment]
@hzdrro Fixed, closing
