### ISSUE TITLE
win平台切换浅色主题，托盘图标变透明

### ISSUE THREAD

**Issue by aoeiuv-liu** [Qv2ray/Qv2ray#636]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:
win10平台切换成浅色主题，托盘图标变透明了。可以手动调整成黑色的托盘图标，可不可以增加一个自动根据系统是深色主题还是浅色主题来判断是使用黑色的图标还是使用白色的图标？
![image](https://user-images.githubusercontent.com/20061353/83364407-bb0f7200-a3d3-11ea-9778-3dbacc710b6d.png)

# 如何复现这个 Bug：

1. 
2. 
3. 
4. 

### 相关截图或日志

<details>

```
Qv2ray 日志：


```

</details>

### 受影响的 Qv2ray 安装平台

- Linux
- macOS
- Windows

### 受影响的 Qv2ray 安装源

- ArchLinuxCN - 稳定版
- ArchLinuxCN - 开发版
- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版
- Fedora - 稳定版
- Fedora - 开发版
- openSUSE - 稳定版
- openSUSE - 开发版
- Flathub 包
- Snap 包
- Homebrew Cask
- Scoop
- 手动编译
- Github Release

### 首选项 -> 关于信息：

```
版本号: 
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by DuckSoft** [comment]
https://qv2ray.github.io/getting-started/step5.html#%E8%B0%83%E6%95%B4%E7%95%8C%E9%9D%A2%E4%B8%8E%E6%98%BE%E7%A4%BA%E8%AF%AD%E8%A8%80
