### ISSUE TITLE
记忆 UI 大小

### ISSUE THREAD

**Issue by isArtJay** [Qv2ray/Qv2ray#637]
# 描述

每次打开面板发现位置和高度都会回到初始位置，希望能增加此功能，这样每次打开面板后不必再重新调整。

**Comment by DuckSoft** [comment]
你好，感谢反馈，将调研可行方案并予以实现。

**Comment by cangyin** [comment]
显然 rc4 还是没有实现，我来踢一下，防尘。

**Comment by LittleControl** [comment]
对对对,强烈建议,不然每次都要调整大小来查看log不太方便

**Comment by Yirect** [comment]
希望能记住UI调整，有些节点名称显示不完全，每次都要重新调整

**Comment by U-v-U** [comment]
WIP

**Comment by U-v-U** [comment]
fixed (Implemented). closing.
