### ISSUE TITLE
前置代理功能不生效

### ISSUE THREAD

**Issue by larchsis** [Qv2ray/Qv2ray#638]
首先感谢这个全新的客户端，整体感觉不错。
前置代理功能经过测试以及查看生成的config.gen.json文件，发现并没有生效。
具体描述：

1. 打开【首选项】---【连接设置】---【前置代理】，设置为http类型以及主机和端口；
2. 链接vmess服务器成功；
3. 打开谷歌页面失败，日志内容如下：

> V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 windows/amd64)
A unified platform for anti-censorship.
2020/06/01 12:17:17 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  E:/greensoft/gfw/Qv2ray/config/generated/config.gen.json
2020/06/01 12:17:17 [Warning] v2ray.com/core: V2Ray 4.23.2 started
2020/06/01 12:17:55 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://jp-5.azure.v2ray.ikuuu.pro:443/hls/cctv5phd.m3u8):  > dial tcp 20.46.165.237:443: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://jp-5.azure.v2ray.ikuuu.pro:443/hls/cctv5phd.m3u8):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/06/01 12:18:13 127.0.0.1:55769 accepted //www.google.com:443 [outBound_PROXY]

4. 打开配置文件E:/greensoft/gfw/Qv2ray/config/generated/config.gen.json，发现在outbounds项下面多了一个"_QV2RAY_USE_GLOBAL_FORWARD_PROXY_": null但是这部分内容显然没有填写正确。

**Comment by DuckSoft** [comment]
右键点节点，选编辑，
![图片](https://user-images.githubusercontent.com/7822648/83375919-13119d00-a403-11ea-9748-b46b807bc9fb.png)

**Comment by larchsis** [comment]
> 右键点节点，选编辑，
> ![图片](https://user-images.githubusercontent.com/7822648/83375919-13119d00-a403-11ea-9748-b46b807bc9fb.png)

这设置藏的够深的……多谢提示。再次测试了一下，勾选后连接服务器成功，访问google依然失败。
前置代理不论选http还是socks，配置文件中都是socks。

> {
>     "mux": {
>     },
>     "protocol": "socks",
>     "sendThrough": "0.0.0.0",
>     "settings": {
>         "servers": [
>             {
>                 "address": "127.0.0.1",
>                 "port": 1080
>             }
>         ]
>     },
>     "streamSettings": {
>     },
>     "tag": "_QV2RAY_FORWARD_PROXY_"
> },

错误日志：

> V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 windows/amd64)
A unified platform for anti-censorship.
2020/06/01 12:40:02 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  E:/greensoft/gfw/Qv2ray/config/generated/config.gen.json
2020/06/01 12:40:02 [Warning] v2ray.com/core: V2Ray 4.23.2 started
2020/06/01 12:40:31 127.0.0.1:57326 accepted //www.google.com:443 [outBound_PROXY]
2020/06/01 12:41:01 127.0.0.1:57376 accepted http://www.gstatic.com/generate_204 [outBound_PROXY]
2020/06/01 12:41:01 127.0.0.1:57379 accepted //www.google.com:443 [outBound_PROXY]
2020/06/01 12:41:12 [Warning] [1290621050] v2ray.com/core/proxy/http: failed to read response from www.gstatic.com > io: read/write on closed pipe

**Comment by DuckSoft** [comment]
Assigned to @Qv2ray-dev

**Comment by DuckSoft** [comment]
这可能是我们写出bug了……如果不介意，可以帮我们发一个 PR 修一下吗？

**Comment by hailouc** [comment]
鸭鸭，这个前置代理抓紧搞好吧，解决下上游v2ray原生支持配置起来手改超级麻烦， 希望小Q给它搞完善 让它能对多种协议的节点均能友好的支持前置代理！辛苦啦 @DuckSoft @everyone

**Comment by DuckSoft** [comment]
总结问题：带有传输层设置的前置代理功能在 V2Ray 核心中不受直接支持。
等待上游解决问题。目前我们已经有一个现成的方案，但是比较丑陋……
预计在 2.6.0 正式版加上吧。

**Comment by larchsis** [comment]
> 总结问题：带有传输层设置的前置代理功能在 V2Ray 核心中不受直接支持。
> 等待上游解决问题。目前我们已经有一个现成的方案，但是比较丑陋……
> 预计在 2.6.0 正式版加上吧。

抱歉，回复晚了，之前有事忘记自己提交的问题了。
由于公司网络都是通过代理出去，所以才会有这样的需求，本身v2ray核心也查了些资料，手工配置一直没有成功。期待你们的正式版发布然后试用。多谢~~~~

**Comment by larchsis** [comment]
问题先关闭

**Comment by heiyutian** [comment]
> 总结问题：带有传输层设置的前置代理功能在 V2Ray 核心中不受直接支持。
> 等待上游解决问题。目前我们已经有一个现成的方案，但是比较丑陋……
> 预计在 2.6.0 正式版加上吧。
截至 2.7.0版本，前置代理依然不生效，我前置的ssr本身没问题，在双ssr的前置测试都可以有效，qv2ray还是不行。

**Comment by U-v-U** [comment]
@heiyutian 前置代理现在是复杂配置的「代理链」功能，这个功能支持全部协议类型

**Comment by heiyutian** [comment]
> @heiyutian初步代理现在是复杂配置的“代理链”功能，这个功能支持全部协议类型

我开两个ssr的端口分别是1080和1081，ssr2前置设置127.0.0.1-1080是可以走ssr1的，在qv2ray的首选项里面，常规设置和连接设置也填写了127.0.0.1-1080就没用。
什么复杂配置我也不懂，我期望的就是在首选项里面填好了配置，就能够让qv2ray所有的流量都经过ssr1就行。
