### ISSUE TITLE
[建議]Qv2ray在Windows下的Icon顯示問題

### ISSUE THREAD

**Issue by noah137** [Qv2ray/Qv2ray#640]
Qv2ray的桌面圖標以及任務欄圖標顯示不清晰，希望能夠調整一下比例以適應低分屏
system version: Windows10 2004
display resolution: 1920 x 1080
scale: 100%
qv2ray version: 2.6.0-rc3

**Comment by noah137** [comment]
![qv2ray_icon_2](https://user-images.githubusercontent.com/64382544/83408025-7ec82a00-a444-11ea-8d5f-e9a8b1a6d1ed.png)
![qv2ray_icon_2](https://user-images.githubusercontent.com/64382544/83408051-8ee00980-a444-11ea-9555-7d45ce785824.png)

**Comment by DuckSoft** [comment]
感谢反馈，将做调整。

**Comment by DuckSoft** [comment]
问题定位。图标没有为 Windows 预留各种尺寸的图标。
https://github.com/Qv2ray/Qv2ray/blob/master/assets/icons/qv2ray.ico

暂时手头上没有 windows 系统，等下解决。

**Comment by unknowndev233** [comment]
> 问题定位。图标没有为 Windows 预留各种尺寸的图标。
> https://github.com/Qv2ray/Qv2ray/blob/master/assets/icons/qv2ray.ico
> 
> 暂时手头上没有 windows 系统，等下解决。

我的系统是 Win10，假设需要什么的话可以找我

**Comment by DuckSoft** [comment]
久等了。哪位 Windows 用户看看这个图标可不可以。

[icon.zip](https://github.com/Qv2ray/Qv2ray/files/4750866/icon.zip)

**Comment by unknowndev233** [comment]
> 久等了。哪位 Windows 用户看看这个图标可不可以。
> 
> [icon.zip](https://github.com/Qv2ray/Qv2ray/files/4750866/icon.zip)

这个图标为什么有一圈阴影？

**Comment by DuckSoft** [comment]
将于 2.6.0-rc5 中放出此修复～感谢你的反馈～
