### ISSUE TITLE
[BUG反饋]在group editor的connections選單下的二級選單出現顯示bug

### ISSUE THREAD

**Issue by noah137** [Qv2ray/Qv2ray#641]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

# 简单描述这个 Bug:
group editor的connections選單下的二級選單出現顯示不完整的情況

# 如何复现这个 Bug：

1. 打開Qv2ray主程式
2. 點擊靠近左下角的 Groups / Subscriptions 打開Group Editor
3. group editor的connections選單下的二級選單出現顯示bug

## 圖片

![qv2ray_render_bug_1](https://user-images.githubusercontent.com/64382544/83410416-f5672680-a448-11ea-84c2-351bef3fb338.png)

## 系统信息
Windows10 2004
### 受影响的 Qv2ray 安装平台
- Windows

### 受影响的 Qv2ray 安装源
- Github Release

### 已安装的插件 & 插件安装源：
QvSSRPlugin.v2.0.0-pre2.Windows-x64

### 首选项 -> 关于信息：

```
版本号: 2.6.0-rc3:5544
内部版本号：不知道
编译信息：Qv2ray built from Github Action
其它编译信息：qt5.14.2-d761a974b843c7556dac78f04e3f9dde7c3e400e-ci.windows-latest
```

**Comment by DuckSoft** [comment]
请问：你期待显示的内容为？实际显示的内容为？

**Comment by noah137** [comment]
> 请问：你期待显示的内容为？实际显示的内容为？

最後一個選單與邊緣並無明顯的分界感，可以默認為擴展到邊緣
![image](https://user-images.githubusercontent.com/64382544/83414294-d28c4080-a44f-11ea-98b0-131c2651dbe8.png)
或是在這邊添加一條分界綫、
![image](https://user-images.githubusercontent.com/64382544/83414359-ef287880-a44f-11ea-9621-81cabb19bf7c.png)
![image](https://user-images.githubusercontent.com/64382544/83414386-fea7c180-a44f-11ea-8fe1-21ab5c0c2bea.png)

**Comment by Qv2ray-dev** [comment]
![image](https://user-images.githubusercontent.com/59914293/83414755-9c9b8c00-a450-11ea-9397-c87231e26834.png)

经过调查，此问题出现在 Qt 的 Fusion 主题，您可以在首选项中切换主题为 Windows 或 WindowsVista 并再次尝试

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/83414670-7970dc80-a450-11ea-89b9-a830ccc8fb03.png)
![图片](https://user-images.githubusercontent.com/7822648/83414788-a4f3c700-a450-11ea-8bd5-1ff939cfcb51.png)

这可能是 Qt 自己的问题，不同主题下效果不同。

**Comment by Qv2ray-dev** [comment]
上游 Bug 在 Qv2ray 这里很难（甚至不能）被修复
