### ISSUE TITLE
无法更新任何种类订阅，总是提示“订阅源仅返回0个节点，确定要继续吗？”

### ISSUE THREAD

**Issue by liuxb** [Qv2ray/Qv2ray#642]
win10 32位，qv2ray 2.5.0 或 2.6.0，
添加订阅链接，点击“更新订阅数据”时，总是提示“订阅源仅返回0个节点”，不管是vmess还是ssr都一样，订阅链接没有被墙可以直接访问（通过代理结果也一样）。
同样的v2ray链接在v2rayn里完全正常。
举个ssr例子https://raw.githubusercontent.com/ssrsub/ssr/master/ssrsub
点击更新按钮时，似乎软件没有做任何动作，直接就弹出那个提示了。。。
![rr3](https://user-images.githubusercontent.com/936007/83479191-71558300-a4ca-11ea-8168-f000647becc7.gif)

**Comment by DuckSoft** [comment]
raw.githubusercontent.com 是被 DNS 污染的。没问题。

**Comment by DuckSoft** [comment]
附图：更新订阅的代理设置：
![图片](https://user-images.githubusercontent.com/7822648/83479325-da3cfb00-a4ca-11ea-9884-806f9bcd1922.png)

**Comment by DuckSoft** [comment]
更新：我本地更新完全没问题。请再核实一下你的网络环境和 Qv2ray 里的设置。
![图片](https://user-images.githubusercontent.com/7822648/83479469-36a01a80-a4cb-11ea-96ec-79f3a095586c.png)

**Comment by MarksonHon** [comment]
使用 SSR、Trojan 等由插件提供的协议之前必须把插件安装好并启用插件，你看看你的插件是不是正常的？

**Comment by liuxb** [comment]
dns污染的问题我本地有方案的，应该没问题。
![Untitled](https://user-images.githubusercontent.com/936007/83479684-e83f4b80-a4cb-11ea-8f0d-7c0400d56d31.png)
再试一个v2ray的，同一个链接，在v2rayn里面和qv2ray
![rrr](https://user-images.githubusercontent.com/936007/83479993-ba0e3b80-a4cc-11ea-8dff-17522fcf3dc1.gif)

**Comment by DuckSoft** [comment]
你这是 vmess v1 吧，Qv2ray v2.6.0 才加回来支持。
