### ISSUE TITLE
全键盘操作 Qv2ray 的一点建议

### ISSUE THREAD

**Issue by unknowndev233** [Qv2ray/Qv2ray#643]
目前（2.5.0）Qv2ray 暂不支持用 delete 键删除代理，反观隔壁 v2rayN 能这么做
可能它在平常不是很重要，但是在极端的情况下（例如鼠标突然故障时）可能很有用

**Comment by DuckSoft** [comment]
@unknowndev233 收悉。

**Comment by FANminiworld** [comment]
> 目前（2.5.0）Qv2ray 暂不支持用 delete 键删除代理，反观隔壁 v2rayN 能这么做
> 可能它在平常不是很重要，但是在极端的情况下（例如鼠标突然故障时）可能很有用

也不能算极端情况，键盘的操作效率远高于鼠标

**Comment by unknowndev233** [comment]
> > 目前（2.5.0）Qv2ray 暂不支持用 delete 键删除代理，反观隔壁 v2rayN 能这么做
> > 可能它在平常不是很重要，但是在极端的情况下（例如鼠标突然故障时）可能很有用
> 
> 也不能算极端情况，键盘的操作效率远高于鼠标

要看是做什么吧

**Comment by unknowndev233** [comment]
> @unknowndev233 用del键删是挺爽的

难道爽了再 Ctrl + Z 撤销吗？（不是

**Comment by Qv2ray-dev** [comment]
@unknowndev233 删除是可以添加确认框的

**Comment by unknowndev233** [comment]
> @unknowndev233 删除是可以添加确认框的

这个好

**Comment by Qv2ray-dev** [comment]
fixed, close.
