### ISSUE TITLE
libprotobuf.so.22缺失

### ISSUE THREAD

**Issue by SmileDup** [Qv2ray/Qv2ray#645]
于2020-6-3在Arch Linux(x64)更新go,protobuf,protobuf-c三个包过后，启动qvray报错：
`qv2ray: error while loading shared libraries: libprotobuf.so.22: cannot open shared object file: No such file or directory`

protobuf内库文件名称变更为usr/lib/libprotobuf.so.23

**Comment by Qv2ray-dev** [comment]
@SmileDup 重新编译即可， duplicated

**Comment by DuckSoft** [comment]
详见 #644
