### ISSUE TITLE
qv2ray: error while loading shared libraries: libprotobuf.so.22: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by luchun** [Qv2ray/Qv2ray#646]
# 简单描述这个 Bug:
系统: archlinux
通过  sudo pacman -U qv2ray-dev-automation-2.6.0.5544-1-x86_64.pkg.tar.xz 安装Qv2ray后无法启动，在命令行执行 qv2ray得到如下报错
qv2ray: error while loading shared libraries: libprotobuf.so.22: cannot open shared object file: No such file or directory
查找libprotobuf.so.22 找不到，原因是是Qv2ray依赖的protobuf 已更新到3.12.0-1，提供的是libprotobuf.so.23。

### 受影响的 Qv2ray 安装平台

- Linux

### 受影响的 Qv2ray 安装源
- Github Release

### 已安装的插件 & 插件安装源：
无

### 首选项 -> 关于信息：

```
版本号: 
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
请问应该使用protobuf的哪个版本

**Comment by DuckSoft** [comment]
上游 protobuf bump 了 soversion，需要重新构建。
详见 #644 #645
我触发一次就好了。

**Comment by DuckSoft** [comment]
另外，你如果有配置 archlinuxcn 源，可以直接 sudo pacman -S qv2ray-dev-git 安装最新的预览版

**Comment by DuckSoft** [comment]
构建成功，请自取：
https://github.com/Qv2ray/Qv2ray/actions/runs/122887413

**Comment by luchun** [comment]
感谢 已经好了

**Comment by trennble** [comment]
当前这个时间点的最新版本又发生了。。。。

**Comment by DuckSoft** [comment]
```
ducksoft@duckarch ~> ldd /usr/bin/qv2ray
        linux-vdso.so.1 (0x00007ffe8b7ec000)
        libQt5Network.so.5 => /usr/lib/libQt5Network.so.5 (0x00007f8cdeb52000)
        libprotobuf.so.23 => /usr/lib/libprotobuf.so.23 (0x00007f8cde834000)
```

> 当前这个时间点的最新版本又发生了。。。。

一切正常。滚滚更健康。
