### ISSUE TITLE
macos 10.15.2,打开软件没有任何界面显示

### ISSUE THREAD

**Issue by 547555909** [Qv2ray/Qv2ray#647]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:
软件版本2.6.0-r3/2.5.0 只有软件在dock栏跳动一会，没有出现其他界面

# 如何复现这个 Bug：

1. 安装软件
2. 打开软件
3. 复现这个bug

### 如果是连接问题，在其他 v2ray 客户端里出现过吗？ 
非链接问题

### 相关截图或日志

<details>
![image](https://user-images.githubusercontent.com/19320063/83596624-a8459a80-a597-11ea-80b8-42de2f979ab4.png)

```
Qv2ray 日志：
没加载成功，无法提供

```

</details>

## 系统信息 （请删掉不符合的项）
macos 10.15.2
### 受影响的 Qv2ray 安装平台

- macOS

### 受影响的 Qv2ray 安装源

- Github Release

### 已安装的插件 & 插件安装源：
没安装插件，因为打开不软件

### 首选项 -> 关于信息：

```
版本号: 2.5.0、2.6.0-r3
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by wy-luke** [comment]
manjaro刚才更新了系统，也打不开了。只是闪现一下界面

**Comment by DuckSoft** [comment]
> manjaro刚才更新了系统，也打不开了。只是闪现一下界面

请加群 https://t.me/qv2ray 与我们直接对话以解决问题。

**Comment by DuckSoft** [comment]
> manjaro刚才更新了系统，也打不开了。只是闪现一下界面

Manjaro 用 Arch Linux CN 源会经常遭遇这种问题。因为 Arch Linux 更新了部分包，Arch Linux CN 需要更新 qv2ray 以保持与新版的兼容性。你可以用 pacman -Q protobuf 检查一下你本地的 protobuf 依赖版本，如果版本低于 3.12.0，你可以在这评论，我帮你打一个旧版 protobuf 的包。

**Comment by DuckSoft** [comment]
> 软件版本2.6.0-r3/2.5.0 只有软件在dock栏跳动一会，没有出现其他界面

来自 @ymshenyu：
你为啥不试试万能的重启呢？

**Comment by wy-luke** [comment]
> > manjaro刚才更新了系统，也打不开了。只是闪现一下界面
> 
> Manjaro 用 Arch Linux CN 源会经常遭遇这种问题。因为 Arch Linux 更新了部分包，Arch Linux CN 需要更新 qv2ray 以保持与新版的兼容性。你可以用 pacman -Q protobuf 检查一下你本地的 protobuf 依赖版本，如果版本低于 3.12.0，你可以在这评论，我帮你打一个旧版 protobuf 的包。

是的，低于3.12.0, 是3.11。麻烦您了，非常感谢。

**Comment by DuckSoft** [comment]
> > > manjaro刚才更新了系统，也打不开了。只是闪现一下界面
> > 
> > 
> > Manjaro 用 Arch Linux CN 源会经常遭遇这种问题。因为 Arch Linux 更新了部分包，Arch Linux CN 需要更新 qv2ray 以保持与新版的兼容性。你可以用 pacman -Q protobuf 检查一下你本地的 protobuf 依赖版本，如果版本低于 3.12.0，你可以在这评论，我帮你打一个旧版 protobuf 的包。
> 
> 是的，低于3.12.0, 是3.11。麻烦您了，非常感谢。

2.5.0 版本的降级构建版本已经发到你的 GitHub 公开邮箱上了。
