### ISSUE TITLE
缺少依赖库 libprotobuf.so.23

### ISSUE THREAD

**Issue by alucardwind** [Qv2ray/Qv2ray#648]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:

系统是manjaro
更新2.5.0-4后出现此问题，程序无法启动，终端其中后报错
qv2ray: error while loading shared libraries: libprotobuf.so.23: cannot open shared object file: No such file or directory
请问我是需要手动更新什么库吗？

# 如何复现这个 Bug：

终端启动v2ray

## 系统信息 （请删掉不符合的项）

Manjaro 20.0.2 Lysia
x86_64 Linux 5.6.15-1-MANJARO

### 受影响的 Qv2ray 安装平台

- Linux

### 受影响的 Qv2ray 安装源

- ArchLinuxCN - 稳定版

### 已安装的插件 & 插件安装源：

无

**其他信息**
无

**Comment by Qv2ray-dev** [comment]
@alucardwind duplicated, see https://github.com/Qv2ray/Qv2ray/issues/644

**Comment by gs-notageek** [comment]
由于Arch上protobuf发生更新，而后Arch用户无法使用前一版本的qv2ray，并通知ArchLinuxCN对上游软件进行重编译，使新版本依赖于libprotobuf.so.23
但是在manjaro系统上并没有这一更新，因此如果采用ArchLinuxCN源的qv2ray，更新后就会出现这一问题，但是ArchLinuxCN只负责Arch，并明确表示不对manjaro上的兼容性问题负责
因此现在manjaro上无法使用

**Comment by gs-notageek** [comment]
可以使用AUR仓库的qv2ray

**Comment by DuckSoft** [comment]
还是 Manjaro 降低了门槛啊……作为一个滚动发行版，你应该至少了解一下回滚这个基本操作……
如果升级到 qv2ray-2.5.0-4 炸了，为何不回滚到 qv2ray-2.5.0-1 呢
