### ISSUE TITLE
当前个人使用 Qv2ray 的一些小问题

### ISSUE THREAD

**Issue by unknowndev233** [Qv2ray/Qv2ray#650]
1. 在我现在使用的 KDE 上，因为有两个 Qv2ray 用于 autostart 的 .desktop 文件导致刚登陆时 qv2ray 命令被执行两次，希望在各种兼容 XDG 规范的路径添加用于登陆时启动的 .desktop 文件时提前检查一下（可能很久以前的 Qv2ray 使用的是 Qv2ray.desktop，但是在某个更新中修改为 qv2ray 了

2. 在初始配置高级路由中设置域名策略从 Asis 到 IPIfNonMatch 并在此之后点预置方案选择 v2rayN 时，刚刚选择的 IPIfNonMatch 会变回 Asis
哪怕是在空方案改为 IPIfNonMatch 时并且确定之后再用预置方案为 v2rayN 也会变回 Asis

3. 希望 Qv2ray 可以在修改配置文件后留下修改前的配置文件做备用，因为一些原因，我的 Win10 并不稳定，在蓝屏或者屏幕冻结后，Qv2ray 的 Qv2ray.conf 会变为最后一次写入时大小相当的空白文件

**Comment by MarksonHon** [comment]
首先，个人建议，你自己的锅要自己背，别麻烦软件的开发者，就比如说你的多个 desktop 文件，这是你自己的锅应当由你自己解决。
其次，一个方案是包含了域名策略的，你不能指望导入一个新的方案而不改动域名策略。
最后，你自己的系统不稳定、需要开发者帮忙解决的，你需要把你的程序版本、系统版本都说出来，放便开发者定位问题。且如果是 insider 系统，那么不要指望开发者去刻意适配一个不稳定的系统。

**Comment by DuckSoft** [comment]
1: Good Bug, Will Fix
2: 这是预期行为
3: 需要讨论

**Comment by unknowndev233** [comment]
> 1: Good Bug, Will Fix
> 2: 这是预期行为
> 3: 需要讨论

原来第二个属于特性

**Comment by unknowndev233** [comment]
> 1. 在我现在使用的 KDE 上，因为有两个 Qv2ray 用于 autostart 的 .desktop 文件导致刚登陆时 qv2ray 命令被执行两次，希望在各种兼容 XDG 规范的路径添加用于登陆时启动的 .desktop 文件时提前检查一下（可能很久以前的 Qv2ray 使用的是 Qv2ray.desktop，但是在某个更新中修改为 qv2ray 了
> 2. 在初始配置高级路由中设置域名策略从 Asis 到 IPIfNonMatch 并在此之后点预置方案选择 v2rayN 时，刚刚选择的 IPIfNonMatch 会变回 Asis
>    哪怕是在空方案改为 IPIfNonMatch 时并且确定之后再用预置方案为 v2rayN 也会变回 Asis
> 3. 希望 Qv2ray 可以在修改配置文件后留下修改前的配置文件做备用，因为一些原因，我的 Win10 并不稳定，在蓝屏或者屏幕冻结后，Qv2ray 的 Qv2ray.conf 会变为最后一次写入时大小相当的空白文件

以上三个问题的版本号都是 2.5.0

**Comment by unknowndev233** [comment]
> 一个方案是包含了域名策略的，你不能指望导入一个新的方案而不改动域名策略。
> 同时，开发者帮忙解决的，你需要把你的程序版本、系统版本都说出来，放便开发者定位问题。且如果是 insider 系统，那么不要指望开发者去刻意适配一个不稳定的系统。

对于后者，我用的是非 insider 系统，不过由于硬件问题……
一言难尽
