### ISSUE TITLE
[BUG] Alter ID 不能大于1024

### ISSUE THREAD

**Issue by LOVEChen** [Qv2ray/Qv2ray#651]
# 简单描述这个 Bug:

Alter ID 不能大于1024

## 系统信息 （请删掉不符合的项）
Mojave 10.14.6

### 受影响的 Qv2ray 安装平台

- macOS

**Comment by DuckSoft** [comment]
Bug Confirmed. Will fix immediately.

**Comment by DuckSoft** [comment]
Good first issue! Will be fixed in commit 9d8047ac7f9e283946d1a7e05ed7bf2d3c67ad5f.

**Comment by DuckSoft** [comment]
You can take the hot-built package here:
https://github.com/Qv2ray/Qv2ray/runs/738120080

Fixed. Closing!
