### ISSUE TITLE
打开时提示缺少libprotobuf.so.23

### ISSUE THREAD

**Issue by xiaohaoxiang** [Qv2ray/Qv2ray#652]
我用的Manjaro的系统，目前最新的libprotobuf.so为libprotobuf.so.22，请问Qv2ray是否使用了过于新的库？

**Comment by Qv2ray-dev** [comment]
https://github.com/Qv2ray/Qv2ray/issues/644

**Comment by DuckSoft** [comment]
> 我用的Manjaro的系统，目前最新的libprotobuf.so为libprotobuf.so.22，请问Qv2ray是否使用了过于新的库？

不，恰恰相反，Manjaro 使用了过旧的库。建议换 Arch，加群可以提供技术支持。
https://t.me/qv2ray
