### ISSUE TITLE
订阅地址线路中文的话，很多无法显示，不知道为什么

### ISSUE THREAD

**Issue by bbhxwl** [Qv2ray/Qv2ray#653]
如果订阅如果叫日本1，可以显示出来，叫台湾1就不行，俄罗斯1也不行，韩国1也不行，不知道为什么。base64 加密的，格式应该没啥问题吧，叫日本就可以显示，不知道为什么。

**Comment by DuckSoft** [comment]
有图吗

**Comment by bbhxwl** [comment]
> 有图吗

是不显示线路，不知道怎么用图表示出来。。。我自己做的订阅网址的base64 加密。

**Comment by bbhxwl** [comment]
{"host":"azure.microsoft.com","path":"/v2ray","tls":"","verify_cert":true,"add":"default.us.nwncd.com","port":"6060","aid":2,"net":"ws","headerType":"none","v":"2","type":"none","ps":"俄罗斯1","remark":"俄罗斯1","id":"6d759b7b-d3c3-323f-bc19-aafe720331a5","class":0}


比如这样，他就不显示线路。

**Comment by DuckSoft** [comment]
https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)

请对照标准自己检查一下，自己做的格式是否有误。

**Comment by bbhxwl** [comment]
> https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)
> 
> 请对照标准自己检查一下，自己做的格式是否有误。

格式是没问题，不然也不会用英文就都正常，不知道什么问题。好像都这样。

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/83755649-74a26780-a6a0-11ea-81d0-24853ac455a3.png)
我这里 Base64 编码之后，导入没有任何问题，使用的就是你上面的“俄罗斯1”节点。
我使用 Linux 的 GNU coreutils 8.32-1 进行编码，编码结果如下：

```
eyJob3N0IjoiYXp1cmUubWljcm9zb2Z0LmNvbSIsInBhdGgiOiIvdjJyYXkiLCJ0bHMiOiIiLCJ2ZXJpZnlfY2VydCI6dHJ1ZSwiYWRkIjoiZGVmYXVsdC51cy5ud25jZC5jb20iLCJwb3J0IjoiNjA2MCIsImFpZCI6MiwibmV0Ijoid3MiLCJoZWFkZXJUeXBlIjoibm9uZSIsInYiOiIyIiwidHlwZSI6Im5vbmUiLCJwcyI6IuS/hOe9l+aWrzEiLCJyZW1hcmsiOiLkv4TnvZfmlq8xIiwiaWQiOiI2ZDc1OWI3Yi1kM2MzLTMyM2YtYmMxOS1hYWZlNzIwMzMxYTUiLCJjbGFzcyI6MH0K
```
你可以和你的编码结果核对一下，看看是否有问题。

**Comment by DuckSoft** [comment]
人呢……还有后续吗？

**Comment by DuckSoft** [comment]
暂无回应，暂时关闭。

**Comment by bbhxwl** [comment]
> 暂无回应，暂时关闭。

有大哥。我正在测试。

**Comment by bbhxwl** [comment]
我测试的utf8格式，是有问题，挺奇怪。能检测到1个节点，但是显示不出来。
![111](https://user-images.githubusercontent.com/26525599/83799014-ba2e5700-a6d7-11ea-84d3-a3cb4e9d73fc.png)

![222](https://user-images.githubusercontent.com/26525599/83799023-be5a7480-a6d7-11ea-829c-0b4ac41a894a.png)

**Comment by DuckSoft** [comment]
可能涉及节点敏感信息，建议加群私聊讨论：https://t.me/qv2ray
或者也可发送订阅地址到 realducksoft@gmail.com，帮你看一下原因。

**Comment by bbhxwl** [comment]
Unicode和ASCII 也测试也是这样，奇怪。

**Comment by DuckSoft** [comment]
再次核实一下你的格式：
Base64(vmess://Base64(UNICODE JSON), \r\n, ...)
注意要套两层

**Comment by bbhxwl** [comment]
C# 代码，          return Content(Base64.EncodeUrlSafeBase64("vmess://" + Base64.EncodeUrlSafeBase64(System.IO.File.ReadAllText("D:\\a.txt"))));
a.txt里面就是{“ host”：“ azure.microsoft.com”，“ path”：“ / v2ray”，“ tls”：“”，“ verify_cert”：true，“ add”：“ default.us.nwncd.com”，“ port“：” 6060“，” aid“：2，” net“：” ws“，” headerType“：” none“，” v“：” 2“，” type“：” none“，” ps“：”俄罗斯1“，”备注“：”俄罗斯1“，” id“：” 6d759b7b-d3c3-323f-bc19-aafe720331a5“，”类别“：0}

**Comment by DuckSoft** [comment]
土制base64 encode硬编码json导致问题。已定位。暂时关闭。
