### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by WOAZAA** [Qv2ray/Qv2ray#654]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

# 简单描述这个 Bug:
首选项-连接设置中‘Use V2ray DNS for Direct Connection’选项Connection错误拼写为Conenction

# 如何复现这个 Bug：

1. 打开主界面
2. 点击首选项
3. 点击连接设置标签页

### 相关截图或日志
<img width="674" alt="批注 2020-06-05 023457" src="https://user-images.githubusercontent.com/12210261/83797394-29567c00-a6d5-11ea-873e-bbbb1abbe433.png">

### 受影响的 Qv2ray 安装平台

- Windows

### 受影响的 Qv2ray 安装源

- Github Release

### 首选项 -> 关于信息：

版本号: 2.6.0-rc3:5544

**Comment by DuckSoft** [comment]
@WOAZAA 收悉，即刻修复。

**Comment by DuckSoft** [comment]
已修复于最新提交 209707ff87068ad5face856a4e06dbb1b313f08a。
感谢反馈。
