### ISSUE TITLE
使用问题一则

### ISSUE THREAD

**Issue by AaronYeung1989** [Qv2ray/Qv2ray#655]
我添加了节点之后，所有数据都是0，是不是哪里设置错了？另外，我的Qv2ray无法点开登录时启动这个选项，请大神帮忙看下，谢谢。
然后日志上是这样写的：
V2Ray 4.23.4 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 windows/amd64)
A unified platform for anti-censorship.
2020/06/05 03:25:36 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  D:/Qv2ray.v2.5.0.Windows-x64/deployment/config/generated/config.gen.json
2020/06/05 03:25:36 [Warning] v2ray.com/core: V2Ray 4.23.4 started

![QQ截图20200605033000](https://user-images.githubusercontent.com/66421397/83802235-f6b08180-a6dc-11ea-84a1-1339e5e9b35b.png)
![QQ截图20200605033013](https://user-images.githubusercontent.com/66421397/83802237-f87a4500-a6dc-11ea-8c34-295bfa5f977a.png)
![QQ截图20200605033022](https://user-images.githubusercontent.com/66421397/83802240-f912db80-a6dc-11ea-8c26-67000d48f828.png)
![QQ截图20200605033030](https://user-images.githubusercontent.com/66421397/83802243-f912db80-a6dc-11ea-820f-57a5853035a5.png)

**Comment by DuckSoft** [comment]
添加节点之后要双击连接节点。

**Comment by AaronYeung1989** [comment]
> 添加节点之后要双击连接节点。

是显示已连接上。。。但是速度和数据都是0
漏了一幅图
![QQ截图20200605033730](https://user-images.githubusercontent.com/66421397/83802735-e64cd680-a6dd-11ea-95bc-13e650b4b58d.png)

**Comment by DuckSoft** [comment]
看上去是没有流量流进来。请打开Windows的系统设置，跳转到网络——代理，然后截图页面。
我们检查一下代理设置是否正确。

**Comment by DuckSoft** [comment]
人还在吗

**Comment by AaronYeung1989** [comment]
在。系统里的是这样的
![QQ截图20200605034435](https://user-images.githubusercontent.com/66421397/83803315-eef1dc80-a6de-11ea-95d3-d92b0908fe07.png)
![QQ截图20200605034445](https://user-images.githubusercontent.com/66421397/83803318-f0230980-a6de-11ea-8350-2c9d151e39ef.png)

**Comment by DuckSoft** [comment]
你的系统代理设定疑似被其他应用程序干扰了。检查一下你有没有开其他梯子程序，有的话记得关掉。
然后按下面的方式填写：
地址：`http://127.0.0.1`
端口：`8888`
然后点保存即可

**Comment by AaronYeung1989** [comment]
好的。我试一下

**Comment by AaronYeung1989** [comment]
> 8888

非常感谢，可以翻墙了。

**Comment by DuckSoft** [comment]
对于此类使用问题，建议加入我们的 Telegram 群进行讨论：
https://t.me/qv2ray

问题已解决，先行关闭。

**Comment by AaronYeung1989** [comment]
> 对于此类使用问题，建议加入我们的 Telegram 群进行讨论：
> https://t.me/qv2ray
> 
> 问题已解决，先行关闭。

另外，为什么无法登录开启软件？点了勾选以后提示错误信息
![QQ截图20200605040950](https://user-images.githubusercontent.com/66421397/83805441-7a20a180-a6e2-11ea-9dcf-56ae4c513166.png)
