### ISSUE TITLE
无法加载 libprotobuf.so.23

### ISSUE THREAD

**Issue by crimx** [Qv2ray/Qv2ray#656]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:

昨天滚动更新后无法打开 Qv2ray，显示

```
qv2ray: error while loading shared libraries: libprotobuf.so.23: cannot open shared object file: No such file or directory
```

因为之前更新前还在用是没有问题的，请问这是

- 滚动更新导致依赖缺失
- 或者这是新增的依赖需要自行安装
- 还是 Qv2ray 新版打包出了问题

该如何修复这个问题。对 QT 不太熟，如有问题请指正。

### 受影响的 Qv2ray 安装平台

- Linux (Manjaro)

### 受影响的 Qv2ray 安装源

- ArchLinuxCN - 稳定版

**Comment by Qv2ray-dev** [comment]
https://github.com/Qv2ray/Qv2ray/issues/644

**Comment by crimx** [comment]
Sorry 看走眼了😂
