### ISSUE TITLE
feature request about mouse hovering on group names

### ISSUE THREAD

**Issue by cangyin** [Qv2ray/Qv2ray#657]
![Snipaste_2020-06-05_13-18-12](https://user-images.githubusercontent.com/50256182/83840004-0a390800-a730-11ea-93da-eb3d1b6d58c9.png)

能不能把这个鼠标悬停提示换成其他内容，比如上次更新时间、组内流量总计什么的。

**Comment by DuckSoft** [comment]
啊，这个建议很好。
Noted。

**Comment by Soowin** [comment]
订阅链接暴露了！

**Comment by cangyin** [comment]
> 订阅链接暴露了！

edited, thx.

**Comment by unknowndev233** [comment]
> > 订阅链接暴露了！
> 
> edited, thx.

建议刷新链接

**Comment by cangyin** [comment]
Implemented in 2.6-rc4
