### ISSUE TITLE
win10无法开机启动

### ISSUE THREAD

**Issue by AaronYeung1989** [Qv2ray/Qv2ray#658]
在勾选“登录时启动”会跳错误提示：无法设置自动启动选项。
请问如何解决，如图所示：
![QQ截图20200605144653](https://user-images.githubusercontent.com/66421397/83845461-808f3780-a73b-11ea-8e7d-7dbb6e91ffe3.png)

**Comment by DuckSoft** [comment]
无法复现。请检查是否安装了什么奇怪的杀毒软件之类的。
或者，使用管理员权限运行 Qv2ray 再试一次。

**Comment by Qv2ray-dev** [comment]
@AaronYeung1989 请检查任务管理器内是否有禁用掉的 Qv2ray 自启设置
（或查询安全软件相关设置）

**Comment by AaronYeung1989** [comment]
> 无法复现。请检查是否安装了什么奇怪的杀毒软件之类的。
> 或者，使用管理员权限运行 Qv2ray 再试一次。

只装了360，没有其他的杀毒软件。已用管理员权限运行过，还是不行。

**Comment by AaronYeung1989** [comment]
> @AaronYeung1989 请检查任务管理器内是否有禁用掉的 Qv2ray 自启设置
> （或查询安全软件相关设置）

如图所示，不知是否有禁用掉的设置
![QQ截图20200605145801](https://user-images.githubusercontent.com/66421397/83846455-3313ca00-a73d-11ea-9589-f7e7e7d08a0b.png)

**Comment by DuckSoft** [comment]
@AaronYeung1989 3  6  0

**Comment by DuckSoft** [comment]
非常抱歉，我个人不对安装了 360 的电脑提供技术支持。
欢迎其他热心人士前来帮忙。另请高明吧。

**Comment by cangyin** [comment]
都会fq了，就该学会卸载国产毒瘤杀软了
