### ISSUE TITLE
Feature request: NaiveProxy support

### ISSUE THREAD

**Issue by dancwj** [Qv2ray/Qv2ray#664]
请问能不能支持NaiveProxy?

**Comment by DuckSoft** [comment]
可。让我研究一下。

**Comment by dancwj** [comment]
> 可。让我研究一下。

多谢！最近安装了NaiveProxy，速度很快，安装简便，但是客户端太缺乏了，Windows需要开一个cmd的黑窗口，macOS还没有好的客户端，期待Qv2ray的率先支持

**Comment by dancwj** [comment]
> 可。让我研究一下。

https://github.com/proxysu/windows

这个ProxySU的一键安装工具很好用

**Comment by s-kk** [comment]
Qv2ray is a frontend for v2ray, and it should focus on v2ray instead of unifying other proxy utilities. Frontends for other censorship circumvention tools should be made separately.

**Comment by dancwj** [comment]
> Qv2ray is a frontend for v2ray, and it should focus on v2ray instead of unifying other proxy utilities. Frontends for other censorship circumvention tools should be made separately.

你的想法和作者不同，作者推出的是一个平台，已经兼容SSR和Trojan插件，再增加一个应该没有问题，作者也没有只针对v2ray来开发，哪天v2ray被gfw完全破解，还可以用插件来上。正因为作者提供插件平台，所以才提出是否开发naiveproxy插件的要求，所以你的说法不成立

**Comment by DuckSoft** [comment]
你好，完事了：https://github.com/Qv2ray/QvPlugin-NaiveProxy
刚写完，问题肯定还有很多，欢迎测试～
