### ISSUE TITLE
Qv2ray crashes always when i try to connect any node (节点)

### ISSUE THREAD

**Issue by coolrose78** [Qv2ray/Qv2ray#665]
My OSX is High Sierra (10.13.6). I can install Qv2ray version 2.5 without any problem . I have installed both SSR (v1.0.3) and trojan(v1.0.1) plugins. 

When I try to connect any trojan or SSR node (节点)，the program crashes immediately.  What might be the reason?  Is it because of libgrpc.dylib not compatible to old version of os....

Process:               qv2ray [76661]
Path:                  /Applications/qv2ray.app/Contents/MacOS/qv2ray
Identifier:            qv2ray
Version:               2.5.0 (2.5.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           qv2ray [76661]
OS Version:            **Mac OS X 10.13.6**
Report Version:        12

Crashed Thread:        2  QThread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    **DYLD, [0x4] Symbol missing**

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/qv2ray.app/Contents/MacOS/../Frameworks/libgrpc.dylib (**which was built for Mac OS X 10.15**)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by DuckSoft** [comment]
You can mitigate this using the following steps, however, an upgrade of your OS X is suggested:

1. In Qv2ray main window, click **Preferences** to open settings window.
2. Choose **Kernel Settings** Tab, and disable **API Subsystem** by unchecking it.
3. Save the preferences and restart Qv2ray.
![图片](https://user-images.githubusercontent.com/7822648/84000241-e4616c80-a996-11ea-8c03-ee098112f12a.png)

You will lose the statistics functionality, but the main function still works.
You may want to report to https://github.com/grpc/grpc/ to make them support OS X 10.13.
We cannot help further.
