### ISSUE TITLE
Qv2ray 日志查看时需要禁止滚动

### ISSUE THREAD

**Issue by unknowndev233** [Qv2ray/Qv2ray#669]
为什么？
在日志中的茫茫大海看到很有用的东西时谁也不希望它突然消失不见，不是吗？

**Comment by cangyin** [comment]
哈哈，赞同！

**Comment by Mr-xn** [comment]
附议：日志 IP地址这些颜色不用黄色啊  好刺眼 看不清。。。![](https://i.imgur.com/cf2SqVG.png)

**Comment by DuckSoft** [comment]
> 附议：日志 IP地址这些颜色不用黄色啊 好刺眼 看不清。。。![](https://camo.githubusercontent.com/013b5174bda226b00e4de72bbd357b3ebe05af81/68747470733a2f2f692e696d6775722e636f6d2f636632537156472e706e67)

设置第一项，关掉，不客气

**Comment by unknowndev233** [comment]
> > 附议：日志 IP地址这些颜色不用黄色啊 好刺眼 看不清。。。![](https://camo.githubusercontent.com/013b5174bda226b00e4de72bbd357b3ebe05af81/68747470733a2f2f692e696d6775722e636f6d2f636632537156472e706e67)
> 
> 设置第一项，关掉，不客气

能自行设置配色吗？

**Comment by U-v-U** [comment]
@unknowndev233 fixed and confirmed. closing.
