### ISSUE TITLE
对于当前不能点击的菜单选项，文字会变的很奇怪

### ISSUE THREAD

**Issue by zjy8963** [Qv2ray/Qv2ray#670]
![image](https://user-images.githubusercontent.com/48082574/84213021-24893200-aaf2-11ea-905f-b8816650f7c9.png)

如图所示

**Comment by cangyin** [comment]
@zjy8963 什么系统、Qv2ray 什么版本

**Comment by DuckSoft** [comment]
看字体是 Windows。这个虚化是正常现象。能不能点击，你看鼠标能否在对应的菜单项上悬停就好了。
