### ISSUE TITLE
系统语言为中文时无法启动

### ISSUE THREAD

**Issue by popozhu** [Qv2ray/Qv2ray#671]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:

在 macOS 10.13.5 第一次启动 Qv2ray 时，无法启动。Qv2ray 只在 Dock 栏弹跳无响应。

后面发现当系统语言为中文时，就会出现这个问题。把系统语言切换到英文，就能正常启动。

# 如何复现这个 Bug：

1. macOS 10.13.5 + 系统语言为中文，第一次启动软件
2. 见 console 日志，可看到 `LSExceptions shared instance invalidated for timeout.`
3. 
4. 

### 相关截图或日志

<details>

```
Qv2ray 日志：

LSExceptions shared instance invalidated for timeout.
```

</details>

### 受影响的 Qv2ray 安装平台

- macOS 

### 受影响的 Qv2ray 安装源

- 手动编译 [x]
- Github Release [x]

### 首选项 -> 关于信息：

```
版本号: 
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by DuckSoft** [comment]
Qv2ray 目前因为构建机工具链版本原因，暂时无法支持 macOS 10.13。
请考虑升级系统。

**Comment by popozhu** [comment]
感谢答复。

首先，把 macOS 10.13 的系统语言切换到 **英文** 后已经解决我遇到的问题。

但还是想反馈一下，希望帮助到其他人（issues里也有人遇到无法启动的问题）

最后，希望可以显示声明最低支持到 macOS 的哪个系统版本

**Comment by DuckSoft** [comment]
这里也希望大家了解几个事实：
* Qv2ray 开发组没人有 macOS 电脑，就算有黑果虚拟机也没有 10.13 这么老的镜像。
* Qv2ray 开发组没人懂苹果开发。

我们会尽力支持。

**Comment by Qv2ray-dev** [comment]
Interesting: 
https://github.com/shadowsocks/ShadowsocksX-NG/issues/712
