### ISSUE TITLE
qv2ray 2.6.0-rc3:554在deepin v20会提示环境变量有问题

### ISSUE THREAD

**Issue by 3232948807** [Qv2ray/Qv2ray#672]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:

qv2ray 2.6.0-rc3:554在deepin v20会提示环境变量有问题
![截图录屏_选择区域_20200610171324](https://user-images.githubusercontent.com/61373853/84251207-9fc50500-ab3f-11ea-8bbe-b47ce847a7b5.png)

**Comment by DuckSoft** [comment]
这是 Deepin 自己的问题，Qv2ray 只是警告你系统代理功能可能会被 Deepin 干扰而无法使用。
这个警告每次打开软件只会出现一次。

很多 Deepin 用户问我们，怎么代理不好用。我们排查了半天才知道这个问题。
无奈至极，出此下策。

建议去上游催更：https://github.com/linuxdeepin/go-lib/issues/15

**Comment by DuckSoft** [comment]
相关链接：https://github.com/Qv2ray/Qv2ray/pull/589/

**Comment by ArisAachen** [comment]
确实有这个问题    才看到

**Comment by xmuli** [comment]
> 建议去上游催更：linuxdeepin/go-lib#15

滴滴， 表示已经修复
