### ISSUE TITLE
求助一下全局的问题

### ISSUE THREAD

**Issue by bbhxwl** [Qv2ray/Qv2ray#674]
求助一下全局的问题，我配合sstap连接本机socks5的话，我自己好像是可以，别人有说连接后，网页也打不开了，为啥呢，有啥全局的好办法么。

**Comment by DuckSoft** [comment]
一万个人有一万个环境，使用问题建议加群讨论：https://t.me/qv2ray

**Comment by ayalhw** [comment]
bugs label可还行
