### ISSUE TITLE
 "testsEnabled": "VMessAEAD" 支持

### ISSUE THREAD

**Issue by Mr-xn** [Qv2ray/Qv2ray#675]
vmess的最新版 v4.24.2中新增的 "testsEnabled": "VMessAEAD"，相关协议更新：[这里](https://www.v2fly.org/chapter_02/protocols/vmess.html#vmessaead-%E5%A4%B4%E9%83%A8%E5%8A%A0%E5%AF%86%E5%AE%9E%E9%AA%8C-%EF%BC%88%E5%85%AC%E6%B5%8B%E9%98%B6%E6%AE%B5%EF%BC%89)  
希望下个版本的GUI添加编辑界面的出站设置位置加上 "testsEnabled": "VMessAEAD" 的设置，同时支持vmess://协议的导入支持读取并配置上。  
目前可以通过在连接配置文件上右键 `编辑为json`  来手动添加。

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/84387049-f9ebc600-ac24-11ea-854a-cc28acee73be.png)

**Comment by DuckSoft** [comment]
我们可能会在dev分支上暂时添加此功能。
若正式版发布之前，此功能已被官方启用为默认值，将不会随正式版放出。
