### ISSUE TITLE
DNS 分流配置不当造成节点连接失败一例

### ISSUE THREAD

**Issue by 763139102** [Qv2ray/Qv2ray#676]
# 简单描述这个 Bug:

双击订阅列表 提示 配置错误

# 如何复现这个 Bug：

1. 双击订阅列表

```
Qv2ray 日志：

2020/06/12 18:13:51 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /home/hchxue/.config/qv2ray/generated/config.gen.json
main: failed to create server > v2ray.com/core/app/dns: failed to create hosts > v2ray.com/core/app/dns: neither IP address nor proxied domain specified for domain: 

```

### 受影响的 Qv2ray 安装平台

- Linux   deepin v20  

### 首选项 -> 关于信息：

```
版本号: 2.6.0-rc3:5544
内部版本号：
编译信息：Qv2ray built from Github Action
其它编译信息：qt5.14.2-d761a974b843c7556dac78f04e3f9dde7c3e400e-ci.ubuntu-16.04
``

**Comment by DuckSoft** [comment]
检查设置中的 DNS 分流设置，看看是否设置了错误的选项。

**Comment by DuckSoft** [comment]
提示：检查此处：
![图片](https://user-images.githubusercontent.com/7822648/84493221-01b97200-acda-11ea-83d8-1b78c53f0c86.png)

**Comment by DuckSoft** [comment]
因无回复，暂时关闭本 Issue。
稍后你可考虑加入我们的 Telegram 群组与我们直接讨论。
http://t.me/qv2ray

**Comment by 763139102** [comment]
> 因无回复，暂时关闭本问题。
> 稍后你可考虑加入我们的电报群组与我们直接讨论。
> http://t.me/qv2ray


还是不行

**Comment by DuckSoft** [comment]
你不要光说"不行"，一张图、一个日志、一个具体的现象描述都能让我们对你的问题有更清晰的了解。
我们不是大魔导师，没有水晶球，更不可能隔着网线读心窥屏，望理解。

**Comment by DuckSoft** [comment]
如果确实不善言辞，你可以打开 Teamviewer，将其中的用户名和密码通过邮件发送至 realducksoft@gmail.com，可以帮你远程调试一下，20 分钟内有效。

**Comment by 763139102** [comment]
![截图录屏_选择区域_20200611114944](https://user-images.githubusercontent.com/25519902/84495242-59d08400-ac9a
![截图录屏_选择区域_20200612184813](https://user-images.githubusercontent.com/25519902/84495251-5dfca180-ac9a-11ea-9efa-8542bfca5efd.png)
![截图录屏_选择区域_20200612184819](https://user-images.githubusercontent.com/25519902/84495256-5e953800-ac9a-11ea-86fb-1ebc87a26c4d.png)
![截图录屏_选择区域_20200612184825](https://user-images.githubusercontent.com/25519902/84495260-5fc66500-ac9a-11ea-948b-9a77cde89921.png)


-11ea-92de-6ef629a3887e.png)
![截图录屏_选择区域_20200612184808](https://user-images.githubusercontent.com/25519902/84495245-5c32de00-ac9a-11ea-848a-f416baf1bc69.png)

**Comment by DuckSoft** [comment]
你两个入站都没开。
![图片](https://user-images.githubusercontent.com/7822648/84495321-8c4fa080-acdd-11ea-8740-1979ace3612d.png)

**Comment by 763139102** [comment]
> 你两个入站都没开。 把SOCKS设置和HTTP设置两个勾全勾上。
> ![图片](https://user-images.githubusercontent.com/7822648/84495321-8c4fa080-acdd-11ea-8740-1979ace3612d.png)


选择了也会报同样的错误

**Comment by DuckSoft** [comment]
请截图连接设置——DNS Settings——静态解析域名中的内容

**Comment by DuckSoft** [comment]
人还在吗？GitHub 上沟通不是很方便，有条件建议加入 Telegram 群讨论。
https://t.me/qv2ray

**Comment by 763139102** [comment]
> 人还在吗？GitHub的上沟通不是很方便，有条件建议加入电报群讨论。
> https://t.me/qv2ray

您好，刚刚下载了 Teamviewer，已发邮件，谢谢您的帮忙 ，https://t.me/qv2ray 地址打不开

**Comment by DuckSoft** [comment]
秒了。是你那里有个空项没删除导致的。
这个小问题已经在最新版修复了。

**Comment by DuckSoft** [comment]
@763139102 这次应该可以了。如果还有问题，请再开一个 Issue。

**Comment by 763139102** [comment]
> @ 763139102这个应该可以了。如果还有问题，请再开一个问题。

好的，再次感谢
