### ISSUE TITLE
Qv2ray v2.6.0-rc3 界面过大撑爆 720P 小屏电脑

### ISSUE THREAD

**Issue by mini536** [Qv2ray/Qv2ray#678]
![图片](https://user-images.githubusercontent.com/32984303/84517531-06921c00-ad02-11ea-92cb-df599dc963ca.png)
如图，由于软件窗口偏大，我电脑没法按确定
版本是2.6 rc3

**Comment by DuckSoft** [comment]
Assigned to @Qv2ray-dev.

**Comment by Qv2ray-dev** [comment]
@mini536 你的屏幕分辨率是 1366x768 吗？

**Comment by cangyin** [comment]
可以暂时先用 Enter 键代替鼠标。

**Comment by mini536** [comment]
> 
> 
> @mini536 你的屏幕分辨率是 1366x768 吗？

对

**Comment by Qv2ray-dev** [comment]
@mini536 试用一下 dev 分支的最新版本 https://github.com/Qv2ray/Qv2ray/actions/runs/133844163

**Comment by mini536** [comment]
> 
> 
> @mini536 试用一下 dev 分支的最新版本 https://github.com/Qv2ray/Qv2ray/actions/runs/133844163

![图片](https://user-images.githubusercontent.com/32984303/85091772-d58e7b80-b21a-11ea-9701-fb181b60406d.png)
分支版本可以了

**Comment by Qv2ray-dev** [comment]
Thanks, closed.
