### ISSUE TITLE
为啥用Qv2ray无法观看B站港澳台视频，而用V2rayN跟Clash就能正常访问？还有在用aniGamerPlus下载动画疯视频时建立和加载下载任务的速度也比那两个客户端慢。

### ISSUE THREAD

**Issue by YFTX2015** [Qv2ray/Qv2ray#679]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:

# 如何复现这个 Bug：

1. 
2. 
3. 
4. 

### 相关截图或日志

<details>

```
Qv2ray 日志：


```

</details>

### 受影响的 Qv2ray 安装平台

- Linux
- macOS
- Windows

### 受影响的 Qv2ray 安装源

- ArchLinuxCN - 稳定版
- ArchLinuxCN - 开发版
- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版
- Fedora - 稳定版
- Fedora - 开发版
- openSUSE - 稳定版
- openSUSE - 开发版
- Flathub 包
- Snap 包
- Homebrew Cask
- Scoop
- Chocolatey
- 手动编译
- Github Release

### 首选项 -> 关于信息：

```
版本号: 
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by DuckSoft** [comment]
提问之前先阅读用户手册，是一个比较好的习惯。
https://qv2ray.github.io/getting-started/step5.html#%E8%B0%83%E6%95%B4%E8%B7%AF%E7%94%B1%E6%96%B9%E6%A1%88
