### ISSUE TITLE
Debian GNOME 随开机启动时无顶栏图标

### ISSUE THREAD

**Issue by Wings-Fantasy** [Qv2ray/Qv2ray#680]
# 简单描述这个 Bug:

软件设置开机启动，开机后，托盘不显示软件图标。但是通过查看后台进程确认软件启动成功，并且可以正常使用，只是没有显示图标

# 如何复现这个 Bug：

1. 在软件中勾选开机启动
2. 重启计算机

### 受影响的 Qv2ray 安装平台

- Linux

### 受影响的 Qv2ray 安装源

- Github Release

### 首选项 -> 关于信息：

```
版本号: 2.5.0
内部版本号：2.5.0
编译信息：Qv2ray from manual build
其它编译信息：Qv2ray 2.5.0:5335
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

OS：Debian Linux
DE：GNOME
使用了TopIcons Plus扩展(已尝试不使用扩展，依旧出现问题)

**Comment by Qv2ray-dev** [comment]
GNome 对于 Qt 程序的兼容性欠佳，我认为是 Upstream 问题

**Comment by DuckSoft** [comment]
https://qv2ray.github.io/faq/#_1-qv2ray-%E5%9C%A8-gnome-%E4%B8%8A%E7%9A%84%E6%89%98%E7%9B%98%E5%9B%BE%E6%A0%87%E4%BC%9A%E5%81%B6%E5%B0%94%E6%B6%88%E5%A4%B1

上游问题无误。你可以尝试一下这里的解决方案，或者更直接一点，KDE 真香。

**Comment by 17hao** [comment]
@Wings-Fantasy 可以试下gnome插件[AppIndicator](https://extensions.gnome.org/extension/615/appindicator-support/)
