### ISSUE TITLE
feature request about Advanced Route Settings 

### ISSUE THREAD

**Issue by cangyin** [Qv2ray/Qv2ray#681]
![image](https://user-images.githubusercontent.com/50256182/84585379-dbaee180-ae41-11ea-94fd-ccf266c63bee.png)

能不能做个语法糖，把这个 domain: 前缀去掉。

**Comment by Qv2ray-dev** [comment]
不可，因为在 V2ray 配置中，带 domain 和不带 domain 是两种不同的概念
