### ISSUE TITLE
蓝屏后配置文件损坏

### ISSUE THREAD

**Issue by WangJJ1121** [Qv2ray/Qv2ray#682]
# 简单描述这个 Bug:

不确定原因蓝屏后, 会造成配置文件损坏. 

# 如何复现这个 Bug：

自从安装了wireshark之后, 电脑开始出现蓝屏(无法导出蓝屏信息). 重启后, Qv2ray会出现配置文件损坏的提示, 要求把损坏文件删除后重新配置. 

不知道v2ray核心或Qv2ray与wireshark是否有冲突造成蓝屏, 但把wireshark卸载后依然会出现蓝屏造成同样的错误. 希望能获得一些建议.

### 相关截图或日志

![360截图17340909115118156](https://user-images.githubusercontent.com/39559535/84590990-7ec92080-ae6d-11ea-8373-b984a7cb7cc1.png)

### 受影响的 Qv2ray 安装平台

- Windows10 1903

### 受影响的 Qv2ray 安装源

- Github Release 2.5.0

### 已安装的插件 & 插件安装源：

Qv2ray Command 插件 v1  
QvPlugin-Trojan v1.0.2  
QvPlugin-SSR v1.0.5

**Comment by DuckSoft** [comment]
这个问题在 2.6.0 已有改进，但蓝屏等不可抗力导致的配置文件丢失，请恕我等无能为力。
若你发现了代码哪里可以改进，欢迎提交 Pull Request。

**Comment by DuckSoft** [comment]
PS：Wireshark、Qv2ray、V2Ray 核心应该都是无辜的，有问题的是 Windows 自己。

> 当你对着别人说︰“我写了能让 Windows 当机的程式”，别人只会白你一眼，并说︰“喂，我装好系统的时候就免费带着了”。
> ——Torvalds, Linus. Post to comp.os.linux.development.apps newsgroup. 1995-03-08 [2006-08-28].

**Comment by WangJJ1121** [comment]
谢谢.
