### ISSUE TITLE
希望可以添加自动更新订阅功能

### ISSUE THREAD

**Issue by adinlead** [Qv2ray/Qv2ray#683]
希望可以添加自动更新订阅功能,或者去掉点击更新订阅时的确认弹窗;或者直接在首页增加个"更新全部订阅"的按钮

**Comment by Qv2ray-dev** [comment]
Working in progress

**Comment by Famingwu** [comment]
哈哈，我也想说这个问题，希望安静模式下自动按照设定频率更新订阅，而不是弹出窗口让我手动更新，最好还能自动添加自动连接质量好的线路

**Comment by Qv2ray-dev** [comment]
fixed in https://github.com/Qv2ray/Qv2ray/commit/3dc2f4bfbd1e320336e2063e030379ad468f95b2
