### ISSUE TITLE
请问 V2Ray 4.24.2 加入的 VMessAEAD 会尽快支持吗？

### ISSUE THREAD

**Issue by AIrSkycc** [Qv2ray/Qv2ray#685]
https://www.v2fly.org/chapter_02/protocols/vmess.html#userobject

**Comment by DuckSoft** [comment]
这是个试验性选项，未来即使不开这个开关也会默认启用。
我们在即将放出的 Qv2ray v2.6.0-rc4 预览版中包含此功能。

**Comment by DuckSoft** [comment]
Added as a blocker of #701.

**Comment by Qv2ray-dev** [comment]
fixed.

**Comment by DuckSoft** [comment]
已在最新的 dev 分支中实现，将包含在 Qv2ray v2.6.0 正式版中发出。
