### ISSUE TITLE
无法打开本地插件目录

### ISSUE THREAD

**Issue by xbk2000** [Qv2ray/Qv2ray#689]
操作系统是ubuntu18.04，使用AppImage文件运行，点击打开本地插件目录，没有任何反应。

**Comment by DuckSoft** [comment]
大概是 xdg-open 的问题。已提交给 AppImage 维护者。
你可以手动创建这个目录：`mkdir -p $HOME/.config/qv2ray/plugins`。

**Comment by ymshenyu** [comment]
已在2.6.0+修复。

**Comment by tzsword** [comment]
> 大概是 xdg-open 的问题。已提交给 AppImage 维护者。
> 你可以手动创建这个目录：`mkdir -p $HOME/.config/qv2ray/plugins`。

使用snap安装的，同系统版本，　也是打不开

**Comment by DuckSoft** [comment]
> > 大概是 xdg-open 的问题。已提交给 AppImage 维护者。
> > 你可以手动创建这个目录：`mkdir -p $HOME/.config/qv2ray/plugins`。
> 
> 使用snap安装的，同系统版本，　也是打不开

若确定这个问题在 2.6.0 以上的版本仍然存在（snap 要用 --edge 选项安装），请开一个新 Issue 报告。

**Comment by tzsword** [comment]
> > > 大概是 xdg-open 的问题。已提交给 AppImage 维护者。
> > > 你可以手动创建这个目录：`mkdir -p $HOME/.config/qv2ray/plugins`。
> > 
> > 
> > 使用snap安装的，同系统版本，　也是打不开
> 
> 若确定这个问题在 2.6.0 以上的版本仍然存在（snap 要用 --edge 选项安装），请开一个新 Issue 报告。

edge开发版可以了　谢谢
