### ISSUE TITLE
自动连接bug

### ISSUE THREAD

**Issue by EA-DICE** [Qv2ray/Qv2ray#690]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:
在自动连接选项，固定连接复选框勾选后无法选择具体服务器
![image](https://user-images.githubusercontent.com/42771283/85204106-ad02a080-b344-11ea-8769-55d2e083ede8.png)

# 如何复现这个 Bug：

1. 选择固定连接
2. 下方配置选项中无法选择具体节点
3. 
4. 

### 相关截图或日志

<details>

```
Qv2ray 日志：


```

</details>

### 受影响的 Qv2ray 安装平台
- Windows
### 受影响的 Qv2ray 安装源
- Github Release
### 已安装的插件 & 插件安装源：
trojanplugin1.0.2＆GitHub release
### 首选项 -> 关于信息：

```
版本号: 2.6.0-rc4:5625
内部版本号：
编译信息：Qv2ray built from Github Action
其它编译信息：qt5.14.2-d04cb5b1de4711306de893ef8f803276a7810b4f-ci.windows-latest
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by Qv2ray-dev** [comment]
![image](https://user-images.githubusercontent.com/59914293/85213964-f8926a00-b397-11ea-8095-6ff1a6db398c.png)

未能复现问题，请确认你所说的 “下方配置选项中无法选择具体节点” 指什么行为？

附上屏幕录制可以帮我们更好的定位/解决问题

**Comment by EA-DICE** [comment]
> ![image](https://user-images.githubusercontent.com/59914293/85213964-f8926a00-b397-11ea-8095-6ff1a6db398c.png)
> 
> 未能复现问题，请确认你所说的 “下方配置选项中无法选择具体节点” 指什么行为？
> 
> 附上屏幕录制可以帮我们更好的定位/解决问题

稍后带来演示

**Comment by Qv2ray-dev** [comment]
好的，感谢

**Comment by EA-DICE** [comment]
抱歉，刚刚有急事，现在上传一个视频，如视频所示，我仅可以选择分组而无法选择具体服务器

[媒体1.zip](https://github.com/Qv2ray/Qv2ray/files/4808801/1.zip)

**Comment by Qv2ray-dev** [comment]
你的默认组内有链接配置吗？

**Comment by EA-DICE** [comment]
> 你的默认组内有链接配置吗？
> 我这里无法复现
我使用订阅链接，组内有多个节点

**Comment by Qv2ray-dev** [comment]
这个问题原因未知，现阶段解决方案是：
主界面右键点击一个节点，然后“设置为自动链接”

**Comment by EA-DICE** [comment]
> 这个问题原因未知，现阶段解决方案是：
> 主界面右键点击一个节点，然后“设置为自动链接”

收到

**Comment by EA-DICE** [comment]
> 这个问题原因未知，现阶段解决方案是：
> 主界面右键点击一个节点，然后“设置为自动链接”

Windows上也无法复现吗

**Comment by DuckSoft** [comment]
玄学问题……先关掉了
