### ISSUE TITLE
Windows 平台下异步 TCPing 延迟测定数值异常

### ISSUE THREAD

**Issue by FANminiworld** [Qv2ray/Qv2ray#694]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:

部分情况下延时测量结果过大

# 如何复现这个 Bug：

在主界面左侧节点选择区域    右键----测试延迟    即可复现    【反复执行  断网----联网  （趁网络不注意赶紧测试延迟）  复现机率更高】

### 如果是连接问题，在其他 v2ray 客户端里出现过吗？ 

非连接问题，没有

### 相关截图或日志

<details>

一些截图：  （其中部分是沙雕群友提供的）

![Bug 反馈 1 ](https://user-images.githubusercontent.com/49353343/85352375-62e21080-b538-11ea-8c25-b2bc91a38642.jpg)

![Bug 反馈 2 ](https://user-images.githubusercontent.com/49353343/85352470-9b81ea00-b538-11ea-830e-59b707350800.jpg)

![Bug 反馈 3 ](https://user-images.githubusercontent.com/49353343/85353134-24e5ec00-b53a-11ea-9f52-7f7d28c7a0c4.jpg)

![Bug 反馈 4 ](https://user-images.githubusercontent.com/49353343/85353145-29120980-b53a-11ea-9a22-ed1868131131.jpg)

</details>

<details>

```

Qv2ray 日志：

没有。。。。。。

```

</details>

### 受影响的 Qv2ray 安装平台

- Windows

### 受影响的 Qv2ray 安装源

- Github Release

### 已安装的插件 & 插件安装源：

Trojan Plugin  `https://github.com/Qv2ray/QvPlugin-Trojan/releases/tag/v2.0.0-pre3`
NaiveProxy Plugin  `https://github.com/Qv2ray/QvPlugin-NaiveProxy/releases/tag/v0.1.0-rc3`
SSR Plugin  `https://github.com/Qv2ray/QvPlugin-SSR/releases/tag/v2.0.0-pre5`

### 首选项 -> 关于信息：

![Bug 反馈 5 ](https://user-images.githubusercontent.com/49353343/85353655-5ad7a000-b53b-11ea-9ed3-ffd0309febfa.jpg)

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by DuckSoft** [comment]
这是 Bugdows 平台的已知问题，应该与日前引入的异步测速有关。
近期将进行调查。

**Comment by DuckVador** [comment]
@FANminiworld  https://github.com/Qv2ray/Qv2ray/actions/runs/148874451  可以试一下这个action里面的版本，是否还有同样问题

**Comment by FANminiworld** [comment]
> @FANminiworld https://github.com/Qv2ray/Qv2ray/actions/runs/148874451 可以试一下这个action里面的版本，是否还有同样问题

TCPing 、 ICMPing  暂时无法复现

**Comment by DuckSoft** [comment]
Good! Thanks! @DuckVador @FANminiworld
