### ISSUE TITLE
建议添加右键快捷展示所有节点选择的功能

### ISSUE THREAD

**Issue by madinghui** [Qv2ray/Qv2ray#698]
建议在任务栏右键添加快捷选择节点的功能，挺方便的，不然还得打开选

**Comment by 2utv** [comment]
可以在最近连接选取直接点击。默认10个显示不够的话还可以设置中改。

**Comment by Qv2ray-dev** [comment]
@2utv 所以你是再说已经实现了的功能嘛？

**Comment by DuckSoft** [comment]
因为已有“最近使用”列表，暂时不考虑添加此功能。
