### ISSUE TITLE
建議添加LoadBalance負載均衡功能。

### ISSUE THREAD

**Issue by noah137** [Qv2ray/Qv2ray#702]
V2Ray原版支持LoadBalance，希望Qv2ray也加上
LoadBalance的好處：
可以同時消耗多個小雞的流量，降低每個小雞的CPU和RAM占用。
使用LoadBalance更容易讓GFW識別為訪問正常網站，通過訪問不同而不是只訪問一個網站讓GFW的干擾風險降低。

**Comment by DuckSoft** [comment]
原版的 LoadBalancer 我们测试过，他是一个非常简单的伪随机，不适合实际使用。
我们已经在复杂路由编辑器里支持此功能。请细心挖掘。
