### ISSUE TITLE
高级路由设置配置

### ISSUE THREAD

**Issue by lbhnrg2021** [Qv2ray/Qv2ray#704]
高级路由设置配置无法成功，总是走代理，绕过中国大陆选项我也关了，有没有类似白名单代理的配置案例

**Comment by DuckSoft** [comment]
且问一句：你是凭什么断定那个东西走"代理"了？
提示：分流与否要看日志，日志说 outBound_PROXY 就是走代理，outBound_DIRECT 就是直连，outBound_BLOCK 就是阻断。
光看速度图像那可不行，那是总流量。

**Comment by lbhnrg2021** [comment]
就是因为日志都走了proxy才来issues

**Comment by DuckSoft** [comment]
请截图相关设置和相关日志。

**Comment by lbhnrg2021** [comment]
![TIM截图20200627152937](https://user-images.githubusercontent.com/11476217/85917240-06aa2400-b88b-11ea-8fe7-6d755506f019.png)
![TIM截图20200627153011](https://user-images.githubusercontent.com/11476217/85917259-22152f00-b88b-11ea-8ae5-1b5dfa96c75d.png)

**Comment by lbhnrg2021** [comment]
我到是在直连配了geosite:cn，大部分国内站点就不走代理了

**Comment by lbhnrg2021** [comment]
先这么搞，谢谢了

**Comment by ppanphper** [comment]
同样的问题，绕过中国大陆的选项没用

**Comment by DuckSoft** [comment]
> 同样的问题，绕过中国大陆的选项没用

请勿挖坟。
