### ISSUE TITLE
macOS 2.6.0-rc4:5677 手速够快仍然可以点开一堆首选项窗口

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#709]
> Linked Issue: #706

#706 中在 Linux 下测试，问题已经修复，但在 macOS 下仍然可以复现：

![图片](https://user-images.githubusercontent.com/7822648/85939319-d4f69300-b946-11ea-8f2d-022e755b9f2c.png)

**Comment by EpLiar** [comment]
提供一下更多细节

* 不需要手速，等待若干秒甚至几分钟都可以复现
* Dock 栏上的 Qv2ray 图标，右键点击退出无法关闭弹出来的窗口，也无法关闭主程序
* 托盘图标点击退出可以正常关闭所有窗口

**Comment by DuckSoft** [comment]
> 提供一下更多细节
> 
>     * 不需要手速，等待若干秒甚至几分钟都可以复现
> 
>     * Dock 栏上的 Qv2ray 图标，右键点击退出无法关闭弹出来的窗口，也无法关闭主程序
> 
>     * 托盘图标点击退出可以正常关闭所有窗口

后两点将拆分成另一个独立的 Issue。

**Comment by EpLiar** [comment]
> > 提供一下更多细节
> > ```
> > * 不需要手速，等待若干秒甚至几分钟都可以复现
> > 
> > * Dock 栏上的 Qv2ray 图标，右键点击退出无法关闭弹出来的窗口，也无法关闭主程序
> > 
> > * 托盘图标点击退出可以正常关闭所有窗口
> > ```
> 
> 后两点将拆分成另一个独立的 Issue。

第二点是基于多首选项的前提下的

**Comment by EpLiar** [comment]
测试了一下，2.6.1 和 2.6.2 已经不会出现多首选项窗口的场景，Close.
