### ISSUE TITLE
macOS Dock 栏上的 Qv2ray 图标右键点击退出可能无法关闭窗口

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#710]
> Referenced from #709

在 #709 的基础上：Dock 栏上的 Qv2ray 图标，右键点击退出无法关闭弹出来的窗口，也无法关闭主程序
托盘图标点击退出可以正常关闭所有窗口

**Comment by EpLiar** [comment]
只要首选项有至少一个窗口，右键 Dock 图标就会无法退出

**Comment by EpLiar** [comment]
依旧存在。

**Comment by U-v-U** [comment]
Should be a feature, not a bug?

**Comment by dyhkwong** [comment]
这个 issue 不是 macOS only，其他平台也能复现；右键点击退出等效于点击主窗口的关闭按钮，在有其他窗口打开的情况下主窗口的关闭按钮是失焦无法点击的，无法触发关闭事件。（应当不是 bug 是 feature，许多其他 Qt 程序、非 Qt 程序也这样，比如 qBittorrent）
