### ISSUE TITLE
计划：原生的分出站的流量统计

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#711]
上游 PR 即将被合并：https://github.com/v2fly/v2ray-core/pull/38
若上游在 Qv2ray 2.6.0 发布 Deadline 之前足够长的时间合并，我们或将支持其中的分出站的流量统计。

**Comment by Qv2ray-dev** [comment]
Waiting for #741

**Comment by Qv2ray-dev** [comment]
Done, Closing
