### ISSUE TITLE
Feature request: latency test in batch mode

### ISSUE THREAD

**Issue by idnsunset** [Qv2ray/Qv2ray#712]
Can qv2ray support performing latency test on all selected nodes? I've tried the latest 2.6.0-rc4, it seems to test only the last one in the queue.

**Comment by Qv2ray-dev** [comment]
@idnsunset You may want to try right-clicking the selected nodes.

**Comment by idnsunset** [comment]
> @idnsunset You may want to try right-clicking the selected nodes.

I just select a group of nodes and right click to choose "test latency", but only the last one is my selection gets tested.

**Comment by Qv2ray-dev** [comment]
@idnsunset Confirmed, Thanks. WIP

**Comment by Qv2ray-dev** [comment]
fixed, closing

**Comment by DuckSoft** [comment]
@Qv2ray-dev ps: this functionality will be released in Qv2ray v2.6.0 stable version. thanks for your great idea.
