### ISSUE TITLE
Feature Request + Error

### ISSUE THREAD

**Issue by asterriya** [Qv2ray/Qv2ray#713]
Is that possible to add feature like "share over lan"?
When I choose Ipifnotmatch then my connection always break up sites and after reload they are start to work
My v2ray + ssr config start to connect and work smoothly when I choose only quiet mode
When I rename my config time to time it's crash Qv2ray

**Comment by Qv2ray-dev** [comment]
@asterriya Read the doc

**Comment by Qv2ray-dev** [comment]
Crashing when renaming a connection has been fixed.

**Comment by Qv2ray-dev** [comment]
https://qv2ray.github.io/getting-started/step5.html#%E5%9F%BA%E4%BA%8E%E6%9C%AC%E5%9C%B0%E7%BD%91%E7%BB%9C%E7%9A%84%E4%BB%A3%E7%90%86%E5%85%B1%E4%BA%AB

**Comment by asterriya** [comment]
> Crashing when renaming a connection has been fixed.

No. I try 2.5.0 and last pre-release. The same error time to time

**Comment by Qv2ray-dev** [comment]
It's not the pre-release, the fix is still in `dev` branch

**Comment by asterriya** [comment]
Oh, ok. Waiting then. And what about Android version with plugin support?

**Comment by Qv2ray-dev** [comment]
@asterriya We are not working on the Android version recently, please wait till Sept/October

**Comment by asterriya** [comment]
> @asterriya We are not working on the Android version recently, please wait till Sept/October

will it support plugins too?

**Comment by Qv2ray-dev** [comment]
@asterriya We hope so.
Due to technical limitations, we MAY want to bundle the plugins (together with the vCore)

These are NOT the final decisions, things may change from time to time.

**Comment by asterriya** [comment]
And please ad option inside Qv2ray to update itself automatically including plugins and v2ray core

**Comment by asterriya** [comment]
When I choose "Ipifnotmatch" then my connection always break up sites and after reload they are start to work

**Comment by Qv2ray-dev** [comment]
@asterriya No it's our design.
Users should AT LEAST know how to download and read documentations BEFORE using Qv2ray.

It's the lowest boundary when using Qv2ray.

**Comment by Qv2ray-dev** [comment]
@asterriya Did you mean the it reconnects?
Or ...?

You may want to write in Chinese if it's more convenient.

**Comment by asterriya** [comment]
> @asterriya Did you mean the it reconnects?
> Or ...?
> 
> You may want to write in Chinese if it's more convenient.

I don't know Chinese and no. It's not reconnected. Just broke all sites

**Comment by asterriya** [comment]
Also My v2ray + ssr config start to connect and work smoothly when I choose only quiet mode

**Comment by Qv2ray-dev** [comment]
> I don't know Chinese and no. It's not reconnected. Just broke all sites

Oops, Sorry.

You said "broke all sites", changing `IpIfNonMatch` settings will automatically re-connect the active connection after you click "OK" in the Preferences Window.

You may want to configure a stable DNS server since `IpIfNonMatch` will perform a DNS query if your target domain is not in the `domains` list. (And continue trying to match the IPs' rule after the DNS query.)

For more information, please see: 

https://www.v2fly.org/en/configuration/routing.html#routingobject
https://www.v2fly.org/en/configuration/dns.html

**Comment by asterriya** [comment]
Yes I know about that but still it's well working only with AsIs rule. I even try to clear cache and cookies and Try to add dns inside q2vray by myself but still it's doesn't work with IfIpnotmatch.
