### ISSUE TITLE
请问qv2ray是将域名转发给代理还是将ip转发给代理呢？

### ISSUE THREAD

**Issue by yuerongz97** [Qv2ray/Qv2ray#715]
如题，假如我访问的网站需要走代理，请问qv2ray是将该域名转发给代理呢，还是将解析后的ip转发给代理呢？

**Comment by DuckSoft** [comment]
Qv2ray 本身没有代理功能。
Qv2ray 依靠 V2Ray 核心实现其代理功能。
你应该问的是：V2Ray 是将你的域名转发给代理，还是将解析后的 IP 转发给代理。

如此，请参见上游文档（ https://guide.v2fly.org ），或去上游发帖（ https://github.com/v2ray/discussion/issues ）询问。
