### ISSUE TITLE
Ubuntu 强制断电重启导致配置文件内容丢失

### ISSUE THREAD

**Issue by Laputa0** [Qv2ray/Qv2ray#721]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

# 简单描述这个 Bug:
在Qv2ray已启动的情况下，强制断电重启，会导致配置文件清空，无法启动Qv2ray，只能删除qv2ray文件夹，重新生成配置文件。

# 如何复现这个 Bug：

1. 电脑强制断电重启

### 受影响的 Qv2ray 安装平台

- Linux

### 受影响的 Qv2ray 安装源

- Github Release

### 首选项 -> 关于信息：

```
版本号: 2.6.0-rc4:5625
内部版本号：
编译信息：Qv2ray from manual build
其它编译信息：Qv2ray 2.6.0-rc4:5625
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

系统环境:Ubuntu 20.04 LTS x64

**Comment by DuckSoft** [comment]
强制断电这个……好像真救不了。我们将尽力进行优化。
若你有什么好主意，欢迎与我们分享。

**Comment by Laputa0** [comment]
我的想法是自动备份一个配置文件，如果那个配置文件为空就将备份的那个复制过来，我也不太懂，说不定有更好的方法

**Comment by Qv2ray-dev** [comment]
说不定 crontab 会帮助你实现此功能
Qv2ray 确实无法预知断电问题，另外每次启动都备份我认为不是好方法（？）

**Comment by Laputa0** [comment]
我是不太明白一个文件突然掉电内容为什么会清空，其他的文件一般没有这种情况。
