### ISSUE TITLE
分享：mips64el 架构的 Qv2ray 构建方式

### ISSUE THREAD

**Issue by lophyxp** [Qv2ray/Qv2ray#722]
我编译完成了并使用了mips64el架构的Qv2ray
具体步骤如下：

1. 从https://github.com/Qv2ray/Qv2ray/releases下载tarball，https://github.com/Qv2ray/Qv2ray/archive/v2.6.0-rc4.tar.gz
2.安装编译期依赖apt install qttools5-dev libprotobuf-dev libgrpc++-dev libgrpc-dev protobuf-compiler-grpc protobuf-compiler libprotobuf-c-dev protobuf-c-compiler（这个依赖能够完成编译，但是不纯净，有冗余）
3.下载各个子模块，并把它们放到正确的位置：
https://github.com/Qv2ray/QvPlugin-Interface        => src/plugin-interface
https://github.com/Qv2ray/QvUIStyles                => 3rdparty/uistyles
https://github.com/Qv2ray/x2struct                  => 3rdparty/x2struct
https://github.com/Qv2ray/zxing-cpp                 => 3rdparty/zxing-cpp
https://github.com/Qv2ray/QNodeEditor               => 3rdparty/QNodeEditor
https://github.com/itay-grudev/SingleApplication    => 3rdparty/SingleApplication
https://github.com/diegolagoglez/libsemver          => 3rdparty/libsemver
https://github.com/Qv2ray/QJsonStruct               => libs/QJsonStruct
https://github.com/Qv2ray/PureSource                => libs/puresource
https://github.com/Qv2ray/QvRPCBridge               => lib/libqvb
4.配置
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
5.编译
make
6.安装
sudo make install

用起来很爽，真的很爽！尤其是全局代理，太棒了！我还以为墙塌了呢！

- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:
我现在遇到问题是 sudo make install安装很不清真，我想制作deb包。但是没有成功……

# 如何复现这个 Bug：
我尝试了
1. 
cd build
make package
提示：
make: *** 没有规则可制作目标“package”。 停止。
2. 
cd build
cd ..
ln -s debian DEBIAN
cd ..
dpkg-deb -b Qv2ray-2.6.0-rc3/
提示：
dpkg-deb: 错误: 正在解析文件 'Qv2ray-2.6.0-rc3//DEBIAN/control' 第 21 行附近，软件包 'qv2ray:any' :
 Depends 字段，无效的软件包名 ${shlibs :必须以字母或数字开头

### 如果是连接问题，在其他 v2ray 客户端里出现过吗？ 
不牵扯

### 相关截图或日志
不牵扯

## 系统信息 （请删掉不符合的项）
lophyxp@loongson-L39
OS: Debian testing bullseye
Kernel: mips64 Linux 5.2.5-lophyxp
Uptime: 2h 58m
Packages: 2290
Shell: bash
Resolution: 1920x1080
DE: KDE 5.70.0 / Plasma 5.17.5
WM: KWin
GTK Theme: Breeze [GTK2/3]
Icon Theme: breeze
Font: Noto Sans Regular
Disk: 86G / 191G (48%)
CPU: 4x UnknownICT Loongson-3 V0.13 FPU V0.1
GPU: AMD/ATI Oland [Radeon HD 8570 / R7 240/340 / Radeon 520 OEM]
RAM: 2669MiB / 8014MiB

### 受影响的 Qv2ray 安装平台

- Linux
debian bullseye mips64el
- macOS
不牵扯
- Windows
不牵扯

### 受影响的 Qv2ray 安装源
- 手动编译

### 已安装的插件 & 插件安装源：
无

### 首选项 -> 关于信息：

```
版本号: 2.6.0-rc3:5544
内部版本号：
编译信息：Qv2ray from manual build
其它编译信息：Qv2ray 2.6.0-rc3:5544
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
**我应该使用怎样的指令来制作Qv2ray的deb包呢？**

**Comment by lophyxp** [comment]
补充：vcore的安装步骤如下：
https://github.com/v2ray/v2ray-core/releases
unzip v2ray-linux-mips64le.zip -d v2ray
mv v2ray ~/.config/qv2ray/vcore

**Comment by lophyxp** [comment]
摸索出来了，打包步骤如下：
apt install ninja-build

cd Qv2ray-2.6.0-rc3

cd build && \
make clean && \
cd .. && \
tar czvf ../qv2ray_2.6.0~rc3.orig.tar.gz .

dpkg-buildpackage -us -uc

**Comment by Qv2ray-dev** [comment]
✌️ 感谢支持 Qv2ray!

**Comment by DuckSoft** [comment]
@ymshenyu 考虑支持一下 mips64el 架构吗？

**Comment by Qv2ray-dev** [comment]
已知使用 Action 打包 arm 需要两个小时
不知道 mips 会用多长时间

**Comment by lophyxp** [comment]
CPU:龙芯3A3000 4核心 1.2G
mips64el打包需要大约一个半到两个小时。

**Comment by Qv2ray-dev** [comment]
@DuckSoft Should we write these in the doc?

**Comment by DuckSoft** [comment]
[qv2ray_2.6.0~rc4-1_mips64el.deb.zip](https://github.com/Qv2ray/Qv2ray/files/4875160/qv2ray_2.6.0.rc4-1_mips64el.deb.zip)

在 Debian Buster 上打出来了……i5-7200U，大概花了40分钟。
其实很简单。凑齐依赖之后 `dpkg-buildpackage -us -uc` 就完事了。

稍晚些时候将更新文档。感谢分享。

**Comment by lophyxp** [comment]
关于新版本v2.6.0正式版的打deb包

基于第一层楼的RC3的3rdparty libs的源代码，有更新的在下面提示更新

https://github.com/Qv2ray/Qv2ray/releases

tar xzvf v2.6.0.tar.gz

cd Qv2ray-2.6.0-rc3/
cp -a 3rdparty ../Qv2ray-2.6.0/
cp -a libs ../Qv2ray-2.6.0/
cp -a src/plugin-interface ../Qv2ray-2.6.0/src

# update source code need
https://github.com/Qv2ray/QJsonStruct               => libs/QJsonStruct

cd ../Qv2ray-2.6.0
tar czvf ../qv2ray_2.6.0.orig.tar.gz .

apt install qtdeclarative5-dev

dpkg-buildpackage -us -uc

# 2020-07-10 14:31:00
# 2020-07-10 15:44:00
龙芯3A3000 4核心 1.2G 大约编译了不到一个小时。（开始时由于编译依赖出错了一次。临近结束时我给家里干活，没有一直盯着，空闲了一会儿）

**Comment by lophyxp** [comment]
# Qv2ray-2.6.3

https://github.com/Qv2ray/QvPlugin-Interface        => src/plugin-interface
https://github.com/nu-book/zxing-cpp                => 3rdparty/zxing-cpp

https://github.com/Qv2ray/QNodeEditor               => 3rdparty/QNodeEditor

https://github.com/itay-grudev/SingleApplication    => 3rdparty/SingleApplication
https://github.com/diegolagoglez/libsemver          => 3rdparty/libsemver

### https://github.com/Qv2ray/shadowsocksr-uvw is bad choose! broken compile!
https://github.com/skypjack/uvw                     => 3rdparty/uvw
https://github.com/libuv/libuv                      => 3rdparty/libuv

### https://github.com/Qv2ray/QJsonStruct is bad choose! broken compile!
https://github.com/bczol/QJsonStruct                => libs/QJsonStruct
https://github.com/Qv2ray/PureSource                => libs/puresource

apt install debhelper ninja-build libgrpc++-dev libprotobuf-dev protobuf-compiler protobuf-compiler-grpc qtbase5-dev qtdeclarative5-dev qttools5-dev

cd Qv2ray-2.6.3

tar czvf ../qv2ray_2.6.3.orig.tar.gz .

dpkg-buildpackage -us -uc

# vcore
https://github.com/v2ray/v2ray-core/releases
unzip v2ray-linux-mips64le.zip -d v2ray
mv v2ray ~/.config/qv2ray/vcore
