### ISSUE TITLE
分组订阅里面 Group：opvwt组和默认组 无法删除，删除后还会自动新增

### ISSUE THREAD

**Issue by EvanQuCN** [Qv2ray/Qv2ray#726]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:

分组订阅里面 Group：opvwt组和默认组 无法删除，删除后还会自动新增

# 如何复现这个 Bug：

1. 
2. 
3. 
4. 

### 如果是连接问题，在其他 v2ray 客户端里出现过吗？ 
有

### 相关截图或日志

<details>

```
Qv2ray 日志：


```

</details>

### 受影响的 Qv2ray 安装平台

- Linux
- macOS
- Windows

### 受影响的 Qv2ray 安装源

- ArchLinuxCN - 稳定版
- ArchLinuxCN - 开发版
- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版
- Fedora - 稳定版
- Fedora - 开发版
- openSUSE - 稳定版
- openSUSE - 开发版
- Flathub 包
- Snap 包
- Homebrew Cask
- Scoop
- Chocolatey
- 手动编译
- Github Release

### 首选项 -> 关于信息：

```
版本号: 
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by kidonng** [comment]
请问 opvwt 是什么组？默认情况下是没有的。
另外请提供详细的 Qv2ray 版本和系统信息。

**Comment by cangyin** [comment]
从这关软件的设计上来说，默认分组确实是不应该删除的，因为在删除其他含有节点的分组时，其中的节点会被移至默认分组。

**Comment by EpLiar** [comment]
对于 Qv2ray 的逻辑来说，会至少拥有一个组。opvwt 实际上是随机出来的名字，你可以对它直接改名。

同时你在受影响的平台里表示全平台影响，但是 Qv2ray 5677 并没有至少两个组的问题？

如果可以，请提供更多信息。

**Comment by EvanQuCN** [comment]
> 请问 opvwt 是什么组？默认情况下是没有的。
> 另外请提供详细的 Qv2ray 版本和系统信息。
Qv2ray 2.6.0-rc:5625

win10 64 2004


> 对于 Qv2ray 的逻辑来说，会至少拥有一个组。opvwt 实际上是随机出来的名字，你可以对它直接改名。
> 
> 同时你在受影响的平台里表示全平台影响，但是 Qv2ray 5677 并没有至少两个组的问题？
> 
> 如果可以，请提供更多信息。


![GIF 2020-7-2 9-21-55](https://user-images.githubusercontent.com/45114488/86305983-9cf09800-bc45-11ea-824e-ed0cc5acb94a.gif)

**Comment by cangyin** [comment]
我们暂时无法在 Windows 环境下复现你所遇到的问题，请加入我们的[ telegram 群组](https://t.me/qv2ray)，方便直接交流。

或者你可以尝试手动删除 `config/Qv2ray.conf` 文件，这样会删除所有分组信息。而后重新导入订阅。

**Comment by EvanQuCN** [comment]
好的 我尝试下 谢谢

**Comment by EpLiar** [comment]
@EvanQuCN 对于 5625 版本，我在 Win 10 上尝试对 bug 进行复现，没有复现成功。

如果可以，备份信息后重新安装一下当前版本，或是在 dev 分支安装最新的测试版。

为了确保纯净重装，卸载版本之后请删除 `C:\Users\USERNAME\AppData\Local\qv2ray` 的所有内容再安装

**Comment by EvanQuCN** [comment]
> @EvanQuCN 对于 5625 版本，我在 Win 10 上尝试对 bug 进行复现，没有复现成功。
> 
> 如果可以，备份信息后重新安装一下当前版本，或是在 dev 分支安装最新的测试版。
> 
> 为了确保纯净重装，卸载版本之后请删除 `C:\Users\USERNAME\AppData\Local\qv2ray` 的所有内容再安装

删除 config 重新打开后不会随机生成文件夹了,谢谢
默认文件夹 是没法删除的对吧
