### ISSUE TITLE
疑问：关于DNS

### ISSUE THREAD

**Issue by the-one-step** [Qv2ray/Qv2ray#728]
1. dns config
![Screenshot from 2020-07-02 10-36-05](https://user-images.githubusercontent.com/52375886/86310137-e0e89a80-bc4f-11ea-88d2-0e3a28495976.png)

2. 使用 https://nstool.netease.com/ 在线检测dns  与 v2ray设置里的DNS不一致
![Screenshot from 2020-07-02 10-37-39](https://user-images.githubusercontent.com/52375886/86310222-13929300-bc50-11ea-9052-a92e2c37ca8b.png)

**Comment by DuckSoft** [comment]
见图：绕过中国大陆

**Comment by the-one-step** [comment]
猜测这个dns 可能是线路那边的dns，但是为什么啊，明明本地设置了dns

**Comment by DuckSoft** [comment]
你有提前测过这个在线工具的准确性和可参考性如何吗？
自己裸连测一下看看？
