### ISSUE TITLE
第二章

### ISSUE THREAD

**Issue by the-one-step** [Qv2ray/Qv2ray#729]
关闭“绕过大陆” ， dns 还是“您的DNS地址信息: 47.90.108.197 阿里云”

没用V2Ray测试过了，是'您的DNS地址信息: 218.104.128.194 福建省厦门市联通'，用的是手机热点上网，联通号

**Comment by DuckSoft** [comment]
大哥，给你说了，网易怎么显示我们管不着，这个东西自己有没有问题都两说。
你不妨说一下你自己的顾虑，你为啥要测这个……

另外，你自己的 IP 地址和物理位置就这么草率的暴露了吗，记得打码呀

**Comment by the-one-step** [comment]
切换到中转线路后，dns又变为阿里云的dns

**Comment by DuckSoft** [comment]
你先说一下，你为啥要测这个，以及这个 DNS 对你/对 Qv2ray 有什么影响？

**Comment by DuckSoft** [comment]
咳，自己都弄不太明白的东西，又何必苦苦追求呢。
散了吧。

**Comment by the-one-step** [comment]
我猜测可能是线路服务商那边的dns，正在那边咨询这个问题..

**Comment by DuckSoft** [comment]
已经确定这个问题与 Qv2ray 无关。已锁定。
