### ISSUE TITLE
V2ray 核心设置不正确。  错误是：  V2ray Assets 路径不可用。

### ISSUE THREAD

**Issue by shanzhaozhen** [Qv2ray/Qv2ray#731]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:
V2ray 核心设置不正确。  错误是：  V2ray Assets 路径不可用。

# 如何复现这个 Bug：

1. 运行环境Fedora 32, Qv2ray 2.5.0
2. v2ray-core 确实也安装上了
3. 已经在首选项中的内核设置中设置好正确的v2ray-core路径
4. 可以正常执行v2ray-core
`[szz@localhost Downloads]$ /bin/v2ray/v2ray 
V2Ray 4.25.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)
A unified platform for anti-censorship.
2020/07/02 17:10:38 Using config from STDIN
`

### 相关截图或日志

<details>

```
Qv2ray 日志：


```

</details>

### 受影响的 Qv2ray 安装平台

- Linux
- macOS
- Windows

### 受影响的 Qv2ray 安装源

- ArchLinuxCN - 稳定版
- ArchLinuxCN - 开发版
- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版
- Fedora - 稳定版
- Fedora - 开发版
- openSUSE - 稳定版
- openSUSE - 开发版
- Flathub 包
- Snap 包
- Homebrew Cask
- Scoop
- Chocolatey
- 手动编译
- Github Release

### 首选项 -> 关于信息：

```
版本号: 2.5.0
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by EpLiar** [comment]
可以提供报错的截图么？另外 V2Ray assets 和内核路径应该是不一样的

**Comment by DuckSoft** [comment]
https://qv2ray.github.io/getting-started/step2.html#%E6%94%BE%E7%BD%AE%E4%BD%A0%E7%9A%84-v2ray-%E6%A0%B8%E5%BF%83

**Comment by shanzhaozhen** [comment]
> 可以提供报错的截图么？另外 V2Ray assets 和内核路径应该是不一样的

感谢，一开始看不明白核心文件跟资源文件有什么区别，以为资源文件是Qv2ray自动生成的文件，所以没有配置这个路径（默认：/usr/local/share/v2ray/）,我改为我安装v2ray核心的路径解决了（/bin/v2ray/）
