### ISSUE TITLE
Ubuntu 16.04 修改 CMakeLists.txt 指向自定义 Qt 库后无法编译问题一则

### ISSUE THREAD

**Issue by hongruixing** [Qv2ray/Qv2ray#733]
CMakeFiles/qv2ray_autogen.dir/build.make:99: *** target pattern contains no '%'.  Stop.
CMakeFiles/Makefile2:151: recipe for target 'CMakeFiles/qv2ray_autogen.dir/all' failed
make[1]: *** [CMakeFiles/qv2ray_autogen.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by DuckSoft** [comment]
请提供足以让我们复现此错误的详细命令及环境信息。

**Comment by hongruixing** [comment]
g++版本
g++ (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE

修改cmake文件
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_PREFIX_PATH "/opt/Qt5.14.2/5.14.2/gcc_64")
set(Qt5_DIR "${CMAKE_PREFIX_PATH}/lib/cmake/Qt5")
set(Qt5Widgets_DIR "${CMAKE_PREFIX_PATH}/lib/cmake/Qt5Widgets")
set(Qt5Network_DIR "${CMAKE_PREFIX_PATH}/lib/cmake/Qt5Network")
set(Qt5LinguistTools_DIR "${CMAKE_PREFIX_PATH}/lib/cmake/Qt5LinguistTools")
find_package(Qt5 5.11 COMPONENTS Core Gui Widgets Network REQUIRED)

**Comment by DuckSoft** [comment]
https://github.com/Qv2ray/Qv2ray/blob/master/.github/workflows/build-qv2ray-cmake.yml
你可以参考我们的构建流程。

cc @ymshenyu

**Comment by hongruixing** [comment]
目前Ubuntu 16.04 无法安装 5.9.5版本之后的qt

**Comment by DuckSoft** [comment]
目前我们线上的构建环境用的同样是 Ubuntu 16.04，不能构建请仔细检查一下为什么。
一个可能有用的提示：`CMAKE_PREFIX_PATH` 是个数组。

**Comment by ymshenyu** [comment]
首先，你需要在cmake后添加`-DQt5_DIR=/opt/Qt5.14.2/5.14.2/gcc_64/cmake`，举个例子：
```bash
$ cmake /path/to/qv2ray -DQt5_DIR=/opt/Qt5.14.2/5.14.2/gcc_64/cmake 其他参数...
```

**Comment by hongruixing** [comment]
出现
Increasing BUILDVERSION
CMake Error at CMakeLists.txt:36 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.11) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/study/Qv2ray/CMakeFiles/CMakeOutput.log".

**Comment by ymshenyu** [comment]
@hongruixing 抱歉，写错了。现在更改好了。

**Comment by hongruixing** [comment]
哪里敲错了吗
cmake .  -DQt5_DIR=/opt/Qt5.14.2/5.14.2/gcc_64/lib/cmake
Increasing BUILDVERSION
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:36 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.11) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!

**Comment by ymshenyu** [comment]
是这样，不好意思：
```bash
$ cmake /path/to/qv2ray -DQt5_DIR=/opt/Qt5.14.2/5.14.2/gcc_64/lib/cmake/Qt5 其他参数...
```

**Comment by hongruixing** [comment]
目前cmake正确
cmake .  -DQt5_DIR=/opt/Qt5.14.2/5.14.2/gcc_64/lib/cmake/Qt5
Increasing BUILDVERSION
 
Qv2ray Version: 2.5.0
Qv2ray Build Version: 5348
|-------------------------------------------------|
| Qv2ray, A Cross Platform v2ray Qt GUI Client.   |
| Licenced under GPLv3                            |
|                                                 |
| You may only use this program to the extent     |
| permitted by local law.                         |
|                                                 |
| See: https://www.gnu.org/licenses/gpl-3.0.html  |
|-------------------------------------------------|
| Project Homepage: https://github.com/Qv2ray     |
| Welcome to contribute!                          |
|-------------------------------------------------|
 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "2.6.1") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for modules 'grpc++;grpc'
--   Found grpc++, version 1.31.0-dev
--   Found grpc, version 11.0.0
Qv2ray build info: Qv2ray from manual build
Qv2ray build info ex: Qv2ray 2.5.0:5348
-- Configuring done
-- Generating done
-- Build files have been written to: /study/Qv2ray

but make不行
 make 
CMakeFiles/qv2ray_autogen.dir/build.make:99: *** target pattern contains no '%'.  Stop.
CMakeFiles/Makefile2:151: recipe for target 'CMakeFiles/qv2ray_autogen.dir/all' failed
make[1]: *** [CMakeFiles/qv2ray_autogen.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by DuckSoft** [comment]
try ninja instead of makefiles.
