### ISSUE TITLE
第一次安装新版本，后来别人又说安装2.5.0版本稳定，结果出这个错误提示

### ISSUE THREAD

**Issue by bijiye** [Qv2ray/Qv2ray#735]
- [ ] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

# 简单描述这个 Bug:---------------------------
Qv2ray 无法继续
---------------------------
与当前配置文件相比，您正在运行一个较低版本的 Qv2ray。
请检查是否存在'有关此问题的说明。
或者如果你认为这是一个错误，请提交一个新问题。

Qv2ray 现在将退出。
---------------------------
OK   
---------------------------

# 如何复现这个 Bug：

1. 
2. 
3. 
4. 

### 相关截图或日志

<details>

```
Qv2ray 日志：


```

</details>

### 受影响的 Qv2ray 安装平台

- Linux
- macOS
- Windows

### 受影响的 Qv2ray 安装源

- ArchLinuxCN - 稳定版
- ArchLinuxCN - 开发版
- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版
- Fedora - 稳定版
- Fedora - 开发版
- openSUSE - 稳定版
- openSUSE - 开发版
- Flathub 包
- Snap 包
- Homebrew Cask
- Scoop
- Chocolatey
- 手动编译
- Github Release

### 首选项 -> 关于信息：

```
版本号: 
内部版本号：
编译信息：
其它编译信息：
```

**其他信息**

你认为对我们修复bug有帮助的任何信息都可以在这里写出来：

**Comment by EpLiar** [comment]
对于 Qv2ray 来说，之前安装过高版本后会出现此提示。

如果你在 Windows，删除 `C:\Users\USERNAME\AppData\Local\qv2ray` 所有内容即可。

**Comment by DuckSoft** [comment]
这是因为 Qv2ray 支持配置文件的自动升级，但是不支持配置文件的自动降级导致的。
如果确定要使用 2.5.0，可以像楼上所说，删除配置文件即可。

不过：2.6.0 稳定版将于不日后放出，敬请期待。
