### ISSUE TITLE
在修改高级路由设置并保存时报错

### ISSUE THREAD

**Issue by nukemiko** [Qv2ray/Qv2ray#737]
在修改高级路由设置时会弹窗报以下错误：
main: failed to read config files: [/home/YaeSakura/.config/qv2ray/generated/config.gen.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  /home/YaeSakura/.config/qv2ray/generated/config.gen.json
v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: neither outboundTag nor balancerTag is specified in routing rule > exit status 255

在Windows和Linux上尝试均会出现这种错误，不知道路由规则实际上是否发挥了应有的作用

**Comment by EpLiar** [comment]
@nukemiko 麻烦提供一下截图

**Comment by DuckSoft** [comment]
是什么 Qv2ray 版本呢？不妨贴一下脱敏的 /home/YaeSakura/.config/qv2ray/generated/config.gen.json 文件上来看看？

**Comment by nukemiko** [comment]
> 是什么 Qv2ray 版本呢？不妨贴一下脱敏的 `/home/YaeSakura/.config/qv2ray/generated/config.gen.json` 文件上来看看？

`{
    "api": {
        "services": [
            "HandlerService",
            "LoggerService",
            "StatsService"
        ],
        "tag": "_QV2RAY_API_"
    },
    "dns": {
        "servers": [
            "8.8.4.4",
            "1.1.1.1"
        ]
    },
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 15490,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "sniffing": {
            },
            "tag": "_QV2RAY_API_INBOUND_"
        },
        {
            "listen": "127.0.0.1",
            "port": 10809,
            "protocol": "http",
            "sniffing": {
                "enabled": false
            },
            "tag": "http_IN"
        },
        {
            "listen": "127.0.0.1",
            "port": 10808,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "ip": "127.0.0.1",
                "udp": true,
                "userLevel": 0
            },
            "sniffing": {
                "enabled": false
            },
            "tag": "socks_IN"
        }
    ],
    "log": {
        "loglevel": "warning"
    },
    "outbounds": [
        {
            "mux": {
            },
            "protocol": "vmess",
            "sendThrough": "0.0.0.0",
            "settings": {
                "vnext": [
                    {
                        "address": "103.85.24.33",
                        "port": 443,
                        "users": [
                            {
                                "alterId": 2,
                                "id": "bfd3f2af-3471-3dc6-92a1-b4768605b91e",
                                "level": 0,
                                "security": "auto"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "dsSettings": {
                    "path": "/"
                },
                "httpSettings": {
                    "host": [
                    ],
                    "path": "/"
                },
                "kcpSettings": {
                    "congestion": false,
                    "downlinkCapacity": 20,
                    "header": {
                        "type": "none"
                    },
                    "mtu": 1350,
                    "readBufferSize": 1,
                    "tti": 20,
                    "uplinkCapacity": 5,
                    "writeBufferSize": 1
                },
                "network": "ws",
                "quicSettings": {
                    "header": {
                        "type": "none"
                    },
                    "key": "",
                    "security": ""
                },
                "security": "",
                "sockopt": {
                    "mark": 0,
                    "tcpFastOpen": false,
                    "tproxy": "off"
                },
                "tcpSettings": {
                    "header": {
                        "request": {
                            "headers": {
                            },
                            "method": "GET",
                            "path": [
                            ],
                            "version": "1.1"
                        },
                        "response": {
                            "headers": {
                            },
                            "reason": "OK",
                            "status": "200",
                            "version": "1.1"
                        },
                        "type": "none"
                    }
                },
                "tlsSettings": {
                    "allowInsecure": false,
                    "allowInsecureCiphers": false,
                    "alpn": [
                    ],
                    "certificates": [
                    ],
                    "disableSystemRoot": false,
                    "serverName": ""
                },
                "wsSettings": {
                    "headers": {
                        "Host": ""
                    },
                    "path": "/v2ray"
                }
            },
            "tag": "outBound_PROXY"
        },
        {
            "mux": {
            },
            "protocol": "freedom",
            "sendThrough": "0.0.0.0",
            "settings": {
                "domainStrategy": "AsIs",
                "redirect": ":0",
                "userLevel": 0
            },
            "streamSettings": {
            },
            "tag": "outBound_DIRECT"
        },
        {
            "mux": {
            },
            "protocol": "blackhole",
            "sendThrough": "0.0.0.0",
            "settings": {
                "response": {
                    "type": "none"
                }
            },
            "streamSettings": {
            },
            "tag": "outBound_BLACKHOLE"
        }
    ],
    "policy": {
        "system": {
            "statsInboundDownlink": true,
            "statsInboundUplink": true
        }
    },
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "inboundTag": [
                    "_QV2RAY_API_INBOUND_"
                ],
                "outboundTag": "_QV2RAY_API_",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "outBound_DIRECT",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "outBound_DIRECT",
                "type": "field"
            },
            {
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "outBound_DIRECT",
                "type": "field"
            }
        ]
    },
    "stats": {
    }
}
`

**Comment by DuckSoft** [comment]
你贴的 JSON 没啥问题。我这没法用你的 JSON 复现出你所描述的问题。

```shell
$ v2ray -test -config fuck.json
V2Ray 4.25.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)
A unified platform for anti-censorship.
2020/07/05 23:31:55 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  fuck.json
Configuration OK.
```

```shell
$ v2ray -config fuck.json
V2Ray 4.25.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)
A unified platform for anti-censorship.
2020/07/05 23:33:18 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  fuck.json
2020/07/05 23:33:18 [Warning] v2ray.com/core: V2Ray 4.25.1 started
