### ISSUE TITLE
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)

### ISSUE THREAD

**Issue by nukemiko** [Qv2ray/Qv2ray#740]
浏览外网（不一定被墙）时有一定几率连接中断，并且v2ray日志显示：
`v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)`
在Archlinux上出现，windows未经测试

相关日志：
`V2Ray 4.25.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)
A unified platform for anti-censorship.
2020/07/05 22:59:35 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /home/YaeSakura/.config/qv2ray/generated/config.gen.json
2020/07/05 22:59:35 [Warning] v2ray.com/core: V2Ray 4.25.1 started
2020/07/05 22:59:54 127.0.0.1:54976 accepted //www.bing.com:443 [outBound_PROXY]
2020/07/05 22:59:55 [Warning] [802500368] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/07/05 22:59:55 127.0.0.1:54980 accepted //wiki.archlinux.org:443 [outBound_PROXY]
2020/07/05 22:59:56 [Warning] [3992762223] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/07/05 22:59:56 127.0.0.1:54984 accepted //incoming.telemetry.mozilla.org:443 [outBound_PROXY]
2020/07/05 23:00:44 127.0.0.1:54988 accepted //github.com:443 [outBound_PROXY]
2020/07/05 23:00:47 127.0.0.1:54992 accepted //avatars0.githubusercontent.com:443 [outBound_PROXY]
2020/07/05 23:02:16 127.0.0.1:55000 accepted //github.com:443 [outBound_PROXY]
2020/07/05 23:02:16 [Warning] [1342420076] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/07/05 23:02:32 127.0.0.1:55004 accepted //www.bing.com:443 [outBound_PROXY]
2020/07/05 23:02:32 127.0.0.1:55008 accepted //www.bing.com:443 [outBound_PROXY]
2020/07/05 23:02:33 [Warning] [4135592029] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/07/05 23:02:33 [Warning] [2316578549] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/07/05 23:02:34 127.0.0.1:55012 accepted //pan.baidu.com:443 [outBound_DIRECT]
2020/07/05 23:02:34 127.0.0.1:55016 accepted http://ocsp2.globalsign.com/gsorganizationvalsha2g2 [outBound_PROXY]
2020/07/05 23:02:34 [Warning] [2114731755] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/07/05 23:02:34 [Warning] [2114731755] v2ray.com/core/proxy/http: failed to read response from ocsp2.globalsign.com > io: read/write on closed pipe
2020/07/05 23:02:35 127.0.0.1:55020 accepted //pan.baidu.com:443 [outBound_DIRECT]
2020/07/05 23:02:35 127.0.0.1:55022 accepted //staticsns.cdn.bcebos.com:443 [outBound_PROXY]
2020/07/05 23:02:35 127.0.0.1:55028 accepted //pan.baidu.com:443 [outBound_DIRECT] 
2020/07/05 23:02:35 127.0.0.1:55030 accepted //pan.baidu.com:443 [outBound_DIRECT]
2020/07/05 23:02:35 127.0.0.1:55032 accepted //pan.baidu.com:443 [outBound_DIRECT]
2020/07/05 23:02:35 127.0.0.1:55034 accepted //pan.baidu.com:443 [outBound_DIRECT]
2020/07/05 23:02:35 [Warning] [3493020270] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/07/05 23:02:36 127.0.0.1:55044 accepted //passport.baidu.com:443 [outBound_DIRECT]
2020/07/05 23:02:36 127.0.0.1:55048 accepted //passport.bdimg.com:443 [outBound_DIRECT]
2020/07/05 23:02:36 127.0.0.1:55052 accepted //wappass.baidu.com:443 [outBound_DIRECT]
2020/07/05 23:02:36 127.0.0.1:55056 accepted //passport.baidu.com:443 [outBound_DIRECT]
2020/07/05 23:02:36 127.0.0.1:55058 accepted //passport.baidu.com:443 [outBound_DIRECT]
2020/07/05 23:02:36 127.0.0.1:55062 accepted //passport.baidu.com:443 [outBound_DIRECT] 
2020/07/05 23:02:36 127.0.0.1:55060 accepted //passport.baidu.com:443 [outBound_DIRECT]
2020/07/05 23:02:45 127.0.0.1:55074 accepted //incoming.telemetry.mozilla.org:443 [outBound_PROXY]
2020/07/05 23:02:46 127.0.0.1:55078 accepted //profile.accounts.firefox.com:443 [outBound_PROXY]
2020/07/05 23:02:46 [Warning] [3308312718] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/07/05 23:02:47 [Warning] [2643300725] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)`
![Screenshot_20200705_224502](https://user-images.githubusercontent.com/53572814/86535605-191fff80-bf14-11ea-8b64-e932c4860dae.png)
![Screenshot_20200705_224516](https://user-images.githubusercontent.com/53572814/86535607-1b825980-bf14-11ea-8a63-742e19e6b37b.png)
![Screenshot_20200705_230002](https://user-images.githubusercontent.com/53572814/86535610-1e7d4a00-bf14-11ea-9e37-dbb0f26278ee.png)
![Screenshot_20200705_230031](https://user-images.githubusercontent.com/53572814/86535615-22a96780-bf14-11ea-9c64-c8ef933341ba.png)

**Comment by DuckSoft** [comment]
系统时间。
