### ISSUE TITLE
Feature: 复杂路由编辑器中的代理链式转发

### ISSUE THREAD

**Issue by liuquan321** [Qv2ray/Qv2ray#742]
目的：
     在Qv2ray统一管理[代理转发](https://toutyrater.github.io/advanced/outboundproxy.html)中的多个客户端
背景：
     如果中转服务器是ssr协议由于v2raycore无原生ssr支持，需要在本地同时启动v2ray与ssr客户端，目前Qv2ray虽然有了ssr插件，但是同时只能启动一个客户端导致需要额外命令行再启动一个wv2ray管理非常不便，是否可以让Qv2ray同时启动多个客户端呢？

**Comment by DuckSoft** [comment]
是说“把SSR节点当作前置代理”使用吗？

**Comment by DuckSoft** [comment]
如果你对 V2Ray 有深入的了解，就知道 V2Ray 有几种出站叫做 SOCKS5/HTTP 出站。
如果你对 Qv2ray 有一定了解，就知道 Qv2ray 的[插件集成功能](https://qv2ray.github.io/plugins/v2ray-integration.html#v2ray-%E9%9B%86%E6%88%90%E5%A6%82%E4%BD%95%E8%BF%90%E4%BD%9C%EF%BC%9F)正是应用了上面的原理。

我认为，启动多个实例是伪需求。实际的需求是你想实现链式转发/前置代理。

**Comment by DuckSoft** [comment]
仔细阅读了文档，我们在复杂路由编辑器中支持一下 `proxySettings` 应该就可以了。
目前我们的复杂路由功能也是可以启动 SSR/Trojan/NaiveProxy 节点当作出站的。敬请期待。

**Comment by liuquan321** [comment]
> 仔细阅读了文档，我们在复杂路由编辑器中支持一下 `proxySettings` 应该就可以了。
> 目前我们的复杂路由功能也是可以启动 SSR/Trojan/NaiveProxy 节点当作出站的。敬请期待。

确实是个伪需求，刚尝试了下从json直接导入带有proxySettings选项的vmess outbound（称为 outbound A），再把其他ssr连接配置的json文件直接导入为outbound B就可以在2.6.0-rc4中曲线实现该需求，美中不足的是一旦不小心修改了outbound A就会把proxySetting选项覆盖掉，期待后续版本的正式支持。

同时在这个操作中我发现另一个点，有没有可能支持从已经配置的其他连接配置中直接导入outbound呢？在ssr服务端频繁变动的场景中复制粘贴ssr的json 似乎不是一个长期可靠的方式。

**Comment by DuckSoft** [comment]
> 有没有可能支持从已经配置的其他连接配置中直接导入
这个功能 2.5.0 之前是有的，但是最近因为重构组编辑器，没有加回这个功能。
已经安排在 2.6.1 里了。

**Comment by liuquan321** [comment]
> > 有没有可能支持从已经配置的其他连接配置中直接导入
> 
> 这个功能 2.5.0 之前是有的，但是最近因为重构组编辑器，没有加回这个功能。
> 已经安排在 2.6.1 里了。

期待2.6.1的到来

**Comment by Qv2ray-dev** [comment]
1. `dev` 和 `version-v2` 分支现已经支持导入现有出站
2. `proxySettings` 涉及到 v2.7 重构，暂不支持 GUI 编辑，请见谅

**Comment by U-v-U** [comment]
v2.7.0-alpha2 已经完整支持链式代理，closing
