### ISSUE TITLE
Qv2ray v2.6.0-rc5 延迟测定若使用 ICMPing 会导致程序卡死/闪退

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#744]
根据 @zzndb 的 stack trace 报告，问题定位在 `Qv2ray::components::latency::LatencyTestThread::run()`。
对应的上次修改由 @Qv2ray-dev 做出。等待修复中。

**Comment by Qv2ray-dev** [comment]
fixed. Closing
