### ISSUE TITLE
建议：系统代理托盘图标颜色

### ISSUE THREAD

**Issue by liuquan321** [Qv2ray/Qv2ray#745]
现在工具栏菜单没有对启用项进行标识，有时候会很困惑。比如在”系统代理“这一项无法一下判断出当前是否启动了系统代理，
“最近连接”菜单虽然是按连接顺序倒序排列的，不过要能将当前启用服务器加一个标识就更直观了。

**Comment by cangyin** [comment]
关于
>”系统代理“这一项无法一下判断出当前是否启动了系统代理
的问题，参见 issue #551

**Comment by cangyin** [comment]
在[最新版本](https://github.com/Qv2ray/Qv2ray/releases/tag/v2.6.0-rc5)中，托盘图标已经能够指示当前系统代理的启用状态。

启用系统代理 _VS_ 禁用系统代理
![image](https://user-images.githubusercontent.com/50256182/86770477-56ef6600-c083-11ea-90e5-bb850a53484a.png) ![image](https://user-images.githubusercontent.com/50256182/86770511-61a9fb00-c083-11ea-91a1-067c951ee2dc.png)

**Comment by liuquan321** [comment]
> 在[最新版本](https://github.com/Qv2ray/Qv2ray/releases/tag/v2.6.0-rc5)中，托盘图标已经能够指示当前系统代理的启用状态。
> 
> 启用系统代理 _VS_ 禁用系统代理
> ![image](https://user-images.githubusercontent.com/50256182/86770477-56ef6600-c083-11ea-90e5-bb850a53484a.png) ![image](https://user-images.githubusercontent.com/50256182/86770511-61a9fb00-c083-11ea-91a1-067c951ee2dc.png)

这两个颜色区分度略小，是不是可以考虑更明显一些，比如红色 绿色？

**Comment by DuckSoft** [comment]
> > 在[最新版本](https://github.com/Qv2ray/Qv2ray/releases/tag/v2.6.0-rc5)中，托盘图标已经能够指示当前系统代理的启用状态。
> > 启用系统代理 _VS_ 禁用系统代理
> > ![image](https://user-images.githubusercontent.com/50256182/86770477-56ef6600-c083-11ea-90e5-bb850a53484a.png) ![image](https://user-images.githubusercontent.com/50256182/86770511-61a9fb00-c083-11ea-91a1-067c951ee2dc.png)
> 
> 这两个颜色区分度略小，是不是可以考虑更明显一些，比如开启红色，关闭无色？

你好，你认为哪两个颜色比较好，可以提供给我们 RGB 代码（或者对应的颜色截图）。
我们日后可能会提供给用户自定义颜色的功能。

**Comment by liuquan321** [comment]
> > > 在[最新版本](https://github.com/Qv2ray/Qv2ray/releases/tag/v2.6.0-rc5)中，托盘图标已经能够指示当前系统代理的启用状态。
> > > 启用系统代理 _VS_ 禁用系统代理
> > > ![image](https://user-images.githubusercontent.com/50256182/86770477-56ef6600-c083-11ea-90e5-bb850a53484a.png) ![image](https://user-images.githubusercontent.com/50256182/86770511-61a9fb00-c083-11ea-91a1-067c951ee2dc.png)
> > 
> > 
> > 这两个颜色区分度略小，是不是可以考虑更明显一些，比如开启红色，关闭无色？
> 
> 你好，你认为哪两个颜色比较好，可以提供给我们 RGB 代码（或者对应的颜色截图）。
> 我们日后可能会提供给用户自定义颜色的功能。

红色 #FF0000
无色透明 似乎没有rgb值是alpha设为0
--

**Comment by 9Ajiang** [comment]
+1，目前这个颜色还是略难区分，可以参考ssr这种整个图标变色是不是会好一点，例如没有连接的时候是白色的，连接但是不开启系统代理是蓝色的，开启系统代理是绿色的这样~

**Comment by Yudezhi** [comment]
附议

**Comment by cangyin** [comment]
![image](https://user-images.githubusercontent.com/50256182/87218875-63c4d000-c389-11ea-8458-0722eec1d332.png)
我觉得 让用户自己配色就好了

**Comment by liuquan321** [comment]
> +1，目前这个颜色还是略难区分，可以参考ssr这种整个图标变色是不是会好一点，例如没有连接的时候是白色的，连接但是不开启系统代理是蓝色的，开启系统代理是绿色的这样~

整个图标改变颜色确实要好些，4k 分辨率下区分右下角那个点的颜色挺吃力的。

**Comment by sephiroth945** [comment]
+1 确实比较难分辨，也可以考虑启动代理用右下角加点的图片，未启用代理用不加点的图标

**Comment by BrsyRockSs** [comment]
附议 
  确实对于大屏幕一个点的区别，而且是蓝色和绿色的区别确实挺难分辨，
  1 我想提一点，就是当我不知道或者看不出来是否开启代理的时候，我会选择右击系统托盘的图标，弹出来的菜单没有办法直观的告诉我，是否已经启动代理。我指的是暗色主题，fusion主题里面的连接和断开连接会有一个明显的反色显示，但是暗色主题中，仅仅有一个字体加粗的感觉，
  2 当鼠标移动到系统代理那个选项卡的时候，右边弹出来的 启动和禁用，左边没有一个对号或者提示符来显示当前的状态。我建议可以考虑加一下。
  3 还有一点我建议可以在系统托盘最上方加一条不可点击的信息显示当前连接的服务器名称，如果没有就写一个‘无代理’或者无可用服务器之类的，
 4 当前启动的服务器，只是在前面加了一个小点，并且左边信息栏的单条数据其实挺高的，当我想快速找到当前连到哪个服务器的时候其实没有那么直观，建议给当前连接的服务器加个独有的底色，因为当你连接完A服务器又点了一下其他的服务器，你其实只能靠那个小圆点来找当前连接的服务器了。
  我只是提出一些易用性的建议，希望对项目有一些帮助。谢谢

**Comment by U-v-U** [comment]
1. 2.7 正在计划使用 QCron 周期性检测系统代理状态，所以至今没有更新此 Issue
2. 首选项只是起到一个设置的作用，并不建议在那里弄一个 Indicator
3. 可以，不过和 Hover 的 Tooltip 些许重复 
4. 服务器列表右侧有个按钮：
![image](https://user-images.githubusercontent.com/59914293/89604524-09426500-d89e-11ea-8d20-713a1437d8c3.png)
