### ISSUE TITLE
Linux mint：注销，重新登陆，端口占用

### ISSUE THREAD

**Issue by concept-design** [Qv2ray/Qv2ray#748]
- **版本**
Linux mint 20
qv2ray: 2.6.0-rc4:5625
- **问题**
注销系统，重新登陆，出现端口占用为问题
![Screenshot from 2020-07-08 05-52-19](https://user-images.githubusercontent.com/52375886/86848024-dd399580-c0df-11ea-8d24-6600dc506893.png)
> 补充：ubuntu没有遇到这种问题

**Comment by diandianti** [comment]
> * **版本**
>   Linux mint 20
>   qv2ray: 2.6.0-rc4:5625
> * **问题**
>   注销系统，重新登陆，出现端口占用为问题
>   ![Screenshot from 2020-07-08 05-52-19](https://user-images.githubusercontent.com/52375886/86848024-dd399580-c0df-11ea-8d24-6600dc506893.png)
> 
> > 补充：ubuntu没有遇到这种问题

你这个问题应该是因为qv2ray在系统注销的时候没有完全退出的关系，我也遇到过，你可以试一下
`ps -aux| grep qv2tay`
查看一下在跑qv2ray进程，然后使用`kill -9 pid_of_qv2ray`关掉相应的进程就可以了

**Comment by concept-design** [comment]
是滴

**Comment by DuckSoft** [comment]
Merged into #830
