### ISSUE TITLE
分组的最后更新时间显示没有及时同步

### ISSUE THREAD

**Issue by cangyin** [Qv2ray/Qv2ray#750]
## 简单描述这个 Bug:

鼠标悬停提示中的更新时间与实际最近更新时间不同步

![image](https://user-images.githubusercontent.com/50256182/86997877-be232c80-c1e1-11ea-8de8-0bb1c84a567c.png)

![image](https://user-images.githubusercontent.com/50256182/86997976-f460ac00-c1e1-11ea-9f00-5ff20d44b59b.png)

在截图之前已经更新过订阅。

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.0-rc6:5746
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-dc5215093be30ad4cf9c443e586e4cea815cd286-ci.windows-latest
```

### 操作系统

- [ ] Linux
- [ ] macOS
- [x] Windows

### 安装来源

- [ ] ArchLinuxCN - 稳定版
- [ ] ArchLinuxCN - 开发版
- [ ] ArchLinux AUR - 稳定版
- [ ] ArchLinux AUR - 开发版
- [ ] Fedora - 稳定版
- [ ] Fedora - 开发版
- [ ] openSUSE - 稳定版
- [ ] openSUSE - 开发版
- [ ] Flathub 包
- [ ] Snap 包
- [ ] Homebrew Cask
- [x] Scoop / Chocolatey / Github Release
- [ ] 手动编译

### 已安装的插件、版本及安装来源
Trojan-GFW plugin
SSR plugin

**Comment by DuckSoft** [comment]
不是每次订阅都会出新节点，新节点必然新时间。
若订阅到同名节点，信息有变动才会更新更新时间。

> from @Qv2ray-dev

**Comment by cangyin** [comment]
对于节点而言，只有信息变动才更新更新时间，这是可以理解的；但是对于一个订阅分组而言，更新时间应该与 update subscription 的时间一致。
![image](https://user-images.githubusercontent.com/50256182/87112305-0bfd6a80-c29e-11ea-9518-7c26eaf736be.png)
然而截图中这个时间并没有同步。

如果说对于一个订阅分组，update subscription 之后，既无任何节点信息变动，也无节点增删，那么其鼠标悬停提示中的最后更新时间也不变。这勉强勉强也是可以接受的。

但是重启 Qv2ray 之后，上图中的鼠标悬停提示变成这样
![image](https://user-images.githubusercontent.com/50256182/87112624-e4f36880-c29e-11ea-8748-59ca81d58b32.png)
鼠标悬停中的最后更新时间与 update subscription 时间同步了！

这就没办法解释了。

**我觉得这必须是个 BUG**

~（解释不清楚，我太难了）~

**Comment by DuckSoft** [comment]
感谢反馈。已加入 2.6.1 豪华套餐。

**Comment by Qv2ray-dev** [comment]
fixed.
