### ISSUE TITLE
Ubuntu 20  v2ray 4.26.0   Config Error 

### ISSUE THREAD

**Issue by biology-geek** [Qv2ray/Qv2ray#752]
main:failed to read config files:[/home/xxx/.config/qv2ray/generated/config.gen.json]>v2ray.com/core/main/json:failed to execute v2ctl to convert config file.>v2ray.com/core/common/platform/ctlcmd:failed to execute v2ctl:
v2ctl>Read config:/home/xxx/.config/qv2ray/generated/config.gen.json
v2ray.com/core/infra/conf:failed to parse to outbound detour config.>
v2ray.com/core/infra/conf:unknown config id: > exit status 255

The v2ray core config failed

**Comment by DuckSoft** [comment]
Hello could you please kindly provide with your `/home/xxx/.config/qv2ray/generated/config.gen.json` to help us locate the problem?

**Comment by biology-geek** [comment]
{
    "api": {
        "services": [
            "HandlerService",
            "LoggerService",
            "StatsService"
        ],
        "tag": "_QV2RAY_API_"
    },
    "dns": {
        "servers": [
            "1.1.1.1",
            "8.8.8.8",
            "8.8.4.4"
        ]
    },
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 15490,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "sniffing": {
            },
            "tag": "_QV2RAY_API_INBOUND_"
        },
        {
            "listen": "127.0.0.1",
            "port": 8889,
            "protocol": "http",
            "settings": {
            },
            "sniffing": {
                "enabled": false
            },
            "tag": "http_IN"
        },
        {
            "listen": "127.0.0.1",
            "port": 1089,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "ip": "127.0.0.1",
                "udp": true,
                "userLevel": 0
            },
            "sniffing": {
                "enabled": false
            },
            "tag": "socks_IN"
        }
    ],
    "log": {
        "loglevel": "warning"
    },
    "outbounds": [
        {
            "protocol": null,
            "streamSettings": {
                "kcpSettings": {
                }
            },
            "tag": "jgvohopqrdafqhv"
        },
        {
            "protocol": "freedom",
            "sendThrough": "0.0.0.0",
            "settings": {
                "domainStrategy": "AsIs",
                "redirect": ":0",
                "userLevel": 0
            },
            "streamSettings": {
                "kcpSettings": {
                }
            },
            "tag": "outBound_DIRECT"
        },
        {
            "protocol": "blackhole",
            "sendThrough": "0.0.0.0",
            "settings": {
                "response": {
                    "type": "none"
                }
            },
            "streamSettings": {
                "kcpSettings": {
                }
            },
            "tag": "outBound_BLACKHOLE"
        }
    ],
    "policy": {
        "system": {
            "statsInboundDownlink": true,
            "statsInboundUplink": true,
            "statsOutboundDownlink": true,
            "statsOutboundUplink": true
        }
    },
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "inboundTag": [
                    "_QV2RAY_API_INBOUND_"
                ],
                "outboundTag": "_QV2RAY_API_",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "outBound_DIRECT",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "outBound_DIRECT",
                "type": "field"
            },
            {
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "outBound_DIRECT",
                "type": "field"
            }
        ]
    },
    "stats": {
    }
}

**Comment by EpLiar** [comment]
@biology-geek Looks like you didn't set it up correctly. When I remove this part on the configuration, core could boot up normally.

> {
> "protocol": null,
> "streamSettings": {
> "kcpSettings": {
> }
> },
> "tag": "jgvohopqrdafqhv"
> },

**Comment by biology-geek** [comment]
But I remove the code that you saying, nothing changed

**Comment by Qv2ray-dev** [comment]
@biology-geek try re-import your connection configurations, or update the subscription.
This may caused by a filesystem failure

**Comment by biology-geek** [comment]
Ubuntu 20
Qv2ray 2.5.0+v2ray 4.26+SSRPluginv1.0.5
Qv2ray 2.6.0+v2ray 4.26+SSRPluginv2.0.0
snap install Qv2ray2.5.0
download Qv2ray2.6.0 appimage
This error occurred in both environments 
Qv2ray 2.6.0+v2ray 4.26+SSRPluginv2.0.0 can‘t recognize the ssr connection
Is it the v2ray version too high??? Use the low version not find this error

**Comment by Qv2ray-dev** [comment]
try re-import your connection configurations, or update the subscription.
This may caused by a filesystem failure

**Comment by afotohi12** [comment]
i have same problem in ubuntu 22 and i cant solve.

**Comment by elven2016** [comment]
> i have same problem in ubuntu 22 and i cant solve.

hello, i encouter the  same issue ,how do you  fixed it in ubuntu22.04?

**Comment by zareisajad** [comment]
Same problem here:

main: failed to read config files: [/home/username/.config/qv2ray/generated/config.gen.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl:

**Comment by HHHHHONORG** [comment]
Hello.I also have the same question.How to solve
