### ISSUE TITLE
自动连接列表为空

### ISSUE THREAD

**Issue by Wings-Fantasy** [Qv2ray/Qv2ray#753]
## 简单描述这个 Bug:

 新版本更新后，首选项-自动连接列表里没有存在的线路

## 如何触发这个 Bug：

1. 从2.5.0更新到2.6.0
2. 首选项-自动连接选择下拉框列表变为空

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

尝试回滚到2.5.0，bug消失

### 相关截图或日志

<img src="https://s1.ax1x.com/2020/07/10/UuKDN4.png"/>
<img src="https://s1.ax1x.com/2020/07/10/UuK3NQ.png"/>

## 系统信息

OS: Debian 10
DE: GNOME

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.0:5756
编译信息：Qv2ray from manual build
额外编译信息：Qv2ray 2.6.0:5756
```

### 操作系统

- [x] Linux
- [ ] macOS
- [ ] Windows

### 安装来源

- [ ] ArchLinuxCN - 稳定版
- [ ] ArchLinuxCN - 开发版
- [ ] ArchLinux AUR - 稳定版
- [ ] ArchLinux AUR - 开发版
- [ ] Fedora - 稳定版
- [ ] Fedora - 开发版
- [ ] openSUSE - 稳定版
- [ ] openSUSE - 开发版
- [ ] Flathub 包
- [ ] Snap 包
- [ ] Homebrew Cask
- [x] Scoop / Chocolatey / Github Release
- [ ] 手动编译

**Comment by DuckSoft** [comment]
@Wings-Fantasy 已确认有此问题。目前的绕过方式是直接右击节点选设置为自动连接。将于2.6.1中修复。

**Comment by Wings-Fantasy** [comment]
> @Wings-Fantasy 已确认有此问题。目前的绕过方式是直接右击节点选设置为自动连接。将于2.6.1中修复。

右击设置一次之后，列表的选项被正确填充了，谢谢

**Comment by Qv2ray-dev** [comment]
fixed in dev. closing
