### ISSUE TITLE
macOS 10.15.5 下系统代理功能对某些程序不生效

### ISSUE THREAD

**Issue by Lewin671** [Qv2ray/Qv2ray#755]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

2.6.0:5756版本，开启系统代理无效。
OS： MacOS 10.15.5

## 如何触发这个 Bug：

1. 
2. 
3. 
4. 

### 相关截图或日志

<details>

```
请在此粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 
编译信息：
额外编译信息：
```

### 操作系统

- [ ] Linux
- [ ] macOS
- [ ] Windows

### 安装来源

- [ ] ArchLinuxCN - 稳定版
- [ ] ArchLinuxCN - 开发版
- [ ] ArchLinux AUR - 稳定版
- [ ] ArchLinux AUR - 开发版
- [ ] Fedora - 稳定版
- [ ] Fedora - 开发版
- [ ] openSUSE - 稳定版
- [ ] openSUSE - 开发版
- [ ] Flathub 包
- [ ] Snap 包
- [ ] Homebrew Cask
- [ ] Scoop / Chocolatey / Github Release
- [ ] 手动编译

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
所谓“无效”具体是指的是？

**Comment by Lewin671** [comment]
> 所谓“无效”具体是指的是？

开启qv2ray的系统代理，但是无法使用系统代理。
比如，在浏览器中无法直接使用代理，需要使用switchomega进行指定端口才能代理。

**Comment by DuckSoft** [comment]
> > 所谓“无效”具体是指的是？
> 
> 开启qv2ray的系统代理，但是无法使用系统代理。
> 比如，在浏览器中无法直接使用代理，需要使用switchomega进行指定端口才能代理。

我在 macOS 10.15.5 下测试，没有安装 switchyomega 的 Chrome 浏览器、Safari 浏览器和 Firefox 浏览器均能正常识别系统代理设置，并自动调整为直连/代理，无法复现此情形。不过如果你都有了 switchyomega，想必是代理功能被接管了，就安心用 switchyomega 就好了，不用管系统代理的事情了。

**Comment by Lewin671** [comment]
之前使用的qv2ray是一直可以使用系统代理的。在没有switchyomega开启系统代理的时候就可以使用qv2ray的系统代理。
但是，今天提示我更新到最新版本2.6.0:5756，更新后重新连接就无法使用系统代理了。

**Comment by DuckSoft** [comment]
macOS 有一个玄学。你不妨重启系统试试。

**Comment by Lewin671** [comment]
> macOS 有一个玄学。你不妨重启系统再试试。

重启大法有效！

**Comment by EpLiar** [comment]
对于此 issue 提出的问题，我做了如下测试：

环境：Qv2ray 2.6，升级后未重启，macOS Catalina 10.15.5

1.手动添加节点，确保不会因为 complex config 而导致不读首选项
2.打开本地 http 端口，禁用系统代理
3.打开 Chrome 的无痕窗口，访问 bilibili，Qv2ray 无日志
4.在 Qv2ray 的图标处打开系统代理，刷新网页，Qv2ray 有日志

所以如果愿意刨根问底，可以多试着能否找出复现步骤，或是在一段时间正常使用后，忽略此问题。
