### ISSUE TITLE
中文翻译typo

### ISSUE THREAD

**Issue by hzdrro** [Qv2ray/Qv2ray#756]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
https://github.com/Qv2ray/Qv2ray/blob/dev/translations/zh_CN.ts#L1880
"v2.46+"应为"v4.26+"？

**Comment by DuckSoft** [comment]
嗯，是的～手滑了～
如果你能发一个 PR，我会非常高兴帮你合并的～
