### ISSUE TITLE
请问，能否新增kcp呢？ May I ask for add kcptun in the application？

### ISSUE THREAD

**Issue by ChainZeaxion** [Qv2ray/Qv2ray#766]
请问能否增加kcp加速？
无加密tcp容易被识别，加tls容易被干扰和延迟
希望增加kcp来转换成UDP，以便提速和避免识别和干扰

May I ask for add kcptun in the application？
Unencrypted tcp is easy to identify, plus tls is easy to be interfered and delayed
Hope to increase kcp to convert to UDP in order to speed up and avoid identification and interference

**Comment by EpLiar** [comment]
为什么不直接使用 mKCP？

**Comment by DuckSoft** [comment]
请教一下，你想以什么形式，加在什么地方呢？
