### ISSUE TITLE
Are config files generated by Qv2ray v2.5.0 compatible with v2.6.0?

### ISSUE THREAD

**Issue by bokemanoh** [Qv2ray/Qv2ray#767]
Are config files generated by v2.5.0 compatible with v2.6.0?
Can I copy 'Qv2ray.v2.5.0.Windows-x64\config' to 'Qv2ray.v2.6.0.Windows-x64' in order to migrate all the settings? 

Or should I just reconfigure everything?

**Comment by DuckSoft** [comment]
Upgrading is usually **automatic**, if it's between **minor versions** (eg: 1.6 -> 1.99, 2.5 -> 2.6), not major versions (eg: 1.99 -> 2.5).
Overwriting binaries directly is supported. If you are worried, just have a backup of your config files.

**Comment by Qv2ray-dev** [comment]
We'll provide instructions in case the config files are not compatible. That occurs **rarely** but it **MAY** happen.

In case the version difference between your previous Qv2ray and the new Qv2ray is too large to migrate. Qv2ray will give you a warning complaining about the error. There'll be no damage.

**Comment by bokemanoh** [comment]
Thanks for reply! Things are okay now.

According #453, I copied the files under 'config' to 'X:/users/username/.qv2ray/'.
Bypass Mainland CN was re enabled, other settings seems been migrated with no issue.

Need to re assign the v2ray core exe/assets path to 'X:/users/username/.qv2ray/vcore' accordingly.
