### ISSUE TITLE
最新预览版2.6.0:5769在Fedora 32下连接时报错

### ISSUE THREAD

**Issue by ZXfkSIE** [Qv2ray/Qv2ray#768]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

Fedora 32下将Qv2ray-preview及其附属包更新到最新版（2.6.0:5769 + Core 4.26.0）后，连接时报错。
顺便一提，V2Ray-Core配置是测试通过的。（两个路径分别为`/usr/bin/v2ray`与`/usr/share/v2ray`）

## 如何触发这个 Bug：

1. 打开V2Ray
1. 连接某个节点
1. 报错。

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

无

### 相关截图或日志

<details>

```
main: failed to read config files: [/home/gbcat/.config/qv2ray/generated/config.gen.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  /home/gbcat/.config/qv2ray/generated/config.gen.json
v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > v2ray.com/core/infra/conf: failed to open file: geoip.dat > open /usr/bin/geoip.dat: no such file or directory > exit status 255
```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.0:5769
编译信息：Qv2ray dev branch built by openSUSE Build Service
额外编译信息：(Official Build) 4.12.14-lp151.28.52-default x86_64, Qt 5.13.2
```

### 操作系统

- [ ] Linux

### 安装来源

- [ ] Fedora - 开发版

### 已安装的插件、版本及安装来源

Trojan-GFW Plugin 2.0.0-pre3 （Github上下载后手动安装）

## 附加信息

报错信息里可以看出，v2ctl试图读取`/usr/bin/geoip.dat`文件，可实际上该文件的位置在`/usr/share/v2ray`，且首选项里也通过了配置测试。
事实上我通过两条软链接命令`ln -s /usr/share/v2ray/geoip.dat /usr/bin/geoip.dat`和`ln -s /usr/share/v2ray/geosite.dat /usr/bin/geosite.dat`就让软件使用恢复正常了。

**Comment by zzndb** [comment]
Confirmed on openSUSE and it seems not a packaging related error.

The stable version works fine.  @Qv2ray-dev

**Comment by Qv2ray-dev** [comment]
Bug confirmed here: https://github.com/Qv2ray/Qv2ray/compare/master...dev#diff-5c8055c11e5211390c0f23b938ad2444R218

**Comment by Qv2ray-dev** [comment]
It's caused by a rename from V2ray to V2Ray
![image](https://user-images.githubusercontent.com/59914293/87242074-0057a280-c45c-11ea-864b-509ea5604bcd.png)

**Comment by Qv2ray-dev** [comment]
fixed. Thanks for your contribution!

**Comment by zzndb** [comment]
@ZXfkSIE building triggered, you can update later from the repo if needed.
