### ISSUE TITLE
分流错误

### ISSUE THREAD

**Issue by nita0318** [Qv2ray/Qv2ray#776]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
分流错误，应该走代理的流量走直连了

## 如何触发这个 Bug：
1. 连接v2ray节点
2. 访问https://twitter.com/
3. 连不上

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
相同节点下v2rayN 3.19无此问题

### 相关截图或日志

V2Ray 4.26.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 windows/amd64)
A unified platform for anti-censorship.
2020/07/13 14:55:06 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  D:/Qv2ray.Windows-x64/deployment/config/generated/config.gen.json
2020/07/13 14:55:06 [Warning] v2ray.com/core: V2Ray 4.26.0 started
2020/07/13 14:55:11 127.0.0.1:9910 accepted //twitter.com:443 [outBound_DIRECT]
2020/07/13 14:55:15 127.0.0.1:9913 accepted //twitter.com:443 [outBound_DIRECT]
2020/07/13 14:55:23 127.0.0.1:9921 accepted //twitter.com:443 [outBound_DIRECT]
2020/07/13 14:55:27 127.0.0.1:9926 accepted //twitter.com:443 [outBound_DIRECT]
2020/07/13 14:55:34 127.0.0.1:9934 accepted //twitter.com:443 [outBound_DIRECT]

请在此粘贴 Qv2ray 日志：

[INIT]: Qv2ray 2.6.0 on Windows 10 Version 2004 x86_64
[CORE-UI]: Successfully installed a translator for zh_CN
[LICENCE]: 
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

Copyright (c) 2019-2020 Qv2ray Development Group.
Third-party libraries that have been used in Qv2ray can be found in the About page.

[INIT]: Application exec path: D:/Qv2ray.Windows-x64/deployment
[CORE-SETTINGS]: Found a config file, v= path=D:/Qv2ray.Windows-x64/deployment/config/
[INIT]: Using D:/Qv2ray.Windows-x64/deployment/config/ as the config path.
[COMMON-FILEIO]: Some comments have been removed from the json.
[CORE-UI]: Removed translations
[CORE-UI]: Successfully installed a translator for zh_CN
[COMMON-NETWORK]: Current OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
[CORE-UI]: Found factory style: windowsvista
[CORE-UI]: Found factory style: Windows
[CORE-UI]: Found factory style: Fusion
[CORE-UI]: Found QSS style at: ":/uistyles/flatwhite.css"
[CORE-UI]: Found QSS style at: ":/uistyles/psblack.css"
[COMPONENT-PLUGINHOST]: Reloading plugin list
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[COMMON-FILEIO]: Some comments have been removed from the json.
[CORE-UI]: Applying built-in darkmode theme.
[CORE-UI]: Loading data...
[COMMON-NETWORK]: Start checking update for channel ID: 0

[COMPONENT-UPDATE]: Received update info:
 --> Latest: 2.6.0
 --> Current: 2.6.0
 --> Ignored: 0.0.0
[COMPONENT-UPDATE]: No suitable updates found on channel 0

[CORE-CONNECTION]: Inserting default values to simple config
[QV2RAY-CORE]: Cannot disconnect when there's nothing connected.
[CORE-CONNECTION]: Outbound protocol vmess is not a registered plugin outbound.
[CORE-CONNECTION]: Outbound protocol freedom is not a registered plugin outbound.
[CORE-CONNECTION]: Outbound protocol blackhole is not a registered plugin outbound.
[CORE-CONNECTION]: Outbound protocol dns is not a registered plugin outbound.
[CORE-CONNECTION]: Applying new outbound settings.
[CORE-VCORE]: Starting kernels with V2rayIntegration.
[CORE-VCORE]: Core ABI: Windows PE 可执行文件
[CORE-VCORE]: Host ABI: Windows PE 可执行文件
[CORE-VCORE]: Host is compatible with core
[CORE-VCORE]: V2ray output: V2Ray 4.26.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 windows/amd64);A unified platform for anti-censorship.
[CORE-UI]: ProxyAddress: 127.0.0.1
[COMPONENT-PROXY]: Setting up System Proxy
[COMPONENT-PROXY]: Qv2ray will set system proxy to use HTTP
[COMPONENT-PROXY]: Qv2ray will set system proxy to use SOCKS
[COMPONENT-PROXY]: Windows proxy string: 127.0.0.1:8889
[COMPONENT-PROXY]: System default proxy info:
[COMPONENT-PROXY]: PROXY_TYPE_DIRECT
[COMPONENT-PROXY]: 127.0.0.1:8889
[COMPONENT-PROXY]: Setting system proxy for Global Proxy
[COMPONENT-PROXY]: System default proxy info:
[COMPONENT-PROXY]: PROXY_TYPE_DIRECT
[COMPONENT-PROXY]: PROXY_TYPE_PROXY
[COMPONENT-PROXY]: 127.0.0.1:8889
[CORE-UI]: OnConnected signal received for: rmmwdskvnkkw
[CORE-UI]: Setting current item.

[CORE-VCORE]: gRPC Version: 1.29.1

[COMPONENT-PROXY]: Clearing System Proxy
[COMPONENT-PROXY]: Cleaning system proxy settings.

### 打开首选项 -> 关于，填写以下信息

版本: 2.6.0:5756
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-e25fbfaecf7b1e4bb9fae7d57e898eb7970a1759-ci.windows-latest

### 操作系统

- [x] Windows

### 安装来源

- [x] Github Release

### 已安装的插件、版本及安装来源
无

## 附加信息
测试时v2rayN和Qv2ray均使用4.26.0版本的v2ray核心
Qv2ray首选项-连接设置-绕过中国大陆测试时未勾选
geoip.dat和geosite.dat来自项目(https://github.com/Loyalsoldier/v2ray-rules-dat)为7.13最新版
相同节点可以访问google.com.hk
系统版本19041.329
用的Qv2ray不是安装版本

**Comment by Qv2ray-dev** [comment]
检查一下你的首选项，高级路由设置里面有没有出现 twitter 字样呢 ？

**Comment by DuckSoft** [comment]
我怎么感觉这是个复杂配置呢……请问一下，你是怎么导入的这个节点呢？

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/87283419-db306600-c527-11ea-84d9-33c25d5fa8c6.png)
无法复现

**Comment by DuckSoft** [comment]
"增强规则"，配置如图：

![图片](https://user-images.githubusercontent.com/7822648/87283971-70cbf580-c528-11ea-8556-370074ce13ff.png)
![图片](https://user-images.githubusercontent.com/7822648/87283988-76294000-c528-11ea-9fcb-007271844402.png)

同样无法复现：
![图片](https://user-images.githubusercontent.com/7822648/87284114-98bb5900-c528-11ea-8c7f-d2ae9c63b1c1.png)

请检查你的高级路由设置中填写的内容。
