### ISSUE TITLE
深色模式UI失效

### ISSUE THREAD

**Issue by xgdgsc** [Qv2ray/Qv2ray#778]
## Briefly describe this bug：

2.6深色模式UI失效,2.5可以

## How to trigger this bug：

1. 启用 深色模式UI
 
 

### Related screenshots or logs

没有相关日志
 

## System Information

kubuntu 16.04

### Open Preferences -> About, and enter the following info

![image](https://user-images.githubusercontent.com/1189869/87368800-483c0e00-c5b1-11ea-9b53-cd3bba93270f.png)
关于界面不能复制？

### Operating systems

- [x] Linux
- [ ] macOS
- [ ] Windows
 
### Installation source
 
AppImage

### Installed plugins, versions and sources

default

**Comment by Qv2ray-dev** [comment]
你或许想试试主题里面的 Built-in UI Style

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/87386289-b644fd00-c5d2-11ea-9db8-fdd419987f26.png)
无法复现。推测是因为 Qt 工具链升级到 5.15，导致超低版本的 Kubuntu 16.04 的不兼容。
你可以使用内置暗色模式顶一下。不过，还是推荐升级到受社区支持的发行版版本，以获得更好的使用体验。
