### ISSUE TITLE
MacOS 11 Big Sur Beta 2 手动退出Qv2ray或直接关机后 未恢复系统代理设置

### ISSUE THREAD

**Issue by AIrSkycc** [Qv2ray/Qv2ray#781]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
MacOS 11 Big Sur Beta 2 手动退出Qv2ray或直接关机后 未恢复系统代理设置

导致退出QV2ray或重启后，所有应用无法连接网络

## 如何触发这个 Bug：

1. 正常退出Qv2ray
2. 正常关闭系统

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
未测试

### 相关截图或日志

<details>

```
请在此粘贴 Qv2ray 日志：
认为此问题与日志无关

```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.1:5779
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-6e03550de328ed1f65b28756329ce8484bf66f88-ci.macos-latest
```

### 操作系统

- [x] macOS

### 安装来源

- [x] Scoop / Chocolatey / Github Release

### 已安装的插件、版本及安装来源

无

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
咳，请 @Qv2ray-dev 处理～感谢～

**Comment by patui** [comment]
这个bug很严重，Windows版本也有这个问题。

**Comment by daveleenew** [comment]
同样遇到

**Comment by Tanche-Z** [comment]
win10 2004以及archlinux也是同样问题哦。不手动推出qv2ray的话，下次开机就是全局代理状态，导致无法正常联网，需要重开qv2ray再关闭。

**Comment by U-v-U** [comment]
Investigating.

**Comment by U-v-U** [comment]
Hello @AIrSkycc @Tanche-Z @daveleenew @patui 
Please try https://github.com/Qv2ray/Qv2ray/commit/869a3038c6482fd7dd6cc04239b2e2a85a73d8d3
