### ISSUE TITLE
archlinux更新2.6.1:5779版本，菜单不显示应用图标

### ISSUE THREAD

**Issue by Jeff5219** [Qv2ray/Qv2ray#782]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

archlinux更新2.6.1:5779版本，菜单不显示应用图标

## 如何触发这个 Bug：

1. 
2. 
3. 
4. 

### 相关截图或日志

<details>

```
请在此粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 
编译信息：
额外编译信息：
```

### 操作系统

- [ ] Linux
- [ ] macOS
- [ ] Windows

### 安装来源

- [ 1] ArchLinuxCN - 稳定版
- [ ] ArchLinuxCN - 开发版
- [ ] ArchLinux AUR - 稳定版
- [ ] ArchLinux AUR - 开发版
- [ ] Fedora - 稳定版
- [ ] Fedora - 开发版
- [ ] openSUSE - 稳定版
- [ ] openSUSE - 开发版
- [ ] Flathub 包
- [ ] Snap 包
- [ ] Homebrew Cask
- [ ] Scoop / Chocolatey / Github Release
- [ ] 手动编译

## 附加信息

*请注意打码隐私相关信息。*

**Comment by Qv2ray-dev** [comment]
@Jeff5219 已知问题，将在新版修复

**Comment by DuckSoft** [comment]
问题已定位，今晨修复。

**Comment by DuckSoft** [comment]
已在 dev 上修复。今天晚些时候请尝试一下 Arch Linux CN 自动打包的 qv2ray-dev-git，看看是否还有此现象。
感谢反馈。
