### ISSUE TITLE
为直连使用v2ray DNS和使用本地DNS的作用是什么？要不要勾选？

### ISSUE THREAD

**Issue by borninfreedom** [Qv2ray/Qv2ray#784]

**Comment by EpLiar** [comment]
所见即所得。

**为直连使用 V2Ray DNS**意思是不走代理的网站请求远程 DNS
**使用本地 DNS**的意思是需要代理的域名请求本地 DNS (如果你没有额外设置，通常遵循运营商默认)

**Comment by borninfreedom** [comment]
谢谢回复，怎样设置才是最优的方案，让响应更快？

**Comment by EpLiar** [comment]
@borninfreedom 两个都不要打勾最快

**Comment by borninfreedom** [comment]
OK, thank you
