### ISSUE TITLE
Feature: 希望能提供选项调整高级路由设置中不同路由条目的优先级

### ISSUE THREAD

**Issue by yyjdelete** [Qv2ray/Qv2ray#786]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
希望能提供选项修改高级路由设置的优先级
默认是阻断>代理>直连
但有些时候需要从代理的domain/ip中排除特定地址, 需要直连>代理, 希望能增加相应选项调整不同路由条目的优先级设置(不确定有没有其他人想要更进一步的优先级配置, 如`直连1>代理1>直连2>代理2>阻断1`之类的)
这个涉及到最终生成配置中routing.rules的排列顺序, v2会路由到第一个匹配的条目

### 相关截图或日志

<details>

```
请在此粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.1:5779
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-6e03550de328ed1f65b28756329ce8484bf66f88-ci.windows-latest
```

### 操作系统

- [ ] Linux
- [ ] macOS
- [x] Windows

### 安装来源

- [ ] ArchLinuxCN - 稳定版
- [ ] ArchLinuxCN - 开发版
- [ ] ArchLinux AUR - 稳定版
- [ ] ArchLinux AUR - 开发版
- [ ] Fedora - 稳定版
- [ ] Fedora - 开发版
- [ ] openSUSE - 稳定版
- [ ] openSUSE - 开发版
- [ ] Flathub 包
- [ ] Snap 包
- [ ] Homebrew Cask
- [x] Scoop / Chocolatey / Github Release
- [ ] 手动编译

## 附加信息

*请注意打码隐私相关信息。*

**Comment by cangyin** [comment]
新建 -> 手动输入 -> 打开路由/复杂配置编辑器
![image](https://user-images.githubusercontent.com/50256182/87558614-e3d19980-c6eb-11ea-9e27-67250a09218d.png)

这里可以自定义路由规则的优先级。

**Comment by cangyin** [comment]
新建 -> 手动输入 -> 打开路由/复杂配置编辑器

![image](https://user-images.githubusercontent.com/50256182/87559154-825dfa80-c6ec-11ea-8d2d-00d7d1866843.png)


这里可以自定义路由规则的优先级。

这里涉及的相关概念请自行查阅 v2ray 核心文档。

**Comment by SharerMax** [comment]
> 新建 -> 手动输入 -> 打开路由/复杂配置编辑器
> 
> 这里可以自定义路由规则的优先级。
> 
> 涉及的相关概念请自行查阅 v2ray 核心文档。

首选项中的默认路由规则不能使用配置编辑吧？

**Comment by EpLiar** [comment]
> 首选项中的默认路由规则不能使用配置编辑吧？

Qv2ray 默认帮你绕开大陆和直连私有 IP 地址 (即 192.168.x.x 等)，你可以取消打勾**绕过中国大陆**使默认路由规则只有直连私有 IP。

**Comment by SharerMax** [comment]
z

> > 首选项中的默认路由规则不能使用配置编辑吧？
> 
> Qv2ray 默认帮你绕开大陆和直连私有 IP 地址 (即 192.168.x.x 等)，你可以取消打勾**绕过中国大陆**使默认路由规则只有直连私有 IP。

这个我知道。但是，如果我要实现未匹配的规则走直连怎么实现（默认路由规则）？

**Comment by U-v-U** [comment]
@SharerMax 
- IP 填写 0.0.0.0/0 和 ::/0
- 域名填写 `regexp:.*`
即可成为使用直连兜底

**Comment by SharerMax** [comment]
> @SharerMax
> 
> * IP 填写 0.0.0.0/0 和 ::/0
> * 域名填写 `regexp:.*`
>   即可成为使用直连兜底

Nice! 这个实现了直连兜底的效果。

但是，默认路由规则的优先级设置如描述所说是为了有能力编写排除下一级所含规则中的特定规则，如：
1. Apple 和 部分Google 域名直连（不走代理）https://github.com/Loyalsoldier/v2ray-rules-dat#geositedat-1
2. 123.123.123.0/24 走代理，但 123.123.123.1 直连

基于以上的描述我认为还是**需要优先级的设置**
另外，虽然 @U-v-U 提供的方式可以实现兜底直连方式，但是换为设置`主出站协议`为直连的方式就更好了。基于此可否**增加一个设置项，设置直连是否为 `主出站协议`**

**Comment by DuckSoft** [comment]
复杂配置编辑器在路上了，复杂高级路由还会远吗。
敬请期待。
