### ISSUE TITLE
路由修改规则后无效

### ISSUE THREAD

**Issue by jiemo9527** [Qv2ray/Qv2ray#793]
在首选项-路由设置中添加直连域名，修改后无效，依然走proxy。重启无效
使用v2rayN不存在这个问题。

**Comment by EpLiar** [comment]
请提供截图或完整配置信息

**Comment by DuckSoft** [comment]
“添加直连域名”——怎么添加的？

**Comment by jiemo9527** [comment]
为什么设置局部规则大于全局规则 已解决closed

**Comment by DuckSoft** [comment]
先看文档是个好习惯。
https://qv2ray.github.io/manual/route.html#%E8%B7%AF%E7%94%B1%E6%96%B9%E6%A1%88
