### ISSUE TITLE
建议：日志区使用更加稳重护眼的色彩主题

### ISSUE THREAD

**Issue by Dothion** [Qv2ray/Qv2ray#794]
亮色主题下太亮
![](https://user-images.githubusercontent.com/31262977/87762982-8736c180-c846-11ea-810f-0ff22fbe9d69.png)

暗色模式要好很多，但有一些还是太暗
![](https://user-images.githubusercontent.com/31262977/87763807-f19c3180-c847-11ea-8366-ef7448e14eef.png)

速度图像区也有一定辨识难度

**Comment by Dothion** [comment]
建议分别设置暗色主题和亮色主题下的色彩主题，比如 vim-one

```
<span style="color:#0184BC">2020/07/17 16:12:55</span> <span style="color:#A626A4">tcp</span>:<span style="color:#C18401">127.0.0.1:60455</span> <span style="color:#50A14F">accepted</span> <span style="color:#A626A4">tcp</span>:<span style="color:#C18401">clients1.google.com:443</span> [outBound_PROXY]

<p style="background-color:#282C34;color:#CCCCCC"><span style="color:#56B6C2">2020/07/17 16:12:55</span> <span style="color:#C678DD">tcp</span>:<span style="color:#E5C07B">127.0.0.1:60455</span> <span style="color:#98C379">accepted</span> <span style="color:#C678DD">tcp</span>:<span style="color:#E5C07B">clients1.google.com:443</span> [outBound_PROXY]</p>
```

![](https://user-images.githubusercontent.com/31262977/87767181-d67ff080-c84c-11ea-8dd5-a81ec1100b08.jpg)

如果分别设置比较麻烦，那么用亮色主题的配色和暗色主题的背景也没什么问题

![](https://user-images.githubusercontent.com/31262977/87767446-43938600-c84d-11ea-8163-68faae7de993.png)

**Comment by DuckSoft** [comment]
设置第一项

**Comment by DuckSoft** [comment]
不过，这些专业的配色方案的确值得借鉴。未来我们可能会考虑加入更多的内置方案供用户自己更换。
感谢你的反馈。
