### ISSUE TITLE
请问这该如何解决？

### ISSUE THREAD

**Issue by noctis0216** [Qv2ray/Qv2ray#796]
![image](https://user-images.githubusercontent.com/39451004/87839197-5f8a3c80-c8cc-11ea-9f5c-6ecf2042e882.png)
![image](https://user-images.githubusercontent.com/39451004/87839206-6a44d180-c8cc-11ea-9368-b2bd347ece79.png)

**Comment by U-v-U** [comment]
https://qv2ray.github.io/getting-started/step2.html#%E9%85%8D%E7%BD%AE-v2ray-%E6%A0%B8%E5%BF%83

**Comment by noctis0216** [comment]
谢谢
