### ISSUE TITLE
java程序设置tcp代理的问题

### ISSUE THREAD

**Issue by Wings-Fantasy** [Qv2ray/Qv2ray#797]
## 简单描述这个 Bug:

不知道是bug还是我设置问题，java的tcp链接不能正常被代理

我使用`java -jar -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1080 client.jar`命令想要把使用TCP链接的java程序挂上qv2ray代理，但是qv2ray的日志上输出了`tcp:127.0.0.1:58250 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 67`。程序貌似没有正确的链接上代理，请问是哪里的问题？
注：socks代理端口被我改到了1080

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

没有尝试过

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.1:5779
编译信息：Qv2ray from manual build
额外编译信息：Qv2ray 2.6.1:5779
```

### 操作系统

- [x] Linux

### 安装来源

- [x] Scoop / Chocolatey / Github Release

**Comment by DuckSoft** [comment]
```
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> chr(67)
'C'
```

这是 SOCKS 入站收到了一个 HTTP 代理的 `CONNECT` 请求头的反应。
请你再检查一下代理是否配置正确，不要把 HTTP 代理指向 SOCKS 入站。

**Comment by DuckSoft** [comment]
顺便一提，这是啥 Java 程序……如果手动指定 SOCKS 代理不成功，不妨试试手动指定 HTTP 代理看看。
~~都不成功就把那个程序扬了。~~

**Comment by Wings-Fantasy** [comment]
我把代理设置到了http端口上，程序迟迟链接不上服务器，服务器那边没有收到客户端的链接。同时，qv2ray的日志上输出
` [Warning] [918605505] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: failed to read http request > malformed HTTP request "\x05\x02\x00\x02"`

**Comment by DuckSoft** [comment]
这又是 HTTP 代理端口收到了 SOCKS5 端口代理数据包的明显特征。
请问你的这个程序究竟是何方神圣，可否放出来让大家评赏一番。

**Comment by studentmain** [comment]
@Wings-Fantasy 这是向http端口发送了socks5握手
