### ISSUE TITLE
向分组中批量导入链接时出现乱序

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#800]
> Originally posted by @leoxxx from https://github.com/Qv2ray/QvPlugin-Trojan/issues/12

@DuckSoft: 已在 Qv2ray v1.99 / v2.0 / v2.1 / v2.5 / v2.6 复现。

**Comment by U-v-U** [comment]
Known issue, will be resolved in Qv2ray v2.7-pre1

**Comment by DuckSoft** [comment]
@leoxxx 感谢反馈，正在修复。

**Comment by U-v-U** [comment]
partially resolved this issue by sorting connections by the name.

Rewrite of Import algorithm is required, so let's wait.

**Comment by leoxxx** [comment]
空格识别问题解决了，逆序问题依然存在于2.6.3。
