### ISSUE TITLE
关于README.md中Fedroa仓库的徽章，这个应该不是COPR？？

### ISSUE THREAD

**Issue by tzwjkl** [Qv2ray/Qv2ray#803]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

[README.md](https://github.com/Qv2ray/Qv2ray/blob/master/README.md#availability--status) 中 Fedora 的徽章，徽章文字为 Fedora Copr ，但实际来自 OBS 。
说实话其实我对 Copr 这一概念并不是完全了解，Google 查询方知其为 Cool Other Package Repo 的缩写。既然是 Repo ，那它应该只能单指 [https://copr.fedorainfracloud.org/](https://copr.fedorainfracloud.org/)？况且我不能用 `dnf copr` 命令与该仓库交互。
所以有此疑问，它是 Copr 吗？
 #699 
@zzndb @kidonng 

## 如何触发这个 Bug：

无，否，略

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

无，否，略

### 相关截图或日志

无，否，略

```
请在此粘贴 Qv2ray 日志：

无，否，略

```

</details>

## 系统信息
```
$ uname -a
Linux DESKTOP-C65S96A.lan 5.7.8-200.fc32.x86_64 #1 SMP Thu Jul 9 14:34:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 32 (Thirty Two)
Release:	32
Codename:	ThirtyTwo
```

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.1:5779
编译信息：Qv2ray built by openSUSE Build Service
额外编译信息：(Official Build) 4.12.14-lp151.28.52-default x86_64, Qt 5.13.2
```

### 操作系统

- [x] Linux
- [ ] macOS
- [ ] Windows

### 安装来源

- [ ] ArchLinuxCN - 稳定版
- [ ] ArchLinuxCN - 开发版
- [ ] ArchLinux AUR - 稳定版
- [ ] ArchLinux AUR - 开发版
- [x] Fedora - 稳定版
- [ ] Fedora - 开发版
- [ ] openSUSE - 稳定版
- [ ] openSUSE - 开发版
- [ ] Flathub 包
- [ ] Snap 包
- [ ] Homebrew Cask
- [ ] Scoop / Chocolatey / Github Release
- [ ] 手动编译

### 已安装的插件、版本及安装来源

无，否，略

## 附加信息

<details>
编译信息也没有Copr嘛

![2020-07-20 00-40-13 的屏幕截图](https://user-images.githubusercontent.com/17105863/87880123-accbf280-ca21-11ea-8a63-d33474034755.png)

*请注意打码隐私相关信息。*

**Comment by zzndb** [comment]
确实不是 Copr ，和 openSUSE 的一样都是 OBS ，从同一个 spec 文件构建。
