### ISSUE TITLE
Dark UI not working properly on Plasma

### ISSUE THREAD

**Issue by RigoLigoRLC** [Qv2ray/Qv2ray#804]
- [x] **I'm sure I've tried to reproduce the problem several times and will provide the system environment, each software and its version that is involved in the problem.**

## Briefly describe this bug：
After upgrading the application, dark mode UI will not work properly. If theme was switched when the application is running, it would adapt to the changes; however when you launch the application with dark theme already set, the application will launch with light theme every time.

**Dark tray theme is not affected.**

## How to trigger this bug：

1. Launch Plasma desktop with theme "Breeze Dark" set.
2. Launch Qv2ray. The UI did not adapt to the dark theme.
3. Launch KDE settings and change theme to "Breeze" (light), apply, and change it back to "Breeze Dark" again.
4. Qv2ray has a dark theme now (incomplete, for example, the link textbox on the main window)

### Related screenshots or logs

<details>

![image](https://user-images.githubusercontent.com/49363666/87884024-f3c7e100-ca3d-11ea-92c6-d23b2bc791df.png)
```
Please paste your Qv2ray log here:


```

</details>

## System Information
```
$ inxi -Fx
System:    Host: rigo-magicbook Kernel: 5.7.9-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.1.0 
           Desktop: KDE Plasma 5.19.3 tk: Qt 5.15.0 wm: kwin_x11 dm: LightDM 1.30.0, SDDM Distro: Manjaro Linux
...

$ pacman -Q plasma-desktop qt5-base qv2ray 
plasma-desktop 5.19.3-1
qt5-base 5.15.0-4
qv2ray 2.6.1-1
```

### Open Preferences -> About, and enter the following info

```
Version: 2.6.1:5779
Build info: Qv2ray for Arch Linux CN
Extra build info: (Official Build) 5.6.12-arch1-1 x86_64
```

### Operating systems

- [x] Linux
- [ ] macOS
- [ ] Windows
 
### Installation source
 
- [x] ArchLinuxCN - Stable
- [ ] ArchLinuxCN - Dev-git
- [ ] ArchLinux AUR - Stable
- [ ] ArchLinux AUR - Development
- [ ] Fedora - Stable
- [ ] Fedora - Preview
- [ ] openSUSE - Stable
- [ ] openSUSE - Preview
- [ ] Flathub
- [ ] Snap
- [ ] Homebrew Cask
- [ ] Scoop / Chocolatey / Github Release
- [ ] Compile manually

### Installed plugins, versions and sources
No plugins

## Additional Info

*Please hide your server address and UUID if you wish to post the vmess string or your connection setting.*

**Comment by U-v-U** [comment]
Try setting theme in the preference window, just under the "Adapt dark theme" field.

**Comment by DuckSoft** [comment]
Seems to be a bug related to Breeze, where breeze simply changed their palette.
Specifying the theme explicitly in Qv2ray will help.

**Comment by DuckSoft** [comment]
Need more feedback. Closing.
Will reopen if there's further response.
