### ISSUE TITLE
Feature request: Forward to NaiveProxy 

### ISSUE THREAD

**Issue by BingLingGroup** [Qv2ray/Qv2ray#805]
可否让QvPlugin-NaiveProxy支持NaiveProxy前置代理v2ray-core，这样就可以在使用QvPlugin-NaiveProxy的时候自定义V2ray的配置了，而不是像现在这样只能用于Socks5分流，而且由于NaiveProxy的Socks5不支持udp，所以导致V2ray也不支持udp。而如果V2ray配置中使用了udp over tcp这类的传输协议（如vmess），就可以让NaiveProxy“间接”支持udp，虽然代价是服务器端需要多开一个V2ray实例

我觉得比较合适的修改大概是在首选项-连接设置-前置代理里面添加一个NaiveProxy的选项，这样就可以允许其他V2ray配置使用这个前置代理。如果是需要NaiveProxy的配置，可以从已导入的NaiveProxy配置中选择

虽说这并不是v2ray-core自带的前置代理功能，而且目前也可以通过再开一个NaiveProxy实例的方法来达到一样的效果，但还是觉得内置支持会更方便一些

~~另外似乎NaiveProxy前置的方案会比v2+ws+tls和v2+h2+tls的方案都快~~

**Comment by U-v-U** [comment]
Please see #742

**Comment by BingLingGroup** [comment]
行，基本算相似的功能请求，那我关了
