### ISSUE TITLE
manjaro kde系统

### ISSUE THREAD

**Issue by SkyHunterC** [Qv2ray/Qv2ray#806]
在最新的2.6.1版本，在启动系统后，Qv2ray不能自启，终端启动后没有UI界面，而且自己自动将系统的网络也代理了，关掉终端退出程序后，自己的网络都连不上

**Comment by U-v-U** [comment]
@SkyHunterC 你的 issue 模板呢

**Comment by DuckSoft** [comment]
尊重和理解是相互的。如果你不花一分钟看一眼 Issue 模板，我是一秒钟都不会浪费在你的 Issue 上的。

——Victoria Raymond

**Comment by SkyHunterC** [comment]
@DuckSoft  c,这给你牛气的，我又不知道，我还在看模板，你爱理不理

**Comment by cangyin** [comment]
@SkyHunterC 

作为 Qv2ray  的用户，我也想劝劝你。开发者们开发这款软件的初衷和目的都不是为了自己的利益，他们不亏欠于任何一个用户。
所以，如果需要反馈问题或者提交需求，都应该在尊重开发者的前提下进行。这个 issue 模板中需要你提供的各种细节可以帮助开发者定位，进而解决你的问题。要知道，短短的一段话是无法完整详细描述你的使用环境和引发错误的操作步骤的。如果没有这些信息，开发者就要一句一句一条一条地询问，他们不烦，你也该烦了。所以，何不一开始就把模板里面的信息填写好呢。况且 Qv2ray  的用户千千万，仅 [Qv2ray 用户群组](https://t.me/qv2ray) 就有 2千多人，开发者也不可能对每个用户的问题都一句句地交互。这个 issue 模板，是出于双方的便利而设置的。

如果你这是你第一次在 github 提 issue，或者只是单纯地没有注意到应该使用 issue 模板。没关系，只要重新发起一个 issue 就好（注意提供你的信息——也就是填好 issue 模板），开发者们不是小肚鸡肠。对事不对人，是吧。


> 尊重和理解是相互的。如果你不花一分钟看一眼 Issue 模板，我是一秒钟都不会浪费在你的 Issue 上的。
> 
> ——Victoria Raymond

这句话出自 v2ray 核心的第一开发者 Victoria Raymond，用来怼那些大爷一样的用户的。希望你不是。
