### ISSUE TITLE
qv2ray 会影响ubuntu20.04的软件源更新

### ISSUE THREAD

**Issue by elvisjade** [Qv2ray/Qv2ray#810]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
qv2ray 会影响ubuntu20.04的软件源更新

## 如何触发这个 Bug：

1. 使用qv2ray的appimage软件
2. 使用sudo gedit /etc/apt/sources.list

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
这个不太清楚

### 相关截图或日志

<details>

```会报错

获取:96 http://mirrors.tuna.tsinghua.edu.cn/ubuntu xenial-security/multiverse DEP-11 64x64@2 Icons [29 B]
Can not add an empty (zero-length) key to the cache                            
正在读取软件包列表... 完成
W: GPG 错误：https://qv2ray.github.io/debian stable InRelease: 由于没有公钥，无法验证下列签名： NO_PUBKEY 25F84048D7007085
E: 仓库 “https://qv2ray.github.io/debian stable InRelease” 没有数字签名。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。



请在此粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: ubuntu 20.04
编译信息：
额外编译信息：
```

### 操作系统

- [ `] Linux

### 安装来源

- [ ] ArchLinuxCN - 稳定版
- [ ] ArchLinuxCN - 开发版
- [ ] ArchLinux AUR - 稳定版
- [ ] ArchLinux AUR - 开发版
- [ ] Fedora - 稳定版
- [ ] Fedora - 开发版
- [ ] openSUSE - 稳定版
- [ ] openSUSE - 开发版
- [ ] Flathub 包
- [ ] Snap 包
- [ ] Homebrew Cask
- [ ] Scoop / Chocolatey / Github Release
- [` ] 手动编译

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
用前先读说明书。
https://qv2ray.github.io/debian/

**Comment by elvisjade** [comment]
> 用前先读说明书。
> https://qv2ray.github.io/debian/

emmm，可能因为我是新学linux，我就是从这里更新过，但是后来想不用这个，但是删不掉这个了，现在改sources.list不管怎么改都还是有qv2ray，可以问一下 https://qv2ray.github.io/debian/这个要怎么清除之类的么？

**Comment by DuckSoft** [comment]
`sudo gedit /etc/apt/sources.list` 删除对应行，保存，`sudo apt update`。

**Comment by elvisjade** [comment]
> `sudo gedit /etc/apt/sources.list` 删除对应行，保存，`sudo apt update`。

谢谢您的回复，主要是我现在是删的干干净净的，只有清华源

# deb cdrom:[Ubuntu 16.04 LTS _Xenial Xerus_ - Release amd64 (20160420.1)]/ xenial main restricted
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main restricted
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates main restricted
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial universe
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates universe
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial multiverse
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates multiverse
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security universe
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security multiverse

但是sudo apt update后还是会报错

获取:1 https://qv2ray.github.io/debian stable InRelease [1,782 B]
命中:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                               
错误:1 https://qv2ray.github.io/debian stable InRelease                                  
  由于没有公钥，无法验证下列签名： NO_PUBKEY 25F84048D7007085
命中:3 http://mirrors.tuna.tsinghua.edu.cn/ubuntu xenial InRelease      
命中:4 http://mirrors.tuna.tsinghua.edu.cn/ubuntu xenial-updates InRelease
命中:5 http://mirrors.tuna.tsinghua.edu.cn/ubuntu xenial-backports InRelease
命中:6 http://mirrors.tuna.tsinghua.edu.cn/ubuntu xenial-security InRelease
正在读取软件包列表... 完成
W: GPG 错误：https://qv2ray.github.io/debian stable InRelease: 由于没有公钥，无法验证下列签名： NO_PUBKEY 25F84048D7007085
E: 仓库 “https://qv2ray.github.io/debian stable InRelease” 没有数字签名。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。

**Comment by DuckSoft** [comment]
我用 Arch，不用 Ubuntu。呼叫外援 @ymshenyu

**Comment by DuckSoft** [comment]
来自群友的提醒：`sudo rm /etc/apt/sources.list.d/qv2ray.list`

**Comment by elvisjade** [comment]
> 我用 Arch，不用 Ubuntu。呼叫外援 @ymshenyu

真的真的很谢谢您，主要是我真的搜来搜去还是没解决，qv2ray真的很好用，可能我一开始不太懂，安装时候弄错了，现在主要是改不回去了，就很担心

**Comment by elvisjade** [comment]
> 来自群友的提醒：`sudo rm /etc/apt/sources.list.d/qv2ray.list`
> 
> > 欢迎加入 [Qv2ray User Group](https://t.me/qv2ray) @ Telegram.

好的，我现在试试，现在加入

**Comment by DuckSoft** [comment]
看到你的系统版本是 Ubuntu 16.04，不满足使用 Debian 源的最低版本要求，怪不得要删仓库来着。
这么低的系统版本也只有 AppImage 能用了。

当然，如果有机会，还是推荐升级到最新的受支持版本。感谢反馈。

**Comment by elvisjade** [comment]
> 看到你的系统版本是 Ubuntu 16.04，不满足使用 Debian 源的最低版本要求，怪不得要删仓库来着。
> 这么低的系统版本也只有 AppImage 能用了。
> 
> 当然，如果有机会，还是推荐升级到最新的受支持版本。感谢反馈。

emmm 不会呀，我是20.04呢，我用的20.04的镜像装的呀，而且系统设置，关于里面，我也是20.04（Ubuntu 20.04 LTS）

**Comment by DuckSoft** [comment]
在镜像列表里，`xenial` 是 16.04 的代号，而 20.04 是 `focal`。
请自己核实一下。

**Comment by elvisjade** [comment]
> 在镜像列表里，`xenial` 是 16.04 的代号，而 20.04 是 `focal`。
> 请自己核实一下。

好像是软件和更新里面都是16.04，但是系统关于里面都是20.04。我是从https://ubuntu.com/download/desktop这里，下载的20.04的镜像。
好奇怪哦

**Comment by DuckSoft** [comment]
你或许在配置镜像源的时候没有注意，选择了错误的版本。

**Comment by elvisjade** [comment]
> 你或许在配置镜像源的时候没有注意，选择了错误的版本。

好的呢，我看看

**Comment by MarksonHon** [comment]
看起来你换了清华大学的镜像源，但是，你把 Ubuntu 20.04 的软件源换成了 Ubuntu 16.04 的软件源。而 Ubuntu 16.04 是四年前的老版本，那个时候甚至都没有 Qv2ray。
这里推荐你以下几个网站去自动化生成软件源配置，以免误操作。
<https://repogen.simplylinux.ch/>
<https://mirrors.ustc.edu.cn/repogen/>
把你的软件源修正以后，再安装 Qv2ray 即可。

**Comment by elvisjade** [comment]
> 在镜像列表里，`xenial` 是 16.04 的代号，而 20.04 是 `focal`。
> 请自己核实一下。

应该是20.04的，我用lsb_release -a查了一些。

 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

软件源那边可能是我软件源又搞错了什么，不过这次已经没有受qv2ray的影响了。非常感谢您！！！

**Comment by Copay** [comment]
@elvisjade 非常感谢您！！！

**Comment by MarksonHon** [comment]
有事可以进 Telegram 群聊：
<https://t.me/qv2ray>

**Comment by DuckSoft** [comment]
客气。有其他使用上的问题，欢迎加我们的 Telegram 群（`@qv2ray`）。
