### ISSUE TITLE
macOS 开机启动之后 DOCK 栏图标显示

### ISSUE THREAD

**Issue by BleuRain** [Qv2ray/Qv2ray#811]
macOs 10.15.6
不知道是不是 bug，开机之后并未打开 Qv2ray 的任何窗口，但是 DOCK 栏会显示应用图标
打开窗口之后，再关闭 DOCK 栏图标就消失了

**Comment by DuckSoft** [comment]
我没有在使用 macOS，所以不知道这是否是预期行为。
@EpLiar 劳驾核实，多谢。

**Comment by EpLiar** [comment]
已收到，明早尝试复现。

**Comment by EpLiar** [comment]
10.16 beta 2，Qv2ray 2.6.1:5798 无法复现

你可以在首选项 -> 用户与群组 -> 登录项中移除 qv2ray 后再尝试一下

**Comment by DuckSoft** [comment]
可，暂时关闭。

**Comment by BleuRain** [comment]
macOS 10.15.6
Qv2ray 2.6.2:5800
删除登录项就无法开机自启动

**Comment by DuckSoft** [comment]
不知道你的预期是什么样子，是“开机自启动后托盘图标不应该显示”吗？还是其他的？

**Comment by EpLiar** [comment]
@BleuRain 是否开启了安静模式？

**Comment by BleuRain** [comment]
预期应该是开机之后，只有托盘图标显示，dock 栏没有图标 @DuckSoft 

设置了开机自动启动和安静模式 @EpLiar ep

**Comment by EpLiar** [comment]
@BleuRain 收到。明早我会在 10.15 尝试复现。

**Comment by BleuRain** [comment]
好的 @EpLiar

**Comment by EpLiar** [comment]
@BleuRain 我在 10.15.6 Qv2ray 2.6.2 (5800 & 5801) 尝试复现出您说的场景，均失败。要么是无图标，要么是窗口和图标同时存在，接下来我将持续关注此 issue。

同时欢迎加入 Qv2ray 的 Telegram 用户群： t.me/qv2ray 以获得实时的回复
