### ISSUE TITLE
关于用户级配置和数据文件内容/目录拆分

### ISSUE THREAD

**Issue by liolok** [Qv2ray/Qv2ray#812]
[XDG Base Directory](https://wiki.archlinux.org/index.php/XDG_Base_Directory) 也是老生常谈了。

Qv2ray 好像没什么用户级别的缓存，主要是配置跟数据吧。我个人是这样分类的：

- 配置：用户可以手动编辑修改，当然也可以通过程序生成（默认配置、GUI 选项）；
- 数据：用户不需要也不应该手动编辑、完全由程序生成，但仍可以手动备份再迁移。

这个“是否给用户编辑”终究也是交互设计的一环，我的建议是：

- Qv2ray 自身的配置“暴露”给用户，即通过 GUI 可以修改的配置，尽量都以文件的形式友好的呈现出来；
- Qv2ray 生成的 v2ray core 相关配置、最近连接的节点之类的文件则作为数据存放到 `$XDG_DATA_HOME`。

可以注意到 `~/.config/qv2ray/Qv2ray.conf` 这个 json 文件里面主要是用户配置，但是还有一部分内容是最近连接的 N 个节点 ID，这部分就应该拆分到数据目录下存放。这个 json 对象本身层数也比较多，换成 yaml 这种本身就能通过多个文件进行嵌套的语法会不会友好很多呢。

**Comment by U-v-U** [comment]
首先拆配置文件肯定是好
其次我觉得不能拆这么细致，（因为还有 Windows 和 macOS）

**Comment by liolok** [comment]
mac 不了解，Win 下面没有目录规范只能一坨吗，好残念啊。

**Comment by DuckSoft** [comment]
呃，Stale Issue，Closing
