### ISSUE TITLE
2.6.2 侧边栏默认大小略窄

### ISSUE THREAD

**Issue by EA-DICE** [Qv2ray/Qv2ray#813]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
软件左侧节点栏缩放不正常，过于窄小而节点名称无法完整地显示

## 如何触发这个 Bug：

1.运行软件即可
2. 
3. 
4. 

### 相关截图或日志
![image](https://user-images.githubusercontent.com/42771283/88020746-d474a500-cb5e-11ea-8b5e-8ab77f1f9563.png)

<details>

```
请在此粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本:2.6.2:5800
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-090db660ade774167e2089a9bd57d58d58dfd3c8-ci.windows-latest
```

### 操作系统

- [ ] Linux
- [ ] macOS
- [x] Windows

### 安装来源

- [ ] ArchLinuxCN - 稳定版
- [ ] ArchLinuxCN - 开发版
- [ ] ArchLinux AUR - 稳定版
- [ ] ArchLinux AUR - 开发版
- [ ] Fedora - 稳定版
- [ ] Fedora - 开发版
- [ ] openSUSE - 稳定版
- [ ] openSUSE - 开发版
- [ ] Flathub 包
- [ ] Snap 包
- [ ] Homebrew Cask
- [x] Scoop / Chocolatey / Github Release
- [ ] 手动编译

### 已安装的插件、版本及安装来源
trojan 2.0.0 GitHub

## 附加信息

首次运行软件UI一切正常，但是在退出重启软件后左侧节点栏UI大小不合适，并且在我手动调节UI大小后，退出重启软件UI还是会变回过窄的样子。在上个版本（2.6.1）中则不存在该bug，UI一切正常
*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
Windows 用户加一个启动参数 `--noScaleFactor` 启动即可。

**Comment by EA-DICE** [comment]
这个宽度是正常的，刚刚好，之前的版本也一直是这个宽度
![image](https://user-images.githubusercontent.com/42771283/88022776-7944b180-cb62-11ea-87ea-3a1b1f11b902.png)

**Comment by DuckSoft** [comment]
2.6.1 -> 2.6.2 UI 发生了一些变动。
@U-v-U 若有必要，可以回滚一下这些变动。

**Comment by Rasta0501** [comment]
我也发现了，左边显示节点的部分偏窄

**Comment by U-v-U** [comment]
![image](https://user-images.githubusercontent.com/59914293/88769858-8d665f80-d1af-11ea-90c5-d32cf8a71555.png)

Cannot reproduce on the latest `dev` branch, maybe already fixed?
This will be changed together with the v2.8 UI refactor.
