### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Zhiyi-Ren** [Qv2ray/Qv2ray#815]
能不能支援以下ssr协议
二维码扫描没有其他软件那么快，SS很方便的

**Comment by DuckSoft** [comment]
1. https://github.com/Qv2ray/QvPlugin-SSR
2. 欢迎帮我们实现一个像其他软件那么快的二维码扫描功能

**Comment by MarksonHon** [comment]
建议阅读官方文档
<qv2ray.github.io>
