### ISSUE TITLE
config.gen.json 出现部分空值

### ISSUE THREAD

**Issue by sagasm** [Qv2ray/Qv2ray#819]
版本2.6.2:

## 如何触发这个 Bug：

1. 生成一个复杂配置
2. 加入一个http和socks入站
3. 保存配置并生成config.gen.json
4. 发现allocat.refresh, settings.timeout, settings.userLevel未按设置值赋值.
5. quicSettings.security未设置默认值

### 相关截图或日志
![TIM截图20200722115919](https://user-images.githubusercontent.com/14829950/88132759-ed3e9280-cc12-11ea-943b-d649fb877cc3.png)
![TIM截图20200722115919](https://user-images.githubusercontent.com/14829950/88132822-09423400-cc13-11ea-8dfa-c9663114b896.png)

**Comment by DuckSoft** [comment]
这些空值有影响到正常使用吗？若无，可忽略。
若有，请提出受影响的使用场景，我们可针对进行修复。

cc @U-v-U

**Comment by sagasm** [comment]
是不符合V2Ray.config.schema.json的定义,也许会有潜在问题.

**Comment by U-v-U** [comment]
https://github.com/cwxyz007/v2ray-config-json-schema/blob/master/V2Ray.config.schema.json 这个？

**Comment by DuckSoft** [comment]
> 是不符合V2Ray.config.schema.json的定义,也许会有潜在问题.

也许有。好的。有了再说。

**Comment by sagasm** [comment]
我坦白,这两天我在玩mellow的负载平衡,把config.gen.json丢给mellow的时候每次都要改一改.

**Comment by DuckSoft** [comment]
> 我坦白,这两天我在玩mellow的负载平衡,把config.gen.json丢给mellow的时候每次都要改一改.

~~啊，好伤心，Qv2ray As A Configuration Generator~~

**Comment by U-v-U** [comment]
我记得 Mellow 是 V2Ray 魔改的，如果 V2Ray 都能支持读取，那么他的下游就应该可以

这个问题更应该汇报给 Mellow，而不是 Qv2ray
