### ISSUE TITLE
 普通用户突然运行不了?   

### ISSUE THREAD

**Issue by clnote** [Qv2ray/Qv2ray#820]
$./Qv2ray.v2.6.2.linux-x64.AppImage 
[INIT]: Qv2ray 2.6.2 on Debian GNU/Linux bullseye/sid x86_64
[CORE-UI]: Successfully installed a translator for zh_CN
$

**Comment by DuckSoft** [comment]
检查后台是否有一个实例已在运行。
Qv2ray 是以单例模式运行的，若再执行一次会唤醒之前的实例使其出现。

**Comment by clnote** [comment]
> 是以单例模式运行的，若再执行一次会唤醒之前的实例使

没有呢.

**Comment by clnote** [comment]
> > 是以单例模式运行的，若再执行一次会唤醒之前的实例使
> 
> 没有呢.

我试了下root可以, 一开始以为配置问题,但是我移动了qv2ray的配置,普通用户还是不行

**Comment by DuckSoft** [comment]
> > 是以单例模式运行的，若再执行一次会唤醒之前的实例使
> 
> 没有呢.

你是通过何种方式**断定**没有其他 Qv2ray 实例在运行的？

**Comment by clnote** [comment]
ps ax | grep Qv2ray

**Comment by DuckSoft** [comment]
你好，请试试 `ps ax | grep -i Qv2ray`

**Comment by clnote** [comment]
> 你好，请试试 `ps ax | grep -i Qv2ray`
没有, 但是核心是运行的,,可能我之前设置了启动就链接?

**Comment by DuckSoft** [comment]
我觉得你这个问题已经不属于 Qv2ray 本身的问题了，应该是你对 Linux 系统不熟悉造成的。
你可以考虑加入我们的 Telegram 群与我们继续讨论。GitHub Issue 上不再对这个问题跟进。

https://t.me/qv2ray
