### ISSUE TITLE
希望支持Windows登陆时启动不显示主界面

### ISSUE THREAD

**Issue by Sealt** [Qv2ray/Qv2ray#821]

**Comment by DuckSoft** [comment]
任意设置一个自动连接的节点就不会显示主界面了。
节点列表选个节点，右键，设置为自动连接。

**Comment by Sealt** [comment]
仍希望支持不自动连接时，不弹出主界面。谢谢

**Comment by U-v-U** [comment]
@Sealt 这是设计，既然 qv2ray 是一个后台程序，你不希望他在没有链接的时候仍然藏在后台

**Comment by DuckSoft** [comment]
我来试着实现一下吧，不过这个选项不会默认开启。
