### ISSUE TITLE
求助：能否使用adguardhome里的本地dns，设置改了很久，都没有效果。

### ISSUE THREAD

**Issue by Guantum** [Qv2ray/Qv2ray#822]
openwrt路由里用的AdGuard Home，在使用Q2ray时候，不知如何能走AdGuard Home的本地dns。
尝试了，在首选项“DNS设置”，添加本地DNS 如192.168.1.1:53。“连接设置”中，勾选或者不勾选 “使用本地DNS” “DNS拦截”，都没效果。

使用Q2ray后，AdGuard Home日志里看不到dns解析记录，网页广告也没过滤掉，所以肯定没走这个dns，关闭Q2ray后正常，想能不能和AdGuard Home一起用？

对dns设置参考了[784](https://github.com/Qv2ray/Qv2ray/issues/784)操作的。

**Comment by DuckSoft** [comment]
不知道 AdGuard Home 的原理是什么，如果是 DNS 过滤，那么在首选项——高级路由设置——域名——阻断中填写一行规则即可达到相同效果：`geosite:category-ads-all`

关于自定义 DNS：保证“使用本地 DNS”勾选，并且保证所添加的本地 DNS 处于首位，使其匹配。

最后，我们叫 Qv2ray，不叫 Q2ray。

**Comment by PaTTeeL** [comment]
建议这两个选项修改一下表达，虽然基本可以猜到意思，但我也是过来看issue确认功能的😂
“为直连使用V2Ray DNS” 改为 “直连使用V2Ray远程DNS”
“使用本地 DNS”改成“全局使用本地DNS”或者“禁用远程DNS”
另外感觉这两个选项应该是互斥的，就是全局远程DNS或者全局本地DNS，但现在可以同时勾选，那问问如果两个都选了，是不是走了代理的网站用了本地DNS，本地直连的网站倒反而用上了远程DNS？

**Comment by guanhemeng** [comment]
勾选使用本地DNS
在系统设置中将DNS改为192.168.1.1

**Comment by PaTTeeL** [comment]
> 勾选使用本地DNS
> 在系统设置中将DNS改为192.168.1.1
> （qv的连接设置为指定远程DNS，勾选本地DNS后其将不起作用，所以是在系统设置中修改）

懂了，我还以为是Qv2ray来主动查询本地DNS，那感觉这个选项叫”禁用V2Ray的DNS功能“会不会更容易看懂一些，另外”为直连使用V2Ray DNS“改叫”直连使用V2Ray的DNS设置“是不是会更好？
