### ISSUE TITLE
删除分组导致分组数据出错

### ISSUE THREAD

**Issue by sagasm** [Qv2ray/Qv2ray#823]
## 如何触发这个 Bug：

1.  打开组编辑器
2.  删除5个分组(包括默认分组)中的两个,ok按钮返回.
3. 发现默认分组多出来10多个无效连接

版本: 2.6.2

- [x] Windows
win10 x64

**Comment by U-v-U** [comment]
你的原来分组中有没有链接呢

**Comment by sagasm** [comment]
原来默认分组有两个复杂配置

**Comment by DuckSoft** [comment]
正常现象。为了防止误删分组，我们把“清空分组内所有节点”和“删除分组并将组内所有节点移动到默认分组”拆开了，确保用户不会因为误操作丢失数据。

正确删除一个有内容的分组的方法是：先在主界面右键点分组，选删除，这时会清除分组内所有节点；之后再在组编辑器中删除分组。
