### ISSUE TITLE
桌面环境销毁时 Qv2ray 不会随之关闭

### ISSUE THREAD

**Issue by rhjdvsgsgks** [Qv2ray/Qv2ray#830]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

de 注销/关机时,  qv2ray 不会随之关闭，会导致再次登录后提示端口被占用。 de 关闭后 qv2ray 仍会“尝试绘制窗口”，但绘制不了（因为 de 已经关闭了），于是会不停的报错， systemctl-journald 会一直记录报错导致一直有 8m/s 的数据写入磁盘，关机时也会因为 qv2ray 和 systemctl-journald 一直无法正常退出而卡住直到超时强制关闭。
在每次注销/关机前手动退出 qv2ray 可解决

## 如何触发这个 Bug：

1. 启动 qv2ray
2. 关机/注销

### 相关截图或日志

```
archlinux qv2ray[2101]: The Wayland connection broke. Did the Wayland compositor die?
```
```
Signal: 6
------- BEGIN QV2RAY CRASH REPORT -------
#0: [94078619321533]  in /usr/bin/qv2ray (deleted)
#1: [94078619328236]  in /usr/bin/qv2ray (deleted)
#2: [140136353264607]  in /usr/lib/libc-2.31.so
#3: [140136353264469] raise in /usr/lib/libc-2.31.so
#4: [140136353171538] abort in /usr/lib/libc-2.31.so
#5: [140136358877611] QMessageLogger::fatal(char const*, ...) const in /usr/lib/libQt5Core.so.5.15.0
#6: [140136295452921]  in /usr/lib/libQt5WaylandClient.so.5.15.0
#7: [140136295511184] QtWaylandClient::QWaylandDisplay::flushRequests() in /usr/lib/libQt5WaylandClient.so.5.15.0
#8: [140136295546120]  in /usr/lib/libQt5WaylandClient.so.5.15.0
#9: [140136365204698] QWindowPrivate::setVisible(bool) in /usr/lib/libQt5Gui.so.5.15.0
#10: [140136372660257] QWidgetPrivate::show_sys() in /usr/lib/libQt5Widgets.so.5.15.0
#11: [140136372696272] QWidgetPrivate::show_helper() in /usr/lib/libQt5Widgets.so.5.15.0
#12: [140136372709332] QWidgetPrivate::setVisible(bool) in /usr/lib/libQt5Widgets.so.5.15.0
#13: [140136374555911] QDialog::setVisible(bool) in /usr/lib/libQt5Widgets.so.5.15.0
#14: [140136374553270] QDialog::exec() in /usr/lib/libQt5Widgets.so.5.15.0
#15: [140136374772645] QMessageBox::warning(QWidget*, QString const&, QString const&, int, int, int) in /usr/lib/libQt5Widgets.so.5.15.0
#16: [94078619329600]  in /usr/bin/qv2ray (deleted)
#17: [140136353264607]  in /usr/lib/libc-2.31.so
#18: [140136353264469] raise in /usr/lib/libc-2.31.so
#19: [140136353171538] abort in /usr/lib/libc-2.31.so
#20: [140136358877611] QMessageLogger::fatal(char const*, ...) const in /usr/lib/libQt5Core.so.5.15.0
#21: [140136295452921]  in /usr/lib/libQt5WaylandClient.so.5.15.0
#22: [140136295511184] QtWaylandClient::QWaylandDisplay::flushRequests() in /usr/lib/libQt5WaylandClient.so.5.15.0
#23: [140136295546120]  in /usr/lib/libQt5WaylandClient.so.5.15.0
#24: [140136365204698] QWindowPrivate::setVisible(bool) in /usr/lib/libQt5Gui.so.5.15.0
#25: [140136372660257] QWidgetPrivate::show_sys() in /usr/lib/libQt5Widgets.so.5.15.0
#26: [140136372696272] QWidgetPrivate::show_helper() in /usr/lib/libQt5Widgets.so.5.15.0
#27: [140136372709332] QWidgetPrivate::setVisible(bool) in /usr/lib/libQt5Widgets.so.5.15.0
#28: [140136374555911] QDialog::setVisible(bool) in /usr/lib/libQt5Widgets.so.5.15.0
#29: [140136374553270] QDialog::exec() in /usr/lib/libQt5Widgets.so.5.15.0
#30: [140136374772645] QMessageBox::warning(QWidget*, QString const&, QString const&, int, int, int) in /usr/lib/libQt5Widgets.so.5.15.0
#31: [94078619329600]  in /usr/bin/qv2ray (deleted)
```
### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5888
编译信息：Qv2ray for Arch Linux CN
额外编译信息：(Official Build) 5.6.12-arch1-1 x86_64 
```

### 操作系统

- Linux

### 安装来源

- ArchLinuxCN - 开发版

### 已安装的插件、版本及安装来源

无插件

## 附加信息

de 为 kde ，使用了 wayland

希望能做成一个 systemd 的 user unit ，像 pulseaudio 一样

**Comment by U-v-U** [comment]
Are you using Weston?

**Comment by rhjdvsgsgks** [comment]
> Are you using Weston?

nope , im using kwin

**Comment by rhjdvsgsgks** [comment]
the log has been updated

**Comment by U-v-U** [comment]
Thanks

**Comment by willyywt** [comment]
根据KDE开发的博客，Plasma下Wayland混成器KWin和Plasma Shell是两个进程，而Gnome Shell则不是：

> Wayland is the natural choice for a compositor service to talk to apps. D-Bus is the most popular option for other desktop environment services to talk to apps. In some desktop environments, the compositor and other services may live in the same process (Gnome Shell in particular), others distribute services over few or many processes.
> 
> In Plasma, the compositor and the desktop shell are two seperate processes. The compositor implements the window management policy, and the desktop shell process draws your wallpaper, your panels and your menus. The notifications service lives in the Plasma desktop shell process as well. 

我用KDE的时候也发现这个现象，因为关机的时候能观察到Plasma桌面关闭了但是应用程序（比如Qv2ray）的窗口没有关闭。而GNOME则不出现这个现象，关机的时候GNOME桌面环境销毁了就看不到图形窗口了。虽然都是支持Wayland协议的桌面环境，但是Wayland协议依靠桌面环境的实现，而不同桌面环境的实现不一样，就可能有特定桌面环境下的bug。不同的桌面环境对freedesktop标准的实现也不一样，比如GNOME就没有系统通知栏。

总而言之，这可能就是Plasma的bug，可能和X11，Wayland，QtWayland什么的都没有什么关系。
[](
https://blogs.kde.org/2020/10/11/linux-desktop-shell-ipc-wayland-vs-d-bus-and-lack-agreement-when-use-them)

**Comment by rhjdvsgsgks** [comment]
确实应该是 kde 的问题，而且我发现如果在 kde 使用 wayland 的情况下关闭显示器，所有 wayland 应用都会不停的刷类似的 log

**Comment by DuckSoft** [comment]
上游问题……暂时动不了，先关掉了～
