### ISSUE TITLE
功能请求：节点测速功能

### ISSUE THREAD

**Issue by jiwangyihao** [Qv2ray/Qv2ray#831]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
很多时候，仅仅知道节点的链接延迟是不够的，有的节点可能延迟低但是比较卡，所以希望可以在Qv2ray中对节点的实际速度进行测速

**简单描述你预期的解决方案？**
可以像隔壁v2rayN一样接入speedtest CLI来完成测速功能

**你有想到其他比较容易实现的解决方案吗？**
其他的恩。。。想不到了诶

**补充内容**
好像没什么要补充的了

**Comment by Iongtimenosee** [comment]
可以增加测试真连接延时，和下载速度。

**Comment by jiwangyihao** [comment]
> 可以增加测试真连接延时，和下载速度。

嗯，我也觉得这样挺好的

**Comment by U-v-U** [comment]
Currently, we have decided to add realping as a latency test method for the connected node.
The speed test is not *currently* under consideration.

You may want some 3rd-party applications/softwares like https://github.com/tindy2013/stairspeedtest-reborn
