### ISSUE TITLE
功能请求：右键菜单的系统代理选项展示系统代理状态

### ISSUE THREAD

**Issue by CeresCa** [Qv2ray/Qv2ray#832]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
系统代理不能直观的从右键菜单看出来，每次要设置一下才放心
![image](https://user-images.githubusercontent.com/5327960/88515879-f5d20700-d01e-11ea-852f-369363833f1b.png)

**简单描述你预期的解决方案？**
在右键菜单系统代理那里增加图标或者文字，说明当前系统代理状态

**你有想到其他比较容易实现的解决方案吗？**
比如系统代理选项文字后加个括号，类似 “（已开启）” 这种

**补充内容**

**Comment by DuckSoft** [comment]
感谢反馈。

目前的难点在于我们无法得知系统代理的真实状态。例如，是否有其他程序动了我们的系统代理设置等。
正因为不知道，所以我们没有明确地把自己记录的状态放在右键菜单里。

我们有一个比较不明显的暗示：当开启系统代理的时候，Qv2ray 的托盘图标的小圆点会从绿色（活跃，无系统代理）变成蓝色（活跃，已设置系统代理）。

开发进度追踪： https://github.com/Qv2ray/Qv2ray/issues/551

**Comment by 111kb** [comment]
这个蓝绿真的很难分清  换成其他颜色会更好

**Comment by zhj9709** [comment]
> 这个蓝绿真的很难分清 换成其他颜色会更好

+1，确实难分清

**Comment by U-v-U** [comment]
Closing, merged into #551
