### ISSUE TITLE
Bug Report: 首选项设置了最近连接列表为10个，但是实际记录超过10个

### ISSUE THREAD

**Issue by cangyin** [Qv2ray/Qv2ray#833]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

首选项设置了最近连接列表为10个，但是这里显然超过了10个了。

![image](https://user-images.githubusercontent.com/50256182/88532340-068e7700-d037-11ea-94d8-279b39c50e65.png)

![image](https://user-images.githubusercontent.com/50256182/88532304-f70f2e00-d036-11ea-9b9a-67af0cc3659a.png)

## 如何触发这个 Bug：

1. 设置 最近列表 为 10 个
2. 多次，多次切换节点
3. 可得最近列表最多为 20 条记录

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.2:5812
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-5b6fe5a94f6a55862e338d265a17f203eab0d158-ci.windows-latest
```

### 操作系统

- Windows

### 安装来源

- Github Release / Scoop / Chocolatey

### 已安装的插件、版本及安装来源
SSR   v2.0.0
Trojan-GFW    v2.0.0
Command   v2.0.0

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/88533058-31c59600-d038-11ea-9d3b-12ade96b5fc8.png)
问题已定位。设置文件中的实际值是 20，但是窗口不知为何显示的还是 10。
https://github.com/Qv2ray/Qv2ray/search?q=maxJumpListCount&unscoped_q=maxJumpListCount

转交给 @U-v-U

**Comment by DuckSoft** [comment]
6eeb52f859eb5d3267cdff97943ec3121d0d1fe8 修了！
