### ISSUE TITLE
功能请求：建议使用热更新方式升级

### ISSUE THREAD

**Issue by JobsLeeCN** [Qv2ray/Qv2ray#835]
**更新方式太过麻烦，每次需要重新下载和覆盖**
建议使用热更新方式平滑升级。

**Comment by DuckSoft** [comment]
这个几乎一定是不会做的功能。因为需要这个功能的，本身就不会是我们的目标用户。
建议有类似需求的人了解一下包管理器。

**Comment by halk947** [comment]
scoop，apt或者brew都可以管理
