### ISSUE TITLE
使用疑问：<订阅-导入过滤器 过滤多个字符问题>

### ISSUE THREAD

**Issue by Silentely** [Qv2ray/Qv2ray#836]
在订阅设置里 有一个导入过滤器，当我想过滤多个字符时该用什么分割？（例如：包含台湾和俄罗斯字符的不导入）
我尝试使用英中文逗号分隔和回车分隔和空行分隔均无效。

**Comment by DuckSoft** [comment]
@Silentely 右侧仅导入不包含：关系切换到Or模式，一行一个屏蔽关键词

**Comment by DuckSoft** [comment]
举例说明：
![图片](https://user-images.githubusercontent.com/7822648/88661767-a4ec0c80-d10b-11ea-8dd6-a3957e47d39b.png)

**Comment by Silentely** [comment]
> @Silentely 右侧仅导入不包含：关系切换到Or模式，一行一个屏蔽关键词

明白了 谢谢解答 非常感谢
