### ISSUE TITLE
Qv2ray v2.6.2.5800 Forwarding Proxy Settings Won't Save

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#837]
- [x] **I'm sure I've tried to reproduce the problem several times and will provide the system environment, each software and its version that is involved in the problem.**

## Briefly describe this bug：
Forwarding Proxy Settings Won't Save

## How to trigger this bug：

1. Open "Preferences"
2. Change Forwarding Proxy Type from HTTP to SOCKS
3. Save
4. Reopen "Preferences"

### If it's a connection issue, has it happened in other V2Ray clients?
Nope.

### Related screenshots or logs

<details>

```
Please paste your Qv2ray log here:


```

</details>

### Open Preferences -> About, and enter the following info

```
Version: v2.6.2.5800
```

### Operating systems

- Linux
- macOS
- Windows

*Please hide your server address and UUID if you wish to post the vmess string or your connection setting.*

**Comment by U-v-U** [comment]
fixed, closing.
