### ISSUE TITLE
Qv2ray v2.6.2 在 macOS 未知版本 图标在程序坞跳动不显示

### ISSUE THREAD

**Issue by zilchzz** [Qv2ray/Qv2ray#839]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
第一次在macOS上使用打开可以正常使用；
第二次在macOS打开之后就一直无响应，图标在程序坞中一直跳动；

## 如何触发这个 Bug：

1. 未知，正常使用便触发了；

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
无

### 相关截图或日志
无
<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：

没有弹出日志；
```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: v2.6.2
```

### 操作系统

- macOS

### 安装来源
- Github Release / Scoop / Chocolatey

## 附加信息

我同时安装了V2rayU，并且我想让Qv2ray跟v2rayU的代理端口保持一致；
隐隐约约感觉跟使用同一个端口有关系，但在我将v2rayU的代理端口更改之后，还是一样无法打开；
我试过卸载重装，还是一样的问题。
*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
macOS 什么版本？

**Comment by zilchzz** [comment]
macOS版本：10.15.6 (19G73)

**Comment by DuckSoft** [comment]
呃，众所周知我们没有 macOS 设备。等一个志愿者来复现问题。

**Comment by EpLiar** [comment]
## 环境
* macOS 10.15.6 Catalina
* Qv2ray 2.6.2     安装方式 GitHub Release
* V2RayU 2.2.0    安装方式 GitHub Release

## 步骤与结论

在我使用 V2RayU 绑定同一个端口之后，退出 Qv2ray 再启动，并没有加载时的跳动，仅提示核心无法启动。(然后 Qv2ray 小 crash 了一下

所以这个暂时可以归为未知问题。

暂时 close。如有成功复现的具体步骤，我们会 reopen 该 issue。
