### ISSUE TITLE
功能请求：节点去重

### ISSUE THREAD

**Issue by iam7cn** [Qv2ray/Qv2ray#842]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
节点多了可能存在重复节点

**简单描述你预期的解决方案？**
增加节点去重功能

**你有想到其他比较容易实现的解决方案吗？**
没有

**补充内容**
白嫖订阅经常弄一万个重复节点，严重影响了白嫖体验

**Comment by Copay** [comment]
@iam7cn 能不能提供一个借口来自定义排序

**Comment by DuckSoft** [comment]
节点重新排序这个功能可以理解，没有什么歧义。
节点去重这个功能如果要做，先要定义一下，什么样的两个节点算是重复节点。

**Comment by Copay** [comment]
@DuckSoft 可以提供一个去重接口，通过用户指定的逻辑来确定重复

**Comment by DuckSoft** [comment]
> @DuckSoft 可以提供一个去重接口，通过用户指定的逻辑来确定重复

用户以什么方式指定逻辑呢？

**Comment by iam7cn** [comment]
> > @DuckSoft 可以提供一个去重接口，通过用户指定的逻辑来确定重复
> 
> 用户以什么方式指定逻辑呢？

地址和端口 一致就可以去重

**Comment by U-v-U** [comment]
@iam7cn 据我所知，有写机场使用 path 作为中转分流

**Comment by DuckSoft** [comment]
我先把这个 Issue 拆成两份吧。这个 Issue 用来讨论去重问题。
我另开一个用来追踪节点重新排序功能的进度。

**Comment by Copay** [comment]
> > @DuckSoft 可以提供一个去重接口，通过用户指定的逻辑来确定重复
> 
> 用户以什么方式指定逻辑呢？

可以内置一个脚本引擎，也可以复用系统自带的脚本引擎。
比如说Windows下可以复用powershell脚本而Linux下可以复用shell脚本

**Comment by DuckSoft** [comment]
> > > @DuckSoft 可以提供一个去重接口，通过用户指定的逻辑来确定重复
> > 
> > 
> > 用户以什么方式指定逻辑呢？
> 
> 可以内置一个脚本引擎，也可以复用系统自带的脚本引擎。
> 比如说Windows下可以复用powershell脚本而Linux下可以复用shell脚本

哦我的老天爷，这太复杂了……不如这个艰巨的任务就交给你来完成吧……

**Comment by DuckSoft** [comment]
咳，从开发者的角度来说，这个功能实现的难点在于定义重复节点到底是个啥。
如果要定义重复节点是个啥，就要对每一种节点实现一种稳定的、类型无关的比较器，而这在 C++ 中是比较难以实现的。

目前我们核心开发团队的重心仍在 2.7 的复杂路由编辑器上，暂时无暇顾及这边的事情。
这个功能大概率会搁置很长时间才做。希望理解。

**Comment by Copay** [comment]
@DuckSoft 可以把这个功能独立出来，作为仅处理配置的程序

**Comment by DuckSoft** [comment]
**Talk is cheap. Show me the code. **
--- Torvalds, Linus. Message to linux-kernel mailing list. 2000-08-25

> @DuckSoft 可以把这个功能独立出来，作为仅处理配置的程序

**Comment by Copay** [comment]
> **Talk is cheap. Show me the code. **
> --- Torvalds, Linus. Message to linux-kernel mailing list. 2000-08-25
> 
> > @DuckSoft 可以把这个功能独立出来，作为仅处理配置的程序

行 我给你整个nodejs脚本先

**Comment by DuckSoft** [comment]
以下是开发组经过商讨后的最终决定：

1. 懒。

2. 正常的使用场景下，没有哪个机场会给你出现重复节点的订阅。节点去重的最常见需求场景是四处找一些所谓的免费白嫖订阅，然后搅合在一起，结果却发现这些节点全是重样的，只是名字不一样。**我们认为，我们的目标用户群不会是这样的不注重自己的信息安全，只会搜集并使用白嫖节点的人。我们没有必要为自己永远不会用到的功能付出时间和精力。**

3. **再有人提类似的需求，直接关闭并链接到这个回复。**
