### ISSUE TITLE
SNI field being ignored

### ISSUE THREAD

**Issue by jitdor** [Qv2ray/Qv2ray#844]
- [x] **I'm sure I've tried to reproduce the problem several times and will provide the system environment, each software and its version that is involved in the problem.**

## Briefly describe this bug：

The "SNI name" (custom hostname) field from subscription links (the peer=domain.com parameter in trojan:// links) are not being retrieved by the Qv2ray client.

## How to trigger this bug：

1. Setup father node a.server.com with Trojan server listening on port 443
2. Setup transit node b.server.com which forward TCP traffic from port 10000 to a.server.com port 443, with "SNI" pointing to a.server.com
3. Instruct Qv2ray to read and refresh the subscription
4. The subscription contains the Trojan link in the following format `trojan://[UUID]@b.server.com:10000?allowInsecure=0&peer=a.server.com#Name_of_node`
5. The resultant Qv2ray node setting has an empty SNI

### Open Preferences -> About, and enter the following info

```
Version: 2.6.2:5800
Build info: Qv2ray built from Github Action
Extra build info: qt5.15.0-090db660ade774167e2089a9bd57d58d58dfd3c8-ci.windows-latest
```

### Operating systems

- [ ] Linux
- [ ] macOS
- [x] Windows
 
### Installation source
 
- [ ] ArchLinuxCN - Stable
- [ ] ArchLinuxCN - Dev-git
- [ ] ArchLinux AUR - Stable
- [ ] ArchLinux AUR - Development
- [ ] Fedora - Stable
- [ ] Fedora - Preview
- [ ] openSUSE - Stable
- [ ] openSUSE - Preview
- [ ] Flathub
- [ ] Snap
- [ ] Homebrew Cask
- [ ] Scoop / Chocolatey / Github Release
- [ ] Compile manually
- [x] Downloaded qv2ray-2.6.2-win64.exe from Github

### Installed plugins, versions and sources
SSR Plugin QvSSRPlugin.v2.0.2.Windows-x64.dll
Trojan-GFW Plugin QvTrojanPlugin.v2.0.0.Windows-x64.dll

**Comment by DuckSoft** [comment]
We don't know what's `peer`. We only know `sni`. That's it.

**Comment by DuckSoft** [comment]
@jitdor later we may add a compatibility layer for "peer", though it's a totally irrelevant name.
enough walls, huh.

**Comment by jitdor** [comment]
> @jitdor later we may add a compatibility layer for "peer", though it's a totally irrelevant name.
> enough walls, huh.

Thanks! At the same time I've submitted a request to the V2board author about the peer field.

![image](https://user-images.githubusercontent.com/8012216/88947943-dad3f100-d2c3-11ea-9331-6f079c28e85d.png)

**Comment by U-v-U** [comment]
No, **peer** is evil and not a standard.
We shouldn't make unstandardized widespread.

https://tools.ietf.org/html/rfc6066
https://tools.ietf.org/html/rfc6066#section-3

Only one "peer" ah?

**Comment by DuckSoft** [comment]
FYI: https://github.com/v2board/v2board/pull/295
