### ISSUE TITLE
Feature Request: ignore the notification of translation failed

### ISSUE THREAD

**Issue by KevinZonda** [Qv2ray/Qv2ray#845]
**Is your feature request related to a problem? Please describe.**
Nop.

**Describe the solution you'd like**
An option should be given to disenable the notification.

**Describe alternatives you've considered**
None.

**Additional context**
The notification will display everytime when open the qv2ray.

![image](https://user-images.githubusercontent.com/33132228/88950399-2c31af80-d2c7-11ea-85cf-9eea84a5203f.png)

**Comment by U-v-U** [comment]
@KevinZonda Cool idea, thanks

**Comment by U-v-U** [comment]
wip

**Comment by U-v-U** [comment]
fixed. closing

**Comment by KevinZonda** [comment]
❤️
