### ISSUE TITLE
在托盘点击“连接”一段时间后，主界面的图标和状态不一致

### ISSUE THREAD

**Issue by wajika** [Qv2ray/Qv2ray#847]
2.6.2版本

此时是开启状态，按钮的状态和程序状态不一致
![image](https://user-images.githubusercontent.com/17058349/89002219-1fe13d00-d32f-11ea-9e94-3754b5f00586.png)

**Comment by EpLiar** [comment]
你是否选到了并未连接的节点上？

**Comment by wajika** [comment]
好像是的，为什么每个节点一个按钮？

**Comment by EpLiar** [comment]
@wajika 因为点进去代表着该节点的当前状态
