### ISSUE TITLE
功能请求：关于真链接延时的实现问题

### ISSUE THREAD

**Issue by DuckVador** [Qv2ray/Qv2ray#850]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
真链接延时更能反映出节点实际的工作状态

**简单描述你预期的解决方案？**
对于一组节点测试:
1. 测试真链接时qv2ray连接到指定节点
2. 由latencytest后端的libuv与libcurl结合请求https://www.google.com
3. 测试延时后，继续测量下一个节点
对于单一结点测试:
上面方案1,2

**你有想到其他比较困难实现的解决方案吗？**
上面方案比较容易实现，但是无法并发执行。
另一种方案改动较大，
1. 由KernelInstanceHandler生成多(测试)端口入站、多个节点的出站的config
2. 由latencytest后端的libuv与libcurl结合并发请求https://www.google.com

**补充内容**
上面libcurl可以换成其他的库(或者QNetworkAccessManager?)，但是libcurl可以与libuv天然![结合](https://gist.github.com/clemensg/5248927)
大家更倾向于哪一种实现方案 @Qv2ray/management

**Comment by DuckSoft** [comment]
我倾向于不加入批量测试。

**Comment by DuckVador** [comment]
> 我倾向于不加入批量测试。

这样实现更简单一些，也避免了一些潜在的问题:
- qv2ray在测试时,由于RealPing是直接可以改变qv2ray的链接状态,如果用户想停止测试怎么办?

**Comment by DuckSoft** [comment]
只有在已连接的时候才能进行真延迟测试。
断开连接，停止测试。

**Comment by DuckVador** [comment]
OK,我觉得基本可行了

**Comment by U-v-U** [comment]
或许 google.com 应该作为一个可配置项目

**Comment by U-v-U** [comment]
我认为单连接 real latency 测试可行
批量就不用了

**Comment by DuckSoft** [comment]
实现啦！关掉啦！
