### ISSUE TITLE
在Arch-Linux中，出现库libZXingCore.so.1缺失，导致无法开启

### ISSUE THREAD

**Issue by Tanche-Z** [Qv2ray/Qv2ray#851]
## 简单描述这个 Bug:
终端输入：qv2ray
显示如下：  
qv2ray: error while loading shared libraries: libZXingCore.so.1: cannot open shared object file: No such file or directory

## 如何触发这个 Bug：
正常开启新版qv2ray 2.6.2-1

### 操作系统
- Linux
- ArchLinuxCN - 稳定版

**Comment by EpLiar** [comment]
https://t.me/qv2ray_outpost/249

> Arch Linux 中的 zxing-cpp 发生了 sobump
>
> Arch Linux 用户（以及衍生版用户）请注意：近期 zxing-cpp 发生了大版本变动。若你遇到 qv2ray 无法启动，并出现 zxingcore 字样报错的情况，不妨先降级回 zxing-cpp 1.0.8。

请查看我们在 Tg 的公告频道。

**Comment by U-v-U** [comment]
fixed in qv2ray-dev-git
