### ISSUE TITLE
Bugdows 中文路径/空格路径问题

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#853]
**我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
核心路径带中文，带空格，Windows 上出毛病

## 如何触发这个 Bug：

1. 核 心 路 径 带 中 文 带 空 格
2. 异 常 出 现

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
没用过

### 相关截图或日志
所有版本都有这问题

### 操作系统
- Windows

### 安装来源
所有来源均有此问题

### 已安装的插件、版本及安装来源
可能影响带内核的插件

## 附加信息
也许有用：
- https://blog.csdn.net/qq_15947787/article/details/77801569
- https://blog.csdn.net/qq_41077484/article/details/81661358

**Comment by U-v-U** [comment]
Cannot reproduce, closed.
