### ISSUE TITLE
功能请求：请求添加一个“一键把剪贴板中的链接的域名添加到直连域名中”的功能

### ISSUE THREAD

**Issue by kasusa** [Qv2ray/Qv2ray#854]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
我一般是使用全局代理。经常碰到有些国内网站由于走了v2ray代理而不能成功加载的问题。
我在首选项里面找到了这个“高级路由设置”功能，但是如果每次都要手动添加真的很麻烦。
希望可以在右键菜单增加**一键把剪贴板中的链接的域名添加到直连域名中**这样的功能

**简单描述你预期的解决方案？**
我做了一个示意图：![image.png](http://ww1.sinaimg.cn/large/006rgJELly1ghcdx0ctfxj30tu0m9132.jpg)
**你有想到其他比较容易实现的解决方案吗？**
1. 弄一小段代码来用正则把连接中的**域名部分**提取出来
2. 在后台直接把这个域名放到**直连域名**里面
3. 刷新一下

**补充内容**
1. 个人认为Qv2ray自带的路由规则不太好用（跟我之前用的clash win版相比更加经常的把我经常上的国内网站当做国外网站走）……
2. 完全看不懂路由-域名策略里面的三种模式的意义，虽然名字可以翻译，但是意义不明白，希望这里可以有一些参考说明书之类的。

**Comment by DuckSoft** [comment]
AsIs -> IPNonMatch，能解决99%问题。

**Comment by DuckSoft** [comment]
最后，回归到问题上来：

**Comment by DuckSoft** [comment]
> 个人认为Qv2ray自带的路由规则不太好用（跟我之前用的clash win版相比更加经常的把我经常上的国内网站当做国外网站走）……

空规则，IPOnDemand，请。

>完全看不懂路由-域名策略里面的三种模式的意义，虽然名字可以翻译，但是意义不明白，希望这里可以有一些参考说明书之类的。

读[文档](https://qv2ray.net/manual/route.html#%E8%B7%AF%E7%94%B1%E6%96%B9%E6%A1%88)，请。

**Comment by EpLiar** [comment]
分流并不是壳该做的功能，因为核心已经自带了。

如果你的规则是想国内直连其他代理，那么空规则+IPIfNonMatch 策略就可以了。这个策略会读 geolocation-cn，然后读不到的读 geoip，能解决 99% 的问题。最后，如果你发现有漏网之鱼 (中国域名走了代理)，欢迎来 v2fly/domain-list-community 反馈，我在那等你。

**Comment by kasusa** [comment]
ok 了解了 .是我没有仔细看文档
