### ISSUE TITLE
macOS 神奇版本上 SingleApplication 锁内存失败

### ISSUE THREAD

**Issue by Fuego-Zero** [Qv2ray/Qv2ray#856]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
无法启动软件，双击启动以后，直接闪退

## 如何触发这个 Bug：

1. 安装完成后，直接启动软件就触发

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：
SingleApplication: Unable to attach to shared memory block.
"QSharedMemoryPrivate::initKey: unable to set key on lock"

```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 
编译信息：
额外编译信息：
```

### 操作系统

- macOS

### 安装来源
- Github Release / Scoop / Chocolatey

### 已安装的插件、版本及安装来源
未安装插件

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
macOS 何种版本？Qv2ray 版本如何？

**Comment by kidonng** [comment]
@DuckSoft https://t.me/qv2ray/303336

**Comment by maiyuyu** [comment]
@Fuego-Zero   同样遇到安装后无法打开，重启后解决。
感觉可能是跟macOS的安全机制中对APP签名的限制有关。

**Comment by U-v-U** [comment]
@maiyuyu 非相关问题

**Comment by Dawson0x00** [comment]
我也是这个问题，无法启动app 命令行下查看到如下报错：
[INIT]: Qv2ray PreInitialization: OK
SingleApplication: Unable to attach to shared memory block.
"QSharedMemoryPrivate::initKey: unable to set key on lock"

**Comment by U-v-U** [comment]
如果不需要 SingleApplication, 可以使用 `-DQV2RAY_HAS_SINGLEAPPLICATION=OFF` 参数编译

**Comment by DuckSoft** [comment]
最新 2.7.0-alpha1 已修复
