### ISSUE TITLE
功能请求：建议增加pac与托盘代理情况

### ISSUE THREAD

**Issue by shellfeel** [Qv2ray/Qv2ray#857]
建议增加pac与托盘代理情况

**Comment by kidonng** [comment]
请按照模板提交请求。

PAC 问题见 https://qv2ray.net/plugins/v2ray-integration.html#为何不用-pac？

**Comment by MarksonHon** [comment]
1. PAC 功能已经被弃用，建议使用 v2ray 的内置路由功能。
2. “代理情况”是个啥新需求，你没有说明白。
3. 请按照模板填写 issue。
