### ISSUE TITLE
功能请求：使用等宽字体显示日志

### ISSUE THREAD

**Issue by Sam0523** [Qv2ray/Qv2ray#860]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
当前的日志显示为非等宽字体，相同字符数的内容并不能对齐，看起来很难看：
![image](https://user-images.githubusercontent.com/10058007/89419301-ced4ad00-d763-11ea-9d42-3e49c7c19288.png)

**简单描述你预期的解决方案？**
默认使用等宽字体显示日志。可以考虑允许用户自己设置字体和大小？

**你有想到其他比较容易实现的解决方案吗？**
只是修改为用系统默认的 monospace 等宽字体显示日志，应该不难？

**Comment by U-v-U** [comment]
resolved in dev and v2.6.3, closing.
