### ISSUE TITLE
功能请求: 增加正常模式与黑暗模式的切换

### ISSUE THREAD

**Issue by LittleControl** [Qv2ray/Qv2ray#861]
不知道是不是随着系统的颜色模式自动适配的,但是我在ArchLinux下似乎是没后夜间模式的,所以Qv2ray也无法去变色?  
强烈介意增加暗黑模式切换开关  
因为没有Qt编程的经验,所以对于这方面也不是很通透.要是需要用css来控制样式的,我可以提供帮助(开心)

**Comment by cangyin** [comment]
这个需求应该可以用黑色界面主题实现
![image](https://user-images.githubusercontent.com/50256182/89484337-df6f3c80-d7d0-11ea-8089-26892f067165.png)
**界面主题**选择黑色，并勾选**适应暗色主题**

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/89500105-b613d800-d7f3-11ea-90f8-3013cb406457.png)
供参考。

**Comment by LittleControl** [comment]
抱歉,一直没有关注更新,记得之前看到的主题是只有默认和windows风格的了.已经调整好了,感谢
