### ISSUE TITLE
系统环境变量代理是在哪里设置？

### ISSUE THREAD

**Issue by idalin** [Qv2ray/Qv2ray#863]
使用qv2ray之后，发现系统(archlinux+深度桌面)被设置相应的环境变量：
```
ftp_proxy=ftp://127.0.0.1:8889
http_proxy=http://127.0.0.1:8889
https_proxy=https://127.0.0.1:8889
no_proxy=localhost,127.0.0.0/8,::1
```
这本来没什么问题，但是当我退出qv2ray之后，发现这个环境变量还存在，重启系统之后仍然存在。进入qv2ray的首选项中，入站设置中把“设置系统代理”去掉之后，退出，重启系统仍然存在这个环境变量。
切换到另外一个用户，发现不存在这个环境变量。
所以怀疑是保存在$HOME目录下的，但是常规的~/.zshrc(我用的zsh)之类的地方都没找到这个设置。在$HOME目录下grep相应的关键字也没找到。
所以请问一下这个设置是在哪里？要怎么去掉？

**Comment by DuckSoft** [comment]
https://github.com/linuxdeepin/go-lib/issues/15
你可能是 Deepin “高级功能”的受害者。

**Comment by dreamlu** [comment]
这个bug最新的ubuntu 20.04也有,原来设置了下强制所有连接 功能, 然后关闭了,重启后又被改了, 似乎不是标题的环境变量，是系统的网络代理设置被改成由 自动变成了手动
![image](https://user-images.githubusercontent.com/21306894/126119817-171999f6-8efe-4399-8e31-d17ec9dd084b.png)

**Comment by dreamlu** [comment]
@DuckSoft
