### ISSUE TITLE
功能请求：检查更新开关

### ISSUE THREAD

**Issue by zerofancy** [Qv2ray/Qv2ray#870]
虽然我也认同及时更新的必要性，但Linux（Kubuntu）添加了debian软件源后软件内再检查更新弹窗就没有必要了。

希望增加一个检查更新的开关，或者让通过软件源安装的版本不检查更新（比如调高软件源安装的版本的版本号）

**Comment by DuckSoft** [comment]
> 软件源安装的版本不检查更新
Good Idea.

**Comment by DuckSoft** [comment]
#871. Awaiting triage from Debian maintainer.
