### ISSUE TITLE
使用疑问：ubuntu16.04 无法打开2.6.3版本

### ISSUE THREAD

**Issue by LuckySquirrel** [Qv2ray/Qv2ray#874]
![Screenshot from 2020-08-07 10-25-43](https://user-images.githubusercontent.com/30206054/89602128-a39faa00-d898-11ea-8b68-99d9613e7629.png)

### 你想做啥？

使用新发布的版本

### 你目前试了啥？
qv2ray2.6.0版本使用正常，但是2.6.2、2.6.3打开时报错
### 其他要补充的信息？
无

**Comment by LuckySquirrel** [comment]
找到问题了，是因为没有给程序权限
右键文件 –> 属性 –> 权限 –> 允许作为程序执行文件

**Comment by U-v-U** [comment]
OK.
