### ISSUE TITLE
高级路由设置的“代理域名”中应删除“geosite:steam”

### ISSUE THREAD

**Issue by alxt17** [Qv2ray/Qv2ray#876]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
在预置方案“v2aryN方案”中，“代理域名”中不应当出现“geosite:steam”。
(且直连规则中已经包含“domain:store.steampowered.com”)
(对于大多数用户而言，默认情况下steam无需代理，代理规则中的“geosite:steam”应当被删除。)

## 如何触发这个 Bug：
1. 首选项 ->高级路由设置 -> 预置方案 -> v2rayN方案。

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray from manual build
额外编译信息：Qv2ray 2.6.3:5840
```

### 操作系统

- Linux

### 安装来源

- Qv2ray Debian Repository

**Comment by DuckSoft** [comment]
啊，这个方案本来就是从 v2rayN 抄过来的……
既然如此，直接扬了吧。

感谢你的反馈。

**Comment by DuckSoft** [comment]
0330ed348a86b892f317dbcff403925bb51288b8
