### ISSUE TITLE
魔改JSON实现的链式代理分流功能似有异常

### ISSUE THREAD

**Issue by EsuRt** [Qv2ray/Qv2ray#878]
使用链式代理后，通过百度查询到的ip是代理服务器的（百度的连接也是经过“outBound_PROXY”），同样的配置在V2rayN上没问题，且在不更改Qv2ray其他配置的情况下，更改为非链式的代理，通过百度能查询到本地ip，分流正常。请问是不是配置有问题，以下是配置的截图：
![1](https://user-images.githubusercontent.com/15177069/89725832-a3dda800-da46-11ea-8ef8-1b810719ff92.jpg)
![2](https://user-images.githubusercontent.com/15177069/89725835-a6d89880-da46-11ea-89f8-9769e053c944.jpg)
![3](https://user-images.githubusercontent.com/15177069/89725836-a7712f00-da46-11ea-91f0-97dd677a808e.jpg)
![4](https://user-images.githubusercontent.com/15177069/89725837-a809c580-da46-11ea-9a20-132236cb2445.jpg)
![5](https://user-images.githubusercontent.com/15177069/89725840-a93af280-da46-11ea-902b-09370b909226.jpg)

**Comment by U-v-U** [comment]
复杂配置不会应用首选项的高级路由设置

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/89725935-c1f7d800-da47-11ea-95ca-ca3b0774fd5f.png)
![图片](https://user-images.githubusercontent.com/7822648/89725936-c6bc8c00-da47-11ea-926d-17b245c72ab8.png)

预告：2.7.0 在路上了

**Comment by U-v-U** [comment]
This will be released together with Qv2ray v2.7.0-alpha2, with all protocol/plugin supported.
