### ISSUE TITLE
使用疑问：广告屏蔽策略优先级过高

### ISSUE THREAD

**Issue by Double-Wen** [Qv2ray/Qv2ray#880]
### 你想做啥？
*简要描述你的最原始的目的。*
我是百度智能云用户，百度智能云的管理控制台https://console.bce.baidu.com/  会被误判为广告而遭到qv2ray的屏蔽和拦截

### 你目前试了啥？
在没有使用代理的情况下百度智能云是 肯定可以访问的，在高级路由中将百度智能云的管理控制台添加到了直连域名列表，可是这并不生效。在高级路由设置中将block geosite:category-ads-all规则删除则百度智能云可以正常访问。

### 其他要补充的信息？
我既想屏蔽广告，又想访问百度智能云，该怎么办？ FROM Qv2ray 2.6.3:5841

**Comment by U-v-U** [comment]
后续版本将会添加规则优先级设置

**Comment by EpLiar** [comment]
> 我是百度智能云用户，百度智能云的管理控制台https://console.bce.baidu.com/ 会被误判为广告而遭到qv2ray的屏蔽和拦截

See https://github.com/v2fly/domain-list-community/commit/a6464ef5c7cc791603233903f9f346b1cee273aa.

你可以更新 geosite.dat 以修复此问题，这是上游的误判。
