### ISSUE TITLE
功能请求：增加定期更新v2rayCore、geoip、geosite的功能

### ISSUE THREAD

**Issue by EsuRt** [Qv2ray/Qv2ray#881]
1、v2ray有时候会发布新版本修复bug，如果不经常关注，很容易遗漏更新版本。
2、geoip和geosite定期更新有助于更好地分流，主要是定期更新geosite能对之前未列入该文件的国内网站有明显的速度改善，一般这两个文件随v2ray一起发布，v2ray的更新不是非常频繁，导致原文件中的ip和网站可能有些陈旧，但github上有其他的维护项目，如https://github.com/Loyalsoldier/v2ray-rules-dat，更新较快，希望能增加自定义网址更新文件的功能。

**Comment by DuckSoft** [comment]
@EsuRt 有个东西叫包管理系统。

**Comment by FANminiworld** [comment]
@DuckSoft 本项目预订用户会使用包管理
