### ISSUE TITLE
关于透明代理的一些疑问或建议

### ISSUE THREAD

**Issue by rhjdvsgsgks** [Qv2ray/Qv2ray#882]
### 你想做啥？
使用透明代理

### 你目前试了啥？
使用非 root 用户启动 qv2ray 并尝试开启自带的透明代理功能

### 其他要补充的信息？
但因为不是 root 用户无法创建透明代理
```
failed to set IP_TRANSPARENT > operation not permitted
```
### 一些建议
建议 qv2ray 在遇到这种情况的时候改成只创建配置文件并实时显示日志（就像正常链接一样），实际启动 v2ray 由 systemd 完成，由 systemd 给予以用户帐号运行的 v2ray 绑定相关端口的权限

**Comment by U-v-U** [comment]
或者你可以使用 setcap 给 v2ray 添加 capabilities

**Comment by DuckSoft** [comment]
https://qv2ray.net/faq/#_4-linux-%E8%AE%BE%E7%BD%AE%E4%BA%86%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86-redirect-tproxy-%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%83%BD%E4%BD%BF%E7%94%A8-%E6%8F%90%E7%A4%BA-failed-to-set-ip-transparent-operation-not-permitted-%EF%BC%9F

**Comment by rhjdvsgsgks** [comment]
感谢，之前看文档的时候看漏了
