### ISSUE TITLE
VLESS代理出入站流量统计无效

### ISSUE THREAD

**Issue by zhuzeitou** [Qv2ray/Qv2ray#883]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
VLESS代理出入站流量统计无效

## 如何触发这个 Bug：

1. 使用VMess出站（VMess+HTTP/2+TLS及VMess+WebSocket+TLS），流量统计正常
2. 将出站改为VLESS（VLESS+HTTP/2+TLS及VLESS+WebSocket+TLS，偷懒照搬原有配置少量修改），网络连接正常，直连统计正常，代理流量统计不正常

### 相关截图或日志

<details>

油管统计

![image](https://user-images.githubusercontent.com/4777466/89801461-c95fd400-db62-11ea-947e-8dbfcac709e3.png)

使用VLESS出站的统计

![image](https://user-images.githubusercontent.com/4777466/89801494-d67cc300-db62-11ea-9a35-f4293d671b7b.png)

![image](https://user-images.githubusercontent.com/4777466/89801962-64f14480-db63-11ea-8e99-8c9f7a867aeb.png)

对比切换到使用VMess的统计

![image](https://user-images.githubusercontent.com/4777466/89801613-01ffad80-db63-11ea-869f-a0588dc4b8f2.png)

![image](https://user-images.githubusercontent.com/4777466/89802048-85b99a00-db63-11ea-9389-a7b31c3a8e08.png)

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.windows-latest
```

### 操作系统

- Windows

### 安装来源

- Github Release / Scoop / Chocolatey

### 已安装的插件、版本及安装来源

无

## 附加信息

*请注意打码隐私相关信息。*

**Comment by U-v-U** [comment]
@zhuzeitou 
fixed, please try 
https://github.com/Qv2ray/Qv2ray/actions/runs/202748276
or
https://github.com/Qv2ray/Qv2ray/actions/runs/202748262

**Comment by zhuzeitou** [comment]
It works! Thank you very much for your help.

**Comment by U-v-U** [comment]
Thanks!

**Comment by dna1982** [comment]
> @zhuzeitou
> fixed, please try
> https://github.com/Qv2ray/Qv2ray/actions/runs/202748276
> or
> https://github.com/Qv2ray/Qv2ray/actions/runs/202748262

Windows-x64版本，打开就报错了。

stacktrace：
[QvBugReport_1598583306.zip](https://github.com/Qv2ray/Qv2ray/files/5139772/QvBugReport_1598583306.zip)

**Comment by DuckSoft** [comment]
@U-v-U Consider remove that "enhanced" backtrace. 
It seems that warning logs can be regarded as irreversible error.

**Comment by U-v-U** [comment]
@DuckSoft It's been removed for years.
