### ISSUE TITLE
"Recent Jumplist" crashes when shown the second time

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#884]
- [x] **I'm sure I've tried to reproduce the problem several times and will provide the system environment, each software and its version that is involved in the problem.**

## Briefly describe this bug：
"Recent Jumplist" crashes when shown the second time.

## How to trigger this bug：

1. Launch Qv2ray.
2. Right click to show the menu.
3. Hover on "jumplist", then move away.
4. Repeat step 3.
5. Booooom!

### If it's a connection issue, has it happened in other V2Ray clients?
Nope.

### Related screenshots or logs

```
#4: [140398394602463]  in /usr/lib/libc-2.31.so
#5: [140398413939486]  in /usr/lib/libQt5Widgets.so.5.15.0
#6: [140398414008725] QWidget::removeAction(QAction*) in /usr/lib/libQt5Widgets.so.5.15.0
#7: [140398415349178] QMenu::clear() in /usr/lib/libQt5Widgets.so.5.15.0
#8: [94563234321541] MainWindow::OnRecentConnectionsMenuReadyToShow() in /home/ducksoft/OFFICE/GFW/Qv2ray/build/qv2ray --> ../src/ui/windows/w_MainWindow.cpp:[128:38]
```

</details>

### Open Preferences -> About, and enter the following info

```
Version: 2.6.3:5888
Build info: Qv2ray for Arch Linux CN
Extra build info: (Official Build)
```

### Operating systems

- [x] Linux
- [x] macOS
- [x] Windows
 
### Installation source
 
- [x] ArchLinuxCN - Stable
- [x] ArchLinuxCN - Dev-git
- [x] Homebrew Cask
- [x] Scoop / Chocolatey / Github Release
- [x] Compile manually

### Installed plugins, versions and sources
No relationship.

## Additional Info
https://github.com/Qv2ray/Qv2ray/blame/521786b69e665ed87fcdbc8761cc6ab926696350/src/ui/windows/w_MainWindow.hpp#L171

**Comment by DuckSoft** [comment]
https://github.com/Qv2ray/Qv2ray/blob/521786b69e665ed87fcdbc8761cc6ab926696350/src/ui/windows/w_MainWindow.cpp#L129

`tray_ClearRecentConnectionsAction` is only constructed once. once called by `addAction()`, the ownership will be moved.
the next time you try to move a destructed `tray_ClearRecentConnectionsAction`, it will surely crash.

**Comment by U-v-U** [comment]
it's not the root cause....

**Comment by U-v-U** [comment]
fixed, closed.
