### ISSUE TITLE
v2ray 核心设置不正确

### ISSUE THREAD

**Issue by hhhaiai** [Qv2ray/Qv2ray#886]
- [ ] **I'm sure I've tried to reproduce the problem several times and will provide the system environment, each software and its version that is involved in the problem.**

## Briefly describe this bug：
 macos 打开节点，核心错误
![image](https://user-images.githubusercontent.com/5738285/89853650-7c144e80-dbc4-11ea-8de6-9595739f6b85.png)

## How to trigger this bug：

1. 
2. 
3. 
4. 

### Related screenshots or logs

<details>

```
Please paste your Qv2ray log here:


```

</details>

### Open Preferences -> About, and enter the following info

```
Version: 
Build info: 
Extra build info: 
```

### Operating systems

- [ ] Linux
- [x] macOS
- [ ] Windows
 
### Installation source
 
- [x] ArchLinuxCN - Stable
- [ ] ArchLinuxCN - Dev-git
- [ ] ArchLinux AUR - Stable
- [ ] ArchLinux AUR - Development
- [ ] Fedora - Stable
- [ ] Fedora - Preview
- [ ] openSUSE - Stable
- [ ] openSUSE - Preview
- [ ] Flathub
- [ ] Snap
- [ ] Homebrew Cask
- [ ] Scoop / Chocolatey / Github Release
- [ ] Compile manually

## Additional Info

*Please hide your server address and UUID if you wish to post the vmess string or your connection setting.*

**Comment by hhhaiai** [comment]
![image](https://user-images.githubusercontent.com/5738285/89853705-a36b1b80-dbc4-11ea-8bef-109c616634a3.png)

**Comment by hhhaiai** [comment]
![image](https://user-images.githubusercontent.com/5738285/89853726-b7af1880-dbc4-11ea-89e6-c6a3d6e6b5fd.png)

version: 2.6.3:5840

**Comment by U-v-U** [comment]
https://qv2ray.net/getting-started/step2.html#%E4%B8%8B%E8%BD%BD-v2ray-%E6%A0%B8%E5%BF%83%E6%96%87%E4%BB%B6

**Comment by hhhaiai** [comment]
ok.  thx. 这个核心插件未下载导致的

![image](https://user-images.githubusercontent.com/5738285/90213026-605cb280-de27-11ea-82db-953f76b66302.png)
