### ISSUE TITLE
使用疑问：如何在复杂设置中设置DNS

### ISSUE THREAD

**Issue by dna1982** [Qv2ray/Qv2ray#887]
### 你想做啥？
*简要描述你的最原始的目的。*
我想在复杂设置的GUI面板上配置DNS。

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
看完文档，没有相关内容，就过来问一问。

### 其他要补充的信息？
全局设置中的DNS似乎是针对简单设置的，对复杂设置不起作用？

**Comment by U-v-U** [comment]
目前（2.6.3）中的生成策略是 “缺啥补啥”，因此你只需要在复杂配置 json 中删除 dns 项即可

敬请期待 v2.7-pre1, 该版本中添加了对于复杂配置 DNS 的设置

**Comment by dna1982** [comment]
> 目前（2.6.3）中的生成策略是 “缺啥补啥”，因此你只需要在复杂配置 json 中删除 dns 项即可
> 
> 敬请期待 v2.7-pre1, 该版本中添加了对于复杂配置 DNS 的设置

我看了眼复杂设置的JSON，里面没有DNS信息。这是不是说会补上全局设置的DNS？

**Comment by U-v-U** [comment]
@dna1982 是的（正常来说）

**Comment by dna1982** [comment]
> @dna1982 是的（正常来说）

明白了 谢。
