### ISSUE TITLE
关于最新版Qv2ray在macOS 10.13.6上连接节点卡死的问题

### ISSUE THREAD

**Issue by VersionZKP2356** [Qv2ray/Qv2ray#888]
你好！我在macOS 10.13.6上使用Qv2ray时，点击连接节点，Qv2ray会卡死，但是已经能够通过节点上网了，希望尽快修复，谢谢！

**Comment by U-v-U** [comment]
请使用 Legacy 包
https://dev.azure.com/realducksoft/Qv2ray/_build/results?buildId=760&view=artifacts&type=publishedArtifacts

或在首选项关闭 API

或者升级系统

**Comment by VersionZKP2356** [comment]
Legacy包确实解决了问题，谢谢。
