### ISSUE TITLE
ubuntu1804安装完成运行时终端报错:failed to commit changes to dconf

### ISSUE THREAD

**Issue by RichardPeng0624** [Qv2ray/Qv2ray#889]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
运行时终端会报错:
dconf-WARNING **: 19:19:27.840: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=3b3a9c0c507542319f40deb86dc2cfd8 --binary-syntax --close-stderr”
且节点均为0kb/s,无法连接.

## 如何触发这个 Bug：

1. 安装完成且配置完core路径后,运行程序在终端中即出现报错.
2. 修改generate目录下的json文件权限,仍然出现该报错.
3. 
4. 

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
windows系统下,使用v2rayN可以连接到节点,故初步判断服务器无问题.

### 相关截图或日志

<details>

```
(process:7464): dconf-WARNING **: 19:19:27.819: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=3b3a9c0c507542319f40deb86dc2cfd8 --binary-syntax --close-stderr”: 子进程退出，代码 1

```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.ubuntu-16.04
```

### 操作系统

- Linux

### 安装来源
- Github Release 
### 已安装的插件、版本及安装来源
无安装插件

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
Assigned to @ymshenyu.

**Comment by ymshenyu** [comment]
请问你是否使用了sudo，su或者root账户来运行qv2ray呢？

**Comment by RichardPeng0624** [comment]
> 请问你是否使用了sudo，su或者root账户来运行qv2ray呢？

您好,我是使用sudo 执行的程序.

**Comment by RichardPeng0624** [comment]
如果不使用sudo直接运行,会提示如下报错: 
无法确定配置文件的位置：
Qv2ray 找到了一个配置文件，但是由于某些错误加载失败。
作为权宜之计，你可以移走这个文件然后重启 Qv2ray：
/home/xxx/.config/qv2ray/Qv2ray.conf
Qv2ray 即将退出。

**Comment by DuckSoft** [comment]
@RichardPeng0624 AppImage 版本不应使用 root 权限运行。你可以用 root 权限删除 /home/xxx/.config/qv2ray 这个文件夹，之后用普通用户重试。

**Comment by RichardPeng0624** [comment]
感谢,这样操作后上述报错消失,但是导入订阅后出现如下错误:
另一进程正在使用启动此连接所需的端口：

入站标签 "_QV2RAY_API_INBOUND_" 需要在 127.0.0.1 监听端口 15490
入站标签 "http_IN" 需要在 127.0.0.1 监听端口 8889
入站标签 "socks_IN" 需要在 127.0.0.1 监听端口 1089

**Comment by EpLiar** [comment]
@RichardPeng0624 杀一下残留进程即可

**Comment by RichardPeng0624** [comment]
谢谢大家,可以用了!但是目前延迟测试还是"错误",我自己再调整一下

**Comment by W-E-A** [comment]
从首选项中把延迟测试改成TCP就可以正常测试了
