### ISSUE TITLE
使用疑问：Ubuntu 20.04 下的蜜汁现象

### ISSUE THREAD

**Issue by Jayj1997** [Qv2ray/Qv2ray#890]
### 你想做啥？
在ubuntu20.04无法(稳定？)连接，至于多不稳定大概就是十分钟里有两秒是连上的……网上暂未看到相关内容，是否对20.04需要额外的设置？

### 你目前试了啥？
看完文档，没有相关内容，就过来问一问。
同样的文件版本 Qv2ray2.6.3 内核版本unkonw
同样设置在ubuntu16.04可以 在同电脑的windows10可以

### 其他要补充的信息？
为毛主力系统用不了yingyingying

**Comment by Jayj1997** [comment]
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
A unified platform for anti-censorship.
2020/08/12 00:20:47 [Warning] v2ray.com/core: V2Ray 4.22.1 started
2020/08/12 00:23:24 127.0.0.1:42768 accepted //clientservices.googleapis.com:443 [outBound_PROXY]
2020/08/12 00:24:27 127.0.0.1:42830 accepted //clients4.google.com:443 [outBound_PROXY]
2020/08/12 00:25:09 127.0.0.1:42842 accepted //safebrowsing.googleapis.com:443 [outBound_PROXY]

补上log

**Comment by Jayj1997** [comment]
想起来问题好像就是那个a unified platform for anti-censorship,之前在windows上也与见过，但是shit忘记当初怎么解决的了。好像就是乱搞了一下就okay了，再不上port
tcp        0      0 127.0.0.1:8888          0.0.0.0:*               LISTEN      15656/v2ray         
tcp        0      0 127.0.0.1:1089          0.0.0.0:*               LISTEN      15656/v2ray         
tcp        0      0 127.0.0.1:15490         0.0.0.0:*               LISTEN      15656/v2ray         
tcp        0      0 127.0.0.1:15490         127.0.0.1:60828         ESTABLISHED 15656/v2ray         
tcp6       0      0 127.0.0.1:60828         127.0.0.1:15490         ESTABLISHED 12490/qv2ray        
udp        0      0 127.0.0.1:1089          0.0.0.0:*                           15656/v2ray         
unix  2      [ ACC ]     STREAM     LISTENING     139381   12490/qv2ray         /tmp/.fnrCeM/s
unix  3      [ ]         STREAM     CONNECTED     142361   12490/qv2ray         
unix  3      [ ]         STREAM     CONNECTED     142363   12490/qv2ray         
unix  3      [ ]         STREAM     CONNECTED     139376   12490/qv2ray         
unix  3      [ ]         STREAM     CONNECTED     142362   12490/qv2ray         
unix  3      [ ]         STREAM     CONNECTED     141383   12490/qv2ray         
unix  3      [ ]         STREAM     CONNECTED     142364   12490/qv2ray

**Comment by DuckSoft** [comment]
最新核心已经 4.27 了。

**Comment by Jayj1997** [comment]
测试发现只有在刚打开浏览器的一段时间可以使用。然后在想是不是开了浏览器顶掉了端口？想了想没道理。发现打开浏览器不到十秒钟代理就被阻止了……我在想是哪个狗贼搞没了我的代理。就想到了刚开始没有装v2ray的时候用的谷歌浏览助手……立即卸载。之后使用正常fuck

**Comment by DuckSoft** [comment]
呃……好。解决了就好。
