### ISSUE TITLE
建议：增加检测一定时间内平均速度达不到指定值，重新启动v2ray。

### ISSUE THREAD

**Issue by nopreq** [Qv2ray/Qv2ray#891]
我在使用telegram上传多个文件时，第一个文件能达到2M。但是第二个文件只有300-500K。但是如果我断开v2ray然后再连接它。速度就能达到2M。后面的文件上传都是这样的现象。请增加一个功能检测到节点平均速度在设定值以下时，重新启动节点。
1.可设置单位时间内上传或下载值。比如，可设置 3秒 平均值 1M 或者 5秒 2M
2低于平均低于设定值 ，重新连接当前使用节点。
谢谢！

**Comment by MarksonHon** [comment]
您好，Qv2ray 的理念是在默认情况下不会“自动”替使用者做出决定，因此，至少最近几个版本不会有自动重启内核的功能。而且，一个节点速度慢一般意味着这个节点连通性差，或者被运营商限制 QoS（服务质量）了，因此个人建议更换更好的节点。

**Comment by nopreq** [comment]
能不能做成一个可选项。
这个节点速度的情况是我重新连接节点后，能达到2M。就是说，不重新连接，只能300k，重新连接后就能达到2M。比如我有两个300M文件，第一个文件的上传平均速度在2M左右直到上传完毕。但如果不重新连接，第二个文件的平均上传速度在300k左右，如果我看到在300k左右，我重新连一下同一个节点，就是点qv2ray 的断开，然后再点一下连接，那第二个文件的上传平均速度也是在2M左右直到上传完毕。多个文件的情况也是一样。强调的是同一个节点。

**Comment by EpLiar** [comment]
@nopreq Qv2ray 是有「重新连接」按钮的

**Comment by nopreq** [comment]
@EpLiar 是有的，我现在就在用，但是假如我有1000个文件上传的话就要盯着速度。达不到就点断开，然后点连接。这个有点什么，我就想能不能增加个可选项，让我设置，就不用一直盯着了。

**Comment by EpLiar** [comment]
@nopreq 「平均速度达不到指定值」会造成误判，尤其是不同线路不同服务不同 QoS 程度的情况下。我们设想一下，如果是对面服务器放缓，那你突然自动重新连接，造成的损失如何处理？如果是无法断点续传的情况呢？

**Comment by nopreq** [comment]
@EpLiar 对的，所以要做成一个可选项，默认不打开。比如我这样的情况，我觉得这样好，就把这个功能打个勾，就在我这样的网络情况下使用。比如你的网络情况和我的不一样，你不勾选这个功能就好了。

**Comment by DuckSoft** [comment]
啊，欢迎 PR，我们太菜了不会做。

**Comment by pvxx** [comment]
建议用Tunnel模式，不会出现掉速哦
