### ISSUE TITLE
升级v2.6.3后mac端运行无响应

### ISSUE THREAD

**Issue by karon110** [Qv2ray/Qv2ray#893]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

昨天升级到2.6.3以后，运行会一直再跳，最后就无响应了，没有任何ui出现，只能强制退出，多次重试结果是一样的。

## 如何触发这个 Bug：

1. 覆盖安装v2.6.3
2. 
3. 
4. 

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
运行以后无响应，所以无法查看
```

### 操作系统

- macOS 10.15.5 (19F101)

### 安装来源

- Github Release / Scoop / Chocolatey 下载地址https://github.com/Qv2ray/Qv2ray/releases/tag/v2.6.3

**Comment by U-v-U** [comment]
Did you try running it from the terminal?

**Comment by karon110** [comment]
> 您是否尝试从终端运行它？

感谢，重启电脑，自动升级系统以后就可以了，升级后版本是10.15.6 (19G73)
