### ISSUE TITLE
Bug Report: Qv2ray GUI glitches with i3wm

### ISSUE THREAD

**Issue by s-kk** [Qv2ray/Qv2ray#894]
- [x] **I'm sure I've tried to reproduce the problem several times and will provide the system environment, each software and its version that is involved in the problem.**

## Briefly describe this bug：
The user interface is glitchy with i3wm, Archlinux.

## How to trigger this bug：

1. Start the Qv2ray GUI
2. The GUI glitches appear

### If it's a connection issue, has it happened in other V2Ray clients?
N/A

### Related screenshots or logs
![20200813095353](https://user-images.githubusercontent.com/51714930/90086197-73e71b00-dd4c-11ea-9eda-729937088893.png)

<details>

```
Please paste your Qv2ray log here:


```

</details>

## System Information
OS: Archlinux
Desktop Environment: i3
Window Manager: i3

```
Version: 2.6.3:5840
Build info: Qv2ray for Arch Linux CN
Extra build info: (Official Build) 5.6.12-arch1-1 x86_64
```

### Operating systems

- [x] Linux
- [ ] macOS
- [ ] Windows
 
### Installation source
 
- [x] ArchLinuxCN - Stable
- [ ] ArchLinuxCN - Dev-git
- [ ] ArchLinux AUR - Stable
- [ ] ArchLinux AUR - Development
- [ ] Fedora - Stable
- [ ] Fedora - Preview
- [ ] openSUSE - Stable
- [ ] openSUSE - Preview
- [ ] Flathub
- [ ] Snap
- [ ] Homebrew Cask
- [ ] Scoop / Chocolatey / Github Release
- [ ] Compile manually

### Installed plugins, versions and sources
N/A

## Additional Info
Could be a conflict between Qv2ray GUI and GTK themes.

**Comment by U-v-U** [comment]
Possible upstream Qt / i3wm bug.

**Comment by DuckSoft** [comment]
Please test other Qt programs (such as qBittorrent, ...) and see if they work normally.
If not, it's an upstream bug and we cannot fix.

**Comment by s-kk** [comment]
@DuckSoft tried qBittorrent, same problem. Seems to be a Qt upstream issue. Thanks a lot for helping!

**Comment by U-v-U** [comment]
Thanks.
