### ISSUE TITLE
[CORE-VCORE]: API call returns: 2 (v2ray.com/core/app/stats/command: outbound>>>outBound_DIRECT>>>traffic>>>uplink not found.) [CORE-VCORE]: API call returns: 2 (v2ray.com/core/app/stats/command: outbound>>>outBound_DIRECT>>>traffic>>>downlink not found.) [CORE-VCORE]: API call failure threshold reached, cancelling further API aclls.

### ISSUE THREAD

**Issue by CandiceYT** [Qv2ray/Qv2ray#895]
版本：2.6.3:5840
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.ubuntu-16.04

v2ray内核配置正常
连接后，无字节传输。

终端出现：
[CORE-VCORE]: API call returns: 2 (v2ray.com/core/app/stats/command: outbound>>>outBound_DIRECT>>>traffic>>>downlink not found.)
[CORE-VCORE]: API call returns: 2 (v2ray.com/core/app/stats/command: outbound>>>YOUNG>>>traffic>>>uplink not found.)
[CORE-VCORE]: API call returns: 2 (v2ray.com/core/app/stats/command: outbound>>>YOUNG>>>traffic>>>downlink not found.)
[CORE-VCORE]: API call returns: 2 (v2ray.com/core/app/stats/command: outbound>>>outBound_BLACKHOLE>>>traffic>>>uplink not found.)
[CORE-VCORE]: API call returns: 2 (v2ray.com/core/app/stats/command: outbound>>>outBound_BLACKHOLE>>>traffic>>>downlink not found.)
[CORE-VCORE]: API call returns: 2 (v2ray.com/core/app/stats/command: outbound>>>outBound_DIRECT>>>traffic>>>uplink not found.)
[CORE-VCORE]: API call returns: 2 (v2ray.com/core/app/stats/command: outbound>>>outBound_DIRECT>>>traffic>>>downlink not found.)
[CORE-VCORE]: API call failure threshold reached, cancelling further API aclls.

**Comment by U-v-U** [comment]
你的核心版本是？
请不要在 v4.26 以下版本启用出站统计

**Comment by CandiceYT** [comment]
V2Ray output: V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom;A unified platform for anti-censorship.

**Comment by CandiceYT** [comment]
我没打开出站统计操作，只在入站里边配置了

**Comment by DuckSoft** [comment]
核心版本过低。
