### ISSUE TITLE
无法启用系统代理

### ISSUE THREAD

**Issue by yidasanqian** [Qv2ray/Qv2ray#899]
<img width="265" alt="无法启动系统代理" src="https://user-images.githubusercontent.com/10655188/90308623-7c3d8280-df13-11ea-8d2c-2815e61d818b.png">

使用的最新版

**Comment by DuckSoft** [comment]
你连节点了吗

**Comment by yidasanqian** [comment]
点击连接无反应

**Comment by cangyin** [comment]
加入 [Qv2ray群组](https://t.me/qv2ray)，方便交流

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/90308769-f589a500-df14-11ea-8af6-1fe364e442a7.png)
双击节点以连接。没连过节点，当然点连接无效。

**Comment by yidasanqian** [comment]
可以了，感觉可以优化下，第一次用，还以为点击一次就可以了，还要双击
