### ISSUE TITLE
功能请求：Windows 添加高优先级自启动

### ISSUE THREAD

**Issue by wanzzhehe** [Qv2ray/Qv2ray#902]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
在Win10启动以后，qv2ray启动顺位过低，导致需要等待相当一段时间后才能使用代理

**简单描述你预期的解决方案？**
添加高优先级启动（可能需要管理员权限）

**你有想到其他比较容易实现的解决方案吗？**
没有

**补充内容**
我是在 Wallpaper Engine中看到高优先级启动时产生的想法，这样就能够在系统刚刚启动时就使用代理而不是要先盯一会儿桌面或者浏览器的“你的代理服务器出现问题”界面（笑

**Comment by wanzzhehe** [comment]
在Linux下如果是用Systemd的话倒比较容易实现，不过Windows下我没怎么了解过

**Comment by DuckSoft** [comment]
太菜了，不会写……欢迎 PR。

**Comment by DuckSoft** [comment]
大概调查了一下，是注册了系统服务，然后实现的这个效果。
不过鉴于 Qv2ray 属于用户进程，这样做可能的确有些不太清真……
https://steamcommunity.com/app/431960/discussions/2/1354868867716403366/

**Comment by sagasm** [comment]
在自启动里面调整下顺序看看

**Comment by Copay** [comment]
@wanzzhehe 可以试一试task scheduler

**Comment by wanzzhehe** [comment]
@Copay 谢谢，我去看看

**Comment by DuckSoft** [comment]
暂时关闭本 Issue。
