### ISSUE TITLE
功能请求：正在使用的服务器能不能高亮显示？

### ISSUE THREAD

**Issue by leoxxx** [Qv2ray/Qv2ray#905]
服务器一多，一个小黑点有时很难注意到在用哪个。主要是因为连接过的服务器边上都有个延迟数，就算没在用，也会显示上次的数，有点迷。
现在选中时为淡蓝底，黑字。那能不能使用时的高亮改成黄底红字？颜色方面我也不是很懂，或者还有更好的配色？

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/90504456-ac8b5800-e183-11ea-80dd-c5314410bd64.png)
