### ISSUE TITLE
使用疑问：qv2ray的配置文件在哪里,如何重置它们

### ISSUE THREAD

**Issue by hehelego** [Qv2ray/Qv2ray#906]
### 你想做啥？
*简要描述你的最原始的目的。*

我乱搞了一波配置...然后不能正常访问wikipedia,代理挂了(服务器没事...)  
我在另一台机子上面重新安装qv2ray,按照user-manual配置,它成功连接服务器并可以正常访问wikipedia等网站.  
我意识到是配置有问题,想要把配置恢复default settings,但是qv2ray本体并不提供这个功能.

另外如何重置v2ray core的配置啊....

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*

我删掉了`~/.config/qv2ray/`以及`~/.config/qv2rayrc`然后用pacman重装qv2ray.  
启动发现之前的配置还在那里.

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by hehelego** [comment]
删了`~/.config/qv2rayrc ~/.config/qv2ray`,把v2ray本体也删掉...reboot,重装.  
然后它现在正常....  

虽然我仍然不知道如何正确重置配置...

**Comment by DuckSoft** [comment]
可能是我语文不太好，没看懂你的问题。

**Comment by zhihuiyuze** [comment]
在Windows中qv2ray生成的v2ray配置文件在C:\Users\zhyz\AppData\Local\qv2ray\generated\config.gen.json里
