### ISSUE TITLE
窗口上只有首选项和插件

### ISSUE THREAD

**Issue by learnonroad** [Qv2ray/Qv2ray#907]
ubuntu16.04 
2.6.3

**Comment by learnonroad** [comment]
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 qv2ray : 依赖: libc6 (>= 2.28) 但是 2.23-0ubuntu11.2 正要被安装
          依赖: libgrpc++1 但无法安装它
          依赖: libprotobuf17 但无法安装它
          依赖: libqt5core5a (>= 5.11.3-1~) 但是 5.5.1+dfsg-16ubuntu7.7 正要被安装
          依赖: libqt5gui5 (>= 5.11.3-1~) 但是 5.5.1+dfsg-16ubuntu7.7 正要被安装
          依赖: libqt5network5 (>= 5.11.3-1~) 但是 5.5.1+dfsg-16ubuntu7.7 正要被安装
          依赖: libqt5widgets5 (>= 5.11.3-1~) 但是 5.5.1+dfsg-16ubuntu7.7 正要被安装
          推荐: v2ray 但无法安装它
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。



 初步怀疑是qt版本问题... 5.9 & 4.9

**Comment by DuckSoft** [comment]
16.04 用不了 deb，版本太老了。
建议从 snap 装。
