### ISSUE TITLE
Debian 仓库无 i386 架构

### ISSUE THREAD

**Issue by mal1029** [Qv2ray/Qv2ray#911]
信息如下：

N: 鉴于仓库 'https://raw.fastgit.org/Qv2ray/debian/master stable InRelease' 不支持 'i386' 体系结构，跳过配置文件 'main/binary-i386/Packages' 的获取。
N: 鉴于仓库 'https://qv2ray.net/debian stable InRelease' 不支持 'i386' 体系结构，跳过配置文件 'main/binary-i386/Packages' 的获取。

请问该如何处理？

**Comment by DuckSoft** [comment]
暂时的解决方案：从 snap 安装。
至于是否给 Debian 仓库追加 32 位支持，需要仓库维护者 @ymshenyu 进行裁断。

**Comment by ymshenyu** [comment]
现在各大linux发行版都在逐渐放弃i386，snap已经一段时间没有释出这个架构的包了。

**Comment by DuckSoft** [comment]
Snap 的底裤容器自 Ubuntu 20.04 以后就不再提供对 i386 架构的支持了，因此恐怕 Snap 上面的版本不是最新的。
但愿我们有足够的理由相信仍在使用 i386 架构的 Linux 用户有足够的能力自行从源码编译并解决其他一切相关问题。

**Comment by mal1029** [comment]
抱歉我不是很懂计算机系统和编程。

我用的64位的，Deepin 20版本，应该是基于Debian 8的吧。

是否跟我先通过Deepin里的星活商店安装有关？

**Comment by DuckSoft** [comment]
那上面两条信息大概属于警告了。
如果你现在能正常安装并使用，就无需顾虑。

**Comment by mal1029** [comment]
谢谢。

**Comment by soenggam** [comment]
@mal1029 那就请用dpkg --remove-architecture移除i386架构

**Comment by mal1029** [comment]
> @mal1029 那就请用dpkg --remove-architecture移除i386架构

dpkg --print-architecture 显示 只有 amd64哦
