### ISSUE TITLE
Deepin遇到了错误环境变量错误问题

### ISSUE THREAD

**Issue by mal1029** [Qv2ray/Qv2ray#913]
在Deepin上遇到了这个信息不知道怎么处理：

¨Deepin可能自作聪明，为你设置了错误的 HTTPS_PROXY 和 FTP_PROXY 环境变量。
原来正确的 http:// 可能被错误地替换为 https:// 和 ftp://，导致这个问题。¨

![image](https://user-images.githubusercontent.com/70007703/90974564-05ca0180-e55f-11ea-8d1b-d38e2306bb01.png)

另外，连接后，log信息里有：

![截图录屏_选择区域_20200823164731](https://user-images.githubusercontent.com/70007703/90974760-97863e80-e560-11ea-9ad3-92eb9ddfd765.png)

这是代表安装和设置有问题？

谢谢。

**Comment by xmuli** [comment]
> 我都帮他们把这个问题暂时修好了（[linuxdeepin/go-lib#16](https://github.com/linuxdeepin/go-lib/pull/16) ），代码也已经合并进 Deepin 了（[linuxdeepin/go-lib@cbd8ac9](https://github.com/linuxdeepin/go-lib/commit/cbd8ac9a8afccbbc6d4c0cc5bae50f4621434de9) ），但 Deepin 迟迟就是不把更新放出来，我也没啥办法。

我它喵的也很奇怪~，我有帮助合并代码，但是居然依旧还是有问题，然后刚才一查，发现注释代码,提交到 develop 分支去了，而现在主要使用的分支，都是 uso / master 等默认分支（少数例外）。

现在正在沟通，建议他们直接让用户自定义后面一部分的环境边境字符串（这边不做检查和拼写～），双方都省心省力

**Comment by huya1121** [comment]
![image](https://user-images.githubusercontent.com/13938600/107146115-0b869880-6981-11eb-91e5-8fe94d509935.png)
Deepin 已经在新版本中修复了此问题，但是Qv2ray目前还会有这个提示
[Release]
Version=20.1
Type=Desktop
Type[zh_CN]=社区版
Edition=Y2020E0001
Copyright=Y2020CR001
[Addition]
Milestone=
Buildid=build1

**Comment by DuckSoft** [comment]
那是因为你只更新了 Deepin.

**Comment by huya1121** [comment]
> 那是因为你只更新了 Deepin.

我目前Qv2ray版本是2.6.3

![image](https://user-images.githubusercontent.com/13938600/107146206-96679300-6981-11eb-9250-d16113eaf7bd.png)

**Comment by DuckSoft** [comment]
https://xmuli.tech/posts/60b2fbd8/
https://github.com/linuxdeepin/go-lib/issues/15

![图片](https://user-images.githubusercontent.com/7822648/107146254-e34b6980-6981-11eb-94e4-d43bb9b36a83.png)

**Comment by huya1121** [comment]
> https://xmuli.tech/posts/60b2fbd8/
> [linuxdeepin/go-lib#15](https://github.com/linuxdeepin/go-lib/issues/15)
> 
> ![图片](https://user-images.githubusercontent.com/7822648/107146254-e34b6980-6981-11eb-94e4-d43bb9b36a83.png)

Deepin可能自作聪明，为你设置了错误的 HTTPS_PROXY 和 FTP_PROXY 环境变量。
原来正确的 http:// 可能被错误地替换为 https:// 和 ftp://，导致这个问题。
Qv2ray 很遗憾无法帮你改回来。若因此遇到问题，请勿指责吾等。

从提示上看http proxy被错误的替换为https/ftp，但是实际上目前deepin 21的环境变量显示是正确的，并没有错误。。。
请问是我理解环境变量的设定有错误吗？
``` no_proxy=localhost,127.0.0.0/8,::1
``` ftp_proxy=ftp://127.0.0.1:8889
``` https_proxy=https://127.0.0.1:8889
``` http_proxy=http://127.0.0.1:8889

**Comment by DuckSoft** [comment]
是的，你的理解有问题。
```
ftp_proxy=ftp://127.0.0.1:8889
https_proxy=https://127.0.0.1:8889
```
这俩是错的。

**Comment by huya1121** [comment]
> 是的，你的理解有问题。
> 
> ```
> ftp_proxy=ftp://127.0.0.1:8889
> https_proxy=https://127.0.0.1:8889
> ```
> 
> 这俩是错的。

好，多谢。。。 那只能等Deepin官方修复了。 多谢
