### ISSUE TITLE
功能请求：兼容 “Clash” 节点导入 

### ISSUE THREAD

**Issue by iam7cn** [Qv2ray/Qv2ray#914]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
clash节点需要手动导入软件太麻烦

SS格式
{"name":"AE_1","server":"45.9.249.X","port":34583,"type":"ss","password":"hbWeaNJfjeP6GkT7jp6CSSx8","cipher":"aes-256-gcm"}
SSR格式
{"name":"JP_252","server":"172.105.192.X","port":8099,"type":"ssr","password":"eIW0Dnk69454e6nSwuspv9DmS201tQ0D","cipher":"aes-256-cfb","protocol":"origin","protocol_param":"xxxx","obfs":"plain","obfs_param":"xxx"}
Vmess格式
{"name":"JP_269","server":"xxx.xxx","port":443,"type":"vmess","uuid":"d8e23fb9-ab15-31ad-8eac-916704aa26e0","alterId":0,"cipher":"auto","network":"ws","http-opts":{},"ws-path":"/hls/cctv5phd.m3u8","ws-headers":{"HOST":"xxxx"},"skip-cert-verify":true,"servername":"xxxx"}

观察和Qv2ray的json格式不一样
希望能加入

**Comment by DuckSoft** [comment]
WIP: https://github.com/U-v-U/QvPlugin-ClashSubscription/
