### ISSUE TITLE
不开QV2Ray所有软件都连不了网，使用了QV2Ray后。请问怎么办？

### ISSUE THREAD

**Issue by mal1029** [Qv2ray/Qv2ray#915]
系统 Deepin V20

问题：无论什么连接，我都需要开启QV2Ray才能连接。

请指教。

**Comment by DuckSoft** [comment]
inuxdeepin/go-lib#15

**Comment by mal1029** [comment]
我是说在不需要开启proxy直接连接时，我的网络连接都没有，现在我必须打开proxy软件。

**Comment by DuckSoft** [comment]
不懂。要不你找个 Deepin 专家帮你整整？
Qv2ray 开发组没人在用 Deepin。

**Comment by mal1029** [comment]
谢谢

**Comment by DuckSoft** [comment]
我个人猜测是 Deepin 在同步系统代理设置的时候只同步了代理开启，没有同步代理的关闭。
我本人不使用 Deepin，如果有 Deepin 开发者能协助调查，那将是极好的。

**Comment by mal1029** [comment]
> 我个人猜测是 Deepin 在同步系统代理设置的时候只同步了代理开启，没有同步代理的关闭。
> 我本人不使用 Deepin，如果有 Deepin 开发者能协助调查，那将是极好的。

非常感谢。

**Comment by luojiego** [comment]
我在 **Ubuntu 20.04** 也遇到同样的问题了，**不开 qv2ray** 并且**未设置正常的连接**下，就是无网络状态。
