### ISSUE TITLE
功能请求：增加二维码扫描和批量导出导入功能

### ISSUE THREAD

**Issue by hhhaiai** [Qv2ray/Qv2ray#916]
二维码扫描动态加入新链接。
导入导出功能可以和其他软件间互相切换，建议增加此类功能

**Comment by DuckSoft** [comment]
二维码扫描已有。
![图片](https://user-images.githubusercontent.com/7822648/91380446-93f00180-e857-11ea-88fb-4f11ddd65193.png)

导入导出功能可以和其他软件间互相切换，是个啥意思呢？
哪些其他软件？怎么个互相切换法？还请明示。

**Comment by DuckSoft** [comment]
此外，本 Issue 未遵循 Issue 模板。直接关闭。
