### ISSUE TITLE
功能请求：改进UI/UX设计。

### ISSUE THREAD

**Issue by 0x0004** [Qv2ray/Qv2ray#917]
**你的功能请求与使用中遇到的麻烦有关吗？
本来以为找到了大统一的客户端，解决了 [偶尔自用ss,公司用ssr，测试用v2ray，给客户的文件夹里往往包含几种不同的软件] 这种乱象。
但目前版本的UI和用户体验真的有点一言难尽。

**简单描述你预期的解决方案？
已经使用QT无疑是当下最正确的。可以在能力范围内请一些美工朋友，产品经理，UI设计师，用户体验设计师，来帮忙看下，使Qv2ray变得更好。(比如界面借鉴v2rayN)

**你有想到其他比较容易实现的解决方案吗？
微信里摇银儿。

**补充内容
大统一客户端终于还是来了，泪目。respect！

**Comment by clang-with-gcc** [comment]
俺认为目前 Qv2ray 的界面设计并不逊于 V2rayN，附上对比图。

![图片](https://user-images.githubusercontent.com/69034721/91404978-5fd70980-e874-11ea-942f-7a03aff4a28d.png)
![图片](https://user-images.githubusercontent.com/69034721/91405028-64032700-e874-11ea-817a-2a2199235b80.png)

**Comment by U-v-U** [comment]
🤣 OK, We'll continue improving our UI design.
