### ISSUE TITLE
核心可执行文件不存在

### ISSUE THREAD

**Issue by CodyGuo** [Qv2ray/Qv2ray#919]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 如何触发这个 Bug：

1. 
2. 
3. 
4. 

### 相关截图或日志
![image](https://user-images.githubusercontent.com/10672966/91786186-9e384400-ec39-11ea-99ac-786402bff651.png)

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 
编译信息：
额外编译信息：
```

### 操作系统

- Linux
- macOS
- Windows

### 安装来源

- ArchLinuxCN - 稳定版
- ArchLinuxCN - 开发版
- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版
- Fedora - 稳定版
- Fedora - 开发版
- openSUSE - 稳定版
- openSUSE - 开发版
- Flathub 包
- Snap 包
- Homebrew Cask
- Github Release / Scoop / Chocolatey
- 手动编译

## 附加信息

*请注意打码隐私相关信息。*

**Comment by CodyGuo** [comment]
Windows 安装版本

**Comment by FANminiworld** [comment]
@CodyGuo @DuckSoft close,please

**Comment by MarksonHon** [comment]
@FANminiworld 请自行阅读我们的文档<https://qv2ray.net>，此类 issue 将会被关闭，因为这里您未按照文档进行操作导致的问题，而不是软件出了故障。

**Comment by FANminiworld** [comment]
@MarksonHon @CodyGuo

**Comment by DuckSoft** [comment]
反馈BUG前的注意事项，想必你已经读过了：

2. 发 Issue 之前请确保你已阅读过相关文档、搜索过之前的Issue。如果如果文档里明确有的，那么 Issue 可能被不加提示直接关闭；如果之前的 Issue 已有答案 / 解决方案，可能会被发一个链接直接关闭；当然，也可能根据开发者心情，给你多回几句。我们对此不做任何保证。

4. 若不遵守模板，根据开发者的心情，你的 Issue 可能会被直接关闭，不需要进一步解释。

**Comment by U-v-U** [comment]
🌽

**Comment by CodyGuo** [comment]
操作太复杂了，只能放弃。

**Comment by FANminiworld** [comment]
@CodyGuo 你觉得不好用，你可以用别的，这个项目并不面向大众开发

**Comment by MarksonHon** [comment]
@CodyGuo 其实看懂了文档也就能上手了，放弃了就有点可惜了。

**Comment by CodyGuo** [comment]
不能开箱即用，不如在找一个。

**Comment by 12101111** [comment]
Windows从来都不能开箱即用
