### ISSUE TITLE
VLESS模式的时候，右下角的速度和数据无法统计以及左侧列表

### ISSUE THREAD

**Issue by sunleonx** [Qv2ray/Qv2ray#920]
VLESS模式的时候，右下角的速度和数据无法统计以及左侧列表
![image](https://user-images.githubusercontent.com/38236663/91844725-889f3a80-ec8a-11ea-8edf-8b166451a47e.png)

**Comment by U-v-U** [comment]
Known bug, already fixed.

**Comment by U-v-U** [comment]
Did you read https://github.com/Qv2ray/Qv2ray/issues/883 ?

**Comment by DuckSoft** [comment]
see #883 for the cure.
