### ISSUE TITLE
Question: <Your Awesome Question>please help me install plugin easy way

### ISSUE THREAD

**Issue by dawoodiran** [Qv2ray/Qv2ray#922]
### Any Other Thing

hi 
i use linux mint 20
![نماگرفت از 2020-09-01 20-43-36](https://user-images.githubusercontent.com/34414138/91885608-53501800-ec9d-11ea-999d-572dcea4b5dd.png)
![نماگرفت از 2020-09-01 20-43-05](https://user-images.githubusercontent.com/34414138/91885641-5ea34380-ec9d-11ea-9bd9-fa0eca67a4e7.png)
![نماگرفت از 2020-09-01 20-37-51](https://user-images.githubusercontent.com/34414138/91885659-64992480-ec9d-11ea-9f05-2830796a4a53.png)
![نماگرفت از 2020-09-01 20-52-59](https://user-images.githubusercontent.com/34414138/91885692-74186d80-ec9d-11ea-9f4c-66bfdc31368d.png)

**Comment by flylai** [comment]
Read the **[DOCUMENT](https://qv2ray.net/plugins/)** for more details.

**Comment by sixg0000d** [comment]
[English version here](https://qv2ray.net/en/plugins/)

**Comment by DuckSoft** [comment]
BTW from your screenshots it seems that you are not downloading binary releases but source code tarballs instead which won't be able to be loaded by Qv2ray to serve as plugins. You should download from "releases" like https://github.com/Qv2ray/QvPlugin-Trojan/releases and get something like `xxxxx.so` instead of `xxxxx.tar.gz`.

**Comment by U-v-U** [comment]
FYI, the correct layout should be
 
![image](https://user-images.githubusercontent.com/59914293/91934022-d1073880-ed1c-11ea-8082-4af958342bcb.png)

**Comment by dawoodiran** [comment]
*Thank you my problem of load plugin solved by your help  .please write
complete help for beginner as i.for example i find how can use v2ray core
or how can firefox or Telegram desktop myself.*
*if you have plugin for wireguard or clash in linux please tell me   thank
you for all thing*

‫‪QxQ‬‏ <‪notifications@github.com‬‏> در تاریخ چهارشنبه ۲ سپتامبر ۲۰۲۰ ساعت
۹:۳۴ نوشت:‬

**Comment by U-v-U** [comment]
1. Thanks for letting me know it's working, Clash is another platform that is, quite different from V2Ray, did you mean trying to import the Clash configuration?
2. There's no current wireguard plugin currently, so sad.
