### ISSUE TITLE
在分组名上右键更新订阅总是显示只有0条可用

### ISSUE THREAD

**Issue by cangyin** [Qv2ray/Qv2ray#923]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
在分组名上右键更新订阅总是显示只有0条可用，Qv 首选项中已经设置使用系统代理，但是更新订阅时没有连接信息。
而在 组编辑器 界面进行更新订阅则正常。 

## 如何触发这个 Bug：

1. 右键分组名
2. 点击 **更新订阅**
3. 迅速弹出如下窗口
![image](https://user-images.githubusercontent.com/50256182/91943370-12a0df00-ed2f-11ea-8835-37ce5b6a8cc1.png)

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
未知

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5898
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-c0a01b01df54150bc87c4f9aafbab6dc97e69246-ci.windows-latest
```

### 操作系统
- Windows

### 安装来源
- Github Release / Scoop / Chocolatey

### 已安装的插件、版本及安装来源
![image](https://user-images.githubusercontent.com/50256182/91943482-3ebc6000-ed2f-11ea-87c3-13cdf790060b.png)

## 附加信息

使用拨号连接方式联网。已经设置拨号连接代理。

**Comment by DuckSoft** [comment]
尝试手动指定代理而非“使用系统代理”。
Qt 可能没有认到你的系统代理。

**Comment by cangyin** [comment]
但是在 **组编辑器** 界面进行更新订阅是正常的。

**Comment by DuckSoft** [comment]
可能是 QNetworkAccessManager 生命周期的问题？
@U-v-U

**Comment by U-v-U** [comment]
Cannot reproduce

**Comment by cangyin** [comment]
Re-downloaded Qv2ray, now I can't reproduce too. >_<
