### ISSUE TITLE
功能请求：能否增加通过gfwList.txt解析自定义的规则，感觉这块有所欠缺，或者使用v2ray中的geoip.dat和geosite.dat

### ISSUE THREAD

**Issue by sunleonx** [Qv2ray/Qv2ray#924]
功能请求：能否增加通过gfwList.txt解析自定义的规则，感觉这块有所欠缺，或者使用v2ray中的geoip.dat和geosite.dat，目前无法选择。希望能完善此功能。

**Comment by U-v-U** [comment]
为什么不看看这里呢 [qv2ray://open/preference/route](qv2ray://open/preference/route)

**Comment by sunleonx** [comment]
> 为什么不看看这里呢 [https://qv2ray.net/manual/route.html#%E5%85%A8%E5%B1%80%E8%B7%AF%E7%94%B1%E8%A7%84 ％E5％88％99](https://qv2ray.net/manual/route.html#%E5%85%A8%E5%B1%80%E8%B7%AF%E7%94%B1%E8%A7%84%E5%88%99)

能否给一下相应的配置，我把相关的文件下载下来了，不太能理解如何配置

**Comment by cangyin** [comment]
就差手把手教你了，请自己查看 [Qv2ray文档](https://qv2ray.net/)

**Comment by sunleonx** [comment]
解决了，谢谢各位
