### ISSUE TITLE
KDE桌面环境深色模式下的图标适配

### ISSUE THREAD

**Issue by wallena3** [Qv2ray/Qv2ray#926]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
KDE 桌面环境的深色模式下，Qv2ray的图标会变的看不清。白色的按钮底色，灰白色的形状轮廓。

**简单描述你预期的解决方案？**
检测桌面环境在深色模式还是正常模式，分别加载不同的图标配色方案

**你有想到其他比较容易实现的解决方案吗？**
深色模式下按钮底色可变为黑色/深灰色，按钮中的形状轮廓颜色可不变

**Comment by wallena3** [comment]
今晚我会上传一个截图 明确展示这个issue所表达的问题

**Comment by U-v-U** [comment]
![image](https://user-images.githubusercontent.com/59914293/92066004-6b29b800-edd3-11ea-8a53-4b9871b65aa2.png)

**Comment by DuckSoft** [comment]
呃……如果你有认真读过我们的安装指引……就不会有这个问题了。

https://qv2ray.net/getting-started/step5.html#%E8%B0%83%E6%95%B4%E7%95%8C%E9%9D%A2%E4%B8%8E%E6%98%BE%E7%A4%BA%E8%AF%AD%E8%A8%80

**Comment by wallena3** [comment]
抱歉！ 非常感谢
