### ISSUE TITLE
为啥我的Qv2ray的界面这么大

### ISSUE THREAD

**Issue by caochuangjing** [Qv2ray/Qv2ray#928]
### 你想做啥？
*简要描述你的最原始的目的。*
 

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
例：看完文档，没有相关内容，就过来问一问。

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by U-v-U** [comment]
所以是，，需要直连还是觉得 ui  太大？

**Comment by U-v-U** [comment]
试试用 `--noScaleFactor` 启动 Qv2ray ？

**Comment by DuckSoft** [comment]
大概是因为在小屏幕设备上面开启了 Windows 自带的非整数倍缩放，Qt 这边进行了二次缩放，导致文字看起来过于难受。请以 `--noScaleFactor` 命令行参数启动 Qv2ray 即可解决。
