### ISSUE TITLE
使用疑问：Qv2ray开机时弹出主界面且无法设置关闭

### ISSUE THREAD

**Issue by nukemiko** [Qv2ray/Qv2ray#931]
### 你想做啥？
*简要描述你的最原始的目的。*
**开机时静默启动，不要弹出主界面**

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
**macOS 10.15.6：在 系统偏好设置>用户与群组>启动项 中勾选了Qv2ray后面的“隐藏”，勾选了Qv2ray首选项中的“登录时启动”和“安静模式”；
Arch Linux(桌面环境为KDE)、Windows 10：勾选了Qv2ray首选项中的“登录时启动”和“安静模式”**

### 其他要补充的信息？
*在此附加其他需要补充的信息。*
**“安静模式”似乎不能阻止Qv2ray开机时弹出主界面，macOS中设置Qv2ray启动时隐藏也不管用**

**Comment by EpLiar** [comment]
已知问题，目前没有确切的解决方法，持续关注中…

**Comment by DuckSoft** [comment]
未有设置“启动时自动连接”节点时，启动时弹出主界面是故意而为之。

**Comment by nukemiko** [comment]
> 未有设置“启动时自动连接”节点时，启动时弹出主界面是故意而为之。

我把“自动连接”设置为“记忆上次的连接”，是这个导致的吗？

**Comment by DuckSoft** [comment]
@nukemiko Arch Linux / Windows 上设置了自动连接的节点之后，无法复现

**Comment by nukemiko** [comment]
> @nukemiko Arch Linux / Windows 上设置了自动连接的节点之后，无法复现

啊，那就是macOS  only了，还可能只有我的系统有这问题

**Comment by HsunGong** [comment]
> > @nukemiko Arch Linux / Windows 上设置了自动连接的节点之后，无法复现
> 
> 啊，那就是macOS only了，还可能只有我的系统有这问题

遇到同样的问题，macos。待解决。

此外，qv2ray在docker上会显示图标，并且没有办法隐藏。
更正办法：Refer to `https://blog.csdn.net/qq_37417018/article/details/100109676`
![image](https://user-images.githubusercontent.com/32933986/92581842-c6234980-f2c2-11ea-9ff8-417b5bf0f618.png)

**Comment by Zoupers** [comment]
@DuckSoft 既然都是安静模式了，为什么还要主动弹出窗口呢，我在Manjaro上使用Qv2ray是也遇到了这个开机自动弹出的问题，而且不论如何修改自动连接的模式都无法关掉这个自动弹窗。我已经勾选了安静模式，请问这个如何解决呢？

**Comment by U-v-U** [comment]
如果你没有设置自动连接，那么自动弹出窗口是预期行为

**Comment by Zoupers** [comment]
> @DuckSoft 既然都是安静模式了，为什么还要主动弹出窗口呢，我在Manjaro上使用Qv2ray是也遇到了这个开机自动弹出的问题，而且不论如何修改自动连接的模式都无法关掉这个自动弹窗。我已经勾选了安静模式，请问这个如何解决呢？

最终我发现了是因为Manjaro在某个不知名的地方还有自动启动项（虽然我没有找到在哪里），但是我把autostart目录下的qv2ray.desktop删除了过后就好了，开机仍然自启，但是不会弹窗。
