### ISSUE TITLE
Deepin OS set system https proxy failed.

### ISSUE THREAD

**Issue by jingrongx** [Qv2ray/Qv2ray#932]
In Deepin Qv2ray can't set https proxy.

Workaround:
Add following two lines to .bashrc.

$ vi ~/.bashrc
export http_proxy="http://127.0.0.1:8080"
export https_proxy="http://127.0.0.1:8080"

**Comment by DuckSoft** [comment]
THIS IS NOT A QV2RAY BUG. IT'S A DEEPIN BUG!

Duplicate: #589 #672 #863 #913 #915 

Qv2ray was the first to report and fix this bug for upstream.
See https://github.com/linuxdeepin/go-lib/issues/15 and https://github.com/linuxdeepin/go-lib/pull/16.

DO NOT TAKE IT WRONG.
