### ISSUE TITLE
SS-V2RAY配置方法

### ISSUE THREAD

**Issue by jiujiu1** [Qv2ray/Qv2ray#934]
# Shadowsocks(v2ray-plugin)
- name: "ss-v2ray"
  type: ss
  server: 104.***
  port: 443
  cipher: chacha20-ietf-poly1305
  password: "532**11"
  plugin: v2ray-plugin
  plugin-opts:
    mode: websocket # no QUIC now
    tls: true # wss
    skip-cert-verify: true
    host: www.jiun**qh.com
    path: "/5352"
    mux: 0
    headers:
      custom: value

这个格式的怎么配置???有个KEY不知道怎么填

**Comment by U-v-U** [comment]
![image](https://user-images.githubusercontent.com/59914293/92193907-01291580-ee9c-11ea-89a0-5ab0318f2341.png)
![image](https://user-images.githubusercontent.com/59914293/92193911-04240600-ee9c-11ea-80aa-3fb2bd1dfa9a.png)
