### ISSUE TITLE
无法代理局域网

### ISSUE THREAD

**Issue by driftingdream** [Qv2ray/Qv2ray#935]
### 无法访问 LAN 网络
访问 LAN 网络

### 你目前试了啥？
删去图片处的 `geoip:private`无效
![image](https://user-images.githubusercontent.com/16973422/92326876-fd59e680-f087-11ea-9b66-cf9eaee98461.png)
高级路由设置中，添加代理项 geoip:private 无效，依然走 OutBound_Direct
![image](https://user-images.githubusercontent.com/16973422/92326912-46aa3600-f088-11ea-9520-57a8d921cf38.png)

**Comment by EpLiar** [comment]
私有地址走代理，是有什么特殊需求吗？

**Comment by DuckSoft** [comment]
私有地址目前设定为强制直连。
若有需求让私有地址也走代理，请使用复杂配置。

**Comment by driftingdream** [comment]
> 私有地址目前设定为强制直连。
> 若有需求让私有地址也走代理，请使用复杂配置。

不好意思，我找不到复杂配置的相关文档，能发个 link 吗

**Comment by EpLiar** [comment]
@driftingdream 其实就是添加节点的时候打勾复杂配置，粘贴 json 格式的配置就行

**Comment by driftingdream** [comment]
> @driftingdream 其实就是添加节点的时候打勾复杂配置，粘贴 json 格式的配置就行

了解，谢谢指教
