### ISSUE TITLE
http身份验证无效

### ISSUE THREAD

**Issue by myktw** [Qv2ray/Qv2ray#936]
## 简单描述这个 Bug:

http设置开启身份验证无效无需验证直接使用

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.windows-latest
```

### 操作系统

- Windows

### 安装来源

- Github Release / Scoop / Chocolatey

### 已安装的插件、版本及安装来源

SSR Plugin

**Comment by DuckSoft** [comment]
```bash
$ export http_proxy=http://127.0.0.1:8000 && export https_proxy=http://127.0.0.1:8000
$ curl https://google.com
curl: (56) Received HTTP code 407 from proxy after CONNECT
```

```bash
$ export http_proxy=http://qv2ray:lover@127.0.0.1:8000 && export https_proxy=http://qv2ray:lover@127.0.0.1:8000
$ curl https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```

无法复现。

**Comment by myktw** [comment]
问题出在软件生成配置上无法正常生成http的身份验证socks则可以正常生成
![QQ截图20200907183143](https://user-images.githubusercontent.com/35424096/92378495-77e23f00-f138-11ea-8966-1d42db36b73b.png)

**Comment by U-v-U** [comment]
![image](https://user-images.githubusercontent.com/59914293/92422982-eca58f80-f1b1-11ea-87d4-771e50673d51.png)

**Comment by EpLiar** [comment]
![image](https://user-images.githubusercontent.com/23559565/92423133-88370000-f1b2-11ea-83c7-98aa64f68a09.png)

**Comment by AStupidBear** [comment]
@DuckSoft I can reproduce this with QV2ray installed by Scoop

**Comment by DuckSoft** [comment]
> @DuckSoft I can reproduce this with QV2ray installed by Scoop

Umm……Maybe you want to use our most recent version.
Check them out here if you are using Scoop: https://github.com/kidonng/sushi#qv2ray

**Comment by DuckSoft** [comment]
> @DuckSoft I can reproduce this with QV2ray installed by Scoop

We've located the problem. It's caused by an improper initialization of configuration file from Scoop.
We'd fix this soon.
