### ISSUE TITLE
Bugdows VPN 系统代理设置问题

### ISSUE THREAD

**Issue by everfate** [Qv2ray/Qv2ray#938]
## 简单描述这个 Bug:
win10已经开启windows自建VPN后，使用qv2ray进行连接无法接管系统代理

## 如何触发这个 Bug：

1. 建立一个windows自带vnp并连接，个人是由于使用校园网需要vpn
2. 开启qv2ray连接
3. 无法代理流量，无法fq，日志中没有显示任何代理

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
使用过clash，v2rayN都可以正常使用
这两个软件连接时可以使我正常连接校园网络，但无法连接校园内网。

### 相关截图或日志
![image](https://user-images.githubusercontent.com/61395772/92381806-1ae98780-f13e-11ea-9b3e-f10ad355b7be.png)

<details>

请从此行下面的行开始粘贴 Qv2ray 日志：

V2Ray 4.27.5 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.7 windows/amd64)
A unified platform for anti-censorship.
2020/09/07 19:05:20 [Warning] v2ray.com/core: V2Ray 4.27.5 started
2020/09/07 19:05:20 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  C:/Users/razgzy/AppData/Local/qv2ray/generated/config.gen.json
2020/09/07 19:05:20 127.0.0.1:4485 accepted tcp:127.0.0.1:0 [_QV2RAY_API_]

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.windows-latest
```

### 操作系统

- Windows 10 家庭版

### 安装来源

- Github Release

### 已安装的插件、版本及安装来源

启用和不启用插件都已经尝试，可视为没有使用插件。

## 附加信息

个人认为是VPN的优先级问题？
因为连接校园网本来是使用特定客户端（windows 自带VPN的封装），使用v2rayN是和现在情况一样，无法接管流量。之后我停用校网客户端，改用自建windows VPN，就可以正常连接。
自建VPN配置：
![image](https://user-images.githubusercontent.com/61395772/92382582-66e8fc00-f13f-11ea-94ff-d215b4fe080e.png)

![image](https://user-images.githubusercontent.com/61395772/92382617-749e8180-f13f-11ea-9785-f516488b4703.png)

![image](https://user-images.githubusercontent.com/61395772/92382398-1b365280-f13f-11ea-871b-0817d9e95359.png)

可能相关进程：Sangfor的EasyConnect，但测试时没有使用

**Comment by U-v-U** [comment]
@everfate 参考有个 Issue 的拨号连接代理

**Comment by DuckSoft** [comment]
已知问题。Windows 为拨号网络/VPN 网络的系统代理设定是单独的。
~~开发者没有 Windows，不熟 WIN32API，暂时可能需要你手动设置一下~~

**Comment by everfate** [comment]
> @everfate 参考有个 Issue 的拨号连接代理
