### ISSUE TITLE
trojan-go内核无法被找到，请检查出站设置（已解决）

### ISSUE THREAD

**Issue by everfate** [Qv2ray/Qv2ray#939]
#727  简单描述这个 Bug:

启动trojan-go代理提示找不到内核，然后提示内核启动失败，请检查出站设置

## 如何触发这个 Bug：

1. 根据问题#873， 设置了set-dial-up-proxy.ps1，和system proxy
2. 开启trojan-go节点提示失败

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
没有尝试

### 相关截图或日志
![image](https://user-images.githubusercontent.com/61395772/92386627-b979e680-f146-11ea-9cb6-8111ef77ae17.png)
![image](https://user-images.githubusercontent.com/61395772/92386644-c0085e00-f146-11ea-9294-b4db74445f5c.png)
![image](https://user-images.githubusercontent.com/61395772/92386661-c696d580-f146-11ea-8359-220fbe7c9013.png)

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：
无

```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.windows-latest
```

### 操作系统

- Windows 10 家庭版

### 安装来源

- Github Release

### 已安装的插件、版本及安装来源
trojan
trojan-go
command plugin
都来自 github release

## 附加信息

可能是因为根据问题#873， 设置了set-dial-up-proxy.ps1，和system proxy的原因？

**Comment by EpLiar** [comment]
Trojan-Go 插件需要下载 Trojan-Go 客户端

**Comment by MarksonHon** [comment]
@everfate 先看一下插件的使用方法，Trojan-Go 插件是要使用 Trojan-Go 的内核才行的。

**Comment by everfate** [comment]
> @everfate 先看一下插件的使用方法，Trojan-Go 插件是要使用 Trojan-Go 的内核才行的。

原来如此，使用文档里面没有看到trojan-go的用法

**Comment by DuckSoft** [comment]
呃，欢迎一起完善文档（跑）

**Comment by wbshawn** [comment]
请问是怎么解决的啊? 我找了文档没有找到具体的方法, 也不知道怎么下载Trojan-Go 的内核, 谢谢!

**Comment by D414Dea4** [comment]
> @everfate 先看一下插件的使用方法，Trojan-Go 插件是要使用 Trojan-Go 的内核才行的。
请问trojan-Go的内核下载完怎么使用呢？

**Comment by DuckSoft** [comment]
> > @everfate 先看一下插件的使用方法，Trojan-Go 插件是要使用 Trojan-Go 的内核才行的。
> > 请问trojan-Go的内核下载完怎么使用呢？

下载前，至少先看看主页的教程可以吗？
https://github.com/qv2ray/qvplugin-trojan-go
