### ISSUE TITLE
请问作者能否添加 macos 10.12.6 的兼容版本？

### ISSUE THREAD

**Issue by WROIATE** [Qv2ray/Qv2ray#940]
请问作者能否添加 macos 10.12.6 的兼容版本？

**Comment by DuckSoft** [comment]
你好，开发组没有 macOS 机器，也没有 macOS 10.12.6 这么老的镜像。
建议自行编译。

请参考：https://qv2ray.net/hacking/manuallybuild.html

**Comment by WROIATE** [comment]
好的了解了，谢谢
