### ISSUE TITLE
功能请求：用背景色而不是小圆点表示当前连接的服务器

### ISSUE THREAD

**Issue by xiebruce** [Qv2ray/Qv2ray#941]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
有关，不太容易从我的服务器列表中一眼看出目前正在连接的是哪个，因为目前的标示方式是用一个很小的小黑点

**简单描述你预期的解决方案？**
使用一个背景色来标示，比如目前用鼠标单击某一个服务器项，就会有蓝色的背景来表示当前选中的是哪一项，所以我期望能用另一个背景色(比如绿色一般表示运行中)来表示当前正在连接的服务器项
![image](https://user-images.githubusercontent.com/13575500/92458449-fb169a00-f1f7-11ea-809c-f49466ee606e.png)

**你有想到其他比较容易实现的解决方案吗？**
用大圆点●，箭头符号➤ 或五角星 ★ 代替小圆点，会更明显一点，同时也可以把**服务器名称显示为粗体**，这样更容易一眼看出来
![image](https://user-images.githubusercontent.com/13575500/92460008-ff43b700-f1f9-11ea-98fb-9f7df3644649.png)

当然如果用深绿色大圆点(浅绿色会很刺眼)，会更清楚一点，比如类似`systemctl status`查看程序状态显示的那个绿色
![image](https://user-images.githubusercontent.com/13575500/92460631-c3f5b800-f1fa-11ea-915e-52d3c4e1fedf.png)

还有就是可以用`flatwhite`选中时的这种样式，当然颜色可以用深绿色来表示当前正在连接的服务器
![image](https://user-images.githubusercontent.com/13575500/92461725-2d29fb00-f1fc-11ea-93fa-000fc4df6793.png)

**补充内容**
如果使用背景色来标示当前连接项，会有当前正在连接的项与当前选中项为同一个时，到底要显示哪个颜色的问题，我认为用`flatwhite`那种只在左侧显示一小块颜色而不是改变整个背景色的方式，可以避免这个问题。
![image](https://user-images.githubusercontent.com/13575500/92461725-2d29fb00-f1fc-11ea-93fa-000fc4df6793.png)

**Comment by U-v-U** [comment]
After commit https://github.com/Qv2ray/Qv2ray/commit/3febb7309b0b5f2d0c94ffded9d62a499a643363 the indicator will be `●` instead of `•`

**Comment by xiebruce** [comment]
哈哈，改的好快，这确实是最快的方式了，谢谢！

**Comment by DuckSoft** [comment]
Good Job!
