### ISSUE TITLE
功能请求：配置详情建议添加备注名

### ISSUE THREAD

**Issue by xiebruce** [Qv2ray/Qv2ray#942]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
选中某个服务器时，右侧会显示该服务器的配置详情，我认为缺少了一项备注名，每次都要看看左边选中的那个项里看看备注名
![image](https://user-images.githubusercontent.com/13575500/92463725-c65a1100-f1fe-11ea-94f7-9fcd0f03a528.png)

**简单描述你预期的解决方案？**
添加一个备注名(Remark)就行（能显示所在组，应该也很容易显示备注名吧？）
![image](https://user-images.githubusercontent.com/13575500/92463473-711dff80-f1fe-11ea-9fcf-f21907d8fbd9.png)

**你有想到其他比较容易实现的解决方案吗？**
暂无

**补充内容**
暂无

**Comment by DuckSoft** [comment]
短期解决办法：
![图片](https://user-images.githubusercontent.com/7822648/92498172-e30d3d80-f22c-11ea-9b31-f027a2dbc62a.png)

长期解决办法：
加

**Comment by xiebruce** [comment]
@DuckSoft 好的，原来还可以点这个哈哈
