### ISSUE TITLE
Flatpak version is outdated

### ISSUE THREAD

**Issue by eightfiftytwo** [Qv2ray/Qv2ray#943]
The [flatpak version](https://flathub.org/apps/details/com.github.Qv2ray) is outdated while the snap version is up to date. Please kindly bump the version on flathub. Thank you.

**Comment by U-v-U** [comment]
Do we still maintain flatpak package? @ymshenyu

**Comment by eightfiftytwo** [comment]
The [last commit](https://github.com/flathub/com.github.Qv2ray/commits/master) was in Jun 25.

**Comment by DuckSoft** [comment]
Uh... The maintainer of Flatpak had been busy with his studies.
If you are interested to maintain, it would be awesome.

**Comment by eightfiftytwo** [comment]
I'm afraid I don't have the skills to be a maintainer. Thank you for the quick reply, I'll just carry on using the rpm.
