### ISSUE TITLE
win10 设置全局 utf-8 后，qv2ray 安装界面乱码

### ISSUE THREAD

**Issue by lt-123** [Qv2ray/Qv2ray#947]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

win10 设置全局 utf-8 后，qv2ray 安装界面乱码。 安装完成之后是正常的

## 如何触发这个 Bug：

1.  [启用全局utf-8](https://www.cnblogs.com/walker-world/p/9548852.html)
2.  打开 qv2ray 安装程序

### 相关截图或日志

<details>

![image](https://user-images.githubusercontent.com/12232053/92610437-4610da00-f2ea-11ea-9933-c23f831faab5.png)

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本:  v2.6.3
```

### 操作系统

- Windows

### 安装来源

- Github Release / Scoop / Chocolatey

## 附加信息

win10打开全局utf8后， 有不少软件都会出现这个情况。

**Comment by U-v-U** [comment]
（感觉更像是 NSIS 安装器那边的问题）
cc @ymshenyu

**Comment by DuckSoft** [comment]
上游 NSIS Installer 的特性。要么 Bugdows 10 修复，要么 NSIS 修复。
Qv2ray 这里无法干预。
