### ISSUE TITLE
使用疑问：无法启动V2，提示failed to create server

### ISSUE THREAD

**Issue by cqiyu** [Qv2ray/Qv2ray#948]
![image](https://user-images.githubusercontent.com/24467621/92856418-ff27ff00-f425-11ea-83e5-90c561bb1be3.png)

**Comment by DuckSoft** [comment]
检查首选项——DNS设置——静态解析域名，删除空行。

**Comment by cqiyu** [comment]
已解决，非常感谢！！！

**Comment by cqiyu** [comment]
> 检查首选项——DNS设置——静态解析域名，删除空行。
已解决，非常感谢！！！
