### ISSUE TITLE
功能请求：负载均衡

### ISSUE THREAD

**Issue by delphinuz** [Qv2ray/Qv2ray#949]
v2ray支持负载均衡，而qv2ray目录下的Q2ray\config\connections是存放outbounds讯息，有无考虑多个负载均衡设定，让使用者勾选哪些outbounds來串接，而达到v2ray原本就有的简单负载均衡功能？

比如以下选择，那就会将vps1/vps3/vps4的outbounds串起来。

[v] vps1
[  ] vps2
[v] vps3
[v] vps4

**Comment by EpLiar** [comment]
新版本会有 balancer

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/92863341-62b62a80-f42e-11ea-9813-061dfcc1cce0.png)
静候新版（2.7.0）发布。

**Comment by yidasanqian** [comment]
什么时候发布2.7.0 @DuckSoft

**Comment by DuckSoft** [comment]
> 什么时候发布2.7.0 @DuckSoft

已经有了呀，另外别挖坟。
