### ISSUE TITLE
GUI 显示异常

### ISSUE THREAD

**Issue by woshichuanqilz** [Qv2ray/Qv2ray#950]
- [x] **I'm sure I've tried to reproduce the problem several times and will provide the system environment, each software and its version that is involved in the problem.**

## Briefly describe this bug：
直接从arch的源安装的 打开之后界面就是这样

![2020-09-12_10-54](https://user-images.githubusercontent.com/11295355/92985578-82a92500-f4e6-11ea-8922-f30085c839bc.png)

## How to trigger this bug：
1. install from yay command cn source
2. open the software.  

### Related screenshots or logs
How to check the log file？ I will post it later. 

## System Information

lizhe@ori
 ██████████████████  ████████     OS: Manjaro 20.1 Mikah
 ██████████████████  ████████     Kernel: x86_64 Linux 5.7.19-2-MANJARO
 ██████████████████  ████████     Uptime: 29m
 ████████                          ████████     Packages: 1373
 ████████  ████████  ████████     Shell: fish 3.1.2
 ████████  ████████  ████████     Resolution: 2944x1080
 ████████  ████████  ████████     WM: i3
 ████████  ████████  ████████     GTK Theme: Breath [GTK2/3]
 ████████  ████████  ████████     Icon Theme: breeze
 ████████  ████████  ████████     Font: Noto Sans,  10
 ████████  ████████  ████████     Disk: 29G / 237G (13%)
 ████████  ████████  ████████     CPU: Intel Core i5-9400F @ 6x 4.1GHz [61.0°C]
 ████████  ████████  ████████     GPU: GeForce GTX 660
                                                                       RAM: 2703MiB / 15949MiB

### Open Preferences -> About, and enter the following info

```
Version: 
![2020-09-12_10-59](https://user-images.githubusercontent.com/11295355/92985625-0f53e300-f4e7-11ea-8426-f0fb39cc6fc5.png)

Build info: 
Extra build info: 
```

### Operating systems

- [x] Linux
- [ ] macOS
- [ ] Windows
 
### Installation source
 
- [x] ArchLinuxCN - Stable
- [ ] ArchLinuxCN - Dev-git
- [ ] ArchLinux AUR - Stable
- [ ] ArchLinux AUR - Development
- [ ] Fedora - Stable
- [ ] Fedora - Preview
- [ ] openSUSE - Stable
- [ ] openSUSE - Preview
- [ ] Flathub
- [ ] Snap
- [ ] Homebrew Cask
- [ ] Scoop / Chocolatey / Github Release
- [ ] Compile manually

**Comment by DuckSoft** [comment]
这是你屏幕的缩放比例为负向导致的。
参考 https://github.com/Qv2ray/Qv2ray/issues/200 这里检查你的相关 QT 环境变量。

这个问题与 Qv2ray 本身可能无关。你可以试试打开 qBitTorrent，查看是否也有类似的情况。
