### ISSUE TITLE
使用疑问：V2Ray资源文件不可用

### ISSUE THREAD

**Issue by Acetylene475** [Qv2ray/Qv2ray#954]
当我尝试使用Qv2ray连接代理时, 程序提示"V2Ray资源文件不可用".
检查发现 /usr/lib/v2ray/ 目录不存在.
备注: v2ray版本为4.28.0, 系统版本为 archlinux 5.4.64-1-lts

**Comment by U-v-U** [comment]
@Acetylene475 https://t.me/qv2ray_outpost/261

**Comment by MarksonHon** [comment]
@Acetylene475 Arch Linux 的 v2ray 包改动了路径，二进制在 /usr/bin/v2ray，资源文件在 /usr/share/v2ray/。
