### ISSUE TITLE
One Simple Solution for "Qv2ray Poping Up Error Message Window When Starting"

### ISSUE THREAD

**Issue by LucasWang474** [Qv2ray/Qv2ray#957]
This bug is kinda caused by v2ray and you can deal with it by `killall v2ray` before starting it.
So you can creata script or simply write a shell command to run v2ray.
For me, using arch + i3wm, I created a script `init.sh` under `~/.config/qv2ray/` and write
```bash
#!/bin/sh

killall v2ray &

# optional
sleep 2

exec qv2ray
```
and then
```bash
chmod +x ~/.config/qv2ray/init.sh
```
and finally add `exec ~/.config/qv2ray/init.sh` to my i3 config file. (Well, you can also add it to your `.xinitrc` or `.xprofile`.)

Hopefully it works.

**Comment by LucasWang474** [comment]
BTW, I found that qv2ray-dev version is way more stable than the stable one. WTF is that!

**Comment by U-v-U** [comment]
Thanks for telling us your solution!
Since Qv2ray updates frequently, it's possible that bug fixes being pushed to `dev` branch but have not been released.

**Comment by ayalhw** [comment]
Maybe https://github.com/Qv2ray/Qv2ray/issues/578 is a better solution,
but it's still WIP...
