### ISSUE TITLE
linux下qv2ray的日志提示连接成功, 但浏览器和终端却连接失败

### ISSUE THREAD

**Issue by ding-e** [Qv2ray/Qv2ray#958]
qv2ray 日志:
![2020-09-13_21-45](https://user-images.githubusercontent.com/10878673/93020093-d7938b00-f60d-11ea-80f8-e69945ef99cb.png)

qv2ray 设置: 
![2020-09-13_21-45_1](https://user-images.githubusercontent.com/10878673/93020102-ea0dc480-f60d-11ea-818d-c405cb4c375a.png)

chrome代理设置:
![2020-09-13_21-45_2](https://user-images.githubusercontent.com/10878673/93020106-f2fe9600-f60d-11ea-91d4-9bd064e46ef3.png)

![2020-09-13_21-46](https://user-images.githubusercontent.com/10878673/93020114-027ddf00-f60e-11ea-8c0d-34343ebcdfbc.png)

请问这是什么问题?

另外, 同样代理服务器, 在macos下能代理

**Comment by MarksonHon** [comment]
@ding-e 1、去<https://time.is>检查一下时间。
2、确定 AlterID 不为 0，如果为0你需要降级内核到4.27系列版本。

**Comment by ding-e** [comment]
> @ ding-e 1，去https://time.is检查一下时间
> 。2，确定AlterID不为0，如果为0你需要降级内核到4.27系列版本。

感谢! 确实是内核版本问题
