### ISSUE TITLE
功能请求：托盘图标改进

### ISSUE THREAD

**Issue by Corezcy** [Qv2ray/Qv2ray#960]
**托盘栏里，开启的圆形蓝色、未开启的圆形绿色，有时候很难区别，尤其是晚上**

问题如题，建议扩大开启后的圆形图标面积或者换成更有对比度的颜色

**Comment by xiebruce** [comment]
我倒是觉得在Mac正常模式(即非黑夜模式)下整个图标都模糊，颜色方面确实要区分一下
![image](https://user-images.githubusercontent.com/13575500/93032815-1d7c3d80-f666-11ea-9580-e22bbe24a320.png)

**Comment by U-v-U** [comment]
首选项第二个 @xiebruce

**Comment by EpLiar** [comment]
> 我倒是觉得在Mac正常模式(即非黑夜模式)下整个图标都模糊，颜色方面确实要区分一下
> ![image](https://user-images.githubusercontent.com/13575500/93032815-1d7c3d80-f666-11ea-9580-e22bbe24a320.png)

![image](https://user-images.githubusercontent.com/23559565/93032940-b0b57300-f666-11ea-8a06-fbaad85bf282.png)

请擅用「适应暗色托盘主题」

**Comment by xiebruce** [comment]
是这边吗？可是我觉得我现在用的Fusion主题最好看呃，毕竟改这个主题变的不仅仅是图标🤣
![image](https://user-images.githubusercontent.com/13575500/93032977-db9fc700-f666-11ea-9ec2-6119eba97882.png)

**Comment by EpLiar** [comment]
> 是这边吗？可是我觉得我现在用的Fusion主题最好看呃，毕竟改这个主题变的不仅仅是图标🤣
> ![image](https://user-images.githubusercontent.com/13575500/93032977-db9fc700-f666-11ea-9ec2-6119eba97882.png)

![image](https://user-images.githubusercontent.com/23559565/93033044-16096400-f667-11ea-9481-c5ae4f2b1d05.png)

**Comment by xiebruce** [comment]
@EpLiar @U-v-U 谢谢，还真可以
![image](https://user-images.githubusercontent.com/13575500/93033091-4c46e380-f667-11ea-8349-bb9e5e2e67a8.png)

不过，这文字描述貌似跟变化不一样呀，比如我现在明显不是暗色主题，但是却要勾选“适应暗色主题”才看的清楚，明显这个表述不合理。

我认为应该把现在的两个选项：
```
适应暗色主题
适应暗色托盘主题
```

换成只有一个选项，也就是
```
适应暗色主题
```

意思是如果你当前系统用的是暗色主题，那你就勾一下，图标就会自动变成浅色(因为只有浅色才能适应暗色主题，增加对比度)，而如果不勾，则默认认为你系统当前是用的亮色主题(也就是图标颜色要变的比较深一点，这样才能跟浅色主题有对比度，看的清楚)

**Comment by EpLiar** [comment]
> 不过，这文字描述貌似跟变化不一样呀，比如我现在明显不是暗色主题，但是却要勾选“适应暗色主题”才看的清楚，明显这个表述不合理。

> 
> 我认为应该把现在的两个选项：
> 
> ```
> 
> 适应暗色主题
> 
> 适应暗色托盘主题
> 
> ```
> 
> 换成只有一个选项，也就是
> 
> ```
> 
> 适应暗色主题
> 
> ```
> 
> 意思是如果你当前系统用的是暗色主题，那你就勾一下，图标就会自动变成浅色(因为只有浅色才能适应系统的暗色主题，增加对比度)，而如果不勾，则默认认为你系统当前是用的亮色主题(也就是图标颜色要变的比较深一点，这样才能跟系统的浅色主题有对比度，才能看的清楚)

那如果我用的暗色主题而 Qv2ray 主程序是 Fusion，主界面上的图标就会糊掉。

即使外部是深色，也不代表应用程序会是深色。这两个选项控制的部分一个是托盘，一个是主程序界面

请充分考虑实际情况

**Comment by xiebruce** [comment]
@EpLiar 你说的这个确实是个问题，但是我还是觉得现在的`适应暗色主题`和`适应暗色托盘主题`表述的很不明白，比如“适应暗色主题”中的“暗色主题”指的是谁的主题？是系统的还是qv2ray自身的？反正我的第一印象就觉得这是指电脑系统的暗色主题，因为有“适应”两个字，一般都是软件适应系统嘛(至少我个人是这么理解的)，如果是像我说的这样，那“适应暗色主题”几个字明显不对(因为我勾了之后它适应的是我系统的“亮色主题”)，而如果这个“暗色主题”是指Qv2ray本身的主题，那我觉得应该不用“适应”两个字吧？

我认为出现让人混淆、误解的根本原因，是用了“适应”和“主题”两个字，有人认为主题是系统主题，有人认为主题是Qv2ray主题，解决方法就是不要用“适应”和“主题”两个字，比如改成这样
```
使用深色托盘图标
使用浅色托盘图标
```
这样使用浅色系统主题的人如果默认图标颜色浅，他肯定会觉得颜色太浅看不清，就会去选使用深色图标的，反之，如果使用暗色系统的人默认图标也是深色就会看不清，他就会去选浅色图标，以便跟暗色的系统主题形成对比，容易看清。

另外就是我认为这个选项应该做成单选的下拉菜单吧？毕竟理论上同一时间只能选一个，而不能勾选两个，而现在却能勾选两个。

**Comment by EpLiar** [comment]
> 反正我的第一印象就觉得这是指电脑系统的暗色主题

那如果有人第一反应是程序的主题呢？

> ```
> 使用深色托盘图标
> 使用浅色托盘图标
> ```

这个建议不错

> 另外就是我认为这个选项应该做成单选的下拉菜单吧？毕竟理论上同一时间只能选一个，而不能勾选两个，而现在却能勾选两个。

那为什么不能选两个？首先，程序和系统能不能使用不一样的颜色？可以。既然可以，那为什么不能选两个？

主题和系统都是同一个颜色，两个都选；如果不一样，单选或看着心情来就好了。

**Comment by zzndb** [comment]
它们做的是两件事情。
第一个是适应 Qv2ray 自身主题，它做的事情肉眼可见的区别貌似就是改变了程序界面图标深浅，以 `适应` 各种亮暗主题。
第二个改成 `使用` 感觉确实更好一点。

**Comment by xiebruce** [comment]
我已经彻底乱了🤣 目前我是两个都不勾，托盘图标就是深色(我Mac主题是亮色，所以这个图标颜色就是我想要的)，而且log颜色也刚好是我想要的。

如果我勾了“适应暗色主题”，虽然图标颜色还是深色，但是log颜色已经变成这样，完全没法看了
![image](https://user-images.githubusercontent.com/13575500/93038993-faa75480-f678-11ea-952b-26601b615ae5.png)

**Comment by Corezcy** [comment]
我去，这么多评论了， 看来这个问题大家都关注了

**Comment by ayalhw** [comment]
弱弱地说一句：linux上托盘里的图标不是跟随系统主题吗

**Comment by DuckSoft** [comment]
各位的见解都很独特，值得注意。
奈何技术不足、精力有限，若哪位大神可以发个 PR，感激不尽：
https://github.com/Qv2ray/Qv2ray/tree/master/assets/icons

**Comment by Corezcy** [comment]
可以改一下图标的显示逻辑，在没链接的时候，右下没有店显示：
assets/icons/ui_light/design/tray.svg
在链接的时候，显示绿点，比现在蓝绿容易区分
@DuckSoft
