### ISSUE TITLE
功能请求：新增树莓派arm64版本

### ISSUE THREAD

**Issue by mozhewen** [Qv2ray/Qv2ray#961]
如题。appimage版本无法在树莓派上运行，能否提供树莓派版本？

**Comment by MarksonHon** [comment]
@mozhewen 建议你从 snap 安装，这样就有 arm64 版本了。

**Comment by ayalhw** [comment]
考虑到arm性能，我个人建议自己编译以取得最大性能

**Comment by MarksonHon** [comment]
@mozhewen https://snapcraft.io/qv2ray

**Comment by DuckSoft** [comment]
建议直接从 snap 装，不折腾。
如果今晚还没装上，我给你开虚拟机编译一个。
不过因为架构不同，可能得编个五六个小时。
