### ISSUE TITLE
UX：改进“暗色主题”/“暗色托盘图标”的表述

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#962]
@EpLiar 你说的这个确实是个问题，但是我还是觉得现在的`适应暗色主题`和`适应暗色托盘主题`表述的很不明白，比如“适应暗色主题”中的“暗色主题”指的是谁的主题？是系统的还是qv2ray自身的？反正我的第一印象就觉得这是指电脑系统的暗色主题，因为有“适应”两个字，一般都是软件适应系统嘛(至少我个人是这么理解的)，如果是像我说的这样，那“适应暗色主题”几个字明显不对(因为我勾了之后它适应的是我系统的“亮色主题”)，而如果这个“暗色主题”是指Qv2ray本身的主题，那我觉得应该不用“适应”两个字吧？

我认为出现让人混淆、误解的根本原因，是用了“适应”和“主题”两个字，有人认为主题是系统主题，有人认为主题是Qv2ray主题，解决方法就是不要用“适应”和“主题”两个字，比如改成这样
```
使用深色托盘图标
使用浅色托盘图标
```
这样使用浅色系统主题的人如果默认图标颜色浅，他肯定会觉得颜色太浅看不清，就会去选使用深色图标的，反之，如果使用暗色系统的人默认图标也是深色就会看不清，他就会去选浅色图标，以便跟暗色的系统主题形成对比，容易看清。

另外就是我认为这个选项应该做成单选的下拉菜单吧？毕竟理论上同一时间只能选一个，而不能勾选两个，而现在却能勾选两个。

_Originally posted by @xiebruce in https://github.com/Qv2ray/Qv2ray/issues/960#issuecomment-691762610_

**Comment by ayalhw** [comment]
确实这个样子比较好
