### ISSUE TITLE
组编辑器中移动某个链接到其它组时无法点击组列表菜单

### ISSUE THREAD

**Issue by xiebruce** [Qv2ray/Qv2ray#963]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
在组编辑器中，右击任意一个组中的某个链接→鼠标光标移到`移动到`按钮上方，此时右侧会弹出一个菜单(组的列表)，Bug来了：我想用鼠标点击移动到`aaa`组(被移动选项原来不在aaa组)，无法点击，目前要按键盘方向键“下键”才能选中，然后按enter确定(即无法用鼠标点击)
![image](https://user-images.githubusercontent.com/13575500/93055394-70bdb280-f69d-11ea-85f3-896d23a1d173.png)

## 如何触发这个 Bug：

1. 点击主界面左下角的`分组`按钮，会弹出组编辑器窗口
2. 点击组编辑器窗口中的某个分组，会显示出这个分组里的所有链接
3. 右击第2步中的任意一个链接，并把鼠标光标移到`移动到`菜单上，此时右此会弹出一个菜单(即组列表)
4. 点击第3步组列表中的某个组(非链接当前所在组)，无法点击

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
没有

### 相关截图或日志
截图见“简单描述这个 Bug”

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：

此bug为UI问题，与日志无关！
```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-912fe1b040544214b2f56c52e6da9fdb43c11f26-ci.macos-latest
```

### 操作系统

- Linux
- macOS：Mojave Version 10.14.4 (18E226)
- Windows

### 安装来源
Qv2ray：Github Release，手动下载安装

### 已安装的插件、版本及安装来源
- QvTrojanPlugin.v2.0.0.macOS-x64.so
- QvTrojanGoPlugin.v1.0.1.macOS-x64.so

官网Github Release，手动下载，解压并放置到相应目录

## 附加信息

*请注意打码隐私相关信息。*

由于是UI的bug，貌似没有什么附加信息。

**Comment by EpLiar** [comment]
这是已知问题，开发组内部已经得知，目前没有解决办法，观望中

**Comment by xiebruce** [comment]
@EpLiar 好的，也借这个issue再说一个分组的问题，就是在组编辑器中，如果我把某个链接移动到另一个组时，如果被移动的那一项是正在连接的(即它前面有个小黑点)，移动之后，小黑点不见了，但它还是连接着，应该是处理UI的时候，忘了判断被移动的是不是当前正在连接的，如果是，则要加小黑点。

**Comment by U-v-U** [comment]
@xiebruce 这个属于 Feature, 在 Qv2ray 内部，CurrentConnection 是一个 ConnectionGroupPair 类型，因此当前连接是一个 「Connection」和「Group」的二元组（使用此种设计的原因是你可以使用 “链接到组” 功能让同一个链接配置在不同组内实现不同路由规则。

**Comment by xiebruce** [comment]
> @xiebruce 这个属于 Feature
> 在 Qv2ray 内部，表示当前连接项目的 `CurrentConnection` 是一个 `ConnectionGroupPair` 类型
> 
> * 即当前连接是一个 「Connection」和「Group」二元组
> 
> 使用此种设计的原因是你可以使用 “链接到组” 功能让同一个链接配置在不同组内实现不同路由规则。
> 
> 由于将一个连接移动到另一个组，会存在「潜在的」路由配置更改，因此不打算识别为原来的连接

我也发现了，分组路由可以覆盖全局路由，这样能实现同一个链接在不同组内实现不同路由规则，这个功能不错，不过我暂时还没用到。

但我不明白的是，就算路由规则变了，当前正在连哪个，移动到另外的组后，正在连接的不还是它吗？

不过有另一种情况，就是“正在连接”的项被“链接”到另一个组，这样如果要用小黑点表示当前谁正在连接，就要把标记两个甚至多个小黑点了(也不知道这样是否合适)。

**Comment by DuckSoft** [comment]
测试过了……这个估计是 Qt 在 macOS 的一个 bug……
得想个办法规避一下

**Comment by xiebruce** [comment]
@DuckSoft 好的，辛苦辛苦！
