### ISSUE TITLE
mac 10.13.6 打开 Qvray-v2.6.3 无响应 

### ISSUE THREAD

**Issue by 763139102** [Qv2ray/Qv2ray#964]
一开始安装的软件正常打开，增加vmess,双击连接 ，软件就无响应了 ，强制退出 ，再打开，直接无响应 ，重启电脑无效 ，
**备注下，我是黑苹果 10.13.6**

**Comment by DuckSoft** [comment]
macOS 10.13需用legacy包。

**Comment by 763139102** [comment]
> macOS 10.13需用legacy包。

需用legacy包。  这个是什么

**Comment by EpLiar** [comment]
> 
> 需用legacy包。  这个是什么 

请查看 Release 的内容

**Comment by 763139102** [comment]
> > 需用legacy包。  这个是什么
> 
> 请查看 Release 的内容

![image](https://user-images.githubusercontent.com/25519902/93160197-6bff0a00-f742-11ea-9072-f13152b6380e.png)
可以搜索到，点进去就没有了

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/93182779-aed5d780-f76c-11ea-90cd-553b4c7a6f75.png)

**Comment by DuckSoft** [comment]
的确是因为 Qv2ray v2.6.3 没有放出 Legacy 包导致的。
已加入重建计划。
