### ISSUE TITLE
建议做成一个平台

### ISSUE THREAD

**Issue by shermans** [Qv2ray/Qv2ray#965]
这么多年用了很多很多工具
普及率最高,入手难度最低,适应性最强的, 我认为是fqrouter.
当时特别坚挺. 小白安装就能用. 高手可以玩出更多花样. 网友还在新闻里面发现了它.

Qv2ray我用了半小时, 
感觉最有机会成为一个平台的产品, 作者的思路,产品的内容,都适合.
这些年goagent ss ssr v2ray一代一代换, 用户要试着去学习各种终端. 真的没有fqrouter好用.

所以说一下我对Qv2ray的期许. 
Qv2ray的软件设置, 高级路由设置等等. 我还没明白是什么,但是基本能判断做的比较深入完善.
"有了它们的加持，你可以实现对流量的精准控制，如按需代理、国内外分流等，甚至还可以套娃🤣~"
另外还有插件思路, 等于将来可以兼容更多内容,比如把goagent或者xxnet加进来. 结合高级路由这种"套娃"的骚操作.
只要插件里面有一个插件能出去. 那其他插件的就能套出很优秀的效果来. 

**### 希望Qv2ray能再进化为一个平台. 作者的思路应该也是类似的方向.
1,用户配置界面优化一下,分类一下, 类似chrome的设置,小白打开是一般的设置,需要点高级设置,才展现各种设置.那就很简洁了.
对小白友好,同时功能又高级, 那用户面就很广了. 而且界面不需要一直去开发.只要有插件用,它就不会挂.
2,去core, 不依赖v2ray核心.v2ray也变成插件. 这样只要有一个插件能用,它就能用.万一v2ray将来不好使了,qv2ray也还可以继续存活.
3,用户多了,插件就好办,自然会有更多开发者加入进来. 反正插件模板和接口都公开了.  将来SSR V2RAY都不能用了,有新的什么东西出来,又可以以插件的形式加进来. 而且有"套娃""二级代理"的操作,其他挂掉的协议也就还能继续发挥作用.
这样它就有机会跨越代码开源,实现开发者开源, 只要这世上还有一位开发者维护它,给它做插件,它就能继续存在.
作者本人可以 事了拂衣隐身去,不留功与名 **

**Comment by FANminiworld** [comment]
@shermans 对小白友好：不会的，永远不会的

**Comment by kidonng** [comment]
- 界面改进一直在做。
- 插件系统可以看做平台。
- Qv2ray 依赖 V2Ray core 的路由功能，可预见的时间内不会移除依赖。
- 有更多想法欢迎加入群聊。

**Comment by DuckSoft** [comment]
首先正如楼上的楼上所说，话糙理不糙，对小白友好很可能无法实现。对于一些小白用户来说，他们可能觉得 Qv2ray 非常难以配置、难以使用，并且很多概念与其他的代理客户端完全不同，难以学习和理解。这是非常正常的事情，也是我们目前设置的一个门槛。Qv2ray 是其开发团队和用户社区自行维护的开源免费项目。如果连放置几个文件都做不对，而且不会看文档、不加群、甚至不发 Issue 问，我们不能指望这样的用户为我们贡献什么。就当前来说，我们认为一定的使用门槛是必要的。

Qv2ray 的信条是：Qv2ray 希望成为用户中心型项目，而非小白友好型项目。用户中心型项目中的大部分用户不仅仅是生态的使用者，也是参与者和贡献者。Qv2ray 不希望引入经济赞助、机场合作以及众筹捐款写功能等商业机制，这样必然会引起社群质量的下降。

Qv2ray 的设计理念是：在保持基本功能简明有效的基础上，尽可能地将 V2Ray 核心的各种理念以透明的方式暴露给用户，让用户可以对相应的概念进行复杂的定制和个人化。

我们希望每一个用户都能为 Qv2ray 做出其力所能及的贡献。即使你不会写代码，帮助 Qv2ray 翻译成其他语言、为 Qv2ray 提供优质的 Bug 报告、给 Qv2ray 提一些合用的点子，甚至在用户群组里水水群、指点一下大家，都会让 Qv2ray 变得更好。

另外关于平台方面：在关闭[内核集成](https://qv2ray.net/plugins/v2ray-integration.html)的前提下，可以脱离 V2Ray 核心直接运行插件。这一方面已经很好地实现了。

最后，感谢你的用心反馈。

**Comment by shermans** [comment]
感谢大家的答复.
我说太多了,反而弱化了我的核心想法.
我的核心想法是.
把它做成这样子: 
将来SSR VEMSS等等都挂了, 甚至连Qv2ray当前的开发团队也因不可抗力解散了. (goa ss ssr fqrouter 等之前遇到的那些事情)
但只要世界上还存在  一个 开发者,能  轻易  的就把新的协议做成Qv2ry的新插件,它就能继续发光发热很长时间.
