### ISSUE TITLE
Question: <Your Awesome Question>

### ISSUE THREAD

**Issue by denstiny** [Qv2ray/Qv2ray#968]
### Describe You Purpose
one awesome wm It doesn't work, but gnOME works fine. What core do I lack  
![](https://i.bmp.ovh/imgs/2020/09/3c25c7ce25e3d297.png)

**Comment by DuckSoft** [comment]
No. You're not lacking anything. It's the system proxy settings. 
You know Awesome is a WM and GNOME is a DE, and they are different.
The latter offers both your applications and Qv2ray the system proxy interface, from which programs such as browsers can read settings. When programs like browsers cannot tell which DE are you running on, they tend not to use system proxy settings.

To put it together: You need configure the proxy host/port in the applications, if you choose not to use any DE like GNOME/KDE.
