### ISSUE TITLE
功能请求：HiDPI 图标支持

### ISSUE THREAD

**Issue by sheljoy** [Qv2ray/Qv2ray#969]
客服端UI对HiDPI好像支持不是很好。MacOS,Ubuntu 18.04 上对高分辨率的屏幕，一些icons显示马赛克很明显。

**Comment by ayalhw** [comment]
浅见 沙织:
这个图标hidpi应该是平台的问题吧

要么是平台不支持SVG，要么是SVG渲染有问题

_Origin posted by Asami Saori in telegram group：
https://t.me/qv2ray/349484_

**Comment by DuckSoft** [comment]
2.7.0 已经引入 SVG。期待会有所改善。

**Comment by sheljoy** [comment]
使用snap 安装，图标显示改善很多，但是整个客户端缩到最小，还是很大。

**Comment by DuckSoft** [comment]
缩放大小问题请调节 QT 相关的变量。你可参考此处：https://github.com/Qv2ray/Qv2ray/issues/200
Flathub 多半是不维护了。
