### ISSUE TITLE
功能请求：增加 IOS 支持，绕过 App Store

### ISSUE THREAD

**Issue by 517030910405** [Qv2ray/Qv2ray#972]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
请尽可能清晰简洁地描述问题。例：每次吃饭都要出门穿衣收拾打扮，太烦了……
IOS 没有 qv2ray 客户端，感觉用美区苹果账户太麻烦了

**简单描述你预期的解决方案？**
请尽可能清晰简洁描述问题。例：我想打电话给餐馆让他们直接给我送过来……
跨平台增加 IOS 的支持

**你有想到其他比较容易实现的解决方案吗？**
请简单清晰描述。例：或者直接给餐馆签个协议也行……
编译后，用类似于 i4 助手的工具导入软件，绕过 App Store

**补充内容**
请在此附加任何你认为对你的描述有所帮助的内容。
谢谢！

**Comment by EpLiar** [comment]
开发组太菜了，目前没有人会 iOS，欢迎提交 PR

**Comment by FANminiworld** [comment]
@517030910405 两种绕过 App Store 的方法：（1）TestFlight 测试版 ； （2）企业级应用程序
