### ISSUE TITLE
连接vmess，直接报错io:read/write on closed pipe

### ISSUE THREAD

**Issue by danuonuo** [Qv2ray/Qv2ray#973]
我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。
确定

## 简单描述这个 Bug:
无法连接所有vmess节点，核心检查通过。

## 如何触发这个 Bug：

1. 连接，直接报错io:read/write on closed pipe。
2. 系统时间已经多次确认无误差。
3. 该服务器使用ios/android客户端均可用

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 
没有。

```
请从此行下面的行开始粘贴 Qv2ray 日志：

V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
A unified platform for anti-censorship.
2020/09/19 00:00:18 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /home/danuonuo/.config/qv2ray/generated/config.gen.json
2020/09/19 00:00:18 [Warning] v2ray.com/core: V2Ray 4.28.2 started
2020/09/19 00:00:18 127.0.0.1:40236 accepted tcp:127.0.0.1:0 [_QV2RAY_API_]
2020/09/19 00:00:22 127.0.0.1:42634 accepted http://google.com/ [hvigknrtlchvcvm]
2020/09/19 00:00:22 [Warning] [777364441] v2ray.com/core/proxy/http: failed to read response from google.com > io: read/write on closed pipe
2020/09/19 00:00:23 127.0.0.1:42636 accepted http://google.com/ [hvigknrtlchvcvm]
2020/09/19 00:00:24 [Warning] [1920306820] v2ray.com/core/proxy/http: failed to read response from google.com > io: read/write on closed pipe



## 系统信息
Linux danuonuo 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux



### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5840
编译信息：Qv2ray from manual build
额外编译信息：Qv2ray 2.6.3:5840
```

操作系统

Linux-ubuntu20.04LTS


安装来源

- Github Release


已安装的插件、版本及安装来源
无


附加信息
无

**Comment by DuckSoft** [comment]
大概率是 VMess AEAD 的破坏性变更导致的。可尝试降级到 V2Ray Core 4.27。

**Comment by danuonuo** [comment]
好的，我试试，谢谢


------------------ 原始邮件 ------------------
发件人: DuckSoft <notifications@github.com&gt;
发送时间: 2020年9月19日 07:56
收件人: Qv2ray/Qv2ray <Qv2ray@noreply.github.com&gt;
抄送: danuonuo <3380482166@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Qv2ray/Qv2ray] 连接vmess，直接报错io:read/write on closed pipe (#973)





 
大概率是 VMess AEAD 的破坏性变更导致的。可尝试降级到 V2Ray Core 4.27。

**Comment by SudoShutdownNow** [comment]
楼上正解，需要把core降级到4.27

**Comment by Opdoop** [comment]
@danuonuo 请问降级后解决了这个问题吗？

**Comment by Dompink** [comment]
降级到v2ray core4.27.5成功解决该问题，win10

V2Ray 路径配置检查通过。
V2Ray 当前版本是: 
V2Ray 4.27.5 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.7 windows/amd64)
