### ISSUE TITLE
Update AUR

### ISSUE THREAD

**Issue by glide-the** [Qv2ray/Qv2ray#974]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

打包参数-DQV2RAY_DEFAULT_VASSETS_PATH 修改为"/usr/share/v2ray" 
![image](https://user-images.githubusercontent.com/16206043/93686209-5ba2b280-fae7-11ea-90b6-2171e3c1dcf9.png)
与之前配置不符，配置未更新
![image](https://user-images.githubusercontent.com/16206043/93686243-90166e80-fae7-11ea-8b9e-db2d99ecf738.png)
这里是我手动更改的

## 如何触发这个 Bug：

1. clone 仓库master分支，放在此目录
![image](https://user-images.githubusercontent.com/16206043/93686299-e84d7080-fae7-11ea-8b31-0e314e68a80f.png)

2. 将aru的PKGBUILD之外的文件全部删掉
3. 确认master的submodule正确依赖，并修改PKGBUILD内容修改如下.
![image](https://user-images.githubusercontent.com/16206043/93686400-8ccfb280-fae8-11ea-8e6a-9abd7bd8fccf.png)

 
4. 执行makepkg -si 

### 相关截图或日志

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：


```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: manjaro 20
编译信息：
额外编译信息：
```

### 操作系统

- Linux
### 安装来源

- ArchLinux AUR - 稳定版
- ArchLinux AUR - 开发版

## 附加信息

*请注意打码隐私相关信息。*

**Comment by DuckSoft** [comment]
变更此前应用到了 archlinuxcn，但未应用到 AUR。
将在 2.7.0-alpha1 之前更新。

**Comment by U-v-U** [comment]
ping @DuckSoft You may update it now

**Comment by DuckSoft** [comment]
FIXED
