### ISSUE TITLE
New Feature: Plugin Translations

### ISSUE THREAD

**Issue by U-v-U** [Qv2ray/Qv2ray#975]
QTranslator supports load from multiple translation files.
- Method 1:
  After a plugin has been loaded, the translation should be able to load from `qrc:///PLUGIN_NAME/translations/LANG.qm`

- Method 2:
  Setup a meta translation repo, with string sources being added as submodules.

**Comment by DuckSoft** [comment]
Maybe we can bundle the translations into resources of the plugins.
