### ISSUE TITLE
请求出一个透明代理的教程

### ISSUE THREAD

**Issue by NicholasIrving** [Qv2ray/Qv2ray#976]
对于透明代理的使用有点疑问，请问能不能出一个关于透明代理的使用教程？比如说只代理局域网中某个设备之类的

**Comment by MarksonHon** [comment]
@NicholasIrving 建议加群讨论，并关闭这个 issue，因为你是在求助，而不是报告问题。
群链接：
<https://t.me/qv2ray>

或者阅读新白话文教程 <https://guide.v2fly.org/app/tproxy.html>
