### ISSUE TITLE
deepin 系统中每次启动Qv2ray总是弹出该图片

### ISSUE THREAD

**Issue by dingeral** [Qv2ray/Qv2ray#977]
![截图录屏_选择区域_20200921113128](https://user-images.githubusercontent.com/36292978/93731260-d8748000-fbfe-11ea-82db-40d4e430a46a.png)

能否关闭，或添加一个关闭按钮。

我在最新的 deepin 系统中目前未发现提示的问题。

希望能得到解答

**Comment by DuckSoft** [comment]
重复 issue：#672 #676 #863 #913 #915 #932 
这是个 Deepin 自己的 bug，如果你不使用系统代理功能，这个弹窗不会出现。
如果有疑问，请自行前往上游围观：linuxdeepin/go-lib#15。
这个 bug 由 Qv2ray 社区反馈，并由 Qv2ray 社区为其修复，详见 linuxdeepin/go-lib#16。
在问题修复被上游修复并确认已经正式发布之前，我们不会主动撤掉这个提示。

**Comment by MarksonHon** [comment]
@dingeral 打开终端，输入：
env | grep proxy

如果 HTTP 代理被自动替换成了 HTTPS 与 FTP 代理，那么就说明 Deepin 这个问题还存在，这个提示对话框也就还会保留。
至于能不能提供关闭选项，这要看开发者的意思。

**Comment by dingeral** [comment]
```
$ env | grep proxy
ftp_proxy=ftp://127.0.0.1:1081
http_proxy=http://127.0.0.1:1081
https_proxy=https://127.0.0.1:1081
```

**Comment by DuckSoft** [comment]
You deserve that nag.

> ```
> $ env | grep proxy
> ftp_proxy=ftp://127.0.0.1:1081
> http_proxy=http://127.0.0.1:1081
> https_proxy=https://127.0.0.1:1081
> ```
