### ISSUE TITLE
使用疑问：Qv2ray不能使用手动模式?

### ISSUE THREAD

**Issue by ZimriGeek** [Qv2ray/Qv2ray#978]
### 你想做啥？
某个软件 选择使用代理的时候就手动填写Qv2ray的HTTP或SOCKS5端口 则直接就是代理模式,不指定的则直连
达到目的: 谷歌浏览器设置了代理端口 直接全局;火狐浏览器没有设置代理则直连.这类情景的手动模式

### 你目前试了啥？
由文档得知PAC 功能已被 Qv2ray 开发者弃用,但似乎没有提及手动模式
macOS端最频繁遇到的问题是 对某站点打开调试工具的时候 无论是直连或者代理Server永远显示是:127.0.0.1:1088
相当于所有流量链接都到 Qv2ray 走了一趟才根据 Qv2ray 的设置该代理的代理 该直连的直连 该问题直接通过 Qv2ray 的日志记录即可看出,无论是直连还是代理的流量链接都能被记录.

### 其他要补充的信息？
因为是在找不到手动模式,现在只能直接用core 通过终端直接操作配置文件、直接操作core... 来达到手动模式.
但Qv2ray的功能和UI是目前见过最棒的了.所以求助如何使用Qv2ray达到手动模式

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/93738671-f0f19400-fc18-11ea-8a85-11da71a4a85f.png)

**Comment by EpLiar** [comment]
这个是 Chrome 只能设置系统代理的原因，和 Qv2ray 没有关系。

如果你需要设置了代理不设置就直连，可以尝试在 Chrome 上安装 SwitchyOmega 插件，并配置白名单 / 黑名单。

**Comment by DuckSoft** [comment]
一共两个地方有“系统代理设置”。一个在首选项里，控制每次切换节点时 Qv2ray 的行为；一个在托盘菜单里，属于一次性的行为。
所谓的手动模式，大概就是 Qv2ray 不接管系统代理，由浏览器自行指向吧。所需要的协议和对应的端口都在上图中了，对号入座即可。
最后，文档是个好东西。
