### ISSUE TITLE
使用疑问：snap中的Qv2ray附带的插件版本问题

### ISSUE THREAD

**Issue by VirFunc** [Qv2ray/Qv2ray#980]
### 你想做啥？
开启启动Qv2ray

### 你目前试了啥？
在Ubuntu系统中将Q2ray添加至开机启动中

### 其他要补充的信息？
snap中的Qv2ray自带了SSR和Trojan两个插件，但是这两个插件的版本似乎有问题，当我启动Qv2ray的时候会提示“无法加载这两个插件，这个插件是基于更旧或更新的插件接口构建”。
我尝试过使用`Qv2ray --noPlugin`，Qv2ray可以正常启动。
由于snap自身的问题我没有办法删除`/snap/qv2ray/2820/usr/share/qv2ray/plugins/`目录下的文件，这导致Qv2ray每次开机启动都会自动加载这两个插件并且报错。

**Comment by DuckSoft** [comment]
这个的确是 snap 打包时候的问题。
有请我们的 snap 维护者 @ymshenyu。

**Comment by ymshenyu** [comment]
当前的edge channel的revision是2908，已经去除SSR插件以及trojan插件已经更新，请自己更新到最新的revision

**Comment by VirFunc** [comment]
@ymshenyu 了解，谢谢

**Comment by DuckSoft** [comment]
Okay fine. Closing.
