### ISSUE TITLE
如何实现负载均衡

### ISSUE THREAD

**Issue by lang999** [Qv2ray/Qv2ray#981]
**你的功能请求与使用中遇到的麻烦有关吗？若有，请描述？**
请尽可能清晰简洁地描述问题。例：每次吃饭都要出门穿衣收拾打扮，太烦了……

**简单描述你预期的解决方案？**
请尽可能清晰简洁描述问题。例：我想打电话给餐馆让他们直接给我送过来……

**你有想到其他比较容易实现的解决方案吗？**
请简单清晰描述。例：或者直接给餐馆签个协议也行……

**补充内容**
请在此附加任何你认为对你的描述有所帮助的内容。

**Comment by DuckSoft** [comment]
功能请求的注意事项：
1. 请务必确定你的 Issue 类型分类正确。请不要用功能请求的模板来咨询使用问题，或是报告软件缺陷。分类不正确的 Issue 可能会被无理由立即关闭。
2. 请务必按模板填写。未按模板填写的 Issue 可能会被无理由立刻关闭。
