### ISSUE TITLE
mac系统，使用时缺少核心文件？

### ISSUE THREAD

**Issue by shenzt68** [Qv2ray/Qv2ray#982]
### 你想做啥？
*简要描述你的最原始的目的。*
例：我在学校，校园网能解锁文献数据库，我想对这些地址直连。

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
例：看完文档，没有相关内容，就过来问一问。

### 其他要补充的信息？
*在此附加其他需要补充的信息。*
![image](https://user-images.githubusercontent.com/17406910/93878355-81f56780-fd0c-11ea-8f8d-48273425615b.png)

**Comment by MarksonHon** [comment]
@shenzt68 请看文档 qv2ray.net，本 issue 会被关闭，因为这不是一个程序本身的故障。

**Comment by EpLiar** [comment]
请在首选项设置核心文件路径

文档 qv2ray.net
