### ISSUE TITLE
2.6.3mac版打不开

### ISSUE THREAD

**Issue by lsh1215225** [Qv2ray/Qv2ray#983]
- [ ] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:

最新调mac版安装后打不开，在dock上一直跳，就是进不了界面，系统10.14.6

### 操作系统

- macOS

### 安装来源

- Github Release

**Comment by DuckSoft** [comment]
先 spctl master disable，之后重启就好了，原因不明，估计是 macOS 自带 bug。

**Comment by lsh1215225** [comment]
> 先 spctl master disable，之后重启就好了，原因不明，估计是 macOS 自带 bug。

已经是允许打开任何来源了

**Comment by DuckSoft** [comment]
这个问题已经在 alpha 版本修复。原因已经查明。是因为 Qv2ray 的一个上游依赖 SingleApplication 在试图锁定共享内存的时候，由于上次的主进程异常退出，导致内存锁的无限等待。

你有两个选择：1. 直接重启 macOS 即可继续使用当前版本；2. 更新到我们的最新版本，最新版本中已经修复了这个问题

**Comment by DuckSoft** [comment]
当前最新版本：https://github.com/Qv2ray/Qv2ray/releases/tag/v2.7.0-alpha1

**Comment by lsh1215225** [comment]
> 这个问题已经在 alpha 版本修复。原因已经查明。是因为 Qv2ray 的一个上游依赖 SingleApplication 在试图锁定共享内存的时候，由于上次的主进程异常退出，导致内存锁的无限等待。
> 
> 你有两个选择：1. 直接重启 macOS 即可继续使用当前版本；2. 更新到我们的最新版本，最新版本中已经修复了这个问题

好的，谢谢
