### ISSUE TITLE
DEB包是覆盖安装还是共存安装？

### ISSUE THREAD

**Issue by leoxxx** [Qv2ray/Qv2ray#984]
如题。
我是用LINUX MINT自带的DEB管理器安装的。
如果是覆盖，我要如何共存？
如果是共存，我要如何覆盖？

**Comment by ayalhw** [comment]
没搞懂，啥叫覆盖安装啥叫共存安装？

**Comment by leoxxx** [comment]
> 没搞懂，啥叫覆盖安装啥叫共存安装？

已装低版本，再安装高版本。覆盖就是安装后只有想版本。共存就是安装后有两个不同的版本。

**Comment by DuckSoft** [comment]
此问题与开发者无关。请自行参考包管理器/Linux操作系统对应文档。

**Comment by leoxxx** [comment]
> 此问题与开发者无关。请自行参考包管理器/Linux操作系统对应文档。

那使用疑问是问些啥？这个不算使用疑问？

**Comment by dayu521** [comment]
> > 此问题与开发者无关。请自行参考包管理器/Linux操作系统对应文档。
> 
> 那使用疑问是问些啥？这个不算使用疑问？

这个问题一般来说开发者帮不到你。
打个不恰当的比喻，这就类似于你买了件商品使用有问题，应该找卖家，而不能找厂家。
开发者是厂家

**Comment by EpLiar** [comment]
> 那使用疑问是问些啥？这个不算使用疑问？

这是一个应用无关的问题
