### ISSUE TITLE
使用疑问：<使用过程中的两个疑问>

### ISSUE THREAD

**Issue by Renyicai** [Qv2ray/Qv2ray#985]
### 1、为什么没有Trojan类型了？
自从更新了现在的这几个新版本，却发现连接类型没有了Trojan了，现在用Trojan协议的太多太多了，开发者能加进去吗？

### 2、没有代理模式选择，用的提心吊胆的
这个软件为什么没有PAC模式，GFW等等模式选择？用软件自带的数据查看表看，就是打开国内的B站，这个流量都在刷刷刷的涨，真的是用的提心吊胆的。初步揣测这个软件默认就是全局代理且不能更改。开发者能加入由用户自由选择的PAC模式吗？

**Comment by EpLiar** [comment]
1 Trojan 需要安装插件

2 默认绕开中国大陆

3 请详细查看 Qv2ray 的文档

**Comment by DuckSoft** [comment]
默认绕过中国大陆啊，那个流量显示是总流量，不要见的风就是雨。
内核版本足够高的话，在首选项开分出站流量统计，可以清楚看到哪些直连哪些代理。

有些东西，希望你不要过早得出结论。

**Comment by DuckSoft** [comment]
Trojan 插件下载：https://github.com/Qv2ray/QvPlugin-Trojan/releases
关于 PAC：https://qv2ray.net/plugins/v2ray-integration.html
关于分流其实是默认开启的：https://qv2ray.net/getting-started/step5.html#%E8%B0%83%E6%95%B4%E8%B7%AF%E7%94%B1%E6%96%B9%E6%A1%88
