### ISSUE TITLE
linux mint下无法更新订阅连接

### ISSUE THREAD

**Issue by leoxxx** [Qv2ray/Qv2ray#986]
## 简单描述这个 Bug:

无法更新订阅连接

## 如何触发这个 Bug：
在linux mint下添加订阅连接后点击更新显示仅有0项可用。同样的连接在WIN7下正常。订阅连接中的某个连接可以从WIN7中复制出来后再粘贴进去可以正常工作。测试了SSR和V2RAY，普通连接正常。

## 系统信息

版本: Aug 6 2020 15:51:10
编译信息：Qv2ray from manual build
额外编译信息：Qv2ray 2.6.3:5840
```

### 操作系统

- Linux

linux mint 20 xfce

### 安装来源
qv2ray_2.6.3-1stable1_amd64.deb

**Comment by U-v-U** [comment]
建议检查网络问题（这种问题在 log 里面会体现出来）
或者给 Qv2ray 设置一个代理

**Comment by DuckSoft** [comment]
@leoxxx 确认网络环境及设置，大多数情况是由于dns污染导致的。必要时设置首选项中的qv2ray代理以通过代理更新订阅。

**Comment by leoxxx** [comment]
linux在WIN7上的虚拟机里，网络是同一条网络。

**Comment by U-v-U** [comment]
@leoxxx 首选项尝试设置一个 Qv2ray代理？

**Comment by leoxxx** [comment]
> @leoxxx 首选项尝试设置一个 Qv2ray代理？

怎么操作？但为什么同机同一条线路会有这问题？

**Comment by EpLiar** [comment]
> 怎么操作？但为什么同机同一条线路会有这问题？

![image](https://user-images.githubusercontent.com/23559565/94023204-84c58a80-fde8-11ea-8ace-89ac88a18a52.png)

**Comment by leoxxx** [comment]
意思是这个我要开个本地代理后再去更新？
点订阅后出现下面信息。
[COMMON-NETWORK]: Network error: 
[CORE-SUBSCRIPTION]: Found a subscription with less than 5 connections.

普通连接连接后
2020/09/23 22:12:31 [Warning] v2ray.com/core: V2Ray 4.28.2 started
2020/09/23 22:12:31 127.0.0.1:52856 accepted tcp:127.0.0.1:0 [_QV2RAY_API_]
那我是不是端口要设置成和这个一样？

**Comment by DuckSoft** [comment]
勾使用自定义代理，类型选http，端口抄入站设置的http端口，确定保存。
主界面连一个能用的节点，然后去更新订阅。
更新完成之后，记得把 Qv2ray 代理设回不使用。

**Comment by leoxxx** [comment]
我把HTTP关了，我用SOCKS代理。之后能更新订阅了。

**Comment by duapple** [comment]
> 建议检查网络问题（这种问题在 log 里面会体现出来）
> 或者给 Qv2ray 设置一个代理

订阅链接在手机上和windows上都可以，唯独Linux不行。给qv2ray设置代理后，用代理更新代理解决了。
