### ISSUE TITLE
macOS中断开连接并退出qv2ray后浏览器无法正常打开网页

### ISSUE THREAD

**Issue by weilyin** [Qv2ray/Qv2ray#988]
过程：打开qv2ray，连接代理（系统代理），浏览器可正常打开页面
断开代理，退出qv2ray，浏览器显示代理错误不可正常打开任何网页（包括局域网）
可能是macOS本身的机制导致退出qv2ray后系统代理设置没有被正确清除，导致浏览器因为代理错误不能打开网页。
通过重启浏览器可以暂时解决问题。
修改：后来发现重启浏览器未必每次都能解决问题，其他方法还有清除系统所有代理设置和重启

**Comment by EpLiar** [comment]
> 可能是macOS本身的机制导致退出qv2ray后系统代理设置没有被正确清除

无法复现，即使是查看了系统代理也是被清除了

![image](https://user-images.githubusercontent.com/23559565/94107369-e846cb00-fe6f-11ea-81dd-d767c8ba8d83.png)

**Comment by EpLiar** [comment]
![image](https://user-images.githubusercontent.com/23559565/94107601-6acf8a80-fe70-11ea-9c15-9f78cfedca58.png)

为了确保验证的准确性，我暂时禁用了浏览器上的 SwicthyOmega，依旧无法复现。此 issue 将在得出确切复现方法前关闭
