### ISSUE TITLE
libQvPlugin-BuiltinProtocolSupport.so 2.7.0-alpha1 macOS legacy @rpath 异常

### ISSUE THREAD

**Issue by ChioIeong** [Qv2ray/Qv2ray#989]
### 你想做啥？

MacOS 10.13下，安装Qv2ray V2.7.0 alpha1-legacy，只要启动就会弹出这个界面。

![WX20200924-140741](https://user-images.githubusercontent.com/71756622/94107532-41aefa00-fe70-11ea-9e11-014e3f009f1e.png)

**Comment by DuckSoft** [comment]
@ChioIeong 感谢反馈。估计是 Legacy 的打包脚本忘记更新了。等下会调查。

**Comment by DuckSoft** [comment]
我这无法复现了。推测是 macOS 打包的问题。
@U-v-U

**Comment by DuckSoft** [comment]
问题已定位。

**Comment by U-v-U** [comment]
@ChioIeong 问题已经在最新 dev 修复，Release 里面的文件替换过了，可以重新下载试试看

**Comment by ChioIeong** [comment]
@U-v-U 已解决。优秀！

**Comment by U-v-U** [comment]
感谢 @DuckSoft @ymshenyu
