### ISSUE TITLE
新增 RealPing 测试真延迟在哪？

### ISSUE THREAD

**Issue by Passwww** [Qv2ray/Qv2ray#991]
比如一个香港的节点，qv2ray测得延迟15ms，实际上连不通
另一个香港微软云节点，qv2ray测得延迟0ms，实际上速度很快

能不能像v2rayN一样测得准一点？
真连接延迟检测同样两个节点
香港的显示，The operation has timed out
香港微软云显示243ms

**Comment by EpLiar** [comment]
众所周知，延迟不等于速度

**Comment by Passwww** [comment]
> 众所周知，延迟不等于速度

哪里说延迟等于速度？而是一个机场节点很多，动不动几十个节点的时候
你能直观知道哪些连得上，哪些连不上，你自己一个个测？

**Comment by EpLiar** [comment]
节点右键有真延迟测试

**Comment by EpLiar** [comment]
看起来 v2rayN 的用户门槛还是太低了

**Comment by U-v-U** [comment]
@Passwww 那也没事，真延迟你也不能批量测
