### ISSUE TITLE
使用疑问：launch at login, unable to cancel

### ISSUE THREAD

**Issue by SynonZelra** [Qv2ray/Qv2ray#994]
### 你想做啥？
qv2ray UI auto display after login into system, can't cancel.

### 你目前试了啥？
Perferences -> General Settings -> Lauch at Login //not selected
~/.config/autostart/  //no qv2ray related

### 其他要补充的信息？
Manjaro KDE, install qv2ray via pacman -S

**Comment by U-v-U** [comment]
Unless you have an automatic connection, the MainWindow will always show up.

**Comment by DuckSoft** [comment]
Manage this with: https://userbase.kde.org/System_Settings/Autostart
As is mentioned above, it's a feature when you don't choose a node for automatic connection that the MainWindow will turn up.
