### ISSUE TITLE
使用疑问：<anither process is using the port required to start the connection: port:1090 for listening ip:127.0.0.1 for inbound tag:"socks_IN">

### ISSUE THREAD

**Issue by CnSuperYoung** [Qv2ray/Qv2ray#995]
<!--
你好，文档啥的都看了，但是仍然提示
anither process is using the port required to start the connection: port:1090 for listening ip:127.0.0.1 for inbound tag:"socks_IN"
端口换了好几个还是不行

**Comment by CnSuperYoung** [comment]
anither process is using the port required to start the connection: port:1090 for listening ip:127.0.0.1 for inbound tag:"socks_IN"

**Comment by DuckSoft** [comment]
https://qv2ray.net/faq/v2ray-core.html#%E6%97%A0%E6%B3%95%E7%9B%91%E5%90%AC%E5%9C%B0%E5%9D%80

**Comment by CnSuperYoung** [comment]
任务管理器中没有v2ray.exe相关进程

**Comment by DuckSoft** [comment]
读文档。

**Comment by DuckSoft** [comment]
> 任务管理器中没有v2ray.exe相关进程

文档中描述的一共四种情形，你都排查过了吗？

**Comment by DuckSoft** [comment]
人呢？

**Comment by CnSuperYoung** [comment]
在的，刚测试完成，我的win不知道为啥30000之前全被保留或者占用了，用到了30000以后的，回头重装个系统试试，公司电脑，装了太多测试软件，谢谢大佬指点

**Comment by blueveryday** [comment]
> 你好，请仔细读完这一页文档，并跟随文档自行进行相关排查。
> https://qv2ray.net/faq/v2ray-core.html#%E6%97%A0%E6%B3%95%E7%9B%91%E5%90%AC%E5%9C%B0%E5%9D%80

我按照这个说明排查了，重启电脑以后，没有v2ray的进程。
排查netstat -aon | findstr "1089"
显示没有任何程序占用这个1089端口。
开软件还是报错。
我第一次出现这个问题，以为是docker引起的，就卸载了docker，然后就好了。
重启电脑后，问题又出现了，这次不晓得是哪个软件引起的了。

**Comment by DuckSoft** [comment]
> > 你好，请仔细读完这一页文档，并跟随文档自行进行相关排查。
> > https://qv2ray.net/faq/v2ray-core.html#%E6%97%A0%E6%B3%95%E7%9B%91%E5%90%AC%E5%9C%B0%E5%9D%80
> 
> 我按照这个说明排查了，重启电脑以后，没有v2ray的进程。
> 排查netstat -aon | findstr "1089"
> 显示没有任何程序占用这个1089端口。
> 开软件还是报错。
> 我第一次出现这个问题，以为是docker引起的，就卸载了docker，然后就好了。
> 重启电脑后，问题又出现了，这次不晓得是哪个软件引起的了。

@blueveryday 请勿挖坟。另外，请参考这里：

读文档。我个人的猜测是因为你撞上了 Windows 的强制保留端口区段，建议自己结合文档自己排查一下。
https://qv2ray.net/faq/v2ray-core.html#windows-%E7%B3%BB%E7%BB%9F%E4%BF%9D%E7%95%99%E7%AB%AF%E5%8F%A3
