### ISSUE TITLE
你好  请问v2ray怎样在ubuntu使用呢  找不到教程  求助

### ISSUE THREAD

**Issue by henbucuoshanghai** [Qv2ray/Qv2ray#996]
### 你想做啥？
*简要描述你的最原始的目的。*
例：我在学校，校园网能解锁文献数据库，我想对这些地址直连。

### 你目前试了啥？
*简单叙述你为解决这个问题所进行的操作。*
例：看完文档，没有相关内容，就过来问一问。

### 其他要补充的信息？
*在此附加其他需要补充的信息。*

**Comment by DuckSoft** [comment]
你好，我该如何回答你这个问题呢，找不到教程呢。
