### ISSUE TITLE
BUG 反馈：编辑连接设置的标签名称，主界面分组内的连接名称名没有更变

### ISSUE THREAD

**Issue by wonget** [Qv2ray/Qv2ray#997]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
编辑连接设置的标签名称，主界面分组内的连接名称没有更变。

## 如何触发这个 Bug：

1. 运行 Qv2ray
2. 选中分组内一个连接选择编辑
3. 编辑连接设置的标签名并确定
4. 分组内的连接名称并没有随之更改

### 如果是连接问题，在其他 V2Ray 客户端里出现过吗？ 

不是连接问题。

### 相关截图或日志

截图无法直接贴，没有图床

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.7.0-alpha1:5931
编译信息：Qv2ray built from Github Action
额外编译信息：qt5.15.0-661fa725506e358a920699f524b21b5f8bd252fb-ci.windows-latest
```

### 操作系统

- Windows 10 专业版 1909

### 安装来源

- Github Release

### 已安装的插件、版本及安装来源

Qv2ray 项目组维护的 6 个跟随版本同步的插件，安装来源 Github Release

## 附加信息

1. 对分组内的一个连接进行重命名，打开该连接的编辑页面发现标签名称也没变。

2. Qv2ray v2.6.3 同样存在此问题。

**Comment by U-v-U** [comment]
那俩不是一个东西

**Comment by DuckSoft** [comment]
重命名：F2 / 右键——重命名
