### ISSUE TITLE
功能请求：<网速限制>

### ISSUE THREAD

**Issue by cruisermaxx** [Qv2ray/Qv2ray#998]
增加网速控制选项，流速太大反而是一种负担！

**Comment by DuckSoft** [comment]
@cruisermaxx 爱莫能助，代理功能由核心提供，请向核心反馈，谢谢！
https://github.com/v2fly/v2ray-core/issues

**Comment by cruisermaxx** [comment]
回复也太快了吧，核心没有提供API哈。那核心没有界面，用户是修改不了的哈？

**Comment by MarksonHon** [comment]
@cruisermaxx 这个我告诉你啊，Qv2ray只是V2Ray的一个图形前端啊，所以有需要可以去向V2fly提啊，也许有人会帮你实现啊，仅仅是也许啊。
说句题外话啊，限制流量可以找个防火墙软件啊，具体哪款好咱也不知道啊。

**Comment by DuckSoft** [comment]
@cruisermaxx 你可以直接修改核心代码实现： https://github.com/v2fly/v2ray-core

**Comment by cruisermaxx** [comment]
@DuckSoft 喔喔，那就有点东西了，还要自己编译。。而且没有API，不是写死了吗

**Comment by cruisermaxx** [comment]
@MarksonHon 防火墙就算了吧，还嫌*不够高吗

**Comment by studentmain** [comment]
v2ray使用小技巧：通过路由规则，v2ray可以选择性屏蔽某些网站，阻断某些连接

> @MarksonHon 防火墙就算了吧，还嫌*不够高吗
