### ISSUE TITLE
vmess link parse failed

### ISSUE THREAD

**Issue by idnsunset** [Qv2ray/Qv2ray#999]
- [ x] **I'm sure I've tried to reproduce the problem several times and will provide the system environment, each software and its version that is involved in the problem.**

## Briefly describe this bug：

Please take this vmess link: `vmess://YXV0bzo0ZDUzOWViYS1mZTQzLTExZWEtOTMzNC01NjAwMDJmYmFiYmVAYXBwbGVtdXNpY3MudGs6NDQz?remarks=%E5%96%84%E6%AC%BE8%E9%9F%A9%E5%9B%BD%20%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0%EF%BC%9A%E7%94%B5%E6%8A%A5%E9%A2%91%E9%81%93%EF%BC%9Ahttps://t.me/cnhumanright99&obfsParam=applemusics.tk&path=/HGUguBY9/&obfs=websocket&tls=1`

Illegal value is reported, however, V2rayN on my phone imported it successfully.

**Comment by U-v-U** [comment]
This is Shadowrocket format.
Qv2ray doesn't support it currently.

**Comment by wajika** [comment]
Why not compatible?

**Comment by U-v-U** [comment]
@wajika Go and check yourself.
